### ISSUE TITLE
Enh: Improve random effects to select from presets.

### ISSUE THREAD

**Issue by stevegiron** [xLightsSequencer/xLights#1026]
I've added these preset categories this year to my configuration. They greatly assist in quickly sequencing.

![image](https://user-images.githubusercontent.com/10568498/34010399-6dec1186-e0c1-11e7-8747-1324f3dd1880.png)

If a new feature "create random from presets" was enabled, I'd see it listing the preset groups with a checkbox for those to be included.  OR If a group called RANDOM was there, anything in the random group would be fair game.

**Comment by keithsw1111** [comment]
This would be really confusing for users to use. Random number of layers required, extra UI complexity to include/exclude effects ... I am sorry but I just cant see how it would end up as anything but a really confusing and rarely if ever used feature.
