### ISSUE TITLE
Spiral tree mapping screwed up. 

### ISSUE THREAD

**Issue by jjewell66** [xLightsSequencer/xLights#1036]
Hi, every effect I try on my spiral tree just spirals. Snow doesn’t fall vertically. It spirals. I’ve tried many different settings in setup and rendering styles. Screen preview matches physical leds. Even screen preview doesn’t show falling snow. 
Tree is just one string of 95 leds wrapped 8 times around a cone. 9” diameter. 16” tall. Starts bottom right. Counterclockwise spiral when looking from the top.  I’ve been thru the FB page, manual, forum.  Thank you!

**Comment by AzGilrock** [comment]
Yeah its nothing to do with spirals.  Per Preview should be the render style that would work but it doesn't seem to work for the Snowflake effect even on a normal 12x50 flat ribbon tree with that style.

**Comment by DLBeckwith** [comment]
I have the same issue with my spiral tree. If there isn't a fix, is there a workaround?

**Comment by skulltronix** [comment]
I’ve been playing with different ideas to model my tree. Mostly centering around drawing out a Mercator style projection using excel.  Similar to what was done for the ny led ball.

**Comment by skulltronix** [comment]
I did not have trouble mapping my horizontally banded tree using the Mercator method. Maybe I should just ignore the angles and treat the spiral ball like a horizontally banded ball and see what it looks like. Downside: on screen previews don’t look like trees.

**Comment by AzGilrock** [comment]
This shows the per preview problem I mentioned.  Both trees have the same snowflake effect.  Left side is Default render style....right side is Per Preview render style.  I had to put a grey effect underneath so you could see it's actually a tree model there.

![snowflakes](https://user-images.githubusercontent.com/2024669/34322835-c5d77e3c-e7ef-11e7-9341-c1ed591ec408.gif)

**Comment by keithsw1111** [comment]
The problem ... if there is any ... is that the per preview model ends up quite sparse ... and as such the result is probably what is expected ... unless we can shrink the model back down.

**Comment by AzGilrock** [comment]
I think the problem is when you create a group you have the option of a Minimal Grid Per Preview or a total screen Per Preview. When you use Per Preview render style on a regular model I'm not sure what you get but there doesn't seem to be a minimal grid type option.

But the other weird thing I'm seeing is if I do this exact same test on a custom model like my CoroAngel from Boscoyo the result is completely opposite.  The Per Preview looks like its working and Default looks sparse and terrible.
