### ISSUE TITLE
OSX Preview windows

### ISSUE THREAD

**Issue by bacarudaguy** [xLightsSequencer/xLights#1176]
Using OSX 10.12.4 and XL 2018.16 (I know, a couple versions behind) and noticing that the main house preview window will stay assigned to a secondary monitor at all times, however, any additional preview windows (ie - for other houses, locations, etc) will jump back to the main window when performing certain tasks...

-Rendering the sequence and clicking on the progress bar
-Add/renaming a timing track

I know I've had a few other tasks cause this but these two were driving me nuts this evening...

Thanks!

**Comment by bacarudaguy** [comment]
New Task causing the window to move - saving an effect preset.

**Comment by AzGilrock** [comment]
Most of the panels are part of the perspective but not any additional preview windows you create.  I coded them up so that they should return to their last position so not sure why that keeps getting changed on MAC.  I'm storing those preview positions in the xlights_rgbeffects.xml file so you should be able to save a copy of it and then see if you see the values being changed in that file.

**Comment by AzGilrock** [comment]
So when you reposition the windows I update the XML value in the program but they are not written to disk yet until you hit Save on the Layout panel or you choose to save when you exit the program and it asks about saving model, perspective, and other stuff.   I would position the windows and then hit Save on the Layout panel and then see if anything can cause them to move.

**Comment by zcloutier** [comment]
I came across the same issue about a year ago it still does it but what I did to stop it is in System Presences go to Mission Control and uncheck displays have separate spaces then they won’t move but if that is checked they move.

**Comment by AzGilrock** [comment]
We might be switching from wxWidgets to Qt later in the year and that is when I would probably try to tackle including these preview windows as part of the perspective so multiple layouts could be saved.

**Comment by cybercop23** [comment]
Can this be closed?
