### ISSUE TITLE
presets sorting and importing

### ISSUE THREAD

**Issue by hattitude** [xLightsSequencer/xLights#1213]
It would be nice to able to sort the presets alphabetically.

Also, if there is a way to not let you duplicate a preset? Right now you can import the same preset multiple times, so you get duplicates. If it could recognize that there is one with the same name already, and give you the choice of skipping or replacing?

Thanks and great job to all the developers!

**Comment by keithsw1111** [comment]
A duplicate name does not necessarily make a preset a duplicate. Any such feature would need to look at all the preset properties to decide that. And then should it look across all preset folders or just in the current one ... this is more complex to make useable than it first appears.

**Comment by keithsw1111** [comment]
But overall I agree the presets dialog needs an overhaul ... its useability is not great.

**Comment by AzGilrock** [comment]
What's there is the overhaul....quit insulting my dialog...lol.

**Comment by cybercop23** [comment]
New feature added to the next version that allows moving presets up/down/top/bottom and also sort and sort within a group.
