### ISSUE TITLE
Mac OS, Layout tab columns resizing themselves

### ISSUE THREAD

**Issue by leelindquist** [xLightsSequencer/xLights#1266]
Mac OS 10.12.6 (16G29) Minor issue, but annoying. Resizing the Model / Group column on the layout tab does not persist through updating the name of a model. When the name change is saved or when the text selection focus is changed (by hitting tab key or clicking something else) the Model / Group column is automatically resized back to its small / default width. Noticed in .34 and updated to .35 to check if it had been fixed.

Screen capture video (quicktime movie file) attached.

[column resizing.zip](https://github.com/smeighan/xLights/files/2457249/column.resizing.zip)

**Comment by derwin12** [comment]
Appears to have been addressed.
