### ISSUE TITLE
Opening a sequence mapping 

### ISSUE THREAD

**Issue by robbaldwin12** [xLightsSequencer/xLights#1274]
When opening a sequence and models are not correct

The pop up box asking if you want to delete, remap, or rename goes fine... all models are listed in the drop down for rename

the issue arises after going through this any that you have chose to remap now poplulate the mapping popup however on the left side only the models you have chosen to rename show up here instead of all the models. 

I posted a post on facebook with a video of what im referring too
https://www.facebook.com/groups/xLights/permalink/1950653598303719/

**Comment by derwin12** [comment]
Can this be closed .. it should have been done via an import not an open sequence.

**Comment by AzGilrock** [comment]
Someone needs to test if its still a problem.  If you delete a model from your layout and then open a sequence that contained that model this dialog pops up.  You should not be expected to have to do an import to open your existing sequences.

**Comment by derwin12** [comment]
When using the same show folder it works as expected .. it shows all the common elements on the left hand side. Problem from the OP was he pulled a sequence from a totally different show folder and it only shows the common props in the mapping page.
It does not rebuild the master view unless he were to use the import effects option.
