### ISSUE TITLE
xSchedule Web UI Feature Request

### ISSUE THREAD

**Issue by zcloutier** [xLightsSequencer/xLights#1284]
Is there any way that the Web UI could allow you to create and edit playlists as well as create and edit schedules? I'm not looking at having it so you could upload sequences but if it could search your show directory and give you a list of sequences to add to a playlist. To go along with that if it could create and edit schedules that would make the web UI more convenient to use as the computer I use doesn’t have a monitor attached to it so being able to create and modify playlists and schedules would be a lot easier than having to remote in and create playlists and schedules.

**Comment by keithsw1111** [comment]
I really don’t ever see this happening. You may be better off using fpp.
