### ISSUE TITLE
Sequence Download Search Enhancement

### ISSUE THREAD

**Issue by deplanche** [xLightsSequencer/xLights#1329]
Was talking to someone in the Zoom room (I can't remember their name offhand right now), and they brought up a good suggestion.  In the download sequences/lyrics, it would be useful if there was a way to search by the "creator" name in addition to the artist/song title.  Use case would be that if you find a shared sequence that you like and create a mapping file, it would be useful to see what other sequences that person uploaded so that you could use your mapping file for those too.

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.
