### ISSUE TITLE
Changing Start Channels On Single String Models Adds Artifacts to Sequence

### ISSUE THREAD

**Issue by mikegntn** [xLightsSequencer/xLights#1339]
The first universe of my setup is 192 channels, and is used for multiple AC single line props, such as 4 string minitrees and 8 string arches. I'm feeding these props via a E1.31 bridge.  In the past I sent all channels for the minitrees and arches out one port of the bridge to a digi radio for wireless communication.  This year, I decided to hardwire the AC controllers and send the data for half of the minitrees and arches out one port, and the data for the second half of the minitrees and arches out a second port.  To do this, I had to change the start channels for half of the minitrees and arches.  When I did this, xlights introduced artifacts into the sequencing for the minitrees.  If I change the start channels back, the artifacts disappear.  I am on version 2018.40.

**Comment by keithsw1111** [comment]
Does it still occur in .47?

**Comment by mikegntn** [comment]
I don't know. I'll load .47 tomorrow and find out. 

Thank you.

    On Thursday, November 22, 2018, 9:44:05 PM CST, Keith Westley <notifications@github.com> wrote:  
 
 
Does it still occur in .47?

**Comment by mikegntn** [comment]
Just loaded .47, and it occurs in it as well. 

Let me know if I need to send you any files.
Thanks!

    On Thursday, November 22, 2018, 9:44:05 PM CST, Keith Westley <notifications@github.com> wrote:  
 
 
Does it still occur in .47?

**Comment by keithsw1111** [comment]
Can you upload a simple packaged sequence showing the issue.

**Comment by mikegntn** [comment]
Sorry it's taken so long to get back to you.  Had other issues with the lights.  Uploading two versions of the same sequence - original version, and modified version.  Only thing I changed in the modified version was the starting channel #'s for Arch 1,2,3, minitrees 4,5,6, minitree stars 4,5,6. 
[Linus and Lucy_original.zip](https://github.com/smeighan/xLights/files/2647249/Linus.and.Lucy_original.zip)
[Linus and Lucy_modified.zip](https://github.com/smeighan/xLights/files/2647250/Linus.and.Lucy_modified.zip)
