### ISSUE TITLE
Vocal synch with faces in xScheduler

### ISSUE THREAD

**Issue by JoelDearing** [xLightsSequencer/xLights#1346]
To: Keith
Fr: Joel
Re: Vocal synch in faces.

Hi Keith,
We touched on this on the 24th, you said to upgrade to 47.  I did.  I still get the synch issue in xScheduler.  

I tried to attached two :20 video samples but Github wanted something smaller than 10mb.
Look for an e-mail from  wetransfer.com linked to my AOL address.  It contains two zip files that are the videos.   

Look for the bad synch in the xScheduler video around the lyric  "voices sing and let's be jolly"

Let me know if you need anything else.

Best,

Joel

**Comment by keithsw1111** [comment]
can you post the xSchedule logs ... maybe after .48 comes out and you try it one more time. (not because I think it is fixed but because i have removed some noise from the logs)

**Comment by JoelDearing** [comment]
[Dearing 112718 xSchedule_l4cpp.txt](https://github.com/smeighan/xLights/files/2622673/Dearing.112718.xSchedule_l4cpp.txt)

Hope you can use this.  The log is just a lot of this:
2018-11-27 21:55:45,129 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 164
2018-11-27 21:55:45,282 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 153
2018-11-27 21:55:45,435 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 153
2018-11-27 21:55:45,588 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 153
2018-11-27 21:55:45,740 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 152
2018-11-27 21:55:45,891 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 151
2018-11-27 21:55:46,048 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 157
2018-11-27 21:55:46,199 2020 log_base [WARN] Frame interval greater than 200% of what it should have been [50] 151

**Comment by keithsw1111** [comment]
That is the worst delays I have seen. Something on your machine is massively slowing things down. Everyone I have troubleshot has had either a network issue/conflict or something interfering.

Look for things like:
- virus scanners
- dropbox etc
- anything using lots cpu or network
- slow storage

**Comment by JoelDearing** [comment]
My show computer is a 64 bit, quad core 4 gig of ram, with an SSD 
I have taken it off the home network to run the Christmas show, I disconnected from wifi, shut down drop box, turned off Avast virus scan, so it should only be doing is the operating system and xScheduler.

Looking in Task Manager, xScheduler is the only application running (and task manager) and looking, in the processes tab it is the biggest user of memory at over 3 gig at this moment, 10:30 AM et while running library music.  
I run 7 sequences for show mode, and do not fast start them
I also run a library list of ~1200 titles, but again none of those are loaded until needed.  
Today task manager showed memory used at over 3 gig, I stopped and closed xScheduler and memory use dropped to 512 MB.  Reloaded xScheduler and  memory use was at 784 MB.  I'll check it later in the day.  Could xScheduler have a memory leak?

**Comment by JoelDearing** [comment]
Two hours later after running just library music from about 11a-1p, now the Task Manager says memory used is at 1.67 gig.  I'll update again before the show starts.

**Comment by keithsw1111** [comment]
Can you attach your xschedule file ... I would like to see if you are doing anything unusual that might explain why i dont see it.

**Comment by nmiller0113** [comment]
This is an interesting one.  I was considering doing the same thing, so I'm curious what the outcome is on this one.

**Comment by JoelDearing** [comment]
I'll send it via we transfer.  
fyi at 11a task mgr showed 1.67 gig in use
all day it just ran the library files
show starts at 5:30
5:26p 2.16 gig
library music stops
5:29p 2.42
5:30 show starts
5:31 2.43 gig
show runs 40 minutes
6:10p  2.48 gig
Exited xScheduler
drops to 575 mb
reload program  restart show
up to 948 mb
6:19p  1.48 gig

**Comment by JoelDearing** [comment]
tracking more memory usage
6:30 p 1.00 g
7:30 1.56 g
7:50 playlist stopped at the end and did not loop
7:52 restart
this happened the rest of the night.  the list would plays, but would not loop.
the list is the B list, and it worked OK last week, but that was with ver 2018.36
10:09p 1.23   back to the library
log files at the 7:50 stop and 7:52 restart, and log file again at change from show  back to library
finally 10:16 p 1.72 gig
Let me know what else you may need
[dearing xschedler log 112818 751p.txt](https://github.com/smeighan/xLights/files/2627454/dearing.xschedler.log.112818.751p.txt)
[dearing xSchedule_l4cpp log wed 112818 107p.txt](https://github.com/smeighan/xLights/files/2627455/dearing.xSchedule_l4cpp.log.wed.112818.107p.txt)

**Comment by keithsw1111** [comment]
Tell me about your controllers ... are they all e131? Or do you have some serial or lor and if so what are they?

**Comment by JoelDearing** [comment]
I have a San Devises E682 @ 192.168.1.206 driving < 1000 pixels and a 6804 @ 192.168.1.207 driving > 700 pixels, both on  E131.  I have two LOR boxes.  They are a Gen 3 LOR box that I borrowed  (my Gen 2 box is having issues) that feeds the Gen 1 box.  I use the LOR dongle on COM3.     fyi: After the show I closed out xScheduler, and restarted with the library music, it was just under a gig of memory in task manager, This morning TM was showing 3.42 of memory in use.

**Comment by keithsw1111** [comment]
I would like to see results without all your WAV files. I tested last night using MP3s and i dont see any memory leaks.
Also see my facebook post re xSchedule pauses ... you may want to run through that list.

**Comment by JoelDearing** [comment]
OK, I have removed all the .wav files, I'll let you know.   
Re: items in your FB post

 Reading the FSEQ file from disk  
It has always been that way

- Make sure nothing else is likely to be accessing the files 
Dropbox is closed, the e131 are on a static IP

- Make sure your virus scanner is not slowing down access ... consider turning it off and testing without it
Virus is turned off.

- If you have multiple active network connections try disabling the one not used by your show
Wireless turned off except when to send you stuff.
- If you are internet connected ... try disconnecting to the network
No connected
- If you are running multicast to wired controllers try making them unicast
Running all unicast, been that way for years
- If you are using serial devices try disabling those outputs.
I need COM3 for LOR.  99% of the blinky flashy works as it should.  The only issue is the lip synch of the singing face.  

General load
- Check memory utilisation Looked at the list xScheduler is using the most at over 2 gig.  Note have not restarted since removing the .wav files.

Periodic Processes - 1 minute
- If you have more than 2-3 schedules consider disabling most of them.
If I disable them, could I re-enable them when needed?  I usually schedule the week on Sunday, so the weekend schedules are sitting there for several days before being called on.
As you saw in the file I have four M-F playlists and then weekend versions of the M-F playlist.  Four into seven days give a good even distribution having each playlist rotate through the week without horizontal rotation issues.  Each playlist has an bit in seq1 that is a little different, otherwise they are the same.

**Comment by keithsw1111** [comment]
I am not suggesting you make permanent changes ... as you make changes something at some stage is going to fix the problem ... at that point you start to turn things back on until it either slows down again or you have everything working.

Something puzzling in your last response. Are you saying only the singing faces glitch ... everything else is in time? What are these singing faces on? Does it need to receive data over the network? Maybe we are focussing on the wrong thing.

**Comment by JoelDearing** [comment]
The singing face is on a virtual matrix through an HDMI cable into a projector.   No data over the network.  Other effects on the virtual matrix are ok.  There is one other effect in a different sequence that isn't as snappy as I'd like.  That could be my error.

**Comment by JoelDearing** [comment]
I saw your FB post, and recapped it as to what I am doing in a post further back.  Did not see a FB message to me.
The virtual matrix is on xSchedule, and in the  xLights setup it is a Null output.  It does have 20100 channels.  Too many?  I went for a dense look since it was all virtual.  If that is too many what is the max?

**Comment by JoelDearing** [comment]
OK, now that I found your message  (FB didn't alert me)  and now that I know I can make a call via FB  do you want to set up a time?

**Comment by keithsw1111** [comment]
That sounds right ... packets/sec should be roughly number of output universes * frames per second ... it will vary slightly but not a lot.

**Comment by keithsw1111** [comment]
Lets keep the memory usage and performance issues apart ... they are not likely related unless memory usage exceeds the memory in the machine.

Was the log file when using one of the more efficient quality selections.

**Comment by JoelDearing** [comment]
If I understand this correctly:
<<Was the log file when using one of the more efficient quality selections.>>

That log was generated using the old exe and map and then restated with the new exe and .map.  You can see the jump in time here from 14:06 to 14:15

2018-12-02 14:06:18,392 3832 log_base [DEBUG] Result ''
2018-12-02 14:06:18,393 3832 log_base [DEBUG] SDL uninitialised
2018-12-02 14:15:01,011 1900 log_base [INFO] ******* OnInit: xSchedule started.
2018-12-02 14:15:01,011 1900 log_base [INFO] Version: 2018.50
2018-12-02 14:15:01,011 1900 log_base [INFO] Bits: 64bit

**Comment by AzGilrock** [comment]
This is way outdated and unlikely for anything here to be useful for troubleshooting.  If this is still an issue then open a new issue ticket and reference this one.
