### ISSUE TITLE
Two Mac issues

### ISSUE THREAD

**Issue by reelpilot** [xLightsSequencer/xLights#1351]
Pressing esc while rendering to stop the process isn't working on Mac. Also in the settings I have the default model blending set to off, but every new sequence still has model blending enabled by default.

**Comment by AzGilrock** [comment]
I don't think ESC is working on Windows either.  I needed to bail out of a render last night and had to kill xLights in Task Manager.

**Comment by reelpilot** [comment]
I didn't know that one needed to click on the grid first before hitting esc. Thanks Dan, it's working fine when I do that.

**Comment by AzGilrock** [comment]
Yeah I know to try clicking on the grid that doesn't help.  I'm in the 3D branch but I thought that code was much older.
