### ISSUE TITLE
Enhancement request: xScheduler background sequence priority

### ISSUE THREAD

**Issue by jspiker77** [xLightsSequencer/xLights#1354]
In the blend mode would it be possible to have another option that allows for you to set the background sequence at a lower priority than the main sequence and in the event the main sequence is sending data to any channel defined within the channels in the background black out the background sequence and play what is in the main sequence that has a higher priority?

**Comment by keithsw1111** [comment]
FPP set the trend with Background sequences overwriting main sequences. You can do this by sequencing two fseqs in a step ... but its not quite the same as it would restart in each step.

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by jspiker77** [comment]
Yes
