### ISSUE TITLE
Enhancecment request:   option to include Export House Preview during Bulk Render

### ISSUE THREAD

**Issue by MarkAAmber** [xLightsSequencer/xLights#1356]
Within the Batch Render tool.  I would like to have the option (checkbox possibly?) of exporting the house preview video when each sequence is batch rendered.

Alternatively, maybe a separate Batch Preview Export tool that works similar to Batch Render but does a Batch preview video export.

The export video feature already exists and works fine but can currently only be done one-by-one.  This request is simply to include that option during Batch Render or be able to do it some similar batch way.

If a batch method is not possible, another alternative may be to offer a Setting called "Export Preview Video on Save" that would work similar to the "Render on Save" setting.

**Comment by cybercop23** [comment]
This can now be done with the Lua scripts buit in. Please take a look and close this issue if that meets the requirements.
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/968ed8ef-ad7c-4d1e-bb0f-78c53e2d6273)
