### ISSUE TITLE
Implement the "Create Random Effects" process

### ISSUE THREAD

**Issue by smeighan** [xLightsSequencer/xLights#142]
In XL 4.0 the "Create Random Effects" is going to be more extensive.

I believe this would be the goal of this new Wizard

1) Prompt a window of all Effects. Gray out the effects that require user imput.
The effects that will be grayed out (or not shown at all) therefore are
CoroFaces,Faces,Glediator,Piano,Pictures,Text
The remaining effects will be shown in a window,
2) Allow users to click multiple effects or have a select all
3) Prompt for which timing track to use (if there are more than one). This is probably a list, only one selection allowed.
4) Allow a list of all models in sequence, users can select all or click to select which models they want to create random effects on
5) We need to implement the right click protect on each effect. After that has been done. We skip any effects that are protected.

Now the actual generation of effects
loop through each layer on selected model
{
   loop through the timing marks
   {
      if current effect is not protected or is empty then
              randomly pick from the selected effects
   }
}

**Comment by stevegiron** [comment]
Almost there. Just need to the "protect" to return.
