### ISSUE TITLE
2019.5 Mac - default sequence directory

### ISSUE THREAD

**Issue by jarogers** [xLightsSequencer/xLights#1424]
When creating a show that is setup to have a different sequence directory than the show directory, I would expect that the default location when creating, opening or saving a sequence would be the 'overridden' sequence directory as setup in the Setup > Subfolders... modal window.  However the default location for each operation is still the show directory.

**Comment by keithsw1111** [comment]
That is the fseq folder ... not the sequence folder. I believe it is doing the right thing.

**Comment by AzGilrock** [comment]
I'm pretty sure those file dialogs usually default to the last place it was the last time you opened a file dialog in the program.  Pretty sure I've seen it open up in my audio directory to open a sequence because I had navigated to there inside the settings dialog to change the audio file.  In general I don't think we've ever tried to force the location of any open or save dialogs in the program.

**Comment by jarogers** [comment]
@keithsw1111 so the idea is that you from the Setup > Subfolders modal you can select where to store the FSEQ only?  and the .xml goes somewhere else?

How would you go about selecting where to store the .xml sequence file then?  since when creating a new sequence the 'file location' is presented as a label on the form and un-editable.  And this location is the show directory.

**Comment by jarogers** [comment]
@AzGilrock I see that when I create a new sequence and select 'Musical Sequence' it opens the 'Media' directory as defined in the Setup > Subfolders.  But then the resulting 'Filename' on the Info/Media tab of the Sequence Settings modal shows the Show directory.  And then when saving the sequence the default location is the Show Directory again.

Also when Opening a sequence the default location is the Show directory.

**Comment by AzGilrock** [comment]
A sequence file is not really created until you save it....so use Save As.

**Comment by dkulp** [comment]
Under almost all circumstances, the xml should go into the show folder or a subdirectory of the show folder.   When creating a new sequence, it won't prompt for a location until you actually go to save the sequence.   There isn't a file location until it's been asked to be saved.

**Comment by AzGilrock** [comment]
My current practice is I keep each sequence in its own folder under the Show directory.  So when I create the sequence for my first Save I create the sub-folder and then save it there.  From then on it will just use that folder to save the sequence and you don't have to worry about it.  So every sequence I open comes from a different folder so having a common location whether be the show folder or somewhere else is not something I would use.

**Comment by AzGilrock** [comment]
To be honest I wrote that Info/Media tab code so many years ago I'm not sure its even correct.

**Comment by jarogers** [comment]
@AzGilrock fair enough.  And I agree with the idea of separate directories for sequence files, which is sort of what brought me to all of this.

The Show setup subfolders does indeed say 'FSEQ location' but then also makes reference to the 'sequence location' which you can override - however in the case that you are creating a new show and new sequence, the sequence location doesn't even exist yet, as you haven't saved a sequence.  Sort of chicken an egg, I suppose.

Perhaps when saving a new sequence it ought to create a directory with the sequence name in the show directory (by default), and then create the xml sequence inside that?

**Comment by jarogers** [comment]
on further thought, perhaps when creating the show directory for the first time, there should be a 'sequences' directory also created inside the show directory.  This would be the default sequence location, then upon saving a sequence for the first time, it would then create a directory under ../show/sequences/ with the name of the sequence ie ../show/sequences/jingle bells/, where then the sequence would be saved.  next sequence would also use the ../show/sequences/ directory as default, and when saving that sequence would create another directory under sequences ie. ../show/sequences/drummer boy/ . etc.

This way the there wouldn't be a chicken and egg problem with the sequence directory not existing when the show is created.

**Comment by AzGilrock** [comment]
I don't think the way it currently operates bothers me enough to change it.  Maybe one of the other developers will bite.  There is a whole complex search operation that goes on to find associated FSEQ or XML files depending on which one you open and it's a pain trying to keep that code operational every time you change the directory scheme of the program.

**Comment by computergeek1507** [comment]
The "FSEQ Directory" allows you to save the FSEQ files (not the XML Sequence) to a separate location. The FSEQ files can be rather large so this makes it possible to save the FSEQ to a separate folder outside the show folder and not have them backed up to Dropbox or Google Drive. The "Use sequence location" checkbox will place the FSEQ file in the same folder location as the Sequence XML when you save it.

**Comment by AzGilrock** [comment]
Closing obsolete issues
