### ISSUE TITLE
Multi-monitor: if Display scale is not set same on all displays, Balloon tips & drop downs will not display correctly

### ISSUE THREAD

**Issue by pkimbell** [xLightsSequencer/xLights#1447]
If you are using multiple monitors in a Windows environment, you can set the "Scale and layout" differently for each display under the Windows display settings - 100%, 125%, 150%, etc.  If this setting is not set the same for all displays, the balloon tips for the icons, as well as the drop down menus, will not display correctly.  I have two monitors and I have the primary set to 100% and my second display is set to 125%.  With this configuration, the balloon tips will display low and to the far left of the icon you have your mouse over (if I hover over Zoom In, the tip is in-line with the view menu and about the height of 4 icons low).  Once I set this setting the same for all my monitors, 100% or 125%, the tips work correctly.  Same situation with the drop down options.  Running xLights 2019.9 with a Windows 10 system with build 1703.  I have tested this on 3 other computer systems (all previous builds of xLights) and the same result.

**Comment by dkulp** [comment]
This is a wxWidgets restriction.  It only uses a single scale factor.   Really not much we can do about it until wxWidgets gets everything fixed.   There is a wxWidgets PR that is supposed to start addressing some of it  ( https://github.com/wxWidgets/wxWidgets/pull/334 ), but that's been open for 2 years.   Bunch of activity on it lately so it may be merged sometime soonish.  No idea.
