### ISSUE TITLE
Picture- Effects Assist Screen not Scaling

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#1465]
Working on my laptop (1080), When trying to edit an image, I must use the scroll bar on the screen to move from left to right.  The window used to scale down to fit the screen, and I believe that is broken.  I do use this in a full size monitor on my desktop so it's not an issue but using on the laptop is a bit harder.

![image](https://user-images.githubusercontent.com/12719816/52584607-7b98cd00-2e00-11e9-8e7e-73338bf6ef92.png)

**Comment by AzGilrock** [comment]
You mean the entire window or the grid area?  The entire window never scaled from what I remember because I remember running it on a laptop thinking the color picker was really big because it's hard-coded to 256x256 to provide all colors.

**Comment by Clyde-L** [comment]
I was under the impression the matrix would downscale as it does for the morph effect.  This is a rather large matrix... I don't have the issue so much when using on a mega tree.

**Comment by AzGilrock** [comment]
And those icons like the pencil and eraser are not scalable.

**Comment by AzGilrock** [comment]
Ok so the grid area.  Yeah I thought they both worked the same but if it scales down too much it would disappear like for 400x400 model groups.

**Comment by Clyde-L** [comment]
sorry should have been more specific.  The left art panel is fine.

**Comment by AzGilrock** [comment]
So the left art panel on the right side? :)

**Comment by Clyde-L** [comment]
UGH :)  Left art panel is perfect :)  Scaling on the matrix is a 👎  s

I'm also looking for that color pallet save thing ;) haha

**Comment by AzGilrock** [comment]
I guess I don't know what you mean by "left art panel".  For the picture assist there is the grid where you draw on the left and the color picker on the right.

**Comment by Clyde-L** [comment]
I screwed up... the right art panel is fine DOH

**Comment by cybercop23** [comment]
Ahhh... who's on the left and what's on the right? :)
Can this be closed? Sorry.. can't follow it.
