### ISSUE TITLE
Enhancement: Render cache preference saved with sequence xml 

### ISSUE THREAD

**Issue by reelpilot** [xLightsSequencer/xLights#1565]
It appears that xlights remembers the previous sessions selection of render cache (enable, locked effects and disable) when opening up a new instance. It would be useful to have this preference attached to the specific xml for a sequence. That way the preference for render cache can be customized for a specific sequence. 

I always have render cache enabled within my main sequences. However for other sequences, such as those that I downloaded, I want them disabled since I'm only working with them in a limited capacity and I don't want to tie up hard drive space. While I try and remember to always change my preference with each open version of xlights, sometimes I forget and get unwanted results. Having the preference saved with each sequence would be very helpful.

**Comment by keithsw1111** [comment]
I am not so sure this is a good idea as it means any sequence you open from a vendor who has it turned on will impact your environment.

**Comment by reelpilot** [comment]
Good point. That's kind of the problem I'm dealing with now having it enabled automatically when I don't want it. What if instead the preference was based on the show directory folder? That way the user sets what the sequences in a particular directory do. This allows some flexibility to assign different preferences depending on which directory one is working with and it remains off by default until the user changes the preference for a particular directory.

**Comment by keithsw1111** [comment]
But that doesn't address the problem as the show folder comes from the vendor as well ... and when you import a sequence show folder is 1:1 with sequences.

**Comment by reelpilot** [comment]
You're right. I guess there really isn't a way to implement without potentially negatively impacting more users. The only other thought that comes to mind would be if the preference was stripped away to a default setting when the sequence is packaged. That way the user sets the preference, but when shared it defaults to disabled. I'm sure that's way too complicated to implement however.
