### ISSUE TITLE
3D Layout default based per Show folder (not globally in xLights)

### ISSUE THREAD

**Issue by tomhammond** [xLightsSequencer/xLights#1677]
I have a suggestion.  The 3D mode checkbox status seems to be saved in the registry, so it affects each instance of xLights.  If I have two xLights open (one for my 2D show folder and another for a 3D show folder), the current 3D / non 3D mode is applied to both at startup.  Manually correcting the mode after starting each instance works OK.  

It would be better to save the 3D mode checkbox status in the show folder, as different shows may use 2D or 3D modes.  This would help people with transitioning from 2D to 3D, too.  And help when my show is 3D but I am working with a sequence that I purchased that was made in 2D.

That way, when xLights opens a show folder, it sets 2D/3D layout as the show was intended.

Just an idea to simplify the use of 2D/3D.

Thanks!
Tom Hammond
tominohio@gmail.com

**Comment by AzGilrock** [comment]
All models are stored as 3D positioning now so its just a click of a checkbox to switch back and forth and won't hurt anything so I don't see value in changing where this is stored at this point.
