### ISSUE TITLE
Getting "Failed to open phenome dictionary" with AppImage 2019.48 and up

### ISSUE THREAD

**Issue by m00dawg** [xLightsSequencer/xLights#1707]
**Describe the bug**
I think the problem is the word dictionary (for lyrics) may not exist in the AppImage package or xLights can't seem to find where it is. When I right-click and go to Breakdown Word in my lyric track, I get a series of pop-ups:
"Failed to open Phoneme dictionary!" 3 times followed by "Failed to open Phoneme Mapping file!"

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a lyric timing track
2. Import some lyrics, or create some with shift-double-click
3. Right click and go to Breakdown Phrase
4. Right click and go to Breakdown Words

**Expected behavior**
It breaks down the word into the associated phonemes 

**Screenshots**

![Screenshot from 2019-09-12 13-24-02](https://user-images.githubusercontent.com/226504/64810250-a3037400-d560-11e9-81c2-db16bf38d817.png)

**Versions (please complete the following information):**
 - OS: Linux Mint 18.2 (Based on Ubuntu 16.04)
 - xLights 2018.48 (Appimage)

**Additional context**
Trying to build from source right now to see if the base build has the same issue (to confirm if it's an AppImage issue or not). I had some problems with it last time (hence why I switched to Appimage which, for the most part, does work out much better - kudos for releasing these!)

**Comment by tgodfrey73** [comment]
We're you able to resolve this by building from the source? It appears that xLights-2019.40.glibc2.17-x86_64.AppImage was the last build that the dictionary loaded correctly. Every appImage I've tried after fails to load the dictionary.

**Comment by m00dawg** [comment]
Yep building from source solved it for me which is what I've been using since (since I was able to get it to build after moving to Ubuntu 18.04)
