### ISSUE TITLE
Enhancement: Mass Select Elements from Model/Group List

### ISSUE THREAD

**Issue by TimRoenicke** [xLightsSequencer/xLights#1731]
Being able to SHIFT+CLICK or CTRL+CLICK in the Layout Tabs Model/Group window with "Right Click" bulk edit functionality would speed up workflows where i have, lets say, 70 RBL models or 150 peace stakes strune through the yard among many other props. Quickly order sort the pane and shift click them all. 

It may also assist with changing props to a different port on a control. Instead of trying to remember which elements are on the port from the preview screen you could simply order sort by Controller Connection, shift click them all, right click and could bulk edit them to a different controller / port. 

Obviously this is 100% quality of life. The functionality does exist elsewhere. However, I think if the feature is an easy enough one to implement it may warrant a redundant, but I think slightly easier, workflow. I'm using 3D mainly now. 

Just a thought. Thanks for looking at it.

**Comment by keithsw1111** [comment]
You can ctrl click on the layout ... just not in the list ... there are reasons for this ... basically it is not always valid to select multiple items in the list ... but it is always valid to select multiple on the panel.
