### ISSUE TITLE
PROP COLOR ISSUE

### ISSUE THREAD

**Issue by RevRob** [xLightsSequencer/xLights#1784]
I am having issues with a few of my props not following what is programmed in xlights. we started our show last week and noticed something was not right. I have posted a video of a hat, a black cat and one of my skulls that I pulled out of the yard. The cat and skull should match the programming of the hat. You can see from the video that the cat and skull our showing some weird colors. I am not sure what is causing this. I have been troubleshooting it for 2 weeks now. I have gone through my xlights set up and controller set up. I even had some help from Don Gillespie. He went through all my numbers with me as well. When I go to test mode on my controller everything works fine and it will cycle all the colors. When I go into the xlights test console and select ALL channels and go to red it works fine. If I just select the cat and skulls it starts messing up and makes weird colors. I have checked my cat5 cables and tried new ones. I have swapped the extension cords on hat and cat and the problem just switches to the other prop. I have tested extension cables to make sure it is not that. I have swapped ports on the controller to a known good one and the issue follows. I checked all the connections on the ports of the controller. I checked the pigtails and all was well. I have done the check sequence and no issues. When I was working with Don in my thriller sequence we took the color off the effect and the cat was still lighting up almost like it mirroring the house outline. I am not sure what could be causing it. It just seems to happen on effects in the sequences. When it is single colors everything appears to work fine. 

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.60

https://www.dropbox.com/sh/n6kspyqick3u8lh/AAAt21-b4P-rxJBmk_7oIr3La?dl=0

**Comment by keithsw1111** [comment]
So it looks fine on screen but not ok on the lights. Are you playing from xLights, xSchedule or FPP?

**Comment by keithsw1111** [comment]
I dont see a problem on the sequencer screen ... 90% probability your problem is FPP or controller configuration.

**Comment by RevRob** [comment]
I am playing from xSchedule!

**Comment by keithsw1111** [comment]
What colour is the show folder name in the bottom left of the xschedule window. I am guessing not black.

**Comment by RevRob** [comment]
I will check that when I get home from work I dont remember off the top of
my head. I will also look over the controller config. Don and I checked
that the other day through team viewer but could be missing something..
Does it mean something if it is not black?

**Comment by keithsw1111** [comment]
It does ... it means it is not the same config as xLights

**Comment by RevRob** [comment]
Ok I will check that after work and let you know!! Thank you for looking
into it!! Thoughts on what else it could be if it is black?

**Comment by keithsw1111** [comment]
I can think of lots of things ... not going to speculate

**Comment by RevRob** [comment]
Ok thank you. I will let you know about the show folder in xschedule.

**Comment by RevRob** [comment]
So I just checked and it is black at the bottom of xscheduler...

**Comment by keithsw1111** [comment]
I am in zoom right now if you want me to look

**Comment by RevRob** [comment]
I just saw your email! Are you still in there ?

**Comment by RevRob** [comment]
It looks like I missed you. Will you be in there another time?

Thank you Robin

**Comment by keithsw1111** [comment]
I am back in ... sorry was doing a test that smashes my network

**Comment by RevRob** [comment]
Thank you again for your help last night. I did some more testing today
in xlights test mode and had something interesting happen. I wanted to run
it by you and see what your thoughts were. I will try and explain it the
best I can. I selected the hat, spider & the cat and put them on red. The
hat and spider turned red and the cat turned green. I then selected green
and the hat and spider turned green but the cat turned blue. I then
selected blue and the cat turned a purple color but the hat and spider
worked fine. I repeated this for the 10 skulls that are giving me problems
as well and had the same mixed-up colors. This is where it got weird when I
selected the hat, spider, cat and all 10 of the skulls together. The colors
started working fine. Everything went red but if I started unchecking some
of the modes then the colors went back to acting up. I had just Skulls 1-10
Selected and 1-6 were red and the 7-10 were off. So the hat and the spider
work 100% of the time the cat and the 10 skulls are all over the place.
Then I had skulls 1-10 and the cat checked and skulls 7-10 and the cat was
blinking but skills 1-6 were fine. If you just select skulls 1-6 then they
are the wrong color. It is so weird.

Thank you
Robin

**Comment by keithsw1111** [comment]
Would need to spend more time on zoom to work this out.

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by RevRob** [comment]
Yes it can!
