### ISSUE TITLE
After opening large sequence (~50MB), many functions in XLights stop working

### ISSUE THREAD

**Issue by davidslowik** [xLightsSequencer/xLights#1786]
After opening large sequence (~50MB), many functions in XLights stop working. For instance, Import | Import Effects responds with a beep. Tools | Package Sequence doesn't do anything, Tools | Test brings up a dialog that is mostly empty. Just reproduced again and this time along with the beep on Import Effects, it showed the dialog with the following text.
[Window Title]
Xlights Error
[Content]
File dialog failed with error code ffff.

Rebooted the computer and the same issue was present. I tried many versions of XLights and found that is worked in .55 and broke in .56 and is still broken in the current development version 

1. Start XLights 
2. Load the large sequence
3. Try things like Import Effects

- OS: Windows 10
- xLights version 2019.56+

Attaching the log and directly emailing sequence.
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/3774313/xLights_l4cpp.log)

**Comment by keithsw1111** [comment]
I will look at it ... but strongly suggest you try to move away from large sequence files ... you will have issues with performance and it is generally not necessary.

**Comment by davidslowik** [comment]
Most of the large sequences were from importing LOR lms and loredit's. I redid those large sequences and imported sup files and xml's instead and now all my sequences are under 1.5MB.  So I won't have that 50MB issue anymore.
