### ISSUE TITLE
Groups to include polyline segments

### ISSUE THREAD

**Issue by SpudGunMan** [xLightsSequencer/xLights#1814]
when making a group there is a checkbox to include sub-models

however when using individual segments on poly lines they are not sub-models (but you can name them and show them in a sequence)

requesting that groups be able to add the segments as well as sub-models so if I have a poly line around my house trim I could group the strand into things like (group all house vertical lines) and not have to go back and sub model the poly line that is already split up with individual segments option.

**Comment by AzGilrock** [comment]
Technically this request isn't a PolyLine exclusive issue.  For one check the individual segments box has little to do with this.  That only allows you to specify an exact number of pixels for each segment.  The PolyLine still has the same number of segments either way.  And a PolyLine segment is equivalent to a Strand on any other model so in the same way we don't allow you to add a MegaTree strand as a sub-model either.  So what you are really asking is that every strand on every model be allowed to be a sub-model automatically.

**Comment by AzGilrock** [comment]
For the record I had to go test this because I could swear I remember adding some of my  PolyLine segments to a group.  I thought we automatically treated strands and sub-models as the same thing.  Maybe we used to and it changed but I'd have to test older versions unless someone else remembers.

**Comment by keithsw1111** [comment]
I dont think we ever allowed strands to be added. For a couple of reasons ... 1. they are not actually models (so a group cant contain them) 2. It would potentially create an insane number of things to choose from in the model group panel.

**Comment by SpudGunMan** [comment]
Makes sense - what about a option on the poly line to allow segments as models

**Comment by AzGilrock** [comment]
You could have created sub-models in the time we've been talking about it and layouts don't change often.  You already have the capability to create these sub-models.

**Comment by SpudGunMan** [comment]
Interesting response to a feature enhancement. 

Sure .... thought the whole point of git hub and open software development is open ideas. 

You are correct it’s perfect how it is - why enhance it any further. Sorry for the intrusion.

**Comment by AzGilrock** [comment]
And the way open software development works is someone who actually develops the code has to want the change.  Right now I don't but I'm not the only developer.  Just look through the issue list its 100+ enhancements that are wanted that just sit there forever.

**Comment by keithsw1111** [comment]
I was responding to Gil about him thinking it was previously there and pointing out as strands are not derived from the models class i dont think this is a feature that was previously there and removed.

I personally see the value in adding segments of polylines to groups but done poorly I think it causes all sorts of usability issues which I am keen to avoid. It is also important to me that the code remains clear and logical ... I dont want random specific code appearing to make this work ... which is clearly doable but undesirable from a maintenance perspective.

**Comment by AzGilrock** [comment]
And I always try to tell someone how to use what's already in the program because you never know how long you will wait for a feature.  My issue would be that a lot of my PolyLines have dummy segments that I wouldn't want showing up in the group list.

![image](https://user-images.githubusercontent.com/2024669/68632300-41ea1500-04ab-11ea-97df-64b0c6ff8d27.png)

**Comment by keithsw1111** [comment]
Yes ... we would have to exclude 0 node segments.

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by cybercop23** [comment]
But isn't submodels (as you suggested) even better.. since you can name them? Else you'll need the ability to re-name segments too (you know someone will ask for that sooner or later).

**Comment by cybercop23** [comment]
Now that's a compremise, if I've ever seen one.
