### ISSUE TITLE
Add Sync section to check sequence in xschedule

### ISSUE THREAD

**Issue by madsci1016** [xLightsSequencer/xLights#1829]
**Is your feature request related to a problem? Please describe.**
When you have FPP master AND remote sync selected at the same time, xschedule will crash upon first few sync packets. 

**Describe the solution you'd like**
Well, it's my fault, but upon figuring it out and looking at check sequence inside xschedule, there was no warning about it. Maybe a message in a sync section like "Warning, FPP master and remote configured at same time. May cause issues. Are you sure that's intended?" would be nice. 

Not that anyone looks there though. We did AFTER we figured out the problem, so there's that. 

**Describe alternatives you've considered**

**Additional context**
It was Robert's fault too. 

-Bill

**Comment by cybercop23** [comment]
I don't use xSchedule. Has this been resolved or improved? Can this be closed?
