### ISSUE TITLE
F16V3 Upload fails under certain smart receiver conditions

### ISSUE THREAD

**Issue by jspiker77** [xLightsSequencer/xLights#1839]
In you have multiple smart receivers, A -> B and do not use the ports continuously the upload fails to properly configure the controller. For example if you are using port 1 and 2 on smart receiver A then port 4 on smart receiver B and have nothing on port 3 on either receiver it misconfigures the controller . See attached.
![bad](https://user-images.githubusercontent.com/25041955/69767744-8ffd4a80-1132-11ea-88b5-efaa6638af16.jpg)

**Comment by keithsw1111** [comment]
Can you try this in 2020.01 ... I may have this fixed. It will insert a dummy model on any missing smart receivers.

**Comment by jspiker77** [comment]
I'll test it on Tuesday Keith when I shut down the display and let you know.
