### ISSUE TITLE
Warp Effect with "circle reveal" on a group with "Per Model Default" not working

### ISSUE THREAD

**Issue by computergeek1507** [xLightsSequencer/xLights#1848]
**Describe the bug**
When I attempt to use the Warp Effect with "circle reveal" on a group with "Per Model Default"
 the warp effect does not render anything. If I move the same effects to the individual model it works as expected.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add a Warp Effect with "circle reveal" and "Per Model Default" to a group.
2. Added a Second Effect under it.
3. See it not work.

**Expected behavior**
Should work the same as the Model Level behavior

**Screenshots**
![Warp](https://user-images.githubusercontent.com/2293065/70057097-8b111e80-15aa-11ea-846c-f5d389afd26e.gif)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.68

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

[WrapTest.zip](https://github.com/smeighan/xLights/files/3916934/WrapTest.zip)

**Comment by KMojek** [comment]
I finally took a quick look at this one; it seems like only the "dissolve" and "wavy" warps are working as expected with "Per Model Default". Not sure why yet; the RenderBuffer seems to be sized as expected (grouping two matrices, the RenderBuffer size matches each matrix dimensions). The warps that aren't working seem to either turn everything black or have no effect at all. The other canvas-mode effect, Kaleidoscope, seems not to have similar problems.

**Comment by KMojek** [comment]
I've been poking at this off-and-on for the past few days; I think I have a better understanding of rendering but am still missing some bits. I can easily repro this by creating a layout with:
* two 128x96 matrices next to each other
* group the two matrices
* create a trivial sequence with just the group and two layers; butterfly on the bottom layer and warp on the top layer with "per model default" layering

Setting some breakpoints in rendering, I see the following:
* butterfly rendered into 400x104 buffer (seems reasonable given the layout and default 400x400 grid)
* warp rendered twice into 128x96 buffers (seems reasonable for per-model rendering on two matrices)

Before the warps are applied, during the "canvas logic" in `RenderJob::ProcessFrame()`, it thinks the buffer size is 24576x1 (number of pixels for both matrices) and seems to set every single one, but by the time the warp effect(s) are rendered, they just see empty 128x96 buffers as the previous layer.

**Comment by merryoncherry** [comment]
I tried running this recently.  It worked as expected for me, but it does run into #3740.
