### ISSUE TITLE
Copy Effect Render Styles

### ISSUE THREAD

**Issue by jb1677** [xLightsSequencer/xLights#1853]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If you create a single strand effect on a single model and copy/paste it to a group the render style do not update leaving you with the limited render style's.  The opposite is true as well, if you copy the single strand effect from a group to a single element the render styles for a group still appear.

**To Reproduce**
1. Create single strand effect on single model
2 . Note "Render Style" options in Layer Settings
3. Copy effect and past on group
4.  Note that "Render Style" options are still limited as if its a single model

**Expected behavior**
I would think that the Render Style menu should update based on the model not based on the source of the effect

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.68

**Comment by computergeek1507** [comment]
I noticed this bug too, if you click off the effect and then reselect it. The render style drop-down with update with the correct options

**Comment by cybercop23** [comment]
Not an issue in 2024.2+
