### ISSUE TITLE
XLights Crashes when Opening sequence created from LOR Sequence

### ISSUE THREAD

**Issue by mwnance** [xLightsSequencer/xLights#1872]
I am having an issue with XLights.   I create a new sequence,  Import Music, then import a sequence from an LOR sequence.   I render it, Play it and it works fine.  I save it and close it.  When I open it again it crashes.  I have tried it with 3 different LOR Sequences and the same problem.
It creates a crash report but not sure if it gets sent to Xlights.   Anyone have a similar issue.

**Comment by keithsw1111** [comment]
You are going to need to share the sequences with us. I assume this is happening in .70.

**Comment by mwnance** [comment]
Thank you for the email.  I am attaching 2 crash reports which I assume
have the sequence and details.  I have discovered that if I import the
sequence when I am creating it as new that is when the issues happenes.
But if I create a new sequence with music then go up to the import tab it
works ok.

**Comment by keithsw1111** [comment]
I dont see any attachements

**Comment by AzGilrock** [comment]
You normally need to log into Github to add attachment not sure doing it from email will work.

**Comment by mwnance** [comment]
[xLights_dbgrpt-1740-20191215T112328.zip](https://github.com/smeighan/xLights/files/3981638/xLights_dbgrpt-1740-20191215T112328.zip)
[xLights_dbgrpt-7812-20191214T163239.zip](https://github.com/smeighan/xLights/files/3981639/xLights_dbgrpt-7812-20191214T163239.zip)
[xLights_dbgrpt-16276-20191210T215256.zip](https://github.com/smeighan/xLights/files/3981640/xLights_dbgrpt-16276-20191210T215256.zip)

**Comment by keithsw1111** [comment]
I need the sequence ... there is not enough in the crash dump to reproduce this problem

**Comment by mwnance** [comment]
[WizordsLOR.zip](https://github.com/smeighan/xLights/files/3986256/WizordsLOR.zip)

**Comment by keithsw1111** [comment]
That is only part of the sequence. Can you use tools package sequence so we get it all.

**Comment by mwnance** [comment]
[WizardsLOR.zip](https://github.com/smeighan/xLights/files/3990032/WizardsLOR.zip)

**Comment by keithsw1111** [comment]
Hmmm ... so I opened it ... rendered .. played .. I can see all your LOR sequencing. Also closed and reopened no issues.

.71 will be out soon. Will get you to try with that version as it has some crash dump fixes which might give us more information about why it crashes on your machine.

**Comment by mwnance** [comment]
I got the new version and was able to open the sequence without a crash
now.  Weird thing is I still dont see the effects in the view window.

I have a work around so only telling you for future reference.  Thank You
for your help
