### ISSUE TITLE
XSchedule "test mode" disables the prop 

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#1877]
I can see the test mode is in beta but figured I would report the a bug I saw

I went to "test" my arches in the web interface test mode and when I hit "on" the arch did not come on AND it also disabled the arch altogether so now when my show ran the 1 arch would not light up, I tried to hit reset on the test screen for that arch but no luck, the only fix was to totally shut down the program and restart, then the arch worked as it should

**Comment by keithsw1111** [comment]
I am not sure about the first part but the second part i believe is already fixed for .71

Can you reconfirm both once .71 comes out

**Comment by bchiaino** [comment]
absolutely, ill check it out and report back once it is posted. thanks keith!
