### ISSUE TITLE
XSchedule looping lead out

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#1883]
So last night I was outside all night with viewers and using my phone to jump to songs using "buttons", then as it got close to 10PM (22:00) I hit "add 10 minutes to schedule" a few times because the schedule was set to end ar 21:58 we still had a good crowd but by 22:15 or so we were done so I pressed "end gracefully" while my 2017 Medley 2 was playing, at the end of the medley the "lead out" played silent night as it should but it didn't go too my next schedule, it kept looping the lead out until I "stopped all" and "reset schedules", then it played my schedule set to start at 22:00 for background music

you can see in the log that at 22:14:11 the medley ended and lead out / silent night started and ended and then after a bunch of lines at 22:14:51 it starts playing silent night again. 

I attached the log file and my xschedule file
[log1 1223.docx](https://github.com/smeighan/xLights/files/3995092/log1.1223.docx)

Xschedule - https://drive.google.com/file/d/1U44hhKLjiwZm2GehVC5vCASK3JWQyFpF/view?usp=sharing

**Comment by bchiaino** [comment]
Tonight was even worse on the "end gracefully"

I skipped through some tracks again tonight for some favorites to play and then extended the schedule by 30 minutes or so using the "add 10 minutes to schedule" and I noticed both the "22:00" sequence that should be next AND the 16:44 for tomorrow were both marked blue for "next". when I hit end gracefully the show ended as it should and then went into tomorrow 16:45 schedule and not the 22:00 one that should have played. definitely some weird stuff going on once you start jumping around a playlist. 

here's the log that includes just tonights show. - https://drive.google.com/file/d/1P1iuLrkTBh-75GgPvWIrGwfGCUJuUFDe/view?usp=sharing
you can see at 22:39 the lead out ended and then it played 15 MIN PRE SHOW which is scheduled for tomorrow, once I stoped all and reset the schedule then it played the "twinkle" I play for the last hour or so

I attached a pic too showing how all the playlist are marked blue as "next" but obviously it is not correct
![IMG_2953](https://user-images.githubusercontent.com/40632971/71393500-d8494480-25da-11ea-9b37-08a213969421.JPG)

**Comment by bchiaino** [comment]
I think it hit me on why the main show goes back to the 16:45 15 min pre schedule, the MAIN SHOW is cutting off the last few seconds of a 15 minute pre show therefore its also keeping it "blue" because it is going to go back and finish that schedules few seconds that were cutoff before going to the 22:00 twinkle background. I just changed MAIN SHOW to gracefully interrupt so ill see if that makes a difference tonight, not the 15 min pre show should completely finish dn then the main show will being at like 17:00:04

**Comment by cybercop23** [comment]
Can this be closed?
