### ISSUE TITLE
Add support to xschedule for TLS when connecting to an MQTT broker

### ISSUE THREAD

**Issue by pierslawson** [xLightsSequencer/xLights#1899]
**Is your feature request related to a problem? Please describe.**
As far as I can see it is not currently possible to publish / subscribe to MQTT topics when broker is enforcing TLS for secure connections.  

**Describe the solution you'd like**
It would be nice to be able to send messages to an MQTT broker that insists on using TLS. Ideally I could set up xschedule similarly to Node Red... provide a self-cert CA key and optionally provide a client certificate and private key.

**Describe alternatives you've considered**
At the moment the workaround is to turn off TLS for the specific IP Address of the device running xschedule.

**Additional context**
Otherwise, I'm loving the MQTT functionality! Thank you!

**Comment by keithsw1111** [comment]
This is unlikely to happen any time soon due to implementation complexities
