### ISSUE TITLE
xScheduler Resource Issues

### ISSUE THREAD

**Issue by NWF-Geek** [xLightsSequencer/xLights#1936]
**Describe the bug**
After running for several hours, xScheduler causes excessive resource consumption.  I realize this sounds weird, but it is not the xScheduler process itself that is allocating the memory.  Rather, something xScheduler is doing is causing memory to be allocated.  If allowed to run long enough, so much memory is consumed that the system begins thrashing -- that is, constantly swapping data in and out of virtual memory.  At this point, disk usage goes to 100%, memory usage is approximately 97%.  If I disable xScheduler's output by clicking the bulb in the toolbar, this causes all of the allocated memory to be released.  It takes several minutes for the system to recover after doing this, but eventually the disk usage drops to normal.

**To Reproduce**
I run xScheduler to provide scheduled output of xLights-produced FSEQ files.  At this point in the post-season, most of my props and controllers are offline.  The only output in my files is for my 6x6 P10 matrix, which is run by a BBB, running FPP in Bridge mode (I know all the rhetoric about using too much network bandwidth, but at 20 FPS I've never even come close to maxing out my network.
Perhaps relevant to the issue, there is no audio file associated with the FSEQ that's running.  

**Expected behavior**
Normal execution of xScheduler, without increasing resource usage over time.

**Screenshots**
I haven't made screenshots of the Task Manager, showing the problem developing over time, but if you think it would help visualize the problem, I can certainly perform some captures and make them available.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: Currently 2020.4.  HOWEVER, I need you to know that I was running 2018.51 all through both the 2018-2019 season, AND the 2019-2020 season, because it was working for me (I had extended interaction with Keith over some LOR issues that were killing my show, and 2018.51 fixed everything, but 2018.52 and .53 weren't working properly for me, so I fell back to .51, and used it until the 2019-2020 season concluded.  Now, I want to go forward with stuff like 3D, so I really want to upgrade, but this problem has prevented me from doing that so far.

**Additional context**
I've fallen back to 2018.51, and the problem went away.  Re-loaded 2020.2, 2020.3, and 2020.4, and the problem was present in all versions.  You might have seen a discussion thread I opened on this topic on the Official xLights Support Group.  Unfortunately a few people decided to be jerks, rather than trying to help, but there were a few other people who confirmed they have had similar problems.

**Attachments**
As I write this, I have no idea whether any logs, data files, etc would contain anything revelatory.  I would be happy to attach anything and everything that you think might help figure out what's going on.  Please ask, and I'll send it along.

**Comment by NWF-Geek** [comment]
Has anyone looked at this yet?  There are no comments on it.  I am prepared to send support info if someone will tell me what would be useful.

Now that 2020.5 is out, and you can not go backwards once you go forwards, I am now unable to update until I know for sure that running xScheduler isn't going to bring my system down every 4-6 hours.

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by NWF-Geek** [comment]
Presumably so. This problem was endemic to a versions in (I believe) 2020. I used a 2023 version this past season and there were no apparent memory leaks. -jwSent from my iPhoneOn Feb 6, 2024, at 12:24 PM, AlexB ***@***.***> wrote:﻿
Can this be closed?
