### ISSUE TITLE
under face definition

### ISSUE THREAD

**Issue by jdmaag** [xLightsSequencer/xLights#1938]
when i open face definition and add a face i want to use and click download images i keep getting (Error unable to retrieve any faces).

**Comment by computergeek1507** [comment]
try Tools->Purge Download Cache.

![image](https://user-images.githubusercontent.com/2293065/74560695-173dab80-4f35-11ea-9532-62451a5c4430.png)

**Comment by jdmaag** [comment]
does not help. tried thar

**Comment by computergeek1507** [comment]
maybe attach a log file or create a video, it is hard to diagnose with not information

**Comment by jdmaag** [comment]
https://youtu.be/W5AqNR4FTug

**Comment by jdmaag** [comment]
https://youtu.be/W5AqNR4FTug

**Comment by keithsw1111** [comment]
I need to see the log ... my guess you have internet connectivity issues.

**Comment by jdmaag** [comment]
ok, i found it

**Comment by kennyswanson** [comment]
hi all having the same problem as above any ideas  TIA

**Comment by computergeek1507** [comment]
Please make sure you are running the latest xLights 2020.45
