### ISSUE TITLE
xlights crashes with servo effect. 

### ISSUE THREAD

**Issue by shanerehm1234** [xLightsSequencer/xLights#1956]
I had xlights crash on me repeatedly when adding the servo effect to the DMXSkull model in the sequencer. it only seems to happen with the skull model is configured with only the "Jaw servo" box checked. When all the options are checked (except 16-bit and Skulltronics) it works great!

XLights version 2020.6 64-bit

![image](https://user-images.githubusercontent.com/33357706/75508866-60ace280-599a-11ea-9f82-0d41c368f7cf.png)

**Comment by skulltronix** [comment]
I'm having xlights crash every time I import a VSA file.  Newest version. Standard skull model.
[xLights_dbgrpt-16564-20200317T115554.zip](https://github.com/smeighan/xLights/files/4345382/xLights_dbgrpt-16564-20200317T115554.zip)

**Comment by AzGilrock** [comment]
Shane - When you use the Servo effect is the 16-bit box checked in the effect settings?  It sounds like you are telling it to write 16bits of data to the model but you only have an 8bit Jaw servo defined.  The effect is dumb it's not trying to see how many bits are on the servo.

**Comment by skulltronix** [comment]
I’m not Shane.. but I have it defined as 16 bit. 
With the latest xl update I’m getting no movement at the servo when in sequence mode. 
Xl is sending data. FPP is receiving data but no servo movement. 
Servos move under xl test mode and FPP test mode. So communication is there. 
I had Ed look also and he was baffled. 



Jerry Jewell
Skulltronix.com
916 600 2295

**Comment by AzGilrock** [comment]
Jerry your problem sounds completely different so don't pollute someone else's issue thread.

**Comment by AzGilrock** [comment]
Almost 4 years old so I'll assume this is sorted.  Otherwise open a new issue and reference this one.
