### ISSUE TITLE
Feature Request: Add 90 Minute Interval to xSchedule Refire Frequency OR Allow custom entries

### ISSUE THREAD

**Issue by jholmes09** [xLightsSequencer/xLights#1961]
**Is your feature request related to a problem? Please describe.**
I often have to trigger shows in a round-robin fashion every 30 minutes.
This is fine when I have two shows (I schedule each to refire every hour then offset their start time) but if you have 3+ shows, the only option is to manually schedule every playback.

**Describe the solution you'd like**
I would like a 90-minute refire interval option or the ability to input my own interval

**Describe alternatives you've considered**
Currently I create a new schedule to fire once, non-repeating, for each time I need each show to play. When running shows from 6-11 PM, this results in 10 schedules spread across three playlists. 

**Additional context**
See screen-shot of current workaround.
![Annotation 2020-03-04 132111](https://user-images.githubusercontent.com/18503894/75909963-0c32b880-5e1b-11ea-99fb-799a73a05d33.png)

**Comment by cybercop23** [comment]
Available in the nightly built and next version.
