### ISSUE TITLE
2020.01B (MAC) and higher locks up rendering videos on matrix screens

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#1985]
Just started rendering sequences after a while of taking off from the lights and noticed that rendering is locking up a lot and stalling Xlights and I have to force quit to get out

I went back to the beginning of 2020 releases and 2020.01 works great and then there was a 2020.01b release and that is where the issue started, anything from the b release up is not working, the videos on my matrix screens won't complete the render process

This is on Mac only, my pc renders the same sequence fine. The Mac is on Catlina 10.15.2m i5 with 8gb ram.

I have attached the packaged sequence and logs along with the screen shot of where it gets held up

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4388848/xLightsProblem.zip)
[CHARLIE MEDLEY.zip](https://github.com/smeighan/xLights/files/4388849/CHARLIE.MEDLEY.zip)
![Screen Shot 2020-03-26 at 1 21 42 PM](https://user-images.githubusercontent.com/40632971/77678052-fe2e0e80-6f66-11ea-9d2f-d30a028dbb76.png)

**Comment by keithsw1111** [comment]
Try turning off hardware decoding. Does that help.

Sent from my iPhone

On 27 Mar 2020, at 4:38 am, bchiaino <notifications@github.com> wrote:

﻿

Just started rendering sequences after a while of taking off from the lights and noticed that rendering is locking up a lot and stalling Xlights and I have to force quit to get out

I went back to the bringing of 2020 releases and 2020.01 works great and then there was a 2020.01b release and that is where the issue started, anything from the b release up is not working, the videos on my matrix screens won't complete the render process

This is on Mac only, my pc renders the same sequence fine. The Mac is on Catlina 10.15.2m i5 with 8gb ram.

I have attached the packaged sequence and logs along with the screen shot of where it gets held up

xLightsProblem.zip<https://github.com/smeighan/xLights/files/4388848/xLightsProblem.zip>
CHARLIE MEDLEY.zip<https://github.com/smeighan/xLights/files/4388849/CHARLIE.MEDLEY.zip>
[Screen Shot 2020-03-26 at 1 21 42 PM]<https://user-images.githubusercontent.com/40632971/77678052-fe2e0e80-6f66-11ea-9d2f-d30a028dbb76.png>

**Comment by dkulp** [comment]
I'm not able to reproduce.   It's rendering fine on my Mac.

**Comment by bchiaino** [comment]
Keith, With hardware decoding off the sequence renders fine (thanks for the suggestion) with it on though on both my macs (mac mini and MacBook pro, same specs) it stalls 75% of the way through

Daniel, it fails on both of mine once hardware decoding is enabled, is there anything I can do or send you to look at? Its not a big deal being I can just leave the setting off but I did noaarow it down to it maybe being a change between 2020.01 and 2020.01b

**Comment by bchiaino** [comment]
Daniel on the mac end I noticed this is only happening to video that is in a group, not individual prop. at 2:56:200 I have a video that was in ""MATRIX BOTH"" which is my 2 screens and with hardware decoding on I can never render, once it hits that video Xlights locks up. If I move that video off of the matrix group and put it just on the individual matrixes then it renders fine. 

I can zoom one day if there's anything I can run on my macs to see why this is happening, again its only happening in later versions, it used to work fine

**Comment by derwin12** [comment]
So much has changed ... if this is still an issue please repost your current specs and versions.
