### ISSUE TITLE
Sequencer locks up if the house preview is on another monitor

### ISSUE THREAD

**Issue by Docbrew** [xLightsSequencer/xLights#2019]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If I move the house preview window to my second monitor, work with my sequence, render, save, or do nothing, ect... then I close out of xlights.  When I launch xlights again and click on the sequence tab the house preview window shows on my second monitor 
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4500849/xLightsProblem.zip)
but xlights it stops responding and eventually windows will close it.  I have to click on the View>windows>reset to default to get the sequence tab to stop locking up.

**Versions (please complete the following information):**
 - OS: Win10
 - xLights version 2020.16 but has been an issue since back in 2019

**Additional context**
If I move the house preview window to my second monitor, do whatever needed to sequence then move the house preview window back to the original monitor xlights started on I don't have issues when I restart.  This has been and issue on 2 different computer's I've sequenced on.  Unfortunately the other computer crashed so I don't have any logs from it.

**Attachments**
https://www.dropbox.com/preview/Xlights%20issue/xLightsProblem.zip?role=personal

**Comment by keithsw1111** [comment]
I really need a simple animation as a packaged sequence. The problem looks related to your mesh Boone new 19.obj which seems to take a really long time to load.

**Comment by Docbrew** [comment]
I hope this is what you need.  I'm sure you have noticed that I'm running 3D mode.  I unchecked 3D in the layout tab and got the same lock up.

[House preview issue test.zip](https://github.com/smeighan/xLights/files/4511611/House.preview.issue.test.zip)

**Comment by Docbrew** [comment]
Is there something I need to do in my xlights install/files to resolve?

**Comment by keithsw1111** [comment]
I dont see any issue. Try starting xLights with the /w command line switch. This will clear all settings but also get rid of any window state which might be causing issues.

**Comment by cathelest** [comment]
I seem to be having a similar issue, and have tried /w but doesnt seem to reset windows?

[https://cathelest.com/xlights.mp4](https://cathelest.com/xlights.mp4)

I have managed to use a older rgb effects file to fix my setup, so i can use xlights, but here is the "dodgy file" in case it helps,
[https://cathelest.com/xlights_rgbeffects.xml](https://cathelest.com/xlights_rgbeffects.xml)


Not sure how to get any other logs or anything, looked into event viewer in windows, shows events for application hang, but doesnt seem to have any useful info,

**Comment by keithsw1111** [comment]
cathelest: Can you package a sequence for me ... just an empty one ... maybe with that I can reproduce it ... but so far I am getting nothing ... everything works as well as can be expected given how incomplete the files are.

**Comment by cathelest** [comment]
I have managed to reproduce the crash,

It seems to be with the perspectives,

I will attach a video i have recorded for you, aswell as the "new folder" blank new show folder you will see me make at the start,

I create a new show folder "new folder" and change to it,
I switch to sequencer tab and drag the house preview to the other monitor,
I save a new perspective "new"
I close and reopen xlights and switch to sequencer tab.

[https://cathelest.com/xlightsblank.mp4](Video)
[https://cathelest.com/xlights.zip](New Folder Zip)

Let me know if i can help or if im doing something wrong,
Many thanks for your time,
