### ISSUE TITLE
Crash on render 

### ISSUE THREAD

**Issue by scottasu** [xLightsSequencer/xLights#2038]
Sequence -  PPD Shake up Christmas - pro layout.
Xlights versions error is occuring on -  2020.15, 2020.16, 2020.17, 2020.18.   (Same error in every version).
Computer: Macbook air 2010

Bug:  I'm getting an error message "Atos needs to take control of a process" followed by a crash when I first open the sequence in the PPD pro layout and attempt to render to save it.  It consistently crashes at the spinners models so I can never get to a point to save the sequence on my computer.

**To Reproduce**

1. Open Xlights
2. Chose controller layout to point to PPD purchased sequence files for "Shake up Christmas" pro layout.
3. Once opened go open to open sequence files and navigate to Pro layout folder for Shake up Christmas and select the Shake up Christmas XML file. 
4. Click Render all button.  
5.  wait until it gets to spinner models and wait for error message/crash report.

**Expected behavior**
Expected the sequence to finish rendering so I could save the sequence and fix the links so I could then go switch to my layout and import the sequence.

**Versions (please complete the following information):**
 - Mac Airbook 2010 OS X Yosemite 10.10.5
 - xLights 2020.15, 2020.16, 2020.17, 2020.18

**Additional context**
This is the only sequence this happens on.  All of my other PPD sequences and other professionally purchased sequences work perfectly.

Please PM me for files and crash reports, I am happy to provide.

**Comment by keithsw1111** [comment]
PM who/how? How about you send them to me.

**Comment by scottasu** [comment]
Hi Keith,

Attached are the files and crash report. If you need anything else from me to help just let me know.

Scott~

________________________________

**Comment by dkulp** [comment]
You're Mac is old and might be having issues with the video decoding in hardware.  Go to preferences and turn off the video hardware decoding and see if that helps.

**Comment by scottasu** [comment]
Hi Dan,

This did allow me to render and save on the PPD layout.  When I changed the directory back to my layout show folder and imported the files it sill gives me the same error message when I try to play it back to see the house preview.  Is this just a sign that my computer is no longer sufficient for the video content in this sequence?

Scott~

________________________________

**Comment by scottasu** [comment]
I played around with it a little more and noticed any time I am in the Sequencer tab and I click on the effects that mapped over with a video file it automatically generates the Atos needs to take control of a process error message and crashes.

Example is the Matrix video file.

Is there anything I can do to keep that from happening?

Scott~
________________________________
