### ISSUE TITLE
Crash when adding Polymorphic timing

### ISSUE THREAD

**Issue by Qantarus** [xLightsSequencer/xLights#2046]
Describe the bug 

When trying to add polymorphic timing to a sequence, application crashes. Only happens on the attached sequence. First tried to add in 2020.16

To Reproduce Steps to reproduce the behavior:  open attached sequence and attempt to add polymorphic timing track along with the other existing timings.

Versions (please complete the following information):

OS: Windows 10
xLights version. 2020.19

Additional context Add any other context about the problem here.

Attachments
crash log zip
Sequence package zip
[xLights_dbgrpt-13668-20200513T200457.zip](https://github.com/smeighan/xLights/files/4621245/xLights_dbgrpt-13668-20200513T200457.zip)

[Santa's Got a Hot Rod.zip](https://github.com/smeighan/xLights/files/4621303/Santa.s.Got.a.Hot.Rod.zip)
]

**Comment by keithsw1111** [comment]
There is not much we can do about this. I tried it in both the ways we run it and it crashes in both ... and deep in the QM code.
