### ISSUE TITLE
Video stutters and audio is not present when playing FSEQs in XLights Scheduler. (Use Media Player option)

### ISSUE THREAD

**Issue by hearmstinj** [xLightsSequencer/xLights#2059]
**Describe the bug**
This happens when we select the "Use Media Player" option in the FSEQ item settings.
When using the FSEQ option for a playlist item and selecting a video file to play, the video stutters quite a lot (Windows 10, [Version 10.0.18362.836]). Additionally, audio is not present since in the code, we have: _mediaCtrl->SetVolume(0); in PlayerFrame.cpp, line 147. I'm not sure if this is intended or not.

Additionally .MPEG files cannot be played at all by the XLights Scheduler. IT appears that they are not supported by the wxMediaCtrl widget.

Could this be due to xLights using the unstable 3.1.3 version of wxWidgets (the new stable one, 3.0.5 was released on the 25th of April).

**To Reproduce**
>Create a new playlist in xLights Scheduler.
>Add a new FSEQ item.
>Add a video file containing audio and select the video file.
>Hit the checkbox for "Use Media Player" so that is uses the wxMediaCtrl media player.
>Observe that no audio is played due to _mediaCtrl->SetVolume(0) having been set
>Observe that the video stutters quite a bit and (when changing SetVolume), the audio is quite choppy.

**Expected behavior**
The video should play audio. Whatever audio settings are available in the video file, they should be played (e.g. if it's stereo audio, or 5.1 or 7.1, then the media player should play the audio with those settings - e.g. how Windows Media Player perfectly parses whether the audio is Stereo/5.1/7.1).

**Versions (please complete the following information):**
- OS: Windows 10 (1909)
 - xLights version [e.g. 2020.21]

**Comment by jholmes09** [comment]
Have you tried un-checking the "Use Hardware Accelerated Video" checkbox in the options menu?
When I was having video playback issues that resolved it for me.

**Comment by keithsw1111** [comment]
Also use the native player option ... this will generally produce a smoother result

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by hearmstinj** [comment]
This can be closed.
