### ISSUE TITLE
New Sequence Dialog Adding Secondary Timings - Polymorphic Transcription

### ISSUE THREAD

**Issue by jmaudlin** [xLightsSequencer/xLights#2068]
xlights simply crashes out and closes.  Source media file is a video (mp4).  This typically works, but for some reason with this specific video source, it just dies.  Attacched please find crash reports.  

[xLights_dbgrpt-2588-20200528T135750.zip](https://github.com/smeighan/xLights/files/4697687/xLights_dbgrpt-2588-20200528T135750.zip)
[xLights_dbgrpt-3872-20200528T140130.zip](https://github.com/smeighan/xLights/files/4697688/xLights_dbgrpt-3872-20200528T140130.zip)

**Comment by keithsw1111** [comment]
i would need the media but even then likely the answer is there is nothing we can do about it as it crashes in the qm code

**Comment by jmaudlin** [comment]
no problem.   what's the best way to get it to you?  upload to the issue in github?
________________________________

**Comment by jmaudlin** [comment]
it's not a big deal to me, just simply won't use that specific timing track type  - however, it does work when adding the polymorphic timing  after the sequence is created.  was more just reporting it so guys knew :)
________________________________

**Comment by keithsw1111** [comment]
it depends on the digital rights. most pm them to us on fb or the forums
dropbox is often used due to size

**Comment by jmaudlin** [comment]
will do, np
________________________________

**Comment by AzGilrock** [comment]
Obsolete and no response
