### ISSUE TITLE
Some ideas to think from Ralph LEDchip@yahoo.com +1727 480-0452

### ISSUE THREAD

**Issue by ralphpaonessa** [xLightsSequencer/xLights#2081]
My Comments on xLights for the Chief Magician(s)
Really great software, dealing with pixels is something I have been working with for over 30 years and you guys have done a wonderful job creating this software.  There is so much great work you have done here.  You should be proud and I hope a little richer from having done this.  

As my personal contribution, I have a couple ideas that I think are worth throwing out there:
•	Do you think you could add an option to freeze the resolution (center to center spacing on the pixels) on the various models?  So, when a user adds more length to a string, he is adding pixels as opposed to stretching the pixels that were specified in the string from the chart.  When someone is using these products, the resolution is almost always fixed to a certain pixel pitch 100mm, 1”, 2”, whatever.  They take that strand of lights and run it across the trim.  While there still could be a scaling value that the user would put in to determine just how far apart 2 pixels are at 2-inch pitch on a 1080p computer screen.  Once that number is set to correspond to the scaling for the particular photo that is being used right now, it probably would not be changed again unless they changed the picture.  I wish they made variable resolution pixel stings, but that is basically impossible, so, why does your software allow them to work with them?
•	Along the same lines, when you have a model selected, if you zoom in or out, the model size changes.  Again, when the photo is loaded and a relationship between the photo and what is in the document window really needs to be frozen.  You cannot change the size of a Star model unless you do a TON of REAL WORK, not just scroll you fingers.  I find myself un-doing constantly when working with the model  layout.  I am on a notebook, but I can use the touchpad just as easy as anyone can use a mouse.  When I zoom, it is a two-finger drag up or down, which I guess is the same as a scroll wheel on a mouse.
•	It would be great to have an option to summarize the equipment that is required to make the current layout a reality.  The number of strings of how many lights, pre-made models that are placed, the expected amperage of 5 or 12 volts that you will need, you could factor in a lot of different stuff (driver cards, wire), even the number of attachments that should be made to the building.  You could go into a lot of stuff epending on how far you took this, but the basics of the number of pixels in the project, length of cable would be some really valuable information to bring out of the software.  You could even link to a store so the customer could make the order right there in the software and get the equipment shipped out to him.  
If you do not want to do this, is there a way to grab this info in a table from any of the current config files?  Maybe support DDE or OLE, some way to allow us to see what equipment has been laid out in the process. 
I have been in the LED display business for over 35 years and have done literally tens of thousands of quotes.  I built a spreadsheet that I would type in the size of the display, height and width that the customer wanted, the macro then makes a chart showing the cost, power requirements, weight, installation time, technical specifications of the system and a cover letter to attach to the quote.  In the chart is the cost and specifications for each of over 30 different pixel pitches, indoor or outdoor use, type of pixel technology and what the estimated shipping and tax costs would be.  All this data, just from how high and how wide the area is.  I would be glad to demo it for you if you would like.
•	I was thinking of a file exchange system to allow people to share their layouts and sequence files across the network of users.  To facilitate this, when loading an imported sequence file, if it sees model names that it does not know (not in the layout), allow the user to point to replacements that are in their system.  For example, the name for the lights on the hedges are called Bush-01… instead of Hedge-01…, so the user could point to the replacement and all programming for the Bush-01 will now be changed to Hedge-01.  Kind of like when you are bringing in a CSV to a database program, if the variable names do not match up, you can resolve those differences.
•	When making custom models where you are typing in the pixels numbers or clicking to put the next pixel number down, it would be great to be able to draw a line for the sequence of numbers to fill.  So, just by dragging across a grid, you would place a pixel path through the cells where the line was touching when they clicked.
•	Cursor movement of the models seems to come and go at will.  It works about 30% of the time.  When you select a model and it turns yellow, you should be able to move it with the cursor keys unless it is locked correct?
•	It would be great to be able to select more than one model name at a time from the list.  Right now, you cannot select multiple models unless you use the mouse on the layout window and that is a very, scary place to be and make selections from.  If you could do it from the list of names, it would be so much easier.
•	When having multiple effects selected that have been applied to models, it would be great to make changes across those effects by editing the attributes in the form (only common elements)  For example, the colors, the speed, xy location, or tying the attribute to a graph or the music beats.  This would make it so easy to make a wonderful show.
•	When moving models, please allow freezing of the horizontal and vertical directions if the control key is pressed.  Shift should allow scaling and keeping proportions correct.
•	I hate to throw around a term like AI, but, in the case of the layout and wiring setup, I would think that you could get some code to allow you to set some rules up and let it go.  I know that auto-routing CAD software has come down a lot, couldn’t you get a routine out of their code to help you set these pixel numbers automatically?  This wiring process can really take a lot of time.  The spreadsheet function has potential, but I think you would need to write some VB code to really make a useful tool with it.  Maybe you could work with someone that has experience with this if you don’t???
Please take a look at my website that shows what I have been up to.
DirectViewLED.com
Ralph "Chip"Paonessa
LEDchip@yahoo.com 
+1727 480-0452

**Comment by ralphpaonessa** [comment]
Sorry, I did just speak with the guys on Zoom, and they showed me how to do an import of a show and apply it to my layout.  This has a lot of steps in it, but it does work.  Please excuse my bringing it up.

**Comment by dkulp** [comment]
1) No - because the resolution is almost NEVER fixed to a certain pixel pitch.   The picture of my house, for example, due to depth, the spacing along the edge of my driveway becomes wider as it gets closer to the camera.    It may be "somewhat possible" in the 3D view, but definitely not in the 2D view.  

2) No - same reason

3) I don't see this happening.   We talked about trying to keep track of current draws and such before and have completely punted on it every single time. 

4) The import process pretty much already does this by allowing them to map from one to the other.  It currently doesn't attempt a  pure "name match", but that might be a OK suggestion.

5) Not sure what you are tyring to suggest with this one.  A background image can be used to provide a "line" or similar to help filling in the details.

6) Depends on if the focus is on the drawing view or on the tree view or in the property grid.   If the focus is on the tree view, the arrows should allow navigating the tree view.  Likewise for the propgrid.

7) This is being worked on.  Will likely make it for .24.  Just trying to finalize some of the differences between how the list view works on OSX, Windows, and Linux.  Gets complicated.

8) There is already a bulk edit capability built in

9) This could be a "valid" suggestion.

10) Not sure what value or where any sort of AI thing would be plugged into the Layout panel.

**Comment by keithsw1111** [comment]
• When making custom models where you are typing in the pixels numbers or clicking to put the next pixel number down, it would be great to be able to draw a line for the sequence of numbers to fill. So, just by dragging across a grid, you would place a pixel path through the cells where the line was touching when they clicked.

This is a valid request we have seen a few times ... maybe one day.

• When moving models, please allow freezing of the horizontal and vertical directions if the control key is pressed. Shift should allow scaling and keeping proportions correct.

This is also valid ... we already have this in a couple of places and it would make sense here,

The remaining requests are either impractical, undesirable or already exist.

In future it would be better to raise items individually. That way items can be closed. As is even if one item is done this ticket has to be held open as another item may still be valid.

**Comment by sslupsky** [comment]
I would like to add some support for the OP's first suggestion.  I am new to xLights and quite experienced in 3D modelling.  It seems to me that the 2D functionality is rooted in the historical use case of adapting perspective when using a 2D illustration as the background image.  Now that 3D models have been introduced into xLights, it seems to me that should change.

**Comment by AzGilrock** [comment]
This one was way too many suggestions in one ticket.  One idea at a time please.  Open new tickets for any ideas that might still be valid.
