### ISSUE TITLE
some models keep resetting to default

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#2088]
I have been noticing in the last few 2020 versions that when I open Xlights my 1 of my 3 "Bottom Window" models keeps resetting to the default size and details. I have it all set for a 2 years and all of a sudden I open Xlights and window 3 is default settings and bigger on the screen, I can reset it which takes a little time, save it and then reopen a few hours later and then window 2 is blown out to defaults. I attached a video showing how I can simply open xlights, move a few things, save, reopen xlights and the window is set to defaults but if I simply close Xlights and reopen then its back to normal. this is on my MacBook pro, 10.15.5 and 2020.23

video - https://youtu.be/XvDm3NUHVX8

[XLIGHTS.zip](https://github.com/smeighan/xLights/files/4765330/XLIGHTS.zip)

**Comment by keithsw1111** [comment]
There is no commentary in the video so I can only try to replicate what I think I see and i dont seem to be able to reproduce your behaviour. But i also notice odd things like the tooltip appearing on the layout screen ... maybe that is a mac thing.

**Comment by bchiaino** [comment]
sorry Keith, I couldn't do commentary because I was at work at the time clearly working , lol

pretty much I have 3 windows on the first level of my house on the left side all set, I open Xlights and click on some things and move some stuff and click save, close Xlights and reopen and window #3 at 30 seconds in is reset to Xlights default numbers and shape, you can see it no longer fits the window as it should like the other 2, I can then close Xlights and reopen it and the window is back to the way I had it configured originally. It doesn't happen a lot but enough that I started noticing the issue recently

**Comment by keithsw1111** [comment]
I can see the problem in the video ... but i cant seem to reproduce it.

**Comment by bchiaino** [comment]
ok no problem, just figured I would report in case you saw something funny in the files

**Comment by priemd** [comment]
It looks like you're show folder is on Google Drive.  Possibly a sync issue with gdrive?  Take your show folder out of gdrive, can you still reproduce?

**Comment by derwin12** [comment]
Brian is this still something you can reproduce? or can this be closed?
