### ISSUE TITLE
crashing on dragging lyrics

### ISSUE THREAD

**Issue by scottfeld** [xLightsSequencer/xLights#2094]
**Describe the bug**
2020.24   Was same on 2020.23.

seems to be hanging up, delays, spinning blue circle when:
editing lyrics.  no timing track selected, using cntl drag cursor w/mouse to select 3 lines, phrase, words, phonics.
then either cntrl+ left/right to move OR cntrl click 2x to grab the top pharse to drag left/right.

seems to lock up, graphics icons go grey, path bar on top shows (not responding)   from memory???
blue spinning circle, comes goes, several times then may recover.  

usually save right after

not every time.  can't corrolate to time or after a specific event.

**To Reproduce**
lyric phrase + lyric words + lyric phonics.
cntrl left click drag to select and entire phrase, words, and phonics
cntrl left or right to move block,  OR cntrl left click deselects phrase, cntrl left  click  again to regain whole block, drag left/right

seems to lock up    blue spinning circle, path bar at top says '(not responding)'  ??? something like that

**Expected behavior**
used to just move text block

**Screenshots**

**Versions (please complete the following information):**
Windows 10,64 bit]
 - xLights version 2020.24  2020.23 was doing it too

**Additional context**
the crash text box that popped up would not let me add comments, so created CRASH COMMENTS.txt and added to ZIP

**Attachments**
[xLights_dbgrpt-12040-20200613T215629.zip](https://github.com/smeighan/xLights/files/4775790/xLights_dbgrpt-12040-20200613T215629.zip)

**Comment by skydiveguy** [comment]
Im having this exact same issue with dragging an "On" effect in MacOS Catalina. 
2020.26.
Not all the time but frequently. Need to force quit app.

**Comment by keithsw1111** [comment]
I dont understand why you are pressing control? Do you mean shift? 

Either way I dont seem to be able to reproduce. Maybe you could make a video and talk us through what you are doing.

**Comment by scottfeld** [comment]
Keith,
Sorry for the delay in getting back to you on the issue.  Have been pretty
busy and have not had 'Xlights time'....
A) Yes the comment on using control and right or left after selecting a
group was incorrect.  Just use the right or left arrow without control.
B)  Was getting ready to record, wanted to practice before recording, was
able to repeat, issue recurred and I had to terminate Xlights.  Now it does
not seem to want to repeat.
C) The issue may be tied to Hibernation.  I had left Xlights open last
evening along with several apps and placed the PC in hibernate.  Popped
back on this morning and could get the issue.  Terminated and now will not
repeat.
D) spent the morning learning how to record, so I will keep monitoring and
try to record the next time it occurs, noting if it was a return from
hibernation event.  I know when I had the issue originally I was leaving
Xlights open and hibernating so I could start right up the next evening
right where I left off.

Thanks so much for all the work you do on the program and the demos!  My
day job is automotive control algos and SW design so I get the: trying to
reproduce the issue from a very bad description and the 'left out info'
problem.  Doing it in your spare time....  it's not fun when you get paid
to do it......

Scott Feldmann  (Scott-SE-MI in zoom)

**Comment by scottfeld** [comment]
Was able to duplicate issue this evening.  Have been on PC for 3-4 hours.  Xlights shut down.  Started Xlights, opened the demo sequence.  control center wheel-ed to the 42 second point (spot I knew I have a phrase with space to move).  Cntrl left click drag to select the sentence, the words, and the phonics.  all turned purple.  kept control down clicked on sentence, it goes normal, click again and held to drag.  drag left and right, no issues.  released.  Then started hitting the right arrow on keyboard at around 30 seconds, around the 4th click, the movement stopped. the finger froze and no reactions,  @ about 39 seconds when the cursor goes from finger to circle the screen went opaque with a spinning blue circle icon.  the recorder did not seem to capture this.  You can notice the audio drop out around when the issue seems to occur.  After around 3 mins or so I got the 'not responding window / close or wait'.  

vid is too big to attach here even zipped.  putting on google drive in Xlight share/free effects/_NEW(upload here)/For Keith Crash Vid.    seemed a good spot to stash.

**Comment by scottfeld** [comment]
Was able to duplicate issue this evening.  Have been on PC for 3-4 hours.
Xlights shut down.  Started Xlights, opened the demo sequence.  control
center wheel-ed to the 42 second point (spot I knew I have a phrase with
space to move).  Cntrl left click drag to select the sentence, the words,
and the phonics.  all turned purple.  kept control down clicked on
sentence, it goes normal, click again and held to drag.  drag left and
right, no issues.  released.  Then started hitting the right arrow on
keyboard at around 30 seconds, around the 4th click, the movement stopped.
the finger froze and no reactions,  @ about 39 seconds when the cursor goes
from finger to circle the screen went opaque with a spinning blue circle
icon.  the recorder did not seem to capture this.  You can notice the audio
drop out around when the issue seems to occur.  After around 3 mins or so I
got the 'not responding window / close or wait'.

vid is too big to attach here even zipped.  putting on google drive in
Xlight share/free effects/_NEW(upload here)/For Keith Crash Vid.    seemed
a good spot to stash.

**Comment by AzGilrock** [comment]
Why are you holding control down to select the sentence?  I wrote most of that selection code and you can just deselect the timing track and drag a box around lyrics to select them.  Is there a change that requires control key now?  Then you said "kept control down clicked on sentence, it goes normal"  I don't get why are you doing that control click.

**Comment by scottfeld** [comment]
it may be user error?  Cntrl left click drag selected the entire block.
{from your email I learned that the cntrl was not needed for selection} You
need to release the left button to complete the selection.  If you want to
use the mouse to drag the block, with control depressed, clicking on any of
the selected items will deselect the item clicked on causing the need for
the second click to re-add the impacted item.  If you don't have the cntrl
held down, the click will deselect all the selection and only select the
item clicked on.  Playing with it right now, the selection with no cntrl
and cursor keys seems to work with no crash, but not able to use the mouse
to manipulate the block without the cntrl key. {the issue is random so one
test may not be conclusive} Every thing seems happy right now, nothing
seems to cause issues.

**Comment by AzGilrock** [comment]
Internally lyrics are really the same thing as effects when it comes to selection and movement.  The only difference is the timing tracks are used to determine the grid for selection so that's why its easier to just deselect the timing track and drag select a group of lyrics.  Anyways I thought the Shift key was used to move a block of selected lyrics/effects...

**Comment by AzGilrock** [comment]
I'm closing any really old crashes.  New crashes need a new ticket opened.
