### ISSUE TITLE
Clean up the starting point for drag-selecting nodes in Face Defintion edit

### ISSUE THREAD

**Issue by jjblodgett** [xLightsSequencer/xLights#2097]
While trying to mass edit face definition on a large canvas, I have discovered that the drag start position works great if you take the time to make sure you click in a cell first. If you don't click in a cell but just start "near" a cell and drag, it doesn't register where your cursor is in the grid and defaults back to wher. This results in some very weird selections. And if you're not careful, can result in the loss (or at least reversal) of previous selections.

I'm not sure what the architecture is behind the drag feature and whether it has to depend on the grid cell selection or not. I'm also not sure whether this is truly and enhancement or possibly a bug. But I can say it's very annoying and frequently a time waster to go back and fix something that didn't get selected correctly and then have to repeat the action from the same point so it results in a big time drain unless I slow the whole process down and make sure I click into a cell first. But that slows down the whole process since I have to slow down the speed of edits since large grids at small scale make it difficult to individually select cells. Dragging large sections is great but not as user-friendly when it requires the actions to be so precise.

**Comment by keithsw1111** [comment]
This is pretty much the behaviour of the underlying control. There is not a lot we can do about it.
