### ISSUE TITLE
File path breaks moving from Windows to Linux (xSchedule)

### ISSUE THREAD

**Issue by jholmes09** [xLightsSequencer/xLights#2115]
**Describe the bug**
After creating an xSchedule file in Windows, file paths break on the FSEQs when you transfer the show directory to linux.
file path window is completely white-space; it does not show the "broken" path. Any audio associated with the FSEQ also breaks, even after relinking the FSEQ in the linux environment.

**To Reproduce**
I have provided a simple show directory for reference.

1) Open this show directory in xSchedule on Windows 10
2) Confirm you see the FSEQ file paths for both the animation and musical sequence.
3) Confirm both sequences play on Windows (including audio for the musical sequence)
4) Copy/Paste the entire directory to a Ubuntu 18.04.4 Desktop
5) Open the show directory in xSchedule
6) Observe the FSEQ file paths are empty

**Expected behavior**
When I transfer a show directory from Windows to Linux, file paths should auto-repair provided all files are inside the show directory (i.e. /showdirectory/animation_sequence.fseq _or_ /showdirectory/sequences/animation_sequence.fseq)

**Screenshots**
![104876685_10156996793087260_8865002310780751797_o](https://user-images.githubusercontent.com/18503894/85761653-f8b89f80-b6e0-11ea-88a5-ffbbe8963890.jpg)

**Versions (please complete the following information):**
 - OS: Windows 10 and Ubuntu 18.04.4 Desktop
 - xLights version 2020.25

**Attachments**
[xLights Bug Testing Directory.zip](https://github.com/smeighan/xLights/files/4832650/xLights.Bug.Testing.Directory.zip)

**Comment by cybercop23** [comment]
Is this still an issue? If not, please close.

**Comment by derwin12** [comment]
This appears to be working as expected. It wont change file names or directories unless it can find the file. You can also add directories for it to search the .fseq files in. Review the log for exact issues with file directory pathing.

```
2024-03-29 15:35:07,945 140545087861632 log_base [DEBUG] File not found ... attempting to fix location (/tmp/Christmas) : E:\2023\ShowFolder3D\Audio\Shutup and Dance with me - Walk the Moon.mp3
2024-03-29 15:35:07,945 140545087861632 log_base [DEBUG] File not found ... attempting to fix location (/tmp/Christmas\Audio) : E:\2023\ShowFolder3D\Audio\Shutup and Dance with me - Walk the Moon.mp3
2024-03-29 15:35:07,946 140545087861632 log_base [DEBUG]    could not find a fixed file location for : E:\2023\ShowFolder3D\Audio\Shutup and Dance with me - Walk the Moon.mp3
20
```24-03-29 15:35:07,946 140545087861632 log_base [DEBUG]    We will not look for this file again until a new sequence is loaded.
