### ISSUE TITLE
Issue with no effect playback on Mac upon sequence load

### ISSUE THREAD

**Issue by bedawg10** [xLightsSequencer/xLights#2117]
I have an issue where the effects will not playback when I load a sequence unless I click on each effect individually. Once I click on each one they will play and display the preview model. However, every time I click on one they move ever so slightly, which I then have to make sure to hit cmd+Z to undo the move and ensure everything is where it's supposed to be. Hopefully, you guys can replicate that same issue. 

I'm running 2020.26.1 but noticed it became more prevalent back around March.

Running OS Catalina 10.15.5 (19F101)

https://www.dropbox.com/s/sarn88zzn5ugt7b/Screen%20Recording%202020-06-28%20at%201.57.01%20PM.mov?dl=0

**Comment by skydiveguy** [comment]
This happens to me and I just render all to resolve it.

**Comment by cybercop23** [comment]
Can this be closed? If so, please close it.
