### ISSUE TITLE
Bulk Edit of Face Definition not an option in Linux

### ISSUE THREAD

**Issue by Kosh42** [xLightsSequencer/xLights#2123]
**Describe the bug**
Inconsisitent application of bulk edit between xlights on different operating systems.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Sequence Window
2. Right click on a model row name containing singinf faces and select all effects
3. In Effect Settings right clicking on Face Definitions does not give a Bulk Edit option.

**Expected behaviour**
In 2020.26 for Windows you can right click on a row of a sequence containing singing face effects, right click on Face Definition in the Effect Setting window, and bulk edit the face definition in that line. This behaviour is missing in the Linux 2020.26 Appimage version. 

**Screenshots**
![Screenshot from 2020-07-08 22-30-37](https://user-images.githubusercontent.com/58401509/86972378-c3916000-c16a-11ea-9e19-3fd7afb58720.png)
![Screenshot from 2020-07-08 22-31-01](https://user-images.githubusercontent.com/58401509/86972381-c429f680-c16a-11ea-93fd-ffd193ee5e0a.png)

**Versions (please complete the following information):**
 - OS: Linux Mint
 - xLights version 2020.26 Appimage

**Additional context**
The XATW 2018 sequence mapped you your house will give a demonstration of this.

**Comment by MoulderUtes** [comment]
Hey I came across the same issue. Unfortunately Linux isn't too common so who knows if it will get fixed. There are probably better bugs to fix anyways.
