### ISSUE TITLE
Not being able to upload any sequences to my FPP through FPP Connect

### ISSUE THREAD

**Issue by JMHaro** [xLightsSequencer/xLights#2129]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am trying to upload all my sequences to one of my FPPs but it never gives any errors and looks like it completes, but no sequences are ever uploaded.

**To Reproduce**

(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Select FPP Connect
2. Ensre the desired FPP is selected (sometimes it's showing 3 of the same one and other times it's showing 4 of them).  I usually only pick one of them and have tried a different one each time.  There is an image in zip file that shows all 4 in the list.
3. Click upload and it goes though like it's uploading with no errors.
4. But nothing gets uploaded to my FPP.  And log file is showing a warning: Curl did not upload file:  0   Connection timed out after 2000 milliseconds
5. Here is a video hopefully you can get to it to see the issue:  https://www.dropbox.com/s/rgs4coh3ets8z6b/issue_2020-07-11_21-14-30.mp4?dl=0

**Expected behavior**
I expect that it uploads the selected files to the selected FPP's.

**Screenshots**
One screen shot in zip file shows when it's displaying 4 copies of the same FPP.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.28 64bit

**Additional context**

**Attachments**
[xLightsProblem20200711.zip](https://github.com/smeighan/xLights/files/4907918/xLightsProblem20200711.zip)

**Comment by derwin12** [comment]
@JMHaro So much has changed. Can you close this ticket?

**Comment by JMHaro** [comment]
Haven't had any issues with this since originally reported.  Didn't realize it was still open.  Closing ticket.
