### ISSUE TITLE
Disable scroll wheel when over dropdown options 

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#2146]
Can we please have the option to disable the mouse scroll wheel from scrolling through effect changes if the cursor is hovered over it? If you are on a window and scrolling up or down and it catches a drop down window everything in that window starts to scroll and you forget what setting used to be there and you cannot CTRL-Z, No big deal if you can't, just have to be more careful but can't seem to find a way to disable that. On macs it does not scroll over dropdowns which is nice, only scrolls to move the windows up and down.  

Thanks!!

**Comment by bchiaino** [comment]
I just noticed if you CTRL+scroll wheel down then the effect settings dont change as you scroll past but would b cool if it was opposite i think, not sure what the general consent would be but i know a few people have mentioned it

**Comment by Clyde-L** [comment]
Brian, I use the scroll wheel over  every drop-down.  it's become an integrated part of sequencing for me.  Also, many of my demos and videos show the use of the scroll wheel when changing settings.    As long as it is a preference addition where it can  be turned on and off, I'm okay with it.  It also seems as if you've found a work-around.

**Comment by bchiaino** [comment]
Hey Clyde! yes I can definitely see the use for it for a lot of users, would be cool to turn the feature on and off based on user preferences

**Comment by keithsw1111** [comment]
The challenge here is the scroll wheel behaviour is built into the framework. While it isnt necessarily impossible to prevent it it may not be or even worse it would behave differently om different operating systems as this sort of thing is often OS behaviour.
