### ISSUE TITLE
Add "FPP Proxy" capability to xSchedule

### ISSUE THREAD

**Issue by joeharrison714** [xLightsSequencer/xLights#2165]
**Is your feature request related to a problem? Please describe.**
I use xSchedule for scheduling, and my xSchedule box is currently the only thing on both my home and show network.

**Describe the solution you'd like**
I would love it if I could proxy xlights running on my main desktop to my controllers via xschedule, the same as one would using FPP.

**Describe alternatives you've considered**
Switch to FPP

**Additional context**

**Comment by cybercop23** [comment]
Pretty sure xSchedule now supports proxy. Can this be closed?
