### ISSUE TITLE
Automated AVI (or mp4) Creation of Video for Virtual Matrix

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#2181]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create a setting for matrices to be treated as a virtual matrix.  If this setting is enabled instead of fseq data being generated a video file will be automatically created and saved when the sequence is saved. 

**Describe alternatives you've considered**
This can be done manually already.

**Additional context**
My hope is that there can be more flexibility around these virtual matrices since there can be a millions of channels.  I'm asking for this because I think there can be a few benefits.
- Possibility of reducing render time could be another option but may result in confusion.  When I say this option I'm suggesting only render every other pixel or something as this will only be used when sequencing.
- When saving maybe the user can export just this model to 720p (I don't think xLights can do much higher than that today).
- FPP v4.0 & v4.1 seems to have a [minor] issue where if sending pixel data to the virtual matrix there is a black box around the screen.  Playing video files does not have this.  Both myself & Daryl E have observed this behavior.
- Perhaps add an option to include the associated video files when uploading to FPP.  Maybe an exercise for Kulp and separate feature request.
- I do see a complication if a user has multiple virtual matrices where there could be a filename collision.

**Comment by keithsw1111** [comment]
So while there is some concepts in here that are interesting I dont think you should be thinking of xLights as software to create 720P videos for vitual matrices ... it is fundamentally not designed for that. If you want high res videos I suggest you take a look at video rendering and animation packages. Now ... if it was to create lower resolution videos then maybe.

**Comment by MrPaulAR** [comment]
I would be happy with a low resolution video too.  It would still allow some automation for my rendering processes.

**Comment by cybercop23** [comment]
Paul, I'm so not on a quest to get you to close all your issues, but.. I know it is not as automated as you asked, but now this can be done with a Lua script. Will that work? 

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/61e3d451-d9a9-48e5-b9d4-3b36c10127a8)
