### ISSUE TITLE
Buffer Preset option enhancement request

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#2182]
Scott, was wondering is there a way to "update" a buffer preset?  For example, If I screw up the preset when saving it, and need to re-save it.  

Also,  can this list be reorganized?   + and - buttons to move presets up and down?

Finally, is there a way we can use a keybinding to instantly open the Buffer Size box instead of manually right-click+edit?  We can do this with most of the boxes in xLights, just curious :)  Thank you

Clyde

![image](https://user-images.githubusercontent.com/12719816/91086100-6bc88e80-e61c-11ea-836f-83da4bc484b8.png)

**Comment by derwin12** [comment]
@computergeek1507 Should I take your updates and put that code on this? small buttons to the right? Perhaps adding a delete/update/etc?

**Comment by computergeek1507** [comment]
IDK what code you are talking about

**Comment by derwin12** [comment]
This is not practical to change. It is alphabetically sorted by the wxWidgets code.
