### ISSUE TITLE
Display Elements enhancement

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#2183]
I'm sure the coding for this might be challenging.  Can the option to organize your VIEW in the Display Elements be added.  Seems we can click-drag the actual display elements.  Is this a property that could be imposed on the Views themselves?  Or perhaps a + / - button added to allow for that?

I understand the Views may be difficult to make changes to.

Thank you

Clyde

![image](https://user-images.githubusercontent.com/12719816/91086989-b8609980-e61d-11ea-8ebb-b289b04df50a.png)

**Comment by keithsw1111** [comment]
You mean +/- to move them up/down?

I am not sure how much value there is to sorting views? 

A Button implementation is pretty easy. Drag and drop is a lot of code that does not look like it would be used much.

**Comment by Clyde-L** [comment]
Yes, a +/-  to move them up/down.  I've had to create a number of view between layouts and somehow gotten off-track between multiple layouts.

Was only curious if the drag & drop code might "adapt" to that box as well since it was active in this dialog already.  Totally not necessary.

I find the same issue with organizing preset effect groups, they don't move up or down (I know different ticket, but a +/- button for preset group organization would be very helpful).
