### ISSUE TITLE
Threadripper Performance issues

### ISSUE THREAD

**Issue by zachcloutier** [xLightsSequencer/xLights#2191]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I just built a new pc with an AMD Threadripper 3960x and it is only using 4 threads and no more than 20% CPU usage. That by itself isn't really an issue but it is taking a significant amount of time more than my old pc with 3 year old hardware.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
Not sure how to reproduce as I think it is an issue regarding hardware utilization.

**Expected behavior**
A clear and concise description of what you expected to happen and why.
I would expect to get way faster render times as I am going from an 8700k with 6 cores to a 3960x with 24 cores. I also doubled my RAM to 128GB.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10 (2004)
 - xLights version 2020.31-34

**Additional context**
I have this issue with other software and I was told it is controlled in the software by both AMD and the software company.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
So remove variables. If the software and sequence are the same then the issue is in your hardware. Maybe look at drivers. If your sequence depends on shaders etc maybe look at video card drivers. The number of threads used depends on your sequencing style. The more you use groups the less effectively xLights uses multiple cores.

**Comment by AzGilrock** [comment]
One thing I've noticed over recent years is the number of cores is skyrocketing but the actual speed of each core is being lowered so they can control the heat.  xLights can use multiple cores but only when the rendering of the effects is mutually exclusive.

**Comment by AzGilrock** [comment]
I think the only solution is send all the developers machines outfitted with Threadrippers. ;)

**Comment by priemd** [comment]
Agree with Gil, but quick question, when you say 'all drivers are current' don't rely on windows update to tell you so, most video cards will work fine OOB without vendor drivers on a windows 10 brand new install, go to the vendors site and get their latest and greatest driver, don't rely on the base windows one if that is what you are doing.

**Comment by zachcloutier** [comment]
Yes, that is one solution it could get very costly though. Yes, I am aware of that with windows 10 I went right to AMD, Asus, and Nvidia to get all my drivers. My hardware is an Amd Thredripper an Asus motherboard and my GPU is a Quadro. According to the hardware manufacturers, I am up to data I downloaded all the latest and reinstalled them and they said my drivers are already up to date and windows is up to date as well.

**Comment by dkulp** [comment]
It generally depends on the effects used, where they are used, and what level of dependency there exists between models and such.    Effects on groups generally are not done much parallel if there are overlaps between models/channels between groups.   When it gets to a particular frame, if a group/model has a channel range overlap (shares a model or similar) with a group/model above it in the render order and that other group/model and that hasn't finished rendering that frame yet, the thread needs to block.  Some effects can use all the cores available while rendering that specific effect (plasma, butterfly, a few others) but most effects are single threaded.  Putting effects on the groups is definitely easy, but it does limit what stuff can be parallelized. 

In any case, you can try this sequence...   It should peg all the cores for the duration as it uses a bunch of things that are known to be really CPU intensive and are threaded where possible.   
[TestPlasma.zip](https://github.com/smeighan/xLights/files/5170373/TestPlasma.zip)

**Comment by zachcloutier** [comment]
Ok thank you for that information I tried that sequence and here is what it does.


https://drive.google.com/file/d/1y1OO7xVYm4NHs5Yo4r3sjAY609SK6HEI/view?usp=sharing

**Comment by dkulp** [comment]
So pretty much as expected...   There are 10 models so roughly 10 cores are pegged at near 100%.   The other cores are needed while actually rendering the effects and used when merging layers, but aren't for other things so likely cannot be fully used. 

I do find it interesting that my 8 core/16 thread MacBook Pro renders it in 48 seconds compared to your 59 seconds.   As I've said before, if rendering performance is critical, get a Mac.

**Comment by zachcloutier** [comment]
Ok, that makes sense. That is what I was seeing too with my other pc that is 6 cores 12 threads it renders my show faster than my new pc. I'll check what that one does on my old one but I expect similar results to what I have been getting with other sequences.

**Comment by Clyde-L** [comment]
> 
> 
> So pretty much as expected... There are 10 models so roughly 10 cores are pegged at near 100%. The other cores are needed while actually rendering the effects and used when merging layers, but aren't for other things so likely cannot be fully used.
> 
> I do find it interesting that my 8 core/16 thread MacBook Pro renders it in 48 seconds compared to your 59 seconds. As I've said before, if rendering performance is critical, get a Mac.

Considering my machine uses a r9 3900x  12 core/24 thread CPU, I thought I would try to render as well to see exactly where I fall in line.  Seems my final render time was 84 seconds.  It is indeed interesting to see the results.  Is it reasonable to say that xLights favors Intel CPU's?  The Mac renders much better, and I'm sure it has something to do with Dan running xLights on Mac hehe :)   The question I have is, can xLights be tuned to run better on a Ryzen CPU based system?

**Comment by computergeek1507** [comment]
Dan made some changes this morning and it took the render time from ~85 sec to ~55 sec on one of my sequences with videos (hardware video rendering off). My PC is only a Ryzen 3600.

**Comment by zachcloutier** [comment]
I just compiled the latest master and I think the changes Dan made really helped. It took the render time for my show Greatest Showman from ~505 SEC down to ~84 SEC. Also, the CPU was hovering around 94% the entire time.

**Comment by zachcloutier** [comment]
With some more testing, it seems to have helped my show but not the originals from the sequence venders. It cut the render time almost in half for most of the ones I was testing but the ones that were not faster are as fast as my old Intell PC. The test sequence didn't change at all it still renders in 59 SEC.

**Comment by Clyde-L** [comment]
> 
> 
> Dan made some changes this morning and it took the render time from ~85 sec to ~55 sec on one of my sequences with videos (hardware video rendering off). My PC is only a Ryzen 3600.

This is awesome news 👍 Not complaining of course.

**Comment by Clyde-L** [comment]
> 
> 
> With some more testing, it seems to have helped my show but not the originals from the sequence venders. It cut the render time almost in half for most of the ones I was testing but the ones that were not faster are as fast as my old Intell PC. The test sequence didn't change at all it still renders in 59 SEC.

As per the conversation above, when sequencing primarily in groups, the multithreaded performance may be inhibited.  This does make sense to me.  Would moving the effects to the individual props (off the group level) help that much?
