### ISSUE TITLE
Divide Effects like Divide Timings

### ISSUE THREAD

**Issue by jimswinder** [xLightsSequencer/xLights#2200]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Anyway to put in a "cut/divide" feature that would do it to an effect (like dividing a timing ) In my video editing software I can "cut" the video and then move it so I could put in a different effect or even no effect instead of having to drag and shorten the whole effect...especially if it is as long as the whole song.

**Describe alternatives you've considered**
having to drag and shorten the whole effect...especially if it is as long as the whole song.

**Additional context**
N/A

**Comment by cybercop23** [comment]
Doesn't look like this was implemented and unlkle it will be. Can it be closed?

**Comment by derwin12** [comment]
Verified .. this was previously implemented.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/03cbdc1f-c75c-44b8-a1e1-6cbb7b2551ad)
