### ISSUE TITLE
Default Controller Properties

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#2229]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create an option in the controllers tab (global &/or per controller) that allows for common default settings that'll be applied to new models automatically.  Especially useful when Full Control is enabled.  Two things that stand out are
- Global/Per controller: Default brightness
- Global: Default controller & port
-- I get this is odd but my use case is by default I put items on a null controller until I decide where I actually want them.

**Comment by keithsw1111** [comment]
I am not sure this works in an obvious way ... problem is the model is created before its associated with a controller ... how do i know when you assign it to the controller that i should change it ... maybe that model is the exception.
I particularly dont like the second suggestion as very few people would be set up that way.

**Comment by MrPaulAR** [comment]
OK, I understand that the 2nd case is likely a corner case just for me.

Maybe consider the brightness as a "model default" option in preferences instead of a controller default.

**Comment by cybercop23** [comment]
I had a PR that was closed to set the default to 30%. Still think that's valid.. or at least null it and turn it red to "force" the user to select something sensible.

Should this remain open?
