### ISSUE TITLE
FPP Connect List of available FPPs disappears

### ISSUE THREAD

**Issue by patdelaney** [xLightsSequencer/xLights#2239]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
FPP Connect List of available FPPs disappears after the 2nd time you open the FPP connect tool

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
Open XLights
Open a sequence
Render sequence and save it
go to Tools - FPP Connect
  I see all the FPPs on my network over 20 of them
Close FPP connect
go to Tools - FPP Connect
  I no longer see the FPPs

**Expected behavior**
A clear and concise description of what you expected to happen and why.
I should get the same list of FPP devices as before

**Screenshots**
https://youtu.be/0Kyvi7eJe9Y   

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.39

**Additional context**
I am running this on my laptop which also has Virtual box installed, that has configured my laptop with multiple IPs. I suspect that is causing the issue. When I run Check Sequence I get the following:

IP Addresses on this machine:
    192.168.56.1
    10.255.0.1
    10.10.10.1
    192.168.1.116
    172.28.128.1

192.168.1.116 is the hardwire connection.  I have configure this as the Force Local IP address in XLights

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file
![image](https://user-images.githubusercontent.com/8147459/94014881-c49d5b00-fd71-11ea-8f78-60ba83a908bb.png)
![image](https://user-images.githubusercontent.com/8147459/94014903-cb2bd280-fd71-11ea-82bc-25b8703bda72.png)

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked.

**Comment by patdelaney** [comment]
This is still an issue (for me) with 2020.40

**Comment by SaaltFam** [comment]
I have the same issue.
FPP connect indicates not responding, then shows only an FPP that is on the first switch.
It looks as though it cannot see FPP if it is on a second switch after the first.
Hope this helps

**Comment by rudybrian** [comment]
Still happening for me on 2020.42, but no issues on 2020.28

**Comment by MTBehnke** [comment]
I have the same issue.  The first time I use FPP Connect my three RPi's show up on the list.  If I try to use FPP Connect again none of my FPP's show up.  Likewise, if I try to Add FPP and enter their IP Address it doesn't find them.

If I quit xLights and restart, then it works again (once).

Using 2020.41 64bit-Windows version.  One FPP (the master) is connected via ethernet, the other two (remotes) are wireless.  All are on the same vlan and I have no problems accessing anything from my pc, tablet, phone, etc.

**Comment by jimtxas** [comment]
still an issue as 2020.48.  experience same exact results as noted above.

**Comment by rudybrian** [comment]
Are there any additional logs to gather or testing that we can do to help isolate/identify the issue?

**Comment by SaaltFam** [comment]
Forgot all about it now.
If I remember correctly if I had FPP open it did not work but if I closed FPP it was fine.
Now it is so close to show time I have 99.99% setup and not going to play until next year.
Cheers
Aaron

Aaron’s Phone

On 26 Nov 2020, at 7:16 am, Brian Rudy <notifications@github.com> wrote:

﻿

Are there any additional logs to gather or testing that we can do to help isolate/identify the issue?
