### ISSUE TITLE
Unable to download sequences/models

### ISSUE THREAD

**Issue by paulglavin** [xLightsSequencer/xLights#2241]
**Describe the bug**
After clearing download cache I can no longer Download Sequences/Lyrics or import a model.
An error message is displayed stating "Unable to access online repositories" or "Unable to retrieve Vendor Information"

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Click Tools - Purge Download Cache
2. Click on Tools - Download Sequences/Lyrics or Click on the Download model icon and then click on your layout

**Expected behavior**
Model Import Window or Download sequence window should be displayed

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10 and Mac OSX
 - xLights version 2020.38 and 2020.39

**Additional context**
A Captured PCAP shows a network call to https://nutcracker123.com/vendors/xlights_vendors.xml when trying to import a model. Browsing to this page returns a Bluehost webpage instead of downloading an xml file

**Comment by keithsw1111** [comment]
Yeah something funky is going on with the website. I have made changes that will come out in .40 likely tomorrow.

**Comment by doug97gxe** [comment]
anyone fixed this? i have the latest version and i'm having this issue

**Comment by paulglavin** [comment]
> anyone fixed this? i have the latest version and i'm having this issue

This was 2 years ago! Try purging your downloads cache from the Tools menu.

**Comment by keithsw1111** [comment]
Is this still an issue.
