### ISSUE TITLE
Importing Vixen doesn't include colors

### ISSUE THREAD

**Issue by SetMonkey13** [xLightsSequencer/xLights#2261]
When importing Vixen .tim sequences, none of the colors are imported.  Files from Vixen 3.6u3

**Comment by keithsw1111** [comment]
Need a sample sequence with one effect with the problem and need maybe a screen show showing what it should look like.

**Comment by SetMonkey13** [comment]
All the effects get imported with nothing checked for color (so defaults to white).  This includes the on effect, and single strand effect.  I know some of the effects from Vixen won't import correctly.
[Xlight Vixen import Bug.zip](https://github.com/smeighan/xLights/files/5324875/Xlight.Vixen.import.Bug.zip)

**Comment by keithsw1111** [comment]
Yeah ... going to need something simpler to start with ... just one or two effects in a sequence of known colours. Vixens file format is not trivial to reverse engineer.

**Comment by keithsw1111** [comment]
To be clear this is not a bug ... it was never implemented as I had no one to work with to get it right.

**Comment by SetMonkey13** [comment]
Ah, got it.  I assumed that with some of the posts I saw of people shifting from Vixen, that it was implemented.  A very small subset of people use it and only for a brief moment.
Hopefully this file is closer to what your are looking for.
[Xlights Vixen Color.zip](https://github.com/smeighan/xLights/files/5350363/Xlights.Vixen.Color.zip)

**Comment by keithsw1111** [comment]
I have added some colour handling for the simple effects. The chase does not seem to come in with red as the colour ... I dont know why. I have followed their colour conversion algorithm and it just generates white for me.

**Comment by cybercop23** [comment]
@SetMonkey13 can this be closed?
