### ISSUE TITLE
3D OBJ crash Ubuntu 20.04

### ISSUE THREAD

**Issue by mghaff007** [xLightsSequencer/xLights#2272]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Not sure what is happening. 

**To Reproduce**
1. Open Xlights app.
2. Select Layout Tab.
3. Select Preview 3D box.
4. Select 3D Objects tab in Layout.
5. Select Mesh 2.
6. Right Click Delete.
7. Crash.

**Expected behavior**
Expecting it to just delete.

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - xLights-2020.42-x86_64.AppImage
 
 -Gnome 3.36.3
 -Windows X11
 -64bit OS
 -memory 15.5 GiB
 -Processor Intel® Core™ i5-3230M CPU @ 2.60GHz × 4 
 -Graphics GeForce GT 730M/PCIe/SSE2 / GeForce GT 730M/PCIe/SSE2
.

**Attachments**
Crash Report
[xLights_dbgrpt-23402-20201007T080416.zip](https://github.com/smeighan/xLights/files/5344518/xLights_dbgrpt-23402-20201007T080416.zip)

Screen Shot
[Screenshot from 2020-10-07 18-24-30](https://user-images.githubusercontent.com/33535234/95398434-5a38fe80-08cb-11eb-9775-b2372d26a067.png)

**Comment by fone626** [comment]
This also happens on all my computers.  I should have reported this problem myself a long time ago, but I have just learned to live with a hand full of 3d objects that are permanently trapped in my layout.
I sure would be nice to be able to delete them though.

**Comment by cybercop23** [comment]
can this be closed? i don't have access to a linux based install so i can't test.
