### ISSUE TITLE
Port naming 

### ISSUE THREAD

**Issue by dszoka** [xLightsSequencer/xLights#2274]
I would like the ability to add a name to ports when in the Visualiser.

I believe it would make it easier for people with large port counts to remember where each one is .. fence L, Fence R, outhouse etc 

![4BE878FF-69DA-410E-AAB3-2CA0E01EB8EF](https://user-images.githubusercontent.com/42435862/95432086-ea457980-0999-11eb-8731-a46f63d24e1f.jpeg)

**Comment by keithsw1111** [comment]
The problem is the port object is really ephemeral ... it does not get save anywhere or exist ... hence why you can get spurious ones created when you add models with lots of strings and dont have enough ports for them.
