### ISSUE TITLE
Jukebox mapping to keyboard

### ISSUE THREAD

**Issue by networx** [xLightsSequencer/xLights#2280]
I would like to control the jukebox buttons from a streamdeck.

The streamdeck can be programmed to send a key press to the system. So if each jukebox button could be mapped to a custom keyboard press or combination of presses that would be great. For example: set jukebox button 1 to be triggered on the keypress of Alt-F1. Set jukebox button 2 to be triggered on the keypress of shift-alt-3. Each jukebox button would let you set the keypress that it would be triggered from.

Or a mode that could be entered where the jukebox would respond to keypresses A through Z for 1 through 26. Then you could exit that mode with a press on escape.

**Comment by keithsw1111** [comment]
You could put xSchedule in the way. xSchedule buttons can be mapped to keys and xSchedule buttons can press xLights jukebox buttons ... it is kind of convoluted but it could be done.

**Comment by networx** [comment]
Thank you. I will try that out.

**Comment by computergeek1507** [comment]
Are you triggering the jukebox buttons from xLights or xFade?
