### ISSUE TITLE
Linux Appimage - not window close buttons

### ISSUE THREAD

**Issue by Kosh42** [xLightsSequencer/xLights#2294]
**Is your feature request related to a problem? Please describe.**
Frustrating that there is no close window x in the top right of some windows in the Linux Appimage version, ie on the wiring view. You have to ALT + F4 or right click on the top bar to close the window. I only found out that after having to kill a few PIDs.

**Describe the solution you'd like**
I'd like a close window x in the top right of the windows.

**Describe alternatives you've considered**
ALT + F4 or right click on the top bar to close.

**Additional context**
![no close window option linux](https://user-images.githubusercontent.com/58401509/96184262-23e52a00-0f30-11eb-8996-b742bd619461.png)

**Comment by derwin12** [comment]
Cant duplicate this in my linux. Perhaps corrected along the way?
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/5c3b2e4e-d9c3-455f-bed9-dc793091ae29)
