### ISSUE TITLE
Batch render, Option to ignore backups?

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#2296]
Is there a way to add the ability to ignore the backup files on batch rendering or give us the ability to "say no or yes to all" when it prompts us that the backup is newer then saved?

Reason I ask is I have roughly 30 sequences and if you leave a sequence open for a little or while its rendering it makes a backup file which is great BUT then you go to batch render and walk away, come back an hour later and it never got past the 3rd render because a popup came up saying the backup is newer

I get the point in it and its a great feature but I know the backup is usually not the one I want, its just that I saved the sequence and left it open so it created a newer backup file 

thanks!!

**Comment by keithsw1111** [comment]
It should only backup if something changed. If the sequence is unchanged the auto backup does not actually trigger.

**Comment by derwin12** [comment]
The preference seems to handle this..
