### ISSUE TITLE
Expand all layers with effects

### ISSUE THREAD

**Issue by tmeyermn** [xLightsSequencer/xLights#2305]
**Is your feature request related to a problem? Please describe.**
If I want to disable rendering on everything except for some select effects I have to manually go through and open all the groups and sublayers which is prone to human error.  Also, when copying sections to different locations on the timeline it would be nice to have this feature so you don't miss some of the effects when selecting.

**Describe the solution you'd like**
A right click menu option similar to "Show All Effects" 

**Describe alternatives you've considered**
Re-implement the "Show All Effects" function to show all layers that have effects on them.

**Comment by derwin12** [comment]
This is the current implementation. It shows all layers that have effects.
