### ISSUE TITLE
FPP Virtual Matrix Auto Layout

### ISSUE THREAD

**Issue by darylc** [xLightsSequencer/xLights#2307]
**Is your feature request related to a problem? Please describe.**
If you have a FPP controller configured in xlights as a Virtual Matrix with Auto Layout turned on and you assign more than 1 Virtual Matrix to that controller, xlights assigns both Virtual Matrices to the same start channel.

**Describe the solution you'd like**
I would like to specify the order of the Virtual Matrix chaining in the visualiser, however the visualiser is disabled for this controller combination.

**Describe alternatives you've considered**
If you turn off Auto Layout you can manually chain, however you cannot then use Auto Size, which is highly desirable.

**Additional context**
In this case I am using 1 Virtual Matrix on fb0 and 3 Virtual Matricies on fb1 on the raspberry Pi

**Comment by derwin12** [comment]
Darylc, This is an old ticket and perhaps the code has changed, but I am not seeing the same issue.  Can you still do this?
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/c1d9a5a4-1fe7-4487-8b42-afe663e97a43)
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/028fbdf1-bddf-4aaf-9d5d-1f57ab768319)

If I put them both on the same port .. it looks correct as well.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/00a57f16-7e4e-4c69-9850-48c01f6ede58)

**Comment by darylc** [comment]
@derwin12 this is so old I'd just close it out
