### ISSUE TITLE
Singing Faces- Sort Node ranges

### ISSUE THREAD

**Issue by Poporacer** [xLightsSequencer/xLights#2322]
**Is your feature request related to a problem? Please describe.**
When configuring the node ranges in the Face Definition, sometimes you need to define several ranges and it is easy to overlap the ranges for one phoneme. I don't think this will generally cause a problem, but if after saving, it would sort the ranges in order, it would be easy to see the overlaps and combine the definition into a more efficient definition

**Describe the solution you'd like**
When a face definition is saved, sort the node ranges.

**Describe alternatives you've considered**
Just do things as status quo

**Additional context**
Thanks for all the hard work you guys out into this!

**Comment by cybercop23** [comment]
Implemented and merged to master. Please test the nightly (preferred) or in the next version.
