### ISSUE TITLE
Strange Visualizer bug.

### ISSUE THREAD

**Issue by TxBillbr** [xLightsSequencer/xLights#2325]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Using the visualizer to drop an 8-string matrix fails to show the first string of the 8. However source box shows 8 strings with string-1 on the correct port. This occurs only when auto-layout and auto-download are not selected for the controller.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Configure Matrix of 8 strings with 3 strands. Total of 99 nodes per string.
![image](https://user-images.githubusercontent.com/44479016/98322374-de56d280-1fac-11eb-8cdb-6732a6fd363a.png)

2. Use the visualizer to assign the model by dragging the first string to an appropriate port (21 in my case).
3. Visualizer shows strings 2-8 with nothing on port  21. Note the info box above shows the model on port 21.
![image](https://user-images.githubusercontent.com/44479016/98322542-460d1d80-1fad-11eb-9133-6da2d7cd36c9.png)

**Expected behavior**
This has recently occurred. I believe 2020.43 did not exhibit this behavior

**Screenshots**
See above.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.46

**Additional context**
![image](https://user-images.githubusercontent.com/44479016/98322704-b320b300-1fad-11eb-8844-95f9a9f27604.png)
Hide box is unselectable. Models are in both the source column and the destination column.

I did a bit of work to try and determine what was different when everything was working ok and found the trigger for the problem. I found that if the controller did not have auto-layout and auto-download selected, it would exhibit the issue. Selecting those two boxes cause the visualizer to behave correctly.
![image](https://user-images.githubusercontent.com/44479016/98323043-81f4b280-1fae-11eb-9d79-9aa6dd86ae86.png)

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
You didnt include your files but I would bet the problem is the model does not have its start channel within the range of the controller channels ... thus the string wont show. Normally folks would drag a prop on/off a port which then triggers the auto layout. Until then I think it is chopping off your strings.

**Comment by TxBillbr** [comment]
Keith, which files would be useful? I will be happy to add them. This bug is not a show stopper, but did cause me a fair number of hours head-scratching. I did use the drag and drop for the props. My confusion at this point is around the implication if auto layout. I'll go read the docs some more in order to better understand what it controls.

**Comment by keithsw1111** [comment]
Package an empty sequence ... it will include everything we need.
