### ISSUE TITLE
Built-In Circle model doesn't render properly when layers are used.

### ISSUE THREAD

**Issue by ImaStinker** [xLightsSequencer/xLights#2338]
NOTE: SEQUENCE & LOG FILE ATTACHED.
[Circle Model Tests.zip](https://github.com/smeighan/xLights/files/5527264/Circle.Model.Tests.zip)
[Circle Model Tests -- xLightsProblem -- Logs.zip](https://github.com/smeighan/xLights/files/5527268/Circle.Model.Tests.--.xLightsProblem.--.Logs.zip)

**Describe the bug**
Built-in circle model with "n" layer concentric rings does not render effects as expected.  
I was watching the training videos and saw that the Circle model supports layers, so you can make wreaths with concentric circles.  I tried to replace my custom 3 ring wreath model with the built-in circle, but the rendered effects on the new model were inconsistant with the existing custom model.  Considering that it could be an issues with how the models are built, I tried to eliminate that variable.  So I exported the built-in circle model to a csv file, then turned around and imported it as a new custom model.  Then I defined the three sub-model rings to match the built-in model.  Dropping the same effects over both models yields different effect rendering.

Ring Specification:
![image](https://user-images.githubusercontent.com/74269284/98877458-c87a5f00-243d-11eb-933d-c95e411cf6a7.png)

**To Reproduce**
3LayerConcentricRing
![3LayerConcentricRing](https://user-images.githubusercontent.com/74269284/98876541-c1525180-243b-11eb-8c13-694b7e970d57.JPG)

3CircleWreath
![3CircleWreath](https://user-images.githubusercontent.com/74269284/98876588-dc24c600-243b-11eb-9ebd-66d17acda72f.JPG)

[3CircleWreath.zip](https://github.com/smeighan/xLights/files/5527428/3CircleWreath.zip)
subModel "Ring 1" "103-132"  (inner ring)
subModel "Ring 2" "59-102"  (middle ring)
subModel "Ring 3" "1-58"     (outer Ring)

**Expected behavior**
I've included a packaged sequence that shows the expected behavior (3 Circle Wreath) vs the inconsistant behavior (3 Layer Concentric Ring).  Again, the built-in model does not appear to be sequencing according to it's wiring diagram.  I'm showing 4 identical effects in the attached sequence.

**Screenshots**
Front view wiring diagrams of both models.
![3LayerConcentricRing](https://user-images.githubusercontent.com/74269284/98879718-67558a00-2443-11eb-9c21-9602e9a3f10d.png)
![3CircleWreath](https://user-images.githubusercontent.com/74269284/98879727-6ae91100-2443-11eb-8859-25a508600234.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [e.g. 2022.47]

**Additional context**

**Comment by deplanche** [comment]
This isn't a bug, it is how xlights works with the different types of models.  The circle model isn't actually laid out as a circle "inside" xlights, but rather a matrix - if you look at the node layout for it, you'll see what the looks like.  The custom model is actually laid out like a circle - again look at the node layout for that to see the difference.  This difference is the reason that the same effects look different.

If you wanted to get the effects on the circle model to look more like the custom model, change the render style on the circle model from "default" to "per preview."

**Comment by ImaStinker** [comment]
Let me see if I get this right. The internal models are designed to be played on a matrix, period.  If I don't have a matrix, and want to built an actual prop (star, wreath, tree, candy cane, arch, etc) then I have to change the render-style "on the model".

However, there isn't really a render-style that is associated with a model, i.e. nothing on the layout tab where the models are defined.  There is only the "Layer Settings" on the Sequencer tab.  The only way this works like you are suggesting, is if I click off the "reset panel when changing effects" and switch render-style to "Per Preview".  Only then laydown the all the effects for that model's specific row/layer.  If I don't, then I have to manually change **every** effect for that model.  What's more, the layer-settings are not sticky to the particular layer.  They apply equally to any layer and cell that I select.  I can't setup certain layers with particular layer settings (render-style=per preview), and other layers with different settings (render-style=default) then expect those settings to stay as I jump back and forth between the layers to sequence the different models on those layers, right?  I mean "Layer Settings" is **really** per effect, not model.  Or am I missing something?

Thanks.

**Comment by keithsw1111** [comment]
Layer settings is per effect ... because it provides flexibility but there are ways around this. You can change any model to default to per preview by putting it into a group as groups always default to per-preview ... but also let you set the default.
You other option is bulk edit. Select the effects you want to change. Right click on the setting you want to change and select bulk edit.

Internal models are not designed to be played on a matrix. All render buffers are however a matrix ... its just a question of how the nodes get placed in a matrix. Circle models default to each layer as a line in a matrix because it is a useful buffer style for some effects and per preview is always there for people that want per preview ... so the best of both worlds ... now i say this but i will also admit xlights is not consistent ... just see the star model as an example.

So while it is inconsistent it also isnt going to change ... because doing so would break thousands of users and tens of thousands of sequences ... and we wont win any friends doing that ... particularly in November.

**Comment by ImaStinker** [comment]
OK, got it.

Now, as to "... its just a question of how the nodes get placed in a matrix. **Circle models default to each layer as a line in a matrix because it is a useful buffer style for some effects** and per preview is always there for people that want per preview ..."

Where is this information located?  It's certainly not in the node layout, which shows one long string.
I mean, if a person wanted to build a layered circle, and use the Built-in model with Default render-style then they would have to know that the physical prop would need three strings, wouldn't they?

That's the last question I have.  And really, thanks for the support.

**Comment by computergeek1507** [comment]
The node layout dialog itself display the default render buffer. All models have a default render style that are a 2d grid and the node layout dialog displays this grid. The long line you see, is the a 1 high by circle size length grid that is the default render buffer. If you want a custom render buffer, create a submodels with the desired layout.

**Comment by computergeek1507** [comment]
The built-in default buffers are designed for specific reasons. The circle model is a single line so bars effects/single line effects spin around like a spinner. The spinner model is also a 2d grid that will cause it to spin with those effects.

**Comment by computergeek1507** [comment]
This video explains the render engine in detail. http://videos.xlights.org/watch.php?vid=e8f8b522f
