### ISSUE TITLE
Screen Jumping

### ISSUE THREAD

**Issue by HonScottHMcCoy** [xLightsSequencer/xLights#2340]
When editing the properties window in Layout -> Models, it jumps around. For example, I scroll down to brightness and click the checkmark. That jumps the properties back to the top. I have to then scroll down to find the brightness again and then enter the value.

Can it be made to not jump or adjust the focus/location of the properties window when editing fields? 

Thank you.

**Comment by keithsw1111** [comment]
Are you using the latest ... I thought this was fixed in .47?

**Comment by HonScottHMcCoy** [comment]
I have v2020.47. Still jumps.

**Comment by cybercop23** [comment]
Seems fixed (sort of). It does brng the checkbox to the bottom of the screen and need to scroll one line down to set it.

**Comment by derwin12** [comment]
Lets take another look into this...

**Comment by derwin12** [comment]
Seems fine .. it moves a line or so but still keeps it visible.
