### ISSUE TITLE
xLights Crashes When Selecting Protocol Type

### ISSUE THREAD

**Issue by dakingus** [xLightsSequencer/xLights#2347]
**Describe the bug**
When trying to select the renard protocol on Layout-> Controller Connection-> Protocol via keyboard entry, xLights crashes.  

**To Reproduce**
1. Go to Layout
2. Select a model
3. Scroll down to Controller Connection
4. Click in Protocol field to activate it
5. Click the drop down arrow to activate drop down menu
6. Type 're' to select renard
7. xLights crashes

**Video Of Issue**
Attached to this bug report

**Expected behavior**
Renard protocol is selected without xLights crashing

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Macbook Air, 1.3 GHz Intel Core i5, 8 GB RAM
 - MacOS 10.14.5 (18F132)
 - xLights version  2020.47.2

**Additional context**
Brand new xLights setup.  No sequences created yet.  xLights on external monitor. 

**Attachments**
- Crash log attached to this bug report

[Error Info.zip](https://github.com/smeighan/xLights/files/5551286/Error.Info.zip)

**Comment by keithsw1111** [comment]
@dkulp may need to look at this. From the trace in the crash log there is no obvious xLights code causing the crash and similar actions on windows does not seem to crash it. It may be OSX specific.
