### ISSUE TITLE
FPP Connect

### ISSUE THREAD

**Issue by AleXthePunK** [xLightsSequencer/xLights#2355]
Feature request, not a bug

FPP Connect: You can right click on the sequences and clear selected. The request is a right click option on the controllers to clear all of the check marks for those

Thank you

**Comment by cybercop23** [comment]
@derwin12 sometimes I wish I had this....

**Comment by cybercop23** [comment]
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/ff8c6ec3-0503-474e-8721-c200012795db)
