### ISSUE TITLE
6 second delay when playing a sequence

### ISSUE THREAD

**Issue by rpFalcon** [xLightsSequencer/xLights#2356]
Currently running xLights 2020.46 under Windows 7.

**Describe the bug**
I have a sequence I created in a test folder and it is working as expected. Earlier today I imported the models, etc into my show folder. I opened the sequence and rendered it. When I play it there is about a 6 second delay before the first light is turned on and it is somewhat erratic..

This issue is a duplicate from the same problem I had a month ago.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/5569930/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
You are using a seriously large number of multicast universes ... has this number changed recently ... generally we would not recommend large numbers of multicast universes. Is there a particular reason you have gone this way.

**Comment by rpFalcon** [comment]
I recently changed the matrix to unicast 127.0.0.1 and get the same results.

Something got wonkey a while back and I recreated the configuration and was not thinking the matrix has always been unicast.

Here is what my networks look like today.

[Networks.zip](https://github.com/smeighan/xLights/files/5591724/Networks.zip)

**Comment by keithsw1111** [comment]
It would be good to get onto zoom at some point to troubleshoot this.

**Comment by cybercop23** [comment]
Is this still an issue? If not, please close.
