### ISSUE TITLE
v2020.48 Controllers tab a falcon controller shows a "Unused Port Brightness" option but it changes all ports.

### ISSUE THREAD

**Issue by HolidayLighting** [xLightsSequencer/xLights#2363]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
v2020.48 Controllers tab a falcon controller shows an "Unused Port Brightness" option. This actually changed ALL ports and why would you want to change the brightness of unused ports?

**To Reproduce**
1. Go to 'Controllers Tab'
2. Change 'Unused Port Brightness' for a falcon controller
3. Upload to Falcon Controller
4. Falcon controller shows all ports at the brightness you set not "Unused"

**Expected behavior**
What is the intension of this, Why would you change the brightness for unused ports?

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10 x64
 - xLights version 2020.48

**Additional context**

**Attachments**

**Comment by AzGilrock** [comment]
Ever plugged a connector into the wrong spot?  I have props that can draw 15 amps at full power so I know I program unused ports low for safety.

**Comment by computergeek1507** [comment]
The "unused brightness" is better described as the "unset brightness" or "default brightness". If you have xLights full control selected, this value will be used if no brightness is set for the model on the port.

**Comment by HolidayLighting** [comment]
@AzGilrock That does make sense but why not just set all ports to a brightness not differentiate between Used and Unused? Currently, it sets all ports to the value on a Falcon board,

@computergeek1507 Yes for what it does currently I agree it should be renamed to be more clear which is why I wrote this up last night.

**Comment by AzGilrock** [comment]
I'm just telling you why I would change the brightness for unused ports.  I configure my controllers manually which eliminates a ton of settings in xlIghts I don't need to muck with.

**Comment by keithsw1111** [comment]
If it is setting all then its a bug ... it is only meant to be the default for unused ports and the rationale Gil explains.

**Comment by HolidayLighting** [comment]
> If it is setting all then its a bug ... it is only meant to be the default for unused ports and the rationale Gil explains.

I'm fine with that, should there be a setting for used ports as an easy way to set them all via the controller?

**Comment by cybercop23** [comment]
@HolidayLighting  is this still an issue?
