### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by HonScottHMcCoy** [xLightsSequencer/xLights#2369]
v2020.49 64bit
Windows 10

FPP Upload dialog box is too small. Button cut-off.
![image](https://user-images.githubusercontent.com/33946864/100397068-80e2fe00-300d-11eb-9594-98220c5ebd4f.png)

**Comment by derwin12** [comment]
@HonScottHMcCoy Is this still an issue? Can you close the ticket?
