### ISSUE TITLE
2020.48 FPP Discovery "not a supported FPP instance"

### ISSUE THREAD

**Issue by TechplexEngineer** [xLightsSequencer/xLights#2370]
**Describe the bug**
Recently updated, show is running, attempt to us fpp connect, no FPP instances are discovered.

**To Reproduce**
1. Show is running playlist via scheduler
2. Tools > FPP Connect
4. See no FPP instances listed

**Expected behavior**
FPP instances should be listed.

**Screenshots**
<img width="1552" alt="Screen Shot 2020-11-26 at 7 32 11 PM" src="https://user-images.githubusercontent.com/175873/100398794-3158fe00-301e-11eb-85de-07016ff6211d.png">

**Versions (please complete the following information):**
 - OS: Catilina 10.15.7
 - xLights version 2020.48
- FPP see screenshot for full list
<img width="1321" alt="Screen Shot 2020-11-26 at 7 36 52 PM" src="https://user-images.githubusercontent.com/175873/100398957-dffd3e80-301e-11eb-8816-0d471167f3bd.png">

**Additional context**
Relevant snippet from the xlights log:

```
2020-11-26 19:29:34,425 4565695936 log_base [DEBUG] RecalcStartChannels takes 49ms.
2020-11-26 19:29:36,700 4565695936 log_base [INFO] FPP Discovery - 10.10.0.20 is not a supported FPP Instance
2020-11-26 19:29:36,700 4565695936 log_base [INFO] FPP Discovery - 10.10.0.30 is not a supported FPP Instance
2020-11-26 19:29:36,700 4565695936 log_base [INFO] FPP Discovery - 10.10.0.113 is not a supported FPP Instance
2020-11-26 19:29:36,700 4565695936 log_base [INFO] FPP Discovery - 10.10.0.22 is not a supported FPP Instance
2020-11-26 19:29:36,739 4565695936 log_base [INFO] Scanning folder for sequences for FPP upload: /Users/techplex/projects/lightshow/sequences
```

It looks like the code to filter FPP instance has recently changed, I haven't recompiled to add logging to see what condition is causing the system to think the FPP instances are not supported
https://github.com/smeighan/xLights/blob/8f83edce4dcfa1f75a16637bedbedb45f8201de6/xLights/controllers/FPP.cpp#L2652

**Comment by TechplexEngineer** [comment]
It seems that even now when the show has ended, FPP connect is registering all of the FPP instances as "not a supported FPP Instance"

**Comment by TechplexEngineer** [comment]
I clicked the "add FPP" button and entered the IP address of 10.10.0.113 now my FPP instances are listed

**Comment by Dwaynet86** [comment]
i can verify this.
it happens after opening fpp connect more than one time in xlights. if you restart xlights it discovers all fpp instances again on the first run of fpp connect.

**Comment by TechplexEngineer** [comment]
@Dwaynet86 how many FPP instances do you have and what are their versions?

**Comment by Dwaynet86** [comment]
single fpp instance was 3.5 has been updated to 3.6 with same results
![nonefpp](https://user-images.githubusercontent.com/51888733/101109048-94f1a700-359b-11eb-9e7d-e316cd32b82c.png)
![onefpp](https://user-images.githubusercontent.com/51888733/101109051-958a3d80-359b-11eb-8e32-9a8344587c53.png)
