### ISSUE TITLE
High Resolution monitor issue

### ISSUE THREAD

**Issue by MrRyanM** [xLightsSequencer/xLights#2374]
I use a 4k monitor, and when you hover over an icon, the tool tip doesn't show where it should...see attached photo
<img width="1080" alt="2020-11-28 22_17_10-2020-11-28 22_12_37-xLights (Ver 2020 49 64bit) November 24, 2020 png @ 200% (Cu" src="https://user-images.githubusercontent.com/55702933/100533253-e2e76300-31c7-11eb-9cee-95cf5aea3a85.png">

**Comment by myhrmans** [comment]
What OS are you running? What version?

**Comment by MrRyanM** [comment]
Windows 10 Pro 20h2

**Comment by cybercop23** [comment]
is this still an issue? if not, please close.

**Comment by MrRyanM** [comment]
no it is working for me now. thank you
