### ISSUE TITLE
Upload to PixLite 16 fails

### ISSUE THREAD

**Issue by patdelaney** [xLightsSequencer/xLights#2379]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I'm trying to configure my PixLite16 for the Pixel-Lab (Zoom room troubleshooting) when I try to Upload output, I see in lower left side of xlights Advatek: Output update Failed, unable to connect.
![image](https://user-images.githubusercontent.com/8147459/100615272-fa644000-32dc-11eb-947b-9eb0b7db177b.png)

**To Reproduce**
Create a new show directory for this project.
Add Pixlite16 to controllers section, (this is the only controller for this test)
manually add 5 universes
Create a megatree prop. 16 legs 50 nodes (16 ports)
go to visualizer and drag tree over to port 1
Click upload output

![image](https://user-images.githubusercontent.com/8147459/100615686-8ecea280-32dd-11eb-9792-9673a59b84a4.png)

![image](https://user-images.githubusercontent.com/8147459/100615747-a9a11700-32dd-11eb-937f-e70689078e9c.png)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
Windows 10
Xlights 2020.51
Pixlite16 version 1.4.14 (latest version)

**Additional context**

**Attachments**
https://drive.google.com/file/d/13B3H4kQjuqP4B6eHjgoaMSXdugt1X_wQ/view?usp=sharing

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
@patdelaney don't think this is still an issue. Closing, and feel free to reopen if any issues.
