### ISSUE TITLE
Show divider line on FPP connect and retain window size

### ISSUE THREAD

**Issue by jaydonoghue** [xLightsSequencer/xLights#2382]
2 items in this request:
1) Retain window size of FPP connect when reopening it. 
2) Show the horizontal divider line between controllers and sequences

This a minor usability improvement. Each time I open the FPP connect window, I wind up dragging the corners to make the window bigger and hunting for the divider to make the FPP instances section taller. It would be ideal if the window size was retained each time the tool was brought up

The attached screenshot shows the window with my cursor over the divider line - as there is no displayed line, its not always easy to find it.
![image](https://user-images.githubusercontent.com/17279178/100906243-f9770e00-3496-11eb-92f1-ad1844b712b5.png)

**Comment by cybercop23** [comment]
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/9fd443d3-6150-47cc-a8dc-33e86f3dfd00)
