### ISSUE TITLE
Change Label Name of Layers

### ISSUE THREAD

**Issue by craskul** [xLightsSequencer/xLights#2388]
**Is your feature request related to a problem? Please describe.**
For organizational purposes, it would be nice to be able to change the label of a layer.

**Describe the solution you'd like**
I'd like to right-click or double-click on the layer label and be able to type in a new name

**Comment by keithsw1111** [comment]
Layers dont have names ... they just have numbers.

**Comment by craskul** [comment]
I know. I think it would be useful to have the option to be able to rename some of the layers.

**Comment by keithsw1111** [comment]
Give me a use case example?

**Comment by craskul** [comment]
The use case would mainly be for picture or video effects so that one could keep the same or similar images on the same layer and be able to quickly see which layer to put it on. This would help when revisiting an older sequence to modify. 
<img width="698" alt="screenshot1" src="https://user-images.githubusercontent.com/4003059/101202055-95328680-361d-11eb-8df0-520f9de62676.png">

In this screenshot, you can't tell which layer has which image on it so it takes time to figure that out. If layer 7 was labeled Sky Line, Layer 8 was reindeer, layer 9 was Santa, it would be useful.

I understand that it may not be as useful for other effects that build on each other, but in that case, one could label a mask layer or something like that.

**Comment by cybercop23** [comment]
Should this remain open? Seems very unique/one case to me.
