### ISSUE TITLE
Random Pixel color in effects

### ISSUE THREAD

**Issue by dvynsoul** [xLightsSequencer/xLights#2392]
I am seeing random pixel colors show up and in some cases the pixel stays there for a certain amount of time.
So far I have been able to notice it in Shapes and in Spiral effects.

(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a shape like a heart or layer 2 opposite direction  spirals.
2. In your Layer settings, if the blur effect is set to 1. In the heart you will have a single pixel that stays longer than all the rest.
In the spiral effect you will notice it coming down from the top. 

The only way I have been able to remove the random pixel is by setting the Blur to either 2 or 3.

![image](https://user-images.githubusercontent.com/75535559/101247096-3b958f00-36e5-11eb-854c-d09127851ee9.png)

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, 64 bit
 - xLights version 2020.52 64 bit

**Additional context**
I have also noticed the same issue in 2020.51 I don't know of previous version since I just started learning Xlights coming from LOR.

**Comment by keithsw1111** [comment]
This is generally overlapping channels or data layers. Without a sequence we cant really check it. Best option would be pop into the zoom room and get someone to take a look at it for you.

**Comment by dvynsoul** [comment]
Thanks for the quick response. I went throug the check sequence and found several warnings. I went ahead and corrected them but it didn't change the random pixels. I finally started going through the live sequence with lights on and checked on which effects the random flickering was happening. I noticed all the places I had random pixel firing there was either a ramp on the brightness curve or a fade in time from the layers menu. As soon as I set them to 100 the random pixels were gone. Note that this is an LOR Pixie 8 controller and with the LOR software this doesn't happen on ramps or fades so I don't believe it is a power issue on the controller.

**Comment by keithsw1111** [comment]
Pixie controllers are junk controllers. You are lucky they work at all.

**Comment by dvynsoul** [comment]
If it's junk that's another story but it doesn't do the flickering with the LOR software running. When I converted the LOR sequences they show brightness from 0 - 100. However, in xLights I see the brightness goes up to 400. Is it possible that it isn't supplying enough power the lights on the beginning of the ramp?

**Comment by AzGilrock** [comment]
Well it works in LOR because they use a proprietary protocol.  I tried to reverse engineer the protocol the best I could.  I'm assuming you are using the LOR Enhanced protocol in xLights because that is the only one that has a chance of working.  With my work things go well with a smaller number of pixels.  The larger the number of pixels and color changes in the effect causes a big jump in data and that's when things go haywire.  LOR tried to get cute with this protocol and its more efficient than standard DMX packets in some cases but with more complex effects its actually worse.  That's why it failing during the ramp and then stabilizing at 100% because at 100% all pixels are the same color so the protocol is very efficient.

**Comment by dvynsoul** [comment]
That makes sense to me now. Yes I'm using the LOR enhanced protocol. Now that I understand that, do you think putting the Pixie controller on a separate universe with another LOR dongle would 
 help since I'd be putting it in its own porr. Right now I have 2 other LOR controllers running on the same Universe. I have a 16 channel ac and an 8 channel RGB.

**Comment by AzGilrock** [comment]
Yes the more you split the channels between COM port outputs the better it will be.  The LOR dongle plugs in USB but is seen as a COM port to the program.

**Comment by dvynsoul** [comment]
Ok, great to know. I'm going to try bring the minimum intensity on the brightness curve first. If it doesn't work I'll run it on its own com port and see if that helps . Thank you for your assistance!

**Comment by AzGilrock** [comment]
By the way we let you magnify an effect up to 400% brightness but the values still will clamp at 255 so you can never get higher than LORs 100%

**Comment by cybercop23** [comment]
@dvynsoul can this be closed?

**Comment by dvynsoul** [comment]
Yes, it can be closed. Thank you!Sent from my iPhoneOn Feb 5, 2024, at 6:53 PM, AlexB ***@***.***> wrote:﻿
@dvynsoul can this be closed?
