### ISSUE TITLE
Xschedule audio ducker

### ISSUE THREAD

**Issue by ebeckereb** [xLightsSequencer/xLights#2406]
**Is your feature request related to a problem? Please describe.**
When there is a issue with visitors the ability to on demand duck the audio and play a quick psa wav/mp3 over the sequence

**Describe alternatives you've considered**
Using a 3rd party device or stopping show to play a psa sequence when a quick audio interrupt would work

**Comment by cybercop23** [comment]
I don't use xSchedule, but I believe here's an option for this when using the web interface. Can you check/try and if completed, close this?
