### ISSUE TITLE
SegFault when "Creating GL Canvas for Preview"

### ISSUE THREAD

**Issue by whvneo** [xLightsSequencer/xLights#2420]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Starting the AppImage (Linux 64 Bit) or compile one causes a SegFault

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Download latest release (2020.55)
2. chmod +x xLights-2020.55-x86_64.AppImage
3. Starting with the following cli
```
./xLights -m $HOME/Projexts/xLights/media -s $HOME/Projects/xLights/show -w -d
```
or the downloaded version
```
./xLights-2020.42-x86_64.AppImage -m $HOME/Projexts/xLights/media -s $HOME/Projects/xLights/show -w -d
```
```
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Expected behavior**
Start successfull

**Screenshots**

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS with latest updates
 - xLights version 2020.55 (or source from 18th of December 2020)
Some cli output:
```
neo@Nebuchadnezzar:/tmp$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
neo@Nebuchadnezzar:/tmp$ uname -a
Linux Nebuchadnezzar 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
neo@Nebuchadnezzar:/tmp$ glxinfo | grep -i version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 20.2.0
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.0-devel (git-6f39126 2020-05-29 focal-oibaf-ppa)
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.0-devel (git-6f39126 2020-05-29 focal-oibaf-ppa)
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.0-devel (git-6f39126 2020-05-29 focal-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
root@Nebuchadnezzar:~# lshw -c video
  *-display                 
       Beschreibung: VGA compatible controller
       Produkt: UHD Graphics 630 (Mobile)
       Hersteller: Intel Corporation
       Physische ID: 2
       Bus-Informationen: pci@0000:00:02.0
       Logischer Name: /dev/fb0
       Version: 00
       Breite: 64 bits
       Takt: 33MHz
       Fähigkeiten: pciexpress msi pm vga_controller bus_master cap_list rom fb
       Konfiguration: depth=32 driver=i915 latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       Ressourcen: iomemory:600-5ff iomemory:400-3ff irq:157 memory:6000000000-6000ffffff memory:4000000000-400fffffff ioport:4000(Größe=64) memory:c0000-dffff
```
**Additional context**

**Attachments**
[xLights_l4cpp_failed.log](https://github.com/smeighan/xLights/files/5718046/xLights_l4cpp_failed.log)
[xLights_l4cpp_working.log](https://github.com/smeighan/xLights/files/5718047/xLights_l4cpp_working.log)
[xLights_2020.42_working.strace.txt](https://github.com/smeighan/xLights/files/5718050/xLights_2020.42_working.strace.txt)
[xLights_2020.55_failed.strace.txt](https://github.com/smeighan/xLights/files/5718051/xLights_2020.55_failed.strace.txt)
[xLights_dbgrpt-32768-20201218T220022.zip](https://github.com/smeighan/xLights/files/5718052/xLights_dbgrpt-32768-20201218T220022.zip)

**Comment by leighfiddes** [comment]
Same fault occurs on 2020.56 (Ubuntu 20.04 LTS)

**Comment by toozie21** [comment]
Same with 2020.57 (Ubuntu 20.04.1)

**Comment by cybercop23** [comment]
Can this be closed?
