### ISSUE TITLE
Add J1SYS PIXAD8 to controllers

### ISSUE THREAD

**Issue by DavidAVD** [xLightsSequencer/xLights#2432]
Is it possible to add the PIXAD8 pixel controller to the list of J1SYS controllers please?

As far as I know it's much the same overall as the P12 series.

Let me know what exact information you need. Thank you.

**Comment by DavidAVD** [comment]
Is it a case of adding another section to the j1sys.xcontroller file?

I can possibly work out what's needed.

**Comment by keithsw1111** [comment]
You dont add a file ... you add a section to the file.

**Comment by DavidAVD** [comment]
Yes, that's what I wrote above. An extra section in the j1sys.xcontroller file.

What info do you need? Thanks again.

**Comment by cybercop23** [comment]
@DavidAVD are you still looking to do this? IDK if it was added. If so, Fell free to create a PR

**Comment by DavidAVD** [comment]
It went in the too hard basket back then. I just manually configure the controller.

**Comment by cybercop23** [comment]
You can add (if not already there now) a section like with with the right info...
`<Controller Name="P12D">
		<Variant Name="">
            <SupportsAutoLayout/>
			<SupportsPixelPortCommonSettings/>
			<SupportsUpload/>
			<MaxInputUniverses>12</MaxInputUniverses>
			<MaxPixelPort>12</MaxPixelPort>
			<MaxSerialPort>2</MaxSerialPort>
			<MaxSerialPortChannels>512</MaxSerialPortChannels>
			<MaxPixelPortChannels>510</MaxPixelPortChannels>
			<PixelProtocols>
				<Protocol>ws2811</Protocol>
				<Protocol>tm18xx</Protocol>
				<Protocol>ws2801</Protocol>
				<Protocol>tls3001</Protocol>
				<Protocol>lpd6803</Protocol>
			</PixelProtocols>
			<SerialProtocols>
				<Protocol>dmx</Protocol>
				<Protocol>renard</Protocol>
			</SerialProtocols>
			<InputProtocols>
				<Protocol>e131</Protocol>
				<Protocol>artnet</Protocol>
			</InputProtocols>
			<SupportsMultipleSimultaneousOutputProtocols/>
            <ConfigDriver>J1Sys</ConfigDriver>
		</Variant>
	</Controller>`

to this file.. and create a Pull Request...
https://github.com/xLightsSequencer/xLights/blob/master/controllers/j1sys.xcontroller

Else please close this issue.
