### ISSUE TITLE
Spliting an effect

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#2441]
Someone has asked me about this, and I've wondered as well.  There are times when effects span a length of a sequence.  Sometime it would be nice to split them in half and insert/interrupt the effects and insert a new effect between them.  If you're zoomed in and working on a particular area of a sequence, moving and changing the view may cause you to lose your place.  

Similar to video editing software when selecting a point on the timeline, right-click over a selected effect and be able to split an effect at that point.  I know the wave form and effects may not recognize each other or if it can correlate the coordinates you're expecting.  But, it would be a useful addition to the effect editing right-click.  Not sure what that would take to work in.

Thanks and Happy New Year :)

Clyde L

**Comment by Phippers** [comment]
sounds like a blade tool in Final Cut

**Comment by Clyde-L** [comment]
This was eventually created and added to the sequence grid, but never closed.
