### ISSUE TITLE
Batch render needs full path of sequence

### ISSUE THREAD

**Issue by meckman** [xLightsSequencer/xLights#2443]
I’m working on the latest version of xlights on a mac and I’m having an issue determining which sequence to render when trying to perform a batch render. When I pull up batch render it’s only showing the first 11 characters of the sequence/path name (see attachment). Apparently I have multiples due to creating import folders under the main folder and thus I can not determine which sequence to actually render.  It did not matter which option I selected to search in  it still only displayed the first 11 characters. 

![3374D97A-931B-4B79-9B25-6C2BB20E0CCA](https://user-images.githubusercontent.com/57596410/103481602-05adfe00-4daa-11eb-9e20-5ad5f5a80b79.jpeg)
![618B72E7-AE2E-434D-B7E4-B0219FA30068](https://user-images.githubusercontent.com/57596410/103481605-09da1b80-4daa-11eb-8b8a-b2dc4b621c6b.jpeg)
FPP Connect shows the entire path and thus it’s easy to determine which sequence I need to upload to the controllers (see attachment).

**Comment by derwin12** [comment]
Is this still an issue? I see that there is (now) column headings that allow you to reveal the entire path along with modified date.
Perhaps close this one?
