### ISSUE TITLE
Sequence Download Window Additions

### ISSUE THREAD

**Issue by deplanche** [xLightsSequencer/xLights#2446]
I've put together a group of people who are going to help me review and organize the shared sequences on the google drive since there are 400+ sequences in the new uploads or needs review folders.  With that, there are a few enhancements that would be nice to have for the direct download in xlights.

1. Allow the search at the bottom to search by the creator, so if people want to download everything from a certain person, that can be easier to find.
2. Add a line in the item that indicates if a sequence contains a lyric track or not.  Right now the XML files that it reads from lets you say if it is a lyric track or a sequence, but I don't think there is a way to specify if a sequence contains lyrics or not other than in the notes.
3. Be able to filter by sequences with or without lyrics.
4. Add a way to add an image to each, similar to what is done for vendor coro models.  This will let someone quickly and easily see what type and how many props are in a sequence.  Then they can play the video to see how they are used, and download from there.

Right now, people uploading to the drive aren't always adding the video or an image of their layout, but as part of the group reviewing and organizing that, I'd like to have people create those.   That way we it's easier for people to find something that might be useful to them.

Thanks!

**Comment by cybercop23** [comment]
@deplanche IDK where the project ended up and/or if it has been maintained. If it is being maintained, maybe @derwin12 can take a look.

**Comment by derwin12** [comment]
I did make some of the changes .. I think based on the usage of the download sequences it should suffice.
