### ISSUE TITLE
Change number of channels on the Tab

### ISSUE THREAD

**Issue by twodoglights** [xLightsSequencer/xLights#2453]
With the number of 7r or bigger / professional  styled moving fixtures being implemented... Change the tabs to 16 on each tab  to match products being used, or make the  number of channel on the tabs chosen by end user .. this would place all the channels for that fixture on one tab, making it much easier sequence and verify the settings.. everything would be right in front.   Many heads I have found have Pan at channel 10 and Tilt on 12, making flipping between tabs  to verify settings...very time consuming,

making the number of Channels on the tabs, and numbers of tabs selectable    would allow end user with a 16 channel fixture to customize if they want 8 on one tab, and 8 on another,  or all 16 on one tab.

**Comment by AzGilrock** [comment]
I think I need one of them to show up at my door to figure this out. ;)

**Comment by cybercop23** [comment]
Seen or discussd this in zoom. would be nice to have it increased since most heads now so support 12 or 16.
@AzGilrock  you now have 2 to play with....

IDK if this is worth given the new MH Adv.. thougths?

@derwin12

**Comment by twodoglights** [comment]
we still plan to sequence our moving heads in DMX as we have been for the
past 6+ years.  using all the dmx controls i can make  groups of heads or
singles move in circles and all without issues.   with only 8 channels on
the tabs, I have 1 set of our heads that split the pan and Tilt between the
tabs, and that makes it a pain in the ass. ( pan on channel 7 and Tilt on
channel 9). Having all 16 on 1 tab would make everything easier. Pretty
much all Gils new toys seem to be doing is just automating the DMX
sequencing..  and yes we will be test what he has done with 2 different MH
head setups, rather bugs show up with testig on our side than get out and
people that , and I hate to say it this way, refuse how to sequence them in
DMX..  Its just as easy as pixels.

**Comment by AzGilrock** [comment]
Sometimes you can’t teach an old dog new tricks.

**Comment by twodoglights** [comment]
Gil..  no we can learn new tricks,( which I am off for the next 2 days and
will see if  I can get your new toys working on my laptop, once i turn off
the virus scan stuff, then fully test in real time on our moving heads
sitting right behind me).   but we can sequence very quickly in DMX  on the
heads now..   just noone wants to learn how to do it, its actually easy..
Hell i used to work DMX fixtures in the LOR Suite... Xlights is a cake walk
next to that!

the only thing that slows us down is having to flip between tabs  for a 16
channel unit...

**Comment by twodoglights** [comment]
I figured it was a little jab for fun no biggy... but yes this is who you
think,  so from someone that "can" do DMX easily, since i know our heads so
well and all the usable settings etc.. in my head.... hmm just like the
pixel users have "go to layers" of effects for their pixels...  Actually I
olook forward to tinkering with your new goodies.. it will give you a very
good real world test on real operating items,    and 4 of our heads channel
assignments are totally different than the other 4.. so I have a cheat
sheet and do bulk edit on the channel mapping, which others can do "if"
they just took a few moments to create cheats...

and Yes we have used "other sequencers" head maps,  in fact we used Tom
Betgeorges "nightmare before christmas" so we could get that into our
halloween mix 2 years ago. mainly for the timings etc... once i figured out
how he actually "buried/hid" his dmx effects into the sequence,
easily dissected it,  remapped rewrote the heads so it fit "our"
limitations of the way we have to use the heads in the show. His timing
were pretty good, but  yea we did correct some musically wise , and
improved a few lol...  but it gave us lots to work from, which was a big
help time wise. (crap reminds me I have  got the drone out to video it, but
halloween is just a 5/7 day run, basically to test new stuff in the display)

I'll let you know once we get that version of XL loaded on the laptop. and
get the heads functioning on it..

**Comment by twodoglights** [comment]
oh NOW you tell me...  I'll update it shortly.... remaking the models as
the "adv model" using our head specs

**Comment by cybercop23** [comment]
#3804

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/cf4d1b30-afc6-4db6-ab74-f266455c3d72)

**Comment by twodoglights** [comment]
Great! that looks wonderful....make dmx sequencing mucho easier
