### ISSUE TITLE
Multi-channel audio

### ISSUE THREAD

**Issue by allendotson** [xLightsSequencer/xLights#2467]
I am interested in seeing an upgrade to audio in the timeline to support multiple mono channels. For users with soundcards that support multiple outputs, the audio for each channel could be routed to an individual output. This would enable the user to put speakers in multiple locations around their display, and have targeted audio in that area.

Example given could be a pirate ship with cannons that have audio that play a firing sound... and a building somewhere else that also has audio of the impact. The lights would work normally with the timeline, but adds more flexibility with the soundscape.

**Comment by Joylight16888** [comment]
I support this idea. Either surrounding sound (like 5.1) or multi-channel audio support would be nice. Our application is for matrix of speakers working together with LED lights.

**Comment by Kamal-Sonani** [comment]
#1680 closed ,but any way its long time ago may be mind changed😅

**Comment by Joylight16888** [comment]
I tested surrounding sound files downloaded from the web site below:
https://archive.org/details/5.1SurroundSoundTestFilesVariousFormatsAACAC3MP4DTSWAV
The only files accepted by Xlights are .mp4 .wmv files. The surrounding effect is discrete and clear outside Xlights. But inside Xlights, only stereo sound. 
It's obvious some sound libraries have to be replaced.

**Comment by cybercop23** [comment]
Should this be closed?
