### ISSUE TITLE
Marker behavior

### ISSUE THREAD

**Issue by devinhedge** [xLightsSequencer/xLights#2476]
I use markers for navigating backwards and forwards in Digital Audio Workstations (DAWs) and Non-Linear Editors (e.g. Adobe Premiere. When I went to use them in xLights, the behavior was completely not aligned to the behaviors found in any sequencer.

As someone that moves around a lot in my xLights sequences,
I would like the Marker navigation behavior to work similarly to that of Reaper or Adobe Audition, or Adobe Premiere Pro or any DAW/NLE
so that I can quickly move between sections of a sequence in order to edit effects.

I know this will be done when:
GIVEN I have set two markers in my sequence (e.g. markers 0 and 1),
WHEN I navigate to marker 1 using CTRL+1,
THEN the playhead will move to Marker 1, and
     the sequence will scroll horizontally so that Marker 1 is centered in the sequence window

**Comment by devinhedge** [comment]
This logic seems to exist in MainSequencer.cpp::MainSequencer::RestorePosition() and TimeLine.cpp::TimeLine::RestorePosition()

**Comment by computergeek1507** [comment]
So you want the timeline to center the marker on the screen not have it on the left edge when you use it?

**Comment by keithsw1111** [comment]
Why would you want it in the middle of the screen. showing it on the left makes so much more sense.

**Comment by devinhedge** [comment]
I know it seems counter intuitive. The reason that DAWs and NLEs do this is so that you, the content creator can always see what you are doing in context, make your edit fast, and move on. That’s why moving the playhead to the timing Mark while keeping the context of which model layer you were on is also a crucial piece to the move function.

I tried to record the behavior across several DAWs and NLEs last night and ran into an issue being able to export the footage. I have a support ticket in with the software company, and will upload some examples as soon as I get it resolved this morning.

**Comment by devinhedge** [comment]
This is a pretty good example:  https://youtu.be/8BWKJ2iWD_I

**Comment by artwait** [comment]
Just wanted to upvote this request. Centering the marker provides context for what happens before the marker's timestamp, which is useful when hopping around. And, as the OP mentioned, it's a commonly used interaction design in other NLEs. Would also expect the playhead to jump to the marker's location which doesn't seem to be the case currently.

Thanks for considering!

**Comment by AzGilrock** [comment]
Just place the marker such that it centers what you want to see when it’s on the left.  I downvote this request do to care what Adobe and others do

**Comment by artwait** [comment]
I think the problem with that solution is that it a) doesn't scale if the
user changes their horizontal view window or zooms in/out, b) forces the
user to place the marker not where the event occurs, but in a different
location to essentially hack the UI, and c) doesn't place the play head at
the point of the event.

I certainly see that this is one of those features that intelligent people
can feel differently about. Maybe it could be an option in preferences.

**Comment by cybercop23** [comment]
Shoudl this be closed?
