### ISSUE TITLE
In-Program method to batch-edit file paths.

### ISSUE THREAD

**Issue by neowolfwitch** [xLightsSequencer/xLights#2480]
**Is your feature request related to a problem? Please describe.**
Okay, so I know it's usually the result of not following best practices (which many new to xLights may not even know about), but sometimes it is necessary to change the path of media that has gone missing for multiple sequences, for example, if the "permanent" working folder had to be changed for some reason.

**Describe the solution you'd like**
If xLights detects missing media, either automatically or via "Check Sequence", there should be an option to update the path globally within that sequence, and potentially offer an option to select all other known sequences (in the working folder).
 
**Describe alternatives you've considered**
Right now, the only way to do this practically is to edit each sequence's XML data in a text/dev editor- doing a global replace from the old path to the new one. This is prone to errors and can destroy a sequence, and editing these files directly is never recommended.

I am aware of the "Bulk Edit" options within each sequence, but this is not very practical for sequences with a lot of models, or if MANY sequences are involved.

**Comment by cybercop23** [comment]
Given that there's aleady a Bulk Edit. unlikely that such  overall option will be implemented, especially with the recent import from zip file that creates sequence specific asset dirrectory.

Please review and close if no longer an issue.
