### ISSUE TITLE
Effects tab in sequencing does not scale correctly for a 768 x 1366 monitor ON LINUX

### ISSUE THREAD

**Issue by MoulderUtes** [xLightsSequencer/xLights#2483]
**Describe the bug**
The default effects tab in sequencing (default horizontal bar not adjustable window) does not scale for a 1366 x 768 monitor. The last 5 or so effects get cut off. If you un dock it, it grows past a full monitor and on to a second (if you have a second monitor). I believe this started happening on the xLights-2021.02-x86_64.AppImage. Good chance as with the version before this but didn't check. This started hapening when the layout model options were fixed. 

**To Reproduce**
1. be on linux xlights xLights-2021.02-x86_64.AppImage
2. be on a 1366 monitor (or smaller I would assume)
3. now you cant see all the effects
4. if you undock it then it grows off the edge of the screen, you also cant re dock it cause it wont let the right edge to go off the screen. 

**Expected behavior**
Either a horizontal scroll bar on the default effects tab or make the spacing between the effects smaller. 

**Screenshots**
![image](https://user-images.githubusercontent.com/66335335/106328651-09ac2f00-6235-11eb-91b9-7a478b6facd8.png)
the image shows part of a second monitor on the left

**Versions (please complete the following information):**
 - OS: linux manjaro gnome desktop
 - xLights version xLights-2021.02-x86_64.AppImage

**Additional context**
Started happening when scaling on model options were fixed

**Comment by MoulderUtes** [comment]
Note Even after restart and trying anything I cant get the effects bar to re-dock in the correct location as it does not get reset by set all windows to default or dock all windows.

**Comment by cybercop23** [comment]
Is this still an issue for you? If not, please close.
