### ISSUE TITLE
Giving Credit Where Credit Is Due.

### ISSUE THREAD

**Issue by hssusc** [xLightsSequencer/xLights#2487]
I am a firm believer in giving credit where credit is due. There have been a few instances recently where a sequencers work has been shared (on either social media or 'sequence sharing' sites/groups) where the sequence was either mis-credited or not credited at all. (Probably due to lack of metadata to begin with.) With the large amount of new hobbyist users, and new sequence vendors, every year, the potential for ethical problems increases as well. I think it would be of great benefit for the metadata in xLights to auto-populate with this information. 

Information is already prompted for when creating a sequence:

![image](https://user-images.githubusercontent.com/76570408/106383965-89054400-6396-11eb-9ac2-49199253dbe2.png)

(In respect to vendors, the Company Name would be a nice addition here. A field for Contributing Author would also be needed here as I'll discuss below. To ensure the correct song is used, the Music URL would be phenomenal, but I'm sure that gets a little trickier to implement.)

I'm assuming it is possible to add Author, Company, and Website fields to the 'other' tab under preferences. 

![image](https://user-images.githubusercontent.com/76570408/106383873-3c216d80-6396-11eb-9421-4d6f69a1e7fc.png)

Since the Song, Artist, and Album info is already populated into the sequence settings when creating a new sequence, it shouldn't be a huge stretch to populate this information also. 

Here's the kicker: once a sequence is created, that information is no longer editable through the gui/menus (editing the xml is another story and we'll save that for another day). It remains a permanent part of the sequence until the sequence itself is deleted. 

The main advantage of this is when a new sequence is created from scratch, it ensures that Author is credited for their hard work. It would also help with organization efforts in databases, the Google drive, etc. @deplanche has #1329 and #2446 open that this may be of use for. 

The next problem lies with importing sequences. When importing a whole (or at least a large portion of a) sequence, the original Author information needs to be imported with the sequence. When Import Effects (should this change to Import Sequence? We have Effect Presets to import individual effects... I digress.) is implemented, there would need to be something that moves the current Author information to the Contributing Author field, then adds the Author information from the original sequence to the current sequence. 

I hope this makes sense. I'm on my fifth cup of coffee and it seems my brain is working much faster than my body...

**Comment by jnovack** [comment]
You had me until a few specific points:

> Here's the kicker: once a sequence is created, that information is no longer editable through the gui/menus (editing the xml is another story and we'll save that for another day). It remains a permanent part of the sequence until the sequence itself is deleted.

**Case 1 - I legally changed my name changed and now I would like my sequences to reflect that.**
 
Which brings me to my next problem with your request.  The "importing sequences" paragraph.  Do not try to prevent the user from changing from author (especially implementing #1329 and #2446).  

**Case 2 - Someone downloads your sequence, adds something controversial as text or images to the sequence, and uploads it back to the Google Drive.  You are the author.**

Don't try to DRM the sequence.

At best, treat it like an ID3 tag in an MP3 file.  Fill it in, permit rewriting and deleting if the user so wishes.  Do not try to solve a personnel problem with technology.  People will find a way to remove the author.

**Comment by hssusc** [comment]
jnovack - the whole idea is to be able to give credit to the ORIGINAL author of a sequence regardless of how many times it's been edited and/or shared. 

In Case 1, if John Doe created the original sequence, John Doe will be listed as the author of that sequence throughout it's lifespan. If John Doe changes his name to Jane Smith, well, it's a small community and most people will know that John Doe is now Jane Smith. Any new sequences will now be attributed to Jane (as long as John/Jane changes the information in their settings). If any of Johns sequences are distributed on the internet (shared drives, sequence stores, sharing groups/sites, etc.) they would be nearly impossible to track down and edit to Jane and they would still reflect John as the ORIGINAL author. However, if John wanted to change HIS copies over to Jane, the xml can still be edited with a text editor and then re-shared. 

That is the one caveat to this proposal; anybody could edit the xml, at any time. However, at this time, this type of direct plagiarism doesn't seem to be a problem within our community. The problem I've seen the most is that sequence X (one of the greatest sequences ever created and is a viral internet sensation) was created by John Doe, but, for whatever reason, everybody thinks Jimmy Johnson created it. As a result, Jimmy gets all the credit for Johns hard work and effort and John never shares his sequences again. This is why the ORIGINAL author of a sequence should not be editable once the sequence has been created. 

In case 2, yes, the ORIGINAL author would be credited for creating the sequence. However, any changes to a sequence would add the CONTRIBUTING author to the sequence information. If John creates the sequence, he will be the ORIGINAL author for the lifespan of that sequence. If Jimmy makes any changes to that sequence, John will be listed as the ORIGINAL author and Jimmy is now listed as the CONTRIBUTING author. You can be fairly certain that any sequence listed this way was created by John and edited by Jimmy. Any other CONTRIBUTING authors would ALSO be listed. 

Personally, I'd like to see ID3-type tags used for this, also. It would make organizing and searching for sequences much easier. But, I know implementing that from a developers' perspective is much more difficult. So we can save that for another day.
