### ISSUE TITLE
FPP Connect does not display, or upload, files with non-english characters in the name

### ISSUE THREAD

**Issue by gportillo1** [xLightsSequencer/xLights#2497]
**Describe the bug**
When I open FPP Connect, to try to upload a sequence, it is not displaying the music file that is related to a sequence, see attached image.
![image](https://user-images.githubusercontent.com/20132399/107161348-6f956680-6959-11eb-8497-b368c8a61bf7.png)
![image](https://user-images.githubusercontent.com/20132399/107161315-365cf680-6959-11eb-9c11-cc6cfbeafe50.png)

If I rename the file, and replace the "ñ" with an "n", then the file is displayed in FPP Connect, and is uploaded as expected.

![image](https://user-images.githubusercontent.com/20132399/107161491-445f4700-695a-11eb-9f89-4c20f728b726.png)
![image](https://user-images.githubusercontent.com/20132399/107161508-593bda80-695a-11eb-8c95-c19b9f8514c8.png)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a new music sequence.  The musical file name, needs to contain a non-English character, like ñ.
2. Save the sequence
3. Click on Tools > FPP Connect

**Expected behavior**
I expect all of my media files to be displayed, as part of the FPP upload process, regardless of the file name.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10 
 - xLights version 2021.03

If you need more information, I would gladly join a Zoom meeting to show you my issue.  This has been tested in 2 separate PCs, with the same results.

**Comment by jnovack** [comment]
Not all parts of the application may be Unicode compatible and may have unintentional consequences.

It is part of a filename, and while Linux and Windows NTFS  support Unicode characters in the filename, FAT12, FAT16, and FAT32 file systems use the OEM character set.  Also, a large part of xLights and FPP contain scripts and functions which may have parent functions which may NOT be Unicode compatible (for whatever reason).

While this is a good idea, and I'm not disagreeing with you, this is not an easy change as the entire ecosystem has to be fully Unicode compatible.

**Comment by gportillo1** [comment]
Justin, I understand the limitations. A couple of things:
1. The ñ is not a unicode character, it is an ascii character supported by fat16 and 32. 
2. I just posted this because I believe it to be a bug. I have a simple workaround, so it does not bother me.
Personally, if my QA team would ever report a bug like this one, especially with a simple workaround, I would give it a priority 1.... 1 in a million chance of it ever getting fixed.

**Comment by cybercop23** [comment]
There's been a lot of ehnancements in this area. Pelase try with the latest xlights and FPP, 2024.2 adn 7.5. Reopen if you feel recessary.
