### ISSUE TITLE
xLights crashes when view perspective spans 2 monitors

### ISSUE THREAD

**Issue by monstrousmike** [xLightsSequencer/xLights#2523]
**Describe the bug**
xLights stops responding when I open a sequence where the perspective spans two monitors. It never quite finishes opening the sequence. If I click on the xLights window, it goes to "Not Responding".

**To Reproduce**
1. Launch xLights
2. From Controllers tab, Change Temporarily (or Permanently) to the desired show folder
3. Open a sequence
4. If the perspective had been previously saved spanning two displays, the sequence will never complete loading and xLights will stop responding.

**Expected behavior**
xLights should open successfully regardless of the perspective that was last used when editing any sequence.

**Versions (please complete the following information):**
 - OS: Windows 10 Pro will latest updates
 - xLights version 2021.05 64 bit

**Additional context**
I recall this being an issue in the past with nVidia graphics cards. I thought it was resolved at some point, or perhaps a driver update took care of it. The issue persists and I thought I should raise the issue in case there is anything that the developers can do about it.

My work-around is to return to the Default perspective (which I maintain using only one display) before I exit xLights. Once in a while I forget, which leads to the issue the next time I use xLights. Another workaround is to check the perspective before opening the first sequence after launching xLights. If it is set to Default (one display) then it will be OK. If it is set to a perspective that spans 2 displays, then I need to set it back to default until the sequence loads. Once the sequence is loaded I can switch to the perspective that spans displays.

My computer is a CyberPower PC with AMD Ryzen 9 3900X 3.80 GHz, 64GB RAM, SSD hard drives, nVidia GeForce GTX 1650 with two displays

This will occur 100% of the time that my perspective is left (saved) as spanning more than one display. The issue is independent of the sequence itself. I packaged Christmas Every Day as an example.

**Attachments**
[Christmas Every Day.zip](https://github.com/smeighan/xLights/files/6017905/Christmas.Every.Day.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/6017907/xLightsProblem.zip)

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked. <<< I am fine with the sequence being posted publicly. I was the 2020 xLights Around the World sequence.

**Comment by cathelest** [comment]
https://github.com/smeighan/xLights/issues/2019
