### ISSUE TITLE
Value Curve - Node - Popup Information Goes Missing Custom Setting

### ISSUE THREAD

**Issue by byakymyk** [xLightsSequencer/xLights#2525]
OS Mac 11.2.1 Big Sur
xLights 2021.5

When using the Value Curve and trying to adjust the Node values in the Custom Setting.  The Hand icon used to popup and appear the the setting values which dynamically adjusted when moving the node around.  They have now gone missing in this version which makes it difficult to adjust to values preferred.

The popup values will appear when rolling over and resting over the last node to the right of the gui window but will disappear when clicking on any of the nodes.

I have compared to an older Windows version which just to make sure it was available and working properly - which it was.

**Comment by byakymyk** [comment]
https://user-images.githubusercontent.com/2902828/108630759-6f569a00-7434-11eb-9aff-81a3af6ede3f.mp4

**Comment by derwin12** [comment]
Please test and resubmit if this is still an issue.
