### ISSUE TITLE
Picture Effect - Vector Movement - Can't Choose End Position

### ISSUE THREAD

**Issue by byakymyk** [xLightsSequencer/xLights#2534]
OS Mac 11.2.1
xLights 2021.5

End Position is greyed out for Vector Movement in the Picture effect

**Comment by byakymyk** [comment]
<img width="456" alt="2021-02-25_21-16-07" src="https://user-images.githubusercontent.com/2902828/109245583-c6e76380-77ae-11eb-8977-39a15c3e65b9.png">

**Comment by byakymyk** [comment]
Compared to Win 2021.5 and older version of Win prior to 2021 - definitely broken as it was working in older Win version

**Comment by derwin12** [comment]
Cant duplicate.. Brent - can you verify and or close?
