### ISSUE TITLE
wxWidgets is being installed in system

### ISSUE THREAD

**Issue by mase76** [xLightsSequencer/xLights#2537]
Hi!
I am trying to do a Debian package of xLights. However there is one problem:
You write, that wxWidgets is checked for version 3.1.5. If not present, it is checked out, compiled and xLights will be linked statically against it. But wxWidgets gets installed in the system when running the Makefile of xLights, and there is the problem with Debian packaging. Isn't it possible to build and link to wxWidgets without installing it in the system?
As a further try, I will package wxWidgets separately.
I hope, you got, what I mean.

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by mase76** [comment]
The behaviour is still the same. Wx is built and installed into the system and not linked statically.

**Comment by AzGilrock** [comment]
Sounds like you are trying to build the code instead of running our pre-built images.
Follow the Linux instructions here: https://xlights.org/releases/

**Comment by mase76** [comment]
Yes, I am building from source. And yes, I followed the instructions. xlights-wx should not be installed in the filesystem. It should be linked statically. I could run into problems with the "normal" Wx installed in the system.

**Comment by AzGilrock** [comment]
When you build code on your own you have to install and build wxWidgets as part of the process.  How do you think it gets statically linked?  It does so by you building and linking it.  Why are you building anyways?  If you insist on building it yourself instead of using the pre-built images then your on your own.

**Comment by mase76** [comment]
When I install Wx, it is linked dynamically. This way I am unable to package xLights for Debian. Of course I can use the appimage, but that is not the point. Building Wx is ok, but not installing it in the system. I am not sure, if you really got my point.

**Comment by mase76** [comment]
When only building Wx, you have the shared libs under the lib folder in the source tree. You could link statically against it without installing Wx.

**Comment by computergeek1507** [comment]
You can run the make file with specific sections and skip the wx build and install step, then xLights will use the version already installed in the lib folder. We do require wx 3.2 and some custom options so it probably won't build. But if you want to manage the library yourself it's always an option.

**Comment by mase76** [comment]
I will try to build wx with the --disable-shared option. So I should be able to link statically. I hope, this works. Stay tuned...

**Comment by mase76** [comment]
I wasn't able to finish building, because I still have a linker problem against X11. But the static part with Wx works. I added --disable-shared to the Wx configure options and added the static librariies and includes to the cbp files. I will see, if I can fix the X11 linker problem.

**Comment by derwin12** [comment]
I dont think there is anything we can do here..
