### ISSUE TITLE
Going from AC Toolbar to Another Effect Generates Last AC Effect Used

### ISSUE THREAD

**Issue by jimswinder** [xLightsSequencer/xLights#2539]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I turn on the AC Toolbar and use a descending Ramp. I turn off AC Toolbar to use just an "On" effect but when I drag it into the cell where I want the cell to be just on it puts in a Descending Ramp (see attached Video)

**To Reproduce**

1. Click on AC Toolbar to turn it on
2. Click on AC "On" and then AC "Descending Ramp"
3. Click on cells where you want AC "Descending Ramp"
4. Click AC Toolbar off
5. Drag "ON" effect to new cells
6. "Descending Ramp" appears

**Expected behavior**
I would expect going from the AC toolbar to another effect, that effect would be generated in the cell(s) selected not the last AC Toolbar effect I used.

**Screenshots**
Attached Video

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.04

**Additional context**
N/A

**Attachments**
Video File

[Ramps.zip](https://github.com/smeighan/xLights/files/6056071/Ramps.zip)
[Snow For Johnny - Burl Ives.zip](https://github.com/smeighan/xLights/files/6056079/Snow.For.Johnny.-.Burl.Ives.zip)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
is this still an issue? If not, pelase close
