### ISSUE TITLE
Moving head orientation issue

### ISSUE THREAD

**Issue by Phippers** [xLightsSequencer/xLights#2552]
**Describe the bug**
When moving heads are oriented in different rotations, the beam output does not follow the moving head 3D model. 

**To Reproduce**
Go to packaged sequence, and play sequence.

**Expected behavior**
Position of 3D model is the expected behavior. The beam output is incorrect

**Screenshots**
https://www.dropbox.com/sh/bu0ne9zyu6y1bk4/AABRbT--zfvDS9bsfEGE-ffUa?dl=0
Screen shots, video, and sequence in dropbox link.

**Versions (please complete the following information):**
Mac OS 10.15.7

**Comment by AzGilrock** [comment]
See discussion in #2155

**Comment by Phippers** [comment]
> See discussion in #2155

Darn. Thanks. With the orientation of my heads, theres no work around because I have the heads mounted sideways.

**Comment by AzGilrock** [comment]
If you mean rotated sideways there is an Orientation parameter to correct that.  Don’t use the rotation handles set the ration values back to 0 manually

**Comment by Phippers** [comment]
![B2491C93-0074-43D4-81E3-EBE065142F8C](https://user-images.githubusercontent.com/79396182/110397772-53074f80-8027-11eb-8e27-b3980fd31041.jpeg)
They are oriented like this. I found a slight workaround in where I reoriented my matrix panels to match the orientation of the moving heads

**Comment by cybercop23** [comment]
Can this be closed, especially with the new MH Advnaced model?
