### ISSUE TITLE
Generate 3D CustomModels from multiangle video

### ISSUE THREAD

**Issue by OnlineDynamic** [xLightsSequencer/xLights#2555]
**Is your feature request related to a problem? Please describe.**
Would like to be able to create custom 3D objects from camera looking at physical layout.  Allow me to put pixels on natural shapes - trees / bushes etc where the exact layout will change each time they are put up.

**Describe the solution you'd like**
Like the current 2D custom model generator to be extended it to take video from multiple angles to allow xlights to build a 3d rather than 2d model.

**Describe alternatives you've considered**
Manually creating the 3d model (pretty much unworkable with 100's/1000 of pixels)

**Comment by AzGilrock** [comment]
That would be an awesome feature.  I personally would never do it for a free program.
