### ISSUE TITLE
Face effect isn't mapped when switching to a smaller prop (From Boscoyo 46 to 30 singing bulb)

### ISSUE THREAD

**Issue by pp6024** [xLightsSequencer/xLights#2578]
**Describe the bug**
Switching my bulb faces from the Boscoyo 46 to 30 singing bulb results in no face effect being mapped for the affected props.   Sub model effects are mapped.  Just not the Face effect with the lyric track.

**To Reproduce**
1.  Remove Boscoyo 46 singing bulb from layout
2.  Add Boscoyo 30 singing face to layout with same name as prior prop
3.  Load an existing sequence.
4.  Prompt window appears to rename, ignore or remap the affected model/sub-model
5. Select "Map effect to different model"
6.  Assign Base to Socket
7. Assign Bulb to Bulb
8. Assign Prop to Prop (in this case Curly Bulb to Curly Bulb)
9. Click Ok
10. Effects are mapped.   However, the Face effect isn't mapped to the parent model

**Expected behavior**
Map face affect to parent model when sub-models effects are mapped when copying effects between models.   Such as switching between two different height singing bulbs.

**Screenshots**
![image](https://user-images.githubusercontent.com/70034434/113377652-87c2aa00-933a-11eb-8807-b3d99f6e8a41.png)

![image](https://user-images.githubusercontent.com/70034434/113377707-b2acfe00-933a-11eb-8045-4e615b032b92.png)

Image for Face Effect not mapped
![image](https://user-images.githubusercontent.com/70034434/113377775-e7b95080-933a-11eb-96a5-7c7d3a9d4fd3.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version:  2021.10

**Comment by cybercop23** [comment]
The Face effect is applied at the model level, not sub-model. Pretty sure it is working at that level. Going to close this, but if you still have issues, feel free to reopen it.
