### ISSUE TITLE
Right clicking color to open color curve window causes crash if sequence has a VAMP-sourced timing channel (Linux)

### ISSUE THREAD

**Issue by SonnyJim** [xLightsSequencer/xLights#2582]
**Describe the bug**

**To Reproduce**
1. Start a new musical sequence (any audio file, doesn't matter)
2. Right click on 'New Timing' and select 'Add timing track'
3. Select any one of the following:
'Bars and beats'
'Note onset detector'
'Tempo and beat tracker'
Note that it appears to be only specific VAMP plugins that cause the issue, metronome/key detector don't cause a crash

4. Right click on a color in the color dockable window (to open up the color curve window)
5. Crash, even if you delete the timing track before right clicking the color window or open up a previously saved sequence.

**Expected behavior**
Xlights shouldn't crash when opening the color curve window with a timing track

**Screenshots**

**Versions (please complete the following information):**
 - OS: SparkyLinux 5.14
 - xLights versions current git, 2020.23 - 2021.10
 
**Additional context**
It seems tied to the VAMP plugin and the beat markers in the timeline in some way
I am using QM Vamp version 1.7.1 as the more recent version (1.8.0) does not include qm-vamp-plugins.cat and qm-vamp-plugins.n3
Another thing to note is that everything else seems to work fine, only that if my sequence has a VAMP timing track it means I can no longer open the color curve window.  Weird, eh?
**Attachments**
[xLights_dbgrpt-13862-20210404T164110.zip](https://github.com/smeighan/xLights/files/6254063/xLights_dbgrpt-13862-20210404T164110.zip)

**Comment by cybercop23** [comment]
@SonnyJim Is this still an issue? If not, please close.
