### ISSUE TITLE
Hang up on submodels window

### ISSUE THREAD

**Issue by timslights** [xLightsSequencer/xLights#2597]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
In the prop submodels tab, 2020.11 hangs up when i try to reorganise my submodels. Also hangs up after adding 5 or 6 new submodels in a row. Using MacOS.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to a prop
2. Click on the submodels tab
2. Attempt to reorganise the submodels
4. See error - submodel window becomes unresponsive

**Expected behavior**
Expected to be able to continue sing submodel window, rather i have to exit out by clicking OK and going back in to the submodel tab

**Screenshots**
not sure how to add screenshots in here

**Versions (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - xLights version 2021.11

**Comment by cybercop23** [comment]
Seen several of this same issue.
