### ISSUE TITLE
Undo on Layout only moves one item back upon "undo" after moving multiple items

### ISSUE THREAD

**Issue by prosyscon** [xLightsSequencer/xLights#2601]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

NOTE - - - <issue related to Layout>

**Describe the bug**
I moved multiple props sideways, then realized I wanted to move them back.  I pressed "undo" and only of the props returned to the original position. . . and a second "undo" moved the prop to a different, unrelated spot.  Not catastrophic, but definitely not desirable.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
<no audio, but obvious>
https://drive.google.com/file/d/1mUeG0axcR2lZAithr5VidMV1WVtifM9O/view?usp=sharing

**Expected behavior**
all moved props return to original location after pressing "undo"

**Screenshots**
<See attached video>

**Versions (please complete the following information):**
 - OS: [Windows 10 Pro]
 - xLights version 2021.12  (but it occured on 2021.11 as well)

**Additional context**
just working on my layout

**Attachments**
Attached link to my google drive with video of the steps i took

https://user-images.githubusercontent.com/5253618/115100563-6dc4c200-9f0b-11eb-929a-54964cfd67ab.mp4

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
Closing this. Doesn't seem to still be an issue anymore. If still a problem, please reopen.
