### ISSUE TITLE
Max Grid Size and Metronome Numeric Entry Broken - Mac

### ISSUE THREAD

**Issue by dfg138** [xLightsSequencer/xLights#2617]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When numeric box is cleared, it will not take an input.  If there is already a value in the box, it will allow you to type.  See video.  I've experienced this with previous version of xLights, as well.  

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

Video attached

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac Big Sur 11.2.2
 - xLights version 2021.12

**Additional context**

**Attachments**

https://user-images.githubusercontent.com/81779686/116143638-650d8200-a6a9-11eb-907f-392e7a4d3a7a.mp4

**Comment by keithsw1111** [comment]
Looks like an OSX specific bug ... it works on windows. I can clear the spinner text box and then type in a number.

**Comment by gbonesso** [comment]
I could reproduce the bug in OSX, but it look looks related to the field "Max Grid Size" when a group is selected. The fields "X Center Offset" and "Y Center Offset" works as expected. I also tried to reproduce the bug in Windows with this specific case (group selected and "Max Group Size") and I couldn't, it works fine in Windows...

**Comment by sslupsky** [comment]
This looks like a problem with wxWidgets wxNumberEntryDialog().  The problem can also be observed by attempting to key a value for the metronome timing.

wxNumberEntryDialog() uses wxSpinCtrl().  The wxNumberEntryDialog() dialog appears to "continuously" do validation of the input and it appears validation is performed by wxSpinCtrl() while keying the value into the dialog on macOS.  So, if the value in the box is less than the min parameter at any time during entry, the validation fails and wxSpinCtrl() prevents that value from being entered even though the "OK" button has not been pressed.  I suggest to resolve this issue the min value should be set to a value such that wxSpinCtrl() value verification does not prevent valid values to be keyed.  The min value validation should then be performed on the return value in the function(s) that receive the value.  If the min value parameter is <=1 then the problem does not manifest.

In the case of the metronome setting, the min parameter should be 1 in the wxNumberEntryDialog() call and a validation check performed when the OK button is clicked.  

wxNumberEntryDialog() and wxSpinCtrl() are used quite a bit throughout xLights but fortunately, the min value is >1 in only a few places.   wxSpinCtrlDouble() doesn't appear to have this issue.

The OP's problem is here:
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/ModelGroupPanel.cpp#L172

The metronome issue is here:
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/SeqSettingsDialog.cpp#L997
and here:
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/sequencer/RowHeading.cpp#L675


Other instances are listed here:
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/CustomTimingDialog.cpp#L44
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/SubModelGenerateDialog.cpp#L57


Also note, @dkulp identified the spin control issue last year and implemented a fix for bulk editing here:
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/BulkEditControls.cpp#L112-L128


There is one instance of this issue in xCapture here:
https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xCapture/xCaptureMain.cpp#L316

**Comment by sslupsky** [comment]
There may also be issues at the following places as well:

https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/CustomModelDialog.cpp#L2996

https://github.com/smeighan/xLights/blob/2120fdf975d1f8fbfa7a3618053614e53dd537d8/xLights/NodeSelectGrid.cpp#L1083

if GetMinMaxNode() returns a min value > 1

**Comment by sslupsky** [comment]
See PR #3029 for fix for Grid Size, Metronome and Custom Timing.
