### ISSUE TITLE
Importing Custom Prop - Removes groups when "replacing model with this model"

### ISSUE THREAD

**Issue by jefft0825** [xLightsSequencer/xLights#2663]
Custom props that have groups attached to them.    I was helping a friend and I had a Gilbert prop setup to map to a PPD layout and exported my baby grand illusion - so he could import it on his layout and map to the correct groups - i use the submodels from the PPD wreath to map to the baby grand illusion

When he imported the prop, it mapped to the correct groups but when you "replace a model with this model" to swap out the prop, it removes it from the groups

I have created a test layout - it has the PPD wreath with a standard baby grand illusion from the download section.     If you import the xmodel attached in the zip file its the baby grand illusion but its mapped into the PPD wreath groups - they go to the correct groups.   

![image](https://user-images.githubusercontent.com/39816390/120349403-b66dea00-c2c3-11eb-9af4-8bb7e1d19eaa.png)

If you then try and replace the original model with the new model, it takes all those groups out.   
[GE Baby Grand Illusion Left-3.zip](https://github.com/smeighan/xLights/files/6577376/GE.Baby.Grand.Illusion.Left-3.zip)

The only way around this is to completely delete the old model and then configure your start channels for the new prop and the ones before and after it

Here is the test layout i created

[XlightsBug.zip](https://github.com/smeighan/xLights/files/6577397/XlightsBug.zip)

Open the layout - import the custom model attached in the zip file - click yes if you want it to be added tot he groups and then keep clicking through all the error boxes .   You can see that the ppd wreath groups are mapped to the new baby grand illusions.     Now replace the original one with the new one (replace a model with this model) and the groupings are gone on the baby grand

Latest version of xlights running on windows 10

**Comment by cybercop23** [comment]
Seems to be workign on the latrest version, 2024.2. Please reopen if you have any issues.
