### ISSUE TITLE
Bulk Edit script items in Linux version

### ISSUE THREAD

**Issue by KevynChambers** [xLightsSequencer/xLights#2686]
**Is your feature request related to a problem? Please describe.**
 Bulk Edit currently not working on scripted item such as Render Style or Layer Blending in Linux version of xLights version 2021.18

**Describe the solution you'd like**
Ability to use Bulk Edit on script as well as numerical input

**Describe alternatives you've considered**
Each item can be altered individually but with large groups of effects in sequences this is time consuming and tedious and often one cell gets missed?

**Additional context**

**Comment by cybercop23** [comment]
wxWidgets limitation. Duplicate issues.
