### ISSUE TITLE
Moving heads don’t record properly in export video

### ISSUE THREAD

**Issue by tbetgeorge** [xLightsSequencer/xLights#2690]
When using the export video option, moving heads do not record properly with reference to maximum degrees per second on pan and tilt (they go to the immediate values instead of going through the motions slowly when large value changes occur). It works properly when watching in real time. This was verified in version 2021.19 on a Mac.

**Comment by keithsw1111** [comment]
I just tried it on windows and it seems to render ok in the video. I just added a 3d moving head. Droped an on effect (white) on the strand. Set pan and tilt slew limts to 20 and exported the video. When the on effect came on the head moved slowly towards the 255 position.

**Comment by keithsw1111** [comment]
Unless we get a copy of a layout or sequence that has the issue then we are not going to be able to do anything about it.

**Comment by tbetgeorge** [comment]
I emailed mine. I can resend if helpful.

**Comment by lenhard2007** [comment]
Please advise were you would like me to send the email. thanks

**Comment by CFos26** [comment]
I am having the same issue and would be willing to send my sequence and a clip of the house preview video.

**Comment by cybercop23** [comment]
Closing this as there are a lot of seq vendors that export MH in previews and are working. If still an issue, please reopen.
