### ISSUE TITLE
.20 update causing strange single line speeds

### ISSUE THREAD

**Issue by MrPierreB** [xLightsSequencer/xLights#2695]
**Describe the bug**
After opening a sequence on 2021.20, I noticed single lines I have on groups are doubling in speed.

I am guessing it was caused by this change. So it will probably effect shockwave effects as well
— enh (scott) Increase range of shockwave and single strand effect

**To Reproduce**
1. See attached sequence (open and render)
2. Note the speed of the effects.
3. To fix it -  if you pick the single line effect on the rosa grande,  just add another color and remove it again,   or remove and re-add the curve again ... now it will be correct.

**Expected behavior**
For the effects to be the same speeds they were in the previous version.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.20

**Attachments**
- [https://drive.google.com/file/d/1m1o_RqZJvzROspzOYLoHBIszu8T4eQ0Y/view?usp=sharing](https://drive.google.com/file/d/1m1o_RqZJvzROspzOYLoHBIszu8T4eQ0Y/view?usp=sharing)

**Comment by Cranzy-AU** [comment]
@computergeek1507  Do you reckon your fix for this will go through?
