### ISSUE TITLE
No Audio on Mac in xlights after mac goes to sleep

### ISSUE THREAD

**Issue by kbostick88** [xLightsSequencer/xLights#2722]
Everytime I leave xlights open and allow my Mac to sleep, or close the lid upon reopening my Macbook there is no audio in xlights. All other apps audio works as expected. Quiting xlights and reopening it will fix the issue until the Mac goes to sleep again.

**Comment by zackbcom** [comment]
I have the same issue. I have to go to the audio bar and click a different speed play back, and then set it back to Full Speed. It will then work if my audio source hasn't changed

My current issue is that if my audio input changes while it's waking up from sleep, xlights will crash.
