### ISSUE TITLE
On New Sequence & New Import Automatically Match Frame Rate

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#2723]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the solution you'd like**
I've noticed recently that I'm the frame rate of the empty sequence that I create is often not aligned with the frame rate of the sequence that I'm importing.  I only noticed this by accident as I was looking at the sequence settings in a side by side copy of xLights.  I'm asking for either a xLights global option (xLights > Preferences) or a per sequence option on the import wizard.

**Describe alternatives you've considered**
Continue to manually check this.

**Additional context**
None

**Note**
By default all my sequences are set to 40fps when I create them so importing a sequence that's at 20fps doesn't really hurt anything other than it may use additional space on the FSEQ files.  I haven't tested this theory. 

I can see this being more of an issue if a user has the opposite situation where their new sequence is 20fps and the import is 40fps.

**Comment by AzGilrock** [comment]
I think the best that could be done is a warning because there is no limit to how many times you can run the import on a sequence.  You could import from 5 different sequences into 1 if you wanted.  And once a sequence is created its not new even though its empty.

**Comment by MrPaulAR** [comment]
I'll modify the request to fit within these bounds.

If a user runs the import option and the currently open sequence is blank other than a "new timing" track then display the checkbox that is checked by default on the import wizard to adjust the timing of the currently open sequence.  Similar to how the how the blend mode is displayed.  This behavior should be safe which is why the default checked option.

Else if the currently open sequence is 20fps and the import is 40fps then go still display the checkbox and default checked along with the frame rate tooltip.  The reason it should be default checked is granular detail will be lost in the downrate from 40fps to 20fps.

Else if the currently open sequence timing is 40fps and the imported timing is 20fps still display the checkbox but this time unchecked with the tooltip.  Unchecked because going from 20fps to 40fps should still hit exactly on the timing marks.

Else don't display the tooltip.  Should that always need to be present then revert to the last else if above.

The above logic will account for the [likely] most common behavior of a single import with a one time fix.  It will also quickly notify a user if there could be a timing issue and allow them to fix it without going to other dialog boxes.

**Comment by AzGilrock** [comment]
Well if one of the guys want to program that but it sounds like a big mess to me.  I wrote the code that allows you to change the FPS setting of an existing open sequence and it requires the sequence to be saved, closed, and reopened to accomplish an FPS change due to all the memory assignments associated with the FPS value.

**Comment by MrPaulAR** [comment]
> Dont you have to create the empty sequence prior to even doing the import effects option - it would be too late by the time you looked into the source sequence. Perhaps a note on the import in the top section where it asks about blending on/off - perhaps just a display of the source fps.

Yes you do.  But just like the render blending mode is set before the import and there is a checkbox on the import wizard to adjust/correct the blending mode to match that of the original sequence.

**Comment by computergeek1507** [comment]
I'll add a warning tonight

**Comment by cybercop23** [comment]
Still need this?
