### ISSUE TITLE
Test Console Enhancement Request

### ISSUE THREAD

**Issue by TripleJ3EB** [xLightsSequencer/xLights#2728]
I am working on a large light show that will have 700 coroplast props from GE and Bosc.   We need an easier way to test props that people have wired for us to find the problems easier.  A few suggestions that could make things easier:

1.  Allow to pause, and even back up the chase.
2. Have a larger number on screen to show what pixel number is on so we can follow the wiring diagrams, its currently only in the status bar, hard to see from any distance
3. Have ability for the computer to say what pixel number is currently on to follow easier.
4. Be able to specify the exact pixel number to start at.
5. Be able to restart at pixel one.

A few are obviously very close in function, but should make our job of debugging bad wiring jobs on props much easier.

Thanks!

**Comment by keithsw1111** [comment]
Sounds to me like you really need some sort of use case specific test program. I would need to be convinced that there was general utility here and on first read I am not getting it. For a normal user all of this control exists with the ability to control specific nodes ... your use case seem pretty a-typical.
