### ISSUE TITLE
Addition to Ability to Import Views from RGBEffects File and Sequence Files

### ISSUE THREAD

**Issue by DGHayes** [xLightsSequencer/xLights#2736]
**Is your feature request related to a problem? Please describe.**
No, not directly, but could be viewwd as such given the way it works.

**Describe the solution you'd like**
Thank you Scott for adding this wonderful feature Ability to Import Views from "RGB Effects File and Sequence Files”.

This works well if you have all the models or groups named as per import. If you have each of the sequence vendors groups created with 3 digits identifier or prefix, the only groups to import are the exact matches. i.e. Icicles group imports to imported master view, but PPD Icicles or MLS Icicles does not.

Therefore, would it be possible to have a way of entering a **3 letter prefix** to all the groups imported so the groups take up the ones in your layout?

Suggestion would be PPD (Pixel Pro Displays), MLS (Magical Light Shows), XTS (eXtreme Sequences) etc. 

**Describe alternatives you've considered**
The alternative I use at the moment is to create a view with the vendors render order, name that something like PPD 2020, import a sequence and then take the vendors view (PPD 2020) and make it my master. That way I match to render order they have.

![image](https://user-images.githubusercontent.com/33895648/128465883-785437c9-22c1-40ca-9a51-5061b0f82c03.png)

**Comment by cybercop23** [comment]
Shoud this be closed?
