### ISSUE TITLE
Select Effect Window Doesn't Always Show Groups

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#2775]
**Describe the bug**
I'm trying to use the select effect dialog and looking to select the shockwave effect on the everything group but it's only showing individual models.  Other than a couple matrix elements and singing faces nothing is sequenced at the model level. 

![image](https://user-images.githubusercontent.com/3765696/131203230-cee89ad0-76d7-4781-ba78-81b15dc86391.png)

If I change the selection to Shader I get the expected result.

![image](https://user-images.githubusercontent.com/3765696/131203237-d5bd75bd-e1ac-45bc-9450-72e32aa28a5c.png)

**Versions (please complete the following information):**
 - OS: Win 20
 - xLights version 2021.27

**Comment by computergeek1507** [comment]
Can you package the sequence and attached it.

**Comment by MrPaulAR** [comment]
I've provided this directly to @computergeek1507 as this is a vendor sequence.

**Comment by cybercop23** [comment]
@MrPaulAR is this still an issue? Problems with my Mac... I can't test myself.
