### ISSUE TITLE
Props not showing up in display elements when there is a timing track with an identical name.

### ISSUE THREAD

**Issue by MDickson00** [xLightsSequencer/xLights#2785]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

When there is already a timing track in the sequencer with a name (suach as Santa) if there is a prop with an identical name, it will not show up in edit display elements. Alternatively, if there is a already a prop with a name (sucha as Santa) and you create a new timing track and name it the same name (such as Santa) the timing track name will save as Santa_1.

1. Go to sequencer
2. Start a new animation
3. Create a timing track and name it Santa
4. Go to your layout and create a prop named Santa
5. Go back to sequencer, click edit display elements
6. Notice the Santa prop is missing from display elements
7. Alternaitvely, create a prop named Santa
8. Go to sequencer and creat a new timing track and name it Santa
9. Notice it will change the timing track name to Santa_1

Including a video below
https://youtu.be/klJwRk7xYR0

Also attaching an empty sequence with a prop named Santa
[xlights bug.zip](https://github.com/smeighan/xLights/files/7080570/xlights.bug.zip)

**Comment by cybercop23** [comment]
Should be available in the nightly and next version.
