### ISSUE TITLE
Locked out of editing Submodels after reordering or deleting a Submodel in the list

### ISSUE THREAD

**Issue by SoulCube13** [xLightsSequencer/xLights#2806]
**Describe the bug**
After i reorder my submodels on a prop, renaming a submodel, or deleting submodels, i am locked out from editing any other submodel on that prop until i close the window and reopen the submodel window

**To Reproduce**
1. Click Any Prop
2. Click To Edit Submodels
3. Add Submodel
4. Name Submodel
5. Add Nodes To Submodel
5. Delete Submodel
6. *After the last step, you will not be able to edit any other submodel until you close the window and reopen in*
7. **Will also happen if you have submodels already and reorder them by dragging them into any order, you will not be able to edit any submodel**

**Expected behavior**
Be able to edit submodels, reorder submodels, etc. without having the window lock and need to be closed and reopen

**Versions (please complete the following information):**
 - OS: Mac
 - xLights version 2021.29

**Comment by keithsw1111** [comment]
Is this still a problem?
