### ISSUE TITLE
State Effect - display all colors when changing to different color

### ISSUE THREAD

**Issue by jefft0825** [xLightsSequencer/xLights#2813]
Similar to how you all did the submodels - each line of the submodel will be a different color so you can see if there are overlapping nodes

When choosing different colors on a state effect, one you go to a new line, you dont know which nodes were highlighted.    Is there a way to keep all the "reds" on when you go to a new rode range and trying to make the opposite whites?

Would be a lot easier if i knew which nodes were already chosen
![State](https://user-images.githubusercontent.com/39816390/134191491-f54eb493-0183-456b-af70-6785ce75af2c.PNG)

**Comment by derwin12** [comment]
This appears to have been done. 
![image](https://github.com/user-attachments/assets/c4fa4a40-3a78-4052-b7a4-a1be943bdb1c)
