### ISSUE TITLE
Combo box settings in the Sequencer don't allow Bulk editing under Linux

### ISSUE THREAD

**Issue by fone626** [xLightsSequencer/xLights#2825]
**Describe the bug**
Combo box settings in the Sequencer don't allow Bulk editing under Linux.
As far as I know, this has never worked.  I always thought it was a deficiency in the software until I was demonstrating xLights to someone using windows, and to my surprise, it worked on there.

**To Reproduce**
Select multiple items, then right click on an combo box setting... Nothing special happens.  I've tried clicking everywhere on the combo box as well as everyone around it... nothing.

**Expected behavior**
A bulk edit button would appear and allow bulk editing of the option.

**Versions (please complete the following information):**
 - OS: Kubuntu Linux 20.04
 - xLights version : All, It's never worked as long as I've been using xLights

**Comment by fone626** [comment]
Since filing this bug I've found that there is about a 1 pixel area around the combo box that you CAN right click and get the bulk edit menu, so it's no longer impossible, but difficult to hit and next to impossible for others to find.  If its a limitation to how wxwidgets passes through to GTK would it be possible to add the bulk edit menu to the label for the combo boxes as a good work around?

**Comment by cybercop23** [comment]
#3092
