### ISSUE TITLE
Change size of dialog box in FPP Upload

### ISSUE THREAD

**Issue by chuckackerman** [xLightsSequencer/xLights#2931]
The dialog box doesn't show the cancel button.  Can the dialog box be increased in size?

![Screenshot 2021-11-11 144322](https://user-images.githubusercontent.com/39970914/141380010-3ad06dc3-1ab3-44f9-b311-5617a6281781.jpg)

**Comment by keithsw1111** [comment]
I really dont think there is anything we can do about this ... it seems to be buried in the framework.
