### ISSUE TITLE
Xlights not playing nice with AlphaPix Controller

### ISSUE THREAD

**Issue by OceanViper** [xLightsSequencer/xLights#2939]
Using Linux Mint 20.2, xlights 2021.37 visualizer models fail to upload. I have two AlphaPix 2016 controllers. Both fail to upload. Error messages says,  **"Holiday Coro Output Upload Failed, Cannot connect".**  However the visualizer does open the controller's webpage so it is connected.

Let me know if you need any other info. -Ocean

**Comment by keithsw1111** [comment]
Log files would help ... but probably not much.

**Comment by computergeek1507** [comment]
Are you using the app image?

**Comment by OceanViper** [comment]
yes I am using app image

**Comment by OceanViper** [comment]
@cybercop23- Yes this can be closed. This is an old post and after several years of Xlights upgrades the problem still exists. However I found the best solution is to just ignore Xlights messages. Xlights simply lies regarding the AlphaPix controllers connection, or not uploading data. The older Alphapix controls have always been treated like a step child by Xlights. The step child has become used to it. LOL

**Comment by OceanViper** [comment]
This was an old post. After several years of xlight upgrades the quandary still subsists. However I found the best solution is to simply ignore faulty xlight messages as xlights has always treated the older Alphapix controllers like a renegade step child. The controllers do connect and upload data regardless of what xlights cerebrates. Besides, the step child has become immune to xlights treatment. LOL
