### ISSUE TITLE
Cannot Check Individual Start Channels

### ISSUE THREAD

**Issue by wbottomley** [xLightsSequencer/xLights#294]
When setting up a model to display as Arches, single color, you cannot select individual start channels.  Having this option available would be great.  Why?  Due to the fact that all channels/controllers will not be sequentially ordered.  They could be connecting to any controller with available channels.

**Comment by AzGilrock** [comment]
I was looking into this and I think you can select individual start channels.  You gotta change the "# of arches" setting to greater than 1 and then it activates the checkbox.

**Comment by wbottomley** [comment]
I see it does.  But... What if segments 1-7 where on controller 1 and segments 8 & 9 where on controller 2.  There's no way to define them like that.

**Comment by AzGilrock** [comment]
Ok so the real request is that we show a row for every segment.

**Comment by wbottomley** [comment]
Yes so we can define any channel we want to with it.

Thanks for your help Gil!!!!

**Comment by cybercop23** [comment]
This is now achievable with Shadow Model(s). Can this be closed?

**Comment by derwin12** [comment]
There are a number of duplicates of this issue -- #2334
