### ISSUE TITLE
Off-screen Preview Window crashes xlights

### ISSUE THREAD

**Issue by bluecreeklightguy** [xLightsSequencer/xLights#2946]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I've run into this bug for quite some time (a couple of years, dating back to 2019; may have existed earlier, but this is when I began encountering it), but worked around it.  Tonight, it dawned on me to check the .xml file and I think I found the issue.

When you attempt to open a preview window has its title bar off screen (for me it happened on my second monitor), xlights crashes.  I found the location setting in the rgbeffects.xml file (attached).  I manually edited the PosX and PosY values to something on screen, reopened xlights, tried to reopen the preview, and it worked.

I suspect this happens when, on one setup, a second monitor is arranged at a certain height, compared to the main monitor.  And then, when you move to another setup, where the second monitor is lower, compared to the main monitor, the preview is left off screen and unable to be moved because the title bar isn't visible.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Within xlights, click on the Sequencer tab.  No need to have a sequence open.
2. Select the View menu item, then Previews, then select a preview that is off screen so far that the title bar isn't visible (so can't be grabbed and moved back on screen).
3.  xlights crashes every time I try this.

**Expected behavior**
I would expect xlights to redraw the window to a location on screen (maybe upper-left corner).

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows10
 - xLights version 2021.37

**Additional context**
rgbeffects.xml file is attached.  the "problem" preview is called "Neighborhood".  You can see that PosX and PosY are -1025 and -586, respectively.

**Attachments**
xlights_rgbeffects.xml
crash log

[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/7569045/xlights_rgbeffects.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/7569041/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
The problem is more likely a video card issue on your computer.

**Comment by bluecreeklightguy** [comment]
It definitely could be. 

Since I could fix it with a modification to the .xml file, I thought I’d submit, in case it could be reproduced on other systems. I know what causes it now (or at least how to fix it), so I can make that manual change to the xml file if I run into it again. 

Thanks. 

Aaron

**Comment by cybercop23** [comment]
Can this be closed?
