### ISSUE TITLE
Xlights 2021.37 Render and Export of Matrix bug

### ISSUE THREAD

**Issue by djohnson1810** [xLightsSequencer/xLights#2952]
If you have a matrix in a  group and try and "render and export" that matrix to an avi file, you just get a blank (black) file.  If you just choose  "render" it works fine.  If something is dropped directly on the matrix (not the group) everything works as intended.

I was in the Zoom room with Daryl and Keith last night and they confirmed this.

**Comment by derwin12** [comment]
yes..

**Comment by cybercop23** [comment]
Hmmmm.... Windows issue maybe....  seems to be working on a Mac.. unless I'm doing something diff...
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/66c2a7b9-979b-4cba-bb6c-6a1ecf330f45)

**Comment by derwin12** [comment]
That is it exactly Gil -- you cant just render the model as you lose all the effects that hit the model from the various groups. The only real render here has to be a complete render.

**Comment by dkulp** [comment]
My opinion is that we should remove the "Render and Export" option entirely.   Just "Export" and use whatever has currently been rendered.

**Comment by derwin12** [comment]
Thinking about automation here .. can it kick a full render? So if you script, it will do the render? Or just remove the "render and export" option entirely? It has been silently dropping effects the way it is now.

**Comment by cybercop23** [comment]
I see... yeah.... and if I put something after the group effect it will export that. So not really "seeing" anything that's from "blending". Assuming render only renders the model and not whole list.
