### ISSUE TITLE
Sequence files do not show up in xlights

### ISSUE THREAD

**Issue by Rivy5353** [xLightsSequencer/xLights#2955]
When trying to import a sequence in xlights, the files do not show up. They are in the directory outside of xlights but will not show up when I try to import.  Am I doing something wrong?

Thanks, Richie

**Comment by keithsw1111** [comment]
From your description I am not sure I understand what you mean. Do you mean you import a sequence and the effects with pictures/videos/shaders dont show up. If so then yes you likely imported them incorrectly. There are many videos explaining how to do this. Once it is wrong you will want to select effects and re-point the files. You can use bulk edit to do this more quickly ... again there are many videos around on how to do that as well. Pop into xlights zoom and they will get you sorted pretty quickly.
