### ISSUE TITLE
UI breaks with output fractional scaling

### ISSUE THREAD

**Issue by stromnet** [xLightsSequencer/xLights#2964]
**Describe the bug**
Running on Linux with sway (wayland) as window manager, and laptop 4k monitor scale 1.5, the menus are broken 

**To Reproduce**
With a 'sway' WM just add `output eDP-1 scale 1.5` or similar to your config.
With other WM... I guess try changing to some fractional scaling?

**Expected behavior**
Proper menus.

**Screenshots**

Here I clicked the Help menu:
![image](https://user-images.githubusercontent.com/668449/143313543-05904f8e-c59a-4e8f-8e02-27b056380d6a.png)

Here I clicked the Effect drop-down (which renders too high up, and small size, making it tricky to use)
![image](https://user-images.githubusercontent.com/668449/143313688-dc35fe74-b0ec-4fcf-9f73-eb76f20e8b80.png)

Changing scale to 1 or 2 makes it work as expected.

**Versions (please complete the following information):**
 - OS: Linux 5.14.x with sway 1.6.1 (and also latest sway-git)
 - ./xLights-2021.38-x86_64.AppImage

**Comment by cjd** [comment]
xLights is not running on wayland directly (not supported by wxwidgets) and so has to go via xwayland
I'm guessing xwayland isn't handling the scaling properly.
Also the appimage includes it's own libraries for X etc - so there may be a mismatch happening.
If you manually compile does it behave the same?

**Comment by cybercop23** [comment]
Can this be closed?
