### ISSUE TITLE
DMX not rendering single strand or butterfly type 2

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#2969]
From zoom..
Click on the butterfly for start rt - only shows red .. last year it pulsed.. 
other props pulse - the star is a dmx prop which is different than the other props, but it worked as defined prior.

Changed to type 1 you get something..

kategaudry at gmail.com

[bug dmx.zip](https://github.com/smeighan/xLights/files/7604903/bug.dmx.zip)

**Comment by dkulp** [comment]
This is due to 35a4e345f6df56f93ba769f9e44ddbe98d340d6c .   I'm tempted to revert as it shouldn't be needed anymore, but not 100% sure.
