### ISSUE TITLE
Unable to save FSEQ file yet .XSQ file saves

### ISSUE THREAD

**Issue by LightsOnHudson** [xLightsSequencer/xLights#2972]
Error - permissions unable to write FSEQ file, yet the XSQ file writes on a drive. 
please see screen shot
<img width="678" alt="Screen Shot 2021-11-29 at 9 17 00 AM" src="https://user-images.githubusercontent.com/10136122/143904475-03ffd912-9337-4c9d-8c67-f3520442e6c8.png">

**Comment by dkulp** [comment]
Go into the preferences panel and re-select the FSEQ directory via the "Browse" button.  The sandbox may have lost permission to write to that directory.

**Comment by LightsOnHudson** [comment]
I have. it will not resolve and work. Errors every time. I have to select a local folder to save the FSEQ file. I even thought there was an existing FSEQ file there, No. This is still an issue. 

. That (having an existing FSEQ) file present has caused problems that the new fseq does not have the details. Can we add soemthing that 'an FSEQ exists. Overwrite? - and then it deletes it and then saves a new one?

**Comment by TheDelmosShow** [comment]
I'm having the same issue, I'm exporting everything from my Mac where I make the show to my pc laptop that runs it in xschedlue but I can find a FSEQ on mac. I get the same error

**Comment by nicholastripp** [comment]
I'm experiencing the same issue on macOS 12.2 running version 2021.40.
