### ISSUE TITLE
FPP Connect Overall Progress or Transfer in Alpha Order

### ISSUE THREAD

**Issue by neowolfwitch** [xLightsSequencer/xLights#2990]
**Is your feature request related to a problem? Please describe.**
There is no way to tell how far FPP connect is through your list of uploads. It seems to upload sequences at random (or at least definitely not in alpha order, or the order you list them in), so you have no idea where it's at in the process when it is running. It's particularly aggravating if you are transferring media, which can take quite a while.

**Describe the solution you'd like**
I would love to see either an overall progress bar, or at last it uploading sequences either in alpha order or in whatever order they were sorted in when selecting them in the lower window.

**Describe alternatives you've considered**
Really isn't one. The alternative is to just stare at the screen or walk away for awhile and hope they get done with no real progress indicator.

**Additional context**
Only that this is on the Mac version. It's possible the PC version already does this.

**Comment by cybercop23** [comment]
There was a change late last year to put the FPP status in the lower left status window. Also, FPP was changed to upload in parallel.
