### ISSUE TITLE
Text “Move to center” with XL fonts

### ISSUE THREAD

**Issue by eibanez** [xLightsSequencer/xLights#2998]
**Describe the bug**
The “move to center” option works with OS fonts, but not when an XL don’t is selected 

**To Reproduce**
1. Add text to a matrix
2. Select any XL font and mark the `c` option
3. Select left for movement
4. The text will scroll without stopping

**Expected behavior**
The text should stop like it does when an OS font is selected

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version 2021.39

**Comment by derwin12** [comment]
In the release
