### ISSUE TITLE
XSchedule step to wait on plugin or event

### ISSUE THREAD

**Issue by Holiday851** [xLightsSequencer/xLights#3001]
I have a work-around for my plugin, but it would be cleaner if there were something built-in. A couple options (but there could be other ways):

1. A step like Delay in xSchedule that takes an event. The step would end after the time-out (like regular Delay) or end early if the event happened.
2. A plugin call like SendCommand where the plugin can return a bool to indicate that xSchedule should continue to stay in the step and poll the plugin (if the plugin did not implement the function, it would be the same as returning false). There would need to be a corresponding step in xSchedule that called this plugin command and took a time-out and a retry time as settings.

**Comment by keithsw1111** [comment]
I am pretty sure you can do everything you describe by just thinking about things differently.

A playlist could go into delay and any event could trigger "Next Step" and prematurely end it.

**Comment by Holiday851** [comment]
Yeah, that's what I'm doing - except I go a little further and check to
make sure it's still on the same delay step (in case I had externally done
something different through the web interface or whatever) as well as a
couple other things before going to the next wtep. It's just a little
unclean (and there's a bit of a race condition between doing the check and
executing the next-step) doing those checks, but I totally understand
closing the request out.

While I have you, there was another feature request I was going to put in,
but it would probably take less time to ask you here if you think it's a
reasonable request rather than having you wade through the new issues -
adding a user-set random number seed to effects that have a random
component. Sometimes the random locations generated end up looking
not-so-great because they generate objects on top of each other. It would
be nice to be able to set the seed for that effect starting so "better"
randomness could happen (i.e., cycle through some seeds till you find one
you like). If you think that's a reasonable request, I'll add it as a
feature request; otherwise, nevermind.

By the way, I absolutely love xLights and xSchedule! I only started pixel
displaying a few weeks ago, and I already have quite a nice show - even
built a wireless "Santa" jacket with matrices and strips that match my song
sequences. Also, it was pretty easy to add my own plugin - though I did it
differently than the sample since I don't like the export helper - I just
have a managed C++ DLL (where exports work without any rigamarole) that
calls into my C# DLL for the real work. I spent too many decades with
old-school unmanaged C++, and managed C++ just looks wrong to me, so I try
to do the minimum before switching to C#. Good grief, I just realized that
I have now spent decade*s* in C#, too.

Thanks for your time!
-- Debora

**Comment by AzGilrock** [comment]
You're definitely not the average user if you got a show going in just a few weeks, have a wireless mobile prop, and have created an xSchedule plugin. :)

I've been a software developer for 37 years and I cringed when I read "managed" C++...lol.  I have done quite a bit in C# and its not bad for Windows GUI work but wouldn't use it in anything real time.

**Comment by Holiday851** [comment]
Windows itself isn't great for real-time stuff, but managed code is totally
fine for things like plugins - Y'all are rendering the pixels - I'm just
driving the commands. Plus managed code has come a LONG way. When I first
started (before it was even publicly available), I swore I'd never use it
for anything "real," but by the time I retired, I was using it for Xbox and
HoloLens stuff. And I have nice sweet typesafe wrappers on all the
xSchedule calls that required little work to write and will require very
little to maintain as y'all add new stuff because Reflection is magical.

**Comment by cybercop23** [comment]
Can this be closed?

**Comment by Holiday851** [comment]
You can close anything I've opened.
