### ISSUE TITLE
output different volumes to different sound cards?

### ISSUE THREAD

**Issue by bchiaino** [xLightsSequencer/xLights#3003]
Is there a way yet or a way of adding the following?

I have a mixer that outputs to my FM transmitter and an amp for my outdoor speakers, I would love to tell XSchedule to lower the volume after an hour only on the outdoor speakers and then every hour following as the night goes on, or even on the first song of the playlist loop that's about an hour anyway

So I was thinking if I had 2 sound cards like the built in and a USB sandblaster can I have XSchedule send audio out to the on-board att 100 but the sandblaster at 80 and then on the first track say ((now lower 10% on sandblaster sound card) as the playlist loops around?

thanks for any input!

**Comment by cybercop23** [comment]
I don't use xSchedule but I know FPP has this feature.. Set volume to X or increase/decrease by y%. Has that ben added to xSchedule?
