### ISSUE TITLE
FPP Connect in xLights -  Multiple Controller Download Stops

### ISSUE THREAD

**Issue by bmasella** [xLightsSequencer/xLights#3005]
Open FPP Connect... Choose all of the Devices I want to Upload to by checking them off... Click Upload... Xlights opens a dialog box and then never connects and sends the data... eventually it times out with an Unhandled exception.

If I repeat the process and select 1 "location" it uploads just fine... I can also do 2 locations but seems when I add the 3rd it just doesn't want to cooperate.   

Task manager shows that xLights is not using any CPU when it is just sitting in this limbo state.

I can wait for the Unhandled exception error and then cancel out or Task Manager terminate and restart.

**Expected behavior**
Would like to send to all of my FPP devices at once.

**Screenshots**
<img width="1265" alt="fppconnect1" src="https://user-images.githubusercontent.com/91099432/145740953-9defd65d-881b-4673-9875-b7eeb36cc3ed.png">

**Versions (please complete the following information):**
 - OS: Windows 10,
 - xLights version:  2021.39

**Additional context**
I can get around the problem by just doing the devices one or two at a time.

**Comment by bmasella** [comment]
Tried it again yesterday... it would only let me do them one at a time yesterday.   I tried rebooting the computer, reconnecting to the network and repeatedly it would fail on trying anything more than a single device.   It does seem to be related to the PixelSticks because I CAN do both of the FPPs together.

**Comment by bmasella** [comment]
If you use the ESPixelstick you can't do the manual copy because it needs the sparse .fseq file that contains only what is needed for that controller which it generates at the time of FPP Connect.

**Comment by cybercop23** [comment]
@bmasella there's been a lot of  changes/fixes late last year to both ESPixelStick F/W and xLights. Can you please try again with the latest versions?
