### ISSUE TITLE
AppImage does not show Layout and Sequencer with OpenSuse

### ISSUE THREAD

**Issue by Medel** [xLightsSequencer/xLights#3023]
Since Versions 2021... the AppImage does not work with OpenSuse.

OpenSuse Version: Leap 15.3
The last version that works is 2020.53

In the sequencer view the view is not showing
![Sequencer View](https://user-images.githubusercontent.com/3252272/146768195-bf07d217-c0b4-4422-a999-6eb1330f9a43.png)
In the layout view the preview is not showing
![Layout View](https://user-images.githubusercontent.com/3252272/146768163-81d4c3f4-a2e5-4e97-97da-e70a99dca107.png)

[Console.log](https://github.com/smeighan/xLights/files/7745302/Console.log)

**Comment by ctrlbru** [comment]
Same with Mint.
