### ISSUE TITLE
xSchedule crashes when doing a CURL with SSL issue

### ISSUE THREAD

**Issue by Holiday851** [xLightsSequencer/xLights#3034]
[xlights.xschedule.txt](https://github.com/smeighan/xLights/files/7776556/xlights.xschedule.txt)

Put the attached file in your show directory and rename it to xlights.xschedule.
Run xschedule.
Select the playlist, and run it.
xSchedule will CURL the invalid URL and not crash (the first step), but when it CURLs the SSL error (the second step), it crashes xSchedule.

Would prefer for it to not crash in the SSL case like it doesn't crash in the 404 case.

Low priority for this exact scenario, but there may be other cases of a bad URL crashing xSchedule that could be prevented by fixing this case.

**Comment by Holiday851** [comment]
This does not repro in 2021.40. It correctly just logs the issue and moves on. From the log:
2022-01-01 08:38:05,497 9132 log_base [ERROR] Failure to access https://holiday851.somee.com: 35: SSL connect error.

Perfect.

**Comment by Holiday851** [comment]
Unsure if y'all prefer to have users close resolved issues, or if you prefer to close themselves so you are reminded to add new unit tests, etc.

**Comment by keithsw1111** [comment]
I still think there is a problem in xLights.

**Comment by cybercop23** [comment]
Still need to keep this open?
