### ISSUE TITLE
xLights-2021.40-x86_64.AppImage missing libthai library

### ISSUE THREAD

**Issue by BitJam** [xLightsSequencer/xLights#3038]
chmod a+x xlights-*.AppImage
./xlights-*.AppImage

/tmp/.mount_xLightFLb4WZ/AppRun.wrapped: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

**Comment by sslupsky** [comment]
I do not know if its related but I was having a problem building 2021.40 in macOS yesterday.  Some missing symbols during linking.  Fell back to 2021.38 and build is fine.
