### ISSUE TITLE
layout window for visualizer

### ISSUE THREAD

**Issue by z28kid** [xLightsSequencer/xLights#3039]
**Is your feature request related to a problem? Please describe.**

I often find myself jumping back and forth to the layout to see where my model is placed and then jumping into visualizer to map it to the controller. vs selecting the controller fields in the layout window. For instance I have 5 trees mapped to two different ports, 3 trees in back row and two trees in the front row. I had to move them around to a different bank to not go over the pixel limit

**Describe the solution you'd like**

Which ever is easier, allow the visualizer window to remain open when going to the layout and still able to make selections/changes. Or include a layout in the visualizer window that highlights models when you're selecting the model to drag over to the controller/port.

**Describe alternatives you've considered**

see above.

**Additional context**

**Comment by z28kid** [comment]
Or even the ability to pull out the controllers tab, Layout tab or sequence tab into another window. To allow the user to maybe visualise along with looking at their layout. As I seem to move props around to different ports and controllers as my show grows.

**Comment by keithsw1111** [comment]
This would be a massive amount of change for something with relatively simple workarounds.
