### ISSUE TITLE
[ENHANCEMENT] Ability to preview sequence from Zip Package

### ISSUE THREAD

**Issue by cbennett6008** [xLightsSequencer/xLights#3043]
This is an enhancement request that I think would reduce some support issues.
In order to get a feel for an imported sequence, and make decisions about what effects to map to your props, it's often necessary to change show folder, and open the sequence in the creator's show layout.

I'm not sure if the best process for this would be a built in function, like you've done with Import | Effects, or with a script once that's an option, but I'm envisioning:
-Extract the zip to a temporary location
-Open a second instance of xlights with the temporary show directory, disable save functions?
-Open the Sequence
-When the second instance is closed, clean up the temp directory

**Comment by TechTurtleTube** [comment]
This would be awesome and stop ppl from unzipping and breaking links in the sequence

**Comment by moorejoel** [comment]
This would certainly make it a lot easier for users to get an idea of what a seq looks like if there was not a video preview available.  Great idea.

**Comment by kklown3722** [comment]
This would be so awesome. So much easier for a newbie to see what the sequence is. Also makes it less likely to break something. Great idea

**Comment by eatonaaron** [comment]
This would be a great addition, would definitely  save time from opening a second instance and doing all that.

**Comment by derwin12** [comment]
I think the xsqz format is a good first step to this.
