### ISSUE TITLE
Backups are making folks go over the 250ish file path limit and getting big warnings about it..

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#3090]
Seems like a windows problem but is there anything xlights can do to help avoid this?
Suggesting to folks to perhaps rename long directory names, perhaps move there backups to a different folder (close to the root c:\ etc)
Not use a long date in the backup folder name?

Any other thoughts on this?

**Comment by keithsw1111** [comment]
Shortening the date is not really going to make all that much difference.

Happy to implement a fix for this but I am not sure what it is.

**Comment by derwin12** [comment]
Found this note . Not sure if it could be implemented by xlights or perhaps just a warning/note that pops up?

https://knowledge.autodesk.com/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/The-Windows-10-default-path-length-limitation-MAX-PATH-is-256-characters.html

**Comment by cybercop23** [comment]
Can this be added to Check Sequence and also to the Show Folder selection dialog when selecting a show folder that is say... 150 or so characters to start with?

**Comment by computergeek1507** [comment]
We could auto set the Register Flag on windows for longer file paths and break there system

**Comment by cybercop23** [comment]
Then we'll get more Mac uses and no more need for Render Cache.. seems like a win-win
