### ISSUE TITLE
Bulk Edit option for scripted commands

### ISSUE THREAD

**Issue by KevynChambers** [xLightsSequencer/xLights#3092]
Can the facility to use Bulk Edit on scrited commands such as render style be added for Linux based OS please?

**Comment by cybercop23** [comment]
@KevynChambers I don't have access to a Linux install. Has this been added?

**Comment by KevynChambers** [comment]
Good afternoon,

Not on the latest version I'm running? I think I was using 2023.16? I can
try a later one to see if it works? If not it would be a really helpful
addition!! Editing hundreds on single transaction effects from imported
sequences is a night mare!!

Regards Kevyn.

**Comment by KevynChambers** [comment]
Hi,

I've just downloaded the last available release 2024.02 and it doesn't
allow bulk edit on render style which is the real killer! I can do checked
or unchecked, such as 3D fade or group arches etc and I can do bulk on any
numerical value such as chase size or cycles but not render style.
Hopefully this could be a simple fix? 🤞🤞🤞 It would really help me out
when modding sequences!

Regards Kevyn.

**Comment by cybercop23** [comment]
You are doing this in the GUI right? If you select an effect.. and Ctrl A to select all similar effects... or Right click on a model/layer and select all.. then right click on render style.. what happens?
Hop in the zoom room when you have a monent. Help - Zoom

**Comment by computergeek1507** [comment]
It's a Linux bug, the right click only works on like one pixel on a combo box and it's impossible to find it

**Comment by cybercop23** [comment]
wxWidgets or xLights issue? Can it be fixed at all?

**Comment by computergeek1507** [comment]
WX issue

**Comment by cybercop23** [comment]
@KevynChambers maybe look for this issue and/or open a new one in wxWidgets and hope they will fix it or provide a solution/workaround.
https://github.com/wxWidgets/wxWidgets

**Comment by KevynChambers** [comment]
Hi,

Well I assume I'm doing it correctly? I'm not using CRTL A as it's not
always every effect in a sequence I want to change, more normally I'm just
lassoing the effects I'm working on? But the bulk option for the other two
work? I can't do Zoom right now as I'm cooking dinner and minding two
children (7&4) Is this the UK zoom or US? (I'm UK based)

Thanks Kev.

**Comment by KevynChambers** [comment]
I should also add I can use the exact same technique on a Windows machine
which will allow this to work but I can't abide the crap that windows has
with it so I have a simple dedicated Linux based mini PC just for sequences
and xLights work. Plus I can't set the screens up how I like off the
Windows machine either so if I can I will try and work with the Linux
option.

Regards Kev.

**Comment by cybercop23** [comment]
If you select an effect and then Ctrl A.. it will only "select" the same effect across the sequence for Bulk Edit. Yes, lasso also works. Since this is confirrmed to be a wxWidgets issue that's also open source and used by xLights, there isn't much we can do until they fix it, themselves.

**Comment by computergeek1507** [comment]
As a temporary fix I wrote a lua script for you that "bulk" edits selected effects render style on a model, if you unzip this and put it in a folder called scripts in your show folder. Then edit it to set the render style you want(spelling and case mater).


[BatchRenderStyle.zip](https://github.com/xLightsSequencer/xLights/files/14169095/BatchRenderStyle.zip)

**Comment by KevynChambers** [comment]
Wow! Thanks so much!! Hopefully I can get this to work? Not that PC savvy
unfortunately!!
