### ISSUE TITLE
macOS UI scroll bars do not appear

### ISSUE THREAD

**Issue by sslupsky** [xLightsSequencer/xLights#3095]
**Describe the bug**
The scroll bars for some of the windows are often not drawn unless you resize it.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Open a sequence - I have included a screenshot below.

**Expected behavior**
Scroll bars should be rendered if the content of the window does not fit.

**Screenshots**
This screenshot shows the "Effects Settings" window.  You can see that the scroll bars are not present.
![Screen Shot 2022-01-19 at 9 27 54 AM](https://user-images.githubusercontent.com/16888734/150174265-be8dddf0-970d-430d-875d-a5c67a02fa90.png)

If I resize the window by click and drag the top of the window, the scroll bars appear.
![Screen Shot 2022-01-19 at 9 36 43 AM](https://user-images.githubusercontent.com/16888734/150174528-fbe92ea1-bba1-4101-ac44-c336db4f7e40.png)

**Versions (please complete the following information):**
 - macOS Big Sur 11.6.1
 - xLights version 2022.02.1

**Comment by AzGilrock** [comment]
Yeah we've had that bug forever even on Windows.  I remember spending a lot of time and never could figure out a fix.  It was happening with my DMX Effect and was one of the reason I made it have tabs.

**Comment by sslupsky** [comment]
Yeah, i suspect this is some kind of wxWidgits issue.

**Comment by cybercop23** [comment]
<img width="729" alt="image" src="https://github.com/xLightsSequencer/xLights/assets/23619433/28d752bb-5f86-4631-936e-e1f1cdeabfc6">
