### ISSUE TITLE
Is it possible to get os2l, Open Sound to light Controle using xlights for live control 

### ISSUE THREAD

**Issue by ranvirgorai** [xLightsSequencer/xLights#3101]
**Is your feature request related to a problem? Please describe.**
If we can trigger some effect using OS2L protocal 

**Describe the solution you'd like**
we can play song in some other software and show will run. than we no need to do sequencing for each song. 

**Describe alternatives you've considered**

**Additional context**
As virtual dj provide Open sound to light support, So we can play any song and it will trigger those effect in xlights.

**Comment by keithsw1111** [comment]
http://os2l.org/

You will need to be clearer about expected behaviour here and not assume we know anything about what you are talking about ... some of it i can guess but some of your statements make me concerned I have it wrong.

**Comment by cybercop23** [comment]
@ranvirgorai are you still lookign to do this? If so, please provide more detailed directions. Else, please close it.
