### ISSUE TITLE
xSchedule does not respect order of steps

### ISSUE THREAD

**Issue by Holiday851** [xLightsSequencer/xLights#3103]
This can be closed. I think it's is only cosmetic. I was trying to figure out why the parameter 3 thing wasn't working (i.e., not allowed to have a blank parameter 3 when doing a plugin command), and this seemed suspicious.

Repros on 2022.03 Windows 10

To Repro:
1. Copy the attached file to your xSchedule show directory and rename it without the .txt extension.
2. Open the schedule file in Notepad.
3. Notice that the order of steps is:
      <PLICommand Command="Send command to plugin" Parm1="Test" Parm2="Test" Parm3="Test" Delay="0" Name="Command"/>
      <PLIFSEQ FSEQFile="D:your-fseq-here.fseq" ApplyMethod="0" StartChannel="1" Channels="0" Delay="0" Name="FSEQ" Priority="1"/>
4. Start xSchedule
5. Double-click the playlist
6. Notice that the order of steps is now:
        your-fseq-here
        Command

(also it does not respect the name "FSEQ" and instead uses the fseq filename, but that is just cosmetic)

Expected: if I need a plugin command to run before the fseq, then respect order.

Yes, I know I can do this as two separate steps but that ruins the ability to do a shuffle since the two will no longer be paired.

[xlights.xschedule.txt](https://github.com/smeighan/xLights/files/7921248/xlights.xschedule.txt)

**Comment by keithsw1111** [comment]
Steps are controlled by priorities ... not their order in the file.

**Comment by cybercop23** [comment]
@Holiday851 can this be closed?
