### ISSUE TITLE
xSchedule - two FSEQs in a step make for weird behavior (one doesn't play, and the other one gets the wrong length and delay)

### ISSUE THREAD

**Issue by Holiday851** [xLightsSequencer/xLights#3105]
Repros in 2022.03 Windows 10

Do either:
1. Save the attached file in your xSchedule show directory and take off the txt extension.
 2. Edit the file in notepad and fill in with FSEQs that you already have (one longer than 5 seconds and one less than 5 seconds)
 3. Save it

OR

1. Start xSchedule
2. Create a new advance playlist
3. Add a FSEQ (that is longer than 5 seconds) and give it a delay of 5 seconds
4. Add a second FSEQ (that is less than 5 seconds) to the same step and leave its delay at 0.
5. Save it
6. Your schedule file should look mostly like the attached file except with your own files and buttons.

then continue with
1. Start xSchedule.
2. Notice that the length of the step is only about 5 seconds.
3. Play the playlist
4. It will play the longer one immediately (not waiting for 5 seconds) but it will only play for a total of 5 seconds (cuts off the FSEQ)
5. It will not play the shorter one at all
6. Edit the schedule file and put this between the two FSEQ calls (i.e., turn it into two separate steps)
    </PlayListStep>
    <PlayListStep Name="">
7. Run xSchedule
8. It will play the shorter one, wait 5 seconds, then play the longer one. (i.e., correct).

Expected: 
the length of the step would be 5 seconds + length of the longer FSEQ
the shorter file would play immediately
then wait (5 - length of shorter file) seconds
then play the longer file

OR 

if having two FSEQs in a step is not a supported scenario, then do not allow the user to add a second one through the UI

(I've been trying a few different things to get things to happen the way I want - I have an interlude FSEQ that I want to play before each song - doing a run every step didn't work because it ran during my first/last steps which is not what I want because they are special. Running it before the song in a single step - i.e., this bug's scenario - didn't work because it doesn't run one of them. Putting them in separate steps does not work because shuffling could get me two+ interludes in a row or two+ songs in a row.)

Another way of fixing would be to flag a step as being attached to its predecessor(s) (i.e., they shuffle as a unit which would be useful for other things especially if you are wanting to do jumps to named steps) - and preventing the user from adding a second FSEQ to a step.

[xlights.xschedule.txt](https://github.com/smeighan/xLights/files/7921736/xlights.xschedule.txt)

**Comment by keithsw1111** [comment]
This is problematic. The problem is xSchedule needs to pick an item as the timing item for the step ... and this item then controls the step duration ... eveything else is meant to fit within that timespan. If you cant do that then you need to think about faking it out with maybe a dummy item which does nothing but represents the whole duration.
