### ISSUE TITLE
Import Previews and Models - Added selection ability

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#3125]
On the layout, right click and import Previews/Models/Groups.
Can there be a couple of things added like:

Select Highlighted .. so one can hilight a bunch of props using click/shift click, to check/select them for import.
Select Siblings - not sure if its broken or what but if one selects a group or highlights a group, right click select siblings, will select all the props not just the props in that group.

Thanks 
Daryl
(from a zoomer)

**Comment by bcarriveau** [comment]
Beat me to it. Was just typing one out, Yes please! Having group one click siblings would be amazing, multi select shift click would also be a plus!

**Comment by cybercop23** [comment]
@derwin12 the siblings will be best.. select the model and it will then select all groups... sounds like right up your alley - toegether with select highlighted (since you have so much practice)

**Comment by derwin12** [comment]
Looking at the code "siblings" is using the Tree terminology .. ie The top of the tree (Default) points to pretty much all the models,
 
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/9540fe50-658a-486f-851c-db87847b664e)

It doesnt consider groups->models as being siblings. Going to see if that is feasible.

**Comment by cybercop23** [comment]
so those are acquaintances and can add true siblings

**Comment by computergeek1507** [comment]
Why not have 2 opinions, all groups and all models under preview
