### ISSUE TITLE
3D Models continually dissapearing

### ISSUE THREAD

**Issue by Jaa1i** [xLightsSequencer/xLights#3132]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
My 3D models are continually dissapearing. It occured during 2022.02 however a restart seemed to fix the issue. Now in 2022.4 even a restart doesn't fix it. I have to select the 3D model again, for each one of them. However the texture of the 3D model is no longer appearing.

**To Reproduce**
There doesn't seem to be any trigger for this error that I have noticed.

**Expected behavior**
For my 3D models to be persistent and not continually dissapearing

**Screenshots**

<img width="2631" alt="Screen Shot 2022-02-22 at 10 46 30 am" src="https://user-images.githubusercontent.com/50488459/155039316-d8c02f12-2375-4bba-bfde-d88a06eca499.png">
<img width="1913" alt="Screen Shot 2022-02-19 at 8 04 00 pm" src="https://user-images.githubusercontent.com/50488459/155039328-dd67df02-1766-4b99-928d-572ff596111e.png">

**Versions (please complete the following information):**
MacOS 12.0.1

**Comment by bakelitephone** [comment]
Please help I am having the same problem in 2022.08 (on a MAC), it worked perfectly last year and now my house model is just grey. 
I have made sure there are no spaces or strange characters in the .obj or .mtl file names (see attached screenshot)

I have also tried re importing my .obj file (myhome.obj) and the surfaces are still grey. This same 3D object worked perfectly back in December so please help

![65CEA450-856A-4367-98B2-0DC3E56ED41A](https://user-images.githubusercontent.com/69304144/163355853-84edc88c-6584-429c-b2bf-edec99d00cda.jpeg)
)

**Comment by bcarriveau** [comment]
In addition to Gils great idea, if you just changed the name of your OBJ you would also have to then edit the obj name referenced inside of the .mtl file.

**Comment by cybercop23** [comment]
@Jaa1i is still still an issue? If not, please close.
