### ISSUE TITLE
LOR Controllers in PullDown Menu of "Controllers"

### ISSUE THREAD

**Issue by jimswinder** [xLightsSequencer/xLights#3139]
**Is your feature request related to a problem? Please describe.**
 No
**Describe the solution you'd like**
Is it possible to have our LOR Controllers show up in the "Controller" Pull Down menu in the Layout Tab?

**Describe alternatives you've considered**
Just use "Use Start Channel"

**Additional context**
![Controller Tab](https://user-images.githubusercontent.com/13740582/155827100-e67c17db-b28d-4dd2-b3d5-4133f0c14520.jpg)
![Layout Tab](https://user-images.githubusercontent.com/13740582/155827102-3e26aaaf-4308-4664-ae93-4dbfc7433c50.jpg)

**Comment by keithsw1111** [comment]
I dont think we can ... the controller is used under the auto layout capability which we cant really support on Serial controllers.

**Comment by jimswinder** [comment]
ok...thanks for replying.
________________________________
