### ISSUE TITLE
xLights: Add a button to sub-model "Select Nodes" window that puts a placeholder (",") into the node list

### ISSUE THREAD

**Issue by Holiday851** [xLightsSequencer/xLights#3144]
Select a custom model in Layout
Click in the sub-model text box ("Click to edit")
Click the "..." button to edit
Click "Add" to create a new sub-model
Double click on "Bottom" to open up "Select Nodes"
Ensure the "Ordered Selection" is checked.
Start double-clicking to add ordered nodes.
If you want to have a skip (for example, you want it to look like "1,,,2,3,,,4" you can't (see bug 3145)

Request:
A button that adds "," to the sequence would be nice; otherwise, you have to go back to the previous screen and manually add the commas. 

Sometimes (I can't get a consistent repro to log a bug on it), when you make the sub-model window maximized and drag the "Node Ranges" columns to be larger, the text box won't allow you to scroll to the beginning of the list of nodes. For long lists of nodes, that means you have to "Select All" text, paste it into Notepad, add the commas, select the updated text in Notepad, and paste it back into the text box because you cannot see where the cursor is in order to add the commas.

**Comment by Holiday851** [comment]
Version 2022.05 64-bit Windows 10

**Comment by computergeek1507** [comment]
In my testing the box only goes "read only" in non order selected mode. Please provide a video with more info.

**Comment by Holiday851** [comment]
This is a feature request - not a bug. The read-only issue is 3145. This is a request to have a  button to add "," to the node list to make it quicker to create a sparse matrix (i.e., with a lot of holes/skips/empty columns).

**Comment by Holiday851** [comment]
![AddEmptyCell](https://user-images.githubusercontent.com/95460274/156095745-a7fb09ec-dc60-4948-a0fb-48c433f886d2.png)

**Comment by computergeek1507** [comment]
In the initial bug report you put `"If you want to have a skip (for example, you want it to look like "1,,,2,3,,,4" you can't (see bug 3145)"`, that is not true, you can, you just have to type it in. I assumed you wanted a button because you couldn't type it. I understand your request. I assumed you needed a solution to a problem that doesn't need fixing.

**Comment by Holiday851** [comment]
I want a button for workflow reasons. It's not a big deal, but it's just
more efficient to go click-click-click instead of click a node, type a
comma, click a node, type a comma

**Comment by computergeek1507** [comment]
I will look into it

**Comment by AzGilrock** [comment]
Scott how about make it so we just tell Siri what we want? :)

**Comment by Holiday851** [comment]
I was just trying to suggest something to make it easier on users. I know before I retired, I appreciated it when users suggested something that was very easy for me to implement but made their task flow a little better.

It won't hurt my feelings if you close this as Wont-Fix.

**Comment by AzGilrock** [comment]
Cool so we were both doing the same thing.

**Comment by cybercop23** [comment]
@Holiday851 there's now an option to make all sting equal. Right click and choose 
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/bd52b9c8-c5c2-40f8-b7b6-9cd67be6e5e7)

Can this be closed?
