### ISSUE TITLE
Export House Preview Video not working - Mac version 2022.5

### ISSUE THREAD

**Issue by ponddude85** [xLightsSequencer/xLights#3149]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When exporting the whole house preview the video generated plays the music but no video. It is a mix of random colors with no discernible images.  

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Open a sequence. 
2. Ensure sequence is rendered. 
3. Click on 'File' > 'Export House Preview Video' 
4. Open completed video in Quicktime

**Expected behavior**
Should be a completed video of the display. 

**Screenshots**
Screen shot of what the video looks like is attached. 

**Versions (please complete the following information):**
 - OS: Mac 12.2.1
 - xLights version 2022.5

**Additional context**
<img width="1440" alt="Screen Shot 2022-02-28 at 10 38 34 PM" src="https://user-images.githubusercontent.com/100659840/156100887-96bc5235-05e9-4e6f-adcd-a8e47022d17c.png">

Google Drive link of a sequence but this is happening with any sequence.  https://drive.google.com/file/d/1SsVpKdwZKSES0abQ4BBpSxKHF34QZo_f/view?usp=sharing

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
I cannot reproduce this.   Exporting video is working fine on both M1 based Mac's I have as well as my 2016 Intel MBP.     Can I have more details about the Mac that you are attempting this on?

**Comment by ponddude85** [comment]
I certainly can share details:

MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
2.8 GHz Quad-Core Intel Core i7
8 GB 2133 MHz LPDDR3
Macintosh HD
Intel Iris Plus Graphics 655 1536 MB

macOS Monterey Version 12.2.1

**Comment by Darzoom** [comment]
Same issue om 6.2 Pro 15-2016
2.6 i7
16gb

**Comment by Darzoom** [comment]
Here is the packaged sequence and a Model video I just created.

https://user-images.githubusercontent.com/81765092/159140110-87117f51-e1e5-4dee-b023-48216e19fda3.mp4

[Boneshaker.zip](https://github.com/smeighan/xLights/files/8310221/Boneshaker.zip)

**Comment by bacarudaguy** [comment]
Can say this is still present in 2022.06.2 - 2019 MBP 16" - AMD Radeon Pro 5300M 4 GB - Intel UHD Graphics 630 1536 MB.

Haven't encountered this issue until this release... 


https://user-images.githubusercontent.com/1183946/160040309-4dcda89c-be75-41ed-a0cd-357017704177.mp4

**Comment by ponddude85** [comment]
Still present in 2022.09

**Comment by AzGilrock** [comment]
I've never actually exported a video before just in case everyone wanted to know.

**Comment by cybercop23** [comment]
@ponddude85 can this be closed. Workig on newever version of Mac/14 & 2024.2
