### ISSUE TITLE
Cube Model - No zig zag - distorts pixels

### ISSUE THREAD

**Issue by jefft0825** [xLightsSequencer/xLights#3157]
Adding a cube model - once you click no zig zag, roughly half of the pixels turn bold and the other half are not - changing the pixel size does not fix it

Picture attached - test xlights layout attached

Windows 11 - 2022.6

![Cube Picture](https://user-images.githubusercontent.com/39816390/157485831-cf9100a4-936c-43e3-aa0e-486090e304de.png)
[Cube Issue.zip](https://github.com/smeighan/xLights/files/8216405/Cube.Issue.zip)

**Comment by keithsw1111** [comment]
That zip file seems to be empty

**Comment by keithsw1111** [comment]
Did you run check sequence ... sometimes we report what is wrong there.

**Comment by jefft0825** [comment]
No issues with Test Sequence 

If you change the height (pixel count) it changes the brightness on the back side of the cube.   If you lower it down, you they all look the same.    If you make it higher, the back gets dim

Forgot to save the sequence to generate the rgbeffects and networks as wel

Attached now
[Test Cube Issue.zip](https://github.com/smeighan/xLights/files/8223869/Test.Cube.Issue.zip)

**Comment by AzGilrock** [comment]
Does the look change when you zoom in and out?

**Comment by jefft0825** [comment]
No - zooming in and out does not change it.   Pan does not change it.   Making the pixel size bigger or smaller does not change it

**Comment by jefft0825** [comment]
Changing to Square helps but distorts the entire thing where the lines look jagged and not straight.    Its a workaruond but looks funky too

**Comment by harueg** [comment]
Hi
I've used the test cube model, thanks, set it to 16 x 16 x 16 nodes.
It renders wonderful on the preview screen. Some of the effects also do something 3Dish, looks nice.
My  question now : Are there any effects especially made for 3D matrices ? Or even something like videos ? Well, this would be a different story altogether ?
Thanks

**Comment by harueg** [comment]
https://www.youtube.com/watch?v=RdVZpPDMKp8

This is an interesting approach

**Comment by keithsw1111** [comment]
There are no effects made for 3D ... but using buffers and layers if you understand what you are doing it is possible to create 3D effects using a combination of 2D effects carefully applied.

**Comment by harueg** [comment]
Hi Keith
Thanks for the quick response !
Yep, that's what I already figured. Some Effects, especially Tindrell do make some 3D Effects.
And no, I don't understand what I am doing, but will have a look at the video about buffers.
Found this :
https://www.youtube.com/watch?v=tn_u4J69FOY
maybe it works the other way around as well.
