### ISSUE TITLE
Edit cell in Key Bindings window unviewable

### ISSUE THREAD

**Issue by Phippers** [xLightsSequencer/xLights#3167]
In the key bindings windows, the right most "window" where the key binding parameters are edited is not viewable until you stretch the window past the resolution of a normal monitor. See attached photos. 

The only way I was able to view it was expanding window size to two monitors.

Issue found on my Windows 10 & Macbook Pro.

![Capture](https://user-images.githubusercontent.com/79396182/160494063-7834aee6-5e03-4ec1-9e79-3153a78b41fe.PNG)
![Capture1](https://user-images.githubusercontent.com/79396182/160494064-91f762fe-d0f6-41c7-9308-2112219ce785.PNG)

**Comment by keithsw1111** [comment]
I dont seem to be able to reproduce the problem. on a 1920x1080 it displays ok ... what is your resolution? ... even 1280x1024 it works ok.

**Comment by cybercop23** [comment]
Is this still an issue? Seems okay on my Mac 14/2024.2. If not, please close.
