### ISSUE TITLE
AppImage hangs, closes and logs out

### ISSUE THREAD

**Issue by mkozik13** [xLightsSequencer/xLights#3180]
Good evening,

Have AppImage versions 2022-05, 06 and 07 on my Ubuntu Linux 21.10 machine.  Was working fine until yesterday when I tried opening a sequence for Easter.  I had created it last week, then when I went to open it again, I got a xLights is not responding [force quit or wait] dialog box.  If I wait about 30 seconds, the screen goes blank and then returns to the login screen.  When I log back in, xLights is closed.  I have tried this using each of the versions listed above with the same response.  I checked other sequences from last year Christmas and Halloween and they appear to be opening properly.  Not sure if it matters or not, but those sequences were created when I was using my Win10 machine.  I recently moved everything to Linux, but again, all has been working fine (faster even) up till this past week.  

I CAN say that OS updates were performed this week and I am guessing have lead to this issue, however, I am not savvy enough to know and understand which update may be causing the issue.  I looked through the FB page to see if anyone else was seeing this but did not find anything.

I appreciate your help in advance,

Mark

**Comment by mkozik13** [comment]
Still having this issue, now with 2022.08.  Any ideas from anyone?

Thanks in advance

**Comment by AzGilrock** [comment]
The lack of replies is because its Linux not because we aren't reading the issues.  Sorry we just don't have any developers that focus heavy on the Linux build.  I think Scott has tried a little bit.

**Comment by computergeek1507** [comment]
Dan updated the make file to the latest wxWidgets and the 2022.9 appimage is working on my Ubuntu 20.04 machine

**Comment by AzGilrock** [comment]
If its just a certain file I would troubleshoot it by deleting effects and seeing if it still crashes.  Start right down the middle and delete the 2nd half and see if it crashes.  Delete the first half see if that crashes.   Then you know which section to target and you can narrow down rather fast when you keep throwing away half at a time.

**Comment by mkozik13** [comment]
Thanks Gil - The issue is that I cannot get that far!  I open xLights, load the sequence, the app sits there with nothing happening and then finally shows the error and the message to either wait or force close.  If I wait, it will take some additional time and then log out and close xLights!  Anything I can do with the file directly?  I know that is a dangerous animal ....
