### ISSUE TITLE
OSX House Preview video export green screen

### ISSUE THREAD

**Issue by bacarudaguy** [xLightsSequencer/xLights#3188]
**Describe the bug**
When using Export House Preview Video on OSX 10.15.7, the entire exported video is all green. I've attached a system screenshot as well as a video preview of the green video. I've tried several different sequences and this issue has carried over from at least 2022.5 or so when I first noticed it.

**To Reproduce**
Open a sequence and export house video preview. When completed, finished export is all green.

**Expected behavior**
Should be a full sequence video of the house preview

**Screenshots**
Screenshot of system config. 
<img width="258" alt="Screen Shot 2022-04-06 at 1 29 10 PM" src="https://user-images.githubusercontent.com/1183946/162097490-deebe218-f0a6-4c31-b8c0-a82f3a524062.png">

**Versions (please complete the following information):**
OSX 10.15.7
XL 2022.07

https://user-images.githubusercontent.com/1183946/162097533-ca490985-f269-491b-8e64-8aec930e22d3.mp4

**Comment by bacarudaguy** [comment]
This seems to be the same issue as #3149

**Comment by cybercop23** [comment]
Is this an issue anymore? Seems okay on 14.3 with latest 2024.2 xlights. If not please close.
