### ISSUE TITLE
Copy Models - loses groups associated with that model

### ISSUE THREAD

**Issue by jefft0825** [xLightsSequencer/xLights#3190]
If you have a prop in a group or multiple groups, copy and paste does not keep the groups associated with that prop.  

Example - If you had 4 mini trees in a group and wanted to add 4 more, you would have to copy and paste them and then go back and manually add them to the existing groups that the originals were in

This gets pretty challenging if that model is in a lot of different groups having to go back and figure out which ones you need to add them to

**Comment by Poporacer** [comment]
I am not quite clear on your request, So you have 4 Mini Trees and they are in several groups, and you want to Copy and Paste those trees and it would automatically put those pasted trees into the same groups? If so, that could be very problematic. What if the trees were on the left side of your house and you had them in a group for left side but pasted them on the right side? In order for it to work, you would have to get an option box to select what groups that you want it copied to and I have a feeling that code would be very tedious. 
You mentioned that it is challenging to go back and figure out what groups a model is in? Do you know it identifies all of the groups that a model is in already?
![image](https://user-images.githubusercontent.com/46263877/162544095-9150828f-156a-47a7-a58a-c8b804f8a90e.png)

**Comment by jefft0825** [comment]
Copy a model, then paste it to duplicate it.  All the groups associated with the new “copy” are gone

**Comment by keithsw1111** [comment]
The problem with this is not how hard it would be to do ... but I dont think it is always true ... in fact maybe often true ... that you would want a copied model to be in the same groups as the original model. So that means now you need to distringuish when you do and dont want it to behave this way ... and it gets even worse if you consider the submodels.

**Comment by jefft0825** [comment]
For people that always work in groups or people
Who purchase sequences, they would almost always need the groups associated as the old model 

is there a way to make it an option?

or import groups from another model?

**Comment by jefft0825** [comment]
If I am adding 10 ppd wreaths, or 10 Gilbert HD props, I have to download them 1 by 1 and can’t use the copy/paste function as the groups associated with the models do not come in

**Comment by keithsw1111** [comment]
So if i take it as a given some would want the old behaviour and some the new (at least some of the time) ... how would you propose to distinguish between the two? Also is it possible that sometimes you would want to add it to the same groups and at other times you might want to create a new set of groups for the new model ... I can see people wanting that as well ... and maybe in the same paste operation. For example I want a group for each model of a set of submodels but i also want to add it to my all group.

Again ... not saying this is a bad idea but we have to have a full solution not a part one. The current behaviour is the safest as it doesn't do anything that then has to be undone ... but it does leave work for the user to do that the computer could do for them.

**Comment by jefft0825** [comment]
Any of the models in the download section that have groups for the submodels already attached to them, it would always need to be added to the same groups.    

Only time I could think of when copying a model that it really wouldn’t be added to the same group is if you are doing multiple groups for the same type of props.    -  (example - Trees left group and a Trees right group)


Is there a way to have a pop up message asking if you want to keep the groups associated with this model?   This way you have a choice to keep them with the model.  This really comes in handy on larger displays when needing to add a lot of the same model

**Comment by cybercop23** [comment]
How about let current flow be as is, and add a Right Click option to "Duplicate and Add to Same Groups"?

**Comment by jefft0825** [comment]
That would definitely work

**Comment by cbennett6008** [comment]
A couple things I thought of.

When pasting a model, a popup, (could be the same one as when you export a model with the group checkboxes), or would you like this group to be part of the groups of the source model,
Or a 'Paste Special' Where we could choose to paste with groups
Or let us select several props and right click, sync groups  (I think submodels on did-similar props would make this very challenging)

Being that we can export models with groups now, this is a workaround, but it doesnt' feel nearly as fluid as copy/paste.

**Comment by eatonaaron** [comment]
This would for sure be a time saver. When having a lot of the same models like arches or stakes or poles, would save time from having to manually do them all. Also you could add something about the controller they are on as well. If you want them to continue the controller chain or so on.

**Comment by wantmoore** [comment]
I like to believe that I'm a relatively savvy person when it comes to technology, but submodels and model groups not being able to be copy/pasted from a given model has been one of the strangest and most challenging things for someone new to xLights. It goes against expected "copy/paste" behavior of almost every other piece of software. Would love love love to be able to clone one.

**Comment by AzGilrock** [comment]
We don't need extra people piling on asking for the same thing unless you're showing up with cash.

**Comment by jefft0825** [comment]
I'll start the bidding at $5 😂

**Comment by AzGilrock** [comment]
When model copy/paste code was written submodels did not even exist nor did HD props with a billion submodels.   If it was bothering me I'd fix it but so far I hadn't even noticed.

**Comment by computergeek1507** [comment]
When I was working on a large drive through, this was really pissing me off. When copying models it sucked to add them to all the groups

**Comment by AzGilrock** [comment]
Yeah I didn't even know it wasn't copying the submodels.  Since I have an established layout I tend to just download 1 new model at a time.

**Comment by derwin12** [comment]
I believe this was implemented..
