### ISSUE TITLE
House Background Image

### ISSUE THREAD

**Issue by Garyb77** [xLightsSequencer/xLights#3197]
I have an issue in Xlights v 2022.07. y house background image is a grey square, tried many things. Went back to 2021.37 and works fine
![Background](https://user-images.githubusercontent.com/97515572/162567692-68d9195c-3e3a-4a38-bd3b-485001ed4061.png)
I have searched the forums to no avail any help would be appreciated.
The image is in my show folder but xlights will not display any image i try even though it shows the thumbnail preview. I am at a loss now so came here as i hope it may just be a simple bug fix
Many Thanks
Gary

**Comment by AzGilrock** [comment]
I’m going to guess you might be running an old OpenGL 1.0 video driver.  It’s over 20 years and we aren’t trying to support that anymore.  Update your video driver and if you say it’s already best it can be then next question is how old is the computer.  The picture you posted doesn’t help as much as if you did a Tools -> Package Log Files and give us that zip file and we would know all about your driver.

**Comment by djservice94** [comment]
I had the same issues, is a video driver issues, At least for me.

**Comment by cybercop23** [comment]
Is this still an issue?

**Comment by Garyb77** [comment]
Wow that was a while back lol. No mate. Unfortunately it was user error my
end and was resolved by upgrading GPU on my computer. Thanks for getting in
touch. I must have forgotten to take it down
Cheers
Gary
