### ISSUE TITLE
Submodel Bug

### ISSUE THREAD

**Issue by mc-sketchy** [xLightsSequencer/xLights#3224]
**Describe the bug**
When changing multiple SubModels in a Model, often after the second or third edit, all SubModels are frozen and edits cannot be made. You can begin editing again by saving or canceling and reopening the SubModel section.

**To Reproduce**
Video of bug:
https://user-images.githubusercontent.com/103663289/166304066-3baace34-3d8e-4761-8d44-7dfbaee5bd41.mov

1. Go to SubModel section
2. Click on any SubModel
3. Change something in the SubModel
4. Save or Cancel the changes5. 
5. Repeat steps 2-4 a few times and the SubModels should be frozen after one of the repeats.

**Expected behavior**
Nothing freezes and able to edit until done with Model

**Screenshots**
See video above

**Versions (please complete the following information):**
 - macOs: 12.3.1 (21E258)
 - xLights: 2022.09
 - Mac mini (M1, 2020)
 - Chip: Apple M1

**Additional context**
I have experienced this problem for as long as I can remember but just now submitting this report. 

**Attachments**
No crash reports and the bug is not related to a sequence

**Comment by cybercop23** [comment]
I have ran into this too. Same here.. just close and go back.

**Comment by derwin12** [comment]
Must be mac and wxWidgets? Cant duplicate on PC - perhaps fixed with the latest release of wxWidgets pushed.

**Comment by cybercop23** [comment]
Definitely a Mac thing and I'll try again with the latest wx to see if it's still happening

**Comment by cybercop23** [comment]
Tried several different ways and wasn't able to reproduce it. I'll keep trying, but looks promising.

**Comment by derwin12** [comment]
Lets call this closed as unreproducible.
