### ISSUE TITLE
3D view: Pan + Zoom stops working after a period of time

### ISSUE THREAD

**Issue by aukieranw** [xLightsSequencer/xLights#3233]
**Describe the bug**
The ability to pan and zoom in 3D view in my layout seems to stop working after a period of manipulating models. Everything works perfectly until it doesn't - can be hours or days and then _something_ I do upsets it. When using my mouse wheel to try and zoom, my view seems to pan up and down. When trying to pan around by clicking the middle mouse button and dragging, nothing happens. "Tilting" using the left mouse button still appears to work as expected.

The two things I've found to fix the issue are;
1 - exit the app and relaunch
2 - exit 3D mode, go into another show folder, enter + exit 3D mode in that show, then go back into my show folder and re-renter 3D mode there.

**To Reproduce**
I seem to have this issue rear its head mostly when trying to line up objects with features of my house, so when I'm moving my view around a lot to get an object exactly where I want it. I've attached my current layout as well as the logs from my current running instance.

**Expected behavior**
Expected behavior is exactly how the app  

**Screenshots**
Screen recording attached.

**Versions (please complete the following information):**
 - OS: Windows 11 currently. Issue was also present on Windows 10
 - xLights version: 2022.09. Issue has been present across all builds I have used since starting early this year.

**Attachments**

[Screen recording of issue]https://user-images.githubusercontent.com/1207661/167342671-55c8af94-1be7-4d9a-bd17-2dae34b03303.mp4
[Show folder zip](https://github.com/smeighan/xLights/files/8648811/Show.zip)
- Log package
[Log Package](https://github.com/smeighan/xLights/files/8648822/xLightsProblem.zip)

**Comment by CaCtus491** [comment]
I'm running into the same (or a similar issue) with 2022.17.
See the following recording: https://www.youtube.com/watch?v=yOUOgVio21U&t=120s

As per the video, right clicking and resetting the view seems to resolve the issue.

It only starts to happen with high levels of zoom.

**Comment by cybercop23** [comment]
Is this still an issue? I'm using 3d for 1.5+ years and have not ran into this issue. If no, please close.

**Comment by macmanluke** [comment]
I have this exact issue both on windows and mac - after a period of time working in 3d i loose the ability to pan and scrolling to zoom starts moving diagonally instead of zooming. Quitting fixes it but seems to happen again really soon.
