### ISSUE TITLE
xLights does not export model groups from Model exprot function

### ISSUE THREAD

**Issue by MrChristmas2000** [xLightsSequencer/xLights#3237]
Using 2022.9 xLights no longer export the 'Display as' ModelGroup to the excel .csv file.
I tried it in 2021.40 and is was working from that version.

**Comment by computergeek1507** [comment]
It is a separate sheet in excel

**Comment by computergeek1507** [comment]
Look at the tabs at the bott

**Comment by cybercop23** [comment]
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/9318bac2-b47f-4d9e-b98d-6aaa2071cb25)
