### ISSUE TITLE
Use State as Outline for faces effect no longer works

### ISSUE THREAD

**Issue by CSnead62** [xLightsSequencer/xLights#3244]
It appears the Use State as outline for faces no longer works.  the last i was able to get it to work was in 2022.06.  I just updated to 2022.10 from there. I went back to check 2022.08 and 2022.09 and it doesn't seem to be working there as well.  I have not checked 2022.07

I have verified that my states are still defined on the model.  however when using the face effect and select the show outline box and the select the drop down for the state the list is empty. When i try to load a sequence that I have used the state for the outline in. the face shows up as all white when i click on the face effect to make a change it will freeze it. 

To reproduce:

be sure you have a state defined for the model. 
create a face effect
check the box "show outline"
open the drop down box that says "use state as outline" - box will be empty

load a sequence that has the face effect outline with a state defined and click on the effect to change it.  

I can send a sequence privately if you would like to see it. Users were already able to repoduce in the official xlights group 

**Expected behavior**
I would expect it to work the same as 2022.06

**Screenshots**
 
![no state showing up on faces ](https://user-images.githubusercontent.com/105607424/168491424-e62a1c8b-e3e8-4bd9-b225-7a4ccf5d7982.jpg)
![States showing up](https://user-images.githubusercontent.com/105607424/168491425-9aac9e75-04f0-452f-9e3a-a6cc32ba434e.jpg)

working as intended in 2022.06
![2022 06 face states work in sequence](https://user-images.githubusercontent.com/105607424/168491426-dc175a87-0317-4bb1-8f5b-7563d20ac0a2.jpg)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.08 thru 2022.10

**Comment by CSnead62** [comment]
This issue still exist in 2022.11. however it no longer hangs up when selecting a color. if you want to change it.  Also as long as you dont click on the face effect it will still play with the normal state colors. but once you click on the effect it will default to all white once it renders.

**Comment by keithsw1111** [comment]
Is this still a problem and if so can you send us a sequence that shows it.
