### ISSUE TITLE
Xlights instant crash

### ISSUE THREAD

**Issue by dnnrwmb** [xLightsSequencer/xLights#3245]
I started playing with layer settings and found that I liked "Per Model Vertical Per Strand". It worked for a sequence in version 2022.9 until I tried to import the effects into a new sequence. It crashed the new sequence. Now whenever I select the setting Xlights crashes instantly. I triede going to version 2022.20 but Xlights kept locking up whenever I selected anything in my sequence. I stepped back to version 2022.8 but found the same issue with setting "Per Model Vertical Per Strand". Just tried "Per Model Horizontal Per Strand" and got an instant crash. The sequence that I used "Per Model Vertical Per Strand" is still OK.
I have an HP Elite Book with Intel Core I7 processor running Windows 10 Pro with plenty of spare RAM memory.

**Comment by AzGilrock** [comment]
Sounds like it’s something in your sequence.  If only we had a way to see it.

**Comment by derwin12** [comment]
Close this?
