### ISSUE TITLE
Enhancement: sort Models in Group by location

### ISSUE THREAD

**Issue by wiidaddy** [xLightsSequencer/xLights#3248]
Currently you can either sort Models in Group by Name or reposition those models, manually.

Since rendering within a group is affected by the order in which models are placed in the group. It would be very convienant to add an option to sort Models in Group by Location. Location would be determined by a model's  X, Y, Z, or any combination. I'll leave it up to the developers to decide which value to use. For example, if sorting by the X value then models would be sorted from left to right.

**Comment by AzGilrock** [comment]
Models inside a group are not rendered based on their order in the group as far as I remember.  Individual models are rendered based on the order they appear in the Master View.

**Comment by AzGilrock** [comment]
Per model default would be the only render buffer that would drill down to the individual models and I that case I can’t think of a reason order would matter.

**Comment by cybercop23** [comment]
Anything further to be done here?

**Comment by derwin12** [comment]
I think this is still valid .. as you can run a single strand effect for example down the group list and you want it to hit on the props say left to right across your yard. A new right click sort option seems viable.

**Comment by cybercop23** [comment]
Available in the nightly and next version.
