### ISSUE TITLE
Twin Rays And Acid Jelly Shaders Not Working

### ISSUE THREAD

**Issue by JacobSmith10** [xLightsSequencer/xLights#3254]
When loading the shader "Twin Rays" or "Acid Jelly" nothing shows up. it's just black and effects that may be placed underneath the shader will not show up.

When loading either of the shaders I mentioned before, they should show up on my layout, rather then doing nothing.

 - OS: [macOS Big Sur .]
 - xLights version [2022.11 May 21 2022]

**Comment by derwin12** [comment]
Just an FYI .. that this appears to be working in PC with .11. So perhaps a MAC render issue.

**Comment by cybercop23** [comment]
@JacobSmith10 is this still an issue on latest 2024.2 xLights?

**Comment by dkulp** [comment]
The seem to be working fine on the mac now.
