### ISSUE TITLE
crashing when rendering sequence

### ISSUE THREAD

**Issue by AL-Robert** [xLightsSequencer/xLights#3264]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug** render sequence and it crashes 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-4380-20220526T083348.zip](https://github.com/smeighan/xLights/files/8779496/xLights_dbgrpt-4380-20220526T083348.zip)
[xLights_dbgrpt-7792-20220506T142337.zip](https://github.com/smeighan/xLights/files/8779497/xLights_dbgrpt-7792-20220506T142337.zip)
[xLights_dbgrpt-8784-20220516T044509.zip](https://github.com/smeighan/xLights/files/8779498/xLights_dbgrpt-8784-20220516T044509.zip)

**Comment by derwin12** [comment]
@AL-Robert  - can you close this ticket? The logs show a problem with the codec either the audio track or the video files.
eg. Part two MOV.mov

As others have not had an error - and I assume you have this sequence working, there is unlikely anything that the devs can do.
You can re-encode the audio and/or the videos if you face this issue.

2022-05-06 14:23:37,170 7852 log_base [ERROR] ---------- WHVD: Failed to set media type : 0xc00d5212 : MF_E_TOPO_CODEC_NOT_FOUND
