### ISSUE TITLE
Allow display order of timing tracks to be changed per view

### ISSUE THREAD

**Issue by craiz** [xLightsSequencer/xLights#3275]
**Is your feature request related to a problem? Please describe.**
I would like to order my timing tracks in a specific order.  For example, lyrics on top, then beats, then per instrument.  The controls are there in the Display Elements window but the up/down buttons do not function on the timing tracks.

**Describe the solution you'd like**
Allow timing track order to be changed per view the same way the order of models and groups can be changed in the Display Elements window.

**Describe alternatives you've considered**
I've tried adding them in a specific order, which sort of works until I need to add a new one out of order.

**Comment by cybercop23** [comment]
You can no rearrange TT and even add them to other views. Please review and if it solves your request, please close.

**Comment by craiz** [comment]
@cybercop23 I assume you meant to say that "you can now rearrange...". I tried it on xLights 2024.02 and I can only change the order of timing tracks when selecting the Master View. Is that what is expected? Trying to change the order of TT in other views in the Display Elements window does nothing. I do see that changing the order in the Master View applies to the other views for that sequence. This will accomplish what I wanted to do. It does seem clunky and not intuitive how to do this. I normally only use the Master View to set the render order and don't look at it for sequencing and never paid attention to timing tracks in that view.

**Comment by AzGilrock** [comment]
Adding timing tracks to other views???   I need to check into this if someone made a change.  I'm not sure everyone understands the implications.  Timings do not existing in every sequence so it doesn't make sense to store timings in a View.  Timings are exclusive to each sequence.  That's why it seemed "clunky" cause it only made sense to reorder them in the sequence and the Master View is the sequence.  All other Views are global so you are not guaranteed to have that timing name in other sequences.

**Comment by cybercop23** [comment]
Sure does. Have a view for say... Characters and bring in a TT to know when and when to drop the Face effect for diff characters. Very very useful.

**Comment by AzGilrock** [comment]
Yeah but its messed up.  Just create a sequence, create a new timing, then create a new view with that timing.  Save everything.  Now create another new sequence and Edit Display Elements.  That new view you created does not show that new timing track you created.  In fact when I tried this it showed a completely different timing track.  People just don't know how things work when they change code.
