### ISSUE TITLE
MAC 3D Issue with navigation

### ISSUE THREAD

**Issue by SmartKartNotes** [xLightsSequencer/xLights#3278]
original layout was from 2019 all drawn up in sketches and worked fine.I got a new Mac mini M1 and old show folder works great on new computer. My house roof was drawn wrong so I scanned my house with Hover and made a new sketchup file, exported the OBJ and now I am unable to zoom in when I add the mesh file. No zoom, no pan, some left click movement.
[Mac 3D issue.zip](https://github.com/smeighan/xLights/files/8866188/Mac.3D.issue.zip)

**Comment by cybercop23** [comment]
@SmartKartNotes is this still an issue? Can it be closed?

**Comment by dkulp** [comment]
Closing.  Not enough information and no response from user.
