### ISSUE TITLE
import from lor

### ISSUE THREAD

**Issue by tgrinnall** [xLightsSequencer/xLights#3287]
the ripple effect isn't importing over correctly. this may be because on the lor side there is a few more features on the ripple effect. it just gives me a slow single ring. when its suppose to be like 5 different rings following each other. one of the effects starts at 4700ms. this effect is on the bulbs and icicles group. there is many other spots that uses the ripple effect in the sequence also. i was able to use the shockwave effect to get it close enough.

**Comment by tgrinnall** [comment]
the ripple effect isn't importing over correctly. this may be because on the lor side there is a few more features on the ripple effect. it just gives me a slow single ring. when its suppose to be like 5 different rings following each other. one of the effects starts at 4700ms. this effect is on the bulbs and icicles group. there is many other spots that uses the ripple effect in the sequence also. i was able to use the shockwave effect to get it close enough. 
[Uploading devil.zip…]()

**Comment by keithsw1111** [comment]
Without a sample loredit file (ideally with just the one effect) along with maybe a screen capture of what the effects look like there is not much we can do.
Bringing across the effect settings is something we can only do with good user provided examples.

**Comment by tgrinnall** [comment]
[WOWH-DevilWentDownToGeorgia-ProPlus for Keith.zip](https://github.com/smeighan/xLights/files/8952418/WOWH-DevilWentDownToGeorgia-ProPlus.for.Keith.zip)

**Comment by tgrinnall** [comment]
[20220621_145150.zip](https://github.com/smeighan/xLights/files/8952432/20220621_145150.zip)

this is what the effect does

**Comment by tgrinnall** [comment]
![Screenshot 2022-06-18 195259](https://user-images.githubusercontent.com/103583883/174887723-aa633b11-52de-448d-8f3f-bd624ec5099a.jpg)

these are the options i get in lor for the ripple effects

**Comment by keithsw1111** [comment]
This helps but it isnt perfect as the settings you show in the screen grab do not seem to correlate with anything in the file so i am left guessing which number is which. I also cant see the extreme values (upper and lower) so it is hard to be sure I am mapping the ranges correctly.

Finally i think we also have the problem that the LOW ripple is part xLights ripple and part xlights shockwave. I am not sure we are going to be able to accurately split them. There is also going to need to be some user tweaking.

Either way next release will have my cut at it. Feel free to add more information and i will try to fine tune it up to a point.

**Comment by cybercop23** [comment]
@tgrinnall is there any more info you need to procide to Keith on this?

**Comment by cybercop23** [comment]
Closed per Timmy.
