### ISSUE TITLE
Showing Controller connection failure despite being connected (Ubuntu 22.04)

### ISSUE THREAD

**Issue by Ipleadthe5th** [xLightsSequencer/xLights#3311]
Sequence is a very simple 2 string (150 pixels/ea across 2 outputs) running a 30 second Red, white & blue bars on loop.

**Describe the bug**
Running xLights 2022.13 on Ubuntu 22.04 (running USB wifi and Ethernet to Pixel controller), Both xLights and xSchedule claim to not be able to connect to my controller (Alphapix Flex) despite being able to open the web page for the controller AND being able to output to the controller. 
Biggest issue is that xSchedule can run a schedule despite showing red and counting failures, but can only do so for about 30min before something goes wrong resulting in my controller locking up and needing to be reset. 

**To Reproduce**
Run xLights on Ubuntu 22.04

**Expected behavior**
Both xLights and xSchdule should show green connection to controller.

**Versions (please complete the following information):**
 - OS: [Ubuntu 22.04 Desktop]
 - xLights version [2022.13]

**Additional context**
- Compiled using "make" command.
- "Check Schedule" shows no problems.
- IP is force set to the proper IP for the Ethernet port. 
- Have tested on my windows PC which shows green and can run a schedule indefinitely. Also had this issue when trying to run on Ubuntu 20.04_Server & xLights 2022.08.
- I'm newish to this github stuff and will provide whatever files are needed to help fix this. I know Ubuntu systems are kinda rare here.

**Comment by keithsw1111** [comment]
On no windows platforms xlights pings controllers by opening the controllers web page. It is possible the controller has a bug which is causing this to crash after a number of calls. Here is a web page (cut and paste it into a html file and open it in your browser. change the ip address to be your controller) it will load the root web page of your controller every 3 seconds (xlights does it every minute). If there is a bug in your controller i think this will prove it.

<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script>

            let count = 0;
        
            function success()
            {
                ++count;
                $('#pings').html(count);
            }
        
            async function callweb(url) {
                const response = await fetch(url, {   
                    method: 'GET', // *GET, POST, PUT, DELETE, etc.
                    mode: 'no-cors', // no-cors, *cors, same-origin
                    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
                    credentials: 'same-origin', // include, *same-origin, omit
                    headers: {
                        // 'Content-Type': 'application/x-www-form-urlencoded',
                    },
                    redirect: 'follow', // manual, *follow, error
                    referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
                    //body: JSON.stringify({}) // body data type must match "Content-Type" header
                });
                success();
            }
        
            $(document).ready(function() {
                var intervalId = window.setInterval(function(){
                    callweb($('#url').val());
                }, 3000);            
            });
            
        </script>
    </head>
    <body>
        <input type="text" id="url" value="http://192.168.0.1/" />
        <div id="pings">0</div>
    </body>
</html>

**Comment by Ipleadthe5th** [comment]
> 
Thanks Keith! Unfortunately that dosn't seem to be the problem. I can get to over 100 pings and the controller dosn't lock up. It usually locks up by the 30th "failure" on xSchedule. I should clarify that it only seems to be a problem with xSchedule.  As far as I've been able to tell, it works just indefinitely if I am just "running" a sequence on loop through the xLights sequencer. 
Really appreciate the help!
-Alan

**Comment by keithsw1111** [comment]
Once the controller locks up ... 

1. stop xSchedule
2. run xlights
3. send data to the controller

what happens.

**Comment by merryoncherry** [comment]
Some of those controllers hate doing web requests when they are processing data.  Can you do those 100 pings while the controller is being hit with data to output to lights?

**Comment by Ipleadthe5th** [comment]
> 
Keith, Usually once it locks up from running on xSchedule the controller is completely unresponsive and can't even be accessed through its web page; the controller needs to be power cycled to get it back. I am testing it again right now and will let you know in about an hour. 

Merryoncherry, I tried that just a little earlier with Keith's HTML file. When I was doing output through xLights while the HTML file was running it would freeze (even with only 1 or 2 pings), but as soon as I closed out the HTML file it would continue to work through xLights just fine. But ill try the 100 pings while xLights is outputting next to see if that causes a full lock up like im seeing with xSchedule.

**Comment by Ipleadthe5th** [comment]
Just tried to run xSchedule in "test mode" and it caused a lockup that required a power cycle in about 20min.
I dont know how important it is but perhaps I should mention that I do NOT have the PPA installed since im running Ubuntu 22.04 and the latest PPA is for 19.10 as far as I can see.
Its really killer that xLights can run on loop just fine but xSchedule is having so much trouble.

**Comment by merryoncherry** [comment]
Not sure xLights polls the controller like xSchedule does.  If it doesn't that pretty much explains it.  Using good firmware for the controller and all that?

**Comment by Ipleadthe5th** [comment]
As far as I know I am. Its a 6 month old Alphapix controller straight from Holidaycoro. It works just fine when I use xSchedule on my Windows10 laptop and desktop, but I know that dosnt mean much for this situation. Perhaps I should induce the lockup again and post the log? One thing that stick out so far is that is says "controller folders not found".

**Comment by keithsw1111** [comment]
xLights does not ping the controller like xSchedule does. Every minute xSchedule on Linux (not on windows) opens the root web page to see if the controller is online. This is clearly causing issues for the controller due to a bug in their firmware. I have looked at the code and I think it unlikely it is an xLights bug. While sure I could work around it by giving you a way to turn off the ping it would make more sense for the controller not to crash.

**Comment by Ipleadthe5th** [comment]
But if pinging the root web page was the problem, wouldn't it have locked up during the HTML file test?
Im going to try several other tests today such as running it without my USB WiFi addapter in to see if maybe its some issue with Ubuntus networkManager. Perhaps I need to get deeper into the network settings and better define the routes and so forth. 

I'm also not sure what caused it last night but I was able to get xSchedule to run for 110min before lockup (by far the longest run on this setup), has me suspecting the controller may be overheating since it was later at night that it worked? I will check for that today as well.
Again, than you all so much for your help on this rare and out there issue. This is an awesome community!

**Comment by Ipleadthe5th** [comment]
Just had a lockup with the case open and the power supply fan didn't even kick on on this cool morning so it looks like overheating isn't the problem.
Also reached out to HolidayCoro and they said the only knows reason for lockup is a "PING (ICMP) stream of data to the controller" and to "Make sure you are not running FPP or monitoring tools using ICMP."    Looks like you were right Keith. 
I did discover that in the update notes for xLights that the most recent fix for Alphapix flex firmware was in version 2020.25 for firmware 4.05. I am currently running 4.06. So I think I'll try rolling back to 4.05 and see what happens next.

**Comment by keithsw1111** [comment]
The ubuntu version of xLights/xSchedule does not send ICMP packets.
