### ISSUE TITLE
Layered arch model with non-zigzag wiring

### ISSUE THREAD

**Issue by merryoncherry** [xLightsSequencer/xLights#3313]
**Is your feature request related to a problem? Please describe.**
I have a layered arch made out of strips in tubes, no data wire coming out of the far end of the tube.  The best wiring for this is to have all the connections near the controller, but the existing arch model has wiring order that "zigzags", alternating direction with each layer of the arch, so in this configuration the wire from the controller has to go to the far end of the arch for some of the layers.  

**Describe the solution you'd like**
I'd like a checkbox on the arch model property grid that provides a wiring that doesn't zigzag, so that all the layers connect from the same end.

**Describe alternatives you've considered**
Of course, as it needs multiple connections to the controller, and #2466 for multiple controller connections isn't implemented yet, the easiest way to support it is a custom model, which is what I'll be doing.  But the easiest way to generate that custom model was by exporting the layered arch with non-zigzag wiring.

**Additional context**
A more detailed description of my prop, and the arch model, is here:
https://merryoncherry.org/2022/05/22/5-layer-pex-arch/

I also have a patch that implements this feature as I've described it.  As I already exported the custom model I'm now using, my problem is already solved and I don't really need the feature in xLights, but if you think other people might want to do something similar, I can make a PR.

**Comment by merryoncherry** [comment]
@cybercop23 Thanks for all the recent housecleaning.  You want the patch for this one or want it closed?

**Comment by AzGilrock** [comment]
If you already had a solution I'd post the PR.

**Comment by merryoncherry** [comment]
PR #4310

**Comment by cybercop23** [comment]
I see waiting on MR merge. Can this be closed?
