### ISSUE TITLE
option to select multiple props in visualizer

### ISSUE THREAD

**Issue by z28kid** [xLightsSequencer/xLights#3317]
**Is your feature request related to a problem? Please describe.**
if someone was wanting to move props from one port to another due to expansion. it can speed things up being able to drag several props at once.

**Describe the solution you'd like**
Being able to either draw a selection or use a shift/control click to select multiple props on the port in visualizer

**Describe alternatives you've considered**
the current process is to one by one drag and drop

**Comment by computergeek1507** [comment]
You can right click on the port number move all the models from one port to another

**Comment by z28kid** [comment]
However scott, moving all does just that. I have 12 driveway poles 6 on one port and 6 on another all 6 follow other props. I was just thinking having the ability to select pole 1 3 5 7 and move that to it's own port could be nice. I'm not sure how many people really move things around a lot. However as I have found, as I get additional controllers or props, I move things around to make sense for chaining props together.

**Comment by keithsw1111** [comment]
While i agree this would be nice it is a lot of work to build in. It also raises behavioural issues which are not obvious such as when you drag these multiple props what order should they drop in. Sure its easy i guess if they were already chained but if they werent you could still end up having to drag them all. If they are all similarly names (from a sort perspective) then moving them off and then using the double click method to add them after the currently selected model may be just as easy to do in practive. If you have to hunt through the list maybe not so much so.

**Comment by cybercop23** [comment]
You could use the Layout and multi-select and Bluk Edit Ctrl Ports. Seems like this is unlikely to be implemented. Shoudl this be closed especialluy given these alternatives?

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/d48da235-be68-47e1-8f17-008d45aa38a6)
