### ISSUE TITLE
Ability to Backup FPP Devices

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#3340]
**Describe the solution you'd like**
Now that FPP v6 is rolling out and people are starting to use licenses I think it would be a good option to include the ability to automate FPP backups from within xLights.

I think there are several places that this could be added.  Only 1 is needed.  The backup location would be the xLights backup path that is used for all the various XML files.

- New button on the controller tab that is available if the controller is fpp based.
- - Downside is it won't appear for FPP instances that are not controllers
- Option on FPP connect to create a backup
- xLights preference to automatically backup any found FPP instances.  Maybe run xScanner in the background

**Describe alternatives you've considered**
Use FPP WebUI for this.

**Comment by MrPaulAR** [comment]
I'm talking about the FPP configuration that's generated on /backup.php and
not anything else.

The downside of a local backup is it doesn't help when the SD dies.

**Comment by derwin12** [comment]
Seems redundant with the fpp functionality. They have the ability to copy to usb or other fpp devices.
