### ISSUE TITLE
Custom model issue

### ISSUE THREAD

**Issue by jlpjindiana1983** [xLightsSequencer/xLights#3344]
When I go to create a costume model the picture keeps showing up sideways. I’ve tried outside of xlights to to rotate it to correct it but no matter what I do it’s sideways as the back ground picture trying to create the costume model. I’ve also tried rotating it in xlights and nothing Changes.

**Comment by keithsw1111** [comment]
The image loader in xlights requires the image to be actually rotated. OS rotation often does not do this. Try using a program to rotate the image and resave it.
