### ISSUE TITLE
Importing effects crashes xLights

### ISSUE THREAD

**Issue by cmora111** [xLightsSequencer/xLights#3348]
I downloaded Rick Harris' Heros sequence.
I selected new sequence and traversed to the location of the mp3, it loaded fine.
I then went to the import->import effects
traversed to the directories to the xsq file, selected it and in crashed with the the following:

Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Bail out! Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Aborted (core dumped)

The machine is a Alienware 51x running Ubuntu 22.04 Kernel 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux.

**Comment by cmora111** [comment]
Sorry forgot the xLights version:  xLights-2022.14-x86_64.AppImage

**Comment by cmora111** [comment]
$ ./xLights 
bash: ./xLights: Permission denied
mora@spectrix:~/Projects/xLights(15:32:11)$ chmod 755 xLights
mora@spectrix:~/Projects/xLights(15:32:40)$ ./xLights 
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 15:32:45.706: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:32:45.707: Failed to load module "canberra-gtk-module"
[mp3float @ 0x55a5007b9680] Could not update timestamps for skipped samples.
[mp3float @ 0x55a5007b9680] Could not update timestamps for discarded samples.
[mp3float @ 0x55a5007b9680] Could not update timestamps for skipped samples.
[mp3float @ 0x55a5007b9680] Could not update timestamps for discarded samples.

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:29.226: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:29.233: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:29.235: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
WaveForm - glVer:  4.6 (Core Profile) Mesa 22.0.1  (Mesa Intel(R) HD Graphics 4600 (HSW GT2))(Intel)
EffectGrid - glVer:  4.6 (Core Profile) Mesa 22.0.1  (Mesa Intel(R) HD Graphics 4600 (HSW GT2))(Intel)
TimeDisplay - glVer:  4.6 (Core Profile) Mesa 22.0.1  (Mesa Intel(R) HD Graphics 4600 (HSW GT2))(Intel)
ModelPreview - glVer:  4.6 (Core Profile) Mesa 22.0.1  (Mesa Intel(R) HD Graphics 4600 (HSW GT2))(Intel)
Preview - glVer:  4.6 (Core Profile) Mesa 22.0.1  (Mesa Intel(R) HD Graphics 4600 (HSW GT2))(Intel)

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:29.709: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:31.951: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:31.953: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:31.954: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:32.090: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:32.096: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:32.098: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:32.219: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:32.224: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:32.226: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:32.286: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:33.735: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:33.743: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:33.746: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-WARNING **: 15:33:33.913: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:33.921: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:33.923: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:33.997: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:665244): Gtk-CRITICAL **: 15:33:33.997: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
**
Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Bail out! Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Aborted (core dumped)

Not sure why the canberra-gtk-module is not loading:

$ sudo apt install libcanberra-gtk-module
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcanberra-gtk-module is already the newest version (0.30-10ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by keithsw1111** [comment]
Without giving us a copy of the files there is not much we can do to help.

**Comment by bmcghee1101** [comment]
I'm having the exact same issue using the same version of Ubuntu.

**Comment by cmora111** [comment]
What I did as a workaround was to I selected new sequence on the top panel, loaded the mp3. Then went to file->open sequence and loaded the filename.xsq sequence file. then setup the sequence that way

**Comment by bmcghee1101** [comment]
I did the same thing as a work around but the mapping of the effects was much more difficult to do. Tonight I'm going to try it again and see if I can get more information on the issue. Its something with Ubuntu 22.04. I tried the other night on 20.04 and it worked fine.

**Comment by cmora111** [comment]
Very strange. I will try and get more info as wll. Thanks for the response.

**Comment by bmcghee1101** [comment]
I tried it again. All I did was open xlights, create a musical sequence, then import effects. 
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 20:07:20.648: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:07:20.776: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:07:20.779: Failed to load module "canberra-gtk-module"
[mp3float @ 0x55619bb9c000] Could not update timestamps for skipped samples.
[mp3float @ 0x55619bb9c000] Could not update timestamps for discarded samples.
[mp3float @ 0x55619bb9c000] Could not update timestamps for skipped samples.
[mp3float @ 0x55619bb9c000] Could not update timestamps for discarded samples.

(AppRun.wrapped:7030): Gtk-WARNING **: 20:07:49.969: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:7030): Gtk-CRITICAL **: 20:07:49.979: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:7030): Gtk-CRITICAL **: 20:07:49.982: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
WaveForm - glVer:  3.3.0 NVIDIA 470.141.03  (Quadro P400/PCIe/SSE2)(NVIDIA Corporation)
EffectGrid - glVer:  3.3.0 NVIDIA 470.141.03  (Quadro P400/PCIe/SSE2)(NVIDIA Corporation)
TimeDisplay - glVer:  3.3.0 NVIDIA 470.141.03  (Quadro P400/PCIe/SSE2)(NVIDIA Corporation)
ModelPreview - glVer:  3.3.0 NVIDIA 470.141.03  (Quadro P400/PCIe/SSE2)(NVIDIA Corporation)
Preview - glVer:  3.3.0 NVIDIA 470.141.03  (Quadro P400/PCIe/SSE2)(NVIDIA Corporation)

(AppRun.wrapped:7030): Gtk-WARNING **: 20:07:51.747: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)
**
Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Bail out! Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Aborted (core dumped)

The last three lines are what I get when I try to import the effects. This is running xlights-2022.16-x86_64.AppImage on Ubuntu 22.04

**Comment by briggtr** [comment]
System:  Ubuntu 22.04.5 LTS
**Crashing** xLights Versions:  
xLights-2022.17-x86_64.AppImage
xLights-2022.11-x86_64.AppImage

**Working** xLights version:
xLights-2021.40-x86_64.AppImage

I am getting the following error in the 2022 versions I have tried when xLights crashes:
**Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
Bail out! Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))**

Sequence I am doing:
Load xLights
Sequence -> File -> New Sequence
Musical Sequence
Choose an Audio File
Choose 40fps
Choose Done
Import -> Import Effects
Choose zipped sequence
Click Open
Popup Appears about extracting sequence 
- on 2022 version xLights then crashes
- on 2021 version xLights pops up a "Map Channels" window and xLights does NOT crash

**Comment by keithsw1111** [comment]
Still no files provided.

**Comment by fone626** [comment]
It appears that any version from 2022.09 to current crashes when importing any and all sequences.  2022.08 and earlier work correctly.

**Comment by keithsw1111** [comment]
And yet still no files provided ... going to need to close this one as no one seems to be willing to help identify the issue.

**Comment by fone626** [comment]
> And yet still no files provided ... going to need to close this one as no one seems to be willing to help identify the issue.

What files would you like?  Literally ANY sequence will crash xLights.  I just created a sequence with a single on effect and tried to import it and it crashed.
It's also crashing hard without offing to write a crash report or I would happily send you that.

I ran strace and the part that seems to matter looks like this:
.....
brk(0x5595d3d5b000)                     = 0x5595d3d5b000
brk(0x5595d3d7c000)                     = 0x5595d3d7c000
brk(0x5595d3d9d000)                     = 0x5595d3d9d000
brk(0x5595d3dbe000)                     = 0x5595d3dbe000
write(2, "**\nGtk:ERROR:../../../../gtk/gtk"..., 123**
Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
) = 123
write(1, "Bail out! Gtk:ERROR:../../../../"..., 130Bail out! Gtk:ERROR:../../../../gtk/gtkrbtree.c:471:_gtk_rbtree_insert_after: assertion failed: (_gtk_rbtree_is_nil (tree->root))
) = 130
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
gettid()                                = 2489653
getpid()                                = 2489653
tgkill(2489653, 2489653, SIGABRT)       = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2489653, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)

**Comment by computergeek1507** [comment]
Are you using the appimage or building from source?

**Comment by fone626** [comment]
> Are you using the appimage or building from source?

I've done both with the same results

**Comment by keithsw1111** [comment]
Ideally you would send us the sequence you are trying to import. You would also create the empty sequence you are looking to import into, save it and then package it as well. That would let us load up your layout and import into that.

**Comment by fone626** [comment]
> Ideally you would send us the sequence you are trying to import.
[crash.zip](https://github.com/smeighan/xLights/files/9692004/crash.zip)
Sorry for not sending this sooner.  The crash does seem to have something to do with my layout.  I tried to make it easy for you by making a layout with a single strand and I was able to get the import to show up without an immediate crash, so attached is my whole config that does crash.  Any sequence I've tried to import with cause a crash so I've just packaged a sequence with just a single on effect in it that has been verified to cause a crash it every time.

**Comment by TechplexEngineer** [comment]
Hit this on xlights 2022.19 trying to import https://drive.google.com/file/d/1f05WoUKAgbl63-iU-mLyGY-DUWlDjD58/view
[xLightsProblem-gtk.zip](https://github.com/smeighan/xLights/files/10118307/xLightsProblem-gtk.zip)

**Comment by keithsw1111** [comment]
> Hit this on xlights 2022.19 trying to import https://drive.google.com/file/d/1f05WoUKAgbl63-iU-mLyGY-DUWlDjD58/view [xLightsProblem-gtk.zip](https://github.com/smeighan/xLights/files/10118307/xLightsProblem-gtk.zip)

Does it still fail on the current version?

**Comment by TechplexEngineer** [comment]
@keithsw1111 I as was able to complete the import in 2022.22 and 2022.23 but trying to render crashes.

```
TimeDisplay - glVer:  4.6 (Core Profile) Mesa 21.2.6  (Mesa Intel(R) UHD Graphics (TGL GT1))(Intel)
Preview - glVer:  4.6 (Core Profile) Mesa 21.2.6  (Mesa Intel(R) UHD Graphics (TGL GT1))(Intel)
08:32:19: Error: Directory '/tmp/xLights_dbgrpt-412314-20221130T083219' couldn't be created (error 17: File exists)
08:32:19: Error: Failed to create directory "/tmp/xLights_dbgrpt-412314-20221130T083219" (error 0: Success)
08:32:19: Error: Debug report couldn't be created.
```

It says it failed to create the directory but that directory exists. Here are its contents.

[xLights_dbgrpt-412314-20221130T083219.zip](https://github.com/smeighan/xLights/files/10123643/xLights_dbgrpt-412314-20221130T083219.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/10123653/xLightsProblem.zip)
[XATW Light of Christmas - atw.xsq.zip](https://github.com/smeighan/xLights/files/10123656/XATW.Light.of.Christmas.-.atw.xsq.zip)

**Comment by cybercop23** [comment]
Is this still an issue? If not, please close it.

**Comment by cmora111** [comment]
I'm not sure because I found a workaround for the issue. Last time I checked it was still an issue.
 
Carlos

**Comment by cybercop23** [comment]
Okay, we need someone to check this issue, else we'll close it and can be reopened if necessary.

**Comment by AzGilrock** [comment]
I’d say any issues about crashes that are over a year old need to just be closed and a new issue opened if it crashes again.  Just too many changes for any of the old logs to be relevant

**Comment by cybercop23** [comment]
Adree. Don't want to overstep my bounds and loose my newly acquired "rights". :)

**Comment by cmora111** [comment]
agreed.
 
Carlos
