### ISSUE TITLE
Enhancement for the model export function.

### ISSUE THREAD

**Issue by MrChristmas2000** [xLightsSequencer/xLights#3357]
**Is your feature request related to a problem? No it would provide more sequence info though..

After opening a sequence and doing a model export, add an extra excel sheet that gives one all the models that have effects applied to them.

 If a sequence is not open skip it.

No additional comment at this time.

**Comment by keithsw1111** [comment]
Why not just use tools export effects?

**Comment by cybercop23** [comment]
@MrChristmas2000 does this fit your solution? Can't say I ever used it, but seems to have a lot of info there.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/f8de65b9-a50d-4d9e-aef3-a23057d4b21b)
