### ISSUE TITLE
Draw model in sub models not working

### ISSUE THREAD

**Issue by jettrobombino** [xLightsSequencer/xLights#3380]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When clicking on pixels in the draw model, its not selecting them. Only way i could even show what i am talking about is me clicking the select all button and it actually selects them all but when i select a box of them shown on the bottom picture to be removed from the selection and press ok it never removed them from the selection shown in top picture. Same goes for just selecting them. Having to input every single row individually in all my sub models has been time consuming haha.

**To Reproduce**
Click one of your models.
go to sub models and click the button.
Click add new sub model or even edit one.
Click draw model button
Try and select one pixel or multiple, it always goes back to white
click ok
nothing happens.....

**Expected behavior**
Before when i selected draw model it would specifically create each custom model i made. 

**Screenshots**
![Xlights draw model issue 2](https://user-images.githubusercontent.com/111618762/185722704-839c3d01-cd51-43a8-adb8-b7a9739ec3f7.png)
![Xlights draw model issue 1](https://user-images.githubusercontent.com/111618762/185722701-682e1617-d3fe-4906-a60c-149395903492.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.15 64 bit

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
John K in zoom also notes that the data shown in the draw model is not the same as the model data for his larger custom model.
He tried going back a number of different versions and never found a working version.

**Comment by derwin12** [comment]
Looks fine in the preview
![image](https://user-images.githubusercontent.com/4643499/187101087-299af742-4adb-415e-b836-e70bf9c9d3c9.png)
Click Draw Model and it gives you the finger :-)
![image](https://user-images.githubusercontent.com/4643499/187101107-7b67cafa-07b8-49c0-aead-a712981d4bf2.png)

[Matrix Entry.xmodel.txt](https://github.com/smeighan/xLights/files/9440734/Matrix.Entry.xmodel.txt)

**Comment by computergeek1507** [comment]
fix the check sequence warning and see if it fixes it
![image](https://user-images.githubusercontent.com/2293065/187114171-6f9734f6-a4de-46d7-bbf8-fb4e124457fc.png)

**Comment by computergeek1507** [comment]
![image](https://user-images.githubusercontent.com/2293065/187119765-16fdc8b0-b772-4f5a-91ab-1a1134e0a06b.png)

**Comment by computergeek1507** [comment]
![image](https://user-images.githubusercontent.com/2293065/187119813-763f1620-e954-45cb-afcd-dcf987492092.png)

**Comment by derwin12** [comment]
Good catch! We will pass this along to John K.

**Comment by keithsw1111** [comment]
Is this closed?

**Comment by derwin12** [comment]
I believe it can be.. The author confirmed it was working in zoom.

**Comment by jettrobombino** [comment]
Don't know why, but it still isn't working on my computer. Might be something wrong with my xlights and need to uninstall and reinstall it. I will pickup a headset today so I can join a zoom call and see if someone can help me out on it. Thank You!

**Comment by computergeek1507** [comment]
The user Daryl was referring to, we fixed in zoom(we fixed the duplicate nodes), the person who made the original issues I have not seen in there to help.

**Comment by AzGilrock** [comment]
I'm just going by what Daryl said.  "The author"...

**Comment by cybercop23** [comment]
@jettrobombino please confirm this is not an issue for you, else this will be closed.

**Comment by jettrobombino** [comment]
This is no longer an issue. Thank You!
