### ISSUE TITLE
Xlights Freezes (not responding) when House Preview is on second monitor

### ISSUE THREAD

**Issue by Chuckytt** [xLightsSequencer/xLights#3385]
On win 10 with three monitors. I have Xlights on the Primary monitor (LG 2560×1080) then the house preview on a second monitor (MSI  2560×1440). I also have a third monitor (cheap vizio TV 1920x1080). 
If I undock the house preview and put it on either of the secondary monitors and set it as a custom perspective in the sequencer. The next time I open the sequence tab Xlights goes into a freeze state (Not Responding). This seems to be common on a lot of version. Their seems to be an issue with using multiple displays, as if I disable all but my primary monitor, I have no issues. Once I enable a second monitor and try to launch xlights sequencer tab instant freeze.
The only way to get the house preview to show is by clicking on (view > perspectives > Dock All). 

I have heard to put Xlights on the primary monitor to help solve the issue, which it did help a little, but it would be nice to have a saved perspective where the house preview doesn't need to be re-docked just to view. 

System: 
Intel 10700K
RTX 3080 GFX Card
32gb RAM DDR4
850w PSU
Xlights is on a drive with 400GB of open storage.

**Comment by Fonzi03** [comment]
Odd, I have tried on my PC and my Laptop with no issues. I have my laptop going through a thunderbolt dock and extended to 2 additional displays and put the preview on display 3 and xlights on display 2. I always run my house preview and model preview on a second monitor and have never had this issue. 
mon1: 2560x1600
mon2: 3440x1440
mon3: 1080x2560

**Comment by keithsw1111** [comment]
These issues are almost always video driver related.
