### ISSUE TITLE
Moving Head color problem

### ISSUE THREAD

**Issue by stealthyoshi** [xLightsSequencer/xLights#3386]
3D moving head model no longer displays a beam in visualizer if the value entered on the color chanel isn't assigned to anything.  Prior to .16 if you entered a value that wasn't assigned, it would just be a white beam.

**Comment by derwin12** [comment]
Cant duplicate in later versions of 2022. R/G/B/W were set to 0 but the beam still shows in visualiser. Still the case in 2024.12.
