### ISSUE TITLE
Enhancement request: add Generic Serial Variant for FPP

### ISSUE THREAD

**Issue by patdelaney** [xLightsSequencer/xLights#3391]
**Is your feature request related to a problem? Please describe.**

Users would like the ability to Select a Serial Output as a variant of FPP. There are 2 use cases that I can think of at this point.
•	DMX dongle for DMX devices
•	LOR Dongle for LOR controllers

There are uses cases to support 2 serial devices, one for DUMB DMX lights and one for LOR controllers (I used to do it that way before I moved those outputs off FPP to Falcon controllers)

The main reason is so that users can use the visualizer to setup their DMX and LOR props. Currently users have to select a Pihat configuration so that the serial device shows up in the visualizer. It’s kind of a hack work around.  It would be much better of USB serial devices was an Option.

We are aware that the USB serial devices must be attached in a specific order because if using 2 devices the tty ports could get flip flopped.

submitted on behalf of John Larson

**Comment by dkulp** [comment]
Some of this is already there....    If you add a "USB" device in xLights, you can use Vendor/Model of FPP for both and the FPP stuff will be enabled.  You can set the FPP protocol to use, the ip address, the FPP ttyS or ttyUSB port, etc...

**Comment by cybercop23** [comment]
@patdelaney does Dan's suggestion fit your need? If so, can this be closed?
