### ISSUE TITLE
Cut and Paste Error?

### ISSUE THREAD

**Issue by mborgetti** [xLightsSequencer/xLights#3417]
The version of xLights used: 2022.17
The platform you are running it on: MacSO Monterey

Problem: Having two instances of xLights open cannot copy a model effect(s) from one sequence to a sequence opening the in the second instance of xLights

1) Open two instances of xLights with two different show directories/network configs (Yours and then the layout of the sequence you purchased)
2) Open a sequence in both instances of xLights
3) Copy all the effects from one model
4) Click on a model in the second instance sequence ... PROBLEM: Paste is still greyed out so you cannot paste the effects

**Comment by computergeek1507** [comment]
You need to do a copy in the second instance first to fake out the copy/paste logic

**Comment by derwin12** [comment]
It cant be coded .. the fix was noted above.
