### ISSUE TITLE
Upload to San Devices e682 and e6804 broken.

### ISSUE THREAD

**Issue by MDickson00** [xLightsSequencer/xLights#3418]
When uploading from xlights to San Devices e682 and e6804 via xlights fails on firmware version 5.x.

When uploading the with the upload input and upload outpu buttons linked together, the upload input will fail to connect.

We have been able to fix this issue by un-linking the upload input and upload output buttons and using the upload output button only.

**Comment by darylc** [comment]
Keith was trying to work on the San Devices upload a few weeks ago, but his San Device is stuck on v4.x firmware and won't upgrade.  He could do with a donation of a 5.x San Device controller to ensure xLights supports v5.x properly.  Maybe your observation may be enough to help him guess how to fix it.

**Comment by MDickson00** [comment]
Daryl, there is a fix for the firmware update as well, San Devices recently
released a new "boot loader" which fixes the upgrade issue. It can be found
on the following page and is called "fwloader_1_0"

**Comment by MDickson00** [comment]
Link https://sandevices.com/sandevices-technical-support/

**Comment by darylc** [comment]
@MDickson00 FYI Keith's sandevice controller still doesn't take the upgrade so this is unlikely to be fixed in the short term.

**Comment by MDickson00** [comment]
We have a work around for now so it's not a major bug. Some of the guys
that had problems upgrading said that the san device must not have any kind
of network connection to get it to upgrade.

**Comment by keithsw1111** [comment]
@computergeek1507 has a v5 san devices I believe. Maybe he can reproduce it.

**Comment by computergeek1507** [comment]
I will look at it. The v5 firmware has two "pages" and the http parameters are the same for each page. I think the constructor switches the pages to a known initial state. It may also be something related to not delaying enough between calls.

**Comment by wjdean76** [comment]
Can confirm this is still an issue. Just updated my 2 E682 to the 5.081 firmware and xLights cannot upload inputs and outputs.

**Comment by cybercop23** [comment]
@wjdean76 can you please re-test with the latest version of xLights, 2024.2? There were some issues arounf 2023.19-ish but they should have been fixed.
