### ISSUE TITLE
Model render export creates corrupt file if Low Render Export preference is checked - via xlights or script

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#3437]
If the Low Definition Render is set in preference .. no matter what is scripted the file is 1kb and "corrupt".
Works fine if the preference is left unchecked.

Tried using RenderExportModel.lua for this.. seems like the property is not used.  The results of the export is the same if I run it like this:
(I never actually tried the xldo code, but assume the results are the same)

`RunCommand('renderAll', {} )`

Or this..

```
properties = {}
properties['highdef'] = 'true'	
RunCommand('renderAll', properties)
```

The preceding and remaining script is the production xlights git code...
```
models_str = RunCommand('getModels', {})
models = models_str['models']

sel_model = PromptSelection(models,'Select Model')
<<
RunCommand as above
<<
properties = {}
properties['model'] = sel_model
properties['format'] = 'avicompressed'
properties['filename'] = sel_model .. ".mp4"
Log(properties['filename'])
Log(properties['model'])

```

https://user-images.githubusercontent.com/4643499/191621346-0acd9590-71ba-4d9c-887e-b226ba9bac91.mp4

**Comment by computergeek1507** [comment]
Only the "exportModelWithRender" command supports the highdef parameter

**Comment by derwin12** [comment]
so simple fix is to not renderall first? and just use the one command? I will try that out...

**Comment by derwin12** [comment]
Same result .. if the preference is selected, it creates a 0-1kb corrupt file. Ignores the parameter or something..

**Comment by freman** [comment]
I think I'm having the same issue but using the xlDo api.

```
xlDo '{"cmd":"loadSequence", "seq":"sequence/BeforeXmas/Grinch 2.xsq", "promptIssues":"false"}'
xlDo '{"cmd":"renderAll", "highdef":"false"};'
xlDo '{"cmd":"uploadSequence", "ip":"10.0.0.249", "media":"false", "format":"v2std", "seq":"sequence/BeforeXmas/Grinch 2.xsq"}'
xlDo '{"cmd":"closeSequence"}'
```

Doesn't matter if I use highdef:true or highdef:false I get a 1.3k fseq

**Comment by dkulp** [comment]
I believe you would need to do a save in there.   Upload only uploads based on the fseq file on the disk.

**Comment by freman** [comment]
> I believe you would need to do a save in there. Upload only uploads based on the fseq file on the disk.

This does indeed seem to fix my issue but if I haven't saved why did my fseq get corrupted?

**Comment by dkulp** [comment]
I'm not sure if it's corrupted.  If it didn't save, it's likely all black.   All black compresses VERY well and would result in a very small sequence.

**Comment by freman** [comment]
Ah ok, I assumed it was corrupted because it was so small and nothing was displayed. I've managed to accidentally achieve the same thing in UI and xlDo but now I can't replicated it. You can probably safely ignore my data point.

**Comment by derwin12** [comment]
Doing some basic tracing via debugger and it it seems the lowdefinitionrender export just doesnt create a valid mp4 file. Not really a scripting issue at this point.
Preference set to low render definition
Matrix set to a 5 factor for render factor
Right click on model, model->render and export.
Exported file is not valid.
