### ISSUE TITLE
Corrupt rgb effects file

### ISSUE THREAD

**Issue by z28kid** [xLightsSequencer/xLights#3459]
The rgb effects file got corrupt while I was trying to follow your example of creating candy cane sticks and poly line sticks. for a peace stakes. 
I first tried to make poles using poly line and changed the drop pattern to a neg. value, I then deleted that and then followed Keiths method of using the candy cane model, I changed the settings to match 6 poles and 25 pixels per pole. I rotated the model 90* in 3d view, scaled and resized. I hit save, then deleted the model and saved my layout to basically undo any changes I had made. I then went to my controller tab because I was needing to move props around on one of my controllers. I went to open a second instance of xlights and then a warning came up about not being able to locate my rgb effects file. I tried to rename the xbkp to xml which did not work either.

[xlights_rgbeffects.xml.zip](https://github.com/smeighan/xLights/files/9720607/xlights_rgbeffects.xml.zip)

**Comment by AzGilrock** [comment]
When you say "your example" who are you talking about?

**Comment by z28kid** [comment]
Gil,
the "your" was Keith at the time. He was in zoom and mentioned how he had made peace stakes and gave suggestions to make them using other models when they might be in a straight line as they were in my case.
