### ISSUE TITLE
Crash on Render with 2022.19 on Mac OSX

### ISSUE THREAD

**Issue by bigwavedave42** [xLightsSequencer/xLights#3466]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am having issues with xLights fully crashing when trying to render a sequence.  It is consistent on OSX.  I have been able to successfully render it on Windows 10, which leads me to believe it is not related to the sequence per-se.  I also used this same sequence last year (2021.37ish era) and did not have this problem.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Load sequence
2. Ensure Shaders are mapped.
3. Run Check Sequence
4. Click Save or run Render All
5. Crash...

**Expected behavior**
I would expect it to render successfully.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac 12.6
 - xLights version 2022.19

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced

https://drive.google.com/drive/folders/1sRpQFXBoxDJ9DZNot2Uc5EXya3ha_Qrg?usp=sharing

The link includes a crash report and the sequence

**Comment by cybercop23** [comment]
Is still still an issue?

**Comment by bigwavedave42** [comment]
oof, forgot all about this, it was so long ago!  I'll close this as it is over a year ago and many versions ago!
