### ISSUE TITLE
FPP Connect closes without finishing

### ISSUE THREAD

**Issue by chuckackerman** [xLightsSequencer/xLights#3467]
Weird anomaly in FPP Connect...

When I send a new sequence to FPP (I have 4 of them) via FPP connect it sends just fine.  If I try to send it again it immediately stops and returns xLights.

This happens for any file that already exists on the FPP controllers.  If FPP Connect comes across a file that already exists FPP Connect stops and returns to xLights.

This is a huge problem if I've indicated that I want to send a lot of sequences to FPP because once it comes across a sequence that it already knows about it immediately stops and returns to xLights not finishing the rest.  This is a pain when uploading over 80 sequences.  I didn't even know this was happening for the last several weeks and was pulling my hair out trying to figure out why my sequences weren't right.

It's almost as if xLights didn't have permission to delete the old file before writing the new file.

I've mitigated this by deleting all of the FSEQ files on all FPPs before uploading but that's kind of a drag.

I'm on xLights 2022.19 (but this issue showed up on earlier versions) and FPP 6.1.1. on all Pi's.

**Comment by cybercop23** [comment]
Is this still an issue? Please try with latest xLights, 2024.2 and FPP 7.5. If no further issues, please close.
