### ISSUE TITLE
Upload to ESPixelstick Crashing xLights

### ISSUE THREAD

**Issue by jazakrzewski** [xLightsSequencer/xLights#3469]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Upload to ESPixelstick is crashing

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

Setup a controller with ESPixelstick v4 and then upload ouputs

**Expected behavior**
A clear and concise description of what you expected to happen and why.

Outputs uploaded to controller

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

Windows 10
xLights 2022.19
ESPixelstick v4 development

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-18772-20221012T174944.zip](https://github.com/smeighan/xLights/files/9768898/xLights_dbgrpt-18772-20221012T174944.zip)

**Comment by jazakrzewski** [comment]
After additional testing, the issue occurs when skipping a port in your assignment

![image](https://user-images.githubusercontent.com/58450237/195860413-033dbfd1-517e-4f51-bd6a-d31e453e79d6.png)

**Comment by robdmiller** [comment]
I had this as well, moving everything up to fill the void fixed.  I just moved from WLED where the gap wasn't a problem.

**Comment by cybercop23** [comment]
@jazakrzewski @robdmiller please test with the latest ESP f/w Beta 5 and latest xLights.
