### ISSUE TITLE
Music keeps playing after pressing STOP button

### ISSUE THREAD

**Issue by sheisler314** [xLightsSequencer/xLights#3471]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Sometimes, when playing the sequence it will keep playing after you press the stop button.  The preview window stops but the sound/music keeps playing. Prior versions did not do this.

**To Reproduce**
Unable to reproduce consistently, happens on random sequences, one that it happened with today is attached.
**Expected behavior**

**Screenshots**
Can't provide screen shots as it happens randomly.

**Versions (please complete the following i
[TSO-WizardWinter.zip](https://github.com/smeighan/xLights/files/9780901/TSO-WizardWinter.zip)
nformation):**
 - OS: Windows 10 21H2
 - xLights version: 2022.19

**Comment by derwin12** [comment]
Take note on your windows task bar -- might it still be doing a (background) render?

**Comment by sheisler314** [comment]
It's done this several times since I posted this.  No rendering (I use the feature on the bar to pop-open the window and watch for items that slow-render all the time) and no savings going on either.  The song will play all the way to the end but nothing is going on with the sequence on the house preview.  The only way to stop the music when this happens is to either close Xlights or Close the sequence, then the music stops playing.  This happens on multiple sequences on 3 different computers that I use to work on sequencing.

**Comment by keithsw1111** [comment]
Is this still a problem ... if this was common i would have expected to see a lot more noise about it.

**Comment by cybercop23** [comment]
@sheisler314 still having issues? If not, pelase close.
