### ISSUE TITLE
Rotate handle on layered arches is quite tall.

### ISSUE THREAD

**Issue by MDickson00** [xLightsSequencer/xLights#3473]
When building or in some cases importing a layered arch into the layout it creates an extremely tall rotate handle, the more layers you add the taller it gets,

1. create a new arch model in layout
2. choose layered arch
3. ad x number of layers
4. ad x number of pixels per layer
5. watch the model handle grow.

See attached screenshot.

![prop handle bug](https://user-images.githubusercontent.com/83371818/195743693-23d5b1e0-824b-4fe1-bc03-abaa6c67c2df.png)

**Comment by cybercop23** [comment]
Implemented and merged to master. Please test in nightly (preferred) or next version.
