### ISSUE TITLE
xLights background photo of house disappeared in layout after update. Have tried uploading several photos and they show up as a white box,

### ISSUE THREAD

**Issue by swswswn** [xLightsSequencer/xLights#3477]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Was this an update from last year's xlights? If so they updated the video/ui and it likely means your open gl windows drivers are out of date. See if there are updated drivers on your video driver company's website. If you want to go to tools->package logs and upload that here it might help to diagnose the issue.

**Comment by swswswn** [comment]
The update was for Oct 4 2022.  XLights 19

**Comment by swswswn** [comment]
and, Yes it was from Jan, 2022

**Comment by Sparky2211** [comment]
@swswswn, were you ever able to get this resolved? I've updated my drivers and still no luck with my background image.

**Comment by cybercop23** [comment]
@swswswn @Sparky2211 is still still an issue? If so please provide logs from the latest xlights version, else, please close it.
