### ISSUE TITLE
Crash on Play following Save and Render following Effects Import

### ISSUE THREAD

**Issue by gnedge** [xLightsSequencer/xLights#3488]
**LINK to two separate crash reports under same circumstances in different versions of xLights available on demand.**

This issue occurs intermittently but frequently enough now that I have workaround steps in my mind.  The issue is as follows:

1) Open Sequence
2) Import Effects into that sequence
3) Render
4) Play
5) Crash

It doesn't happen with every sequence, only some and it does not happen every time and it has happened across the last several versions including the most recent update.

The workaround to avoid losing work is to "Save" between Render and Play.  Following the crash, subsequent opens of the sequence and plays work perfectly, it's just the sequence of events above.  I am unable to consistently repro but given this has now happened more than 20 times under the exact same circumstances, I am attaching the error report.

**Versions (please complete the following information):**
 - OS: Win11
 - xLights version 2022.20 64bit

**Comment by AzGilrock** [comment]
There nothing attached and you can’t attach over email

**Comment by gnedge** [comment]
As I said at the top of the report:  "LINK to two separate crash reports under same circumstances in different versions of xLights available on demand."  The crash contains sequence elements I purchased therefore I will not share it publicly.

**Comment by AzGilrock** [comment]
> The workaround to avoid losing work is to "Save" between Render and Play. Following the crash, subsequent opens of the sequence and plays work perfectly, it's just the sequence of events above. I am unable to consistently repro but given this has now happened more than 20 times under the exact same circumstances, **I am attaching the error report.**

I’m referring to where you said you were attaching the error report boss

**Comment by gnedge** [comment]
> I’m referring to where you said you were attaching the error report boss

Attached with a complimentary virtual coffee :)  Note three subfolders illustrating same issue across three separate crashes under same circumstances spanning two different versions of xLights.

[Crash.zip](https://github.com/smeighan/xLights/files/9839323/Crash.zip)

**Comment by keithsw1111** [comment]
Is this still happening?

**Comment by cybercop23** [comment]
@gnedge is still still and issue? If so, please provide updated logs using the latest xlights version. If no longer an issue, please close.
