### ISSUE TITLE
layout model position doesn't save

### ISSUE THREAD

**Issue by MrRyanM** [xLightsSequencer/xLights#3509]
When resizing the models panel in the layout. The panel size does not save and I have to resize it every time I open the application

<img width="487" alt="image" src="https://user-images.githubusercontent.com/55702933/198861120-17b2c1e0-cbd4-4df5-b73f-f3ae29e74b07.png">

**Comment by MrRyanM** [comment]
Also display elements. I am using a 4k monitor

<img width="296" alt="image" src="https://user-images.githubusercontent.com/55702933/198861511-7afb2f6b-9bb9-414c-91c6-d82f870cb58e.png">

**Comment by keithsw1111** [comment]
The layout panel splitters do save and restore. Are you sure you dont mean the columns in the list?

There are no splitters in the display elements. Again are you referring to the columns. Note the column in available in your image is small because there are no models. If there were models then it would be wider.

**Comment by ptr727** [comment]
I noticed the same behavior, panel sizes are not saved, need to resize every time, also 4K monitor and Win11.

**Comment by MrRyanM** [comment]
https://user-images.githubusercontent.com/55702933/200127445-8b03dbd0-67f3-4437-aacc-4930f1afbe96.mp4

**Comment by MrRyanM** [comment]
Any fix for this?

**Comment by AzGilrock** [comment]
Like Keith said xLights does attempt to save the splitter position in the registry.  Maybe Windows 11 is blocking it.  BTW...the Perspectives have nothing to do with those splitter positions so don't bother saving that.  Have you tried quitting the program with the file menu instead of the red x?

**Comment by computergeek1507** [comment]
I found when working on the Submodels dialog, we normally load and set the position settings in the dialog constructor, when the dialog is shown, wx calls the layout method which overrides these values, I had to move the load code into a separate method that happens later.

**Comment by computergeek1507** [comment]
https://github.com/smeighan/xLights/commit/44ca0b0b9e8a605732c1b9f3bd3c79a3064e88a3

**Comment by AzGilrock** [comment]
Yep I saw that code when I was working on a new dialog using the Submodels dialog for reference.  If that's the problem then it must have changed behavior because I know that splitter position used to save correctly.

**Comment by MrRyanM** [comment]
Great Thanks everyone!

**Comment by cybercop23** [comment]
@MrRyanM  can this be closed?
