### ISSUE TITLE
Experience Lights Controller being limited to 680 pixels per port

### ISSUE THREAD

**Issue by vman916** [xLightsSequencer/xLights#3515]
I was setting up my Christmas layout yesterday and assigned 682 pixels to a single port in the Visualizer.  I received ERR: Pixel port 1 has 682 nodes allocated but maximum is 680.  I know their ports are supposed to support unlimited pixels, but even if not, 680 seems very low, so wanted to report it as a potential bug?

**Comment by AzGilrock** [comment]
You know there are physical limitations to how much data you can send to a WS28xx chip per second.  If you go over 680 you won't be able to refresh the pixels at 40 fps which is what a lot of the sequencers use these days.  So even if they fix the config to let you do this be aware you'll need to stick with 20 fps sequencing.

**Comment by computergeek1507** [comment]
I have to look at it. xLights doesn't have an "unlimited" option at the moment. If you add too many it will lower the frame rate as Gil suggested.

**Comment by vman916** [comment]
Thank you for the reminder about that but right now (at least for this year) I do not plan to add another receiver in that yard for this year at least, but thank you guys for the quick response.

**Comment by computergeek1507** [comment]
If you want a "quick fix", go to "C:\Program Files\xLights\controllers" and open the experience.xcontroller file with notepad. Change the "MaxPixelPortChannels" value to be 4000, save and restart xLights

**Comment by vman916** [comment]
Perfect!  Thank you.

**Comment by cybercop23** [comment]
Changed... <MaxPixelPortChannels>6000</MaxPixelPortChannels>
