### ISSUE TITLE
xLights 2022.22 crash when moving effects around (LInux)

### ISSUE THREAD

**Issue by m00dawg** [xLightsSequencer/xLights#3553]
**Describe the bug**
2022.22 is crashing nearly non-stop for me. It appears to be due to trying to copy or otherwise move effects in the sequence editor. This is for existing shows as well as creating a new show, as seen from the screencast below. It seems to happen with multiple effect types but seems to be the On and Single Strand effects, possibly others. 2022.20 does not have this problem (unless I tend to try and copy/paste certain effects too quickly).

It looks like it might be related to a channel that points to a group. In my case a group of groups.

**To Reproduce**

[Screencast 2022-11-11 22:33:52.webm](https://user-images.githubusercontent.com/226504/201457251-9dc35db5-e21f-415f-8644-8bf5dde48d22.webm)

(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Open xLights
2. Go to File->New
3. Create an Animation, Select 50fps
4. Place an effect on a channel that belongs to a group
5. Try to move the effect.

**Expected behavior**
In 2022.20, I'm able to adjust and copy or cut and paste the effect to other channels.

**Versions (please complete the following information):**
 - OS: Linux Mint 21 (Ubuntu 22.04)
 - xLights: 2022.22 (AppImage)

**Additional context**
I think 2022.21 may also have this issue. I noticed when it crashes, it gives me an interesting error that the directory to put the debug info already exists. I haven't seen that in previous versions of xLights, though I'm not sure if that's related.

[debug.tar.gz](https://github.com/smeighan/xLights/files/9994109/debug.tar.gz)

**Comment by m00dawg** [comment]
Additional context, it looks like 2022.22 writes files in the current directory the AppImage was executed in (namely some xml files and backups of the open sequence) as opposed to the directory the sequence file is located in or a normal xLights directory.

**Comment by ouinouin** [comment]
Hi, same issue here, using ubuntu 22.04.
it crashes while dragging the effects or sometimes while scaling the time, but basically renders soft unable to be used. in my setup there is only a simple matrix 5x5 no groups nothing.

[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/9995869/xLights_l4cpp.log)
[backtrace.txt](https://github.com/smeighan/xLights/files/9995870/backtrace.txt)

**Comment by extremeskillz** [comment]
same issue here with 20.04lts. I reverted back to 2022.5 as its the only version not crashing the system on anything at the moment.

**Comment by toddejohnson** [comment]
When this happens on my Linux systems with AppImage (2022.22-master) I also receive in the console :

```
19:12:23: Error: Directory '/tmp/xLights_dbgrpt-220268-20221117T191223' couldn't be created (error 17: File exists)
19:12:23: Error: Failed to create directory "/tmp/xLights_dbgrpt-220268-20221117T191223" (error 0: Success)
19:12:23: Error: Debug report couldn't be created.
```

It looks like it doesn't check if the folder exists when it tries to create it. Do we need a separate issue for this?

**Comment by m00dawg** [comment]
This also seems to be happening on 2022.23 as well.

**Comment by josh-holt** [comment]
I see the same issue with Ubuntu 22.10 and xLights 2022.23 AppImage. The crash occurs pretty randomly when interacting with the timeline and edit controls in the Sequencer interface. For me, I see the same "Failed to create directory" error for the debug report, but the report still saves anyway. I think that is a separate issue since the backlog in that folder points to an exception interacting with gtk3.

```
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN14xlCrashHandler11HandleCrashEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1009) [0x558022ebf729]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN11xlGLBaseApp16OnFatalExceptionEv+0x52) [0x558022441bc2]
/tmp/.mount_xLightjTr8tr/usr/bin/../lib/libwx_gtk3u-3.3.so.0(+0x6fee26) [0x7ffa5d0fee26]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bcf0) [0x7ffa5c23bcf0]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN9RenderJob11GetwxStatusEv+0x51) [0x55802285c921]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN9RenderJob11LogToLoggerEi+0xb3) [0x55802285dc93]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN9RenderJob7ProcessEv+0xc4) [0x558022861184]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN13JobPoolWorker10ProcessJobEP3Job+0x24d) [0x5580229a69dd]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(_ZN13JobPoolWorker5EntryEv+0xf7) [0x5580229a6de7]
/tmp/.mount_xLightjTr8tr/AppRun.wrapped(+0x1429ffa) [0x5580229a6ffa]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc3a3) [0x7ffa5c6dc3a3]
/lib/x86_64-linux-gnu/libc.so.6(+0x90402) [0x7ffa5c290402]
/lib/x86_64-linux-gnu/libc.so.6(+0x11f590) [0x7ffa5c31f590]
```

I downgraded to the xLights 2022.20 AppImage and everything seems stable so far.

**Comment by s0meguy1** [comment]
I am having the same issue using Appimage on ubuntu 22.04 on versions 2022.21-23.

It seems to just happen randomly, 2022.20 still works, but I am unable to use any newer version

**Comment by cybercop23** [comment]
@m00dawg is still still an issue on latest version? If not, pelase close.

**Comment by s0meguy1** [comment]
> @m00dawg is still still an issue on latest version? If not, pelase close.

I don't know about everyone else, however I'm on Ubuntu 23.10, had no issues this past Christmas with xlights. Never did understand what happened with my system the year prior. Same hardware but I was using Ubuntu 22.04 last year when I commented with the same issue.
