### ISSUE TITLE
xSchedule not responding to Received FPP events

### ISSUE THREAD

**Issue by GrizAF** [xLightsSequencer/xLights#3557]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xSchedule is not responding to FPP events even though the log is seeing them

To verify - I have added FPP events within xSchedule, and I have also tried adding them on advanced playlists (although that should only be for transmitting events, I believe)

Not sure why it is receiving the event, but not triggering what the event is setup to perform.

Thank you for your help!

**To Reproduce**
Create an FPP event that does not require a button (e.g. toggle on off mute) and create a button to fire that event
Or
Replicate with an F48v4 by creating an FPP event from the Input tab - it does not matter what major/minor numbers are set - none of them work

**Expected behavior**
Expect xSchedule to respond to the FPP event and respond based on chosen event in the drop down

**Screenshots**
Log is uploaded (see Bottom of log)

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2022.22

**Additional context**

**Attachments**
Log attached
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/9998316/xSchedule_l4cpp.log)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by GrizAF** [comment]
To verify - I have added FPP events within xSchedule, and I have also tried adding them on advanced playlists (although that should only be for transmitting events, I believe)

Not sure why it is receiving the event, but not triggering what the event is setup to perform. 

Thank you for your help!

**Comment by cybercop23** [comment]
@GrizAF have you found a solution for this? Newer FPP versions now use Command Presets vs Events. So of this is still an issue and you are looking for a solution, please update the post with the latest info you have tried, including the versions of xlights and fpp. Please re-test with the latest versions if you need/want a working solution.

If no longer an issue for you, please close.
