### ISSUE TITLE
Add Flip Horizontal (et al) as Warp Effect option(s) -- Enhancement

### ISSUE THREAD

**Issue by steveking16** [xLightsSequencer/xLights#3572]
I have two (semi) mega trees, one on each side of my display,  I like to "mirror" them for most effects.  I build the Left hand tree (or import into it) first.  There are often dozens of effects built.  It would be nice to copy all those to the other tree and then just lay a flip horizontal warp effect over the top of the second tree (where applicable).

It's not as simple as selecting all the effects and doing a bulk edit on the layer setting transformation.  Rather it is goin through each effect and adjusting it correctly - Rotate CC90 to Rotate CW 90, Flip Vertical to Rotate 180, None to Flip Horizontal.

This could also be useful on various groups of props - for example, left and right mini-tree, or even and odd ones.

I thought about just making a group of the two trees and then apply the mirror effect on that, but it doesn't work right.
I know I can export tree one to video and then flip the video horizontally on tree two, but that doesn't  always work well.

There are likely use cases for the other Layer Setting transformations, but flip horizontal in the one i'm drooling on.

**Comment by keithsw1111** [comment]
Why not just export the first model as a video ... then use the video effect with a flipped buffer on the second model. Alternatively you could bulk edit flip the buffer ... but this only works if you have not used other buffer styles on some effects.

**Comment by steveking16** [comment]
Exporting a video of a tree does work in that specific case.  Most of the time, this means copying the source prop, to another prop, and exporting the second prop and adding two layers above - the video and an OFF effect -- so you still have the source if you need to edit anythig. Unless there is any text or other effect in the middle of the sequence that you don't want to flip.  Yes there on convolutions you can use to manage those: 
  - flip the effect first, export video, flip the video which unflips the effect, or
 - copy the affected effects above the video and "off" the section you don't want to flip (doubling the number of layers on the copy tree).
But just laying down a warp where you want to flip would be easier.
This also doesn't work as well if the original and the copy don't match exactly, for example odd and even mini-trees, or my garage matrix (24x60) and my "tune-to" P5 panel.  The P5 gets the matrix effects (mirrored) at 70% brightness, and then "tune-to" and song/artist text scrolling over.  I often have to edit the effects to adjust for being on a P5 vs a lower res matrix.  
The edit using a video export process involves moving the text and former video off, edit the effects, reexport the remainder, then replace the text and video (likely with an Off effect under the imported video to hide the source effects).  
The OFF effect "hides" any full house or other group effects that might impact this.
This would all be easier with a warp that transforms the "canvas" below
