### ISSUE TITLE
2022.22 Crashes while running controller discovery to update DDP Hostnames

### ISSUE THREAD

**Issue by davidcharlessmith516** [xLightsSequencer/xLights#3579]
Running controller discovery one time to discover new devices picks up the devices on my network, but some show the hostname while others show DDP_192.168.XXX.XXX. Some research into this issue led me to discover the running controller discovery again could pick up more hostnames. Now, when I run discovery with no new controllers to discover, in an attempt to pick up the hostname for each device, xLights crashes. I have been able to reliably reproduce this issue.

[xLights_dbgrpt-4264-20221119T235753.zip](https://github.com/smeighan/xLights/files/10048909/xLights_dbgrpt-4264-20221119T235753.zip)
[xLights_dbgrpt-11552-20221120T000037.zip](https://github.com/smeighan/xLights/files/10048913/xLights_dbgrpt-11552-20221120T000037.zip)
[xLights_dbgrpt-7676-20221120T000135.zip](https://github.com/smeighan/xLights/files/10048912/xLights_dbgrpt-7676-20221120T000135.zip)
[xLights_dbgrpt-4136-20221120T000202.zip](https://github.com/smeighan/xLights/files/10048908/xLights_dbgrpt-4136-20221120T000202.zip)
[xLights_dbgrpt-13688-20221120T000352.zip](https://github.com/smeighan/xLights/files/10048914/xLights_dbgrpt-13688-20221120T000352.zip)
[xLights_dbgrpt-7576-20221120T000529.zip](https://github.com/smeighan/xLights/files/10048910/xLights_dbgrpt-7576-20221120T000529.zip)
[xLights_dbgrpt-7616-20221120T000812.zip](https://github.com/smeighan/xLights/files/10048911/xLights_dbgrpt-7616-20221120T000812.zip)

**Comment by cybercop23** [comment]
@davidcharlessmith516 can you try this with the latest version and/or close this issue?
