### ISSUE TITLE
2022.23 Lots of crashes while adjusting sequence parameters on Linux AppImage build

### ISSUE THREAD

**Issue by nhendin** [xLightsSequencer/xLights#3582]
I'm seeing lots of crashes on Linux (Ubuntu 2022.04.1 LTS).

I have a simple sequence and a layout with one model, a 50 pixel line, using DDP protocol to a controller running WLED over wifi.
That all works fine, but if I edit settings of an effect (the one I tested was setting the style parameter on the Butterfly effect. If I adjust it too quickly it will hang and stop outputting to the lights. Some times the UI freezes and I have to restart sometimes I can turn the "output to lights" off and on and it comes back,

Here's what I get in the console logs.
This does not seem to happen on WIndows.

Thank you for reading. Let me know If I can provide anything else.

neil@orac:wled-xlights$ ~/bin/xLights-2022.23-x86_64.AppImage &
[1] 102445
neil@orac:wled-xlights$ ./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(59): assert ""traits"" failed in Get(): create wxApp before calling this
Gtk-Message: 23:39:38.875: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:39:38.876: Failed to load module "canberra-gtk-module"

(AppRun.wrapped:102445): Gtk-WARNING **: 23:39:49.845: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:49.845: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:49.845: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(AppRun.wrapped:102445): Gtk-WARNING **: 23:39:49.845: gtk_widget_size_allocate(): attempt to allocate widget with width 6 and height -7

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:49.845: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Layout - glVer:  3.3.0 NVIDIA 515.65.01  (NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2)(NVIDIA Corporation)

(AppRun.wrapped:102445): Gtk-WARNING **: 23:39:54.257: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:54.263: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:54.264: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
WaveForm - glVer:  3.3.0 NVIDIA 515.65.01  (NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2)(NVIDIA Corporation)
EffectGrid - glVer:  3.3.0 NVIDIA 515.65.01  (NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2)(NVIDIA Corporation)
TimeDisplay - glVer:  3.3.0 NVIDIA 515.65.01  (NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2)(NVIDIA Corporation)
ModelPreview - glVer:  3.3.0 NVIDIA 515.65.01  (NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2)(NVIDIA Corporation)
Preview - glVer:  3.3.0 NVIDIA 515.65.01  (NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2)(NVIDIA Corporation)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:54.688: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:39:54.689: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-WARNING **: 23:40:01.188: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:40:01.192: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:40:01.193: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-WARNING **: 23:40:01.532: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-WARNING **: 23:40:43.767: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:40:43.767: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:40:43.768: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-WARNING **: 23:40:43.991: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-WARNING **: 23:40:44.263: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:40:44.267: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:40:44.268: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-WARNING **: 23:40:44.506: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-WARNING **: 23:41:12.657: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:41:12.657: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:41:12.657: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-WARNING **: 23:41:13.015: Negative content width -9 (allocation 25, extents 17x17) while allocating gadget (node button, owner GtkButton)

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:41:13.019: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(AppRun.wrapped:102445): Gtk-CRITICAL **: 23:41:13.021: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

**Comment by nhendin** [comment]
Added some of the debug logs, the ones I was able to atttach.


[backtrace.txt](https://github.com/smeighan/xLights/files/10062558/backtrace.txt)
[xLights_l4cpp.log](https://github.com/smeighan/xLights/files/10062559/xLights_l4cpp.log)

**Comment by cybercop23** [comment]
@nhendin if this is resolved, can you please close it?
