### ISSUE TITLE
Render Issue

### ISSUE THREAD

**Issue by Titanhunter99** [xLightsSequencer/xLights#3585]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
xLights crashes (shuts down) during rendering.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Sequencer
2. Click on Render
3. xLights shuts down

**Expected behavior**
A successful rendering of all layers

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version [ 2022.23]

**Additional context**
Possible issue with the number of layers used in the sequence? This was a purchased sequence but I can share with devs if necessary.

**Attachments**
Log file attached
[xLights_dbgrpt-10280-20221121T175638.zip](https://github.com/smeighan/xLights/files/10061456/xLights_dbgrpt-10280-20221121T175638.zip)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
The log shows a LOT of corruption in the Render Cache.   I would suggest deleting your entire  D:\xLights\xLights\2021 Show\RenderCache\ directory and re-trying.

**Comment by Titanhunter99** [comment]
Done that already. I'm thinking its with the purchased sequence. I'm in the process of importing effects one at a time, maybe I can find the culprit.

**Comment by keithsw1111** [comment]
Then you will need to package the sequence and send it to one of the devs.

**Comment by Titanhunter99** [comment]
Prolly will end up sending. Just wanna make sure it's not my machine first. The log also shows a memory allocation issue. It does seem to fault out when rendering a shockwave and pinwheel effect imported to some of my models.

**Comment by cybercop23** [comment]
@Titanhunter99 any updates on this? Or can this be closed?

**Comment by Titanhunter99** [comment]
Can be closed thanks
