### ISSUE TITLE
xLights Scheduler 2022.23 64bit Locks When Using Network Drive

### ISSUE THREAD

**Issue by justaplane** [xLightsSequencer/xLights#3590]
Version: 2022.23 64-bit
Software: Xlights Scheduler

OS: Windows 10

Issue: Sequences are stored locally on the same computer xscheduler and xlights is installed on, however show files used (i.e. Music, shaders, etc) are stored on a Synology rackstation that is on 24/7. It is mounted as Drive Z: and locally accessible. When running the schedule after aproximately 10 mins, the scheduler will lock up and will not become unlocked until you manually go and open the network folder and click around a bit (almost as if it's not keeping it alive). I do not have this issue with any other programs that access the NAS. It seems to be an issue directly related to the scheduler.

**Comment by derwin12** [comment]
Was this an issue in prior releases? Can u downgrade to confirm?

**Comment by cybercop23** [comment]
@justaplane is this still an issue? Can you please retest with the latest versions and if no further issues, please close?
