### ISSUE TITLE
Sequencer House Preview, bulb size changing autonomously

### ISSUE THREAD

**Issue by socal8995** [xLightsSequencer/xLights#3596]
I don't think attaching a sequence will show this issue.

**Describe the bug**
The pixel size on my layout for my rooflines, as set by the "Pixel Size" attribute, will randomly increase size in my house preview. The first time it happened I decremented the size by 1 for each string in the rooflines, then incremented each of them back to size 5. This temporarily fixed it.

**To Reproduce**
I don't know how to reproduce this. I have not noticed a recurring pattern yet of what triggers it.

**Expected behavior**
The pixel size on the house preview does not change size.

**Screenshots**
I have attached 2. The first shot is from the House Preview as seen while sequencing (some roofline bulbs grow larger). The second is the house preview as seen from the layout tab (bulbs are the correct size per Pixel Size setting). Not screenshot 2 from the Layout tab, was taken after screenshot 1.

**Versions (please complete the following information):**
 - OS: Win10
 - xLights version: 2022_23 64 bit

**Additional context**
![Screenshot 2022-11-26 153504](https://user-images.githubusercontent.com/119140504/204112828-f33c65a4-6529-4e4c-9aa9-437364f929d3.png)

![Screenshot 2022-11-26 153625](https://user-images.githubusercontent.com/119140504/204112832-77e61e98-f1a0-449e-a6a0-829395b85777.png)

**Comment by cybercop23** [comment]
@socal8995 is still still a thing with the latest version? IDK if it was fixed, but without a way to recreate the issue, it will be hard to do anything. Please try again with the latest version and see if its still happening.
