### ISSUE TITLE
"Create Random Effects" does not respect "Select Effects for Generate Random" setting/preferences

### ISSUE THREAD

**Issue by BigLep** [xLightsSequencer/xLights#3601]
**Describe the bug**
I specified only a couple of effects that I would like in Preferences → Random Effects
![IMG_5967](https://user-images.githubusercontent.com/85411/204445312-202531dd-e2fb-48df-829b-cd30613e8483.jpeg)

When I "Create Random Effects"...
![IMG_0273](https://user-images.githubusercontent.com/85411/204445366-0bd89f5b-3f0e-4f50-b7dd-0f1c2dd63f90.jpeg)

Different effects are applied than what I had set in my preferences:
![IMG_8869](https://user-images.githubusercontent.com/85411/204445416-af6b4834-f721-4009-a490-2dc98bb3f1cb.jpeg)

**Expected behavior**
I expect the random effects to only be the ones I selected in my settings.  In this case I had only selected "On" and "Off".

(my usecase is that I am trying to generate random On / Offs for my AC controller)

**Screenshots**
Inlined above.

**Versions (please complete the following information):**
 - OS: macOS 13.0.1
 - xLights version: 2022.23

**Additional context**
None

**Attachments**
None

**Comment by cybercop23** [comment]
@BigLep can tou please close this issue?
