### ISSUE TITLE
Problem with Xlights and QuinLed Dig Quad

### ISSUE THREAD

**Issue by chickenrun81** [xLightsSequencer/xLights#3607]
Hi everybody.
I'm french. sorry for my english wrotten.

Since a few week i bought a QuinLed Dig Quad drive by Wled.
With QuinLed i have only 4 ports connected on GPIO 16, 3, 1 and 4
When i configure my channels with wled i assigned output1 to GPIO3 and output 2 to GPIO16, as you can see in this picture
![1](https://user-images.githubusercontent.com/114053880/205257501-4abef42c-47ee-4211-ac7c-890c73fb4847.png)

With Xlights i set controller like that:
![2](https://user-images.githubusercontent.com/114053880/205257900-3f9a2299-2be4-4918-864f-21287aa62cd8.png)
I'm right?

and my layout like that:
![3](https://user-images.githubusercontent.com/114053880/205258131-e6f6b029-95fc-4d31-8933-111e80ec6bb2.png)

When i visualise i obtain this:
![4](https://user-images.githubusercontent.com/114053880/205258350-ed3ae303-d90e-4ad6-b6c4-8d8ae67a94a3.png)
Why have i 5 outputs? because QuinLed had only 4 outputs.

if i click upload output and i came back in wled settings led preference, my outputs have change
![5](https://user-images.githubusercontent.com/114053880/205259061-bc6ce4c1-f0df-4f8d-932f-684c06fc5b93.png)
output1 : ok GPIO3
Output2 : bad GPIO1 i want GPIO16
how can i do to set output2 to gpio16?

I know in Xlights i can attach a file with all report but i don't know how to do

Thank you for your help.

**Comment by bcarriveau** [comment]
Your on the latest version of wled?
 xL version?

The dig quad can use 5 outputs,  gpio15 being the 5th.

Currently xLights uses these pins for uploads.

<Port1>16</Port1>
<Port2>3</Port2>
<Port3>1</Port3>
 <Port4>4</Port4>
 <Port5>15</Port5>

**Comment by computergeek1507** [comment]
You are currently using output 1 and 3, move the models to output 2 to use the correct GPIO. Output 5 is the relay port on the quad that can be used as a pixel port.

**Comment by chickenrun81** [comment]
Hi.
My version of wled
![6](https://user-images.githubusercontent.com/114053880/205506936-d4448a94-659f-4902-8588-9a2410c4831a.png)

**Comment by keithsw1111** [comment]
Is this still a problem?

**Comment by cybercop23** [comment]
@chickenrun81 plese close this issue.

**Comment by chickenrun81** [comment]
ok
