### ISSUE TITLE
QuinLED-ESP32-AE+ 3 extra output channels

### ISSUE THREAD

**Issue by jflickinger** [xLightsSequencer/xLights#3608]
Please add support for the three extra channels when using QuinLED-ESP32-AE+ on a DigUno or DigQuad 

Pinout for ESP32-AE+:
https://quinled.info/quinled-esp32-ae-pinout-guide/

**Comment by computergeek1507** [comment]
The dig uno only has two output terminals, does the AE+ have the three outputs on the esp32 board itself?

**Comment by jflickinger** [comment]
Yes. Verified they work with WLED via WLED webpage. I was able to get xlights to play nice by setting the digQuad as a digOcta and then later change the GPIOs via WLED webpage.

**Comment by keithsw1111** [comment]
Has this been fixed?

**Comment by cybercop23** [comment]
@jflickinger please close this issue.
