### ISSUE TITLE
QuinLED Dig-Octa

### ISSUE THREAD

**Issue by bmasella** [xLightsSequencer/xLights#3623]
**Is your feature request related to a problem? Please describe.**
I noticed that .24 added support under WLED for the DIG Octa.   We have it flashed with ESPixelstick to take advantage of configuring it to be an FPP Remote.   When adding to xLights I noticed it was under WLED...  Will it also be in ESPixelstick or perhaps standalone with the variants of WLED or ESPixelstick?  

I have it added to my controller in xLights... as WLED but I notice that the visualizer doesn't display any props... is this coming?

**Describe the solution you'd like**
ESPixelStick - versions of the Quin LED controllers.
Visualizer to display the props to add them appropriately to the controllers.

**Comment by computergeek1507** [comment]
The ESPixelstick Upload code will need to updated for more outputs. There is currently a bug in it when the JSON buffer is to large it will lock up xLights. I want to fix it but I only have a single port ESPixelStick. If someone loans me the controller hardware, I can attempt to add it.

**Comment by bmasella** [comment]
I can send you my Quin Octa

**Comment by bmasella** [comment]
email me at info@depoebaylights.com with your address and I will get them sent out asap.   It is flashed with the ESPixelstick Code that supports FPP and the multiple outputs of the board.  I could also send a Dig Quad if you wanted one of those as well.

**Comment by daklights** [comment]
Might I suggest also updating xLights' config settings for the QuinLED Dig Octa brainboard to have 9 output ports (vice the current 8 ports)?  Port 9 can be set to "relay" in the espixelstick v4 firmware, and therefore can control the GPIO-driven relay on the Dig Octa brainboard... but as of now, xLights considers Port 9 as non-existent.

**Comment by bmasella** [comment]
I gave one of the new boards ready to send out Scott

Bill Masella
VP Operations - Pacific View Lodging
***@***.***
(509)599-3902 mobile
________________________________

**Comment by cybercop23** [comment]
@MartinMueller2003 is looking to a a PR wit the updated HW supported by ESPixelStick 5x.

Can this be closed?

**Comment by bmasella** [comment]
Yes close

-=Bill Masella=-
***@***.***

________________________________
