### ISSUE TITLE
Timeline Zoom out past set duration.

### ISSUE THREAD

**Issue by cathelest** [xLightsSequencer/xLights#3624]
Not sure if a feature request or bug, or neither,
Please delete if this is a rare use case and i`m being silly,

But at present I am importing some effects for a tune to sign from a separate xsq file,

If my importing sequence is longer then the sequence i am importing into, then the effects run past the end of the sequence,
I can only zoom out to the end of the defined sequence.

I know you can go into sequence settings, set it longer, delete unwanted effects past the end point and then change duration back,

But would have thought that zooming out should zoom out to a point to show any effects on the timeline, or allow us to zoom out more
then it does now?

**Comment by ebuechner** [comment]
Try this. Zoom out as far as you can. Then slide your xlights window to the left grab the edge of the x lights window and expand it to the right to expose the effects that are beyond the end of the timeline.

**Comment by cybercop23** [comment]
@cathelest can this be closed? Not sure this is an issue still.
