### ISSUE TITLE
Batch Render, Missing Reference File, Add Skip Sequence Option

### ISSUE THREAD

**Issue by TripleJ3EB** [xLightsSequencer/xLights#3639]
It would be nice if during batch rendering, if there is an error on sequence open about a missing reference that an option be given to skip that sequence instead of just OK and rendering something that will not look right anyway.
Thanks

**Comment by derwin12** [comment]
There is a preference to skip errors on the batch render .. or are you asking for something different?

**Comment by TripleJ3EB** [comment]
Ah didnt know about that...but looks like it will just ignore the errors.  Does it still render that sequence?  and does it report at end of all the issues it ignored?

**Comment by derwin12** [comment]
It still renders .. creates the fseq file .. no it does NOT tell you it had errors.

**Comment by TripleJ3EB** [comment]
Okay, the ignore part is better, wish it would report at end there was a problem then.

**Comment by cybercop23** [comment]
@TripleJ3EB there was a recent change that now shows in the status bar that there were errors. Please test with most recent version, 2024,2 and if no longer an issue or working in a way you expect, please close this issue.
