### ISSUE TITLE
Some shader effects not displaying unless manually selected each time

### ISSUE THREAD

**Issue by whirlywhopter** [xLightsSequencer/xLights#3643]
**Describe the bug**
Shader effects will sometimes not render, leaving the affected prop or sub-model showing as solid yellow.  This does not seem to affect all shaders used in the sequence and even other layered effects on the same prop or model will render as expected.  If the affected shader is selected in the sequence window, it will often trigger xLights to render that effect but typically not others having the same issue in that part of the timeline.  Inspecting the effect, it appears to have all the parameters set (shader file and settings, layer blending, layer and buffer settings, etc.)  The effect will typically then behave normally for a period of time but this is not consistent and will often stop working again after a "Render All" even within the same xLights session or after restarting/reloading the sequence.

This behavior does not seem to affect all instances of the same shader.  Often other instances of the same shader using the same file/path may will render correctly and re-downloading the shader file does not seem to make any improvement.

I am seeing the behavior in multiple sequences including ones which rendered normally in previous versions before I began to notice this issue.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. When a sequence exhibits this behavior, select the impacted shader effect by clicking on it in the sequence window
2. The effect will typically automatically re-render and display normally on that prop after it has been selected
3. If another impacted effect on a different prop is selected, it will typically re-render and display but it does not seem to impact or improve any of the other props showing the same problem in the sequence or even at that point in the timeline.
4. If a "Render All is performed, the effects may revert to their previous behavior and not render correctly until manually selected again.

**Expected behavior**
All effects and components within the sequence will render when selecting "Render All" and display in the preview window and when the sequence is sent to the display.

**Screenshots**
I have attached two screenshots. The first shows xLights immediately after a "Render All" where a section of the sequence is not able to render several of the shader effects and the result is visible in the House Preview window.  If I render a video or save the file and play on my display it appears as it does in the preview.  The second is the result after manually clicking on all the affected shaders in this portion of the sequence and no other changes made in the sequence.  This process seems to allow xLights to resolve the rendering issue temporarily.  
![Screenshot before  manually selecting impacted effects](https://user-images.githubusercontent.com/104389627/208308873-adbc0b37-20a9-4a5a-bf09-6172d981d0ad.png)
![Screenshot after manually selecting all impacted effects](https://user-images.githubusercontent.com/104389627/208308881-0257a3dd-a9a2-4639-88c1-d1a0eaae8b59.png)

I have also captured a video of this same behavior but it is large.  If that would be helpful as well, please let me know where I can forward this or any other information that might be helpful in troubleshooting.

**Versions (please complete the following information):**
 - macOS Ventura 13.1, M1 Max MacBook Pro
 - xLights version 20222.25.1, wxWidgets 3.3.0
 Note:  I have been seeing this behavior to various extents with the last several versions of xLights and over the more than one macOS update.

**Additional context**
The problem also impacts the saved fseq when played on my actual display.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file

- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by atticusm** [comment]
I have experienced this same issue on PC. I turned off render cache and upgraded to the newest version. I will keep an eye out and if I can replicate it will post here.

**Comment by whirlywhopter** [comment]
Thanks!  Just for additional background information, on the Mac, I have tried enabling and disabling the render cache along with totally deleting the cache contents with each change and that does not seem to have had any effect so far.

**Comment by AzGilrock** [comment]
If its not right after a Render All and clicking on the effect fixes it then its a render order issue and you have another effect overwriting the shader.

**Comment by AzGilrock** [comment]
Create a sequence with just one shader effect and try to reproduce the problem.

**Comment by whirlywhopter** [comment]
In my case, I see this at all kinds of different times including just after opening a sequence or immediately after a render-all.  I often use layered effects with shaders  and different layer blending styles to create composite effects (mask, brightness, additive/subtractive, etc.) and have not seen this kind of behavior until recently.  It also does not seem to consistently happen with every effect within a sequence.

**Comment by AzGilrock** [comment]
When you click on an effect it trigger that effect to render by itself.  When you do a render all it renders all the models in the proper render order which may not look the same as when you clicked on an effect.  I've wasted a lot of hours troubleshooting reports like this just to discover its a render order issue.  So I'm suggesting you spend some time looking at what other effects are in the same time period and what is your render order based on the Master View.  Also remember its not the order a model is in a group its the order that model by itself is listed in the Master  View that determines when it's rendered.

**Comment by atticusm** [comment]
Merry Christmas. I have a packaged sequence I can replicate the issue with. Let me know who to send it to please.

**Comment by keithsw1111** [comment]
Is this still a problem?

**Comment by whirlywhopter** [comment]
Sorry for the delay, I just saw this question.  Let me go back and re-test some of the affected sequences in the current xLights version and confirm.

**Comment by cybercop23** [comment]
@whirlywhopter can you please create a simple sequnce and share it here using Package Logs so we can see. It is maybe more involved because of the order of your master view or other things?

If not of interest, please close.
