### ISSUE TITLE
Image used to create Xlights model viewable when creating sub modles

### ISSUE THREAD

**Issue by CustomChristmasCreations** [xLightsSequencer/xLights#3647]
**Is your feature request related to a problem? Please describe.**
This is not related to an issue, just an enhancement request.

**Describe the solution you'd like**
I would like to be able to see the picture I used to create the Xlights model when making the sub models or faces. Some of the dense props, or more detailed props can be challenging to sub model when the image is gone. 

**Describe alternatives you've considered**
I have tried comparing models to design model, but it can be challenging due to size of widow that shows the model. Zooming out makes it too hard to identify what things are.

**Additional context**
![Female elf top](https://user-images.githubusercontent.com/121060118/208514735-028e2e66-1aa3-4638-8fda-38f788fedc05.png)

**Comment by derwin12** [comment]
This is or was added .. It is hiding on the "Draw Model" button of the submodel dialog.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/bfbc0154-b8e4-4b03-8b7a-bd1378fcffd6)
