### ISSUE TITLE
Can no longer rearrange House Preview

### ISSUE THREAD

**Issue by darkcirk** [xLightsSequencer/xLights#3650]
When starting from a new show folder and rearranging the sequencer layout, once I move the house preview, it will not re-dock anywhere.

 - OS: Mac OS 12.6.1
 - xLights version 2022.25.1

**Comment by AzGilrock** [comment]
I think I ran into this the other day also.  If you remove everything from the left side it wouldn't let me drop a panel back in there.  I would expect that behavior to be controlled by wxWidgets so maybe that 3rd party library changed.

**Comment by AzGilrock** [comment]
Of course I just tried this and its working fine when I tried to reproduce it. Guess I'll just keep an eye out.  Hard to fix unless we can cause it to happen.

**Comment by darkcirk** [comment]
I can make it happen every time I start from a new show directory.  I'm having a different display issue where pixels show a different size from model preview to house preview that seems to be narrowed down to the show directory I'm using.  I thought if I moved all my models to a new show directory, the problem would be fixed and it was, but now I can't move the house preview.  Not sure what bug I have in my show directory.

**Comment by cybercop23** [comment]
@darkcirk  is this still an issue? If so, please upload a Package Logs zip file. If no longer an issuse, please close.
