### ISSUE TITLE
Error occurred While connecting To LOR Network on Comm3(available Ports COM3)

### ISSUE THREAD

**Issue by Mikemcphail** [xLightsSequencer/xLights#3653]
unable to open serial port COM3 Error code=1

**Comment by AzGilrock** [comment]
Doesn’t sound like an xLights problem.  If the device is on that com port it would work.

**Comment by bcarriveau** [comment]
I'm wondering if an lor utility is still running holding onto that port.

**Comment by Mikemcphail** [comment]
I killed the apps and restarted computer still got that error I am 3rdGOD 1stFamily 2ndI am 3rdOn Dec 24, 2022, at 6:33 PM, Bill Carriveau ***@***.***> wrote:﻿
I'm wondering if an lor utility is still running holding onto that port.

**Comment by Mikemcphail** [comment]
I am sure it is me doing something wrong. I can’t find specific instructions for what I am doing I am 3rdGOD 1stFamily 2ndI am 3rdOn Dec 24, 2022, at 8:08 PM, Mike Mcphail ***@***.***> wrote:﻿I killed the apps and restarted computer still got that error I am 3rdGOD 1stFamily 2ndI am 3rdOn Dec 24, 2022, at 6:33 PM, Bill Carriveau ***@***.***> wrote:﻿
I'm wondering if an lor utility is still running holding onto that port.

**Comment by AzGilrock** [comment]
You didn’t describe what hardware you have

**Comment by Mikemcphail** [comment]
How can I tell if another utility is Running and it will not let it work

**Comment by Mikemcphail** [comment]
The problem is a little different now 
Created Layout all ok
Loaded Sequence and played it it seems all ok it is faces and I can see preview and can see them working when sequence is playing
I was having trouble connecting controllers now i think they are connected but when i play  the sequence the faces are not moving and i cannot preview them and the controllers are not out putting. But if I disconnect the USB cord and delete the controllers and restart Xlights the sequence plays and all the faces are moving and i can preview i am not sure can some one help

**Comment by keithsw1111** [comment]
Is there still an issue here?

**Comment by cybercop23** [comment]
@Mikemcphail please close this issue.
