### ISSUE TITLE
Copy Effects

### ISSUE THREAD

**Issue by Strawberry1997** [xLightsSequencer/xLights#3661]
**Is your feature request related to a problem? Please describe.**
copying a line of effects is cumbersome because you have to make timing marks for the whole sequence.

**Describe the solution you'd like*
![Screenshot 2022-12-31 at 8 42 04 PM](https://user-images.githubusercontent.com/78796480/210159045-f07377e0-f951-4644-bfe5-30fe5b3784db.png)

I would like to click on the prop in the timeline and it will automatically select all the effects on that layer.
also be able to select more than one layer at a time by using the ctrl key and or dragging a box around the layers to be selected.
once they are selected ctrl-c can be used, then to paste you would select on another prop/layer and ctlr-v to paste correctly in the timeline. 
This feature is in Vixen.

**Comment by AzGilrock** [comment]
No you don’t need timing marks to do a copy.  In fact it’s easiest to turn off all timing tracks and then drag a yellow dashed box around what you want to copy.   You can also right-click a layer and select all the effects on that row or you can select all effects on the entire model.  Now learn xLights so you can go tell the Vixen guys the 5,000 things we can do that it can’t

**Comment by Strawberry1997** [comment]
I drew a yellow box around a group of effects and copied, then selected a new row to copy them to but it didn't keep them in the same timeframe.

**Comment by Strawberry1997** [comment]
![Screenshot 2023-01-01 at 2 37 21 PM](https://user-images.githubusercontent.com/78796480/210182771-ffd4f017-79c6-47d5-9f84-e557c82f35a3.png)

**Comment by Strawberry1997** [comment]
For the whole Layer or Line
![Screenshot 2023-01-01 at 2 37 32 PM](https://user-images.githubusercontent.com/78796480/210182793-051e2861-da7d-4891-bf0e-83b476ed58e9.png)

**Comment by AzGilrock** [comment]
Yes when you select effects they are not locked into the time where they came from.  It’s meant to be able to paste anywhere.  The first effect on the top row of your selection sets the reference.  Then when you right click to paste that click defines where the reference will start for the paste.  It’s assumed if you want the whole row you will do a row copy.  But there are other tricks I use if you have trouble getting the alignment you want.  Put a dummy effect at the start of the top row.  Then you can paste it without being precise, then select everything you pasted and hold down shift to drag it all left till it hits time zero then it will be aligned how it was where you copied it.

**Comment by Strawberry1997** [comment]
I agree paste anywhere, but I would like a feature to select a prop and it lock it to the timeline.

**Comment by devinhedge** [comment]
It seems that the requested featur is partially implemented but might have a bug in it.

I noticed last night, while working on next year's sequences, that when I select effects on multiple layers or select all of the effects on a model that have multiple layers, when I attempt to paste them in a different instance of xLights, it only pastes one effect, or doesn't paste as all.

This is actually two different behaviors it seems.

## Behavior one:
1. Turn off timing marks.
2. Select effects on multiple layers in a section for a model by dragging around them.
3. Switch to a different instance of xLights with a different sequence open.
4. Ensure the model I wish to paste the effects on has the same or more layers
5. Turn off timing marks
6. Select the first cell cell on the top layer where I want to paste
7. CNTL+v to paste

Result: Only the last effect of the group of effects that was pasted will do so.

## Behavior 2.

1. Turn off timing marks.
2. Select a model whose effect I want to copy
3. Right-click on the model, Select Model..., Copy Effects from the context menu
4. Switch to a different instance of xLights with a different sequence open.
5. Ensure the model I wish to paste the effects on has the same or more layers
6. Turn off timing marks
7. Select Model... Paste Effects... 

Result: Model... Paste Effects is greyed out.

## System Configuration

- Windows 10 (latest patch)
- xLights 2022.26
- CPU: AMD Ryzen 5 3rd Gen
- RAM: 32GB
- GPU: Nvidia GeForce RTX 2080

**Comment by AzGilrock** [comment]
The Paste option is greyed out until you do a copy in each instance.  So do a dummy copy first in the destination instance before you copy in the first instance.  We didn’t really design for multiple instances it just happens to work.

**Comment by cybercop23** [comment]
Can this be closed as WAD?
