### ISSUE TITLE
Bulk Edit Window Size Issue on Mac

### ISSUE THREAD

**Issue by kbostick88** [xLightsSequencer/xLights#3676]
When you go to bulk edit an effect setting on Mac the Bulk Edit pop up window does not size correctly, it cuts off the right side of the text field. 

I was able to reproduce this across 3 different Macs running different versions of xlights from 2022.19 > 2023.01
macOS versions 12.6 > 13.1

I have included a short video showing the issue

https://user-images.githubusercontent.com/17733692/211864642-bf515727-5f6d-48bd-ad40-d9097f77065d.mov

**Comment by cybercop23** [comment]
@kbostick88 is this still an issue? If not, can you please close?

FWIS... 2024.2.1 (nightly) 
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/79a2fcb4-a914-42c3-a8ba-a872d3dbeea1)

**Comment by kbostick88** [comment]
ill test on the newest version, but it was still an issue in Dec.
