### ISSUE TITLE
House Preview darker than model preview

### ISSUE THREAD

**Issue by darkcirk** [xLightsSequencer/xLights#3677]
My layout has the normal brightness in the layout tab.  In the House Preview, my layout is dimmer.  If you select an effect and view the model view next to the house preview, the difference is very evident.

https://youtu.be/fdXZKP-Uf5w

**Versions (please complete the following information):**
 - OS: Mac OS 12.6.1
 - xLights version 2022.25.1

**Attachments**
I am attaching my xlights_rgbeffects.xml file
[xlights_rgbeffects.xml.zip](https://github.com/smeighan/xLights/files/10396302/xlights_rgbeffects.xml.zip)

**Comment by cybercop23** [comment]
@darkcirk is this still an issue for you? Please test and if not, please close this issue.

I'm runnign on a Mac, with latest version 2024.2.1 (nightly) and I don't see this issue.
