### ISSUE TITLE
View Layout (House Preview) / Sequences on a monitor simultaneously while running Sequences on XSchedule

### ISSUE THREAD

**Issue by forgekeeper** [xLightsSequencer/xLights#3682]
**Is your feature request related to a problem? Please describe.**

Fairly new to this and just wondering is there a way to Display Your Layout (Like when testing sequences in XLights) while running your sequences via XSchedule. I would like to be able to watch my scheduled sequences on a computer monitor if possible.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AzGilrock** [comment]
Probably not practical to create that anymore.  LOR used to have a feature to do this and I thought it was cool and had this idea years ago.  Problem these days is you can really create a listener when many controller are just getting a sync packet.  And you really don’t want to bog down the show player computer trying to display all the show data.

**Comment by forgekeeper** [comment]
Thank you for your reply.  I suppose that once a sequence is debugged/finalized and actually ready to be scheduled one really wouldn't need to view it on a screen.  I am new to this and had some sequences I wanted to use for a test of the scheduler and just wanted to view them as they played.  To Bad that feature is not available because I think it would be cool too.  Maybe one day something like having a duplicate schedule in X-Lights proper can be triggered by the scheduler and the House Preview viewed.  Thanks again.

**Comment by dkulp** [comment]
There's kind of a way to do it with FPP (VirtualDisplay), but there are a BUNCH of restrictions with it.   Since it's not something that you want running on any main show player, we would recommend having a dedicated FPP Pi  running in remote mode specifically just for the display.   Currently it's "2D" display only.   It will also likely have issue with high channel counts, doesn't do things like moving heads, etc...

**Comment by forgekeeper** [comment]
Thank You for your reply.  Now that you mention it I do somewhat recall reading something about using the FPP to display, I just can't remember where.  I will keep in mind the Virtual Display aspect.

**Comment by DoctorWiz** [comment]
I recognize this is likely difficult to implement, but for what it's worth... I'd really like to see this enhancement as well.

**Comment by cybercop23** [comment]
Hoping this will be fixed. https://github.com/FalconChristmas/fpp/issues/1330

For now, since it doens't look like they may be implemented, @forgekeeper  can you please close this issue?

**Comment by forgekeeper** [comment]
Closing as requested.  Sure would like to see this one day though.
