### ISSUE TITLE
Support all current ESPixelStick V4 Platform variants

### ISSUE THREAD

**Issue by MartinMueller2003** [xLightsSequencer/xLights#3739]
I am getting defects reported in the ESPV4 project that indicate xLights is not configuring the ESP properly. As the platform list expands, people are generating custom mixes of supported features. All of these variants report as the same version (the base V4 version). 

The current reccomended mechanism to determine the number of output ports and the capabilities of those ports is to read the config from the device and parse it. The config contains a complete list of capabilities and settings. The same is true for the input capabilities. FYI, this is how the browser UI works. 

You can contact me at MartinMueller2003 on discord or on the red site.

**Comment by keithsw1111** [comment]
While you can include such settings in discovery they have to be in an xcontroller file for us to apply the rules. We cant be pulling this from the controller all the time as it wont always be online.

Our position on this is as follows. We will add xcontroller files to the distribution where there is sufficient volume in the market. We are not adding files for small scale boards. Instead we allow users to add their own xcontroller files to their install folder. Small scale vendors can directly distribute such files until they hit sufficient scale to make it sensible to add to xlights.

**Comment by MartinMueller2003** [comment]
Thanks for the information. Do you have a pointer to the xcontroller format definitions?

**Comment by derwin12** [comment]
Perhaps check the existing ones.
https://github.com/smeighan/xLights/tree/master/controllers

**Comment by computergeek1507** [comment]
Is there a specific controller that is missing? Looking at the ESPixelstick issue tracker I didn't see anything related to this.

**Comment by MartinMueller2003** [comment]
Just getting started on this, We are up to 23 platform variants. I looked in the esp controller file and it looks nicely expandable. It does not support everything V4 supports. I see generic serial is missing and most of the pixel types are not there either. Pixel type identifiers shift baased choicces made by yhe platform owner.

**Comment by keithsw1111** [comment]
Martin ... can you maybe put in a pull request with an updated xController file.

**Comment by MartinMueller2003** [comment]
Can Do.

**Comment by cybercop23** [comment]
@MartinMueller2003 are there more that should be added to the list? If so, maybe you can do a PR and we can close this issue for now.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/8e3a77a2-b1cc-4f44-b3dc-46637745e274)

**Comment by MartinMueller2003** [comment]
OK. I will update the list. This list has grown a lot since last April.

**Comment by cybercop23** [comment]
Thanks @MartinMueller2003. Best way to handle it, is to do a PR since you know all there's to know about the new models.
Please close this and replace it with a PR when ready.
