### ISSUE TITLE
Option to Set Effect Default

### ISSUE THREAD

**Issue by MCStoff** [xLightsSequencer/xLights#3760]
Feature rich effects offer a staggering number of options.  Allowing the user to create a "default" that is used each time the effect is utilized would help users quickly get to where they want to be.  There are certain effects that have default settings that I never use; one example is with the Fan Effect.  The default duration is set to 80% of the effect time on the timeline.  Another example is the pinwheel.  Most props have a minimum of five legs or spokes.  The default value is 3.

Addition of a simple check box or button in the effect dialog that allows the current settings to be saved as the default on the effect would be a time saver during sequencing and would be a simple way to allow users to customize the interface in a manner that best suits his or her needs.

**Comment by bacarudaguy** [comment]
Effect Presets already exists... and shows a preview of the effect...

**Comment by MCStoff** [comment]
You have misunderstood what I am requesting. I would like for the default settings for an effect when it is selected to be determined by the user. Sent from my iPhoneOn May 16, 2023, at 11:47 AM, bacarudaguy ***@***.***> wrote:﻿
Effect Presets already exists... and shows a preview of the effect...

**Comment by AzGilrock** [comment]
I'm not even sure how this would be implemented since the way we currently store effects in the sequence XML is we only list parameters that are not the default values in order to save space.  So most of the effect settings usually don't exist in the XML file.

By the way what are you setting the Fan duration to?  That duration is the main thing that makes it different than Pinwheel.  It doesn't shorten the effect duration that controls the time it takes for it to expand and contract which makes it more interesting than Pinwheel.  So at 80% I believe that takes 10% of the time to expand and is full 80% and then 10% to contract.

**Comment by MCStoff** [comment]
While the fan is just an example, there are many others individual to me that I would prefer,I am sure others would be as well.  I have a preferred initial setting for about half of the effects. I know it can be done, but as you mentioned, the way it is set up right now, the change may require too much coding to put in place relative to the benefit gained. If I were coding, rather than trying to strip the variables from the defaults where they are now, I would include the preferred default variables where the information for the Default Perspective is stored so that when it is loaded, the user’s effects default preferences are brought in over-riding the system defaults. Thanks for giving it a critical eye. I appreciate your efforts. Sent from my iPhoneOn May 16, 2023, at 2:33 PM, Gil Jones ***@***.***> wrote:﻿
I'm not even sure how this would be implemented since the way we currently store effects in the sequence XML is we only list parameters that are not the default values in order to save space.  So most of the effect settings usually don't exist in the XML file.
By the way what are you setting the Fan duration to?  That duration is the main thing that makes it different than Pinwheel.  It doesn't shorten the effect duration that controls the time it takes for it to expand and contract which makes it more interesting than Pinwheel.  So at 80% I believe that takes 10% of the time to expand and is full 80% and then 10% to contract.

**Comment by cybercop23** [comment]
Have you considered key bindings? You can set the "defaults" for the effect from a copy/paste and you can also, as sugested, set up presets and then add them to key bindings.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/70557e2a-104b-41b7-8fc1-db6b3d00f52f)

**Comment by MCStoff** [comment]
That’s a good thought. I definitely could make it work on the few that irritate me. 😆 Sent from my iPhoneOn Jan 29, 2024, at 9:46 AM, AlexB ***@***.***> wrote:﻿
Have you considered key bindings? You can set the "defaults" for the effect from a copy/paste and you can also, as sugested, set up presets and then add them to key bindings.
image.png (view on web)

**Comment by MCStoff** [comment]
I will. Thanks for the idea. Sent from my iPhoneOn Jan 29, 2024, at 10:00 AM, AlexB ***@***.***> wrote:﻿
Cool. Please close this issue and if you run into any problems, re-open it or create a new enhancement reqest referencing this one.
