### ISSUE TITLE
Enhancements for the Ripple Effect

### ISSUE THREAD

**Issue by merryoncherry** [xLightsSequencer/xLights#3779]
The ripple effect has great potential, but has a few limitations.  The ripple spacing isn't configurable, and behavior differs depending on which built-in shape it is.  It only has two available motions, implode and explode.  Rotation only works on some shapes.  There aren't that many shapes.  Etc.

I have a prototype that adds some new features to it; you can change the size, motion, twist, direction, etc., and the colors are more flexible.  Here is a draft updated documentation page (subject to change with feedback):
https://drive.google.com/file/d/1Rfn6FzpwgwS-ocoh_BleKX51YVude6Vr/view?usp=share_link

Here is a model preview video from the updated effects:
https://drive.google.com/file/d/1RA4YI_58XZQlwxmHtA9mjYdCh-LrK814/view?usp=share_link
I tried to make it as independent from the matrix resolution as I could, so it can be a pretty good stand-in for shockwave, which is notoriously finicky.  10x resolution on the exact same effects as above:
https://drive.google.com/file/d/168En-l_YMrz5ZrmFk6jFdPNbb73Pgrdq/view?usp=share_link

SVG is one of the fun new features:
Medium-low res matrix:
https://drive.google.com/file/d/1eMlQIiTIsPI5rl7uHA3oQ3kL97v96tNE/view?usp=share_link
Same sequence on high res matrix:
https://drive.google.com/file/d/1ebdCCY-5vG02MQ53Ak8Kybi-4rBDBnzA/view?usp=share_link

As usual, if you don't want to discuss here for whatever reason, email any address at the merryoncherry.org domain.

I will post the draft PR with known issues/sticky points shortly.

**Comment by derwin12** [comment]
Can this be closed then?
