### ISSUE TITLE
Add track head like linear video editors. 

### ISSUE THREAD

**Issue by tjenvy** [xLightsSequencer/xLights#3788]
When editing with a lot of models and groups, trying to see things line up isn't always easy.  Yes you can select them and choose to align tracks etc.  But what would be incredibly helpful would be to have the line go from the waveform across the entire editor.  

All video linear editors do this already.   We already have the line on the waveform and right at the mouse on the line of the effect you are working with. 

![Untitled](https://user-images.githubusercontent.com/11091359/233127298-cb623442-1932-41f1-b201-0a555351b210.jpg)

**Comment by computergeek1507** [comment]
This is the intent of timing tracks and timing marks

**Comment by tjenvy** [comment]
I get that. But adding a timing track and dropping a timing mark just to look at things  and then delete that to stop it from getting so messy.  It’s just extra steps.  If I am dragging an effect across the timeline to drop it would just be easier to see the line across the whole project as I'm dragging.

**Comment by computergeek1507** [comment]
Probably won't add this as the functionality already exists with timing tracks.

**Comment by tjenvy** [comment]
So what you’re saying is that I need to add a timing track. Then drop a timing mark and drag it to where it lines up with one of the effects that I’m looking at I suppose. Then go through and move some things around and just see how it looks. Then go back and delete the timing mark. That’s a lot of extra steps when you’re already doing a lot of clicking and dragging anyways. There’s already a ton of work involved to complete a show, so just trying to make things easier for people would seem like a nice benefit.Sent from my iPhoneOn Apr 19, 2023, at 11:52 AM, Scott Hanson ***@***.***> wrote:﻿
Probably won't add this as the functionality already exists with timing tracks.

**Comment by tjenvy** [comment]
And just to be clear this is not a static line it's a line that moves with the mouse across the timeline. Its already offered in the waveform.

**Comment by AzGilrock** [comment]
Most people create timing marks first and then drop their effects so none of that complicated process is necessary.  You're also not going to get the snap to timing mark action if you don't use the timing tracks so your attempts to align visually using freeform editing like your doing are still prone to misalignments unless you zoom way in.

**Comment by Clyde-L** [comment]
> 

I would suggest the use of a "junk" timing track where you create these marks.  If you open up your Display Elements, you can quickly show/hide a timing track by clicking the "eye" icon on the view you're using to sequence from.  I do this a lot, especially when there are 4 lyric tracks expanded and taking up the space. Sometimes my sequences can have 8 timing tracks and this is a simple easy way to manage what I think you are trying to accomplish :)

![image](https://github.com/smeighan/xLights/assets/12719816/da821463-5bc8-44ae-94bf-dbdb804fe0e0)

**Comment by cybercop23** [comment]
@tjenvy if this solution works, please close this issue. TBH this is how most of the users use this feature.
