### ISSUE TITLE
Curtain effect doesn't work correctly with Per Model Per Preview render style and resized render buffer

### ISSUE THREAD

**Issue by craiz** [xLightsSequencer/xLights#3799]
**Describe the bug**
The Per Model Per X render styles such as Per Model Per Default and Per Model Per Preview do not work correctly with the Curtain effect when using a render buffer that is resized to something smaller than 100%.  The effect renders but it is not per model as expected.

**To Reproduce**
1. Add curtain effect to a group
2. Select Per Model Per Preview as render style
3. Resize render buffer to "Left Half"

At this point it looks like the effect is rendering as if it was set to render style = Default and render buffer = "Right Half".  It is certainly not correctly rendering per model.  If you resize the render buffer back to full size the curtain renders correctly.

**Expected behavior**
I expect the curtain effect to be rendered on the left half of each model in the group.

**Versions (please complete the following information):**
 - OS: Windows 11 Build 25853
 - xLights version 2023.06

**Comment by Clyde-L** [comment]
Try the Overlay Scaled render style.

**Comment by craiz** [comment]
> Try the Overlay Scaled render style.

Thanks for the suggestion @Clyde-L.  Using Overlay Scaled does get the curtain effect to render onto each model in the group instead of the whole group.  However, the result looks like rendering the model and a single line.  What I really need is Per Model Per Preview.

**Comment by derwin12** [comment]
This is expected behavior.  A check sequence will throw the error "ERR: Effect on a model group using a 'Per Model' render buffer is also using a subbuffer. This will not work as you might expect."
I don't see this changing - Clyde as provided the desired approach.
