### ISSUE TITLE
Picture effect scaling

### ISSUE THREAD

**Issue by ebuechner** [xLightsSequencer/xLights#3800]
I know this is been an issue for a while but I couldn't find a bug report on it. While using the picture effect, an image will disappear with certain scaling.
I have a few sequences where I use the start scale and the end scale with different values and as the image is passing through certain scaling the image disappears making the image very glitchy. I think I remember Keith making a mention about this some time ago so I thought this would have been resolved by now.
64 bit windows 10 running with dark mode on the latest x lights 07.

**Comment by ebuechner** [comment]
After playing with this issue for a while I figured something out. If I take the images that were giving me issues and run them through piskel and then save with the same name and format and then do a render all in XLights the issue goes away. Not sure what changed but earlier versions of XLights didn't have a problem with these images.

**Comment by cybercop23** [comment]
I think this might have been the change on OpenGL version. If everything is working as expected, can you please close this issue?
