### ISSUE TITLE
DMX Effect 

### ISSUE THREAD

**Issue by bensovereign** [xLightsSequencer/xLights#3804]
**Is your feature request related to a problem? Please describe.**
when i have to keep changing from page one and two on the dmx effect
**Describe the solution you'd like**
Is there is a way to change the number of channels on each page of the dmx effect. so that we can have all 16 channels on one page so that you don’t have to change form page one to two to get at the other channels for movers.
**Describe alternatives you've considered**

**Additional context**

**Comment by AzGilrock** [comment]
Someone could rework the dialog.  I just can't spend time on that because if I have time to work on moving heads I've got other new ideas that will completely change the best way to control them.

**Comment by bensovereign** [comment]
Great can’t wait to see what you have in mind

**Comment by bensovereign** [comment]
That's great can't wait to see what you come up with!!!!

**Comment by cybercop23** [comment]
#2453

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/efe95990-d548-4c51-bdc3-6eb35e2a012d)
