### ISSUE TITLE
Circle Effect add x and y axis setting

### ISSUE THREAD

**Issue by Darzoom** [xLightsSequencer/xLights#3807]
**Is your feature request related to a problem? Please describe.**
To move a circle effect requires to oversize the buffer and go to Roto Zoom to set.  

**Describe the solution you'd like**
Add the ability to move x and y axis as in other effects like in Pinwell with the x and y axis sliders or values or as a position like the Fan effect.

**Describe alternatives you've considered**
Alternative is using Roto Zoom.

**Additional context**

**Comment by AzGilrock** [comment]
The Circles effect randomizes the X / Y positions of the circles so I'm not sure what benefit this setting would have.

**Comment by Darzoom** [comment]
I would agree that Circles are random except in Radial and Radial 3D.

**Comment by merryoncherry** [comment]
There are a lot of effects that will essentially draw a single circle and let you do interesting things with the size, location, colors, etc.  In alphabetical order, here are the ones I thought of, and it is possible I missed some:

Fan without blend edges
Picture (A picture of a circle .. or video too I suppose)
Pinwheel with thickness all the way up
Ripple with type circle
Shader (probably some shader does this)
Shape with 1 circle not randomized
Shockwave

The circles effect implementation of "Radial" is (circles effect fans please forgive me) not very interesting compared to those.  What the circles effect is really good at is circles that bounce around.  So my personal opinion is leave circles effect to be good at that, and use any of the other effects for a single circle use case.

**Comment by Darzoom** [comment]
You are correct that many effects let you draw a single circle.  But none provide the radials with multiple colors as does Circles on a single layer.  The new Ripple offers something similar, but only 2 colors.  Yes, I can stack multiple Ripples in layers with the colors needed to emulate what Circle/Radials already does in a single layer.  I can also continue implementing the movement of X/Y as I currently am should this not be considered for a further enhancement.  Thanks for providing teh information.  I will look into other ways as well.

**Comment by merryoncherry** [comment]
New ripple can do radial colors on a single layer, if you make a suitable color curve.  It takes a bit more customization than the circle radial, but more flexible because you can control the spacing over time, make a variety of colors and color blends, change the size over time, in a different way than circle does, etc.  The key though is to use the color curve and set the little box below it to outward or inward gradient.

![Radial](https://github.com/smeighan/xLights/assets/102841136/078fe7e6-eb91-448b-8213-cb09719a72d1)

**Comment by Darzoom** [comment]
Thanks for taking the time to explain to use the new Ripple effect using gradients. I have tried that but it is not as easy to implement as the Circle effect and get like results. It's great that XL has so many ways to implement effects.  It’s no big deal if X/Y cannot be manitulated with Radial in Circles.  I’ll just keep using oversized buffer and move with Roto Zoom.  Thanks!

**Comment by cybercop23** [comment]
@Darzoom looks like you hava a workaround/solution. If so, can you please close this issue?

**Comment by cybercop23** [comment]
Discussed this on zoom. Only adde to Radial and Radial 3d as options. Dr Daryl will take a look.

**Comment by cybercop23** [comment]
Implemented and merged to master. Please test the nightly (preferred) or in the next version.
