### ISSUE TITLE
Dimensions no longer working for 'Image' type props, Dimensions not showing, Rulers not working

### ISSUE THREAD

**Issue by DoctorWiz** [xLightsSequencer/xLights#3817]
Dimensions are no longer working for "image" type props, displaying all zeros.  Not sure when it broke but it was several releases ago.  Definitely used to work because I relied on it the last time I modified my layout which was with in a 2022 release.
Furthermore, dimensions are shown when opening an old layout, but when I tried to recreate the problem in a new blank layout, dimensions were not even listed in the prop properties.  See attached pic.
Rulers no longer show a correct length, just always "1".
Dimensions for Candy Canes show their width as "Length" but the value appears to be correct, just mislabeled.  The height though is way off, at least 3-4X what they really are.  I believe this used to work correctly in an older version.
Single Line props show their length, but if they are at an angle they do not show how much space they take up in X, Y, Z.  Likewise, PolyLines show the total length and the individual segments lengths, but not how much space they occupy if at an angle, or curved.  Don't believe that ever worked.

<b><i>Steps to duplicate:</i></b>  <s>Create a new show folder, and a new layout.</s>  Open an old show folder and old layout.
Add a grid for reference (If there isn't one already).
Add an "image" type prop and choose a jpg, png, gif, etc., or select an existing "image" type prop.
Size it approximately using the grid.
Note that the height and width in the prop properties window are zero.
Add or select a candy cane.
Size it approximately using the grid.
Note that the listed "Length" seems to match the width, from the tip over to the vertical shaft.
Note that the "Height" (which is grayed out BTW) is 3-4 times its actual height according to the grid and/or ruler.
Also note that there is a height property near the top of the properties window, and another (apparently unrelated?) height near the bottom under "Size/Location".
Add (or select) a "Single Line" prop.
Move one end so it is at an angle.
Note that under 'Dimensions' it does not say how much space it occupies in X, Y, Z.
Add a "PolyLine" prop with several segments.
Move some of the points around to various angles.
Make one or more segments curved.
Note that under 'Dimensions' it does not say how much space it occupies in X, Y, Z.
Add or select a ruler.
Set it to an approximate known size using the grid.
Note that the "Real Length" always shows "1" no matter how long the ruler actually is or where you place its end points.

<b><i>Summary:</i></b> The only ones of these that are really important is dimensions for the "Image" prop, and the ruler.  They used to work in a previous release.  Candy Canes would be the next most important prop to have dimensions for.  Single Lines and PolyLines are not so crucial but seems like (could be wrong) it would be relatively easy to do by subtracting the smallest X value from the biggest for width, smallest Y from biggest for height, and same again with Z for depth.

Version 2023.8, 64-bit for Windows, wxWidgets 3.3.0  (Oh, and the About Box says Copyright 2013!)
[Dim.zip](https://github.com/smeighan/xLights/files/11492111/Dim.zip)
![DimensionsShowing-NotShowing](https://github.com/smeighan/xLights/assets/20911920/a09a364d-1b78-44dc-b688-0f2b03d15b39)

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.
