### ISSUE TITLE
Update for Sequence Preferences

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#3821]
Would someone consider adding a "Disable Color Update Warning" to the xLights Preferences?  It's common for us to update colors in our sequences to see the quick outcome, but to then always click the "yes update color" becomes quite monotonous.  I do see a need for this function, and it should be set to "on" for the default when a new user installs it.  However many users do not need the warning and I do not see a way has been added to disable it.

Thank you for looking.

Clyde

![image](https://github.com/smeighan/xLights/assets/12719816/d61f4a16-1549-416b-aa23-ae673e1004f7)

![image](https://github.com/smeighan/xLights/assets/12719816/ad6338c7-e62d-4ffc-9a71-62e1341e15c9)

**Comment by computergeek1507** [comment]
I'm not a huge fan of the new warning either.

**Comment by Clyde-L** [comment]
Scott, any way to add a checkbox to disregard this update authorization?

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.

**Comment by Clyde-L** [comment]
Thank you
