### ISSUE TITLE
'Import Effects' Screen - Add count of effects against each group/model/submodel

### ISSUE THREAD

**Issue by OnlineDynamic** [xLightsSequencer/xLights#3823]
**Is your feature request related to a problem? Please describe.**
When Mapping across a sequence with lots of groups/models/submodels onto a layout with not so many it would be helpful to be able to sort the list of available items  by the number of effects that are mapped to them in the original sequence.  Allowing to get the most interesting activity mapped across

**Describe the solution you'd like**
Add a column next to each 'Available' item on the right of the creen to show the number of effects associated in the original sequence.  Then allow sorting on the columns so user can sort alphabetically as current solution or sort by volume of assigned effects

**Describe alternatives you've considered**
Manually opening original sequence and writing down which models have the most going on on them

**Additional context**
I know number of effects isn't a perfect guide to getting a good end result but it would definitely help in the mapping process

**Comment by OnlineDynamic** [comment]
an additional column  could be a metric around % of timeline filled with effects on that particular group/model/subgroup

**Comment by OnlineDynamic** [comment]
or even more advanced would be a graphic timeline showing the effects on the incoming models and an aggregated view of what the resultant mapping profile would create - currently I find I map things and then when I go to preview the result there are large periods of dead space with all the lights off.  This could help resolve that.

**Comment by computergeek1507** [comment]
I added the effect count, I hope in the future to add a dialog with render of the effect start/end times, model properties etc.

**Comment by OnlineDynamic** [comment]
@computergeek1507 thanks for doing this ;) - just checked the nightly build and looks good - one little thing, clicking on the '# Effects' column heading sorts alphabetically by name rather than numerically based on number of effects

**Comment by computergeek1507** [comment]
I couldn't get it working, I was hoping no one would notice, I'll try to fix it.

**Comment by cybercop23** [comment]
@OnlineDynamic this seems to have been fixed plus there's a recent change that only shows effects at the model level (excluding submodels as to not double 3x count).

Please check and close this issue.

**Comment by OnlineDynamic** [comment]
Thanks - all working in 2024.2

Think there is loads more we could do in this space to make a visual indicator of how filled the seq will be posting mapping ;) but this was a great start
