### ISSUE TITLE
add number tags to metrinome

### ISSUE THREAD

**Issue by jackyelliott** [xLightsSequencer/xLights#3832]
This is an enhancement request. No issues with out it. 
Add adjustable numbers tags to the metrinome would allow user to create automations with states that had varied timing.

Very much like beats track, where you can adjust from default to include different counts. The tags would then be able to be pointed to by the STATE EFFECT for the automation just like BEATS track. The difference would be that the speed would be user defined as with the metrinome. 

Beats works well in some cases but generally too slow for other. This is overcome by creating a timing track of your on and repeating the count and in some cases, ITERATE the count. 

Everything is capable of this already with several steps but if the tags could be added to metrinome, this would open up an ease of use for people who aren't as savvy.

**Comment by derwin12** [comment]
Jacky .. is this in there now?

**Comment by jackyelliott** [comment]
Yes it is.  If the ticket is still open you can close it

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 10, 2024 at 3:25 PM, ***@***.***> wrote:   


Jacky .. is this in there now?
