### ISSUE TITLE
xScheduler, Windows, doesn't play background sequence when no sequence is running

### ISSUE THREAD

**Issue by DPattee** [xLightsSequencer/xLights#3838]
**Describe the bug**
I expect my background sequence to always run. But, it doesn't. Whether 'Run background playlist when not running sequence' is selected or not, the background sequence does not play if another sequence isn't currently running.

**To Reproduce**
1. make 2 sequences that activate unrelated props, make 2 playlists that only contain one of the seqs.
2. set sequence 1 on a sechdule
3. set sequence 2 as the background playlist
4. set the channel limits and overwrite mode so they both play at the same time
5. wait until the seq 1 schedule ends and turns off

**Expected behavior**
6. expect the background sequence to continue to play

**Actual behavior**
7. As soon as seq 1 ends, the background seq stops playing (and leaves the prop lights on
8. Trying with teh 'run background when not runnin sequence' option enabled, which sounds right, doesn't make any difference

**Versions (please complete the following information):**
 - OS: Windows 11
 - xScheduler 2023.09

**Additional context**

[xlights.zip](https://github.com/smeighan/xLights/files/11716288/xlights.zip)

**Comment by cybercop23** [comment]
@DPattee if this is no longer an issue, can you please close it?
