### ISSUE TITLE
Not able to Install the Xlights software application onto Laptop

### ISSUE THREAD

**Issue by pixelnewbie** [xLightsSequencer/xLights#3847]
I just purchased a Dell Inspiron 15 laptop with Windows 11 OS, 16GB RAM.  The first thing I wanted to download was Xlights.  I have never done a light show and was hoping to try it this year.  I went to Xlights site and clicked Downloads.  from there I clicked on Download64bit 2023.09 link (and the QM Vamp as well). Once in my download folder, I tried opening the file like the instructions said, and nothing came up.  The second time I tried to run the file I got a popup screen that said  "Search for an app in the Store?  You need to install an app for that task.  Would you like to search for one in the Store?  I also tried downloading from Github with the same results..  

If I hover over the Chrome icon on the taskbar, another box shows up and says "Window Dialog (not responding)"
Is this a Windows 11 compatability issue?  The wrong Xlights Release? or just a PIC error?

![image](https://github.com/smeighan/xLights/assets/136751699/1d0c0d6b-66d1-4fe9-bc8a-2f7246629946)
![SearchAppStoreScreenshot](https://github.com/smeighan/xLights/assets/136751699/f980d88a-f4a3-4343-8fcc-9dbc9fe1de06)
![WindowDialogScreenshot](https://github.com/smeighan/xLights/assets/136751699/b656458b-1708-4297-86af-7cb40deaf4b1)

So eager to get started, any help is greatly appreciated.
Thank you,
Pixelnewbie

**Comment by derwin12** [comment]
People are using windows 11 - so that shouldnt be the issue. Perhaps there is some windows defender/antivirus software blocking it?

**Comment by keithsw1111** [comment]
I suggest you go to the xlights zoom room and get some folks to look over your shoulder while you do it. You are not likely to get anything useful here other than the virus scanner suggestion above as its the most common reason why it would fail or some other security setting preventing it from running. Either way the zoom room guys are the most likely to work it out.

**Comment by cybercop23** [comment]
@pixelnewbie can you please close this issue?
