### ISSUE TITLE
FPP connect on 2023.09 seems to upload udp output to wrong device

### ISSUE THREAD

**Issue by bloojoop** [xLightsSequencer/xLights#3855]
I have xlights 2023.09 and have multiple fpp devices.  I select just the device known as picap (192.168.4.250) and set upd out to all.  This device does not get the upd outputs configued and I took a look at the log and noticed that it did upload to another device that is not even selected.  It uploade ouputs to my k8b (192.168.4.247) even though it is not even selected.  Attaching screen shot of fpp connect settings and the lights log. 
![fppconnect wrong device](https://github.com/smeighan/xLights/assets/88390168/7fff5551-0d92-47fd-9c0d-3fa61c613fc6)
[fppconnect log.txt](https://github.com/smeighan/xLights/files/11872197/fppconnect.log.txt)

**Comment by cybercop23** [comment]
Hey Ron. Is this still an issue? TBH haven't see/heard this in the zoom room. If not, do you mind closing it?

**Comment by bloojoop** [comment]
Yes this was an issue that did get resolved.. It was related to the falcon
f16v4 and was fixed with many of the fpp connect updates.

**Comment by bloojoop** [comment]
This was resolved back mid year 2023 with one of the fpp connect updates.
