### ISSUE TITLE
xLights Crashing When Creating New Sequence

### ISSUE THREAD

**Issue by jpappas6** [xLightsSequencer/xLights#3858]
MacOS Ventura 13.4.1
xLights: 2023.09.3

The bug is after I have rendered and saved a sequence, when I hit the New Sequence button, xLights crashes. The bug started today, but today is the first time I have rendered and saved a sequence and then tried to start a new sequence on build 2023.09.3

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Without at least your networks and rgbeffects files there is nothing we can do to investigate this.

**Comment by jpappas6** [comment]
Sorry about that, Keith. My first time submitting a bug report. I'll add them on the Github page.
________________________________

**Comment by jpappas6** [comment]
Adding networks and rgbeffects files.
[xlights_networks.xml.zip](https://github.com/smeighan/xLights/files/11929872/xlights_networks.xml.zip)
[xlights_rgbeffects.xml.zip](https://github.com/smeighan/xLights/files/11929873/xlights_rgbeffects.xml.zip)

**Comment by cybercop23** [comment]
@jpappas6 is this still an issue? If not, please close.

**Comment by jpappas6** [comment]
Done.

Sent from my iPad

On Jan 28, 2024, at 10:34 PM, AlexB ***@***.***> wrote:

﻿

@jpappas6<https://github.com/jpappas6> is this still an issue? If not, please close.
