### ISSUE TITLE
Xlights crash on Macbook Air 2016

### ISSUE THREAD

**Issue by drianpop** [xLightsSequencer/xLights#3862]
Hi! i just downloaded Xlights on my old macbook to being able to move around with it while running shows outdoor, and when i transfer all the folders and open the secuence, everything looks good, but as soon as i move, click or something on the timeline of the secuence, it crashes.

Anybody has the same problem? What can i do? I should  download older versions of Xlights they will support the FX on the secuence?

Thank you in advance!

**Comment by cramerph** [comment]
MacBook Pro with macOS Monterey 12.6.7. Accessing old sequences or creating new sequences xLights crashes as soon as I try to render.

**Comment by cramerph** [comment]
I deleted everything in the layout and it seems to crash only after I created groups, or downloaded a model from Boscoyo.

**Comment by cybercop23** [comment]
@cramerph is this still an issue? If so, please hop in the zoom room, xlights -> help -> zoom or if no longer an issue, please close.
