### ISSUE TITLE
Data layer import issues with "one output" selected in setup tab

### ISSUE THREAD

**Issue by nmiller0113** [xLightsSequencer/xLights#387]
Dan Kulp has already confirmed this bug on Facebook when Gil Jones asked him about it in response to a message in the forums from me.  When "one output" is selected and used on the setup tab data layer imports don't work right. It truncates the channel count to the size of the first universe.  It's reproducible every time until I rebuilt my setup without "one output" selected...when it is not selected data layer imports work perfectly.

**Comment by cybercop23** [comment]
Is this still a thing? Can it be closed?
