### ISSUE TITLE
xLights closes (just goes away) when rendering a sequence

### ISSUE THREAD

**Issue by chuckackerman** [xLightsSequencer/xLights#3874]
I have a sequence that, when rendered, causes xLights to close near the end of the rendering process.  It seems to crash when the only model left to render is a matrix.  The matrix is about 75% completed when it crashes.

This sequence is a purchased sequence and I've been advised not to post a link to the sequence package here but will gladly send a link in a PM if requested. 

Here is the most recent log file after a crash: https://drive.google.com/file/d/1BvQ_QUhTsuz3zu2Wh15zNLlwX_jg2b-x/view?usp=sharing

Let me know if there's anything else I can provide to help solve this issue.

PC Specs:
Processor	12th Gen Intel(R) Core(TM) i7-12700F   2.10 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor

Windows Specs:
Edition	Windows 11 Home
Version	22H2
Installed on	‎4/‎6/‎2023
OS build	22621.1928
Experience	Windows Feature Experience Pack 1000.22644.1000.0

Regards,
Chuck Ackerman

**Comment by derwin12** [comment]
Chuck - can this be closed - or can you duplicate it still?
