### ISSUE TITLE
Independent control of props using Jukebox mode

### ISSUE THREAD

**Issue by Lanzap** [xLightsSequencer/xLights#3879]
**Is your feature request related to a problem? Please describe.**
I am currently running a VBS live skit show that is using 4 different lighting pixel props to enhance the performance of the show.  I am using jukebox buttons (in loop mode) to set the displayed effects of the props.  In the current version of xlights, if a jukebox button is selected, then all of the props in the layout will change to display the effect set for each prop in the time frame specific in that jukebox selection.  The problem I am trying to solve is to come up with a method where I can control the props independently such that I can change the effect of one (or more) prop without changing the current effects on the other props.

**Describe the solution you'd like**
I would like to see a solution that allows an effects of a prop to change independently from other props.  In other words, it would be nice to be able to have two or three props (lets say 1.  A matrix screen, 2. Walkway Arches, 3. A Star).  The following is an example of what would be nice to accomplish:
1.  Set the matrix screen to an image of Darth Vader, the walkway arches to a red swirling effect, and the star to a red morph.  
2. One minute later, change the image from Darth Vader to Yoda while the walkway arches continue the red swirl effect and the star continues to morph.
3.  Once minute later, change the walkway arches from a red swirl effect to a green swirl effect while the matrix screen continues to display an image of Yoda and the star continues to morph.
4. One minute later, change the star a butterfly effect while the matrix screen continues to display an image of Yoda and the walkway arches continue the green swirl effect.
5. One minute later, change the matrix screen to show a video of an x-wing flying, change the walkway arches to a blue ripple effect, but the star continues to show a butterfly effect.

**Describe alternatives you've considered**
I have looked into xFade as two xLights executables are launched separately and their effects can be mixed before sent to output; however, I am primarily looking at changing the effect of each prop independently from the others instead of cross fading two different effects.  This did give me an idea.  I created 4 different show folders, and each show contains a single prop and a sequence with a series of jukebox buttons that display effects for that prop.  Each prop has its own controller, each with a different IP address, and each with a different set of universe numbers that are used to help keep everything independent.  

After thinking about this, I suppose it's possible to use xFade to control two of these independent props utilizing 2 of the show folders mentioned above.  It seems you could set the cross fade slider in the middle to output to the two different props independently; however, this would still be limited to just 2 independent props (show folders) whereas I need more than 2.

Currently, I am launching 4 different instances of xlights with each instance set to a different show folder (with different controllers, different IP addresses, different universe numbers).  After opening a sequence on each of the 4 different xLights windows, I click "Output to Lights" on each instance of xLights.  After the first "Output to Lights" is clicked, the other three instances produce a warning message stating "Another process seems to be outputting to lights right now.  This may not generate the result expected."  I click "OK" to proceed with output to lights.  Next, I display the jukebox window from each sequence on my Windows Desktop and minimize the xLights windows so that all I see are 4 jukebox windows, each with a series of buttons.

Operating with 4 instances of xLights seems to work fairly well.  I can control the lights on each prop independently, but seems that two occasional bugs show up:
1.  Sometimes the signal will drop momentarily causing the lights to stop for a couple of seconds, then continue with the effect.
2.  Sometimes the loop effect stops working so the prop displays the next effect instead of repeating the effect as selected.
 
I am not sure if these bugs are a negative effect of setting multiple instances of xlights to "Output to Lights".

It would be nice to have a program similar to xFade, but for just for setting jukebox effects on more than 2 jukebox windows with or without a cross fade tool.

**Additional context**

**Comment by AzGilrock** [comment]
I'm sure there is a better way to accomplish this using either FPP or xSchedule.  They are real show players.  xLights was not really meant to be used for live show playback.  With the show players you can have inputs that trigger things to happen and you can have model overlays so that things only effect one model.  You can pretty much control everything.

**Comment by Lanzap** [comment]
Thank you for the suggestions on looking more into the show players, I will
do so.  I've been used to Christmas light show sequences in the past and
have recently been getting more involved with live show playback for
non-Christmas activities.  After being introduced to jukebox mode and
xFade, there seemed to be methods since xFade seems to be more of a live
show playback to some extent.

**Comment by cybercop23** [comment]
Is there anything else to be done here? If no, please close.
