### ISSUE TITLE
Minor: Shader Box Red when downloading a shader until click off and back on.

### ISSUE THREAD

**Issue by sidelights** [xLightsSequencer/xLights#3888]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When adding a shader from the download button the filename box will stay red even if it's a valid shader until clicking off and back on the first time. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Drag a shader effect to a prop/group.
- note filename box is red as nothing is in it. 
3. Click download
4. select a shader 
5. filename box stays red until you click off the effect and back on.  Then box becomes white. 

This is a different behavior than if you browse to a already downloaded shader, upon which after selecting the box is immediately white. 

**Expected behavior**
after downloading a new shader the box should go immediately to white as it does when browsing to a shader file. 

**Screenshots**

**Versions (please complete the following information):**
 Win 11, 
xlights 2023.11

**Comment by cybercop23** [comment]
Available in the nightly and next version.
