### ISSUE TITLE
DMX FPP Issue

### ISSUE THREAD

**Issue by kbostick88** [xLightsSequencer/xLights#3892]
I have noticed an issue with FPP based controllers and DMX.

I set up wireless bracelets with the DMX controller, when I upload the output to the controller FPP is not updating correctly. When I try to manually adjust it, it doesn't seem to save. If I upload the configuration to a Falcon controller it works as expected. 

In the FPP output settings it shows DMX Pro, even though I set it to DMX Open and it shows 16 channels when it should show 5. 
I included screen shots of FPP and my Xlights Config along with a test sequence were it works on Falcon, but not on FPP. 

I tested this on Wallys WB1616 and a PiHat same issue on both. 

[](url)
<img width="1263" alt="Screenshot 2023-07-29 at 10 32 46 PM" src="https://github.com/smeighan/xLights/assets/17733692/3ed5f9a8-4d38-4e82-91df-cc2e77e9b122">

[DMX FPP Bug.zip](https://github.com/smeighan/xLights/files/12208417/DMX.FPP.Bug.zip)
<img width="749" alt="Screenshot 2023-07-29 at 10 33 10 PM" src="https://github.com/smeighan/xLights/assets/17733692/3d09e4ee-968c-46ae-b94b-7666db32ea22">

**Comment by computergeek1507** [comment]
Unsure about the DMX Pro vs Open, but FPP requires a minimum of 16 channels as some DMX controllers require 16 channels present for them to output data.

**Comment by kbostick88** [comment]
Okay, thanks for clarifying that. I don’t get any output with either dmx open or pro though. This was brought to my attention by another user, so I tested on my end and duplicated the issue. Any suggestions what may be happening?On Jul 29, 2023, at 10:45 PM, Scott Hanson ***@***.***> wrote:﻿
Unsure about the DMX Pro vs Open, but FPP requires a minimum of 16 channels as some DMX controllers require 16 channels present for them to output data.

**Comment by cybercop23** [comment]
Are you sure you are connected to TTY1? Here's my bracelet setup on an RPi-MFC...
![image](https://github.com/smeighan/xLights/assets/23619433/1d5b7169-41d5-464a-91b7-ada1360b790a)

**Comment by cybercop23** [comment]
@kbostick88 is this still an issue? Pretty sure you ran your shows with bracelets last year.. :)
If no issue, please close.
