### ISSUE TITLE
Add a save as option to the color palette save button

### ISSUE THREAD

**Issue by cox941** [xLightsSequencer/xLights#3902]
In the current version of xlights, when you save a custom color palette it defaults to the palettes folder in the show folder. It is frustrating to have to go to that folder and rename your custom colors. 

I would like to see the addition of a save as option when you press the save icon.

With the additional colors available in AI making custom palettes is easier than ever. 

![Capture](https://github.com/smeighan/xLights/assets/111090879/b68632c2-e5ca-417f-be51-217679121cfc)

**Comment by cbennett6008** [comment]
Perhaps if space is limited, an option could be added to the dropdown to save as new?

**Comment by cox941** [comment]
sure  anyway to create a new named palette. thank you for looking at this.

**Comment by cybercop23** [comment]
@derwin12 maybe a way to add a prompt when saving a palette file to enter/override the name it was going to use.
