### ISSUE TITLE
Unable to save sequences on MacOS

### ISSUE THREAD

**Issue by catcherdev** [xLightsSequencer/xLights#3907]
**Describe the bug**
Saving any sequence from within xLights results in this error, and sequence is not saved:
> Unable to create file: the_sequence.fseq. Check directory and file permissions.

**To Reproduce**
- Install xLights via App Store on MacOS Monterey `12.2.1`
- xLights version is `2023.11`, wxWidgets `3.3.0`
- Open an existing sequence, or create a new one
- Save using the file icon, save action from menu, or cmd-s

**Expected behavior**
- Successful save with no error

**Versions (please complete the following information):**
- OS: MacOS Monterey `12.2.1`
- xLights `2023.11`
- wxWidgets `3.3.0`

**Additional context**
I've tried allowing/opening the file & directory permissions a number of ways:
- MacOS Privacy/Security -> Full Disk Access -> Check the box for xLights
- MacOS Privacy/Security -> Files and Folders (xLights is not an option here)
- Finder -> right-click directory -> Get Info -> Sharing & Permissions -> add `Read & Write` for all options (user, staff, everyone)
- Terminal -> `chmod a+rw` recursively on the directory
- Tried saving to a completely different root folder, same result

I also uninstalled xLights completely, and reinstalled from scratch using the Mac App Store.

**Other Notes**
I was able to save normally on this machine in Dec 2022. Revisiting now, I'm unable to save any sequences.
It's possible the OS was upgraded since then (I can't be sure), but I'm certain xLights was updated since then.

xLights is an amazing project. Your efforts are greatly appreciated.

**Comment by AzGilrock** [comment]
Where’s your show folder?  Can you do a Tools -> Package Log Files?

**Comment by dkulp** [comment]
Try reselecting the save location at the bottom of the Sequences tab in preferences.   Definitely make sure the directory pointed to there actually exists.

**Comment by cybercop23** [comment]
@catcherdev can you please close?
