### ISSUE TITLE
Single Strand - UI not removing the color band

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#3930]
If you use the Skips it shows a color band...
![image](https://github.com/smeighan/xLights/assets/4643499/302969a1-6f2c-4c8e-a9da-76759fabbb36)

If you switch back to Chase it doesnt remove the color band nor does it use it / update it..
![image](https://github.com/smeighan/xLights/assets/4643499/3bb96773-471c-4d31-ace9-31ba73e7bdf2)

**Comment by cybercop23** [comment]
I know someone that maybe can look into this issue... :)
