### ISSUE TITLE
Exporting a sphere as a 3d custom does not include all pixels

### ISSUE THREAD

**Issue by atticusm** [xLightsSequencer/xLights#3931]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Exporting a sphere as a 3d model does not export all the pixels

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a sphere
2. Set parameters to 360, -86, 86, 1, 40
3. Right click and export as a custom 3d model
4. Import model

**Expected behavior**
Model data should have all 40 pixels

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**
After importing the 3d model, only 23 out of the 40 pixels will import. Scott mentioned there was an issue when exporting non-3d where if multiple pixels were in the same area they wouldn't export. This was fixed for the 2d model but not the 3D. 

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

I created a sphere with the dimensions above and exported it as a 3d model. I looked at this model in notepad++ and it did not have all the pixels. Same as re-importing it. https://drive.google.com/file/d/1CaEoThSSTKDO15DjQihOH49ltovAuGN0/view?usp=drive_link
If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
what is you stands per string count?

**Comment by atticusm** [comment]
8. The numbers are:
Degree 360
Southern Lat -86
Northern Lat 86
# Strings 1
Node/String 40
Strands/String 8

The custom model is accessible with the google drive link above

**Comment by digitydogs** [comment]
This bug is also affecting exporting of mega trees as custom models. 

Create a 1 string 950 node 19 zigzag tree and export it as a custom model.  The generated model will be over 4 megs in size and will be missing the lower right half of the tree.   

Exporting as a 3d model does not result in a larger file size or missing nodes, but the alignment of the nodes is off.

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.
