### ISSUE TITLE
Custom Model Bug

### ISSUE THREAD

**Issue by wcfrostick** [xLightsSequencer/xLights#3944]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When a Node number is missing from a custom model nodes above that range will not visually show up correctly

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. remove a node number in middle of the model
2. select a following node number above the missing node
3. observe the incorrect location of the highlighted node

**Expected behavior**
highlight the correct node visually

**Screenshots**

**Versions (please complete the following information):**
Windows 2023.13

Hi Keith

![xlights issue](https://github.com/smeighan/xLights/assets/23414459/d22ea8d0-5fcc-49e2-8491-4bac20b68b69)

**Comment by cybercop23** [comment]
I removed 58 and everything stayed in place and looks fine. Is your issue related to the zoom in, size, 250 seems high or having an image. Try without.
If not an issue, please close.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/9598a94d-61a8-4157-81c4-74111b1e47e8)
