### ISSUE TITLE
Falcon PiHat in .13 it shows  the controller as having 4 ports when it only has 2. I had a friend try it and it's the same for them. I am using a windows pc

### ISSUE THREAD

**Issue by iancooper65** [xLightsSequencer/xLights#3948]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dartunder** [comment]
The second two ports are shown in red to indicate invalid ports.  
To my understanding, ports are added in groups of 4 as part of the logic to support long-range receivers.

Code Notes:
int UDController::GetSmartRemoteCount(int port)  is creating 4 ports ...

In void ControllerModelDialog::ReloadModels() [ControllerModelDialog.cpp] check to see if the controller supports smart remotes or has more than 4 channels.

        if (pp != nullptr) {

            int currentSmartRemote = 0;
                
           int smartRemoteCount = 0;
            if ((_caps->SupportsSmartRemotes() > 0) || (_caps->GetMaxPixelPort() >= 4)) {
                smartRemoteCount = _cud->GetSmartRemoteCount(i + 1);            
            }

Seems to work but I'm unsure of the consequences of this change, but maybe it helps point you in the right direction. 
Not sure if the _caps->GetMaxPixelPort() >= 4 is needed, but I was trying to be conservative.

**Comment by iancooper65** [comment]
Thanks for the prompt reply. I thought it would still work, but wanted to be sure Ian Cooper On 1 Sep 2023, at 02:59, dartunder ***@***.***> wrote:﻿
The second two ports are shown in red to indicate invalid ports.
To my understanding, ports are added in groups of 4 as part of the logic to support long-range receivers.
Code Notes:
int UDController::GetSmartRemoteCount(int port)  is creating 4 ports ...
In void ControllerModelDialog::ReloadModels() [ControllerModelDialog.cpp] check to see if the controller supports smart remotes or has more than 4 channels.
    if (pp != nullptr) {

        int currentSmartRemote = 0;
            
       int smartRemoteCount = 0;
        if ((_caps->SupportsSmartRemotes() > 0) || (_caps->GetMaxPixelPort() >= 4)) {
            smartRemoteCount = _cud->GetSmartRemoteCount(i + 1);            
        }

Seems to work but I'm unsure of the consequences of this change, but maybe it helps point you in the right direction.
Not sure if the _caps->GetMaxPixelPort() >= 4 is needed, but I was trying to be conservative.

**Comment by cybercop23** [comment]
@iancooper65 can this be closed? if so, can you please close it?
