### ISSUE TITLE
FPP 7.1 cannot seem to push outputs or models if UI has password

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#3951]
We know the fix - remove the password.
But is this intended to work? Two folks today came in zoom today where it was not able to 
fpp connect and successfully push outputs or models.
It simply returns after a very quick progress bar. The view log shows "GET" but no PUT or  POSTS.
Restarting xlights shows us that there was a password after doing fpp connect - and hence we turned it off to move forward.

Daryl.

**Comment by dkulp** [comment]
I'm not able to reproduce this.    I was able to push models, UDP outputs, sequences, media, etc... to an FPP 7.1 instance that has a password configured.

**Comment by derwin12** [comment]
We tried in zoom again .. and could not duplicate either..

**Comment by MDickson00** [comment]
Hey Dan, ran into this exact issue today in Zoom. FPP connect would ask for UI password, once password was input it would not discover FPP, input the FPP IP manually and it would discover the Pi but uploading would not write the UDP information to the Pi. Deleted the old UDP outputs, disabled UI password, rebooted the Pi (turning off UI password did not show a reboot or restart flag) and FPP connect found and uploaded the UDP information and is working fine now. I don't know if it's of any help but the UI password field would pop up two times one on top of the other.

**Comment by derwin12** [comment]
Continues to be a problem.  From zoom .. upload outputs via fpp connect, appears to work but in fact is not pushing the config settings. .18 with 7.2 FPP. Gets  RC: 408

**Comment by derwin12** [comment]
2023-11-02 10:29:18,096 14228 log_curl [INFO]     Discovery CURL Callback - Unauthorized
2023-11-02 10:29:18,714 14228 log_curl [INFO]     Discovery CURL Callback - Unauthorized
2023-11-02 10:29:19,508 14228 log_curl [INFO]     Discovery CURL Callback - Unauthorized
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/13242778/xLightsProblem.zip)

**Comment by derwin12** [comment]
[FPP_Logs_20231102.1729.zip](https://github.com/smeighan/xLights/files/13242799/FPP_Logs_20231102.1729.zip)

**Comment by derwin12** [comment]
Does the code catch and requery for a password if the stored password is incorrect? is that triggered by a 401?
![image](https://github.com/smeighan/xLights/assets/4643499/63ba5d32-c645-4d3e-a296-19bc19dde94b)

**Comment by computergeek1507** [comment]
Probably should remove the password==""

**Comment by cybercop23** [comment]
@derwin12 I know we generally tell folks to disable it, but is this still an issue? Thought @dkulp did a whole bunch of work to fix it and can't reproduce it. If we want to keep it, maybe we can do a deep dive and figure out what/where is happening.

**Comment by derwin12** [comment]
I am curious about Scott's note .. looking at the code, it appears to be broken. As it checks if password == "" then it expects it to be != ""

**Comment by derwin12** [comment]
I tried removing that code Scott and that makes it go thru the getstoredPasswordForService - and it infinitely loops if that password is incorrect. So closing this as unable to duplicate.
