### ISSUE TITLE
loop sequence

### ISSUE THREAD

**Issue by johnnick349** [xLightsSequencer/xLights#3982]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnnick349** [comment]
Hi
I am  just starting to use this and this program is very powerful, All of you developers have done a wonderful job.

using xlights xschedule 2023.14 can a 30 sec sequence be looped to keep running ?

I would like to have the ability to loop ( repeat) a sequence so it goes back to the start  either in Xlights sequencer or xschedule. EX) a 30 sec sequence keep running, ( loop back to start).

I am using a raspberry and FPP connect. I do not want to have to launch FPP, select show and select loop. 

I do have the loop checked and I see that the max count can be set to only 100. I have tried a zero count but the event times out.

**Comment by merryoncherry** [comment]
xSchedule will do it.

**Comment by keithsw1111** [comment]
There is not enough information here to troubleshoot your issue, Are you kicking it off using the schedule or using an event. If an event what command are you using. I would set loop count to 0 ... you dont want it limited.

**Comment by johnnick349** [comment]
I did try a count of zero.
I will supply more information tomorrow.
Thanks john

**Comment by dartunder** [comment]
@johnnick349 If your issue is resolved, please close this

**Comment by cybercop23** [comment]
@johnnick349 can you please close this issue?
