### ISSUE TITLE
fppconnect on mac - should it show master/multisync ??

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#3985]
.. or was that changed on the mac or v7.1
Shows player/w multisync on the windows fpp multisync page.

![image](https://github.com/smeighan/xLights/assets/4643499/c862fffd-2f8c-41c4-82d3-6966bdd460ec)

**Comment by computergeek1507** [comment]
Depending on how the FPP device is discovered it may show master for some reason

**Comment by dartunder** [comment]
was the master listed in the controller list?

**Comment by cybercop23** [comment]
2024.2 seems okay. Player is not in my ctrl list. It was discovers and has the right desc.  Okay to close?
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/264ecb44-5ac7-4e84-98fc-0d9a37774230)
