### ISSUE TITLE
Arch appearance changing in house preview

### ISSUE THREAD

**Issue by whirlywhopter** [xLightsSequencer/xLights#3986]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

When working with a sequence, the house preview will suddenly begin rendering arches with a very exaggerated pixel size (appearance).  This also affects the "Export House Preview Video", often changing suddenly at a random point within the sequence as the video is being exported.  Sometimes the appearance will revert back after time or when zooming or moving within the preview window but in other cases a restart of xLights or the computer can be required.

**To Reproduce**

The problem seems to occur randomly while working with lights.  I have not yet been able to find a specific action or set of actions that reliably trigger it although it often occurs when zooming or moving within the house preview window or during the "Export House Preview Video" process, often changing size during the exported video.  This behavior does not happen within the layout tab view.

Appearance settings for arches:
  Pixel Size 7
  Pixel Style Blended Circle
  Transparency 0
  Black Transparency 0
  Tag Color Black

**Expected behavior**
Preview window should reflect appearance settings and display seen when viewing the arches in the layout tab and should not randomly change size/appearance

**Screenshots**
I have attached a screenshot showing how the arches are displayed in the Layout tab view which does not seem to be affected by this behavior.  The other 2 screenshots were both taken from the same recently exported house preview video.  Initially in the video, the arches rendered with the correct pixel size appearance but a little more than 1 minute into the 3 minute video, the rendering of the arches changes to the exaggerated size for the remainder of the video.  After the export was completed, the house preview window continued to show this exaggerated pixel size but otherwise seemed to work normally

**Versions (please complete the following information):**
 - 64GB MacBook Pro M1 Max
 - OS:  13.6
 - xLights version:  2023.14.2

**Additional context**
Issue seen across multiple xLights and MacOS versions and is not specific to a particular sequence.

**Attachments**
![Arches as seen in Layout view](https://github.com/smeighan/xLights/assets/104389627/0a79ecb6-33cb-46df-a157-d5ac4e522d71)
![Arches rendered normally in House Preview](https://github.com/smeighan/xLights/assets/104389627/6f51d9b5-da73-4674-aa7a-42d834a2c04c)
![Arches rendered incorrectly in House Preview](https://github.com/smeighan/xLights/assets/104389627/780b539d-2a84-4025-91f0-49f38daa4c8e)

**Comment by keithsw1111** [comment]
It would be useful if you could attach a simple sequence that shows the problem.

**Comment by whirlywhopter** [comment]
Apologies for the delay, I was traveling.  The issue seems to occur randomly with any sequence, most often when exporting a house preview video or when moving or re-sizing the house preview window itself or moving it between screens.

**Comment by keithsw1111** [comment]
I am going to close this unless we get a packaged logs/sequence that demonstrates the problem.

**Comment by whirlywhopter** [comment]
The issue does not regularly occur with any specific sequence, it seems to happen randomly with any sequence.  As an example today, I had it occur when changing from one perspective to another which moved the house preview window to a different screen (I use dual monitors).

I am more than happy to try to provide logs or whatever information might help to troubleshoot but the issue does not seem to be specific to any particular sequence file and I have not found a process yet that can consistently produce the issue.  When the issue occurs next, what logs or files should I collect that might be helpful?  I am happy to do this.

I have noticed that in the most recent releases it seems to be occurring less often and sometimes the preview display reverts to the normal pixel size on its own (it was not doing this when I opened this report, it required a restart of xLights or the computer to resolve at that time)

**Comment by keithsw1111** [comment]
You say that but then never do. I need packaged logs or a blank packaged sequence.

**Comment by keithsw1111** [comment]
I do not want a log file ... I need packaged logs ... see the tools menu. These contain more than just the log files. They can be placed here as a dropbox or similar link.

**Comment by whirlywhopter** [comment]
I have the packaged logs captured immediately after I noticed the issue occur.  Can I PM these to someone so that I do not post the included sequence file?  I also created a blank sequence as a packaged sequence as requested, if this is helpful I can send it as well.

**Comment by AzGilrock** [comment]
If you do Tools -> Package Log Files it does not include a sequence but it does contain everything in your layout which helps more than just a log file.  You have to do a Package Sequence for it to include a sequence so don’t do that.   I don’t look at stuff unless it’s posted publicly or it’s a good friend.

**Comment by whirlywhopter** [comment]
I was able to capture the packaged logs immediately after the issue occurred again.  Can I DM these to someone since the zip file appears to include the sequence as well?  I have also packed a blank sequence that I can include too if this provides other information beyond what is included in the packaged logs zip file.

**Comment by AzGilrock** [comment]
If if contains a sequence you didn’t follow what I said?  What menu option are you using?  If you do what we say everyone can help instead of expecting one person to look at it

**Comment by dartunder** [comment]
FYI: I just verified this behavior, If you have a sequence open when you select Package Log Files then the open sequence is included in the zip file.

**Comment by AzGilrock** [comment]
Someone needs to fix that….the whole intent of package log files vs package sequence was supposed to be the presence of a sequence

**Comment by dartunder** [comment]
Including the sequence is intentional for debugging issues, according to this description from the code below.
If however, you close the sequence and select package logs, it will not include the sequence.  

-------
    MenuItem38 = new wxMenuItem(Menu1, ID_MENUITEM18, _("&Package Log Files"), _("Packages up current configuration, logs and sequence for reporting a problem to development team."), wxITEM_NORMAL);	C:\custom_xlights\xLights\xLights\xLightsMain.cpp	987	59

**Comment by AzGilrock** [comment]
Guess I've never had a sequence open.  Problem is nobody sold sequences back when that code was written...it should be optional now.  Someone handy with a computer should be able to edit the zip file and remove the sequence if they are worried about sharing it.

**Comment by AzGilrock** [comment]
But I do apologize for saying you didn’t follow my instructions.   I thought we’ve been telling people for years to use this option when we didn’t want the sequence.

**Comment by keithsw1111** [comment]
It does include the sequence if one is open but not all the assets ... just the effects. Feel free to send it to me and i will take a look.

**Comment by whirlywhopter** [comment]
Apologies, I may not have been clear either that I was later able to go back and do the log file capture from the menu.  Keith, should I just email the files to the account in your Github profile?

**Comment by cybercop23** [comment]
@whirlywhopter is still still an issue? If not, please close it. 
If you need help getting the right info, hop on zoom, xLights -> Help -> Zoom.
