### ISSUE TITLE
Weird behavior when changing font for a text effect

### ISSUE THREAD

**Issue by BoxerMark** [xLightsSequencer/xLights#4000]
While editing another person’s file (Halloween Horror Lights - Bloody Mary), I selected a text effect on the "Right Matrix." The font was .AppleSystemUIFont, 11. (I am using a MAC, BTW, but I don’t know what system the sequel was created on.)

I select Arial Black and the selection bar jumps to Savoye LET. I scroll back up and select Arial Black again. I click OK. The screen shows the selected font is Times, 11.

I click the font button again. Select Arial Black, selection jumps, I scroll up select Arial Black, press OK and the font changed correctly.

System doesn't crash. This behavior has happened at least 5 times while changing font.

**Versions (please complete the following information):**
 - OS: Mac 10.15.7 (I have an old iMac and this is the last version to which I can update)
 - xLights version 2023.14.2

![Screen Shot 2023-09-27 at 2 02 54 PM](https://github.com/smeighan/xLights/assets/146260627/7b923ea3-4264-4cbf-9bcc-606abfc2335f)
![Screen Shot 2023-09-27 at 2 07 06 PM](https://github.com/smeighan/xLights/assets/146260627/8115fb7f-f11f-4d2a-8ad7-53a764f8e0fc)
[Halloween Horror Lights 2023 - Bloody Mary.zip](https://github.com/smeighan/xLights/files/12742656/Halloween.Horror.Lights.2023.-.Bloody.Mary.zip)

**Comment by cybercop23** [comment]
@BoxerMark can you please re-test in the latest 2024.2 and if still an issue, so a screen record.
Else, please close.
