### ISSUE TITLE
Allow copy+paste from timing to model/group layer

### ISSUE THREAD

**Issue by djulien** [xLightsSequencer/xLights#4004]
**Is your feature request related to a problem? Please describe.**
I typically have a timing track with cues/annotations, lyrics, or other labels which are placed precisely for the correct timing, and then wish to place some effects on group or model layers to exactly line up with those timing track marks.  If there are just a few, this can be done manually, but if there are many then it is time-consuming to try to precisely place all those effects.  If I try to copy+paste a row from a timing track to a model/group layer, xLights gives the message "Not enough timing rows to paste timing effects starting on this row"

**Describe the solution you'd like**
I realize that timing marks and effects are different objects, but it would be very handy to be able to copy a timing track to a layer on a group or model, with xLights generating a placeholder On effect for each of the timing track marks.  This would put placeholders in all the correct places, and then the Effect Settings can be used to fine tune what the effect should look like.

**Describe alternatives you've considered**
I tried selecting the timing track label and a placeholder effect,, then selecting the Alignment right mouse functions but they did not do anything.

I also tried copying a timing track from xLights and then pasting it into an external text editor (which gave a ""CopyFormat1 ... NO_PASTE_BY_CELL ..." text block), changing the timing track labels to a "On C_BUTTON ..." string representing an On effect, then copying that to clipboard and trying to Row->Paste effects in xLights, but it gave the same message.

**Additional context**
Is there another way to precisely align a bunch of effects to timing marks more easily?

**Comment by keithsw1111** [comment]
Isnt that why you select the timing track then the timing marks appear and you drop effects.

If the effects are already there ctrl left + right will move to timing marks. ctrl+shift left + right will stretch to timing marks

**Comment by djulien** [comment]
> Isnt that why you select the timing track then the timing marks appear and you drop effects.

Yes, but if i wanted many effects to line up with the timing marks, then it is time-consuming to adjust each effect separately.
 
> If the effects are already there ctrl left + right will move to timing marks. ctrl+shift left + right will stretch to timing marks

Those keystrokes do make it easier for one effect at a time be aligned to the timing marks.  I was just looking for a way to do a bunch of them all at the same time. (for example, add or align an On affect with all of the Beat 1 timing marks, but not the Beat 2, 3, 4, etc)

**Comment by derwin12** [comment]
I think this is covered with the duplicate effect and the new option that was added to retain the timing. So you can place one effect at the timing mark and then duplicate it across to each of the other timing marks.
You can also right click and copy words out of a lyrics and paste to a new line to get timing marks from the lyrics breakdown.
ex of copying the words breakdown to a new timing track then using duplicate to place the one effect at each timing mark.
![image](https://github.com/user-attachments/assets/90bbcd75-bb6d-42b1-9b77-be58ed62935e)
