### ISSUE TITLE
Setting chapters doesn't work on Linux

### ISSUE THREAD

**Issue by fone626** [xLightsSequencer/xLights#4023]
I recently watched Ron Howard's video called "Navigating xLights With Chapters" and realized that the numbers that I have been looking at for years when I click on the timeline actually do something after all, and it would be incredibly useful if I was able to use them.

So under Linux when you select a number by right clicking on the time line nothing at all happens at all.  However, If I get a friend to make a sequence with Chapters set then they show up and are usable and can be deleted but wherever they are set causes the waveform to go blank whenever a chapter marker is visible.  Zooming in to until the chapter marker isn't  will cause the waveform to show again.

**Comment by cybercop23** [comment]
Implemented and merged to master. Please validater in the next version.
