### ISSUE TITLE
Allow text effect to alternate by word instead of by letter

### ISSUE THREAD

**Issue by ekosman87** [xLightsSequencer/xLights#4032]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to change the color of the text on a matrix by word is to create a new effect for each word.

**Describe the solution you'd like**
Instead of the text of a matrix only being able to alternate by letter (or overlayed with another effect), create a check box that allows the colors in the pallet to alternate by word instead of by letter.

**Describe alternatives you've considered**
You can work around by creating a new effect per word, but that's very tedious, you can also layer a second color effect and tweak the fade in times to effect a word at a time but that's even more tedious.
**Additional context**

**Comment by djulien** [comment]
FWIW, I was thinking of suggesting a similar enhancement but using escape codes to reference the color palette in any order.  For example, something like \1 or {1} to select the first color in the palettte, \2 or {2} to select the second color, etc.  This would allow the colors to be used out of order from the palette.  for example, "\1 first color \8 last color, \2 second color, ..."

**Comment by cybercop23** [comment]
Implemented and merged to master. Please test the nightly (preferred) or in the next version.
