### ISSUE TITLE
Backup Question

### ISSUE THREAD

**Issue by NightmareOnRimrock** [xLightsSequencer/xLights#4039]
Hello!

We recently had our computer crash and are attempting to recover our X Lights data.

I know the program sends data errors, does it also send any type of cached data? I know it’s a long shot but we don’t want to leave any stone unturned.

Thank you.

**Comment by derwin12** [comment]
No... if you didnt copy it off your hard drive then you have lost it.

**Comment by keithsw1111** [comment]
Maybe ... did you enter your email address?

**Comment by keithsw1111** [comment]
If you dont answer the question then I cannot scan the crash dumps and identify your files (assuming they are there)

**Comment by derwin12** [comment]
Close this?
