### ISSUE TITLE
FPP Connect creating .patch.0 files on Mac v 2023.16 and FPP 7.2

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4054]
This was from zoom .. we couldnt figure out the reason. The files were renamed to simplify them. Ended up just using the browser and pulling them in. Do you see anything in the logs? If not, feel free to close.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/12910845/xLightsProblem.zip)

**Comment by dartunder** [comment]
Confirmed this is happening on a mac... with larger fseq files... not happening with tiny test files.

**Comment by Darzoom** [comment]
Log Files.  FPP 7.2 new etch.  
[FPP_Logs_20231016-2.zip](https://github.com/smeighan/xLights/files/12911032/FPP_Logs_20231016-2.zip)
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/12911042/xLightsProblem.zip)

**Comment by dkulp** [comment]
Cannot reproduce.  Sent some huge files via fppconnect.   
<img width="617" alt="Screenshot 2023-10-15 at 9 08 55 PM" src="https://github.com/smeighan/xLights/assets/91569/9c187835-4368-4b1f-bdf9-b8e62bd9ae99">

**Comment by derwin12** [comment]
Getting unable to upload outputs (timeout issue) when pushing to an F16v2 2.59. 
Is this the same issue? Timeout hitting /stringports.htm (if memory serves me)

**Comment by ljbrusta** [comment]
What are .patch.0 files when seen on an FPP? I suddenly started seeing them show up tonight when uploading from FPPConnect. I removed all the files for that sequence from the files directory and tried to upload it again. At that point I only got a .fseq.patch.0 file only a few kilobytes in size. The original .fseq file never uploaded. I had to rename the whole sequence, re-render it and then I got the fseq but a couple .patch files also. 
![image](https://github.com/smeighan/xLights/assets/47700342/0ced1ea6-ddc5-495a-aa80-8e9bb2c8b45a)
 

Running Windows 10, xlights 2023-18 and FPP Pi 7.2 - what files can I provide to help?

**Comment by derwin12** [comment]
Another one of these tonight .18 and latest 6.3. Anything we can do to help triage this?

**Comment by derwin12** [comment]
Windows and 6.3.2.2 -same thing .. was working on 6.0

**Comment by dartunder** [comment]
Any chance this or other network issues are IPV6-related?  Is there a way to disable IPV6 on the PI?  As fpp.local often resolves to an IPV6 address.

**Comment by derwin12** [comment]
Assuming this is addressed .. not seeing it much if at all ..
