### ISSUE TITLE
Upload output to Kulp K40PB says complete but outputs does not get changed

### ISSUE THREAD

**Issue by Lacehim** [xLightsSequencer/xLights#4060]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED. 

My Issue doesn't relate to a sequence, it relates to uploading the ports/channels for props to the controller

**Describe the bug**
When Pressing the upload output button xlights is reporting uploading, then complete but FPP (running on a Kulp BBB K40PB it wasn't changing any settings.  I reset the ports in FPP to blank and nothing uploaded at all.  xlights was set to full control so it should have wiped all settings on the outputs and uploaded as per my xlights configuration.  Having full control or not checked didn't change the outcome.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to controller
2. Click on upload output at the bottom
3. In FPP, go to outputs and check the outputs for the controlller

**Expected behavior**
Ports are changed on the FPP settings as per xlights config and replace old ports/models which are for Christmas, not halloween.

**Screenshots**
Attached below

**Versions (please complete the following information):**
 - OS: Windows 10 (updated to latest)
 - xLights version 2023.16 (latest)
 - FPP 7.2-2 (latest) (also an issue in 7.1

**Additional context**
I reloaded xllights 2023.10 and the issue wasn't present.  Upload went to complete, same as before but the config ports actually loaded and worked perfectly.

**Attachments**
Screen shot showing xlights config and FPP outputs after "successful" upload.
![2023-10-16](https://github.com/smeighan/xLights/assets/13537527/9f18a31c-d798-46a9-951b-79d61b0562e7)
![2023-10-16 (1)](https://github.com/smeighan/xLights/assets/13537527/c9d27382-4048-4353-8b9d-362c17d4b9c8)

**Comment by derwin12** [comment]
Same/similar to https://github.com/smeighan/xLights/issues/4061

**Comment by derwin12** [comment]
https://github.com/smeighan/xLights/issues/4022

**Comment by rshoover2001** [comment]
Exact same issue with 2023.16 and Kulp Lights Controllers (multiple) running FPP 7.1

**Comment by derwin12** [comment]
Try this patch version from Dan
https://github.com/smeighan/xLights/issues/4061#issuecomment-1767844468

**Comment by cybercop23** [comment]
Can this be closed? If so, @Lacehim please close. Looks like it is fixed in newer version. #4022.
