### ISSUE TITLE
Performing FPP Upload to ESPPixelStick produces Error 0 after upload even though file was uploaded

### ISSUE THREAD

**Issue by gwolanin** [xLightsSequencer/xLights#4063]
**Describe the bug**
I have an ESPPixelStick v3.0 firmware running firmware 4.0-ci6397314717.  Originally I was using [ESPixelStick v4.0-beta4](https://github.com/forkineye/ESPixelStick/releases/tag/v4.0-beta4) then I upgraded to xLights 2023.16 for Mac.  v4.0-beta4 would not work with xLights as I could not upload new fseq to the device.  It would just timeout.

I upgraded the ESPPixelStick to 4.0-CI release and now am able to upload new .fseq files, but after the FPP Connect has completed, a popup displays a 0 Error message.

I performed a wireshark capture and found he URI of the http_error==404 to be this URL  http://192.168.1.XXX/fpp?path=uploadFile&filename=NeonRopeTest-RWB-Twinklecat.fseq

**To Reproduce**
Have an ESPPixelStick v3.0 hardware with [ESPixelStick v4.0-beta4](https://github.com/forkineye/ESPixelStick/releases/tag/v4.0-beta4) installed
Have xLights 2023.16 version installed
Perform FPP Connect to ESPPixelStick
Files will be uploaded but popup will display an Error 404.

**Expected behavior**
Files should upload w/o incident

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac 12.6.6
 - xLights version 2023.16

**Additional context**

**Attachments**
Screenshot should be attached.

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
<img width="259" alt="Screen Shot 2023-10-17 at 9 26 09 PM" src="https://github.com/smeighan/xLights/assets/920438/ecb94f4e-4b71-401d-9530-15d33bcf3983">

**Comment by derwin12** [comment]
Try this version from a similar issue
https://github.com/smeighan/xLights/issues/4061#issuecomment-1767844468

**Comment by cybercop23** [comment]
@gwolanin  can this be closed? If so, please close it.

**Comment by gwolanin** [comment]
The error did go away when xLights was updated to the latest release in November.
