### ISSUE TITLE
2023.17 Bulk edit - Shaders - not saving where the files have been directed to 

### ISSUE THREAD

**Issue by jzlightshow** [xLightsSequencer/xLights#4064]
Currently running on Windows 11, 
No other programs running.  Was working on v16 with no issues. 
v17 upgraded today.  It's been running slow with having to wait to process some items. 

Imported a song: Smells like teen spirit. 
There are lots of Shaders in this song. 
I selected the shaders that needed to be directed to the special folder with my shaders. 
They all turned purple showing they were selected. 
I selected bulk edit.  
Directed it to the folder name.

Saved and rendered.  The first couple changed but the rest remained the same, not able to locate the files. 

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by jzlightshow** [comment]
I reverted back to v16.  And I noticed that each of the shaders file name had been given a number after each one. 
black cherry1
black cherry2
black cherry3 
etc. 
not sure if the bulk edit did that. 
But I went through and changed the file name for all the shaders using the bulk edit. so all the files are back to using the "actual" shader names.

**Comment by derwin12** [comment]
The 1,2,3 would happen if you did the "Clean Up File Locations". Suggest you pull the shaders in via the import from zip method. If you bring them in with the wrong paths, you lose many of the parameters and settings that went with them in the original sequence. When you fix the path, the parameters get restored BUT the original sequenced values for those parameters are lost.

**Comment by derwin12** [comment]
As an example - if xlights opens the sequence, or import is done and it doesnt know the .fs file - it wont know the parameter values.
![image](https://github.com/smeighan/xLights/assets/4643499/c644d22d-9841-49fa-8d62-3c37b771e6f3)
So only these values would be imported.

![image](https://github.com/smeighan/xLights/assets/4643499/eba2f782-0eb4-4f7d-9506-5442badd2f01)
Whereas if it knows the correct shader, all the parameters are available and would be imported.

**Comment by derwin12** [comment]
As for it being a bug .. I have it in..
https://github.com/smeighan/xLights/issues/3422

**Comment by kevinsaucier** [comment]
Good deal.  So, yeah, definitely seems like a bug, though the only way to 100% resolve it would be to prompt for any missing shaders upon import.  Kind of follows the theme of xLights not being able to find missing images/videos/etc., even though they are in the same folder (or a subfolder) as the sequence file or in one of the directories specified in the Preferences.  That is a continual annoyance.  I know the zip import 'fixes' that, but it's not really a fix, just a bypass of the issue.

**Comment by derwin12** [comment]
Keep in mind, if you are getting broken images/vid and/or shaders you are not following the right process. *IF* you unzip, you need to change show folders to the unzipped show folder, load sequence, render and save. Now you can import from that unzipped folder. Using  *just* the unzipped folder is not a correct way to do an import.

**Comment by kevinsaucier** [comment]
I guess I'm getting off topic from the original post here, but what does loading/rendering/saving the unzipped folder do?  It's not going to change the paths of the media files in the XSQ so what benefit is there?  I stopped doing that process years ago as I figured the only thing it did for me was to let me see the show on the original sequencer's layout, which I don't generally need to do.

**Comment by derwin12** [comment]
"what does loading/rendering/saving the unzipped folder do" - it repoints the files from the authors file structure, to your file structure.

**Comment by derwin12** [comment]
Can we close this? I cant duplicate it - bulk edit path is working as expected. Seems like an issue on the import.

**Comment by jzlightshow** [comment]
Yes On Jan 14, 2024, at 3:48 PM, Daryl ***@***.***> wrote:﻿
Can we close this? I cant duplicate it - bulk edit path is working as expected. Seems like an issue on the import.

**Comment by cybercop23** [comment]
@jzlightshow can you please close this? Only admins and owner can close.
