### ISSUE TITLE
Unable to Upload Outputs to older Alphapix (new as of .18, same in .19)

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4075]
(From Zoom)
From controllers tab, hit Upload Outputs.. Failed
The following is seen in the log:
Received HTTP/0.9 when not allowed

Went to .16 works and  .17 works

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/13073475/xLightsProblem.zip)

Older firmware .. but difficult to update with HolidayCoro process
![image](https://github.com/smeighan/xLights/assets/4643499/8b1946fe-9e8a-48d6-b3e9-f6f231052dc9)

**Comment by derwin12** [comment]
Believe this has been addressed. Thanks Scott.

**Comment by derwin12** [comment]
2 more folks have hit this issue.. Rolling back to .16 works. (Last version he used)

**Comment by computergeek1507** [comment]
Did you try the nightly?

**Comment by dartunder** [comment]
Note they are using an AlphaPix Flex 
Firmware 10.0 20-4-2022

**Comment by derwin12** [comment]
Yes just did. 20-apr-2022 firmware (for both)

**Comment by derwin12** [comment]
The 0.9 message went away but failed to connect results - rather quickly too.

**Comment by computergeek1507** [comment]
I'll see if I can reproduce it

**Comment by derwin12** [comment]
He is still in zoom if you want to check/verify/etc

**Comment by computergeek1507** [comment]
Is it direct or through a FPP proxy

**Comment by derwin12** [comment]
Direct.

**Comment by bcarriveau** [comment]
2 alphapix last night could not upload from 23.19. I didnt think about viewing logn untill after the fact. Just said upload failed in lower left. Uploads in 23.17.

 No proxy, flat networks. 

I'll try and grab a log to be helpful next round 🙈

**Comment by phatm1ke** [comment]
I can confirm as well .19 failed to upload output to 2x AlphaPix 16s and 1 AlphaPix 4. Rolled 'back' to .16 (saw in this thread) and it works.

To those complaining about no logs, not much to be had:

023-11-12 16:20:40,083 12176 log_curl [INFO] Adding Synchronous CURL - URL: http://192.168.69.2/    Method: GET
2023-11-12 16:20:52,082 12176 log_curl [INFO]     CURL Synchronous Response - URL: http://192.168.69.2/    Response Code: 0     Size: 0
2023-11-12 16:20:52,082 12176 log_base [ERROR] Failure to access http://192.168.69.2/: Operation timed out after 12000 milliseconds with 2920 bytes received.
2023-11-12 16:20:52,082 12176 log_base [ERROR] Error connecting to AlphaPix controller on 192.168.69.2.
2023-11-12 16:21:00,654 12176 log_base [DEBUG] Viewing log file C:\Users\lights\AppData\Roaming/xLights_l4cpp.log.


Flat network. Nothing complicated.

**Comment by AzGilrock** [comment]
Scott already committed a change that says it reverts the Alphapix code to the stuff that works
