### ISSUE TITLE
Keep FPPConnect dialog open after upload vs. just disappearing as if it crashed

### ISSUE THREAD

**Issue by ptr727** [xLightsSequencer/xLights#4081]
**Is your feature request related to a problem? Please describe.**
When using FPPConnect, and pressing upload, the UI shows some progressbar activity, but disappears before the progressbars completed to 100%, this always makes me think something crashed or broke.  
I am assuming that the progressbars did complete to 100% but the UI also closed at the same time.
 
**Describe the solution you'd like**
A more standard window behavior could be to keep the UI open until done, providing feedback about the task success/fail state, and then let the user close the dialog.  
Alternatively provide an option (config or in-dialog) to auto close on success, but then do make sure the progressbars reach 100% before closing, and only on success.

**Describe alternatives you've considered**
As is I use FPPConnect, wonder if it worked, check FPP file contents, make sure file timestamps match.

**Additional context**

**Comment by dartunder** [comment]
Can we update the status bar like it is done for upload outputs?

**Comment by cybercop23** [comment]
Please close as a change was implemented.
