### ISSUE TITLE
Xlights 2023-18 not uploading media files to Pi FPP

### ISSUE THREAD

**Issue by murraygyde** [xLightsSequencer/xLights#4083]
I am operating Windows 11 with the latest updates.

Xlights version 2023-18

Pi3B+running FPP version 7.2

Using FPP Connect on Xlights and selecting sequences with media files
![image](https://github.com/smeighan/xLights/assets/111211528/d536a14b-eb76-4a8b-9562-c4ddd476ac38)
The sequence is uploaded but not the media file/s.

This is not displayed as an error on Xlights .

I found this when I went outside to test the sequenes and a warning came up on the Pi that FPP could not find the media file/s

Attached is a copy of the logs from Xlights.and the FPP

**Comment by dartunder** [comment]
@murraygyde I don't see the attached files... is this a GitHub permission thing, or did you not attach them?

**Comment by cybercop23** [comment]
I don't think this is still an issue. If so, pleaase close.
