### ISSUE TITLE
Crash With Output to Lights On and Change Made on Layout Tab

### ISSUE THREAD

**Issue by TripleJ3EB** [xLightsSequencer/xLights#4086]
Windows, been a problem for last couple years for me, when we do testing of props, we are in a test layout, constantly changing out props and ports to verify props are wired correctly.  I would say that about 90% of the time, if you have output to lights enabled, and make a change in the Layout tab, it will crash xlights.  no error message, it just flat out disappears.  It would be greatly appreciated if you could warn or prevent making changes in layout when output to lights is enabled.

**Comment by derwin12** [comment]
Nothing in the logs? There are certainly some changes that cause a crash, if we can duplicate them the devs can track them down.
Any chance you can package logs and upload it?

**Comment by TripleJ3EB** [comment]
I copied the log file right after it disapeared on me.  Then another one after I relaunched xLights so you can tell exactly when it happend.

Forgot to shut the light bulb/output to lights off before I made a change in the layout, a conroller or port number of a model.

[xLights_l4cpp - After Relaunch After Crash.log](https://github.com/smeighan/xLights/files/13245712/xLights_l4cpp.-.After.Relaunch.After.Crash.log)

[xLights_l4cpp - Right After Crash.log](https://github.com/smeighan/xLights/files/13245713/xLights_l4cpp.-.Right.After.Crash.log)

**Comment by derwin12** [comment]
Nothing in the logs of value .. try to duplicate this so we can replicate in debug.
