### ISSUE TITLE
Test Screen - Don't Send Data to Unused Outputs

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#4109]
**Describe the bug**
The setting "Don't Send Data to Unused Outputs" doesn't work as expected on the Controllers tab.

When this setting is enabled and I have just one port selected no data is set to the controller.  Verified by looking at lights & input counters on the controller.  If I click on the controller as a whole then data is sent.

If I uncheck don't send data to unused channels so that all data is sent and only check a port on the controllers tab then only that port lights up.

The expected behavior is that when a range of channels is selected (port, model, pixels, etc) on any tab that channel range(s) will be sent to the controller(s).

Ron A also noted that on the Models tab this was behaving similarly.  If the whole model was selected then it output as expected but if only pixels were selected there was no output unless the don't send data was unchecked.

**To Reproduce**
1. Tools > Test
2. Enable "Don't send data to unused outputs"
3. Turn on just port X of a controller (In my case it was a Scott PB16 port 17)
    * Bottom left will indicate channels are being sent
    * The PB16 indicated no data is incoming
5. Disable "Don't send data to unused outputs"
    * Bottom left will indicate channels are being sent
    * The PB16 now indicates data is incoming
    * Only port 17 is being tested

**Versions (please complete the following information):**
* My Mac
    * OS: Mac Sonoma 14.1
    * xLights 2023.19
* Ron's PC
    * OS: Windows
    * xLights 2023.18

**Comment by cybercop23** [comment]
@derwin12 for your interest...

**Comment by derwin12** [comment]
If the first node is not selected, it assumes the output is not needed and data is not sent. Trying to see if I can figure that code out.

**Comment by derwin12** [comment]
..or if the last node is selected it sends the output. If you select stuff in the middle then no.
```
2024-02-08 15:55:34,444 19064 log_base [DEBUG] Selected channels dump:
2024-02-08 15:55:34,444 19064 log_base [DEBUG]    2401-2403
2024-02-08 15:55:34,461 19064 log_base [DEBUG] checking 1 to 4800
2024-02-08 15:55:34,461 19064 log_base [DEBUG] =====start=====
2024-02-08 15:55:34,461 19064 log_base [DEBUG] Start=1, End=4800 : s=2401, e=2403
2024-02-08 15:55:34,461 19064 log_base [DEBUG] SUSPEND TRUE
2024-02-08 15:55:58,482 19064 log_base [DEBUG] Selected channels dump:
2024-02-08 15:55:58,482 19064 log_base [DEBUG]    2401-2403
2024-02-08 15:55:58,482 19064 log_base [DEBUG]    4798-4800
2024-02-08 15:55:58,506 19064 log_base [DEBUG] checking 1 to 4800
2024-02-08 15:55:58,506 19064 log_base [DEBUG] =====start=====
2024-02-08 15:55:58,506 19064 log_base [DEBUG] Start=1, End=4800 : s=2401, e=2403
2024-02-08 15:55:58,506 19064 log_base [DEBUG] Start=1, End=4800 : s=4798, e=4800
2024-02-08 15:55:58,506 19064 log_base [DEBUG] Suspend FALSE
```
It sends the controller range rather than the output range to:
```
    bool AreAnyIncluded(long start, long end)
    {
        static log4cpp::Category& logger_base = log4cpp::Category::getInstance(std::string("log_base"));
        logger_base.debug("=====start=====");
        auto it = _ranges.begin();

        while (it != _ranges.end())
        {
            long s = GetStart(*it);
            long e = GetEnd(*it);

            logger_base.debug("Start=%ld, End=%ld : s=%ld, e=%ld", start, end, s, e); // dwe

	    if (start >= s && start <= e)
                return true;
            if (end >= s && end <= e)
                return true;

            ++it;
        }

        return false;
    }
```

**Comment by cybercop23** [comment]
#4326

**Comment by derwin12** [comment]
I believe this is merged in now.
