### ISSUE TITLE
Dummy "placeholders" causing an off by 1 channel color issue on Kulp K8-pi and SRx4

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4112]
From Zoom.
This might be more for awareness or to see if it can be duplicated.
FPP 7.2, 2023.16 with k8-Pi (raspberry pi not a bb)

Scenario:
SRx4 - v2 remote type, set to A on the receiver.
The goal was to put the tree across the middle of the SRx4 to distribute power.

Had Star on 13A
Had 8 Port Tree on 13B + C, 14B+C, 15B+C, 16B+C
When pushed to the controller it created DUMMY entries seemingly on every port.
They were set to 0 pixels

Testing from the outputs page, tools->test, display testing etc 
For Red a couple of strands would be Green. 
Swapping of ports/pixel strips made no difference .. the port was putting out Green

"Fix" was to place ANY prop on 14A, 15A, 16A.
Wanted to distribute power, so we didn't move the tree to A.

I didn't see anything in a recent release so we never tried a newer version of xlights or fpp.
If this is addressed already, feel free to close. If you cant duplicate it - we can chalk it up to dumb luck. :-)
Daryl

**Comment by computergeek1507** [comment]
Sounds like it could be a FPP bug

**Comment by bloojoop** [comment]
I copied this issue and added a few notes in fpp issue https://github.com/FalconChristmas/fpp/issues/1639
