### ISSUE TITLE
Moving Heads Offset Issue

### ISSUE THREAD

**Issue by jyshowalter** [xLightsSequencer/xLights#4113]
When importing a sequence (specifically I am seeing this with PPD sequences so far) and I use the offset adjustment when remapping DMX channels, I noticed that the moving heads in the render preview jitter. I haven't fired up my MH to confirm if it's just the preview. 

When alternatively adding an additive DMX effect to offset the pan/tilt channels, the jitter is gone. 

I'm happy to provide a sequence but it is a premium sequence from Pixel Pro Displays and their property, so I will share it privately if needed. 

I am using Windows 10, version 2023.19 xLights.

**Comment by cybercop23** [comment]
Can you just create a new sequnce and copy just one of the DMX effects and see if it happens, then post here?
