### ISSUE TITLE
Proxy Upload Setting is not persisted and fpp connect dialog does not close.

### ISSUE THREAD

**Issue by dartunder** [xLightsSequencer/xLights#4116]
@computergeek1507 

Regarding https://github.com/smeighan/xLights/commit/e86aa399a9587299d5091e7a6647ab04e82173b7 

I selected the checkbox for proxies and uploaded it successfully... (thanks for this feature I like it)
he FPP connect dialog did not automatically close like it does normally.  
As a result, the proxy upload setting was not persisted.

I think you need something like this... return (PostJSONToURL(...) != 200);

**Comment by dartunder** [comment]
I believe the API does not support the description field... some people will consider that a bug since their custom descriptions will be cleared.

**Comment by dartunder** [comment]
@ bool FPP::UploadControllerProxies should return true if a failure occurred
 not true for success to match other similar routines like UploadPlaylist

**Comment by dartunder** [comment]
The FPPconnect dialog not closing ( false error) is fixed!

If there are no new proxies then the descriptions are preserved.  If however I remove one from the list, then all the descriptions are cleared when the new one is added.

Add a description to a proxy, delete another, FPP connect to test this.

I believe the real fix is to update FPP, and this is a minor issue.  Just letting you know. Not an issue for me.

7.3.1 and compiled against this commit:
[use old FPP API for now to not remove descriptions](https://github.com/smeighan/xLights/commit/996e5a76711a788005cf7b789f989a251c064c29)

**Comment by derwin12** [comment]
Dart .. is this still an issue? Not clear from your comments.
