### ISSUE TITLE
Visualizer changes protocol if mismatched protocols assigned to same port 

### ISSUE THREAD

**Issue by Fonzi03** [xLightsSequencer/xLights#4117]
2023.19
I believe in a previous version (I'm remembering maybe November of 2019)

When you opened visualizer and had a protocol assigned to a port, it would not allow you to drop an incompatible protocol on the same bank of ports or gave an error/warning. 

The current behaviors is that it allows you to drop them on the port and changes their protocol. 

This behaviour is unexpected because now your protocol you assigned to that prop is changed and you may possibly have not realized you dropped it on an bank which would have caused that. 

I feel it would be best to warn/prevent the user from dropping incompatible protocols onto ports and not change the protocol of the last assigned string to match.

**Comment by cybercop23** [comment]
Assuming you are running on Windows... you can easily install (override or in a new place) an older version and try it. Then install and replace the latest one. If the behaviour is diff, please include screen shots or screen recording.

If no longer an issue, please close this.
