### ISSUE TITLE
Xlights freezes on Secondary Monitor

### ISSUE THREAD

**Issue by MovieDad** [xLightsSequencer/xLights#4120]
Unable to have Xlights 2023.19 default to the secondary monitor, with enough attempts when I do get it to open on the secondary it just freezes and stays not responding, until force close it. Windows 11 22H2. Primary monitor is 2560x1440, and secondary is 3840x2160.

**Comment by derwin12** [comment]
I believe this is a known issue with very high res screens.

**Comment by MovieDad** [comment]
Any workarounds then, or am I stuck making the 4K monitor the default in windows?

**Comment by computergeek1507** [comment]
Can you make a video and share more information about the display scaling settings in Windows

**Comment by AzGilrock** [comment]
So if you open it on the primary and drag it over to the secondary does it work?

**Comment by MovieDad** [comment]
after dragging it over then its frozen, not responding, waited up to 15 mins and have to force close.

**Comment by AzGilrock** [comment]
I've moved to a Mac but still have a Windows machine but its 10 and not 11.  Scott asked for some specs.  I'd open it on the primary and do a Tools -> Package Log Files and post that zip file here.

**Comment by MovieDad** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/13365983/xLightsProblem.zip)

**Comment by AzGilrock** [comment]
I'm not sure how they have the logs working these days but that only appears to contain log info for the latest startup of xLights so it probably doesn't include the previous startup where the lockup occurred.

**Comment by MovieDad** [comment]
I am forcing it to crash by dragging the screen over and sizing it manually from the right corner, it will crash once I get it big enough.

[xLights_dbgrpt-28540-20231117T215804.zip](https://github.com/smeighan/xLights/files/13400537/xLights_dbgrpt-28540-20231117T215804.zip)
[xLights_dbgrpt-10360-20231117T212129.zip](https://github.com/smeighan/xLights/files/13400538/xLights_dbgrpt-10360-20231117T212129.zip)
[xLights_dbgrpt-27212-20231117T212008.zip](https://github.com/smeighan/xLights/files/13400539/xLights_dbgrpt-27212-20231117T212008.zip)
[xLights_dbgrpt-5772-20231117T211858.zip](https://github.com/smeighan/xLights/files/13400540/xLights_dbgrpt-5772-20231117T211858.zip)

**Comment by cybercop23** [comment]
Is this still an issue? We've seen lots of folks in Zoom with 4k monitors and working without an issue.
