### ISSUE TITLE
xlights tools test not sending out all the channels to FPP 2023.19 v7.2 (or better?) (dedup)

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4122]
From Zoom and could duplicate.. 
Started off with the guy having Suppress Duplicate Frames on all his controllers.

When doing tools...test, all channels, the status on FPP didnt show the entire range being sent to FPP.
(My example)
![image](https://github.com/smeighan/xLights/assets/4643499/5b93e660-73db-47c2-b7d3-b56d1c004c2c)
After unsetting, (uploading controller, fpp connect) and verifying that outputs didnt have it set anymore. Tested again.
The status continued to not show the missing channel range - in his case it was the first 100K or so channels.

For my case it is not including the last couple controllers of channels.
![image](https://github.com/smeighan/xLights/assets/4643499/f1b5393c-37aa-4007-b39e-06f8ea0c52fd)

Can others duplicate? 
We had him restart xlights to get the full range back again (after clearing out the dedup settings)

**Comment by cybercop23** [comment]
@derwin12 I think this was fixed by @dkulp if I recall exactly. Can't easily find the commit.
