### ISSUE TITLE
FPP Connect

### ISSUE THREAD

**Issue by cathelest** [xLightsSequencer/xLights#4130]
Many thanks for adding parallel uploads into fpp connect,

At present though if your are uploading to multiple devices, it will still wait for the sequence to be uploaded to all of them before moving onto the next?

**Comment by cybercop23** [comment]
Correct. When it "proceses" the next sequence and send it. The processing of the FSEQ/sparse is still single threaded.
To separate it, it. will mean having to keep track of all of the upload sequences and sending to controllers for that FPP session. Doesn't seem likely to be done.

**Comment by cybercop23** [comment]
@dkulp is this doable and/or being considered? Shoudl this remain open?
