### ISSUE TITLE
Effect Preset - Option to turn off previews

### ISSUE THREAD

**Issue by jefft0825** [xLightsSequencer/xLights#4140]
The effect preset box severely slows down any sort of use of presets when it shows the preview of the effect.    Can we add a button to disable the preview?

**Comment by derwin12** [comment]
Thought .. can you rename/delete the presets directory then change the attributes on the presets preview folder to read only?
(not to say the devs could put in your request)

**Comment by cybercop23** [comment]
Avail in 2024.2. @jefft0825  please close.
