### ISSUE TITLE
Nested Folders

### ISSUE THREAD

**Issue by Jaa1i** [xLightsSequencer/xLights#4141]
**Is your feature request related to a problem? Please describe.**
When we have HD props, they come with a huge amount of Group folders, not just sub-models. This provides clutter both in the layout tab and the sequencing tab. Some of us also have a large number of Folders that we create ourselves.

**Describe the solution you'd like**
I'd love the ability to nest folders (not just submodels) under props. Also, the ability to nest folders within folders. For example, you could have a "All Group" folders, then have "All Verticals", "All House", "All Floods" nested within that base folder.

To be able to collapse large amounts of groups/folders whilst sequencing would be a very handy feature for those who sequence a section of their house at a time.

**Describe alternatives you've considered**
The alternate is the current state, which works, but is just more messy.

**Comment by AzGilrock** [comment]
There are no folders….there are only groups and I used the folder icon to represent a group.  You can already nest groups within groups so I don’t see anything your asking that doesn’t exist

**Comment by bobreese** [comment]
Placing Groups in Groups can (has been known to) cause issues with Rendering.

**Comment by Jaa1i** [comment]
> There are no folders….there are only groups and I used the folder icon to represent a group. You can already nest groups within groups so I don’t see anything your asking that doesn’t exist

Sorry, I referred to them as folders (they have a folder icon!). I'd like to nest Groups into a Prop. Just like submodels show in a prop when you select the arrow icon next to them, I'd like the Groups related to that prop to show there too, not at the top of my Models list. Some HD Models have a heap of Model Groups that I just don't need to see when working on my Layout or Sequencing, so having the ability to collapse them would be very handy.

**Comment by Jaa1i** [comment]
> Placing Groups in Groups can (has been known to) cause issues with Rendering.

Yeah, I've heard that. But this is something I'd love to see worked on and corrected.

**Comment by AzGilrock** [comment]
Groups within groups rendering works fine.  All because it was an issue in the past doesn’t mean it is today.  You do need to know what your doing with regards to the render buffer options you select.

**Comment by AzGilrock** [comment]
I don’t get what nesting groups within a prop means.  If you want the prop to show every group it’s a member of we are not going to do that to the model tree.

**Comment by Jaa1i** [comment]
> I don’t get what nesting groups within a prop means. If you want the prop to show every group it’s a member of we are not going to do that to the model tree.

The enhancement I am looking for is purely an organisational one. Instead of having all these Star Gazer groups at the top of the models list, why can't these be nested within the Star Gazer model and only be viewed when you expand the Star Gazer model (just like you see with Submodels)? It cleans up the Model list.

<img width="749" alt="Screenshot 2023-11-22 at 09 03 32" src="https://github.com/smeighan/xLights/assets/50488459/6e2762dc-45bf-4719-b9b6-510ff19a9df2">

Also, I understand you can have Groups within Groups, but again from a organisational perspective, I thought it would be good to have a parent group, for example called "All" and then within that Group have all the All groups such as "Whole House", "All Verticals", "All Floods" etc. So then unless you have expanded the "All" group, you won't see the other groups. As it stands, even if you have a Group within a Group, the child group will still be visible in the 'base' directory.

All of this is an attempt to clean up the Models tab to reduce the amount of clutter. Sorry if I'm not explaining it quite right :)

I'd also love this in the sequencing tab, but I understand this would come with a lot more challenges.

**Comment by AzGilrock** [comment]
So you could clean that up without any changes to xLights.  If you change the Preview a group is assigned to you could make it disappear from the list for the Default preview.  Just change it to Unassigned for the ones you don't want to see.  If you add them under another group you will still be able to access them from the default Preview.

Also I'm pretty sure those GE Star Gazer groups are collections of submodels that span all the Stargazer props you have so it doesn't really make sense for us to try to group them underneath any particular StarGazer model.

See how I've hidden "Group1" so that it only shows up under the "All" group?
<img width="417" alt="Screenshot 2023-11-21 at 4 06 14 PM" src="https://github.com/smeighan/xLights/assets/2024669/c1d5182d-cefe-4cdf-91eb-a9237ac75344">

**Comment by cybercop23** [comment]
Can this be closed? Seems like a workaround that lots of use use... Diff Preview. @Jaa1i if so, please close.

**Comment by Jaa1i** [comment]
As pointed out, there is a 'workaround' to one of the feature requests. I still think it is beneficial for it not to be a 'workaround' but just a standard feature.

It also does not address the feature request of nesting prop groups under the prop itself, just as submodels are nested under the prop, which I think would be very beneficial.

**Comment by AzGilrock** [comment]
There’s no way to make this work.  We can’t have a row on the sequencer that can’t accept effects.  We already have one that does and it’s called a group.
