### ISSUE TITLE
Shift palette colors

### ISSUE THREAD

**Issue by ClutchplateDude** [xLightsSequencer/xLights#4154]
Sometimes when I have a color palette selected but I want to insert a color at he beginning, I have to resort to putting it on the saved slot (sucks in Windows) and then get it back.

I'd like the ability to move the colors in the palette in either direction.

No alternatives come to mind

I have already implemented this and will submit PT for this.

**Comment by derwin12** [comment]
That is what this is for..
![image](https://github.com/smeighan/xLights/assets/4643499/972ccad0-b003-420b-8297-3e28229fd005)
![image](https://github.com/smeighan/xLights/assets/4643499/33ce51ff-b98a-492e-987b-87012464a3a9)

**Comment by ClutchplateDude** [comment]
No, that function reverses the palette. That's not what I need since many effects are sensitive to color order. I might have a color gradient setup in the first four slots, but want to add a white before it. Can't do that.

**Comment by derwin12** [comment]
ClutchplateDude - did you want to close this ticket?

**Comment by ClutchplateDude** [comment]
Oh, didn't realize it was still open. Closing.
