### ISSUE TITLE
effects copied in group to not align rows when pasted

### ISSUE THREAD

**Issue by mc-sketchy** [xLightsSequencer/xLights#4157]
**Describe the bug**
When copy and paste rows of sub-model effects (contained in a group), the rows pasted do not align with the rows copied. Some of the rows are pasted outside of the group completely, but it looks like xLights is trying to paste the rows into the order they appear in the prop setup, ignoring the order in the group setup.

**To Reproduce**
1. Create a group of sub-modes from a prop. Do not place the sub-models in the same order they appear in the prop
2. Add the group to the display elements of sequence
3. Open group
4. Create a timing divisions for each sub-model in the group. Do this twice, the first for copy and the second for past
5. Starting at the top of the sub-models, create on effects cascading down, with the effect in only one time division for each sub-model (see video)

**Expected behavior**
The rows of the pasted effects to align with those copied

**Screenshots**
Please see video

**Versions (please complete the following information):**
 - MacOS 14.0
 - xLights 2023.20

https://github.com/smeighan/xLights/assets/103663289/dcd81a60-10e8-4f27-8830-1f554902b4b7

**Comment by AzGilrock** [comment]
Your description sounds like the way it’s supposed to work.  The copy function has no idea where effects came from it pastes effects relative to the first effect on the topmost row you copied.

**Comment by AzGilrock** [comment]
Didn’t see the video at first.  Yeah that doesn’t look right.   Maybe someone screwed up copy paste thinking they were fixing something

**Comment by derwin12** [comment]
Cant duplicate. If this is still an issue, please do a tools->package logs so we can duplicate on your layout.
