### ISSUE TITLE
Xlights crashing when rendering sequence

### ISSUE THREAD

**Issue by danielpiet** [xLightsSequencer/xLights#4160]
Hi team,

I am new to this, so i hope this is the right way to do it.

I am currently experiencing my xlights to crash as i am rendering a sequence.

I have not tried to render all sequences yet, but the issue occurs when i open a saved sequence and then trying to render it. 

<img width="425" alt="Skærmbillede 2023-11-26 kl  14 53 09" src="https://github.com/smeighan/xLights/assets/152080047/b01e9902-c00c-4adf-bd0c-907a4f7ad9ec">
<img width="580" alt="Skærmbillede 2023-11-26 kl  14 53 21" src="https://github.com/smeighan/xLights/assets/152080047/1f8a8769-0b6c-4a44-b4ca-647e95d5eea7">

Video record of my screen can be downloaded from here: https://we.tl/t-3LL3BaW9Sq

I hope the screenshots and the video works.

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
On older macs finding that you can try disabling hardware decoding to see if that corrects the issue.
xlights->preferences, the "other tab". Check mark on the left side about hardware video decoding.

**Comment by danielpiet** [comment]
Thanks Daryl - it works now.

What am i missing out when unchecking the hardware video decoding funktion?

søn. 26. nov. 2023 kl. 20.24 skrev Daryl ***@***.***>:

**Comment by AzGilrock** [comment]
That option is supposed to help sequences render faster.  By unchecking it you are missing out on the crashes.

**Comment by cybercop23** [comment]
Can this be closed? If so, @danielpiet please close it.
