### ISSUE TITLE
Xlights keeps Crashing on Render All and Bulk render

### ISSUE THREAD

**Issue by RiverRaid** [xLightsSequencer/xLights#4163]
Hy there!

On my new PC, xlights crasheds very often on render, but there is one specific Sequence which i can't get to render, no mather what i do, the full Zip from the crashlog is attached. (Tried Proxy on/off, Hardware encoding on/off, New sequence and import the old one, clean up file locations, Bulk render, Windows Antiviros off)

System:
Windwows 11
Processor: Intel(R) Core(TM) i9-14900KF   3.20 GHz
Grafics: NVIDIA GeForce RTC 4080
64 GB of DDR 5 Ram
M2  SSD with 4 TB
Xlights 2023.20 64 Bit

Thank you

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-12616-20231127T132520.zip](https://github.com/smeighan/xLights/files/13474155/xLights_dbgrpt-12616-20231127T132520.zip)

**Comment by AzGilrock** [comment]
I would try to narrow it down to one effect.  Looks like its crashing in a parallel rendering thread.  If you delete half the effects see if it goes away then you know its in the other half.  Keep deleting half and should take long to narrow it down.

**Comment by RiverRaid** [comment]
@AzGilrock Thanks :) At the Moment I'm doing exactly this procedure and try to narrow it down :) Hopefully I'll finde the Problem. The interesting part of the story is that it works flawlessly on the other twinkly tree. But there seems to be a problem with twinkly anyway, because loading the model from the controller also crashes

**Comment by RiverRaid** [comment]
@AzGilrock Checking the Model did the Trick. There were a lot of empty Colums right to the last Pixel (about 200). I removed them and now its working, thank you!!

**Comment by AzGilrock** [comment]
Just curious why use Pebble lights?  I like using the heavy Boscoyo strip and pushing pixels into them.  This year I'm trying the EVO pixels.  They are so much lighter and by using the 2" spacing ones you can make strips that coil up so much better than bullet pixels.  As long as I end up liking the look of them they might be my new goto pixels.

**Comment by RiverRaid** [comment]
Because my neighbour doesn't want to build a "heavy" structure. With Pebbles its quite lightweight and easy , Pole hasn't to be that big etc.. I can't convine him to have a normal Mega  Tree. I tried to and then he bought the Twinklys. Maybe the Pebbles could be a good compromise :)

**Comment by cybercop23** [comment]
Can this be closed? If so @RiverRaid  please close it.
