### ISSUE TITLE
xSchedule Audio/Computer Sleep

### ISSUE THREAD

**Issue by Dubbs2022** [xLightsSequencer/xLights#4166]
Hi,

Issue 1: Audio cutting out, but show still playing
I am using xSchedule and usually it prevents my computer from going to sleep which is nice. However, since the last software update the audio cuts out even though the lights have not turned off. Meaning, while the computer doesn't fully go to sleep, the audio stops after a couple of minutes. 

Issue 2: App closing out when computer hybernates
I've changed my windows 11 setting to performance so the computer should never fall asleep but weirdly that isn't working (separate issue I'm sure). However, last night I opened xSchcedule and haven't touched my computer for 16hours. When I came to it today at around 5:45pm local time, my lights still were not on and when I woke my computer up xSchedule was closed. 

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment]
I really don’t think any of the xLights changes have changed xSchedule behavior.  Not sure there is anything we can do to alter the going to sleep issue.   I’m not familiar with Windows 11 but for earlier versions I just set my laptop to never goto sleep and to only blank the display.

Looking it up it’s not just the performance setting to disable sleep.

Click on the drop-down button associated with the “On battery power, put my device to sleep after” option and choose the Never option. Similarly, set the “When plugged in, put my device to sleep after” option to Never.

**Comment by cybercop23** [comment]
Can this be closed? If se @Dubbs2022  please close it.
