### ISSUE TITLE
New Timing Track FPP Command Functionality...

### ISSUE THREAD

**Issue by RiFF4711** [xLightsSequencer/xLights#4167]
To start, I'm loving the new FPP Command Functionality.  I'm using it to start and stop my TuneTo Matrix during songs.   I would like to be able to quickly add the FPP Command Timing Track to all of my sequences, however I understand I will need to open each sequence individually, then add a timing track.  I've done this to a sequence, then exported the timing track.   When importing the timing track to another sequence, the FPP Command Timing Track retains its name (FPP Commands), however it loses the special flag that it is an FPP Commands timing track and just becomes a standard timing track.  

**To Reproduce**
Open sequence.
Create FPP Commands timing track and add a some commands.
Export FPP Commands timing track.
Open new sequence.
Import FPP Commands timing track.

**Expected behavior**
Should import the FPP Commands timing track with the proper flag, rather than a normal timing track.

**Versions (please complete the following information):**
 - OS:  Windows 10
 - xLights version 2023.20

**Comment by cybercop23** [comment]
@derwin12 maybe of interest to fix? :)

**Comment by derwin12** [comment]
Noting the export does not contain the type .. Looking into the fix..

<?xml version="1.0" encoding="UTF-8"?>
<timings>
<timing name="FPP Commands_New" SourceVersion="2024.02.1">
   <EffectLayer>
      <Effect label="Start One" starttime="0" endtime="6450" />
      <Effect label="Start Two" starttime="6450" endtime="18400" />
      <Effect label="FPP Shutdown" starttime="18400" endtime="27150" />
   </EffectLayer>
</timing>
<timing name="Testone" SourceVersion="2024.02.1">
   <EffectLayer>
      <Effect label="One" starttime="0" endtime="4550" />
      <Effect label="Two" starttime="4550" endtime="19450" />
      <Effect label="Three" starttime="19450" endtime="29200" />
   </EffectLayer>
</timing>
</timings>
