### ISSUE TITLE
Controller/Layout edit panes freeze after only a single edit

### ISSUE THREAD

**Issue by Materdaddy** [xLightsSequencer/xLights#4175]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

I haven't even gotten to a sequence yet because setup is nearly impossible.

**Describe the bug**
The edit/configuration panes for layout/controller stop updating after a single edit to the entity requireing a restart of xLights to resolve.

**To Reproduce**
*In the Controllers tab*:
1. Add Ethernet controller
2. Click to edit something in the edit pane on the right
3. Edit the name
4. Clicking/scrolling in the edit pane results in no visual change to the pane
5. If clicking a region that has a text field, the cursor does change to the "line" indicating the pointer events are being handled, just not drawn.

*In the Layout tab*:
1. Select a model to edit
2. Change any setting (number of nodes, for example)
3. Clicking/scrolling results in no visual change.
4. Like the controller problem, clicking a text field does change the cursor indicating the pointer event is handled, just not drawn.

**Expected behavior**
Continued edits reflected and workable.

**Screenshots**
![image](https://github.com/smeighan/xLights/assets/127463/836d60b6-7f54-4854-9640-792db7d79783)
This is after changing nodes. I can click "Starting Location" but the image shown in the screenshot stays exactly the same. Even when clicking a different model to edit, or switching to/from the Controllers tab and back to the Layout tab. It seems this edit pane is dead until I restart xLights.

**Versions (please complete the following information):**
 - OS: Linux - Debian 11
 - xLights version 2023.21 64bit (wxWidgets 3.3.0)

**Additional context**
I installed the latest stable version from xlights.org on a windows laptop which seems to work fine, but it is 2023.20 as of the filing of this ticket. I suspect this is a linux problem though, not a version problem. I may spend some time bisecting the releases to see if this was a recent regression.

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
Is this still an issue with the latest version? If not.. can you please close it?

**Comment by Materdaddy** [comment]
This is still an issue with tip of tree. I'm trying to make time for a show this year, and looking to help get to the bottom of this issue.

**Comment by Materdaddy** [comment]
I've captured a screencast of the behavior: https://vimeo.com/1185389604?share=copy&fl=sv&fe=ci

This is a fresh build of tip of tree (with a quick ifdef bugfix for a libavcodec  version around an enum variable used in a switch/case statement) on debian 13. I've tried prompting gemini-cli with the bug to fix it, and it changed a bunch of things in LayoutPanel.cpp ModelPreview.cpp and xLightsApp.cpp but didn't fix anything. I reverted those changes before building and recording the screencast.

I'm a software engineer and can hopefully help triage but I don't know how xLights is architected, nor any experience with wxwidgets.

**Comment by Materdaddy** [comment]
In the screencast, it doesn't show what I was doing with the mouse so I'll try to describe it. I clicked the drop-down for `Controller`. Then I clicked the selection area for `Starting Location`. Next I was attempting to click any of the textbox entries (like Lights/Node) with no UI updates. After that I clicked another entry in the `Groups/Models List` which is reflected, but you can see the `Model Settings` pane doesn't update. When you see the spawning of "Blue Square" in the `Model Settings` pane, I was scrolling with the mouse (touchpad) over the `Model Settings` pane.
