### ISSUE TITLE
xSchedule / Remote Falcon Plug In Not starting with the show, or stopping at the end

### ISSUE THREAD

**Issue by JoelDearing** [xLightsSequencer/xLights#4176]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When xSchdule starts the show, the Remote Falcon plugin no longer starts, and when the show ends the plugin no longer stops.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to xSchedule, set up a playlist, enable the Remote Falcon plug in
2. Set up a RF background playlist
3. Associate the background playlist  with the show playlist
4. Watch the RF popup window, or check the associated web page.  The button needs to be hit to start or stop the plugin, it does not auto start or stop

**Expected behavior**
This has worked until a couple of days ago. James w/ RF says he did not write the RF plugin.  

**Versions (please complete the following information):**
 - OS: [Windows 10, 
  - xLights version 2023.13.  As mentioned above the plugin did work for several days into the new season, and appears to have broken 11.28??

**Additional context**
James w/ RF says he'd like to have the code so he couple work on it.

**Comment by computergeek1507** [comment]
The code is in GitHub anyone can work on it. It's just a pain to debug as you can't run it easily from visual studio

**Comment by keithsw1111** [comment]
It’s actually not that hard to debug. Just set up xschedule as the host executable and run it.

On 1 Dec 2023, at 11:11 am, Scott Hanson ***@***.***> wrote:

﻿

The code is in GitHub anyone can work on it. It's just a pain to debug as you can't run it easily from visual studio

**Comment by JoelDearing** [comment]
Thank you for the follow up.  I passed your notes onto James w/ RF via Facebook.  He posted a note yesterday on FB on the bug fixes and another user asked " Hey James, does #117 also apply to x schedule?" #117 is Added an additional check in Jukebox mode to also compare the requested sequence with the sequenced currently in the FPP Schedule table (used for up next)."   James' reply " if xSchedule updates RF to show the next sequence in the scheduled show, then yes."  The RF plugin appears to be pretty popular in xSchedule, is it possible to have it looked at by those who know it best, and address the growth changes that have happened?  TYIA.

**Comment by JoelDearing** [comment]
I have pinged James a few times, and he is saying "Nothing changed in the plugin API, at least in regards to the request/response structure."  Wjat else can I ask him that will get you what you need ?
