### ISSUE TITLE
Clean Up File Locations - Shader Duplication

### ISSUE THREAD

**Issue by brett-foy** [xLightsSequencer/xLights#4181]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you have a sequence that has shaders (and potentially other files) in many file locations and then use "Cleanup File Locations" from the tools menu, xLights makes many file copies of the same  shader name in the show folder shaders directory,and then updates every effect with a different file name.

**To Reproduce**

See video at https://youtu.be/fEpvxlk8aHc

**Expected behavior**
I would expect that if there were 19 effects using the same shader that is currently stored in a different file location, when the cleanup takes place, a single copy of the shader file would be created in the show folder shaders directory and all 19 effects would be updated to the same file name.

**Screenshots**
the short video should demonstrate the process

**Versions (please complete the following information):**
- WIndows 2011
 - xLights 2023.19

**Additional context**
Not a major issue, but definitely challenging for anyone with a lot of effects that have this issue.

**Attachments**
There was no crash.  I am not sure if the rgbeffects.xml / sequence file would be helpful as you can't recreate this without the entire folder structure of all files not located in show folder.

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
if you need any files, let me know, can provide.

**Comment by AzGilrock** [comment]
I'm hearing this is happening on imports now as well.  Trying to reproduce and I'm already seeing wacky stuff.  I got video files that don't seem to be rendering or playing at all even though the correct file is mapped.  I'm also not keen on how imports are storing my files now that I noticed what's going on.  When I import the sequence lets say "Trolls" into my "Christmas" folder I want ALL assets to go into "Christmas/Trolls".  I see where the folders can be changed but that looks like I need to go create every one of those subfolders.

**Comment by AzGilrock** [comment]
Ok well that last part wasn't as bad as I thought.  Didn't notice its actually creating subfolders under that Imported Media folder.  I was afraid they were all getting mixed together.

**Comment by AzGilrock** [comment]
Ok well the issues I'm seeing with the video effect are nothing to do with file locations.  I tried to use aliases and they seemed screwed up.  Its creating copies of all the effects on every strand of the model.  Like my megatree that used an alias during import ended up with 12 layers on all 32 strands with a copy of the effects on every strand.

**Comment by brett-foy** [comment]
Gil, did you see the video with the specific overview?  Potentially helpful

<https://youtu.be/fEpvxlk8aHc?si=RG0NikrOQDtjfFE7>
[maxresdefault.jpg]
see bug report 4181<https://youtu.be/fEpvxlk8aHc?si=RG0NikrOQDtjfFE7>
youtu.be<https://youtu.be/fEpvxlk8aHc?si=RG0NikrOQDtjfFE7>


Sent from my iPhone

On Dec 27, 2023, at 5:27 PM, Gil Jones ***@***.***> wrote:

﻿

Ok well the issues I'm seeing with the video effect are nothing to do with file locations. I tried to use aliases and they seemed screwed up. Its creating copies of all the effects on every strand of the model. Like my megatree that used an alias during import ended up with 12 layers on all 32 strands with a copy of the effects on every strand.
