### ISSUE TITLE
2023.21 - The last entry in a list box doesn't show

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#4188]
For items like views and submodels, it seems that the last item in the listbox control exists (usually) but doesn't show.  For instance, when creating a new submodel, the name of the new submodel doesn't show up, but you can still add pixels to the submodel details.  If you then try to create another submodel with the same name, the box goes red and you can't create it.  

Similarly, when trying to add items to a group, it seems like the last entry in the list box doesn't exist (whether it's a submodel or a full model).  If I filter for a submodel that I know exists, the box remains empty.

The same goes for views.  The first time I opened my views list in 2023.21, it seemed like my standard view (which shows up last in my list) was missing.  I imported it from a backup and I got <view name>_1, though I can't see the _1 version in the list box (confirmed it exists via the drop down in the sequencer and the XML itself).

Not sure if other list boxes are having the same issue or not as those are the ones I've come across so far.

Thanks!

**Comment by keithsw1111** [comment]
This works fine on windows.

**Comment by kevinsaucier** [comment]
Sorry, should have mentioned, this is on Windows (11).  I've attached my layout for your testing.  This is happening on 2 different layouts (though the 2nd is a copy of the 1st so.....)

You can see here, the view exists in the drop down but does not show in the Display Elements dialog.

![image](https://github.com/smeighan/xLights/assets/25715814/dcad1231-aa3f-4e69-a746-11611c6e1aef)



Similarly, you can see the 'All Wristbands' exists in the Sequencer props list, but not in the Display Elements dialog (though there appears to be a blank line there).

![image](https://github.com/smeighan/xLights/assets/25715814/43c9e3d9-37d7-4752-8acd-14096dc2d44a)



In submodels, you can see that S2-Handwritten is the last submodel.  

![image](https://github.com/smeighan/xLights/assets/25715814/8a2b2b68-53b6-4b84-bc56-4e73a8deaf25)


When I click Add and give the new submodel a name, I'm pretty sure it used to show up in the list on the left, but it's missing (maybe I'm misremembering how this works):

![image](https://github.com/smeighan/xLights/assets/25715814/3962edaa-7338-4005-8534-9091534d78b5)


But, when I click one of the other submodels, it enters 'Submodel-1' in the list instead of 'Test' and the range of pixels is gone.

![image](https://github.com/smeighan/xLights/assets/25715814/db9fe079-6c3f-42bf-a171-d9774b6a38e1)


If I then create a new 'Test', it shows it in red to indicate it already exists:

![image](https://github.com/smeighan/xLights/assets/25715814/de20d054-e52f-49b3-9610-b39ce35fdf14)


And, if I then click another submodel in the list, it enters the 'Test' submodel with the pixels I previously assigned to the first 'Test'

![image](https://github.com/smeighan/xLights/assets/25715814/ef7a8e63-7a5d-4e72-93b1-c76ff6b8ee0e)



[Christmas.zip](https://github.com/smeighan/xLights/files/13539901/Christmas.zip)

**Comment by derwin12** [comment]
Is this an issue with  font size set at the windows level? ie not 100%? Just a guess...

**Comment by kevinsaucier** [comment]
Not in front of the computer at the moment but I attached my layout with the pictures above.... Christmas.zip

**Comment by kevinsaucier** [comment]
Well, that's just frustrating.

I just uninstalled 2023.21 and reinstalled 2023.20 and the listbox are working again.

![image](https://github.com/smeighan/xLights/assets/25715814/689f13c0-c869-4bf3-a7d9-58fc28d08529)



I then upgraded to 2023.21 and tested again and the listbox is missing the last entry.  I then uninstalled 2023.21, ensured the registry was clear, and reinstalled 2023.21 as a clean install.  Same problem.

It's actually easier to test the issue looking at the model Cane - 1.  In the code, it has a submodel called 'Submodel-1' as the last entry.  In the UI for 2023.21, it's missing.  In 2023.20, it's there.

![image](https://github.com/smeighan/xLights/assets/25715814/a7aecea6-6f59-4a63-bacf-3ce7e58d6701)

![image](https://github.com/smeighan/xLights/assets/25715814/93826183-e755-439a-9910-b239996de640)


Just for fun, I pulled down this morning's nightly and tried it.  Same issue.  Definitely seems something has changed between 20 and 21.  Could it be a VC++ upgrade (I have quite a few version installed)?  Maybe something to do with dark mode (I see your test is not using dark mode)?

**Comment by kevinsaucier** [comment]
Also, here's the Package Logs output, in case it helps.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/13548565/xLightsProblem.zip)

**Comment by AzGilrock** [comment]
I don't have any input to help with this problem but I'm curious about how you made sure the registry was clear after an uninstall.  I didn't think the uninstall deletes the registry for xLights.  99% of the time an uninstall step is not going to fix anything.  What I do on the Windows side is I install every xLights version into a new directory with the version number in the name so I can go back and run old versions without uninstalling anything.

**Comment by kevinsaucier** [comment]
Unfortunately, the uninstall did completely wipe the registry (I wasn't expecting that), at least the main keys in HKCU.  After the uninstall, they all were gone and I was prompted to enter my email during the first opening of my layout.  Had to switch back to 3D as well.  Once I closed the app, it wrote a whole bunch of setting into the registry again.

![image](https://github.com/smeighan/xLights/assets/25715814/ecdbf300-aef5-423f-80f0-725fa49ca0a0)

**Comment by computergeek1507** [comment]
Can you disable dark mode and see if the issue occurs? wxWidgets renders some system components different in dark mode vs light mode. I found some windows composing bugs when debugging dark mode before.

**Comment by libby2cm** [comment]
@computergeek1507 It's definitely a dark mode rendering bug.. I opened #4199 last night with similar behavior with managing submodels.. and missed this issue already filed. Singleton list items seem to be what's tripping it up. Suppressing dark mode does seem to fix it. I missed the .22 release, so I upgraded to that and the issue persists.

**Comment by computergeek1507** [comment]
It's a wx issue
https://github.com/wxWidgets/wxWidgets/issues/24024

**Comment by cybercop23** [comment]
Looks like this is fixed....
https://github.com/wxWidgets/wxWidgets/commit/8c0d23ab65eb434d29fef2f266a437b924740b77

**Comment by cybercop23** [comment]
FWIW... made the change to my local win dev and discovered ctrls and I now see the 4 that are connected when using dark mode.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/625250ec-022e-410a-9a1d-2bd6d1e973bd)

**Comment by cybercop23** [comment]
Done, 2024.6

**Comment by kevinsaucier** [comment]
Praise the lord!  Thanks!
