### ISSUE TITLE
2023.21: Submodels broken on random props in Layout view

### ISSUE THREAD

**Issue by libby2cm** [xLightsSequencer/xLights#4199]
**Describe the bug**
In 2023.21 on windows, submodels on random models will not load in submodel dialog, or show up in group management. 

**To Reproduce**

1.) Upgrade to 2023.21
2.) Check if you can view/edit/add submodels for props that have them and manage their groups.
3.) Downgrade to 2023.20 and see it work

**Expected behavior**
The ability to manage submodels on a prop.

**Screenshots**

This image shows what's happening on .21.. prop selected & highlighted on preview, dialog open, but submodel is blank:
![xlsnap4](https://github.com/smeighan/xLights/assets/6451331/377f8a80-2c75-4e2e-9c2d-f9281688c459)

After downgrading to .20, it works as expected:
![xlsnap3](https://github.com/smeighan/xLights/assets/6451331/9d18fa2f-a4a5-4721-8e36-8d94b43249b8)

**Versions (please complete the following information):**
 - OS: Win11
 - xLights 2023.21

**Additional context**
I suspect this is related to the ongoing work for darkmode, since it seems to only be a UX rendering issue. Only some props are affected. When adding a new submodel on an affected prop, it will show up along with a duplicate in submodel list, and the original one, but behavior of saving is unpredictable. The XML is correct and rendering still works fine against impacted props, so just seems to be UX issue.

**Comment by derwin12** [comment]
You mention dark mode .. can you go to preferences and override the dark mode to see if the value shows?

**Comment by libby2cm** [comment]
Ah, yes, if I disable dark mode it seems fine. I forgot .22 was out, so I upgraded to it, but the dark mode bug is still there too. Forgot to mention, In the submodel window for example, if I click in the blank spot right under the 'submodel' header column, the submodel config and name show up even though nothing is shown in submodels table. Though if I move mouse around I see the model name flicker briefly.

**Comment by cybercop23** [comment]
Done, 2024.6
