### ISSUE TITLE
Convert Effects to 'Per Model' minor bug

### ISSUE THREAD

**Issue by Arcxk** [xLightsSequencer/xLights#4202]
**Describe the bug**
After using the 'Convert Effects to 'Per Model' ' context menu option for the Row or Model submenu in the sequencer, the event to trigger an immediate render of that change does not get fired. However, simply selecting an effect on of the affected rows/models triggers a re-render. This means a user either has to individually select each effect on a row/model or manually trigger a "render all".

**To Reproduce**
1. Have a sequencer row with effect that contain non "per model" render styles
2. right click on the sequencer row
3. highlight "model" or "row" submenu
4. select "Convert Effects to 'Per Model'"
5. preview the effects either via the "play" button in the top menu, or by clicking on the timeline at the top of the sequencer rows
6. effects are still displaying as if they were not converted to "per model"

**Expected behavior**
Selecting one or more effects on a row or model, then changing the render style via the standard combo selection or the "Bulk Edit" method, triggers a render update for those effects; which are then reflected in the Model Preview and House Preview windows after the render has completed. I would expect the "Convert Effects to 'Per Model'" context menu option to exhibit this same behavior. However, the render does not fire unless manually triggering a "render all" or selecting each of the effects to trigger a render.

OS: Windows 10
xLights version: 2023.20

**Comment by AzGilrock** [comment]
So I'm looking at the code and we have tons of operations that do not trigger a render.  Like all the functions that move a group of selected effects I don't believe trigger a render for those effects unless its buried somewhere I'm not seeing.  So I'm not sure we're always guaranteed that effects are always rendered and up to date unless you do a Render All
