### ISSUE TITLE
Linux Appimage - All windows in layout and sequencer tab blank

### ISSUE THREAD

**Issue by AverageWaffleHouseEnjoyer** [xLightsSequencer/xLights#4208]
**Describe the bug**
On the latest linux appimage available 2023.21, most of my windows are missing. It is blank for the house preview in the layout tab, model and house preview in the sequencer tab, and the timeline in the sequencer. Version 2023.18 works as intended. The only clue I have is that running from the terminal shows the following when switching between tabs with broken windows.

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Screenshots:
2023.21 the left, 2023.18 on the right

Sequence is open in both windows
![Screenshot_20231209_055219](https://github.com/smeighan/xLights/assets/134578419/4261b54b-a73d-4694-abad-011ff646bc4a)
![Screenshot_20231209_054927](https://github.com/smeighan/xLights/assets/134578419/fc46594c-dd43-4000-97e8-20b52660e50d)

**Versions (please complete the following information):**
 - OS: Arch Linux
 - xLights 2023.21

**Comment by isrjo** [comment]
Same on Opensuse

**Comment by AverageWaffleHouseEnjoyer** [comment]
@isrjo Are you on tumbleweed or stable version of Opensuse? This issue doesn’t happen on Debian, but still happens on both of my Arch computers. If you are on tumbleweed, then the common denominator is being on rolling release. Still unsure why 2023.18 specifically is the last usable version.

**Comment by derwin12** [comment]
Should be correct in .5
