### ISSUE TITLE
Servo Timing Track Empty

### ISSUE THREAD

**Issue by McCoyCOREUSA** [xLightsSequencer/xLights#4211]
v2023.22

Servo effect has a timing track checkbox, but when checked the drop-down for timing tracks is empty.

Is this a bug, or is there a step I'm missing for this effect?
![2023-12-09_16-23-32](https://github.com/smeighan/xLights/assets/104024793/43e76823-a2ff-4a9d-8790-1918beb3225d)

**Comment by computergeek1507** [comment]
Is it on a group? Try selecting another effect then select it again

**Comment by McCoyCOREUSA** [comment]
Not a group. Even tried a new sequence and created a little timing track. I tried several things and never get the timing tracks in the drop-down field.
![2023-12-09_18-08-53](https://github.com/smeighan/xLights/assets/104024793/a1743b0d-44c7-49f0-8050-7cae561a31fc)

**Comment by AzGilrock** [comment]
That only works for singing face timing tracks

**Comment by AzGilrock** [comment]
The Servo effect uses phoneme's to create the movement.  A normal timing track doesn't have anything to trigger the motion.
