### ISSUE TITLE
Alias for sub-models

### ISSUE THREAD

**Issue by cybercop23** [xLightsSequencer/xLights#4214]
I know... I know... I know.. you guys give us a centimeter and we take a meter.

Aliases are SO COOL. Can we pretty please get the same for submodels? With all of the HD props from EFL/SS, GE and the likes having 80+ submodels, it will be extremely easy to just alias submodels and not have to create that many groups.

Did I mention how awesome aliases are???

**Comment by AzGilrock** [comment]
Requests made in metric are automatically denied

**Comment by derwin12** [comment]
And perhaps throw in the model name into the alias when you download a model. So if the user changes the name, the original name is retained.

**Comment by cybercop23** [comment]
I think it does that when you rename a model - it will ask you if you want to save the old name as an alias

**Comment by AzGilrock** [comment]
I didn't get to fully review how alias' were implemented but model names needed to be unique so I hope that is also enforced with alias'.  I'd hate to see the big mess that will occur if we end up with multiple models having the same alias names and then someone will add a popup dialog to choose which one you want.  I can see this turning into a management nightmare.

**Comment by cybercop23** [comment]
For the AutoMap option in Import Effects, many to 1 is what we would expect. Map original foo model to bar and baz in my layout. Both bar & baz would have the same alias.

**Comment by keithsw1111** [comment]
How exactly would you see this working? Adding aliases is not that difficult but how would they be used on submodels.

**Comment by kevinsaucier** [comment]
> How exactly would you see this working? Adding aliases is not that difficult but how would they be used on submodels.

Do you mean the actual use case?  I frequently see OEM HD models with mispelled or misnamed submodels.  Or just names that make no sense.  For instance, I have a fan that has both large and small diamond submodels....the submodels are named (All Diamonds, Diamond 1, Diamond 2, Diamond 3, All Large Diamonds, Large Diamond 1, Large Diamond 2, Large Diamond 3).  Have something named Diamond is confusing when it actually means 'Small' Diamond and makes it hard to know what you're mapping to.  Changing those names, however, means that imports will no longer automap and become very tedious, especially when you have 20 of a shape (feathers, small feathers, etc. on the Rosa Grande).

**Comment by cybercop23** [comment]
This is a relatively simple example and can get very complex with the other high density props that have 80+ groups... but the idea is to have Aliases at the submodel level that when doing the mapping it will auto map, like below.
So Balls would have an Aliases as Floods, Floods Grp and 02.14.0Grp FLOODS
So when I auto map, it will take from those aliases and map at the submodel level SpiralX1\Balls <- Floods

![image](https://github.com/smeighan/xLights/assets/23619433/273ffae3-9d50-4324-9a3c-72336247c176)


There's also this "master" document suggesting how to map between diffferent HD sub-models. If we had the ability to add aliases at the submodel level, then we can use automap.

![image](https://github.com/smeighan/xLights/assets/23619433/38c23d9e-5e15-446f-b638-c266a6b01c38)

**Comment by cbennett6008** [comment]
You can create import mappings that would translate effects from one to another, that seems to me like it would allow you flexibility in the occasion that you wanted to import Rosa Grande, onto your Showstopper Flake, or heaven forbid you actually got one of the props you had been aliasing from. :)

**Comment by cybercop23** [comment]
That's exactly what the mapping at the submodel level would do. So you know that to go though import mappings and have it all right there configured in your layout.

**Comment by kevinsaucier** [comment]
Since Keith said it's pretty easy to implement aliases on submodels and all.....  😁  Just wanted to upvote this one again, as I'm now coming across the exact use case as cbennett mentioned.  I am replacing my Rosa Grande and it's 50 submodels with a Showstopper Flake and a Showstopper Spinner (each with their own 50 submodels) and it would be handy to simply define those aliases and have them carry over.  Even nicer if there were a GUI for mapping submodels from one prop into an alias on another (so I don't have to copy/paste them) or even importing a mapping file, since that GUI already exists.  

I'm also finding as I go that it would be handy to have other props mapped out to these submodels (various Gilbert/Boscoyo HD props with 50 submodels) mapped over to the SS HD props' submodels.  I know I can partially do this with the import mapping files during import but they sometimes conflict and can make a mess so I'd end up having to import one at a time.
