### ISSUE TITLE
Opening old fseq file and Lights keep crashing

### ISSUE THREAD

**Issue by gpower25** [xLightsSequencer/xLights#4221]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am trying to open an old FSEQ file but Xlights crashes immediately after. The media file is in the same folder as the FSEQ file. I even moved it to the render cache folder after reading the bug report. However, nothing seems to work.
[xLights_dbgrpt-57177-20231215T223508.zip](https://github.com/smeighan/xLights/files/13691618/xLights_dbgrpt-57177-20231215T223508.zip)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by gpower25** [comment]
Tried to attach FSEQ file, but it says that it is not supported

**Comment by derwin12** [comment]
You don't normally open an fseq file, did you mean .xsql or .xml ??

**Comment by AzGilrock** [comment]
We used to try to support someone trying to open an FSEQ file by looking for the associated XML file with the same name.  We should probably delete that mess if it’s still in there.  So yeah FSEQ is just data it does not contain any of the effects mapped to the models.

**Comment by gpower25** [comment]
Thank you so much for the quick response. I truly appreciate it.

I am trying to recover my old files ( I had created some really elaborate sequences) and found a few fseq files. So given that I did create those sequences last year, was trying to see if I can open. The manual also references the same. ![image](https://github.com/smeighan/xLights/assets/10324555/9e19920b-8d30-4e41-9467-c8243a284f26)

So, the best practice here is to find the xseq file and try to open that instead of the fseq?

Thank you.

**Comment by AzGilrock** [comment]
Devs don’t read or write the manual that’s done by volunteers.   If you had the sequence file in the same folder it should have opened that.  You may be crashing for another reason.  All you can do with an FSEQ file is put it in a show player as long as it matches your old channel layout.   Like I said we should remove any reference of opening FSEQ files cause it just confuses folks

**Comment by derwin12** [comment]
It is coded to support it .. Can you perhaps zip the .fseq file and upload that? I tried to duplicate the issue but wasnt able to.
(Obviously? it wont be able to do anything with an fseq file but load in the corresponding .xsq but it shouldnt crash)

![image](https://github.com/xLightsSequencer/xLights/assets/4643499/6b71dd01-a5c5-44c1-a8bb-182df2f796e4)

**Comment by AzGilrock** [comment]
Yep I want to talk to the guys about deleting that option.  It just adds confusion and complexity and I don't see a practical purpose to allowing it.

**Comment by computergeek1507** [comment]
delete it

**Comment by derwin12** [comment]
> Yep I want to talk to the guys about deleting that option. It just adds confusion and complexity and I don't see a practical purpose to allowing it.

Looking at the code .. it would be (somewhat) helpful for folks that keep all their fseq files in one folder, but the sequences are in another. So you click on the .fseq folder in the fseq_folder, and it goes out and gets the corresponding .xsq. Whether anyone actually does this is another question :-)

**Comment by AzGilrock** [comment]
The FSEQ And XML file used to be in the same folder when we first implemented that feature.  I don't think we want xLights searching around to try to find the XSQ file that might go with the FSEQ someone clicks on.

**Comment by derwin12** [comment]
This seems to still work.. so I assume it has something to do with the .fseq that was being loaded.
If you want to package the sequence (tools->package sequence) we can take another look.
