### ISSUE TITLE
Bulk Edit DMX Effects - change value from Static to Value Curve only updates last effect selected

### ISSUE THREAD

**Issue by chrkov** [xLightsSequencer/xLights#4222]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Only seems to affect DMX effect from what I tested.   Current effects only has a value of 0 set on it.   If I select multiple DMX effects, right click on a channel (tilt for example) and select Bulk Edit.  Then I select Value Curve and setup whatever.   When I finish, the value curve is only applied to the last effect I selected.   The others remain unchanged.   Same goes if there is a Value Curve already applied and I remove the Value Curve and set the channel value to just a static value.   It will remove the Value Curve from only the last object selected.
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1.  Create multiple DMX objects
2. Select objects by holding CTRL and left clicking all the DMX effects you want to change.
3. Right click on a channel and select Bulk Edit
4. Click on the Value Curve option
5. Setup Value Curve and click OK
6. Click OK on the Bulk Edit window
7.  Check individual DMX effects to see that only the last one selected was changed.

**Expected behavior**
All selected DMX effects should be updated.

**Screenshots**
Here is a video link to show the issue.
https://youtu.be/E8YpJnihT88

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2023.22

**Additional context**
Seems to work fine on other effects.  Did the same thing on Single Strand and it updated all the selected effects.

**Comment by AzGilrock** [comment]
Try again.  I just tested and it seems to be working.

**Comment by derwin12** [comment]
Agreed it is working .. note that it does leave the prior value in the box, but it is disabled and the VC is enabled.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/f4e2074c-e9eb-43a5-a41c-1d523e53d868)
