### ISSUE TITLE
Automap using an alias created during a rename maps to all submodels as well.

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#4224]
I just ran across this one and pretty sure it's a bug.  I renamed my matrix from 'Matrix-L' to 'Matrix - Windows - Left' .  I then imported effects from a previous year's sequence and used AutoMap.  'Matrix-L' was successfully associated to the new name, but I didn't notice the submodels were also mapped to 'Matrix-L' (it didn't expand the model in the mapping dialog, like I think it usually does).  

![image](https://github.com/smeighan/xLights/assets/25715814/685bee1d-0371-4e6f-ad3e-45d24ca2af01)

Aliases: 

![image](https://github.com/smeighan/xLights/assets/25715814/e8518a8c-62e2-47e8-a700-76a17ba998e6)

Took me longer than I'd care to admit to figure out WTF was going on here......  🤦‍♂️

![image](https://github.com/smeighan/xLights/assets/25715814/d2a84742-64b4-4048-890c-01f36a1a1341)

Exported test sequence attached.  

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/13693679/xLightsProblem.zip)

**Comment by AzGilrock** [comment]
I'd just like to comment about the expanding of submodels when you map a model.  Who the fuck thought that was a good idea?  It pisses me off having to collapse it every damn model I drag over.  Only way to prevent it is a double-click to map.

**Comment by derwin12** [comment]
> I'd just like to comment about the expanding of submodels when you map a model. Who the fuck thought that was a good idea? It pisses me off having to collapse it every damn model I drag over. Only way to prevent it is a double-click to map.

Doesn't do it for me... just drag and drop ..

**Comment by AzGilrock** [comment]
> > I'd just like to comment about the expanding of submodels when you map a model. Who the fuck thought that was a good idea? It pisses me off having to collapse it every damn model I drag over. Only way to prevent it is a double-click to map.
> 
> Doesn't do it for me... just drag and drop ..

So either you aren't dropping on a model that has submodels or it must be a Mac vs Windows thing.   In this video you can see it expands the model to reveal the submodels on every drop.  It also will expand the submodels if you hover the drop.  Then the last action I did was a double-click and you can see it doesn't expand.  I think the operation should be the same whether I double-click or drag-drop.
https://www.youtube.com/watch?v=1qsi3H8vnCw

**Comment by derwin12** [comment]
> > > I'd just like to comment about the expanding of submodels when you map a model. Who the fuck thought that was a good idea? It pisses me off having to collapse it every damn model I drag over. Only way to prevent it is a double-click to map.
> > 
> > 
> > Doesn't do it for me... just drag and drop ..
> 
> So either you aren't dropping on a model that has submodels or it must be a Mac vs Windows thing. In this video you can see it expands the model to reveal the submodels on every drop. It also will expand the submodels if you hover the drop. Then the last action I did was a double-click and you can see it doesn't expand. I think the operation should be the same whether I double-click or drag-drop. https://www.youtube.com/watch?v=1qsi3H8vnCw

A mac thing .. almost looks like it is doing you a favour whether you like it or not and double clicking when you hover over it.
.. not seen in windows

**Comment by cybercop23** [comment]
Yup... same there on a Mac. I have this #3752 to make it easier to manage, but didn't know it was really just a mac thing. Still think it will be good to have the same expand/collapse all option.

**Comment by AzGilrock** [comment]
So I just tried to use an alias and ran into this on import.  For my case I created an alias of "Mega Tree" for my "Pixel Tree" model.  After import the "Pixel Tree" didn't look right and I discovered every strand now had 12 layers and full copies of all the effects that were supposed to be at the model level.

**Comment by derwin12** [comment]
I think Alex has addressed this.
