### ISSUE TITLE
Aliases don't seem to cover submodels of an aliased model

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#4231]
I had a model called Matrix-TuneTo .  It had 2 submodels, TopHalf and BottomHalf.  I renamed Matrix-TuneTo to Matrix-Mini and allowed Matrix-TuneTo to be added to the list of aliases for the model.

When I AutoMap a sequence from last year, Matrix-TuneTo is mapped to Matrix-Mini but Matrix-TuneTo\TopHalf and Matrix-TuneTo\BottomHalf remain unmapped.  Expanding Matrix-Mini shows TopHalf and BottomHalf exist, but they are not automapped.

Expected behavior:  Submodels of an alias model would be mapped to the newly named model during the AutoMap function.

**Comment by kevinsaucier** [comment]
Just realized this is probably due to #4224 as the top level model is being mapped to ALL of the submodels/strands, which gets in the way of mapping the imported submodels to the aliased submodel.  If that makes sense, please go ahead and close it.  Leaving it open for now, just in case this is an additional issue.

**Comment by cybercop23** [comment]
#4365 Duplicate... developing under the other issue
