### ISSUE TITLE
Xlights crashing after updating Mac to 14.2.1 

### ISSUE THREAD

**Issue by csmithten** [xLightsSequencer/xLights#4232]
[Error Crashes after 14.2.1 Mac update.docx](https://github.com/smeighan/xLights/files/13734115/Error.Crashes.after.14.2.1.Mac.update.docx)

[Error Crashes after 14.2.1 Mac update.docx](https://github.com/smeighan/xLights/files/13734123/Error.Crashes.after.14.2.1.Mac.update.docx)

I am not sure if the Mac Update is the problem - just updated 20Dec23.   It seems to hang during an FPP Connect and crashes afterwards.

**Comment by csmithten** [comment]
I had to reinstall Xlights

**Comment by cybercop23** [comment]
@csmithten is this still an issue?
