### ISSUE TITLE
MacOS M1 Sonoma 14.2.1 (23C71) version does not display house model after save/render unless you select a model. Makes it impossible to visualize

### ISSUE THREAD

**Issue by rsriedel** [xLightsSequencer/xLights#4239]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by rsriedel** [comment]
[xLights_dbgrpt-32170-20231225T060712.zip](https://github.com/smeighan/xLights/files/13781566/xLights_dbgrpt-32170-20231225T060712.zip)

**Comment by rsriedel** [comment]
Crashes a lot too.  attached.

**Comment by cybercop23** [comment]
Is this still an issue? I'm running 2024.2 on 14.3 w/o issues. If okay, please close. If you need more assistance hop in the zoom room, xLights -> Help -> Zoom.

**Comment by rsriedel** [comment]
Hi Alex,

Sorry the late reply.  It appears to work now in the latest release.

Thanks,

Rick
