### ISSUE TITLE
bookworm

### ISSUE THREAD

**Issue by pipppy1** [xLightsSequencer/xLights#4241]
please can we build this on bookworm
with thanks

**Comment by computergeek1507** [comment]
Build the appimg? It should work with newer versions

**Comment by pipppy1** [comment]
haha
dont know how to use or install it

**Comment by pipppy1** [comment]
I can now build it on bookworm but when I run it I get the error "linux-vdso.so.1`: No such file"
please can anyone help

**Comment by AzGilrock** [comment]
No idea what bookworm is nor do I build app images so I’m out.  When you dive into Linux you need to become the expert.

**Comment by pipppy1** [comment]
Manage to get the thing built on raspberry pi 5 in the  end . Thanks all

**Comment by cybercop23** [comment]
It will be nice to include here the steps/process you used in case others come and look for it. But at the least, please close this if you got what you needed.

**Comment by cybercop23** [comment]
@pipppy1 please close this issue.
