### ISSUE TITLE
Crash when rendering pinwheel

### ISSUE THREAD

**Issue by sslupsky** [xLightsSequencer/xLights#4242]
**Describe the bug**
2023.23 on macOS 13.6 crashes when rendering a pinwheel in the attached sequence.  If GPU Rendering is disabled in Preferences, the pinwheel renders without crashing xlights.

[Top Of The World - The Carpenters.xsq.zip](https://github.com/xLightsSequencer/xLights/files/13800299/Top.Of.The.World.-.The.Carpenters.xsq.zip)

**Comment by derwin12** [comment]
Dan put in a fix for pinwheel with more than 8 arms - is that the case here?

**Comment by sslupsky** [comment]
Yes, the pinwheel effects have 10 arms.  Will keep an eye out for the next release.  Thank you.
