### ISSUE TITLE
Layout Objects Not Visible in 3D - Debian 12 with OpenGL 4.6  Mesa 22.3.6

### ISSUE THREAD

**Issue by davestuckman** [xLightsSequencer/xLights#4253]
Installed xlights on Debian 12 on older Dell laptop and xLights 3D layout works as expected
Installed xLights  on Debian 12 on two older HP laptops and in xLights 3D layout objects are not visible once added

Have tried xLights-2023.21-x86_64.AppImage and xLights-2023.23-x86_64.AppImage
"Working" laptop:  OpenGL version string: 4.2 (Compatibility Profile) Mesa 22.3.6
"Non-working" laptops :OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.6

I don't know for sure that OpenGL is an issue, but it is a difference between my installations.  Under File/Preferences/View there are no options to select OpenGL version on Debian.  Web searching on changing openGL / video drivers  on Debian doesn't lead anywhere. 

![image](https://github.com/xLightsSequencer/xLights/assets/155848736/ce8fda88-1436-480f-86cf-e13a6c717a5f)

**Comment by AzGilrock** [comment]
Missing objects like that have always been solved by a driver change.  Whenever you use the word “older laptop” it’s usually an issue.  Just based on all the past similar issues you’re going to need to solve this yourself.  Newer laptop or find a batter driver.  Plus running on Linux is the least supported option.  I don’t know any primary developers that use Linux.

**Comment by isrjo** [comment]
When I ran into this issue I changed the Pixel Style from "smooth" to "Square" (under Appearance) on the each model and that made them reappear in the layout. 

HTH
Jonas

**Comment by davestuckman** [comment]
@isrjo  thank you very much.  That was a quick easy change that worked!
