### ISSUE TITLE
Check for updates not working in 2023.20

### ISSUE THREAD

**Issue by tmeyermn** [xLightsSequencer/xLights#4271]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I haven't been getting update notifications when starting 2023.20.  When I manually check for updates it doesn't find updates either.  The current version available for download is 2023.23 and I am able to manually download and install that version.  Since nobody seems to be talking about it and I don't see a bug report here I'm thinking it may just be a localized problem due to hopping around between versions (forward and back).

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Start up version 2023.20
2. No notification about 2023.23
3. Click on Help->Check for Updates
4. No update found dialog appears.

**Expected behavior**
It should detect 2023.23

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10 (two different machines)
 - xLights version 2023.20

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
It's because the website is broken, may change this in the future

**Comment by tmeyermn** [comment]
Ah, thanks!  Thought for sure it was me switching between versions :)

**Comment by cybercop23** [comment]
Website has been fixed and update notifications are working again. Can this be closed?

**Comment by tmeyermn** [comment]
Yes thank you!On Jan 28, 2024, at 12:14 AM, AlexB ***@***.***> wrote:﻿
Website has been fixed and update notifications are working again. Can this be closed?

**Comment by cybercop23** [comment]
I can't do it myself. Either an admin or you can since you opened it.  Thanks.
