### ISSUE TITLE
xlDo UpLoadSequence

### ISSUE THREAD

**Issue by morrydavis** [xLightsSequencer/xLights#4273]
if media option is set to true it uploads fseq file fine but then fails to find FPP setver when trying to upload media

**Comment by derwin12** [comment]
More details please ... perhaps your xldo script?

**Comment by morrydavis** [comment]
Found this is not related to media option it some time works and sometimes does not doing batch job it tends to fail more often first one typically work second one nearly always fails

**Comment by morrydavis** [comment]
FYI running FPP 7.4
