### ISSUE TITLE
Default order of models for Import Effects

### ISSUE THREAD

**Issue by cybercop23** [xLightsSequencer/xLights#4278]
Currently the map To (left) and map From (right) model lists are alphabetically sorted. This casues an issue especially with some of the newer HD props that have a lot of submodels and are "organized" by area, since it looses the original intent to keep submodels together. (see below)

From extended disussions in the Zoom room, skipping the initial sort of the model lists and keeping the master view display (or forcing master views local and sequence) will be preferrred. The user will still have the ability to click on the column names and sort asc/desc just like you can now.

Alternatively have an option to choose the sorting, including the ability not to sort submodels, so the heavy HD submodels will not loose its organization.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/4dbc94f5-68b4-4824-9c70-16c0bfcf53b9)

@derwin12 per out discussion...

**Comment by computergeek1507** [comment]
i think someone already made an issue for this

**Comment by cybercop23** [comment]
It was me but had the expand/compress all models to make it easier to map/navigate. This can replace that.
