### ISSUE TITLE
(Gil) New Moving Head - the actual head disappeared, is that expected?

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4283]
Just started up the moving_head_adv branch and the first thing I noticed was my heads are not showing in the house preview.
Is that expected? Something I need to tweak in the properties?

(Is there a better place for this discussion)

**Comment by AzGilrock** [comment]
It’s probably not finding the mesh objects,,,,normally an install would locate them to the meshobjects folder…since your not doing an install you need to put the assets there manually I think.

**Comment by AzGilrock** [comment]
They should be in the branch under meshobjects….look for SimpleMovingHead

**Comment by derwin12** [comment]
Ok .. will check that out .. I also see there is a nove DMX fixture .. so perhaps I need to drop that in? DMX Head Adv
Oh wow .. there is a big setup for the actual head - I will give this whirl.

**Comment by AzGilrock** [comment]
Yeah I need to do a tutorial video.  So when you said the head didn’t show I assumed it was the new model.   Are you saying you used the new effect on the old model and the head disappeared?   I might need to test that.

**Comment by AzGilrock** [comment]
But our intent is to delete the old model and upgrade it to the new one we just haven’t added the code to do the update automatically yet

**Comment by derwin12** [comment]
Is there a sample yoke obj/mtl file?

**Comment by AzGilrock** [comment]
Easiest way the get the Mesh objects is do a Download Model operation like your grabbing a file from Boscoyo or other vendor.  Scroll to the bottom and you will find the DMX objects I added a few years ago.  Under one section look for SimpleMovingHead and it has the mesh OBJ's I've been using.

**Comment by AzGilrock** [comment]
Are you doing the nightly install or building your own?  If the nightly install is not putting the object files in place I'll need to work on that.

**Comment by derwin12** [comment]
I have done both .. I dont think the obj files are in place in the source code. The ones on your video and blinky (?) video are not in the branch.
Also a minor glitch.. the pathing window isnt cleared/hidden when you go to color.

![image](https://github.com/xLightsSequencer/xLights/assets/4643499/0593d1f9-7845-46be-9ffa-734f633aaa3f)

**Comment by derwin12** [comment]
> Easiest way the get the Mesh objects is do a Download Model operation like your grabbing a file from Boscoyo or other vendor. Scroll to the bottom and you will find the DMX objects I added a few years ago. Under one section look for SimpleMovingHead and it has the mesh OBJ's I've been using.

Ok .. checking here.. thanks.

**Comment by AzGilrock** [comment]
Wow you're the only one I've seen get the color wheel to draw on Windows.  Its blank on mine.  That Path grid showing through is a Windows Only glitch.  There should be no "clearing" necessary its a completely different tab.  So its a wxWidgets bug I'm gonna need to figure out how to work around.

**Comment by AzGilrock** [comment]
Regarding OBJ files they were supposed to be under the "meshobjects" area.  Looks like I put everything there except the OBJ files.  The MTL files and a PNG are there.

**Comment by AzGilrock** [comment]
Ok I temporarily modified the .gitignore file and now the .obj files showed up so I was able to add and upload them to the meshobjects folder in my branch.

**Comment by AzGilrock** [comment]
Did you see my write up under the conversation section here?  I tried to do the start of a user manual for the model parameters and the effect.

**Comment by AzGilrock** [comment]
Ok weird….I was replying to a comment then after I posted I realized my view wasn’t updated and the comment was 3 days old…lol

**Comment by derwin12** [comment]
The color wheel seems to easily show up if I place this new effect on a single head - other ways seem to work if all the moving heads in the group are set to color wheel. It is not easily repeatable.
Closing this as you addressed the missing obj files and will take a look at the conversation.

**Comment by AzGilrock** [comment]
Yes it hides the color wheel unless every moving head that has a checkbox selected in the effect has a color wheel with matching colors.
