### ISSUE TITLE
Adding Tetra2Go support in the wled.xcontroller file

### ISSUE THREAD

**Issue by jasonsomers** [xLightsSequencer/xLights#4286]
We at RGB2Go would like to request that our Tetra2Go controller be added to the wled.xcontroller file

```
<Controller Name="RGB2Go-Tetra2Go">
        <Variant Name="Base" Base="WLED:BaseWLEDSettings">
            <MaxPixelPort>4</MaxPixelPort>
            <MaxSerialPort>0</MaxSerialPort>
            <Port1>2</Port1>
            <Port2>13</Port2>
	    <Port3>12</Port3>
	    <Port4>14</Port4>
        </Variant>
	<Variant Name="w/ Differential Module" Base="WLED:BaseWLEDSettings">
            <MaxPixelPort>8</MaxPixelPort>
            <MaxSerialPort>0</MaxSerialPort>
            <Port1>2</Port1>
            <Port2>13</Port2>
	    <Port3>12</Port3>
	    <Port4>14</Port4>
	    <Port5>27</Port5>
            <Port6>26</Port6>
            <Port7>25</Port7>
            <Port8>33</Port8>
        </Variant>
</Controller>
```

**Comment by jasonsomers** [comment]
Is there something i could do to expedite this process?  Since I am not a software guy, I am not very familiar with this process, but if someone could point me in the right direction to getting the controller file modified, I would appreciate it! 
Thanks!
-Jason

**Comment by jasonsomers** [comment]
Lol.
I know this is a simple conf file edit - but I didn't want to assume that it would be appropriate for me to make a pull request.

**Comment by computergeek1507** [comment]
I added them and made a new Vendor option for you. 5cd4489a9465ebce1326cc963ff6b56597ef3f92
