### ISSUE TITLE
xLights freezes when I attempt to open layout tab

### ISSUE THREAD

**Issue by MikeO1964** [xLightsSequencer/xLights#4299]
**Describe the bug**

***NOTE:  I am a first time user so may have done something wrong.  I have attempted to attach relevent information.  Please let me know if you need more.

I open xLights with an empty project, no hardware, layout or anything.  Click on layout tab and the application freezes.

**To Reproduce**
See Above

**Expected behavior**
I think this should open the layout tab, which would allow me to upload a photo of my house, but I am a first time user and not positive of that.

**Screenshots**
Opened blank project
![xLights 1](https://github.com/xLightsSequencer/xLights/assets/157918255/80263984-d740-4517-ab77-7bf0f950dbc2)

Highlighted layout tab that i hit
![xLights 2](https://github.com/xLightsSequencer/xLights/assets/157918255/6fe31295-2da4-4ad0-bb14-c98e9f6f1628)

**Versions (please complete the following information):**

OS: Windows 22621.3007
xLights 2024.02 64 Bit

App Hange error screen shot
![app hang error](https://github.com/xLightsSequencer/xLights/assets/157918255/3fd2ece2-e815-41b4-9f82-31d99b51d6a8)

**Comment by derwin12** [comment]
Perhaps try downloading a prior version .. 2023.x from xlights.org - to see if it is your computer or the version.

**Comment by cybercop23** [comment]
Or try to change your show folder to not be on a OneDrive. We've seen issues with it trying/allowing to create the necessary folders. Set your show folder to c:\show as a test.

**Comment by cybercop23** [comment]
@MikeO1964 is this still an issue? Please try the above suggestions and if no longer an issue, please close it.
If you need further help, hop into the zoom room, xLights -> Help ->Zoom

**Comment by MikeO1964** [comment]
> Or try to change your show folder to not be on a OneDrive. We've seen issues with it trying/allowing to create the necessary folders. Set your show folder to c:\show as a test.

I'm trying to change the show folder to something other than the onedrive path, however, any attempt to change that also ends up locking up the software.  Is there a way to change it through the registry?  or reset it without uninstalling/reinstalling?

**Comment by derwin12** [comment]
Run via CMS prompt.
  xlights /w
