### ISSUE TITLE
UI elements invisible in Windows Dark mode

### ISSUE THREAD

**Issue by jagerkin** [xLightsSequencer/xLights#4300]
**Describe the bug**
When in Windows dark mode: elements in the "Controllers" tab are invisible, also in the Layout tab you can't see entries in the Add to Model/Models in Group boxes at all, though you can reorder them and see them in the Model/Group box.

**To Reproduce**
https://youtu.be/W_X0oh1UrYw

**Expected behavior**
List elements should be visible.

**Screenshots**
https://youtu.be/W_X0oh1UrYw

**Versions (please complete the following information):**
 - OS: Windows 11 Professional, 64 bit
 - xLights Ver 2024 02 64bit

**Additional context**
Works fine in light mode.

**Comment by computergeek1507** [comment]
Duplicate
