### ISSUE TITLE
Auto scaling the Faces Eyes Open/Eyes Closed Grid

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4308]
Investigate if easy to allow the Open & Closed boxes to auto scale as the window is made bigger.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/ca616583-a137-4a7e-a6ee-957d2ee01970)

**Comment by AzGilrock** [comment]
If someone can show me how to get wxWidget objects to size and flow easily I'll buy em a beer.  I have so many frustrations and waste so much time trying to get widgets to do what I want.

**Comment by cybercop23** [comment]
FWIW... I was doing some research earlier today in wxWidgets and apparently Audocity is all wxW.
I poked arround and found this Pref that when  activated, it widens the column. See below. 

https://github.com/xLightsSequencer/xLights/assets/23619433/42f1ebc6-fc1a-4090-a904-4c2486643bb9

**Comment by computergeek1507** [comment]
I added this to the Submodels dialog sometimes last year

**Comment by derwin12** [comment]
Awesome .. new tricks to make things better.
