### ISSUE TITLE
xLights Crashes when trying to upload output to a ESPixelStick

### ISSUE THREAD

**Issue by SLSettles** [xLightsSequencer/xLights#4309]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

Describe the bug
xLights shows the ESPixelStick in green status and clicking the Open button opens the web page, but the Upload Output does this crash every time.

To Reproduce

Select the ESPixelStick controller.
Click Upload Output
Crashes
Expected behavior
Expect the Output be sent to the ESPixelStick

Versions (please complete the following information):

OS: MacOS 14.0
xLights version 2024.01
WLED 0.14.1/2401141

Additional context

Appears to be identical to Bug #4005 which was closed last year.

**Comment by cybercop23** [comment]
Are you running WLED FW or ESPixelStick? What is the controller configured as? I use both andusing latest F/Ws and xlIghts there are no issues that I know of. Please check to make sure you have the ctrl configured correctly. If so, please try and then Tools, Package Logs and load the resultin ZIP file here.

**Comment by SLSettles** [comment]
I am running WLED 0.14.1 on an esp8266 3.1.2 (PixelArtStick Costume edition). I can run everything fine using my manual configuration, but if I try to Upload Output XLights crashes every time, without an error report, it just vanishes. 
[xLightsProblem4309.zip](https://github.com/xLightsSequencer/xLights/files/14115955/xLightsProblem4309.zip)

**Comment by computergeek1507** [comment]
What controller settings are you using in xLights, screenshot please

**Comment by cybercop23** [comment]
He's 2 confgiured as ESPixlel stick.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/5cdc3259-964f-497a-a48c-193d6b215ce4)

Change them to WLED lke this and that should work. We're uploaading to the FW not the HW. So since you areusing WLED on a 8266, needs to be set as such...
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/32408c4c-473d-4944-b47c-efeba9739934)

**Comment by SLSettles** [comment]
Ah! I’ll try that. Thanks!

**Comment by SLSettles** [comment]
Yep, that was it. Worked a treat, thanks so much.

**Comment by cybercop23** [comment]
Cool. Please close this issse. Enjoy.

**Comment by AzGilrock** [comment]
Probably should stay open cause xLights shouldn't crash all because a user has HW configured different than we expect.

**Comment by computergeek1507** [comment]
65bdb8b349a255a373ff31a98f88b686cb939b1c
