### ISSUE TITLE
Sequencer - Reset Windows To Default (Edit Display Elements)

### ISSUE THREAD

**Issue by ChooChooMan74** [xLightsSequencer/xLights#4311]
When the Edit Display Elements window is on a secondary monitor, clicking "Reset Windows to Default" does not bring it to the primary monitor.  If the secondary monitor is no longer available, then the Edit Display Elements is not accessible. 

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
Unable to replicate this on a Mac. Having laptop and external monitor connected.. regardless where the main xlights and display elements windows are, on laptop, on monitor, split... regardless, Dock All docks it. If docked and closed and click on Display Elements it shows back up docked.
If I leave it on the external monitor and just unplug the monitor, it moves to the laptop screen.
If I leave it on external monitor and exit xlights and restart it w/o the external monitor it shows up on the laptop screen. Docking All will dock it.

please try similar flow and screen record it and share...

**Comment by cybercop23** [comment]
Mark B (vividsequences.com) tested this on Windows and it worked. So long you do Dock All, they fly back in.
He also mentioned that he has to do this, as expected, when he switches laptops vs desktop and leaves windows open on external monitors.

Moral of the story.... try Dock All.

**Comment by AzGilrock** [comment]
Yep I’ve never seen a Reset to Defaults followed by Dock All not fix this kind of thing

**Comment by ChooChooMan74** [comment]
When I originally did the testing, I tested without closing xlights.  I need to find where to save the location of my sequencing windows. Mine always restores to default on start up. I will update.

**Comment by AzGilrock** [comment]
Yes that’s the Perspectives.

**Comment by ChooChooMan74** [comment]
Can you believe I just learned about perspectives. Anyways. If "Edit Display Elements" is checked, and you click "Dock All", it will bring it in.  If it is not checked, it will not bring it in. Then clicking on "Edit display elements", It is still on the other monitor. Even clicking restore to defaults keeps it on the other monitor. 

In conclusion. While Docking with it enabled will bring it to the main screen docked.  If you return to defaults (the default perspective has it off the screen) In fact, that is the only window that returns to the other screen after you click "Restore to Defaults"  

Here is my Testing.
Put EVERY window onto other monitors.
Save as the Default Perspective (Same as autosave and close??? Didn't try that)
Click Dock All. (Everything Docks)
Click Restore To Defaults
Open all Windows Again.
Edit Display Elements will go back to the secondary monitor.

Running Windows 10, 3 Monitors, Nvidia 3060 Graphics.

**Comment by AzGilrock** [comment]
Well quit doing the steps backwards from what I said works.   You wanted to know how to fix the situation.  Do. Reset to Defaults then a Dock All.   That will get it back on your monitor.   I assumed you would know how to save it from there.
