### ISSUE TITLE
Mirror of Main model element at the end of submodel list

### ISSUE THREAD

**Issue by jackyelliott** [xLightsSequencer/xLights#4318]
I use states for a lot of actions. Using them in submodels is not possible without first placing a face effect down and using state as outline. This works for when you want to statically activate the state chosen.  However, the automation of the State effect is only feasible to be used on the main model element.  This is an issue due to the fact that submodels will over write any state effects that are active due to render order.  Having a mirror of the main element at the bottom of the list that has the same attributes as the main model would alleviate two issues. One is the face effect and the other is states. Face effect is easy enough but can get confusing to most users. 
Creating a submodel for the face effect and keeping it in the correct order is simple but it seems that some users like to reorder things and can't figure out why it's broke. 

What I think may work is giving the attributes of the main model element to the last submodel in the list. Essentially mirroring the main element and sticking it in the list where STRAND is. Or having a totally new position but at the end so that it has higher render order. This can fix the "Dark Faces" effect I use and have automation on the model by using states after the submodels. 

An alternative I've used is creating a group and placing the group down on the list and using a per model default. It works but is complicated and requires a lot of tweaking each time.

**Comment by computergeek1507** [comment]
See if 2d90da687a813a2f4c77b970452f63da6187fcf6 helps with you issue

**Comment by jackyelliott** [comment]
This didn't test properly. Any more chance to look at this

**Comment by cybercop23** [comment]
Done. Available in the nightly and will be in the next version.
