### ISSUE TITLE
Double phoneme in faces

### ISSUE THREAD

**Issue by jackyelliott** [xLightsSequencer/xLights#4319]
This enhancement request is for ease of use.  Having the option for a second set of phonemes in the face definition. Much like the addition of the multiple outlines and the eyes.  This would allow for multiple colors on the same face. Examples, tongues, gums, teeth, and even blacking out areas of the main body when the mouth is open.  

This would need to be either made available only if forced colors (grayed out if not), or take the color of the last color chosen in the pallet. Since the pallet is only so long. Unless the second phonemes can only take one color for all #2 phonemes.  My opinion would be to only allow it when forced colors is checked. 

I've used multiple face effects on layers to accomplish this. It works fine. This however would simplify the process and help me personally with model creation. Simplifying the process for new users and sequencers alike.  
Thank you for your consideration and all of your help.

**Comment by cybercop23** [comment]
Available in 2024.8
