### ISSUE TITLE
Add the Select Highlighted and Deselect Highlights options to Test Lights

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4325]
Seems like this could use the usual right click options of selecting and unselecting highlighted..

![image](https://github.com/xLightsSequencer/xLights/assets/4643499/fca75d2d-39eb-4386-839b-0d315d1bd077)

**Comment by cybercop23** [comment]
Number -> 13.. would select them

**Comment by cybercop23** [comment]
Available in the nightly and next version.
