### ISSUE TITLE
Custom Face Definitions don't display in pull-down menu

### ISSUE THREAD

**Issue by kmillecam** [xLightsSequencer/xLights#4327]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Using the "Face Definition" dialog I've added four faces:
Bulb Custom 1 (red outline), Bulb Custom 2 (orange outline), Bulb Custom 3 (purple outline), Bulb Custom 4 (green outline.

When I attempt to apply one of the definitions to a specific model (bulb 4, for example) the dropdown only lists two of the definitions. Bulb Custom 1 and Bulb Custom 4 in the case when I'm attempting to apply the definition to Bulb 4.

The options in the dropdown do change depending on which model I have selected.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'the layout tab and create a custom model'
2. Name the model "Face 1"
3. Repeat steps 1 and 2 until you've created 4 custom models named: Face 1, Face 2, Face 3, Face 4.
4. In the Models list, click "Face 1"
5. Scroll down to 'Faces and click the "click to edit" option'
6. In the Face Definition dialog click the Add button.
7. Create 4 face definitions, each with a different color selected for the face outline.
8. Save your changes
9. Close the Face Definition dialog
10. In the Models list, click "Face 4"
11. Scroll down to the "Faces" section of the model configuration and click the ... next to the "Click to Edit" label.
12. Expand the "Name" dropdown.
13. Notice that some of the definitions you added are missing.

**Expected behavior**
All of the custom Face Definitions that you added would be displayed in the selector.

**Screenshots**
![Face Definition Dialog](https://github.com/xLightsSequencer/xLights/assets/697409/15000a9a-bbf9-449a-83bb-c4ee73e5b0b6)

**Versions (please complete the following information):**
 - OS: Mac 14.3]
 - xLights version [e.g. 2024.02]

**Additional context**

**Attachments**
I would prefer not to post my sequence. Please feel free to DM me for a copy.

**Comment by cybercop23** [comment]
The face definitions need to be defined for each model. Before you try to use it, check that all bulbs have all face definitions. This particular one, only has 1 & 4 so you will not be able to use 2 and 3 at all. Go to each model, edit Faces and make sure in the drop down 1-4 is listed for each individual model.

If you still have an issue, go to Tools, Package Logs and load the ZIP file that get created or create a test sequence and Package sequence and upload it.

**Comment by kmillecam** [comment]
Thanks for the feedback @cybercop23.
So, are you saying I need to create 16 face definitions? (Four for each model) in order for them to display in the dropdown?

I'm attaching screen captures from each of my 4 custom models to show what the dropdown shows in each.
I'll also attach the sequence file.
![Bulb 1](https://github.com/xLightsSequencer/xLights/assets/697409/1249a98b-8bcc-49c7-9c8f-d358c061b28d)
![Bulb 2](https://github.com/xLightsSequencer/xLights/assets/697409/5634b380-4ad7-42b0-acef-8f283f9e003b)
![Bulb 3](https://github.com/xLightsSequencer/xLights/assets/697409/15a9a547-7811-4631-afc4-fb23c16c8ad8)
![Bulb 4](https://github.com/xLightsSequencer/xLights/assets/697409/8769b717-980b-465d-9cbe-0c78f6885012)
[Hark the Herald Angels Sing.zip](https://github.com/xLightsSequencer/xLights/files/14215724/Hark.the.Herald.Angels.Sing.zip)

**Comment by cybercop23** [comment]
Yes, each model has to have its own face definition. So if you want 4 faces with unique colors, you'll create 4 on one of them.. BUT.. then you can go to the other 3 and click on the 3 dots next to Add and import them from the first one - no need to manually create them all.
Wisht here was an option like we have for Sub-models that will allow you to export from the first one to manu others... ohh well.. we can only dream.

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/75a9c6f2-f4e2-4a56-9027-1bfb493845ff)

Hope this makes sense.

**Comment by cybercop23** [comment]
If okay, I'm going to close this. Feel free to re-open if any issues or hop on zoom, Help -> Zoom

**Comment by kmillecam** [comment]
Thanks for your explanation, @cybercop23 !
