### ISSUE TITLE
Model and Timing Grid name conflict prevents adding model to Sequencer Display Elements

### ISSUE THREAD

**Issue by ghost** [xLightsSequencer/xLights#434]
I have an "Arches" model and a "Mega Tree" model, both named accordingly.

I had timing tracks with the same names ("Arches", "Mega Tree") (don't ask... item specific timings from an LOR import)

I find that the models are missing from the bottom half of the "Add Timings/Models" dialogue box.

If I rename the timings to something different then the models  re-appear in the list and I can then add them.

On a maybe related note... In the "Add Timings/Models" dialogue box, the top half is labeled "Timings:", and the bottom half is labeled "Timings/Models:"... Should "Timings" really be part of both labels?

**Comment by AzGilrock** [comment]
This was brought up before but not sure if in another issue or elsewhere.  Too many issues for me to care to search for it.  Timings and Models are all from the same Element class so we search for an element name so they need to be exclusive names.  I don't think we will change it to allow the same names in both spots but we should try to detect and disallow the duplicate names.

**Comment by AzGilrock** [comment]
Fixed the dialog label.  For the naming conflict I gotta think about that.  It's not as easy as I thought because models can be created while no sequences are open and timing track names only exist inside sequences so you never really know you have a conflict until you open a sequence.
