### ISSUE TITLE
Cant delete an 'inactive' model from layout

### ISSUE THREAD

**Issue by bloojoop** [xLightsSequencer/xLights#4349]
xlights 2024.02

trying to delete a model that is set to inactive yields the following error message. 
![image](https://github.com/xLightsSequencer/xLights/assets/88390168/1a45eec2-0fdf-4a0f-afb2-a60530b9379e)
There are no open sequences and no effects. 

If I reconfigure the model to be active, then it can be deleted with no issues. 

I would expect that we should be able  to delete inactive models.

**Comment by cybercop23** [comment]
FYI... The plan is to allow the deletion of an Inactive model.

**Comment by cybercop23** [comment]
Implemented and merged to master. Please test the nightly (preferred) or in the next version.
