### ISSUE TITLE
Crash on Render All

### ISSUE THREAD

**Issue by cfudala** [xLightsSequencer/xLights#4352]
Short description: 
version  2024.03  
I did a bunch of model imports and sub model manipulation.
Loaded sequence, selected the render all palette,  system crashes.
dump files and package log file attached

Longer description:
I added 1 GE Peacock Arch via the Create new download
I added new sub models and sub model groups
I exported the model as an xLights model
I imported 3 more GE Peacock Arches via the Create New Import Custom button
I selected yes to the combine the groups
I imported one more GE Peacock Arches via the Create New Import Custom button
I selected no to combine the groups
xLights created new submodule groups (as expected)
I imported 2 more  Peacock Arches via the Create New Import Custom button
selected yes to the combine groups (I was hoping they would go to the second group.  Enhancement request on the way :) )
Then I moved the sub models, that loaded into the first groups to the correct (for me) groups.
Closed the application
Restarted and loaded a sequence
Selected render all palette
Crash

I reloaded version 2023.23 on top and all works fine with the same layout and models and model groups.

Windows 10 machine
version  2024.03

Crash report 
https://drive.google.com/file/d/1Xblp1fU8gDgAcHhYzUQHF3dh4GYCSts9/view?usp=sharing

Package logs
https://drive.google.com/file/d/1f9IN5GE4udQL7LfNJ8aMvG0lDbCC7PN3/view?usp=sharing

**Comment by derwin12** [comment]
It doesnt like the shader and color? Not sure of the fix - remove the shader? try a simple sequence with just the shader?
```
2024-02-14 18:34:26,625 12584 log_base [WARN] Unable to bind to colorInput
2024-02-14 18:34:26,760 12584 log_base [DEBUG] ShaderEffect::programIdForShaderCode() - fragment shader C:\Users\carlf\Documents\MyShows\2024\Shaders\Zoom Loop.fs compiled successfully
2024-02-14 18:34:26,760 12584 log_base [WARN] Unable to bind to colorInput
2024-02-14 18:34:27,197 12584 log_base [DEBUG] ShaderEffect::programIdForShaderCode() - fragment shader C:\Users\carlf\Documents\MyShows\2024\Shaders\Zoom Loop.fs compiled successfully
2024-02-14 18:34:27,197 12584 log_base [WARN] Unable to bind to colorInput
2024-02-14 18:34:27,219 6284 log_base [CRIT] Crashed: Fatal exception occurred.
```

**Comment by cfudala** [comment]
I reloaded 2024.03 and loaded a sequence that does not have any shaders.   It still crashes on render.  And now it is not giving me the dump file.  it just quits.   Since you mention colors, I noticed the enhancement to spin the color blocks.  I did click it to see what it does.  I don't remember saving anything after playing with it.  I will try a few more times to get an error report.

**Comment by cfudala** [comment]
sorry hit the wrong button

**Comment by cfudala** [comment]
From the latest log file.  
2024-02-14 21:25:20,166 4232 log_base [CRIT] Crashed: Fatal exception occurred.
There was no shader message in this one.

https://drive.google.com/file/d/1oEq7ab6yI7oQCTIBFheHaTiUafQnC-7P/view?usp=sharing

**Comment by derwin12** [comment]
I don't recognize this one.. What steps can you say you used to make this happen?
```
2024-02-14 18:24:35,458 4112 log_base [] Closing audio device 2.
2024-02-14 18:24:35,514 4112 log_base []     Result ''
2024-02-14 18:24:35,515 4112 log_base [] SDL uninitialized
```

**Comment by cfudala** [comment]
I don't think I can explain any individual item.  In regard to audio device, I use usb c ear phones if that helps.  I am on an older windows 10 pc (i7 processor). The general steps were; I loaded 2024.03 (down load file, run from the dl folder) loaded a sequence, added new props, manipulated layout, played with new features (colors) exited, (most of the time with suspend render checked ) restarted, loaded a different sequence, than what I was playing with, tried to render.  Crash.

Today:  I uninstalled xLights.  Installed 2024.03.  Set show directory etc. to my existing my show directory (containing my xml files of course.)  Started up. Loaded sequence.  Tried to render. Crash

Reinstalled 2023.23 ... noticed that the color bar changes are still there.  But everything renders fine.   Glad this isn't a global problem at least  :)

**Comment by derwin12** [comment]
Try reducing the sequence down to just one model and its effects that still causes the crash. Then you can upload that. I am still leaning towards the shader effect. So perhaps delete the effects on models that dont have the shader and test again.

**Comment by cfudala** [comment]
[xLightsProblem20240215.zip](https://github.com/xLightsSequencer/xLights/files/14305287/xLightsProblem20240215.zip)

I will try what you are suggesting when I am more awake.  Taking apart 50 hours of sequencing for a test is taxing at this hour  :)
The attached zip file is the log from a sequence of the same complexity and no shaders.

**Comment by cfudala** [comment]
I have two sequences that crash every time.   They just happen to be at the top of my list so I never went down any further. Items past those seem to be ok.  I can get it to crash just by opening it and selecting any model that will take up the whole model preview window.   I guess that's also a render.  But in those cases it created the crash file.   One has a shader the other does not.  I will compare for differences and similarities between those that crash and not and post my findings.

**Comment by dkulp** [comment]
It's likely the single strand chase effect.   The changes for the effect backgrounds are definitely causing memory corruption.

**Comment by derwin12** [comment]
> It's likely the single strand chase effect. The changes for the effect backgrounds are definitely causing memory corruption.

I can take a look there ... easy enough to remove the call for that one chase in the interim if needed.

**Comment by derwin12** [comment]
> > It's likely the single strand chase effect. The changes for the effect backgrounds are definitely causing memory corruption.
> 
> I can take a look there ... easy enough to remove the call for that one chase in the interim if needed.

I cant get a crash or issue with 100s of random ss effects. Not sure how to diagnose the memory corruption or how to see that.

**Comment by derwin12** [comment]
If they are not purchased sequences .. and you dont mind uploading one .. use package sequence and include that zip file here.

**Comment by dkulp** [comment]
On a plane right now so cannot check, but trace through the add rect stuff and you will see it didn't pre-size it nearly large enough.

**Comment by derwin12** [comment]
Ok .. 
I have a crash in another issue and it points back to the chase
#4353

**Comment by derwin12** [comment]
the code for the rects is wrapped in a if bufferinit .. so what appears to be happening is it gets sized with the skips sizing, then it wont be resized with the chase. I believe the fix is to remove this from both skips and chase and just let it resize each time. Trying to verify that.
```
 if (buffer.needToInit)
 {
     buffer.needToInit = false;
 }
```

**Comment by cfudala** [comment]
> If they are not purchased sequences .. and you dont mind uploading one .. use package sequence and include that zip file here.

https://drive.google.com/file/d/1vryf7laDE08hhxsbX9S_mGmOVK6ntH95/view?usp=sharing

This is completely mine and it has the shader.  The other one that fails is purchased and it is heavily modified for my layout. (Im sure ron howard wont mind)  All I kept was the timing and tree.  But it does not have a shader and I would love it if you looked at it too,  Let me know. 

However please don't distribute other than for debugging purposes.

**Comment by derwin12** [comment]
Pretty sure we know the cause .. I assume you rolled back to the prior release and it works?

**Comment by cfudala** [comment]
> Pretty sure we know the cause .. I assume you rolled back to the prior release and it works?

Thank you for finding it.  Yes I am running 2023.23 and no issues.

**Comment by robness** [comment]
I was having similar issues and after building and testing out the latest commit from @dkulp  it looks to have solved the rendering issues for me. I had no issues rendering all my sequences using Batch Render.
