### ISSUE TITLE
Color Curve Dialog box memory

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4367]
I've saved over 4 rows of color curves and started on my 5th in the Color Curve dialog box.  As you can see from the first screenshot below, the "OK" and " Close" buttons are not displayed in full.  In order to click the OK button, I always have to expand the size of the box.   I often catch myself accidentally clicking the "Load" button because I don't see the "OK" button haha.

Can this dialog be revised to remember the last user setting?  Or maybe allow the dialog refresh and auto expand and show those buttons upon opening the scree?

Thank you for looking.
Clyde L

![image](https://github.com/xLightsSequencer/xLights/assets/12719816/7f4a09ec-707d-4f38-81f2-576d6f087c0f)

**Comment by cybercop23** [comment]
Implemented. Will be available in the next release or tonight's nightly build.

**Comment by Clyde-L** [comment]
Thank you
