### ISSUE TITLE
Building for Windows - wxWidgets - should we have 2024.01 in here?

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4375]
https://github.com/xLightsSequencer/xLights/blame/6680eb6af0cda217a92613be3dff0f1e24d9ac0e/README.windows#L32C3-L32C101

Can someone comment on what this should be for new installs? Just wanting to confirm..
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/1a03de29-c2f9-4f77-9be1-9e9c46a7a435)

**Comment by computergeek1507** [comment]
I used the master for the nightly because it's normally about the same as the latest tag Dan creates. I would find the newest tag in the xLights Seq version of WX and use it for builds. If it doesn't work then you found a project to work on😜

**Comment by derwin12** [comment]
Ok. that is where I got the 2024.01 from .. the tags. Thanks for the confirmation.
