### ISSUE TITLE
xlights crashes when saving a new sequence

### ISSUE THREAD

**Issue by DBASQLGuru** [xLightsSequencer/xLights#4377]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Create a new sequence, import a bulby singing face and tune to matrix, then press save -- crash

**To Reproduce**
1) Create a new sequence, 
2) import a Boscoyo bulby singing face and Boscoyo Tune to matrix
3) Then press save -- crash

**Expected behavior**
New Sequence FSEQ file to be saved

**Versions (please complete the following information):**
 - OS: [Windows 10 64 bit]
 - xLights version [nightly build 2024_3_6680eb6]

**Additional context**
This is when a new sequence is being created, empty, only adding in the 2 above mentioned props

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced - Don't have drop box..
[xLights_dbgrpt-24860-20240228T114737.zip](https://github.com/xLightsSequencer/xLights/files/14438304/xLights_dbgrpt-24860-20240228T114737.zip)
[Dua Lipa - Levitating.zip](https://github.com/xLightsSequencer/xLights/files/14438309/Dua.Lipa.-.Levitating.zip)

**Comment by cybercop23** [comment]
Dale, do you have render on save turned on? If so, can you turn it off, do the import and save and upload just that part... or drop by in the zoom room so we can take a look.

**Comment by DBASQLGuru** [comment]
Thanks for the heads up!!  I just went back to 2024.2Sent from my iPhoneOn Mar 1, 2024, at 3:59 PM, AlexB ***@***.***> wrote:﻿
Scott make a 3 letter change and seems to test okay now on both the mac and windows. Please try the nightly tonight.

**Comment by computergeek1507** [comment]
My change affects the importing sequence, this seems different

**Comment by cybercop23** [comment]
He was mapping too, but at least he was getting the mapping window, where as Kyle didn't get it at all.
It does point to the same exact error... 
`[01]	ADDR:0x00007ff66e6baa15	HMODULE:0x00007ff66db30000	0000000000b8a9d0	UtilFunctions.obj	?NumberAwareStringCompare@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z@938E35 
`

**Comment by DBASQLGuru** [comment]
> Dale, do you have render on save turned on? If so, can you turn it off, do the import and save and upload just that part... or drop by in the zoom room so we can take a look.

Render on Save turned off - reverted back to 2024.02

**Comment by cybercop23** [comment]
Dale, please try the new nightly to make sure no further issues. Initial testing shows the issue to be resolved.

**Comment by derwin12** [comment]
If still an issue with .05 then please resubmit logs.
