### ISSUE TITLE
Batch Render Crashed when selecting multiple fseq files

### ISSUE THREAD

**Issue by DBASQLGuru** [xLightsSequencer/xLights#4379]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Using the Batch Render tool causes a crash

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Close all SEQ files
2. Under tools - use Batch Render
3. Select 19 FSEQ files - after removing a few props from non-correct Groups
4. Proceed with the task  = immediate crash

**Expected behavior**
All selected FSEQ files should be re-rendered using the new mapping to Groups

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10 64 bit 
 - xLights version [e.g. 2024.04]

**Additional context**
N/A

**Attachments**
FSEQ files are too big for upload
[xLights_dbgrpt-22512-20240301T205311.zip](https://github.com/xLightsSequencer/xLights/files/14467867/xLights_dbgrpt-22512-20240301T205311.zip)

**Comment by cybercop23** [comment]
Dale, please try the new nightly to make sure no further issues. Initial testing shows the issue to be resolved.

**Comment by DBASQLGuru** [comment]
Okay.. I will install it and test.  Thanks!

 

 

 

Regards,

 

Dale Cunningham

DBA / Consultant - SQL Server MCDBA 2000, 2005, MCITP 2008 / 2008 R2, 2012, 2014, 2016

Sunshine Software LLC

817-456-8025

fl ***@***.***> ***@***.***

Skype: fly_scuba

Twitter:  fly_scuba

https://www.linkedin.com/in/dalecunningham <https://www.linkedin.com/in/dalecunningham/>

**Comment by cybercop23** [comment]
Hi Dale. A new nighly will be available tonight with lots of other enhancements. Please test this and let us know if any further issues.

**Comment by DBASQLGuru** [comment]
Thank you for the update sir!

 

 

 

Regards,

 

Dale Cunningham

DBA / Consultant - SQL Server MCDBA 2000, 2005, MCITP 2008 / 2008 R2, 2012, 2014, 2016

Sunshine Software LLC

817-456-8025

fl ***@***.***> ***@***.***

Skype: fly_scuba

Twitter:  fly_scuba

https://www.linkedin.com/in/dalecunningham <https://www.linkedin.com/in/dalecunningham/>

**Comment by derwin12** [comment]
Please verify with .05 and reopen with logs if still an issue.
