### ISSUE TITLE
Duplicate question asked when replacing a model with a model

### ISSUE THREAD

**Issue by blun23** [xLightsSequencer/xLights#4380]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you use the replace model with this model feature, it asks 4 different questions but asks save old name as alias twice.  

**To Reproduce**

1. Go to replace a model with this model and replace a model with this model.  It asks a series of yes and no questions.   Questions 4 and 5 are identical.

**Expected behavior**
For it to only ask the question once if I want to save old name as alias

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Windows 11 and Mac Sonoma 14.2.1]
 - xLights version [2024.04]

**Additional context**
This is my first time on GitHub so please be nice.

**Comment by cybercop23** [comment]
Verified in TestFlight.

**Comment by blun23** [comment]
Great job everyone On Mar 11, 2024, at 6:19 PM, AlexB ***@***.***> wrote:﻿
Closed #4380 as completed.
