### ISSUE TITLE
Models in group are not sorting with display elements.

### ISSUE THREAD

**Issue by brmeadows2841** [xLightsSequencer/xLights#4391]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The models in a group are not sorting with what is displayed in display elements dialog.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to '...' Sequencer 
2. Click on '....' Edit Display Elements
3. Scroll down to '....' group

**Expected behavior**
A clear and concise description of what you expected to happen and why.
I would expect models in the sequence to follow the order in Display Elements 

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
Windows 11 22H2

 - xLights version [e.g. 2019.37]
Xlights 2024.4

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post [your]([url]([PixelStakestest.zip](https://github.com/xLightsSequencer/xLights/files/14509677/PixelStakestest.zip))) sequences publically please say so and be ready to PM them to one of the developers when asked.

[PixelStakestest.zip](https://github.com/xLightsSequencer/xLights/files/14509683/PixelStakestest.zip)

**Comment by brmeadows2841** [comment]
![xlighst display elements ](https://github.com/xLightsSequencer/xLights/assets/81775646/5ede86af-3a66-4fd4-b609-567c89b230f9)
![Xlights Seq view](https://github.com/xLightsSequencer/xLights/assets/81775646/270d53c4-0a0d-4538-9d3a-6fcf95924076)

**Comment by brmeadows2841** [comment]
First pictures are correct, I uploaded them by mistake the next two show the problem.
![display elements](https://github.com/xLightsSequencer/xLights/assets/81775646/e47d68dc-81e8-46ef-9600-1bbea80d747c)
![Sequence editor](https://github.com/xLightsSequencer/xLights/assets/81775646/6471d674-2d7c-4030-8e4a-8f70beb88a0b)

**Comment by brmeadows2841** [comment]
> Not sure I see anything wrong I think its a misunderstanding of what your looking at. For the top screenshot all the "Pixelstake Pixel" models have the eyeball on the left disabled which means those models do not show up in the sequencer grid. But they will show up under any groups they are a member of so when you expanded the "PixelStake Aerial GRP" you see all those same models but the order you see them there is determined by the order they are placed in the group over in the layout page. You cannot change the order that models display in a group from the Edit Display Elements dialog.

When did this change? I have been able to change the order elements displayed before from Display Elements.

**Comment by brmeadows2841** [comment]
Here is the layout tab. How should I sort the group elements in the seq editor? 

![Group display from Layout tab](https://github.com/xLightsSequencer/xLights/assets/81775646/477db568-9db6-47f0-ac99-c02a59b60564)

**Comment by computergeek1507** [comment]
You change the order of models in a group from the group's properties dialog.
![image (1).png](https://github.com/xLightsSequencer/xLights/assets/2293065/82bdea27-c72b-468b-831e-5e14d685d461)

**Comment by brmeadows2841** [comment]
I used Computergeek's method, this corrected the elements in the group.
But I could swear I have used edit Display Elements to correct the order of a group, before.
Oh, well thanks for the attention.
