### ISSUE TITLE
Edit Display Elements View Window Doesn't Display All Added Views (One Is Missing)

### ISSUE THREAD

**Issue by ssharpe83713** [xLightsSequencer/xLights#4395]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
A custom view is added in the Display Elements window, but it doesn't display below the Master View. It appears to only be a problem for the first added view.  Subsequent views are displayed.  The "hidden" view is listed in the drop down from the Sequencer window (see attached video, which shows 3 views on the Sequencer window, but only two of the three displayed on the Display Elements window. The "hidden" view is actually there.  If you click on the blank space just below the bottom visible view, the view elements that have been added to that view are shown (see attached video).

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. From a sequence that only has a Master View, add another view
2. That view isn't visible (but the blank space where it should be seen can be clicked); models can be added as normal.
3. The named view does appear on the sequencer drop down menu; just not on the Display Elements menu.

https://github.com/xLightsSequencer/xLights/assets/41525052/9b6c29c0-291d-4635-a9d0-a8c66ecfb21f

4. No errors.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024-04

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by ssharpe83713** [comment]
Thanks for the tip, Gil! That was it.

Best regards,

Steve

**Comment by derwin12** [comment]
Closing as a duplicate .. note only Windows 11 as far as I can tell.
