### ISSUE TITLE
Sequence Crashes on render - Since 2023 versions

### ISSUE THREAD

**Issue by ponddude85** [xLightsSequencer/xLights#4399]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Sequence imports fine. Save works fine.  Upon rendering the sequencer crashes every single time within 2 seconds of the render starting.  This has been an ongoing issues since version 2023.  

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
Very simple to reproduce - just open the sequence and attempt to render.  Sequencer will crash. Only happens with this particular sequence. 

**Expected behavior**
Sequence should render without crashing sequencer

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac 14.4
 - xLights version 2024.4

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically p
[Archive.zip](https://github.com/xLightsSequencer/xLights/files/14548837/Archive.zip)
lease say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
.3 had a crash .. .4 crashed on import. Can you upload a tools->package logs? Could be a shader issue.

**Comment by ponddude85** [comment]
Yes, of course. Uploaded here. 
[xLightsProblem.zip](https://github.com/xLightsSequencer/xLights/files/14551474/xLightsProblem.zip)

**Comment by derwin12** [comment]
No crash in either of those uploads. If you get another one or can see some recent files like "xLights_dbgrpt-????.zip" upload one of those. I see Dan just updated a change for crashes - and he gets these crashes automagically - so perhaps he has this fixed. 
(if you can upload the zip regardless - I can at least review the log)

**Comment by ponddude85** [comment]
Not really sure where to find that file. I don't see anything like that in my  xLights directory

**Comment by TPerkinsXlights** [comment]
I had a similar issue with 4 and it created the file that you are referring to. I decided to download 3 and use it instead and it doesn't create the zip crash log. It just crashes during the render process. Xlights 4 was crashing during import. Two different scenarios. There just isn't a file created during the render on Xlights 3. I think I may go back to 2023 for a bit. 
 Now - not sure which sequence I was working on at the time. Please be kind if it is a mess. hahaha. 
[xLights_dbgrpt-12868-20240311T121829.zip](https://github.com/xLightsSequencer/xLights/files/14577224/xLights_dbgrpt-12868-20240311T121829.zip)

**Comment by derwin12** [comment]
This log zip shows the known issue. It is fixed in the upcoming release or in the nightly build available.
(howto vid https://www.youtube.com/watch?v=jlaSb3O7CsI)
`[01]	ADDR:0x00007ff6797baa55	HMODULE:0x00007ff678c30000	0000000000b8aa10	UtilFunctions.obj	?NumberAwareStringCompare@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z@938E75 `
