### ISSUE TITLE
Create a Create Random Effect wizard

### ISSUE THREAD

**Issue by smeighan** [xLightsSequencer/xLights#44]
1) "Create Random Effects". This probably is bigger than what we had before. A wizard that might prompt for
a) How many effect layers do you want to use? 3.6.15: this was always 2
b) should we create random effects on all the layers in (a)?
c) Should the effect used on the first model also be used on all the other models? This was the shift-click from 3.6.15
d) Select from a list of all effects. The old method was either all effects or 1
e) Maybe something in color palettes. Should we always use 1 palette and just randomly pick from the 6 colors?
f) Select which timing track(s) should be used when creating random effects

**Comment by stevegiron** [comment]
Can this be closed?
