### ISSUE TITLE
Text showing as just 1 pixel after switch to 3d on per preview

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4400]
From Zoom. If user uses the default 2d per preview, it shows as 1 pixel - any prop it seems. Created a view "front view" and the models appear fine.
2024.02 and perhaps prior and current versions.
Ideas on what may cause this? Layout in the 3d space?

![image](https://github.com/xLightsSequencer/xLights/assets/4643499/4bb9ee6f-1ca7-4326-89d3-e6632cd3301f)
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/7efdba3f-e999-4184-aa1b-e4f70364d1a5)
[test1.zip](https://github.com/xLightsSequencer/xLights/files/14551147/test1.zip)

**Comment by derwin12** [comment]
Appears to be the layout was just done way too big. Leonardo, I dropped a new snowflake on your display using the default sizing and it worked fine. The new one is a fraction of the size of your display. I am afraid to say you need to do some redrawing.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/1fc52df2-70c1-411e-8e15-d6eee2c721bc)

**Comment by LRomano915** [comment]
Ok Thank you, I will catch up with you as to the best way to make it smaller. My first attempt was bad.
