### ISSUE TITLE
xLights Polylines Set to Single Color

### ISSUE THREAD

**Issue by CatalinaLights** [xLightsSequencer/xLights#4407]
[Single Color Polyline.zip](https://github.com/xLightsSequencer/xLights/files/14611416/Single.Color.Polyline.zip)
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
If a Polyline model String Type is set to Single Color or Single Color Intensity, adding an effect directly on the model does not appear to work in the visualizer or outputting to lights (as seen in sACNView). Adding the effect to a group that contains the Polyline model or to the Polyline model strand do work however.
FYI: I just checked in ver 2024.05 and the same issue is there also.

**To Reproduce**
1. Add Polyline model
2. Set String Type to either Single Color or Single Color Intensity
3. Create a Group with the Polyline.
4. Create new sequence (type doesn't seem to matter)
5. Add an On effect to Polyline model in sequencer (I used white checked in color selector)
6. Activate effect (selecting in sequencer or playing sequence). Note nothing visible in House or Model Previews.
7. Move same effect to group in sequencer. Note Polyline now shows as active in House View and Model Previews.
8. Expand Polyline model in sequencer.
9. Move effect to Strand 1. Note Polyline also shows as active in House View and Model Previews.
10. Move effect back to model. Note nothing visible in House or Model Previews.

**Expected behavior**
I expected to be able to add an effect directly to a Polyline model the same as any other model.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [Windows 10]
 - xLights version [2024.04; 2024.05]

**Additional context**
I noticed another thing that I'm not sure is intentional or not, but when the Polyline is set to Single Color Intensity String Type, I would expect it to not display a black box on the model line if it will respond to any color (like an RGB String Type does). It seems to display as black no matter what color it is set for in the model String Type.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment]
Fixed in 0676fad7dc91552d41676bdb44913e29be227372
