### ISSUE TITLE
XLights will not update to latest version

### ISSUE THREAD

**Issue by DPauley1** [xLightsSequencer/xLights#4414]
I have XLights installed on my PC running Windows 11 Pro. It's at version 2023.20. I've tried updating from this version but every time I run the update, the installer does not open. My Norton software says the update file is safe. I've tried disabling Norton when running the file but it still does not open. I uninstalled XLights and it won't install the latest update. I can reinstall XLights with Version 2023.20. any ideas what is happening or what I may be doing wrong?

**Comment by derwin12** [comment]
Disable the new Windows Smartscan software .. if that doent work hop into xlightszoom.com room for help

**Comment by derwin12** [comment]
Sorry .. it is called "SmartScreen" - part of windows defender.

**Comment by DPauley1** [comment]
That did it. Thanks!
