### ISSUE TITLE
Vamp Plugins Not Loading

### ISSUE THREAD

**Issue by Darzoom** [xLightsSequencer/xLights#4415]
**Describe the bug**
Some of the QMV plugins will load.  Others will not.  Specifically:  

/nnls-chroma.dylib.
/mvamp.dylib.
/tipic.dylib.
/azi.dylib.
/ua-vamp-plugins.dylib.
/segmentino.dylib.
bbc-vamp-plugins.dylib.
/cqvamp.dylib.
/Vamp/vamp-libxtract.dylib.
/qm-vamp-plugins.dylib.
/vamp-onsetsds.dylib.
/simple-cepstrum.dylib.
/vamp-aubio.dylib.
/silvet.dylib.
/cepstral-pitchtracker.dylib.
/match-vamp-plugin.dylib.
/tuning-difference.dylib.
/vamp-example-plugins.dylib.
/tempogram.dylib.
/beatroot-vamp.dylib.

They do exist in the /library/Audio/Plug-ins/Vamp directory.  see screenshot.

**To Reproduce**

Create a musical sequence and then try to use plug-ins.  Even when loaded, the above list of plug-ins are not available and show in the log as not found. 

**Expected behavior**
Expect plug-ins that were previously available continue to load. 

**Versions (please complete the following information):**
 OS- Sonoma 14.3.1
Mac -Book Pro M3
XL 24.5

![Screenshot 2024-03-17 at 9 05 36 PM (2)](https://github.com/xLightsSequencer/xLights/assets/81765092/715ddf4b-05ec-4f15-83de-6bd2ef027833)
[xLightsProblem.zip](https://github.com/xLightsSequencer/xLights/files/14629713/xLightsProblem.zip)

**Comment by dkulp** [comment]
None of those are compiled for Apple silicon (only x86_64).  There is nothing we can do about that until they release versions built for arm64.

**Comment by Darzoom** [comment]
Thanks Dan.  I was just adding the comment that they work on my Intel Based Mac.  Now it all makes sense.  Thanks.

**Comment by Darzoom** [comment]
No change.  Only the "base" 20 or so.
