### ISSUE TITLE
Controller dose not want to control lights 

### ISSUE THREAD

**Issue by Sam3287** [xLightsSequencer/xLights#4418]
When ever i boot my kulp k8-b its ses its testing but nothing showing on the lights.

https://github.com/xLightsSequencer/xLights/assets/105610765/92ccae51-3ba5-49cf-a368-d1c2d9ed9d54

**Comment by dkulp** [comment]
You need to resolve the warnings in the red banner.   It looks like you pushed configuration from xLights for a F8, but the controller is a K8.    Double check the xLIghts config to make sure it's for K8 and re-push.
