### ISSUE TITLE
Ripple effect using SVG file doesn't work in 2024.05 or 2025.06

### ISSUE THREAD

**Issue by ucfknight98** [xLightsSequencer/xLights#4430]
Sample sequence 
[RippleIssue.zip](https://github.com/xLightsSequencer/xLights/files/14751175/RippleIssue.zip)

**Describe the bug**
If using a SVG file in ripple, nothing is displayed. If I import a package with ripple files using SVG's, the first render crashes.

**To Reproduce**
Add ripple effect
Select any draw style but 'Old'
Select 'SVG' as object
Point to an SVG file
Nothing will be shown in the preview. 

**Expected behavior**
The SVG image to ripple. Works in 2024.04 and prior.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2024.05 and 2024.06

[xLights_dbgrpt-5632-20240325T172940.zip](https://github.com/xLightsSequencer/xLights/files/14751213/xLights_dbgrpt-5632-20240325T172940.zip)

**Attachments**
Attached crash log from an import then render of a sequence package using render with SVG files.

Added SVG file (but I have the issue with every SVG file I tried) 
[Flower.zip](https://github.com/xLightsSequencer/xLights/files/14751797/Flower.zip)

**Comment by derwin12** [comment]
Please attach the svg file if you could (zip it)

**Comment by ucfknight98** [comment]
SVG file has been added. Note I tried like 6 different files all with the same issue. This was the first one.
    On Monday, March 25, 2024 at 10:49:24 PM EDT, Daryl ***@***.***> wrote:  
 
 


Please attach the svg file if you could (zip it)

**Comment by dkulp** [comment]
Will likely require a Windows person to look at it.   Seems to be working fine on a Mac:

<img width="473" alt="Screenshot 2024-03-26 at 7 39 50 AM" src="https://github.com/xLightsSequencer/xLights/assets/91569/9ca7e7e4-ca5a-4de6-8318-8178bbab1d6a">

**Comment by merryoncherry** [comment]
I'll look at it this week if nobody beats me to it.

**Comment by derwin12** [comment]
Not working in windows - I found this earlier but figured it was just "some" svg worked and some didn't. No crash - but nothing rendered either. Simpler test was to put the svg on the shape effect. Nothing shows up.

**Comment by derwin12** [comment]
Crashes is happening in the similar code (shape or ripple). Some dont crash - but they dont render either.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/8aa8bc93-f034-4f24-979b-de191284b1c2)

**Comment by derwin12** [comment]
wxwidgets updated between .4 and .5 - could it be introduced there? (btw verified with shape effect, works in .4 not in .5)

**Comment by dkulp** [comment]
Almost certainly due to nanosvg.     We pick up the implementation of that from wxWidgets on Windows and thus the version we have really needs to be kept in sync with whatever version they use.

**Comment by derwin12** [comment]
This one is deep .. lol ..
So when it tries to draw the image it gets each pixel from the image and draw it in the buffer. It always returns 0,0,0.
 wxImage* image = buffer.GetPathDrawingContext()->FlushAndGetImage();
 etc etc
 cc = xlColor(image->GetRed(x, y), image->GetGreen(x, y), image->GetBlue(x, y), image->GetAlpha(x, y));

**Comment by computergeek1507** [comment]
I will look at it today

**Comment by derwin12** [comment]
Scott - your commits have it working for me..

**Comment by cybercop23** [comment]
Available in the nightly and next version.
