### ISSUE TITLE
Unable to launch 2024.6 AppImage

### ISSUE THREAD

**Issue by Gilimi-the-Grim** [xLightsSequencer/xLights#4431]
Hello all,

I am running Ubuntu 20.04 LTS and when trying to run xLights 2024.6 AppImage I get Library errors.  Does this indicate I need to upgrade something?  2024.5 works fine.

Here is a sample of what I am getting in the terminal when I run the application.

`oeh@WJHildreth:~$ '/home/joeh/Downloads/App Images/xLights-2024.06-x86_64.AppImage' 
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
/tmp/.mount_xLightEyh3oz/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_xLightEyh3oz/AppRun.wrapped)
`

Thank you for any assistance you can provide.

Joe

**Comment by dkulp** [comment]
Most likely yes.  We've updated to 2022.04.

**Comment by Gilimi-the-Grim** [comment]
Thank you, I will verify on my home machine which is running 22.04.  Thank you for the quick response and assistance.

Joe

**Comment by cybercop23** [comment]
@Gilimi-the-Grim were you able to check and re-test?

**Comment by Gilimi-the-Grim** [comment]
I am sorry.  I was caught up at work till late yesterday evening.  I will check tonight and update you.  Sorry for the delay.

Regards,
Joe

**Comment by cybercop23** [comment]
No problem. Please let us know.

**Comment by Gilimi-the-Grim** [comment]
I just tested on Ubuntu 22.04 and it is working.  Thank you for all you folks do.

Joe
