### ISSUE TITLE
Ability to add a (new) model or group to a sequence via scripting (Lua)

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4433]
Each year folks need to go thru all their sequences to add a new prop or group to their existing sequences. 
There are options in Lua to copy effects over from an existing model but the new model has to be in the sequence first.
Of course if you are just adding a prop to an existing group, no new changes are needed - just batch render..

The ask is to automate this prop adding function.
The thinking here is to start with a prop added to your layout and a have a view created that would be a template for the master view.

The Lua script would then:

1) Prompt for the sequence (this code exists)
2) **Prompt for the template view (new code)**
3) **Do the make master function of display editor (new function)**
4) Optionally render (this code exists)
5) Save sequence (this code exists) and repeat

**Comment by cybercop23** [comment]
Merged.
