### ISSUE TITLE
Crash when trying to create a new curtain effect.

### ISSUE THREAD

**Issue by cmgreenman** [xLightsSequencer/xLights#4436]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Xliights crashes trying to create a new Curtain effect with a musical sequence loaded

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Load Sequence 01 - Let It Snow mod.xsq
2. Open Sequencer 
3. Click the 'Curtain' effect

**Expected behavior**
expected behavior would be to not crash.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Ubuntu Linux 23.10
 - xLights version 2024.5 and 2024.6

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
https://www.dropbox.com/scl/fi/pxrfyy9vdic4tppjohcs2/xLights_dbgrpt-230014-20240326T205219.zip?rlkey=1kbs3fq6wa45qxuyo1yk3n0wu&dl=0

- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file 
See link above to crash file

- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file
https://www.dropbox.com/scl/fi/62y05z3q7rfseem21mg8n/01-Let-It-Snow-mod.zip?rlkey=7emr0pug3bof6dxxs6s9f7md1&dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
It is crashing on a video or something similar .. In preferences -> other do you have hardware encoding enabled?
```
2024-03-26 20:43:39,341 128132493940352 log_opengl [DEBUG] Play fps  20.134228   (25 ms)
2024-03-26 20:43:40,223 128132493940352 log_base [DEBUG] SDL Audio Pause: id: 12, device 2, pause 1.
2024-03-26 20:44:10,087 128132493940352 log_base [CRIT] Crashed: Fatal exception occurred.
2024-03-26 20:44:10,384 128132493940352 log_base [CRIT] xLights version 2024.05 64bit
```

**Comment by cmgreenman** [comment]
I'm not sure where to enable that.   I do have a video in the sequence but
it plays fine.

**Comment by derwin12** [comment]
Take a look under preferences, other tab. The last couple of versions changed quite a few libraries so this might be challenge to debug on the ubuntu side.

**Comment by cmgreenman** [comment]
Not seeing anything hardware related under preferences/other. :-(    I
tried removing the video and got the same crash.  This is a pretty recent
OS install and there isn't much else on it.  The system is a Minisforum
mini pc with Core i5 6th gen, 16GB ram and an Intel Iris 6100 graphics
card.

**Comment by cmgreenman** [comment]
So, I fired up an older appimage (2023.10) and everything works as
expected.  However, 2024.2/5/6 all crash so it's definitely something that
popped up recently.

**Comment by derwin12** [comment]
I can sort of duplicate this with a docker using the appimage and your showfolder .. more correctly .. your audio/the audio.
Please try without the audio and see if  that plays.
Ie. to to files->sequence settings, change from media to Animation.
Render and Play.
For me it wont play with audio - but has no problem without the audio.
I am no expert on this .. but perhaps it will help us figure it out..

**Comment by derwin12** [comment]
The dump is occurring on the bitmap draw in gtk (from what I can tell). The early versions of xlights, may libraries including wxWidgets were updated etc. Could it be that your base linux needs some updates?
When was the last working version for you? (2023.10 is too far back - can you find the latest working version then we can narrow down what changes may have triggered this)

**Comment by derwin12** [comment]
I installed a ubuntu 23.10 docker and ran the appimage without issue OTHER than no audio. Apparently that is not something I can do with a windows to linux docker. Can you try with no audio. Make sure your packages are upto date etc. etc. Others seem to be getting this to work.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/c603f698-1816-40c0-9480-7c1cd72cdeff)

**Comment by derwin12** [comment]
Yea.. I am running in docker and apparently you cant get audio out of a unix docker running on windows. So I am at a roadblock to find the cause. Hoping you find it is just the audio - perhaps even just switch out the .mp3 with another one - just to test.

**Comment by cmgreenman** [comment]
The issue started in 2024.1   2023.23 works perfectly fine.    oddly
enough, in 2024.1 the effect tool bar isn't rendering any pics however I
know for a fact 2024.2/5/6 all rendered the buttons fine.    Also I
converted the sequence to an animation only, saved, rendered, and still
crashes in 2024.1   here's the latest crash file.

**Comment by derwin12** [comment]
btw..yes, Dan & I fixed the buttons in the toolbar in those later versions. Sounds like something in wxWidgets and your config is messing up.

**Comment by cmgreenman** [comment]
I should point out that I tried compiling as well.  I couldn't find the
output from the docker builds (regular or Appimage) and the direct compiled
binary just segfaults on execution.

**Comment by cybercop23** [comment]
@cmgreenman can you try this?
If still have issues, hop in the zoom room so we can take a look
https://github.com/xLightsSequencer/xLights/releases/tag/2024.08

**Comment by cybercop23** [comment]
or better yet today's new release...
https://github.com/xLightsSequencer/xLights/releases/tag/2024.09

**Comment by cmgreenman** [comment]
> or better yet today's new release...
> https://github.com/xLightsSequencer/xLights/releases/tag/2024.09

I'll give .9 a try.   The crashing started with 2024.1

**Comment by cmgreenman** [comment]
Preliminary tests are positive.   It's not crashing like it was before.
 I'll work with it and see.    I did find another issue that popped up at
some point but I need to dig some more to find where and when it started
before opening a new ticket.   It has to do with models not being visible
in the 3D layout.

It also seems to run faster and the deprecated library error is now gone.
lol

**Comment by cybercop23** [comment]
Feel free to reopen this if any furtyher issues related to this item. Else, please open a brand new issue.
