### ISSUE TITLE
XLights crashes when Uploading Outputs to ESPixelStick v4.0

### ISSUE THREAD

**Issue by perigalacticon** [xLightsSequencer/xLights#4438]
**Describe the bug**
When uploading outputs to my device running ESPixelstick 4.0 (4.0-ci6981356867) it crashes after a second and generates a crash report.  I am able to upload sequences using FPPconnect but XLights will not upload the outputs.  My device is a Lolin D32 Pro.  I have been using it for several years without no problem, and I did not change the firmware or any other feature of the controller as far as I know.  It's possible this started since upgrading XLights but the last upgrade was a few months ago I don't know if I tried to upload outputs since then before now.

**To Reproduce**
Click "Upload Output" from the controllers tab within XLights with the Lolin D32 controller selected.

**Expected behavior**
The output definition should be uploaded to the controller within a few seconds and XLights should report it was successful.

**Screenshots**
none

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2023.20 64 bit.
 - ESPixelStick 4.0-ci6981356867
**Additional context**
Happens even after restarting XLights, power cycling the controller, power cycling the PC and power cycling the router.

**Attachments**
https://drive.google.com/drive/folders/10iqo3DETIODceBx0z_Tzjw-ATWzmiNfK?usp=drive_link

**Comment by computergeek1507** [comment]
Please update, I fixed this in version 2024.03, or update to the ESPixelStick 4.0 beta 5, it no longer used websockets which was causing this issue.

**Comment by perigalacticon** [comment]
I found that the crash is eliminated if I use sequential port numbers instead of having a intermediate unused port number.  For example I previously was using ports 1 through 4, but then redefined my controller connections by eliminating ports 2 and 3 which I was no longer using.  After changing the port numbers to 1 & 2 instead of 1 & 4 XLights no longer crashes.  This is more of an issue with ESPixelStick 4.0 but is really not a problem as long as you can easily access the hardware to switch the wire connections.
