### ISSUE TITLE
Stack the controller buttons on a resize

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4443]
When the right side of the controller tab is resized smaller .. the buttons are unusable. Perhaps stack them on two or 3 rows as needed?
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/ba490c6d-d5bf-4d36-b08a-eeee8e60d30b)

**Comment by computergeek1507** [comment]
Need a graphics designer to make us some icons

**Comment by kevinsaucier** [comment]
While you're playing with that, the buttons on the Submodels page have similar issues....  :)

![image](https://github.com/xLightsSequencer/xLights/assets/25715814/97ae20ae-5de6-4436-bc57-72a04c28bee1)

**Comment by marklancer** [comment]
What are the specs for the icons?   File format, size, ratio, etc?

**Comment by cybercop23** [comment]
Should be available in the nightly and next version.
