### ISSUE TITLE
In/Out Transition: From Middle

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4446]
Trying to use "From Middle" transition on basic On, Color Wash, and the Off effects and the "time" entered is not being tracked correctly by xLights.  If I set the transition time at say .5 second, the result is a delayed beginning followed by a quick "from middle" movement of the transition.  

Can someone else please check this out. I'm using 2024.5 and haven't upgraded yet because I'm in a project currently.

Thanks for looking!

Clyde

**Comment by dkulp** [comment]
I'm not seeing an issue: 

<img width="1049" alt="Screenshot 2024-03-30 at 1 51 05 PM" src="https://github.com/xLightsSequencer/xLights/assets/91569/c09d7421-566d-4781-bdf1-9f8b597ad60c">

**Comment by dkulp** [comment]
OK.  So it is reproducible...  The "timing" for the From Middle transition is calculated based on the length of the hypotenuse of the render buffer.  Thus, on a single strand/line, it's correct.   On something tall/skinny (like a tree), it's very fast.  I need to figure out what this is trying to do.   The adjustment slider comes into play here so likely that length needs to take that slider into effect as well.   Still digging.

**Comment by Clyde-L** [comment]
Thank you!
