### ISSUE TITLE
DMX Remap Crashes

### ISSUE THREAD

**Issue by ccaxlights** [xLightsSequencer/xLights#4455]
**Describe the bug**
I am trying to fix DMX mapping issues for moving heads. I have done remapping before without issue. On this purchased sequence it has Pan on the Pan Fine Channel and Tilt on the Tilt Fine Channel. I need to remap channel 12 to 11  and channel 10 to 9. When I try to do this and hit OK, XLIghts crashes and generates a crash report. I have tried about 10 times to do this remapping so I can continue making the MH sequence work on my system. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Select the all DMX effect on the four Moving Heads
2. Go to remap DMX
3. Change Channel 12 to 11, 11 to 12, 10 to 9, 9 to 10

**Expected behavior**
This should remap and get the ffect to apply to the proper command on the movings heads, specifically the pan and tilt.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac Ventura 13.6
 - xLights version 2024.04

**Attachments**
Sequence File
https://www.dropbox.com/scl/fi/ajg3n3qz3sxgftqb5xry2/That-Christmas-Morning-Feelin.xsq?rlkey=zwnmwkvxxt77gmv7c5lm7smnq&dl=0

Report Zip File
https://www.dropbox.com/scl/fi/p9tqvn0nq24lvwgtzinur/xLights_dbgrpt-20024-20240401T195647.zip?rlkey=ki8y52hozuu95xdpn9wmkgezu&dl=0

**Comment by cybercop23** [comment]
Fixed in the latest. Please upgrade and try again.

**Comment by ccaxlights** [comment]
Thank you so much, I thought I had updated fairly recently. I will try that.

**Comment by ccaxlights** [comment]
Cool thanks. Looks like I didn't see those because I was putting remap in the search, not map or mapping.

**Comment by cybercop23** [comment]
We'll blame the original reporter for not using the right key words. Kidding. ☝️ Totally what Gil said, it's the easiest and best way.
