### ISSUE TITLE
FSEQ file is incorrectly generated (ZSTD issue)

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4457]
Originally found on MAC but seems I can duplicate it on Windows.  (timhutson11 at gmail dot com)
Using .7 nightly and perhaps earlier.
Place a bars effect on a single line model. Render and save.
If you sent this file to fpp and output you will get a mess - lots of off an on.
(Fpp 7.6 and 6.3, Falcon v3)
Older fseq files show fine...
Examining the fseq files, I renamed the .fseq name to something original so that I could open .fseq in xlights and it wouldnt load the .xsq.   Drill down and this is what the fseq file sees.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/3e9cd729-dd00-4885-a668-340e9024ffe0)

This is what is in xlights when you render and save it. Just a simple bars effect.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/4beed3c0-f4b7-4e79-957e-be492ac35087)

[FSEQ Bug.zip](https://github.com/xLightsSequencer/xLights/files/14877187/FSEQ.Bug.zip)

**Comment by derwin12** [comment]
Fseq file seems to generate fine as uncompressed or zlib.

**Comment by dkulp** [comment]
9 MILLION channels exceeds the FPP 8M limit by a LOT.   Chop the matrix down to something reasonable and it seems to save and reload fine.
