### ISSUE TITLE
"Allow Blending Between Models" broken in 2024.07

### ISSUE THREAD

**Issue by marklancer** [xLightsSequencer/xLights#4458]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
In 2024.07 sequences render like the "Allow  Blending Between Models" check box is not checked even when it is checked.  

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

When the blending between models is checked effects on props/groups lower in the master view should render on top of  effects higher in the view.  Starting in 2024.07 only the lower effect is rendered.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]  Windows 11
 - xLights version [e.g. 2019.37] 2024.07 

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
Fixed based on #4454 .
Please try the nightly to verify. Will be available in three next release.
