### ISSUE TITLE
When Replacing A Model With Model, Lights is making duplicate models in Groups Again

### ISSUE THREAD

**Issue by blun23** [xLightsSequencer/xLights#4459]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you import a model and replace a model with a model, Xlights is creating duplicate models again like it was in the groups.  I am clicking Yes to everything so It should be combining every name and removing duplicates.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

![Screenshot 2024-04-05 at 12 18 16 AM](https://github.com/xLightsSequencer/xLights/assets/139409588/09bb5c43-882b-4255-8d6c-8ad4a80d1121)

**Versions (please complete the following information):**
 - xLights version 2024.07 Mac

**Comment by cybercop23** [comment]
Just tried it on a Mac, using latest (testflight 7.1) and no issues. Downlaoded a new B Star 23 3 rings, then another one and tried to replace... answered yes.. replaced and only one in the group. The download doesn't have groups, so you must have created them. Do you have groups in groups? Maybe upload your RGBEffects file so we can take a look. 

<img width="535" alt="image" src="https://github.com/xLightsSequencer/xLights/assets/23619433/4a8f073c-bc9c-41c9-81fe-274b1608dff0">

**Comment by blun23** [comment]
Since my show is so big (currently 510 models in 1423 groups), I have to export the models into another layout, make the changes and re-import, then do the replace model with model.  Yes, I have created quite of bit of groups.  Trust me, I have not one group in a group in the whole show.  I can message you the updated model that you can try in your show as an example, but I don't share my rgb effects file.  But It won't allow me to upload the xmodel here.

**Comment by cybercop23** [comment]
Just rename it to txt and upload it, XMLs aren't allowed.

**Comment by blun23** [comment]
[Boscoyo ChromaStar 23 3 ring.txt](https://github.com/xLightsSequencer/xLights/files/14891927/Boscoyo.ChromaStar.23.3.ring.txt)

**Comment by cybercop23** [comment]
Okay... I see the issue. Not related to your showfolder or models. Will need to look more into this.

**Comment by blun23** [comment]
Glad I'm not losing my mind.

**Comment by cybercop23** [comment]
Last worked correctly in 2022.15. Fixed in nightly and TestFlight, will be available in the next release.
