### ISSUE TITLE
Assert on Render - master 

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4497]
Something about custommodel and initrenderbuffer. Was not getting this earlier today..
type looks to be Vertical Per Model/Strand. Not clear how it is getting down to the assert.

![image](https://github.com/xLightsSequencer/xLights/assets/4643499/5d25223c-5611-4153-8ab3-220933d42c23)
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/1dd8a1a0-0c05-461c-96ef-12f29d31dcff)

**Comment by derwin12** [comment]
Does this need updating?
```
    if (StartsWith(type, "Per Preview") || type == "Single Line" || type == "As Pixel" ||
        type == "Horizontal Per Strand" || type == "Vertical Per Strand") {
        return;
    }
```
to something like this earlier call?
```
    else if (StartsWith(type, "Per Preview") || type == "Single Line" || type == "As Pixel" ||
        type == "Horizontal Per Strand" || type == "Vertical Per Strand" ||
        type == "Horizontal Per Model/Strand" || type == "Vertical Per Model/Strand") {
        Model::GetBufferSize(type, camera, transform, BufferWi, BufferHi, stagger);
    }
```

**Comment by computergeek1507** [comment]
Custom models don't have strands, it may be have a override returning zero and causing a divide by zero bug
