### ISSUE TITLE
Whole House Morph Effect Hangs

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4498]
Seems to replicate quite a while back ... I checked back to .03
1 3 second Morph Effect .. waited 10+ mins on Windows..
(added some logging .. nearly a minute per frame to render. So 3*40fps .. about 120mins to render) lol

[hangs.zip](https://github.com/xLightsSequencer/xLights/files/14967914/hangs.zip)

**Comment by cybercop23** [comment]
Model blending is turned off. If you turn it on, its instanteneous, unlikely anybody nowadays has that off.
Also if you change render to Per Preview and keep the blending off, renders in a second.

**Comment by dkulp** [comment]
The "Single Line" default buffer style for the group is creating a 1 x 30,707 size buffer.  There are several effects that will have serious performance issues with a buffer like that, the morph being one of them.   It's not actually hung, it's just really really slow.

**Comment by derwin12** [comment]
oaky .. it looks like the original sequence from the issue just used "random". So I suppose there is nothing we can do here. It is whole house - so why would it default to single line? Oh dang ... I see it .. yes they overrode the group to be single line. Serves him  right. lol
