### ISSUE TITLE
Nightly - Value Curves unable to enter -180.0 (6 chars)

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4500]
Seems the slider and defaults allow you to go as low -180. For both pan and tilt.

![image](https://github.com/xLightsSequencer/xLights/assets/4643499/213a0940-2df0-4820-88ca-367ecceddd9d)

**Comment by derwin12** [comment]
You cant **enter** any number .. seemingly below 0 .. but you can slide it either way..

**Comment by derwin12** [comment]
You know playing around with it .. it is the size of the field. so I cant enter -180.0  but if I drop the .0 it lets it go in.

**Comment by computergeek1507** [comment]
I fixed the OG issue but the ValueCurve::GetRangeParm1 methods seem odd to me, they return the FLOAT_MIN/MAX and not smin/smax which are the passed in Min/Max of the parameter. This allows someone to enter -200 and it doesnt error.

**Comment by derwin12** [comment]
Fixed with Scott's commit. Thanks folks
