### ISSUE TITLE
Issue with Models in latest nightly messing up single line verts and candy canes

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4502]
From zoom.. comparing latest nightly to prior nightly. Poly lines, candy canes are gone .. just to one pixel on the display.
Candy canes as stakes and single line verts on the house.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/cd374392-2aef-4593-9f6e-913489e8c5e3)
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/67c1e690-0669-456c-a71a-d4b535fe5336)

Perhaps this?
https://github.com/xLightsSequencer/xLights/commit/c423c8e50ec28d5175c5533a498a87d8e006232d

**Comment by dkulp** [comment]
Need to attach a layout/sequence.   My candy canes and poly lines are appearing fine.

**Comment by AGFazio** [comment]
> Need to attach a layout/sequence. My candy canes and poly lines are appearing fine.

Dan. Here is my rgbeffets file. 
[xlights_rgbeffects.zip](https://github.com/xLightsSequencer/xLights/files/14985092/xlights_rgbeffects.zip)

**Comment by dkulp** [comment]
Everything looks correct to me.  (although a packaged sequence would be TONS more useful as it has the controller configurations and the house objects and such)

<img width="1226" alt="Screenshot 2024-04-15 at 7 35 35 PM" src="https://github.com/xLightsSequencer/xLights/assets/91569/2e1ff57e-1009-4435-a7b1-85be7618a3d0">

**Comment by AGFazio** [comment]
@dkulp   packaged sequence 
[In Jesus Name 2.zip](https://github.com/xLightsSequencer/xLights/files/14985165/In.Jesus.Name.2.zip)

**Comment by AGFazio** [comment]
@dkulp  . I'm also in the zoom room if you want me to share screen and show you.

**Comment by cybercop23** [comment]
Looks okay on Mac, but see the same issue with last night's version. Nighthly from 2 days ago, seems okay.

**Comment by marklancer** [comment]
I'm seeing the same issue  Windows 11, latest nightly
![xlights issue](https://github.com/xLightsSequencer/xLights/assets/59756293/edfd9b67-031c-497d-8ceb-5026fff73e7b)

**Comment by AGFazio** [comment]
Changes every time I open xLights. Now my virtual matrix is hidden behind the shape of the flood light. Didn't do that prior. Flood light was transparent.   Matrices have blown out as well as stars, single lines, candy canes, 

<img width="874" alt="xlights messed up" src="https://github.com/xLightsSequencer/xLights/assets/81376486/ce6f0e7a-6ff7-4d01-943b-2a3aa5c2f3f1">

**Comment by derwin12** [comment]
Drop a native star.. interesting nan in scale
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/b13e2a26-ceec-4663-bf9f-9a368bf14b90)

**Comment by cybercop23** [comment]
Seems to be fixed with the latest force zero commit. 
[https://github.com/xLightsSequencer/xLights/commit/ffe7e86c3702c130cfd45f3c0386d4ce37156afa](url)

![image](https://github.com/xLightsSequencer/xLights/assets/23619433/c2f2eace-0f17-4a08-a9cd-665244f50831)

**Comment by cybercop23** [comment]
Daryl tested it too. Fixed. Please check tonight's nightly.
