### ISSUE TITLE
2024.9 tools, run scripts, export video files renders ok but video export crashes

### ISSUE THREAD

**Issue by rickkretzer** [xLightsSequencer/xLights#4505]
[A Christmas Twist.zip](https://github.com/xLightsSequencer/xLights/files/15012847/A.Christmas.Twist.zip)
![hardware settings](https://github.com/xLightsSequencer/xLights/assets/117498988/bda6be5d-32d9-47aa-9e3d-cb36be752dcf)
![hardware settings](https://github.com/xLightsSequencer/xLights/assets/117498988/ebb12e29-5305-43e5-92ab-6b3dc6e7d5cc)
[xLights_dbgrpt-12624-20240417T093829.zip](https://github.com/xLightsSequencer/xLights/files/15012886/xLights_dbgrpt-12624-20240417T093829.zip)
[xLights_dbgrpt-20348-20240416T204408.zip](https://github.com/xLightsSequencer/xLights/files/15004565/xLights_dbgrpt-20348-20240416T204408.zip)
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
@rickkretzer looks like you have hardware decoding off, is that right? File -> Preferences -> Other tab (top left).
Can you please post a screenshot here?
The crash zip file doesn't have all of the assets, like videos, pictures and the media. I changed it to an animation and it exported fine with both HD off and FFMPEG auto.
Can you:
1. change sequence type to animation and try again
2. if possible, package sequence and upload it here so we can get all assets and try it.

Also workes on a Mac as an animation sequence since some assets are missing.

@jbs00210 can you try/do the same?

**Comment by computergeek1507** [comment]
If you download the 2024.09 from GitHub releases does it crash?

**Comment by rickkretzer** [comment]
sent sequence as attachment to original problem report
________________________________

**Comment by cybercop23** [comment]
Sorry, missed both. Okay.. with 2024.9 and HD Off, it exported as an MP4.
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/14396f33-5f90-46ae-bac9-2103e5c4020f)

Ahh.. ok.. should have checked.. you were running 2024.8. Try 9 as the other guys sais it works and working for me too.

**Comment by hoodlumj3** [comment]
I'm using 2024.09,  I set Hardware Video Decoding to off or Auto or CUDA and it crashes no matter what
[xLights_dbgrpt-18420-20240418T025653.zip](https://github.com/xLightsSequencer/xLights/files/15015789/xLights_dbgrpt-18420-20240418T025653.zip)

**Comment by computergeek1507** [comment]
When you are exporting, it's "Encoding", not Decoding, the hardware decoders are not used. It may be more what Alex is saying any preview larger than 1080p will be exported as HEVC which may be the issue

**Comment by LawrenceLaxdal** [comment]
I'm also experiencing this issue on 2024.9.

I've attached the crash .zip. I'm a GitHub newbie so if more info or testing is required to help out please let me know!
[xLights_dbgrpt-14996-20240421T143045.zip](https://github.com/xLightsSequencer/xLights/files/15053453/xLights_dbgrpt-14996-20240421T143045.zip)

**Comment by rickkretzer** [comment]
This is fixed with the nightly update on github for 2024.09.1Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
-------- Original message --------From: LawrenceLaxdal ***@***.***> Date: 4/21/24  3:37 PM  (GMT-06:00) To: xLightsSequencer/xLights ***@***.***> Cc: rickkretzer ***@***.***>, Mention ***@***.***> Subject: Re: [xLightsSequencer/xLights] 2024.9 tools, run scripts, export video files renders ok but video export crashes (Issue #4505) 
I'm also experiencing this issue on 2024.9.
I've attached the crash .zip. I'm a GitHub newbie so if more info or testing is required to help out please let me know!
xLights_dbgrpt-14996-20240421T143045.zip

**Comment by LawrenceLaxdal** [comment]
Excellent, thanks Rick! I'll try it out.
