### ISSUE TITLE
DMX effect layer blend modes "Additive" and "Subtractive" no longer work in 2024.09

### ISSUE THREAD

**Issue by tmeyermn** [xLightsSequencer/xLights#4507]
**Describe the bug**
If you add a DMX effect at a group level and then another on a model in the group with "Additive" or "Subtractive" layer blend modes they are ignored.

**To Reproduce**
(packaged sequences are attached)
1. Add the DMX effect at the group level with "per model default" render style.
2. Add the DMX effect on one of the models in the group with "default" render style
3. Change layer blending to "Additive" or "Subtractive" on the DMX effect for the model

**Expected behavior**
If you have a pan value of 128 on the group and a pan value of 30 on the model in the group with layer blending set to "Subtractive" it should subtract the pan value (128 - 30) for the position.  It worked this way in 2024.8 and earlier but broke in 2024.9.

**Screenshots**
![bug](https://github.com/xLightsSequencer/xLights/assets/43391347/9dcb7885-0bb2-4889-8d83-67ad48bd33bd)

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024.09

**Additional context**

**Attachments**
[MHTest2024.1.zip](https://github.com/xLightsSequencer/xLights/files/15014895/MHTest2024.1.zip)
[MHTest2024.9.zip](https://github.com/xLightsSequencer/xLights/files/15014902/MHTest2024.9.zip)

If you would prefer not to post your sequences publicly please say so and be ready to PM them to one of the developers when asked.

**Comment by marklancer** [comment]
This appears to have been fixed in the latest nightly.

**Comment by tmeyermn** [comment]
Confirmed in latest nightly build 2024.09.1 on 4/27/2024.  Thank you!
