### ISSUE TITLE
Matrix Wave effect with Blur gives Bottom line no blur 

### ISSUE THREAD

**Issue by hoodlumj3** [xLightsSequencer/xLights#4508]
**Describe the bug**
The wave effect on a matrix model (specifically) when blur is applied - result is blur does not apply to the last horizontal line (or right most vertical line when waves are transformed 90deg CW or CCW)

**To Reproduce**
See attached show folder archive MatrixWaveBlurBug.zip
but... 
1) create a new matrix model (strings 8, nodes 128 )
2) create a new sequence (just animation)
3) Add matrix into master view if not already
4) Drag wave onto each matrix, expand fully or enough to see 
5) Configure each wave for Sine, Pallette, 900, 20, 100, 3, Right to Left, 0 (for higher density matrix (32x128) make thickness 5)
![2024-04-18 02_30_24-Window](https://github.com/xLightsSequencer/xLights/assets/17824913/9fa4e878-666f-420d-ac12-61cc1a41237f)
6) render

**Expected behavior**
A blurred continuous sine wave moving to the left

**Screenshots**
This is the result - the white one specifically
![2024-04-18 02_42_10-Window](https://github.com/xLightsSequencer/xLights/assets/17824913/7197a527-9cc4-46cb-beb5-9ef3113080cc)
I tried to export the house preview video .mp4 but xlights crashes every time

**Versions (please complete the following information):**
 - xLights windows version 2024.09

**Additional context**
if you make the wave thicker = 26 - it give a more solid look to the wave and bug dissapears - but then it looks like the bottom line is repeating

**Attachments**
[MatrixWaveBlurBug.zip](https://github.com/xLightsSequencer/xLights/files/15015646/MatrixWaveBlurBug.zip)

**Comment by cybercop23** [comment]
Did this started happening with 2024.9? Were you on .8 before when it worked?

**Comment by dkulp** [comment]
No.... this is a strange side effect of Blur of "1".   I saw a similar issue when trying to port the blur effect to the GPU and couldn't work around it which is why blur of 1 does not ever head to the GPU.   At the time, I didn't want to change render behavior of peoples sequences so I left it alone.

**Comment by derwin12** [comment]
So we leave this as is - legacy ..
