### ISSUE TITLE
When using auto map, groups and models auto map, but don't grey out on right side.

### ISSUE THREAD

**Issue by blun23** [xLightsSequencer/xLights#4509]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
As the title states, just went to map a sequence, hit the auto map and it auto mapped based off same name and aliases.  All Good There.  Problem being it doesn't grey out like normal so user doesn't know if they've used the model or group yet.  Even manually moving it over doesn't grey out.  I do have dark mode on but it's always been noticeably darker.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Import Effects
2. Click on Auto map or drag a prop from right to left side
3.

**Expected behavior**
Used groups or models should grey out.

**Screenshots**
![Screenshot 2024-04-17 at 8 36 56 PM](https://github.com/xLightsSequencer/xLights/assets/139409588/91607b8a-db64-4c3f-80ca-2a3489e7d52c)
![Screenshot 2024-04-17 at 8 37 11 PM](https://github.com/xLightsSequencer/xLights/assets/139409588/342d65df-9a52-419d-b93a-5f41eddf3b46)

**Versions (please complete the following information):**
 - OS: Mac Sonoma 14.4.1
 - xLights version 2024.09

**Comment by cybercop23** [comment]
Looks like a side effect of adding options to choose your own colors for highlighting and be on a Mac with dark mode.
You can change them in Preferences -> Color and the right side column...
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/8caae8bd-4a98-49bc-b3d0-8e7fcd06cc00)

**Comment by blun23** [comment]
Honestly bud, I don't think that's it.  It wasn't doing this at all on .08.  Also the Groups weren't showing up blue either on the left before.  It has always darkened when used.  I'll try turning off dark mode and see what it does.

**Comment by blun23** [comment]
Okay so without dark mode on, it greys out, with dark mode, no noticeable difference.


![Screenshot 2024-04-17 at 9 03 27 PM](https://github.com/xLightsSequencer/xLights/assets/139409588/cf8ea1f3-a101-4d15-93e8-1f26a5c95ff7)

**Comment by derwin12** [comment]
It was added in .09. May have missed this test on mac. You can add 2 colors in the preferences for this. People didnt like the defaults and this was added to cover that.

**Comment by blun23** [comment]
Okay so which one to change then so when it's used it'll look different.  If I have to go back to light mode I'm heading back to Mr. Christmas.

**Comment by blun23** [comment]
Also, I never used Mr. Christmas so that isn't really an option

**Comment by blun23** [comment]
So The Unselected Text is what needs changed.
