### ISSUE TITLE
Update Submodel Aliases Using Mapping

### ISSUE THREAD

**Issue by blun23** [xLightsSequencer/xLights#4510]
**Is your feature request related to a problem? Please describe.**
Not a problem but you can currently update Aliases this way on Models but not submodels

**Describe the solution you'd like**
There is a button at the bottom of the Mapping screen that allows you to Update Aliases of Models by using Mapping.  This would be awesome if it could be upgraded to also updated the Submodel Aliases.  This would make auto mapping much more easier for the user.  Currently you only can do something like this with a Mapping File.

**Additional context**
![Screenshot 2024-04-18 at 12 53 46 PM](https://github.com/xLightsSequencer/xLights/assets/139409588/b193562a-1255-408f-9100-aa1710766585)

**Comment by derwin12** [comment]
FYI ,, the import dialog is the next piece in the puzzle for the submodel aliases. Stay tuned.

**Comment by cybercop23** [comment]
Will be available in the nightly build and next version.
