### ISSUE TITLE
Feature Request: Set Default Viewpoint In House Previews 

### ISSUE THREAD

**Issue by MrFunnyPenguin** [xLightsSequencer/xLights#4513]
Hi xLights Team!

I think xLights is a great light show sequencing software. I find it quite easy to use. It would be great if there was an option to set the custom default viewpoint of the House Preview window. Like you could zoom in/out how far you want and then when you right click there could be an option to make that the default viewpoint. It is a little annoying to have to adjust it back every time I reopen xLights. 

Otherwise, great work and I look forward to seeing more greatness in the future!

**Comment by cybercop23** [comment]
You can save multiple view points as Gil suggests and then make one of them your default or make yet another one the default, right click Set As Default Viewpoint.
