### ISSUE TITLE
Hide Color Update Warning setting is not persistent (derwin12)

### ISSUE THREAD

**Issue by brett-foy** [xLightsSequencer/xLights#4516]
Hey team

The menu setting under preference>Effects Grid added in 2024.04 is an awesome add.  Thank you! 

   -- enh (derwin12)    Add preference to hide color update warning

However, it appears that that checkmark/setting is only persistent for the current xlights session.  When exiting and reloading xlights, that checkmark is removed and the default behavior of prompting to validate multiple color sets on effects returns.

It doesn't seem that the setting is being saved?

Thanks for taking a look!

**Comment by brett-foy** [comment]
Nice.  Thanks Gil.

**Comment by derwin12** [comment]
Yea.. I see Gil got this .. thanks.
