### ISSUE TITLE
Edit Display Elements - sort by group by size .. size is not calculated correctly.

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4525]
Seems size doesnt account for submodels or groups in groups when determining the size.

**Comment by derwin12** [comment]
Just to add currently, "size" is the number of models in the group - nothing do to with pixel count. This means a group made up of a lot of submodels &/or models could outnumber an all group for example. Looking to add a new sort option that will sort by pixel count.  So nothing "wrong" with the current code - just not the desired sort order.

**Comment by cybercop23** [comment]
Would the current option have any value once the new one is added, that's by true pixel count?
IDK the original intention of that option, we always thought it was pixel size so you can easily order the MV, but do we need two?
@keithsw1111 any insights?

**Comment by deplanche** [comment]
I like the existing way.   I have groups of several low density snowflakes (12 flakes of 48 nodes), that I like at the top rather than below a group of 2 high density props.   Not against having options for both ways, but don't think it should be just based on pixel count.

**Comment by computergeek1507** [comment]
I wrote it to only care about models in the group. Groups and groups are on their own.

**Comment by cybercop23** [comment]
Avail in nightly and next version.
