### ISSUE TITLE
Prompt to Copy Groups only when the Model is actually in Groups

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#4527]
I get it, this is kind of a 'busy work' request but I figured I'd make it since the newest functionality breaks my workflow so maybe it affects others as well.   

I frequently (or maybe semi frequently) make copies of props that I'm duplicating on my layout.  For instance, I have a bunch of pixel stake toppers (40 or so) that I'm putting on my display.  I used to be able to just CTRL-C, then CTRL-V 39 times in a row and come back in a few minutes and all 40 copies would be there ready for me to use.  Now, with the pop up asking if I want to copy groups, that doesn't work anymore.  I figured I'd just clear the base prop out of all groups but it continues to prompt to copy the groups even when the prop isn't a member of any groups.

Any way to have the prompt only come up when the base prop is actually a member of groups and skip it otherwise?

**Comment by cybercop23** [comment]
Done... #4522

**Comment by kevinsaucier** [comment]
Too easy.  I'm gonna find something else for you to do....  🤣

**Comment by cybercop23** [comment]
> Too easy. I'm gonna find something else for you to do.... 🤣

sure can... but this is only a click away....
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/527b334d-f9bc-4190-95e8-1ad1e34a9acb)
