### ISSUE TITLE
State as outline broken in 2024 .09

### ISSUE THREAD

**Issue by jackyelliott** [xLightsSequencer/xLights#4533]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
The use of state as outline is not working. When you drop down the window to choose the state if shows the face definitions and not the state defintion

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.
The definition for the states should be available so using any model that has states should show the issue.

**Screenshots**
![image](https://github.com/xLightsSequencer/xLights/assets/67920202/d35d5f30-5166-440b-8e08-70c1151764f8)
This image shows that it is pointing to Deer which is a face definition and not the state definitions

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by computergeek1507** [comment]
Oops I probably did that

**Comment by jackyelliott** [comment]
Well, hopefully that means you know what to fix then LOL  Yeah, it's pointing to faces instead of States

**Comment by jackyelliott** [comment]
![image](https://github.com/xLightsSequencer/xLights/assets/67920202/69e9a7db-cdcc-4b16-b0b8-ddf3b68be6e5)

Look at line 290
