### ISSUE TITLE
Set Center Point seems to have issues with submodels groups

### ISSUE THREAD

**Issue by blun23** [xLightsSequencer/xLights#4537]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
It seems the newer feature of clicking on layout in 2d and setting center point does not like groups of submodels only.  I've noticed it in both Icicle Groups/submodel groups and windows groups/ submodel groups.  If you add at least one model to it it works.

**To Reproduce**
Click on a group of submodels, go to layout and right click.  

**Expected behavior**
To offer the regular options of normal groups

**Screenshots**
![Screenshot 2024-04-30 at 11 02 40 AM](https://github.com/xLightsSequencer/xLights/assets/139409588/00c748b2-97d0-4ff2-af2c-a89920af36f2)

**Versions (please complete the following information):**
 - OS:Mac Sonoma 14.4.1
 - xLights version 2024.09
**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
That menu indicates there's nothing selects. Select the group again so the highlight bar is blue and try again.

**Comment by blun23** [comment]
It is also happening with my drum stick groups and spinner arm groups, so who knows.

**Comment by blun23** [comment]
So they still can be changed the old school manual way, but not using the new center mark technique that Gil put in.

**Comment by blun23** [comment]
Changed the title and description to reflect actual issue.

**Comment by derwin12** [comment]
Make life easier for us :-) Do a tools->package logs so we can use your layout to debug .. Thanks

**Comment by blun23** [comment]
> So I'm pretty sure its because the IsModelValid() function that is called to check whether its a valid group first iterates through the models and iterates through every submodel of each model but since its only submodels in the group it never iterates through them.

This was exactly what I was thinking, but couldn't quite put it into words as eloquently as you did.

**Comment by blun23** [comment]
Just noticed today that this is still happening.

**Comment by derwin12** [comment]
> Just noticed today that this is still happening.

Code is not included yet.

**Comment by blun23** [comment]
> > Just noticed today that this is still happening.
> 
> Code is not included yet.

Even using TestFlight?

**Comment by cybercop23** [comment]
Yup, even TS. It's a PR that has not yet been merged into the master branch. There are several of them like that. You can see them in the PR tab.

**Comment by cybercop23** [comment]
Should be available in the nightly and next version.
