### ISSUE TITLE
2024-10 Singing Faces Crash

### ISSUE THREAD

**Issue by DBASQLGuru** [xLightsSequencer/xLights#4542]
After importing a zipped sequence into the Sequence tab, then selecting the singing face from a Boscoyo Bulby Arch - the program crashes.

**Expected behavior**
It is expected to be able to assign a lyrics track to the singing face.
2024-10 64 bit

This issue started with this release version 2024-10
[xLights_dbgrpt-19924-20240503T164303.zip](https://github.com/xLightsSequencer/xLights/files/15205491/xLights_dbgrpt-19924-20240503T164303.zip)
[xLights_dbgrpt-30524-20240503T172618.zip](https://github.com/xLightsSequencer/xLights/files/15205492/xLights_dbgrpt-30524-20240503T172618.zip)

**Comment by derwin12** [comment]
Didnt crash for me .. but I have no audio .. and windows. 
I did a full render (took a while) .. then clicked on each of the face effects.
Are you on mac or windows? Can you provide any more details?
(in the first attached file, the sequence was empty)

The crash has something to do with Render?
Perhaps Dan is catching something in the crash logs.
```
2024-05-03 17:26:17,985 4508 log_base [DEBUG] EffectsGrid::mouseDown effect selected Faces.
2024-05-03 17:26:18,482 4508 log_base [CRIT] Crashed: Fatal exception occurred.


Walking from an exception.
[01]	ADDR:0x00007ff6d0e210a5	HMODULE:0x00007ff6d0600000	0000000000821000	ModelPreview.obj	?Render@ModelPreview@@QEAAXIPEBE_N@Z@5CD145 
[02]	ADDR:0x00007ff6d112052e	HMODULE:0x00007ff6d0600000	0000000000b1ffd0	tabSequencer.obj	?TimerRgbSeq@xLightsFrame@@AEAA_NJ@Z@8CC5CE 
[03]	ADDR:0x00007ff6d12d75b8	HMODULE:0x00007ff6d0600000	0000000000cd7360	xLightsMain.obj	?OnOutputTimerTrigger@xLightsFrame@@QEAAXAEAVwxTimerEvent@@@Z@A83658 
```

**Comment by DBASQLGuru** [comment]
The selection of a singing face, after the import, before any render, in the effects properties, select singing face #2, then the crash

**Comment by derwin12** [comment]
Still cant duplicated it ..  so I assume something in the import - I dont have the original sequence. Can you duplicate it by just importing the face effects? Can you strip out just that effect so you can share the original effect/layout with us?

**Comment by keithsw1111** [comment]
The crash has to do with preview rendering ... not effect rendering. Likely the model was reconstructed and the pointer invalid leading to a crash. These sorts of bugs have been around in low volume for a long time. To reproduce it we need to see every and the exact process you follow. ideally in a video. There is something about what and how you are doing something that is causing it and if you can do it repeatedly and we can work out what it is you are doing and reproduce it we may be able to fix it.

**Comment by DBASQLGuru** [comment]
Hello Alex. I am at my day job presently. However I have not been able to reproduce this issue 
    Get Outlook for iOS
  

 From: AlexB ***@***.***>Sent: Monday, May 6, 2024 9:01 AMTo: xLightsSequencer/xLights ***@***.***>Cc: DBASQLGuru ***@***.***>; Author ***@***.***>Subject: Re: [xLightsSequencer/xLights] 2024-10 Singing Faces Crash (Issue #4542) 
Dale, please provide the steps you take to replicate this issue. If easier, lets set up a time and get on Zoom and we can take a look together. Without this info we can't proceed and this won't be fixed.

**Comment by cybercop23** [comment]
Okay. We'll close and feel free to re-open whne you have a constant way of reproducing this.
