### ISSUE TITLE
model groups with one model causing stalling/crashing

### ISSUE THREAD

**Issue by adub22766** [xLightsSequencer/xLights#4543]
I have a Horizontal lines group with only 1 horizontal line model in it. From 2024.04-2024.10 (seems to be when the model point center definition was enhanced) when placing any effect on this group and rendering it causes xLights to stall and often will crash (my computer is a bit old and actually has caused my whole computer to blue screen then reboot while i have been trying to figure this out). One user on the AusChristmas forums that took my packaged sequence to test said it took 72minutes to render on his hardware running latest release, and another user was over 15mins. This same package renders in under 10seconds on my hardware on 2024.03. Although Dan Kulp had tested on his and it rendered in less than a 2nd on his Mac. Could be a Windows issue?

On my hardware, I have replicated this on versions 2024.04 - 2024.10 on Windows 10.

In my testing, if i add a 2nd model to the group the issue disappears.

[crash_test.zip](https://github.com/xLightsSequencer/xLights/files/15206619/crash_test.zip)
[xLightsProblem.zip](https://github.com/xLightsSequencer/xLights/files/15206620/xLightsProblem.zip)

**Comment by dkulp** [comment]
On both Mac and Linux, the above sequence renders in under a second.   Definitely will need a windows person to look at it.

**Comment by derwin12** [comment]
> On both Mac and Linux, the above sequence renders in under a second. Definitely will need a windows person to look at it.

Yea .. it goes to lala land in windows.

**Comment by derwin12** [comment]
I think this means xlights thinks it is really really big?
 Frame #0 render on model horizontals (400x2147484) layer 0 effect On from 0ms (#0) to 1000ms (#39) took more than 150 ms => 9024ms.
 
 (rb->BufferWi, rb->BufferHt)

**Comment by derwin12** [comment]
Workaround till the patch gets released is to create or add another prop or line to that group.

**Comment by adub22766** [comment]
Thanks for looking into it, you guys do awesome work. Yes, i added a dummy into the group and everything works as normal.

**Comment by cybercop23** [comment]
Will be available in the nightly and next version.
