### ISSUE TITLE
Crashes when add models to groups

### ISSUE THREAD

**Issue by lanops72** [xLightsSequencer/xLights#4556]
[xLights_dbgrpt-29424-20240508T155431.zip](https://github.com/xLightsSequencer/xLights/files/15255784/xLights_dbgrpt-29424-20240508T155431.zip)
[xLights_dbgrpt-33276-20240508T124300.zip](https://github.com/xLightsSequencer/xLights/files/15255785/xLights_dbgrpt-33276-20240508T124300.zip)
When Adding a model to a group xlights freezes 2024.10 64 bit on windows 11.
step 1 open xlights
2. go to layout tab
3. right click on a model
4. add to an existing group
5. Click save button
6. window pops up says log file generated

Expectation
I expect the model to be put in the group and be able to continue sequencing.

[somebody's watching me.zip](https://github.com/xLightsSequencer/xLights/files/15255818/somebody.s.watching.me.zip)

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
7. Scroll down to '....'
8. See error

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Cant duplicate here on Win 10.

**Comment by cybercop23** [comment]
Can't seem to replicate it either TestFlight/Mac, 2024.9.1 or 2024.10. I can add and save Bats -> CC group all day long

**Comment by derwin12** [comment]
Can no longer duplicate using master or nightly. If you can still crash this .. please provide a video or more explicit directions to duplicate it. Ie what props you clicked etc.
