### ISSUE TITLE
Showing incorrect end channel for MH shadow model

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4557]
The MH Dimmer etc are only 2 ( or 8 or) channels long .. but the layout is showing what appears to be a default of 16 channels.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/ce125ce7-d864-4e19-963b-d39bd1a39367)

**Comment by derwin12** [comment]
I think in this scenario - ie a shadow model like this .. then the end channel should just be blank. There is no meaningful number you could put there.

**Comment by cybercop23** [comment]
We can clen it up like we did for groups.. BUT.... should the start channel also be removed and just leave the @MH:1:1?

**Comment by derwin12** [comment]
Seems like a good idea..

**Comment by cybercop23** [comment]
So this looks good?
![image](https://github.com/xLightsSequencer/xLights/assets/23619433/fed624f8-9ca0-49ec-af61-6dddbab1adb2)

**Comment by derwin12** [comment]
I think that makes sense .. also allows one to quickly eyeball all the MH scenarios.

**Comment by cybercop23** [comment]
> I think that makes sense .. also allows one to quickly eyeball all the MH scenarios.

that and any shadowmodels since they all look alike.
