### ISSUE TITLE
Advanced Moving Heads - Gobo Selector

### ISSUE THREAD

**Issue by jholmes09** [xLightsSequencer/xLights#4564]
**Is your feature request related to a problem? Please describe.**
Just like color wheels, Gobos or other effect elements (like prisms) are difficult to select via DMX channel.
I think the color wheel feature expanding into Gobos would be an excellent addition.

**Describe the solution you'd like**
Gobo Selection similar to color wheel.
Control options below gobo wheel when the fixture has additional features.
(Prism ON/OFF, Gobo Rotation or Spin or Shake - Rotation is when you want it to face a specific way, spin is constant motion)

You would need a way to be able to upload PNG files or similar graphic files in accordance to what gobos were in your wheel.

**Comment by jholmes09** [comment]
> Have you read this page: #4260
> 
> I specifically mention gobos and using images in the ToDo section. I have a ton of work already invested in this ability but I inactivated it for now because it doesn't appear to be easily imported to other users unless they have the exact same head. I didn't want to put something out that was a mess. So I'm trying to think of an implementation that works when sequences get shared. Otherwise I can let you program all the extra special features of a head but we would be in the same situation we were before where those effect settings don't work for others.

Oh sorry! I did an issue search for Gobos but didn't find anything so I assumed this was a new issue to present.
Moving heads are always going to be a challenge because every light is slightly different from the other.
Ironically (considering the other thread we are chatting on), we often use presets to get around this :).

I will read the page you referenced and see if I can offer any insight on the matter.

**Comment by cybercop23** [comment]
Closing this as this is already planned as part of the main project. Add/update comments in the main discussion page as needed, with any info and feedback.
