### ISSUE TITLE
Add Aliases to Export Models Spreadsheet

### ISSUE THREAD

**Issue by ItsFitz** [xLightsSequencer/xLights#4566]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem.

**Describe the solution you'd like**
Please add a field in the Export Models spreadsheet containing a list of Aliases associated with each Model and Model Group.

**Why do I want this?**
Using the "Add Aliases" button on the Import Effects window could add a lot of possibly unwanted aliases to the models.  Looking at a complete list of aliases will help review aliases quicker than clicking the aliases button for each model or model group.  You could create a new pop-up window to manage aliases; but that is more effort.  I think reviewing aliases in a spreadsheet is good enough for me.

**Describe alternatives you've considered**
Clicking Aliases on every individual model and model group.  This takes a long time.

This is not a recommended alternative; but I could view/parse the xlights_rgbeffects.xml file.  Keith says "Don't do it!"

**Additional context**
The alias list could be it's own tab in the exported spreadsheet and formatted similar to the Models column in the Groups tab.

Thanks for considering this enhancement.
Fitz

**Comment by cybercop23** [comment]
Yup... this is something that we are considering. We now have aliases at all levels, groups, models and  submodels. so we need to find out if/how we should handle groups and submodels.

**Comment by cybercop23** [comment]
Will be available in the nightly build and next version.Will be available in the nightly build and next version.
