### ISSUE TITLE
Import custom model overlay

### ISSUE THREAD

**Issue by Strawberry1997** [xLightsSequencer/xLights#4569]
When importing a custom model onto a matrix, the main Custom model transfers properly but the submodels of the Custom transfer is skewed. 
This is the custom model on the matrix
<img width="466" alt="Screenshot 2024-05-18 at 3 17 16 PM" src="https://github.com/xLightsSequencer/xLights/assets/78796480/350a2146-97a2-4e8a-b78d-d2f7f2276e7a">

This is a submodel of the custom model imported onto a matrix.
<img width="339" alt="Screenshot 2024-05-18 at 3 17 31 PM" 
<img width="314" alt="Screenshot 2024-05-18 at 3 17 40 PM" 
src="https://github.com/xLightsSequencer/xLights/assets/78796480/723d3e53-987e-4cc1-8d5d-8afbbedf6e60">
<img width="339" alt="Screenshot 2024-05-18 at 3 17 31 PM" src="https://github.com/xLightsSequencer/xLights/assets/78796480/8f36f840-f268-48e2-8c7f-04bf148b6973">
using xlights 2024.10

**Comment by cybercop23** [comment]
Please provide the xmodel used to import the overlay.

**Comment by Strawberry1997** [comment]
[squares.xmodel.zip](https://github.com/xLightsSequencer/xLights/files/15366668/squares.xmodel.zip)
I did import to the center with the same results. These are the pics from the bottom left.

**Comment by Strawberry1997** [comment]
The import works perfect if there is only 1 strand per string. Try a matrix with 2 strands per string. 
This is the matrix I'm working with.

![Screenshot 2024-05-18 at 7 05 03 PM](https://github.com/xLightsSequencer/xLights/assets/78796480/6f6dbb29-cafa-4ba6-a1eb-87660c5448a5)

**Comment by cybercop23** [comment]
Okay.. I see it on a matrix as you have it defined. What sort of matrix is this? Is it really almost 18K pixels?

**Comment by cybercop23** [comment]
I see the issue, but I also question what this matrix really is. @ 17,952 hard to believe it is a pixel matrix.
Also the way you have you set up, currently, it is only 66 tall vs what you think you have of 68. That's causing part of the problem.
Need to understnad what this "thing" really is and make sure it is setup correctly, before we make any changes.

**Comment by Strawberry1997** [comment]
My numbers are a bit off. This is a matrix going on the side of a building. Once the matrix is built these submodels will be added. I tried it on a small matrix with 1 strand per string and it works great, the issue is when the strand per string is greater than 1.

**Comment by Strawberry1997** [comment]
The import does not calculate properly.
I made a new custom model and made a few submodels.
The custom model is proper when imported.
The submodels don't import properly.
Heres a quick model I made with submodels.
[Test traingle.xmodel.zip](https://github.com/xLightsSequencer/xLights/files/15448729/Test.traingle.xmodel.zip)

**Comment by Strawberry1997** [comment]
I'm using the latest Testflight version.

**Comment by cybercop23** [comment]
Does it work with the original model you were using?

**Comment by Strawberry1997** [comment]
This fixed the model that was originally in the matrix. But when I went to add it to another matrix it was messed up, so I made a new model to insert into the matrix and it didn't transfer correctly.
