### ISSUE TITLE
Fire Effect - per Preview crashes 2024.10

### ISSUE THREAD

**Issue by brett-foy** [xLightsSequencer/xLights#4574]
[xLights_dbgrpt-48176-20240520T162816.zip](https://github.com/xLightsSequencer/xLights/files/15381906/xLights_dbgrpt-48176-20240520T162816.zip)
**Describe the bug**
With 2024.10, on multiple sequences, I am experiencing frequent crashes.   9/10 times there is no debug package, but got one today.  It would appear that the issue from my experience checking this file and previous logs is that there is an exception when rendering a fire effect w/ value curve on the height that is also a "per preview" render style.  Not sure if the value curve on heights plays a role, but all of the effects I have seen render cause crash on have had this value curve.

**To Reproduce**
open sequence, render - crash happens in seconds

**Expected behavior**
Rendering to work, no crash

**Screenshots**
no screenshot, crash report attached

**Versions (please complete the following information):**
Windows 11, w/ Nvidia  GPU enabled (tried it with and without nvidia FFPMeg configured)
xLights 2024.10

**Additional context**

**Attachments**
- Crash report attached
- PM me for sequence

Thanks!

**Comment by cybercop23** [comment]
Can you create a new sequence and palce that effect with all the settings on one model and see if it crases. If, so,  please upload that simple sequence.. don't really need the full/final sequence if you can reproduce with one effect on one model.

**Comment by brett-foy** [comment]
i love things that reproduce.   see bug report attached, crashed when I added the third copy of the fire effect 
[xLights_dbgrpt-29656-20240520T165840.zip](https://github.com/xLightsSequencer/xLights/files/15382078/xLights_dbgrpt-29656-20240520T165840.zip)

**Comment by brett-foy** [comment]
here it is with sequence saved.  the crash happened right after I added the twinkle effect under the fire effect on the mega tree left front.  so not sure if its a layers thing also. 

easy fix is to not use per preview on the models, never happens if I do that.

![image](https://github.com/xLightsSequencer/xLights/assets/152660997/88acbab3-275c-4b84-a7c2-fb8632ecd48d)
[xLights_dbgrpt-39276-20240520T170327.zip](https://github.com/xLightsSequencer/xLights/files/15382097/xLights_dbgrpt-39276-20240520T170327.zip)

**Comment by derwin12** [comment]
Easily duplicated .. perhaps related to
https://github.com/xLightsSequencer/xLights/commit/51da6dc8d837c812e1663add3c20a82ddeee71d0

**Comment by derwin12** [comment]
The y value goes beyond the size of the FireBuffer vector.
`int GetFireBuffer(int x, int y, std::vector<int>& FireBuffer, int maxWi, int maxHi)`

maxWi=423, maxHi=726, **size=305829**
The FireBuffer is only 723*423=305829

**Comment by brett-foy** [comment]
I have noticed that the value curve seems to break at about 80% when the height curve gets to ~80% the effect just jumps to top of model.  May be related?

Sent from my iPhone

On May 21, 2024, at 11:38 AM, Daryl ***@***.***> wrote:

﻿

The y value goes beyond the size of the FireBuffer vector.
int GetFireBuffer(int x, int y, std::vector<int>& FireBuffer, int maxWi, int maxHi)

maxWi=423, maxHi=726, size=305829
The FireBuffer is only 723*423=305829

**Comment by derwin12** [comment]
@dkulp  Dan something about this cached buffer .. it is not the right size.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/7f643a1e-f765-47b6-acd8-f27e4dc64a8a)

**Comment by cybercop23** [comment]
2 out of 3?

**Comment by dkulp** [comment]
GetMaxBuffer is also fairly expensive for "Per Preview" render styles.  Thus, calling it every frame is not ideal anyway.  I just pushed a change that only grabs the "max" during init and saves that for use with rendering the rest of the frames.   This is faster as well as  should provide consistency.

**Comment by cybercop23** [comment]
@brett-foy you can grab that in the nightly and test it and will be avail in the next version.

**Comment by brett-foy** [comment]
testing looks good.   also coincidentally fixed the value curve jump issue I mentioned above.   thanks team!
