### ISSUE TITLE
Model Preview placing last copied model on top of previous model in 2D

### ISSUE THREAD

**Issue by bravado67** [xLightsSequencer/xLights#4579]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

I am using Test Flight,
<img width="659" alt="Works in 3D" src="https://github.com/xLightsSequencer/xLights/assets/26886017/8a93aee5-462a-46b9-a399-99e71c1272bf">
 so this is from 2024.10.1.
The screenshot shows that the last of the three copied models places itself over the previous model. It looks normal in House Preview. This is in 2D.
In 3D it works as expected.
<img width="937" alt="Model Prveview Issue" src="https://github.com/xLightsSequencer/xLights/assets/26886017/68a28feb-4e3e-40f9-9808-9966b28d9074">

**Comment by bravado67** [comment]
Fixed. Thank you.

**Comment by cybercop23** [comment]
User error......

**Comment by bravado67** [comment]
It was there. I took screen shots. I was training so 37 people in the UK
saw it happen. An update happened and it was working. User error my ass.

**Comment by cybercop23** [comment]
You welcome. There was no update that would have done anything. So.. there's that.

**Comment by bravado67** [comment]
You know... I try to report something in Github and get attitude from you.
I try to help and you are an ass to me. I won't make the mistake again.
