### ISSUE TITLE
Controllers View Oddness

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#4583]
Windows.  1 annoyance and 1 relatively minor issue, but an issue nonetheless.  Tested in the latest nightly as well.

1.  The Controller page view is kind of wonky on how it's sizing the 2 grids.   When first opened, it looks like the picture below (this was tested after encountering the bug below so it's possible this won't be an issue when the bug is resolved).  Seems backwards, where the left should get 2/3 of the screen and the right should get the rest.  Even better would be the left only being sized as large as the columns require and the right getting the rest.  My window opens up maximized so that may play into it as well.  Kind of a hard issue to duplicate manually but I'm guessing there is some odd code telling the boxes how to size when the window is opened/resized.  Figured maybe it's something to look at as it's kind of an unpredictable behavior.

![image](https://github.com/xLightsSequencer/xLights/assets/25715814/ea85e744-5a52-4dcd-8cce-778431df881a)

2.  If you double click the splitter bar between the grids, the right grid disappears forever....never to be seen again.  If there's some magic way to bring it back, it is not obvious at all.  Why would you double click that bar, you ask......   You wouldn't.....but if you do.....you did.....and it's done.  😁  Expected behavior would be for double clicking to do nothing, but an alternative might be to resize the left side large enough to show the left grid columns (we all have wide screen monitors now, right?) or 75-80% of the screen, whichever is smaller.

**Comment by cybercop23** [comment]
#1 part of this.. https://github.com/xLightsSequencer/xLights/discussions/4541
#2 seems to be an xWidgets issue, but with the planned changes in #1 and not being able to move it, it should not happen.
Closing since this is aready in the planning/work stages.

**Comment by derwin12** [comment]
Double click of the splitter is a wxWidgets "feature" .. I see others code around that. I bet this happens in a number of places.. (eg. submodel dialog)

**Comment by kevinsaucier** [comment]
> #1 part of this.. #4541 #2 seems to be an xWidgets issue, but with the planned changes in #1 and not being able to move it, it should not happen. Closing since this is aready in the planning/work stages.

Well, damn, guess I should have searched a bit before taking all that time to test/post.  🤦‍♂️

**Comment by kevinsaucier** [comment]
> Double click of the splitter is a wxWidgets "feature" .. I see others code around that. I bet this happens in a number of places.. (eg. submodel dialog)

Love those kinds of 'features' that make no sense.  🤦‍♂️
