### ISSUE TITLE
Wiring View: Export Wiring view as DXF is missing!

### ISSUE THREAD

**Issue by SniperMunyShotz** [xLightsSequencer/xLights#4586]
I  was trying to export a wiring view as DXF and the option is missing, is that getting put back in?

**Comment by cybercop23** [comment]
No, that's not longer available.

**Comment by computergeek1507** [comment]
I have made a DXF to xModel generator as part of my masters research. It has a function to find/generate wiring paths. It's not very useful to an average user so I mostly abandon it.
