### ISSUE TITLE
Useless Feature Request In / Out Transition drop down sort to alphabetical

### ISSUE THREAD

**Issue by JoelDearing** [xLightsSequencer/xLights#4587]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
within the layer blending window, for the in transition and out transition tabs, can the drop down selection that shows fade, wipe, clock, and so on be put in alphabetical order?

**Describe alternatives you've considered**

**Additional context**

**Comment by cybercop23** [comment]
Should be available in the nightly and next version.
