### ISSUE TITLE
Middle Mouse Button Functionality for Sequencer Navigation.

### ISSUE THREAD

**Issue by ak463010** [xLightsSequencer/xLights#4593]
Subject: Feature Request - Middle Mouse Button Functionality for Sequencer Navigation

Dear xLight Team,

I hope this message finds you well. I am writing to suggest a new feature that I believe would significantly improve the user experience in our sequencer.

**Feature Description:**
I propose the implementation of a feature that allows users to navigate around the sequencer using the middle mouse button. This would involve clicking and holding the middle mouse button and then moving the mouse to pan around the sequencer.

**Benefit:**
This feature would provide a more intuitive and efficient way for users to navigate large and complex sequences. It would align with common practices in many other software applications, making our sequencer more user-friendly, especially for new users.

**Implementation:**
While I do not have a detailed understanding of our codebase, I believe this feature could be implemented by capturing the middle mouse button click event and translating the subsequent mouse movements into sequencer navigation commands.

I look forward to hearing your thoughts on this proposed feature. I truly believe that it would be a valuable addition to our sequencer.

Best regards,
Avinash Kumar

**Comment by cybercop23** [comment]
Should be available in the nightly and next version.
