### ISSUE TITLE
Tools Prepare Audio is failing..

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4611]
Something that was used back in xLights Around the world - reaper and mp3. Seems it is no longer working.
Investigating the cause..
[01 The Greatest Show Google Play.RPP.txt](https://github.com/user-attachments/files/15826732/01.The.Greatest.Show.Google.Play.RPP.txt)

**Comment by derwin12** [comment]
Its working with the commit/PR *but* I have found that the resulting file is now larger as it is a .wav file in disguise. Using "mp3" fails - so still looking for the perfect solution here.

**Comment by cybercop23** [comment]
@keithsw1111 is this something you can help us with? The audio file gets converted from MP3 -> WAV and it is 10x+ larger than the original file. We definetely need to keep it as an MP3.
