### ISSUE TITLE
Two folks saying  .11 wont start in Windows .. 

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4617]
The logo shows (atleast 1 user is dark mode) then quits.
Not sure how to troubleshoot.
Going to rollback to .10 and see if log shows anything.

(works fine for me btw).
Daryl.

**Comment by derwin12** [comment]
Crashing after the GL panel
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/af5471ef-8008-4313-b425-1b22052b0158)

**Comment by derwin12** [comment]
[xLightsProblem.zip](https://github.com/user-attachments/files/15855693/xLightsProblem.zip)

**Comment by derwin12** [comment]
Tried /w .. still not working.
Crashing on this. This is from my log .. it doesnt appear in the reporting user's log (Joe).

`**"2024-06-15 20:13:00,040 29484 log_base [DEBUG]         Effect assist."**`

**Comment by derwin12** [comment]
Ron R. crashed in a slightly different spot...
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/6506cb5e-6840-4283-b083-ccf0cd2718d2)

**Comment by derwin12** [comment]
Yea no crash dump just stops.

**Comment by derwin12** [comment]
Third one reported..

**Comment by computergeek1507** [comment]
If you have someone that doesn't work on 11 do a package sequence on 10 and upload it

**Comment by derwin12** [comment]
The package logs was from 10. I think two of them were on 10. I am on 10
without issue.

**Comment by xlights33** [comment]
This is a test sequences [packaged]([2024.10.zip](https://github.com/user-attachments/files/15855842/2024.10.zip)) from 2024.10

**Comment by xlights33** [comment]
> If you have someone that doesn't work on 11 do a package sequence on 10 and upload it

[2024.10.zip](https://github.com/user-attachments/files/15855845/2024.10.zip)

**Comment by blun23** [comment]
I'm on the TestFlight on Mac and I am having issues saving a sequence.  Beachball is just spinning after doing the latest update

**Comment by derwin12** [comment]
Duplicate #4618

**Comment by geoffhoops** [comment]
I am having the same problem with the new version .11. The logo flashes up briefly then nothing. the Scheduler and Scanner do exactly the same, nothing happens. Go back to version .10 and everything is fine. reinstall .11 and nothing happens again.

**Comment by keithsw1111** [comment]
> [2024.10.zip](https://github.com/user-attachments/files/15855843/2024.10.zip) This is a test sequences packaged from 2024.10 (Joe)

Downloaded and opened your sequence
![image](https://github.com/xLightsSequencer/xLights/assets/10283944/0484638e-b893-45af-87d3-5c16cd2ffab0)

So if the crash is not specific to your show folder it is going to be down to settings or something else environmental. The only way to troubleshoot may be builds with additional debugging until we isolate the issue.

Looking at the log above in daryls post there is a lot that happens after that log message. In my log the first thing i see is a message about the download cache ... purging the download cache in .10 and re-upgrading to 11 may help ... but equally may not.

**Comment by derwin12** [comment]
Folks having problems, could you verify that this nightly works No. 924
https://github.com/xLightsSequencer/xLights/actions/runs/9378451618
And this one does not..  No. 925
https://github.com/xLightsSequencer/xLights/actions/runs/9395371749

**Comment by derwin12** [comment]
Agree ,.. but need to start somewhere. Ideally we get a second or third confirmation on these commits.
Then put in some debugging and track it down.

**Comment by xlights33** [comment]
> Folks having problems, could you verify that this nightly works No. 924 https://github.com/xLightsSequencer/xLights/actions/runs/9378451618 And this one does not.. No. 925 https://github.com/xLightsSequencer/xLights/actions/runs/9395371749

924   worked  
925 same as 2024.11 just flash startup screen

**Comment by computergeek1507** [comment]
924 was build using the 20240511 Windows github action image, which used the VS2022 17.9 MSBuild compiler. 925 used the newer 20240603 Windows github action image, which used the VS2022 17.10 MSBuild compiler. Maybe a optimization bug in VS2022 17.10. If Keith used 17.10 his release may have the same issue.

**Comment by computergeek1507** [comment]
try installing the newest C++ Redistributable with VS 17.10/ C++14.40 support 

https://aka.ms/vs/17/release/vc_redist.x64.exe
