### ISSUE TITLE
Upgrade to 2024_11 flashes the logo quickly, then nothing.  Reverted back to

### ISSUE THREAD

**Issue by wnartles** [xLightsSequencer/xLights#4618]
Upgraded to 2024_11 flashes the logo quickly, then nothing.  Reverted back to 2024_10.  worked fine.  Restarted windows 10, updated to _11 two more times and same instantly the splash screen goes down.  Can't do any testing since it won't start.  I know its not much info, but that's all I can provide.  Lots of these in Event Manager:

Log Name:      Application
Source:        Application Error
Date:          6/15/2024 10:18:22 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      The-Matrix
Description:
Faulting application name: xLights.exe, version: 0.0.0.0, time stamp: 0x666e1697
Faulting module name: ntdll.dll, version: 10.0.19041.4522, time stamp: 0x8a1bb6f3
Exception code: 0xc0000005
Fault offset: 0x00000000000290a2
Faulting process id: 0x3e30
Faulting application start time: 0x01dabf9bd7964cff
Faulting application path: C:\Program Files\xLights\xLights.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 7048f98b-9788-4b69-9b9d-d9992f1193b3
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-06-16T03:18:22.9466844Z" />
    <EventRecordID>209475</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>The-Matrix</Computer>
    <Security />
  </System>
  <EventData>
    <Data>xLights.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>666e1697</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.19041.4522</Data>
    <Data>8a1bb6f3</Data>
    <Data>c0000005</Data>
    <Data>00000000000290a2</Data>
    <Data>3e30</Data>
    <Data>01dabf9bd7964cff</Data>
    <Data>C:\Program Files\xLights\xLights.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>7048f98b-9788-4b69-9b9d-d9992f1193b3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          6/16/2024 12:22:01 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      The-Matrix
Description:
Faulting application name: xLights.exe, version: 0.0.0.0, time stamp: 0x6632140b
Faulting module name: ntdll.dll, version: 10.0.19041.4522, time stamp: 0x8a1bb6f3
Exception code: 0xc0000005
Fault offset: 0x00000000000a74e5
Faulting process id: 0x3138
Faulting application start time: 0x01dabfacf3b1f47f
Faulting application path: C:\Program Files\xLights\xLights.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: b98fb1ab-0af1-4af3-883c-87b2be0ce179
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-06-16T05:22:01.4119219Z" />
    <EventRecordID>209578</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>The-Matrix</Computer>
    <Security />
  </System>
  <EventData>
    <Data>xLights.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6632140b</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.19041.4522</Data>
    <Data>8a1bb6f3</Data>
    <Data>c0000005</Data>
    <Data>00000000000a74e5</Data>
    <Data>3138</Data>
    <Data>01dabfacf3b1f47f</Data>
    <Data>C:\Program Files\xLights\xLights.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>b98fb1ab-0af1-4af3-883c-87b2be0ce179</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Devs - I had RonR check some nightys for me.
#925 hang and quits
#924 works and a couple prior as well.
So need to check into the commits on that day.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/44b620ed-f8ec-47a7-bb4e-9184654a0be6)

**Comment by derwin12** [comment]
June 5 to 6th 
The only change I see is the reversal of the sketch panel. Cant see that being dangerous.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/a09de41f-5b4e-46a1-9de0-6058b000391b)

**Comment by derwin12** [comment]
Could be users that have never opened the new moving head effect? Is that panel perhaps not initialized for them?
`wxSize old_sz = m_sketchCanvasPanel->GetSize();`

**Comment by NaterDog2020** [comment]
Having the same issue, but works fine when reverted back to Version 10.

**Comment by derwin12** [comment]
Folks having problems, could you verify that this nightly works No. 924
https://github.com/xLightsSequencer/xLights/actions/runs/9378451618
And this one does not.. No. 925
https://github.com/xLightsSequencer/xLights/actions/runs/9395371749

**Comment by daroyaci** [comment]
Same issue here as well, quick flash of logo and then nothing. But 10 works fine like it always did.
i will verify if the nightly above works later today and report back with findings.
Thanks

**Comment by NaterDog2020** [comment]
Ok, I will try those fixes, when I get the chance, and report back. Will be a couple hours.

**Comment by derwin12** [comment]
Joe tried his show folder on a new install and it worked. Still trying to track this down. We have a couple more folks in zoom trying to narrow this down.

**Comment by MrPierreB** [comment]
I know this is a long show, but can somebody who's it crashes for download and install .11 from github.
Might not work, but worth a try.  I downloaded the .11 from xlights.org and then also downloaded .11 from github. The SHA256  hash doesn't match between the 2 files.

**Comment by derwin12** [comment]
Narrowed down to this code in the layout
`model_grp_panel = new ModelGroupPanel(sw, xlights->AllModels, this);`

**Comment by cybercop23** [comment]
> I know this is a long show, but can somebody who's it crashes for download and install .11 from github. Might not work, but worth a try. I downloaded the .11 from xlights.org and then also downloaded .11 from github. The SHA256 hash doesn't match between the 2 files.

They won't. Keith rebuilds it for Windows and then loads it. We have an open requet for some missing files to be looaded in Git so we can build and *only* use Git.  @keithsw1111

**Comment by cybercop23** [comment]
> Someone with failures should try renaming their show folder so that xLights starts up fresh and see what happens.

Fresh folder using /w and still ends. It ends even before asking for a new show folder.

**Comment by computergeek1507** [comment]
try installing the newest C++ Redistributable with VS 17.10/ C++14.40 support

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by NaterDog2020** [comment]
Ok, when i installed the newest C++ Redistributable it worked! 
 Thanks @computergeek1507 !

**Comment by cybercop23** [comment]
@dkulp @keithsw1111 what is the path forward for this fix? Can we recompile the windows version and repost and those that alreay have upgrade can use the above link? Or is it better/faster to just cut 12? There are a lot of changes in 11 and has been almost 2 months and I don't think we should wait until a "full 12" is released.

**Comment by computergeek1507** [comment]
> I thought the Windows installer prompted users to install the C++ redistributable so maybe its just making sure its suggesting the right version.

The version Included in the repo used by the installer is a couple years old. I hope to update the installer to download the newest

**Comment by xlights33** [comment]
> installed the newest C++ Redistributable with VS 17.10/ C++14.40 support  and now able to start 2024.11 
Joe

**Comment by keithsw1111** [comment]
I have updated the xlights download with the latest vc runtime

**Comment by keithsw1111** [comment]
> > I know this is a long show, but can somebody who's it crashes for download and install .11 from github. Might not work, but worth a try. I downloaded the .11 from xlights.org and then also downloaded .11 from github. The SHA256 hash doesn't match between the 2 files.
> 
> They won't. Keith rebuilds it for Windows and then loads it. We have an open requet for some missing files to be looaded in Git so we can build and _only_ use Git. @keithsw1111

What files are you missing?

**Comment by cybercop23** [comment]
@keithsw1111 Git is missing the SMPTE libs, thus Scott can't build and include xSchedule. I know there are some logistics issues to work out, but will help us with getting nightly/beta versions to users for more hands on testing. See https://github.com/xLightsSequencer/xLights/discussions/4501

**Comment by keithsw1111** [comment]
Its here: https://github.com/keithsw1111/libltc

**Comment by cybercop23** [comment]
Thank you very much @keithsw1111 .
@computergeek1507  will this work? Guess we have to clone and refresh or just pull each time?
