### ISSUE TITLE
.11 Crash

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4622]
While going thru the new features .. it crashed. I havent tracked it down but will see if I can narrow it down. Here are the logs
[xLightsProblem.zip](https://github.com/user-attachments/files/15887484/xLightsProblem.zip)
[xLights_dbgrpt-14384-20240618T093839.zip](https://github.com/user-attachments/files/15887485/xLights_dbgrpt-14384-20240618T093839.zip)

Autosave?
Walking from an exception.
[01]	ADDR:0x00007ff7eb966c62	HMODULE:0x00007ff7eac30000	0000000000d346a0	xLightsXmlFile.obj	?Save@xLightsXmlFile@@QEAAXAEAVSequenceElements@@@Z@AE2D52 
[02]	ADDR:0x00007ff7eb9065f0	HMODULE:0x00007ff7eac30000	0000000000cd5e00	xLightsMain.obj	?SaveWorking@xLightsFrame@@QEAAXXZ@A826E0 
[03]	ADDR:0x00007ff7eb906942	HMODULE:0x00007ff7eac30000	0000000000cd67c0	xLightsMain.obj	?OnTimer_AutoSaveTrigger@xLightsFrame@@QEAAXAEAVwxTimerEvent@@@Z@A82A32

**Comment by derwin12** [comment]
It seems the .zip file contains the old prior existing _.xbkp file. Perhaps it couldnt write out the contents to .xbkp and crashed?

**Comment by derwin12** [comment]
Since I was making a bad .11 video at the time .. I have included that for your entertainment :-)
Shows the exact process I went thru - but I am leaning towards some sort of hiccup writing to the drive?
https://github.com/xLightsSequencer/xLights/assets/4643499/ed4840e2-f8a1-44cc-ac20-9be6442b7dd0

**Comment by cybercop23** [comment]
2nd time in a row....

2024-06-18 10:41:17,144 8603012096 log_base [DEBUG] Autosaving backup of sequence.
2024-06-18 10:41:17,145 8603012096 log_base [CRIT] Crashed: Fatal exception occurred.

**Comment by cybercop23** [comment]
Doesn't crash if you skip renaming /Edit Layer Name a submodel....

**Comment by derwin12** [comment]
Narrowed it down .. expand a model (Showstopper spinner). Rename the first (only) layer on any submodel. Hit Save.
This crashes as effect_layer_node is still null;
`effect_layer_node->AddAttribute("layerName", layer->GetLayerName());`

**Comment by derwin12** [comment]
This appears to fix it but leave to Dan to code/confirm.
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/722fdad5-2ff6-4f71-b314-32a6120629fd)

**Comment by blun23** [comment]
> I can follow your steps using your folder and I get beach-balling on Mac, no crash, but locked up. Will kill it and Dan will get logs.

If I'm having an issue and I kill it, how would I get the logs to send to you guys?  Or is it automatic when you force quit

**Comment by derwin12** [comment]
Dan commited fix.

**Comment by blun23** [comment]
> > > I can follow your steps using your folder and I get beach-balling on Mac, no crash, but locked up. Will kill it and Dan will get logs.
> > 
> > 
> > If I'm having an issue and I kill it, how would I get the logs to send to you guys? Or is it automatic when you force quit
> 
> No need for this one. We have all that we need. Thanks for the offer.

I'm fairly good at crashing things when need to.
