### ISSUE TITLE
Change Pop up from Abandon Changes to Save Changes

### ISSUE THREAD

**Issue by Jaa1i** [xLightsSequencer/xLights#4629]
When editing model data, and you press cancel, a prompt asks "Abandon Changes" with the option of No or Yes.

This is vastly different to standard practice with pretty much all computer applications. When attempting to close something without saving, it will ask "Do you want to save changes?" not "Abandon Changes".

I can see someone inadvertently pressing yes, thinking they are saving changes.

<img width="293" alt="Screenshot 2024-06-22 at 23 03 21" src="https://github.com/xLightsSequencer/xLights/assets/50488459/e02f400f-d748-4b07-b66e-1a8c08d64790">

**Comment by Jaa1i** [comment]
Yes, if you press OK, it saves. However if you press Cancel, you receive the Abandon Changes pop up. This is not the industry norm. In almost all other applications, if you close a document that you have not saved changes, it doesn't ask you if you wish to Abandon Changes, it asks if you want to save your changes.

**Comment by computergeek1507** [comment]
The import and Submodel dialog have the same reverse logic questions on close, I thinks it is because everything is upside down and backwards in Australia
