### ISSUE TITLE
Import submodels to differently wired copy of a prop

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#4631]
So, I'm 'fixing' some incorrect wiring on props and it occurs to me that it would be possible to import the submodels from one prop into another, assuming the renumbered pixels are in the same place as the pixels in the original prop.  For instance, if you take prop A with an OEM wiring diagram, then copy it and create prop B and customize/fix the wiring diagram.   All is fine and dandy till you look at the submodels/faces/states.  But, in reality, the data needed for the submodels is available in prop A by looking at the grid coordinates of pixel 1, pixel 2, pixel 3, etc.  If pixel one is Row 3 Column 7 on prop A and pixel 14 is Row 3Column 7on Prop B, all we need to do is switch each pixel in the submodel from pixel 1 to pixel 14.  

Of course, if prop B had pixels in a different place than prop A, that messes up the whole thing, though a list could be generated to note that prop B doesn't have a pixel in Row 3 Column 7 so you could see what was different (or allow you to choose a pixel number to map to it on the fly, but that makes it more complicated).  

Seems that 'fixing' wiring/submodels is a common issue that could be helped by going this route.  I was just about to see if I could do it via PowerShell but it would obviously be easier and more accessible to do it in xLights itself.  :)

**Comment by keithsw1111** [comment]
This already exists in the tools menu.
Sent from my iPhone

On 25 Jun 2024, at 7:16 AM, Kevin Saucier ***@***.***> wrote:

﻿

So, I'm 'fixing' some incorrect wiring on props and it occurs to me that it would be possible to import the submodels from one prop into another, assuming the renumbered pixels are in the same place as the pixels in the original prop. For instance, if you take prop A with an OEM wiring diagram, then copy it and create prop B and customize/fix the wiring diagram. All is fine and dandy till you look at the submodels/faces/states. But, in reality, the data needed for the submodels is available in prop A by looking at the grid coordinates of pixel 1, pixel 2, pixel 3, etc. If pixel one is Row 3 Column 7 on prop A and pixel 14 is Row 3Column 7on Prop B, all we need to do is switch each pixel in the submodel from pixel 1 to pixel 14.

Of course, if prop B had pixels in a different place than prop A, that messes up the whole thing, though a list could be generated to note that prop B doesn't have a pixel in Row 3 Column 7 so you could see what was different (or allow you to choose a pixel number to map to it on the fly, but that makes it more complicated).

Seems that 'fixing' wiring/submodels is a common issue that could be helped by going this route. I was just about to see if I could do it via PowerShell but it would obviously be easier and more accessible to do it in xLights itself. :)

**Comment by kevinsaucier** [comment]
> This already exists in the tools menu.

Ahhh, you are correct, of course.  I looked around but didn't think to look in the tools menu.  Thanks for the point.
