### ISSUE TITLE
Bulk Edit missing in Layout Tab, from the right-click menu

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4632]
In previous verisons of xLights, when a group was selected, you could right-click over the models in the layout screen and see a BULK EDIT function available.  In 2024.11.1 it doesn't appear to be there any longer.  We use this to quickly edit the size of pixels.

Can you please fix this?

Thank you for looking,
Clyde L 
 
 
![image](https://github.com/xLightsSequencer/xLights/assets/12719816/d725877e-4323-440f-b7b0-7d8702fa72bf)

**Comment by computergeek1507** [comment]
Daryl broke it in b7b0ff6e170713e2d37290cf93b6f468e8e85fd7

**Comment by derwin12** [comment]
Is the center plus thing still working if you reverse my change?

**Comment by derwin12** [comment]
It looks like the center thing is working - but perhaps its just the action build, it crashes after I set the center a few times.
[xLights_dbgrpt-16068-20240624T214949.zip](https://github.com/user-attachments/files/15963399/xLights_dbgrpt-16068-20240624T214949.zip)
[xLights_dbgrpt-23672-20240624T214548.zip](https://github.com/user-attachments/files/15963400/xLights_dbgrpt-23672-20240624T214548.zip)
