### ISSUE TITLE
When uploading output to Genius controller pixel count incorrect for unused ports

### ISSUE THREAD

**Issue by horathgar2000** [xLightsSequencer/xLights#4639]
**Describe the bug**
On a Genius Long Range Controller with Smart Remotes A and B. If you have no Models on either output it registers as 1 on the controller. If you have a Model on Controller A1 with 50 nodes and nothing on A2 it duplicates 50 on both A1 and A2. The Channels are correct but this may impact the performance "Frames Per Second" of the output of the controller?
Also If you have Smart Remote A,B,C and Models on A, C but not B then it duplicates the last model from B to C.
Finally DMX has an output of 1 on each port when no models assigned. 
The controller is reporting over 1000 nodes on a port and therefore would run at 20Fps and not 40Fps as I keep the ports to a maximum of 799 nodes per port. The starting and ending channels are correct for each Model that actually exists in Xlights.
Please see attachments

**To Reproduce**
Assign models to a port on a Genius Long Range Controller, Put one on Smart Remote 1A and the second one on 2B.
Upload Output to controller and check configuration on controller.

**Expected behavior**
Unused ports I would expect to see a 0 on that port.

**Screenshots**

**Versions (please complete the following information):**
Windows Versions tested.
xLights64_2024_12_nightly-db472d2
xLights64_2024_12
xLights64_2024_11
xLights64_2024_10
xLights64_2023_23

**Additional context**
![Screenshot 2024-06-27 193003](https://github.com/xLightsSequencer/xLights/assets/58126819/b11cceaa-af94-465a-b23f-6013cd31ea9c)
![Screenshot 2024-06-27 192658](https://github.com/xLightsSequencer/xLights/assets/58126819/f4db30de-4277-4091-8cb3-9019983347ea)
![Screenshot 2024-06-27 192800](https://github.com/xLightsSequencer/xLights/assets/58126819/e61fc27e-6e51-4e64-931a-e53651e88328)
![Screenshot 2024-06-27 193030](https://github.com/xLightsSequencer/xLights/assets/58126819/cef5a812-8928-4884-a4a3-92407edfbc90)

**Attachments**

**Comment by derwin12** [comment]
We can duplicate this .. only comes into play on multiple receivers (that we tested)

**Comment by derwin12** [comment]
@computergeek1507  Scott would this be from the push or the way the genius receives this port request?

**Comment by AGFazio** [comment]
Can duplicate on recievers attached to 2023 Genius 16 as well.

**Comment by derwin12** [comment]
@computergeek1507  I think you need to zero out the pixel count here
![image](https://github.com/xLightsSequencer/xLights/assets/4643499/9698d423-f35e-4e58-a648-4e1b8c8f9625)

**Comment by computergeek1507** [comment]
Can you send me the layout to test it

**Comment by horathgar2000** [comment]
Here is my current layout
[House-Layout.zip](https://github.com/user-attachments/files/16042445/House-Layout.zip)

**Comment by derwin12** [comment]
Scott . Andy is in Zoom and can test/duplicate as well.

**Comment by computergeek1507** [comment]
Looking at the code it looks like it only happens when Full xLights Control is enabled

**Comment by AGFazio** [comment]
@computergeek1507 If I turn off full xlights control, I can't upload outputs to the controller. States failed to connect.

**Comment by computergeek1507** [comment]
I think CreateVirtualStrings needs to be called with true instead of false.

**Comment by computergeek1507** [comment]
are you running firmware 1.1.8 or 1.3.1?

**Comment by AGFazio** [comment]
I am running 1.3.1

**Comment by horathgar2000** [comment]
v1.3.1-2 is what I am currently running.
I just tested v1.1.8-0 with the same result

**Comment by cybercop23** [comment]
I think Scott fixed this last week. Please test and close if issue is resolved.

**Comment by horathgar2000** [comment]
The problem still exists

**Comment by derwin12** [comment]
@cybercop23 We took a look on Andy's view log . The notes, is this how it should work?
![image](https://github.com/user-attachments/assets/243ebe2c-4f88-4385-8d29-2d0a25a8ddfe)

**Comment by derwin12** [comment]
@computergeek1507 Adding Scott back ...

**Comment by horathgar2000** [comment]
Something I just noticed.
2 Receivers -  Nodes A=100 B=0 uploaded output = A=100 B=100
2 Receivers - Nodes A=0 B=100 uploaded output = A=0 B=100
3 Receivers - Nodes A=100 B=0 C=100 uploaded output A=100 B=0 C=100
3 Receivers Nodes A=100 B=0 C=0 uploaded output A=100 B=100 C=100
In my mind if there are no nodes after the proceeding smart receiver with nodes it is filling in the last known non 0 value.
If the last Smart Receiver has nodes on it since the value is not 0 then it does not copy the previous non 0 value to the other receivers.

**Comment by computergeek1507** [comment]
Fixed with #5a1aaa1
