### ISSUE TITLE
Base Layout Folder props different color

### ISSUE THREAD

**Issue by bsmith76s** [xLightsSequencer/xLights#4641]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
When using the base Folder in another folder the props in the layout tab should be a different color when selected. 
**Describe alternatives you've considered**

**Additional context**
This would just give me a quick reference that these are Base folder props and can only be edited in the Base folder. An example would be if I needed to add sub models to a Base folder prop. I could see this is a Base folder prop by the different color.

**Comment by cybercop23** [comment]
They are... .in 2D the 4 corners and "moving" arm are purple and in 3D the entire object selector outline is purple.

**Comment by bsmith76s** [comment]
I didn't notice. I see it now that is super helpful. First year using Base folder.

**Comment by bsmith76s** [comment]
Thank you
