### ISSUE TITLE
Keep focus on Model - Edit Display Elements

### ISSUE THREAD

**Issue by Darzoom** [xLightsSequencer/xLights#4644]
There is no issue.  This is an enhancement request to allow to keep focus on Model from the sequence models list when you open edit display elements and take the edit display list to the focused model.

**Comment by derwin12** [comment]
I tried to implement this but it seems it isn't "easily" achieved. Since we draw the display element pane independently there is no changing focus over to it unless you click on that window - that sort of defeats the purpose of the request.
