### ISSUE TITLE
Multiple text effects cause re-render 

### ISSUE THREAD

**Issue by bobreese** [xLightsSequencer/xLights#4646]
I have a simple 10 minute Non-music sequence with 1 picture and multiple text effects.
A full render takes about 110 seconds.
Problem is, if I click on one of the text effects, the sequence gets rendered again, click on another one, and its blank until the rendering has completed (again about 110 seconds).
I have done
Render - Save
Tried multiple options for Hardware Video Decoding including Disabling it.

I understand I can always click the Suspend Render, but do not understand why clicking a text effect without making any changes causes it to re-render over and over again.
I am including the sequence, Xlights log file, and 2 screenshots.
Thanks for the time.

![Screenshot 01](https://github.com/xLightsSequencer/xLights/assets/461610/63868e4c-36a7-4e5d-a6a1-f162926779b5)
![Screenshot 02](https://github.com/xLightsSequencer/xLights/assets/461610/72c71053-a7c2-410a-bf1f-ce8b41905960)
[Stone Cronies.zip](https://github.com/user-attachments/files/16142986/Stone.Cronies.zip)
[xLights_l4cpp.log](https://github.com/user-attachments/files/16142988/xLights_l4cpp.log)

**Comment by bobreese** [comment]
I have even purged the render cache, closed XLights, reopened the sequence.
Did a Full render, saved.
And it still does it....
If you look at my Task Manger screenshot, its not like I dont have the CPU to do this yet it takes a long time...

**Comment by cybercop23** [comment]
Tried this on TestFlight .. it is a 10 min seq on a VM 256x384 with full render of 38 seconds. It has 4 sections of layered text (3 min, 3min 2 & 2). What's interesting is that when you click on any of the effects in the first section it shows up instanteneous. The other 3 go through a full 30+ sec rerender before they show up (less if you remove the image that's accross the entire duration).

**Comment by keithsw1111** [comment]
Because of the image clicking on a text effect will render the entire duration of the image which is likely the whole song. If this model is also in a group with effects then that will also render ... and before you know it the whole sequence is re-rendering. I like to call it render inflation.

I have often thought about implementing partial time rendering of effects but these days few effects support it and even if they do some settings effectively would stop it working. Interestingly render cache would allow for it but i dont think i ever tried to make that work.

**Comment by bobreese** [comment]
There are no groups involved in this sequence.
Just the Text Effects and the one picture..... 
This is for a P5 panel only and no music.

**Comment by keithsw1111** [comment]
Ok ... but that doesnt change anything ... the reason i stated remains true.

**Comment by cybercop23** [comment]
I moved the Image down to the Tree Model, thinking the same, and the Matrix with only 3 layered texts still took a while to rerender. So if the image was on a  diff model, that should not "force" the full length rerender, right?

**Comment by keithsw1111** [comment]
@AzGilrock No it has always worked that way (at least since 2014). If it didnt then when you clicked on an effect you wouldnt see how it would actually look when you re-rendered the sequence. That would be super frustrating.

**Comment by keithsw1111** [comment]
> Keith is that a change from how clicking on an effect used to work. I always thought we only re-rendered the effect you click on not every effect underneath it. That's why I thought you had to do a full render to get the layer blending from lower layers.

Not its not a change ... if it didnt work that way it would be almost unusable.

**Comment by derwin12** [comment]
The underlying pic effect is causing the entire line to render. This is expected behavior.
