### ISSUE TITLE
MHA - Ability to remove the color wheel choice

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4649]
Once you select a color, you cant unselect it .. meaning no light on for a portion.
Perhaps double click or and "OFF"? Or perhaps I missed something..

![image](https://github.com/user-attachments/assets/56073933-6e6f-4325-ae37-f833304bfa1a)

**Comment by derwin12** [comment]
Was told that I can click the (1) for the color and press the delete (works). Perhaps just adding some simple Help on the bottom of the screen as I see you can also click multiple times on the color wheel? Is that to select a different color for each moving head??

**Comment by AGFazio** [comment]
@AzGilrock - where would one find this documentation?
