### ISSUE TITLE
MHA - Reset to defaults

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4650]
Resetting on the Status page.. should it clear out the other values? Suggest it should..
![image](https://github.com/user-attachments/assets/30d77cd1-0f39-4d12-84f7-49eb4c53855d)
![image](https://github.com/user-attachments/assets/4b0d25e9-695d-4564-ac90-7d311e2e7fcb)
![image](https://github.com/user-attachments/assets/2f620e14-faac-49b9-950e-cc9220a532e3)
![image](https://github.com/user-attachments/assets/3570a974-e1fa-42ea-9045-256aa98d1d9d)

**Comment by cybercop23** [comment]
Done in 13
