### ISSUE TITLE
Turn off Alias Prompting Option

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4675]
Can a new Preference be created to stop the auto-prompt for saving an Alias?  

Thank you for looking,
Clyde L

![image](https://github.com/user-attachments/assets/d399ab64-f9ea-47a0-9e0e-0b6be2d8a4f6)

**Comment by kylegrymonprez** [comment]
A commit has been merged for alleviating this issue. Check it out and see how it works for you @Clyde-L

**Comment by Clyde-L** [comment]
> A commit has been merged for alleviating this issue. Check it out and see how it works for you @Clyde-L

Thank you!
