### ISSUE TITLE
When uploading the config to a Genius Pro 16 Controller the DMX port number does not match first pixel.

### ISSUE THREAD

**Issue by horathgar2000** [xLightsSequencer/xLights#4680]
**Describe the bug**
When uploading the config to a Genius Pro 16 Controller the DMX port number is incorrect.
With the Keep Channel Numbers selected the DDP number is 1 and the pixels start at what ever xlights has.
With the Keep Channel Numbers unselected the DDP number is the first pixel number channel but the Pixels on the Output start at 1.
With either setting the lights do not output unless you change the DDP to match the start channel of the first pixel.
E1.31 works fine as far as I can tell.

**To Reproduce**
Add Controller
Vendor = Experience Lights
Model = Genius Pro 16 Port
ID = X
Auto Layout = Checked
Auto Size = Checked
Full Xlights Control = Checked 
Protocol = DDP
Keep Channel Numbers = This is the problem Checked or Unchecked

**Expected behavior**
If Keep Channel Numbers checked then the DDP start number should match the Start number of the first pixel on controller.
If Keep Channel Number Un-checked then DDP and first pixel should match as 1

**Screenshots**
I can provide if needed.

**Versions (please complete the following information):**
Windows xLights64_2024_13_nightly-b981eb0

**Additional context**

**Attachments**

**Comment by computergeek1507** [comment]
If you can upload your layout I can look into it

**Comment by horathgar2000** [comment]
[Show.zip](https://github.com/user-attachments/files/16461775/Show.zip)

Here is my show config

**Comment by AGFazio** [comment]
Do you happen to have the Genius webpage open when you upload the outputs. If so, it could fail to update. I have noticed this happening on mine.

**Comment by horathgar2000** [comment]
I do a complete refresh of the page as I have noticed the same thing where the page will not pull the settings from the controller until the refresh has been done.
