### ISSUE TITLE
Moving Models

### ISSUE THREAD

**Issue by thekameleon** [xLightsSequencer/xLights#4684]
**Is your feature request related to a problem? Please describe.**
I intend to have models that can move. For instance, a candy cane that can move side to side 120 degrees. With xlights having the models be static, the sequence when part of a group looks odd when the model has moved.

**Describe the solution you'd like**
I would like to see a model where I can specify different positions that it can move and then have a way of specifying those positions in the timeline of a sequence.  I realize there are a number of ways that this can be done (PWM, High/Low/ etc...), but I was thinking something simple like position 1, position 2, etc... and the ability to specify the time it takes to move from one position to another. Let the lighting designer figure out the timing and how they will initiate the change in position (GPIO pin, for example). In my case, I want to use a linear actuator to position an 8ft candy cane from a horizontal to a vertical position. So, if I can drag the horizontal position to the vertical position, it would show on the timeline the number of seconds (that I specified in the layout tab) it would take to get from the first position to the second. Then xlights while rendering xlights would have a pretty good idea of where the candy cane model is and be able to adjust the effect rendering accordingly.

**Describe alternatives you've considered**
I really haven't figured out an alternative.  I kicked around having model variants in the various positions then trying to sequence to that.  However, it quickly got overwhelming with the number of groups going up 3 to 4 fold

**Additional context**

**Comment by keithsw1111** [comment]
And the servo model won’t do this?

On 29 Jul 2024, at 6:49 AM, Keenan Newton ***@***.***> wrote:

﻿

Is your feature request related to a problem? Please describe.
I intend to have models that can move. For instance, a candy cane that can move side to side 120 degrees. With xlights having the models be static, the sequence when part of a group looks odd when the model has moved.

Describe the solution you'd like
I would like to see a model where I can specify different positions that it can move and then have a way of specifying those positions in the timeline of a sequence. I realize there are a number of ways that this can be done (PWM, High/Low/ etc...), but I was thinking something simple like position 1, position 2, etc... and the ability to specify the time it takes to move from one position to another. Let the lighting designer figure out the timing and how they will initiate the change in position (GPIO pin, for example). In my case, I want to use a linear actuator to position an 8ft candy cane from a horizontal to a vertical position. So, if I can drag the horizontal position to the vertical position, it would show on the timeline the number of seconds (that I specified in the layout tab) it would take to get from the first position to the second. Then xlights while rendering xlights would have a pretty good idea of where the candy cane model is and be able to adjust the effect rendering accordingly.

Describe alternatives you've considered
I really haven't figured out an alternative. I kicked around having model variants in the various positions then trying to sequence to that. However, it quickly got overwhelming with the number of groups going up 3 to 4 fold

Additional context
Add any other context or screenshots about the feature request here.

**Comment by thekameleon** [comment]
The servo model is close but it is moving an image or mesh (servo3d).  I want to actually move an actual model in xlights in much the same way. So say I have a candy cane model standing up, I want to make it fall over then stand back up. 

So the servo models are close. They from what I can tell just don't allow you to move a model in a similar manner.

**Comment by cybercop23** [comment]
Sure can. Use servo with an actuator and you can me it layflat and backup.

**Comment by thekameleon** [comment]
Ok, I must not be 3cplaining this well. I understand that a servo pr actuator can move my core prop in real-life. What I'm looking for is xlights to know the position of that coro prop while it is rendering. Does that make sense

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Jul 28, 2024 at 19:25, ***@***.***> wrote:   


Sure can. Use servo with an actuator and you can me it layflat and backup.

**Comment by keithsw1111** [comment]
That is very unlikely to happen.

On 29 Jul 2024, at 10:33 AM, Keenan Newton ***@***.***> wrote:

﻿

Ok, I must not be 3cplaining this well. I understand that a servo pr actuator can move my core prop in real-life. What I'm looking for is xlights to know the position of that coro prop while it is rendering. Does that make sense

Yahoo Mail: Search, Organize, Conquer

On Sun, Jul 28, 2024 at 19:25, ***@***.***> wrote:


Sure can. Use servo with an actuator and you can me it layflat and backup.

**Comment by thekameleon** [comment]
I remember someone saying that about "base" show directories. :) Anyway. I thought I would ask. Maybe one day I'll get lucky. 

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Jul 28, 2024 at 20:39, Keith ***@***.***> wrote:   


That is very unlikely to happen.

On 29 Jul 2024, at 10:33 AM, Keenan Newton ***@***.***> wrote:

﻿

Ok, I must not be 3cplaining this well. I understand that a servo pr actuator can move my core prop in real-life. What I'm looking for is xlights to know the position of that coro prop while it is rendering. Does that make sense

Yahoo Mail: Search, Organize, Conquer

On Sun, Jul 28, 2024 at 19:25, ***@***.***> wrote:


Sure can. Use servo with an actuator and you can me it layflat and backup.
