### ISSUE TITLE
Move a model into the base show from a child (inherited) show folder

### ISSUE THREAD

**Issue by thekameleon** [xLightsSequencer/xLights#4685]
**Is your feature request related to a problem? Please describe.**
More of an inconvenience. Right now, if I want to put a model from a child (inherited) show into the base folder, I have to recreate it in the base folder. 

**Describe the solution you'd like**
Right-click menu and select move model to base show folder.

**Describe alternatives you've considered**
Recreate, or cut and pasting xml from one RGB_Effects.xml to another

**Additional context**

**Comment by keithsw1111** [comment]
Yeah no ... the base knows nothing about the children so this cannot work this way. You can copy it into the base by right clicking on layout and importing the model from the child then when you open the child link them up at that point.

**Comment by thekameleon** [comment]
The base doesn't have to have zero knowledge of the children. A possible implementation is to hold a reference to each child in the base when someone inherits a base. Then the parent would know who their children are... make for a much better parent, you know, knowing where their children are :)
I know one use case or concern would be, what if an end user moves a child show folder. In that case when you open up a base show folder or child show folder. xlights can look for all the children to validate locations, if one is missing, the user can be given the option of finding it, removing it, or ignore it (and suffer the consequences).
Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Jul 30, 2024 at 3:19, Keith ***@***.***> wrote:   


Yeah no ... the base knows nothing about the children so this cannot work this way. You can copy it into the base by right clicking on layout and importing the model from the child then when you open the child link them up at that point.

**Comment by keithsw1111** [comment]
The answer remains no. There is a solution in my previous response that already works.

**Comment by thekameleon** [comment]
I'm just making a suggestion bro.

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Jul 30, 2024 at 15:59, Keith ***@***.***> wrote:   


The answer remains no. There is a solution in my previous response that already works.
