### ISSUE TITLE
3d Model of Moving head when Preset count exceeds DMX channel count

### ISSUE THREAD

**Issue by thekameleon** [xLightsSequencer/xLights#4686]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
3d Object Model of Moving head when Preset count exceeds DMX channel count. Beam is still there but the base, yoke and head all disappear.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add a moving head Advanced
2. Set the DMX channel value to whatever you like (I used 16)
3. Set preset count to 17

**Expected behavior**
I expect the model object for the moving head to be not affected by the preset count

**Screenshots**
I attached a video

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024.13

**Additional context**
None

**Attachments**

https://github.com/user-attachments/assets/7a45613b-cdbc-446e-8491-5d306de9eaef

**Comment by computergeek1507** [comment]
when you have an invalid model configuration for a DMX Moving Head, xLights will not attempt to render it in the preview. If you have a channel set outside the range of valid channels, it will cause this

**Comment by thekameleon** [comment]
> when you have an invalid model configuration for a DMX Moving Head, xLights will not attempt to render it in the preview. If you have a channel set outside the range of valid channels, it will cause this

So I am clear. You cannot have anymore presets than the number of DMX channels configured for the moving head?

**Comment by cybercop23** [comment]
How can you? A preset is a channel, thus it will be part of the total chanel count.

**Comment by thekameleon** [comment]
> How can you? A preset is a channel, thus it will be part of the total chanel count.

I misunderstood what presets are then, I thought they were to preconfigure a setting like say for a specific static gobo so you can easily specify it (by name) without needing to know the DMX data value.

**Comment by derwin12** [comment]
I thought this was just a validation thing..
if # Channels is 16
then # of presets AND the value you can place on it should not exceed 16.

**Comment by thekameleon** [comment]
> I think the "model presets" are being confused with Gils new MH Effects Presets. This are more like Fixed channel values that will always be set when using regular effects like On, bars, etc. it's intended to turn on a shutter or "enable" channel if needed

That makes so much more sense now. Ok so, in just my opinion, there should be a validation limit on total presets to not exceed the channel number. Also if I am understanding this right these presets are like defaults right? Maybe conside changing the property to defaults to reduce future confusion.

**Comment by derwin12** [comment]
Addressed with Scott's commit.
