### ISSUE TITLE
Adjustment Effect no longer working since 2024.11

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4688]
It appears the canvas change may have impacted this .. 

Prior
![image](https://github.com/user-attachments/assets/f5a7dcb5-8a23-421e-873d-421a10a7ac44)

After .11
![image](https://github.com/user-attachments/assets/6eeb2478-a33c-4e20-ae02-77338f18b909)

Just selecting some values to make it apparent..
![image](https://github.com/user-attachments/assets/9c421a29-99db-4e2d-a690-8a6a905dac57)
![image](https://github.com/user-attachments/assets/52e734b1-ad75-4a02-9e82-913ac51c5f38)

**Comment by derwin12** [comment]
![image](https://github.com/user-attachments/assets/0c02ef4f-2cd0-46e7-a485-ae1108c0da60)

**Comment by computergeek1507** [comment]
Probably the canvas mode changes

**Comment by derwin12** [comment]
Dan committed the fix..
