### ISSUE TITLE
XLights shuts down without warning While building a Sequence

### ISSUE THREAD

**Issue by DBASQLGuru** [xLightsSequencer/xLights#4700]
**Describe the bug**
Xlights has shut down 3 times, back to back after importing a sequence related to the 911 Tribute from PPD.

**To Reproduce**
1 Add the music track
2) Import the sequence
3) Expand the elements to match the runtime length of the music

CRASH!!

**Expected behavior**
The ability to import a sequence and then subsequently save it without the application crashing without warnings or errors.

 - OS: Windows 11
 - xLights version 2024.13

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[Whitney Houston - National Anthem (Star Spangled Banner) 911 Tribute.zip](https://github.com/user-attachments/files/16503017/Whitney.Houston.-.National.Anthem.Star.Spangled.Banner.911.Tribute.zip)
[9_11-tribute-g4is94.zip](https://github.com/user-attachments/files/16503042/9_11-tribute-g4is94.zip)

**Comment by derwin12** [comment]
I think we need you to do a tools package logs .. so we can see the log and get your layout.

**Comment by derwin12** [comment]
I dont think attachments work via email replies .. nothing here.

**Comment by DBASQLGuru** [comment]
[xLightsProblem.zip](https://github.com/user-attachments/files/16517651/xLightsProblem.zip)

**Comment by keithsw1111** [comment]
You dont say what models you are importing onto what models. I imported things that seemed to match and selected all effects and expanded to the length of the sequence and rendered and it did not crash. Details matter.

**Comment by DBASQLGuru** [comment]
Here are the mapping done by PPD service.  Also updated to 2024.14 - the crash no longer happens.  

For details..  did you take a screen shot for comparison on how you mapped the sequence?  Details for the end user also help. Thanks.

![1](https://github.com/user-attachments/assets/afb69b44-97a6-41f7-b8ce-fef96f67f619)
![2](https://github.com/user-attachments/assets/e0f82994-93c5-4287-88d6-9e995e7a1d27)
![3](https://github.com/user-attachments/assets/7e2fb954-4242-4184-94c5-c161e16cb3e0)

Please close the case.. It looks like 2024.14 fixed the crashing issue.

**Comment by DBASQLGuru** [comment]
Thanks
