### ISSUE TITLE
Copy/Paste Error Where Unrelated Prop Data is Erased

### ISSUE THREAD

**Issue by Bgoldie20** [xLightsSequencer/xLights#4701]
**Describe the bug**
At random times, when using the AC lights toolbar, with the "Select" tool chosen, I will copy/paste two lines from two props and paste them to two other props. When pasting, it will erase a fifth line of sequencing that is seemingly unrelated to the copy or paste source or destination props.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Click on AC lights tool bar
2. Use "Select" mode for mouse
3. Copy 2 or more lines from 2 or more props
4. Paste to new props at same timestamp
5. Observe another line's data get deleted

**Expected behavior**
Expect to paste data and not interfere with other lines/props.

**Screenshots**
Video link to the problem in attachments section.

**Versions (please complete the following information):**
 - OS: Windows 10, Version 22H2, OS build: 19045.4651
 - xLights version: 2024.13 64bit (no updates available as of 8/5/2024)

**Additional context**
None

**Attachments**
Video link: https://www.dropbox.com/scl/fi/r7ktr4kmbegsv9x3l2u4h/xlights-copy-paste-error.mp4?rlkey=vm7ff47gton1y8ykz5vtwjnz3&st=slcli660&dl=0

Log files: Please PM and I can provide the dropbox link with the sequence file.

**Comment by keithsw1111** [comment]
This could be (in fact most likely is) happening due to model channel overlap. Without access to your layout it would be difficult to validate it.

**Comment by Bgoldie20** [comment]
Thanks for the quick comment! Very possible, I don't have hardware in hand yet so I skipped the configuration steps for models/channels and likely made the error there. Once I start setting up hardware and correct the overlap, I'll report back if still seeing this issue.

**Comment by Bgoldie20** [comment]
Here's the .fseq in case you're interested: https://www.dropbox.com/scl/fi/vomh8b14l02zb1t9y8rax/xLightsProblem_Copy_paste_error.zip?rlkey=ntozpcyb4ui60mwyarfj9n7ka&st=awu0n8ir&dl=0

**Comment by derwin12** [comment]
I cant duplicate this..
Used your seq .. I did a render .. nothing on controller. Check sequence shows no issue.
How did you do this?
"Copy 2 or more lines from 2 or more props"
I did ctrl-x, ctrl-v.

![image](https://github.com/user-attachments/assets/a7247c85-8d69-49e6-9276-04c47fc5bdc1)

**Comment by Bgoldie20** [comment]
To clarify, this was with a copy operation, not a cut (used Ctrl+C, Ctrl+V).

Just did a little more testing and found a contributing factor. When I copy/paste with ON effects at the bottom of the sequencing window, the issue happens. If I simply scroll down so that the bottom-most ON effect is further up the window, the issue does not occur. This video shows it happening and then not happening if I scroll down:
https://www.dropbox.com/scl/fi/reej3t15ldo3c2cxz04wt/xlights-copy-paste-bug-2.mp4?rlkey=bvfi83u52q7fudnqonnwb9kff&st=lokg5xx6&dl=0

**Comment by Bgoldie20** [comment]
Found one more example, in this video I copy/pasted two lines and not only did they not show up where pasted, it also erased two other lines of data. Later in the video I again attempt to copy and paste it to two lines (it does not show up) and two another two lines (again, data is not pasted).
https://www.dropbox.com/scl/fi/opdux7pu1p1ucm1chp3nw/xlights-copy-paste-bug-3.mp4?rlkey=251siqiujdgvj9rek8naqm3tz&st=xyjbu4v9&dl=0

**Comment by derwin12** [comment]
I still cant duplicate it .. I think we need you in the zoom room to show us. I am missing something.

**Comment by derwin12** [comment]
Ok was able to duplicate -- pretty much by luck and trying over and over. Keith just committed a similar issue/fix. Going to see if that helps here.

**Comment by derwin12** [comment]
Still an issue.

**Comment by Bgoldie20** [comment]
Thanks so much for the help and the quick response! I'll look for the changes in the next update!

**Comment by derwin12** [comment]
If you can validate by using the nightly that would be helpful.

**Comment by Bgoldie20** [comment]
Downloaded the nightly build, tested, and everything looks good! No longer seeing erased, incomplete, or bad data on other lines. Copy/paste working as expected in AC lights mode. Thanks again for your help!
