### ISSUE TITLE
FPP Connect - Pixel count set to 0 when pushing single-channel models to FPP

### ISSUE THREAD

**Issue by shanerehm1234** [xLightsSequencer/xLights#4705]
![FB_IMG_1723043578425](https://github.com/user-attachments/assets/34a063a8-3fd0-4444-84bc-dd11f64bcbde)
![FB_IMG_1723043574955](https://github.com/user-attachments/assets/1d51f068-ff09-4622-b970-0ee6c62699bd)
![FB_IMG_1723043570633](https://github.com/user-attachments/assets/1f3c39b7-6cbd-4d67-860d-2d8fc6dca88a)

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Working with single channel models in xLights- Servos and AC devices running on Pixel2Things hardware. Devices are modeled and configured as single-channel entities, The layout is then pushed to FPP using FPP Connect, but on the pixel string FPP configuration page, the PIXEL COUNT is set to 0. I have to go and manually change every 3rd entity to 1 (first channel for every 3 lines) to get them to function with FPP. 

**To Reproduce**
1. Set up servo or AC device in xlights.
2. Connect device to controller using Pixel2Things board
3. Push layout to FPP using FPP connect
4. Check PIXEL COUNT setting on FPP Input/Output configuration tab
5. The first device needs to be set to 1 to function properly, but its set to 0 anytime a new layout is pushed from xLights

**Expected behavior**
FPP SHOULD be able to recognize single channel devices and address them properly. A current workaround is to set up a channel block and configure the devises as shadow models in xlights. 

**Screenshots**

**Versions (please complete the following information):**
Applies to ALL recent versions on xLights and FPP

**Comment by computergeek1507** [comment]
Fixed with 19df993

**Comment by computergeek1507** [comment]
I saw you Facebook post before this😁
