### ISSUE TITLE
Moving Head Advanced Custom Model Import Crashes 2024.14

### ISSUE THREAD

**Issue by davidlsl123546** [xLightsSequencer/xLights#4712]
*Describe the bug**
When loading our custom Dominar X moving head Advanced model, xLights crashes.

**To Reproduce**
Import this model: https://www.dropbox.com/scl/fi/ojxope9ygsa0110ys4w1e/DMXMovingHead-Avd-Dominar-X-1-V8-9-24.xmodel?rlkey=8v8t3ts1u2aukygequt5gvoxa&dl=0

**Expected behavior**
Instant Crash on file selection.

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024.14

**Additional context**
Did not occur in previous versions as far as I know.  Customer reported, multiple users have this issue.  Versions of this model that were already imported DO work in layout and are stable, but cannot import new models.

**Attachments**
- I do not see a crash log from this crash in the User/temp folder.  Let me know if there's anything else I can do to help!

**Comment by derwin12** [comment]
For others..
![image](https://github.com/user-attachments/assets/6073c24d-7faf-4ac2-acb8-a2631f548bfd)

**Comment by derwin12** [comment]
I am thinking xlights doesnt support importing the pre-MHadvanced models. Is that what this was/is? If so this may need to be re-exported.

**Comment by computergeek1507** [comment]
There is another bug that mentioned that, we need to write upgrade code for old 3D model files

**Comment by davidlsl123546** [comment]
No, this is a new moving head advanced model.  It will import correctly in
2024.12, but not 14

**Comment by derwin12** [comment]
Okay.. then Scott it isnt grabbing this type value?
auto type = node->GetAttribute(XmlNodeKeys::DisplayAsAttribute);

**Comment by derwin12** [comment]
Any chance it doesnt "deserialize" if this new attribute isnt in the file?
`node->AddAttribute(XmlNodeKeys::DmxColorWheelDelayAttribute, std::to_string(colors->GetWheelDelay()));`

**Comment by derwin12** [comment]
Note a fresh export model then import also fails.

**Comment by derwin12** [comment]
Works in Nightly #985 but breaks in #986

**Comment by derwin12** [comment]
The .xmodel now has an unexpected wrapper` <models> </models> `that seems to be causing this.

**Comment by derwin12** [comment]
Scott committed a fix for this.
