### ISSUE TITLE
FPP8 won't delete proxies and xlights reports failure on upload

### ISSUE THREAD

**Issue by dartunder** [xLightsSequencer/xLights#4713]
Fails in 2024.14 and the lastest nightly.
This appears to have been a problem since this commit or is due to an FPP issue.
https://github.com/xLightsSequencer/xLights/commit/d3d57000569b8d56be0b593f8c07a09c72fbd872

This is used to upload the proxies:  
return PostJSONToURL("/api/proxies", proxies);

Note: No other instance of PostJSONToURL uses the return value, so I'm unsure of its behavior.

It does upload the proxy, but because it returns a value instead of false, cancel is set, and FPP upload does not complete and shows canceled in the status bar.

* Also at least in FPP 8  (8.x-master-426-g2e6b63a5)
I'm unable to delete the proxy with the standard UI.  
http://fpp.local/proxies.php
Click proxy, hit delete, hit save, and the proxy is not deleted.

**Comment by derwin12** [comment]
Scott committed fix.
