### ISSUE TITLE
Estimated Power Calculation in Visualizer

### ISSUE THREAD

**Issue by Fonzi03** [xLightsSequencer/xLights#4716]
It would be nice if a field was added to the properties of the string which allowed me to input the per pixel wattage and voltage. 

Then when I assign strings to ports it should show an estimated total amps
Pixel Port 1
Pixels: 265
Est. A: 1.99

Even better if this turned red when it exceeded the controllers output fuse capacity

**Comment by MrPierreB** [comment]
It currently does show the draw on the visualizer.   It is using a set number of 0.055 as the amp per pixel draw.
![image](https://github.com/user-attachments/assets/a1579402-f26d-461a-8467-176de7239b7c)

**Comment by Fonzi03** [comment]
@MrPierreB , is it possible to make this an exposed value in the layouts tab.

Exposing the wattage and voltage as a user definable variable, along with either the default brightness set on the controllers tab (or if brightness per model if selected) you can estimate the amps more accurately.

I use a combination of 12mm bullets, 30mm tri led pucks, seed pixels and will soon be adding 10w chips. These are a mix of 5/12v as well

Throwing a warning similar to when you go over the pixel count, if you exceed that controllers specified max current per port would be nice as well.
