### ISSUE TITLE
Falcon PiCap V2 does not showup as selectable

### ISSUE THREAD

**Issue by kylegrymonprez** [xLightsSequencer/xLights#4724]
**Describe the bug**
The new Falcon PiCap V2 cannot be selected in the controllers tab

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Try to add the Falcon PiCap V2 under "Falcon" Vendor
**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Versions (please complete the following information):**
 - OS: MacOS
 - xLights version 2024.14.1 (Mac beta testing), but should be reproducible on all platforms 2024.14+

**Additional context**
I looked for the controller definition in the falcon.xcontroller and it is present, however it has a blank "Name" entry. I am unsure if this is intentional or not. [This commit](https://github.com/xLightsSequencer/xLights/commit/6cdd5527cab53a61f7e0bbe60c4d2e21cbbd356e) by @keithsw1111 adds the payload to the file with the blank name.

I did edit the file locally and add an entry into "Name" and it does then show up, and I was able to push the config to the controller successfully. This could just be a copy/paste error. However, there could be another reason I am unaware of.  The fix is trivial it appears.

**Comment by kylegrymonprez** [comment]
Additionally it seems the PiHat V1 is under the "FPP" vendor. Unsure if this controller should be under FPP or Falcon, but we should probably do it consistently.

**Comment by derwin12** [comment]
Appears to be there..
![image](https://github.com/user-attachments/assets/9304becd-b221-4092-8c30-665fad3d691f)

**Comment by derwin12** [comment]
.. I think "Pi Hat" is a generic entry .. not necessarily just Falcon.

**Comment by kylegrymonprez** [comment]
Okay.....thats weird. I undid the file edit change and now it's there? I have no idea why......

**Comment by kylegrymonprez** [comment]
Okay ignore me......fresh install and it's there as well. I couldn't tell you why it wasn't showing up. PEBKAC
