### ISSUE TITLE
New Galaxy Scale To Buffer Issue

### ISSUE THREAD

**Issue by bravado67** [xLightsSequencer/xLights#4727]
Strange results when using Galaxy effect after the latest update.
<img width="411" alt="Screenshot 2024-08-16 at 3 41 15 PM" src="https://github.com/user-attachments/assets/fbcc2ddc-d00d-44e3-b748-fe625c8851b0">
<img width="469" alt="Screenshot 2024-08-16 at 3 41 27 PM" src="https://github.com/user-attachments/assets/095fb9b8-1f11-4b9c-a032-0b6f5d40576b">
<img width="419" alt="Screenshot 2024-08-16 at 3 41 32 PM" src="https://github.com/user-attachments/assets/97206578-3de0-4484-a601-7634e52dc5fe">

**Comment by computergeek1507** [comment]
Please provide more information

**Comment by bravado67** [comment]
I restarted it, and it looks normal again.
