### ISSUE TITLE
Names/Numbers for Colour pallets

### ISSUE THREAD

**Issue by Melinda738** [xLightsSequencer/xLights#4731]
**Is your feature request related to a problem? Please describe.**
No not a problem - this may already be a feature I am just not aware of. I don't know how to differentiate colour pallets easily

**Describe the solution you'd like**
A way to name or number the colour pallets so I can pick the one I need 

**Describe alternatives you've considered**
I don't really have any alternatives - atm I just have dozens of colour pallets saved

**Additional context**
![Screenshot 2024-08-18 131001](https://github.com/user-attachments/assets/eaa9fddd-ce1b-4b1a-bb12-0000f109a71d)

**Comment by cybercop23** [comment]
See #4313
