### ISSUE TITLE
Batch preview export

### ISSUE THREAD

**Issue by philspitlerSF** [xLightsSequencer/xLights#4733]
I would really like to batch export my sequences as video files.

The batch render works great and it got me thinking, why not be able to batch export the video previews too.

**Comment by computergeek1507** [comment]
If you open the script runner, I created a lua script that does this.

**Comment by philspitlerSF** [comment]
amazing.. thanks.. I didn't even know the there were scripts in xLights. Is the a repository of other scripts? I see the ones installed by default.
