### ISSUE TITLE
Inconsistent paste behavior compared to prior releases. starting with 24.13

### ISSUE THREAD

**Issue by sidelights** [xLightsSequencer/xLights#4736]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
with timing track selected right click paste does not act the same as prior releases.   In prior releases with 'by time' selected at the top and a timing track selected cntr-v and right click paste would snap to the timing mark.  post .13 the right click paste pastes to the point in time you selected.  It also appears to paste to .001 level of precision not a frame. so you will get things like 29.001 or 29.034 vs .025. 

**To Reproduce**

 3 videos included. 
first with 2024.12 showing current and prior behavior. with copy and paste.  ctrl-v and paste both act the same way. 

second nightly build (also seen in .13), paste does not align with the timing mark as prior release. (snap to timing track is enabled). 

behavior does not occur when only one effect is being copied.  Only multiple with right click paste.  Ctrl-v does not act the same.. ctrl v acts as it has in the past. right click paste will paste anywhere as if a timing track is not selected. 

It also seems to effect paste functionality with clicking on the waveform and then clicking near the vertical bar.. Now it will allow you to put an effect in between frames, and does not seem to 'snap' as well as it used to, likely because of the precision down to .001 vs .025 at 40fps. 

3rd video shows the copy and paste in .12 will not let you split a frame, I have zoomed in to a seq at 40 fps, giving .025 between frames.   In .14 nightly you can paste down to .001 it does not respect the frame snap as it does .12.   have not proved this is in .13 yet.  But I suspect they are related.   video starts with showing .14 behavior, and ends with .12 behavior. 

https://github.com/user-attachments/assets/59b735f9-8810-4a5c-af33-d1486b240772

https://github.com/user-attachments/assets/5d0f37bf-f369-48ee-b199-5db3a3287651
[xlights 2024.14.inconsistent.zip](https://github.com/user-attachments/files/16684288/xlights.2024.14.inconsistent.zip)

[xlights 2024.12vs14_intra_frame_paste.zip](https://github.com/user-attachments/files/16684251/xlights.2024.12vs14_intra_frame_paste.zip)

**Expected behavior**
consistent behavior between crtl-v and right click paste as in prior releases.   with a timing track selected the left most timing track line both paste and ctrl-v both snap to that point.  Without a timing track selected the paste will snap to a frame as in prior releases. 

**Screenshots**

**Versions (please complete the following information):**
 - win 11 
 - xLights version 2024.13+
 
 - **Additional context**

**Attachments**

**Comment by sidelights** [comment]
broken in this nightly build
https://github.com/xLightsSequencer/xLights/actions/runs/9881857807
not broken in this nightly build
https://github.com/xLightsSequencer/xLights/actions/runs/9855769147

**Comment by derwin12** [comment]
This appears to be the split code .. I dont know the fix .. it captures the location when you right click for the split effect to work but it is also the consequences of overwriting the original position you wanted for the paste. 
So the paste now requires you to do the right click exactly where you want it to paste.

![image](https://github.com/user-attachments/assets/67ab2dd1-cf67-4cc8-a763-af77fe8ff56a)
