### ISSUE TITLE
[Enhancement] FPP Connect Button on Controllers Panel

### ISSUE THREAD

**Issue by kylegrymonprez** [xLightsSequencer/xLights#4737]
**Is your feature request related to a problem? Please describe.**
FPP Connect is one of the most used tools inside of xLights that is used by a majority of the users for running the show. Inside the Zoom room, many people were saying that it would be a good candidate for having a button on the panel. I agree that it is common enough to not be buried in "Tools>FPP Connect", but also agree it's kind of separate than generic controller setup. However, I do see FPP features have been given some more prominent features inside of controller configuration given it's popularity.

**Describe the solution you'd like**
A button for FPP Connect. 

**Describe alternatives you've considered**
I went ahead and coded this, but I wasn't sure if this was something likely to be accepted. 
![Screenshot 2024-08-21 at 8 02 47 AM](https://github.com/user-attachments/assets/6afa24be-4127-4745-b32f-69ef5726053e)

There's also another place that it could go at the bottom of the Controller configuration pane where "Visualise" is
![Screenshot 2024-08-21 080736](https://github.com/user-attachments/assets/5bcff091-33c6-413d-8ab9-c23d0d93ae7e)

**Additional context**
If this is accepted as a good idea, which one would you all prefer to see submitted - the coding is relatively straight forward and I already have one of the variants coded.

**Comment by cybercop23** [comment]
We've tried to condensed the lower right buttons to save space and those are controller related. FPP is not controller related. Just put it on the left side below Discover... maybe add a spacer or two, to separate the two lists.

**Comment by kylegrymonprez** [comment]
![Screenshot 2024-08-21 at 8 44 25 AM](https://github.com/user-attachments/assets/aaea03ce-9b75-4c5f-9914-4464b5e60f0e)
Here's two spacers

**Comment by dkulp** [comment]
I think I would do "Save", a space", the three Add's, a space, and the two tools (Discover and FPP Connect), but that's me.

**Comment by cybercop23** [comment]
I like the separation... do we even need null with the non-overlap logic? I vote to kill it

**Comment by keithsw1111** [comment]
> I like the separation... do we even need null with the non-overlap logic? I vote to kill it

Do not remove it. There are still valid use cases for this.

**Comment by kylegrymonprez** [comment]
Alright I'll throw a PR up for this

**Comment by kylegrymonprez** [comment]
Code merged
