### ISSUE TITLE
xSchedule & its API uses incorrect sequence duration times for sequences, NOT matching what's showing in xLights sequencer

### ISSUE THREAD

**Issue by msimmons78** [xLightsSequencer/xLights#4738]
**Describe the bug**
Bug in xSchedule and xSchedule API uses incorrect Sequence Duration of musical sequences. The Sequence Settings in xLights Sequencer showing Sequence Duration shows a time duration that doesn't match within xSchedule.  The seq duration shown in xLights is correct as it matches the audio file duration.  So bug appears to be within xSchedule.  (And NO there are no offsets or delays being used or set in xSchedule to make this behavior happen.)

**To Reproduce**
See attached screenshots.
![image](https://github.com/user-attachments/assets/f90bb0c8-0b96-4721-b85d-32b60086a662)
![image](https://github.com/user-attachments/assets/54a16446-7ef5-42ef-8186-fa51dd33fe50)
![image](https://github.com/user-attachments/assets/563c6c67-0c2d-4d15-b4fd-616e8a51c5d3)

**Expected behavior**
Sequence Duration in all xLights programs (including xSchedule & xSchedule API) should match that as shown and set within the xLights sequencer.

**Screenshots**
See attached Screenshots.

**Versions (please complete the following information):**
 - OS: Windows 10 Pro 64-bit (22H2 Build 19045.4780)
 - xLights version 2023.13 64-bit

**Additional context**
N/A

**Attachments**
See attached Screenshots.

**Comment by msimmons78** [comment]
xLights version 2024.13 64-bit is being used, NOT 2023, sorry!

**Comment by msimmons78** [comment]
![image](https://github.com/user-attachments/assets/54daec20-1433-45bb-b938-c580acbe5317)

**Comment by msimmons78** [comment]
![image](https://github.com/user-attachments/assets/25e74081-73ff-4a29-8b97-9f076cd391d0)

**Comment by derwin12** [comment]
xschedule AND fpp use the audio duration when playing a sequence. It will ignore any value greater than the audio length.
Is it just a fraction of a second off? Try reselecting the audio to see if it updates the time.

**Comment by msimmons78** [comment]
> xschedule AND fpp use the audio duration when playing a sequence. It will ignore any value in xlights sequence settings. Is it just a fraction of a second off? Try reselecting the audio to see if it updates the time.

As mentioned in the bug report: "The seq duration shown in xLights is correct as it matches the audio file duration. "   AUDIO DURATION is still not what's shown in xSchedule or its API either.   Yes a fraction of a second off, after 20 sequences is huge. We're building an audio synchronization platform (check it out www.Tune2.app) where this is causing a major issue in our algorithm, garbage in-garbage out.

**Comment by computergeek1507** [comment]
The duration is read from the FSEQ file header. The audio duration isn't known until the audio is loaded at playback time.

**Comment by msimmons78** [comment]
I understand, but something is not right from what I can see, it doesn't make sense.

**Comment by derwin12** [comment]
I used Sequence Info from FPP to display the header .. (I think there is a standalone prg to do this) but for this example:
(I verified 10 other sequences using this technique)
The seq is 50msx4380 frames = 219000ms
xlights has this .. so rounded down a whole frame.
![image](https://github.com/user-attachments/assets/9aafee6e-563d-420d-be38-8578f6d523fd)
![image](https://github.com/user-attachments/assets/3f9df01a-1429-4a70-b8d0-6b3295675212)

xSchedule use the 50x4380 to populate the playlist. 

![image](https://github.com/user-attachments/assets/a6a2caf8-7a5b-45d3-8ea2-a698ca5bf1d1)

**Comment by msimmons78** [comment]
@derwin12 Thanks for the info, so I went and duplicated what you showed and calculated and found several sequences that don't make any sense following what you posted above....

![image](https://github.com/user-attachments/assets/9c86601c-7dd3-4c6d-b52f-d0e2aa441014)

![image](https://github.com/user-attachments/assets/edc4b820-5bdc-45ab-92ed-260dc35399ca)

Any explanation?

**Comment by msimmons78** [comment]
![image](https://github.com/user-attachments/assets/cb199aaf-2fb0-4830-9bfb-2db9ec24a8f7)

**Comment by cybercop23** [comment]
260,833 vs 260,800.. for real!!!

**Comment by derwin12** [comment]
Looking at the code .. it calculates the seq based on reading the mp3  if _overrideAudio is not set - looking to see how that might be set. Preference perhaps?
```
            if (!_overrideAudio && af != "" && wxFile::Exists(af)) {
                _durationMS = AudioManager::GetAudioFileLength(af);
                _controlsTimingCache = true;

                // If the FSEQ is shorter than the audio ... then override the length
                size_t durationFSEQ = fseq->getTotalTimeMS();
                if (_durationMS == 0) {
                    logger_base.debug("Audio length %ld overridden by FSEQ length %ld as zero just cant be right ... likely audio file load failed.", (long)_durationMS, (long)durationFSEQ);
                    _durationMS = durationFSEQ;
                } else if (durationFSEQ < _durationMS) {
                    logger_base.debug("Audio length %ld overridden by FSEQ length %ld.", (long)_durationMS, (long)durationFSEQ);
                    _durationMS = durationFSEQ;
                }
            } else {
                _durationMS = fseq->getTotalTimeMS();
            }
```

**Comment by msimmons78** [comment]
@cybercop23 
Yes, I am for real, but I'm really concerned about 260800 vs 260242?  (Sequence Info from FSEQ in FPP and Playlist from xScheduler screenshots).  Don't you know pennies add up?   So do milliseconds!

**Comment by derwin12** [comment]
Check these settings .. any difference?
![image](https://github.com/user-attachments/assets/b9bcb290-37cc-4090-8d6e-4514cefcaecc)

**Comment by msimmons78** [comment]
@derwin12 None of those are selected, all unchecked.  Do you have time to go into xLights Zoom Room to discuss further?  Or I can setup a Zoom between us?

**Comment by derwin12** [comment]
In your example .. the audio wins out as the sequence is shorter.
I am done zoom room for tonight.

**Comment by msimmons78** [comment]
@derwin12 in xLights sequencer the sequence duration matches exactly what the audio file length is.   Obviously when you are calculating frames x fps it's not going to match exactly the audio file length as shown in examples above.  But in my example there's a huge difference between 260 800 vs 260 242.    If I check Override audio in xSchedule, does that mean that it will play the sequence but use the time from the audio file for the length of the step part of the show?

**Comment by derwin12** [comment]
After some zoom room analysis we found that the audio length is calculated using a stream in xschedule whereas xlights uses audiomanager on the file. With certain mp3 there is a discrepancy.  Files identified has having an 2nd stereo track were in error.
![image](https://github.com/user-attachments/assets/2b99cd8f-8182-4f6d-a733-ca311d30f3e9)

One quick fix is to open n save the audio files to remove this extra track.

The coding workaround is to use the fseq calc ie fps * #of frames. This unfortunately only gets used in xscheduler if you use the fast start audio flag. That has a side effect of loading all the audio into memory which is problematic for larger shows.
The thought is then to add a checkbox/flag to "Use fseq timing" as an override. This means you will get the audio length a < 1 frame length in duration difference from the audio at all times.
![image](https://github.com/user-attachments/assets/eaa368c7-e53b-4c50-8348-07dbc00c0525)

**Comment by msimmons78** [comment]
Thanks everyone for your assistance in this!

Keith --- Could you please explain why when you select Fast Start Audio why it adds additional time to the duration shown for each FSEQ that it's enabled for?

**Comment by computergeek1507** [comment]
I feel like fps * # of frames should always be used for duration as it's the true seq duration

**Comment by msimmons78** [comment]
If that's the case, within xLights under sequence settings.  It should show both values and be appropriately labeled then.  Media Duration Length     and     Sequence Duration Length       And from there anytime we'd see Duration it would be understood that its based on fps * # calculation (ie. sequence duration length).  Because one would think that xSchedule and xLights "duration" time should be the same otherwise.     Most probably didn't care because these two durations are slightly off.  But because of this MP3 MS Stereo issue, it was very noticeable and was off 400-700 milliseconds in certain cases!

**Comment by msimmons78** [comment]
@cybercop23 Alex, could you please explain why when you select Fast Start Audio why it adds additional time to the duration shown for each FSEQ that it's enabled for?  Just trying to wrap my head around this one. Thanks!

**Comment by cybercop23** [comment]
Not me.

**Comment by derwin12** [comment]
Going in circles ..its the same code .. 
it checks the audio length from the stream. if is less than the duration, it use it..
then it checks the fseq duration .. if less it uses that.
Unfortunately there are 3 possible sources of truth for audio length. 
xlights sequence settings based on audio manager reading the file, fseq header calc and then xscheduler audio stream calculation.

**Comment by msimmons78** [comment]
@derwin12 I agree... we saw that during the code debug.  All I was asking above was can someone please explain why when you check Fast Start Audio, why the duration shown for that FSEQ changes when it's checked vs. unchecked.   

Fast Start Audio according to a several year old YouTube tutorial by Keith, it was said Fast Start Audio automatically reads through the whole playlist a Start of show, and loads all audio files in memory to speedup play during sequence transitions.  Since the audio player doesn't have to load them up in memory upon sequence change.

**Comment by derwin12** [comment]
I created a test branch with an override to use fseq time but the engine behind running xschedule is built to use the audio to control the duration. It basically stops at the end of the song .. even if the fseq header is longer or I code it to use the fseq header time. I dont see this changing.
