### ISSUE TITLE
Xlights 2024.14 crashs

### ISSUE THREAD

**Issue by dparham500** [xLightsSequencer/xLights#4741]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to create my first sequence, in either animation or musical, Xlight crashes when I try to add a light sequence every time.  I have restarted Xlight atleast 10 times and rebooted computer twice.  (Macbook Air)

**To Reproduce**
Cant seem to get Quicktime to record screen.

**Expected behavior**
Not crashing

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac Monterey Ver 12.7.6 MacBook Air Early 2015 2.2GHz Dual i7cores
 - xLights version [e.g. 2024.14]

**Additional context**

*
![Screen Shot 2024-08-21 at 1 08 00 PM](https://github.com/user-attachments/assets/80ee06ff-3f4d-4148-95a2-956b11f5dad6)
![Screen Shot 2024-08-21 at 1 07 50 PM](https://github.com/user-attachments/assets/efd0538a-159b-4dfa-a7d7-96cc10bee5e5)
![Screen Shot 2024-08-21 at 1 07 40 PM](https://github.com/user-attachments/assets/9f8ec388-70dd-4c21-9535-83731d31fb0b)
[xLightsProblem A.zip](https://github.com/user-attachments/files/16698340/xLightsProblem.A.zip)

**Comment by dparham500** [comment]
ScreenRecorderProject3.mp4

https://github.com/user-attachments/assets/35d6975e-1198-4834-97bc-770902999035

**Comment by dparham500** [comment]
https://github.com/user-attachments/assets/5c18eabc-ed73-415c-8085-3651450d66ee

**Comment by computergeek1507** [comment]
Can you try disabling Hardware Video Rendering in the Preferences

**Comment by dparham500** [comment]
Computergeek1507- I don't see that under either Xlights or Mac system preferences.

**Comment by derwin12** [comment]
For others:
```
0   xLights                             0x000000010ba1c80c _ZN14xlCrashHandler11HandleCrashEbRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 3772
1   xLights                             0x000000010c8118eb _ZN9xlBaseApp16OnFatalExceptionEv + 91
2   xLights                             0x000000010ca9bacc _ZL20wxFatalSignalHandleri + 28
3   libsystem_platform.dylib            0x00007ff808b1fdfd _sigtramp + 29
4   ???                                 0x00007ff7b581e2f0 0x0 + 140701878838000
5   xLights                             0x000000010c062f69 _ZN16PixelBufferClass5resetEiib + 3497
6   xLights                             0x000000010be816c9 _ZN12xLightsFrame15InitPixelBufferERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEER16PixelBufferClassib + 409
7   xLights                             0x000000010c3c8e4c _ZN9RenderJobC2EP12ModelElementR12SequenceDataP12xLightsFrameb + 860
8   xLights                             0x000000010c3c1a3a _ZN12xLightsFrame6RenderER16SequenceElementsR12SequenceDataNSt3__14listIP5ModelNS4_9allocatorIS7_EEEERKSA_iibbONS4_8functionIFvbEEE + 2010
9   xLights                             0x000000010c3bc4f1 _ZN12xLightsFrame20RenderEffectForModelERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiib + 1137
10  xLights                             0x000000010be8e1f1 _ZN12xLightsFrame19EffectDroppedOnGridER14wxCommandEvent + 1633
11  xLights                             0x000000010ca9f8fa _ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler + 2202
```

**Comment by derwin12** [comment]
Cant duplicate on windows .. hmm.

**Comment by dparham500** [comment]
> Cant duplicate on windows .. hmm.

Were you able to watch the above video?

**Comment by derwin12** [comment]
yes .. it appears you just grab a bars effect and drag across and drop it? Anything subtle I missed?

**Comment by dparham500** [comment]
> yes .. it appears you just grab a bars effect and drag across and drop it? Anything subtle I missed?

Nope, thats exactly what I am doing

**Comment by derwin12** [comment]
Should make absolutely no difference by try removing these unnecessary dups from this group.
![image](https://github.com/user-attachments/assets/a9f9321c-aa0f-4836-8125-3ad1f81ec47d)

**Comment by dparham500** [comment]
Ok, I deleted everything except for the tombstone and it still crashs

**Comment by kylegrymonprez** [comment]
Can you try 2024.15 just to see if it's still an issue?

**Comment by dparham500** [comment]
Just updated to .15.  Still crashes.  
Ordered a cheap Windows 10 desktop to give this a try.  Thank you for everyone's help.








V/R Dennis Parham
 

    On Thursday, August 22, 2024 at 07:03:24 PM PDT, Kyle Grymonprez ***@***.***> wrote:  
 
 


Can you try 2024.15 just to see if it's still an issue?

**Comment by derwin12** [comment]
Unable to duplicate.
