### ISSUE TITLE
Zooming into house is limited.

### ISSUE THREAD

**Issue by efaranda** [xLightsSequencer/xLights#4745]
Current have revision 2024.14 on a Mac Studio.

When I go to the Layout tab and view my house in the layout. I am unable to zoom in on the props.  It will go so far, then stop zooming in

**To Reproduce**

1. Load xLights
2. Select Layout Tab
3. position house in center of screen
4. Use mouse ball to zoom in on a prop mounted on the house.

**Expected behavior**
Would be able to zoom in completely.

**Screenshots**

**Versions (please complete the following information):**
 - OS Sonoma 14.6.1 - Mac Studio w/ 32GB
 - xLights version 2014.14

**Additional context**

**Attachments** - This is a packed sequence file with my configuration.

https://www.dropbox.com/scl/fo/o8a7czp9bpisdjvut2817/AHl1HsZvfrRYvlvqDZgFLOI?rlkey=6l21jjjuqc55hdpmdhg2ab7hf&st=qoze9xg9&dl=0

**Comment by kylegrymonprez** [comment]
Are you referring to 3d navigation?

**Comment by cybercop23** [comment]
Yah, he's in 3d and trying trying to zoom in. I think the issue is the ratio. His house is very small on the standard mesh. Can only zoom in so far.

**Comment by computergeek1507** [comment]
Can you scale up the obj file?

**Comment by efaranda** [comment]
I'm not sure how to do that. I had someone convert the OBJ file for me, and I drew the house in SketchUp, sent them the file, and they sent me the OBJ.  I still have the SketchUp file.  I will load it into the dropbox location

**Comment by dkulp** [comment]
Adjust the scaling parameters in xLights to make it larger:

<img width="632" alt="Screenshot 2024-08-22 at 11 15 23 PM" src="https://github.com/user-attachments/assets/d5af7035-6309-4a82-b7fe-ede4711a5313">

Ideally, if you put some lights on the left/right/top of the area you are sequencing and then flip to 2D, those lights should be about 1000-1500 pixels (turn on the 2d bounding box to figure that out).   When xLights goes to create the buffers for rending on groups, that size would result in a fairly accurate buffer, but not so huge that rendering is horrendous.

**Comment by efaranda** [comment]
I scaled it up from 6 to 50, but I didn't move any props. It does the same thing: it gets to a certain distance from the house, then stops.

I noticed one thing. I switched back to my old house layout, which works fine.

The yard size wasn't in the OBJ file for my old house, but I do on the new house. Could that be it?

BTW: My Mac auto-updated to 2024.15

![Untitled](https://github.com/user-attachments/assets/76e3508c-a470-4776-ac61-8e186bfaef6c)

**Comment by MDickson00** [comment]
> Can you scale up the obj file?

His OBJ file and grid are quite large as you can see in his picture. He is unable to zoom in super close to anything, it's like it hits a wall. I suspect it has something to do with the size of the OBJ/Grid.

**Comment by efaranda** [comment]
I was able to correct it.  I moved the house obj position in the Z axis by 9500 units.  It was around the -3500 position. I moved all my props up and it is now working.
