### ISSUE TITLE
Corrupted MP4 uncompressed matrix model export - matrix 216/384 (testing shows failed exports dating to 2024.09 release)

### ISSUE THREAD

**Issue by mcenerykwm** [xLightsSequencer/xLights#4753]
Use case:  export xLights effects  from a 192/384 Matrix model as MP4 uncompressed video

Discovered that since 2024.09,  the generated uncompressed video fails to display on local machine (Windows media player) nor via video effect in xLights sequence

Expected behavior in 2023.23 - 2024.08.   Broken behavior 2024.09 - 2024.15

Platform: Windows
Layout - single matrix - 192/384
Sequence - 30 second butterfly effect 

Layout, simple butterfly test sequences and several MP4 non-compressed video export examples

When place video effect in sequence, link to video does not display (blue box).  Of interest. the exported MP4 file is shown by other application including uploading to GITHUB (below) 

Thanks

https://github.com/user-attachments/assets/8b93f573-8ac3-4117-a347-603388b9609c

https://github.com/user-attachments/assets/b9819933-a1c3-43c6-8db8-6aa756eb589c

[ButtetflyTest.zip](https://github.com/user-attachments/files/16738060/ButtetflyTest.zip)

**Comment by derwin12** [comment]
I think this was the move from AVI to mp4.
From Google:
"You can't do it. MP4 specification only accepts H264 or H265 codecs for video (based on the MPEG4 file specifications) inside an MP4 container. If you need an uncompressed file probably you need to create an .AVI or .MOV file"

-- do we just remove the option of uncompressed MP4?

**Comment by derwin12** [comment]
Can you try changing the name of the file to an .avi when you export it (not just renaming the resulting file). There is code that handles an .avi file differently.
I cant duplicate the issue using .mp4 but that can me different codecs installed on our PC's

**Comment by mcenerykwm** [comment]
Daryl,

If can't duplicate the MP4 display issue then agree could be local  codec issue - although primary computer recently purchased. 

Agree IF the uncompressed option is effectively not available  then removing "uncompressed" option should be considered to be removed....

Kevin

**Comment by derwin12** [comment]
Use of uncompressed AVI still appears to work.

**Comment by computergeek1507** [comment]
The "Compressed AVI" is created a MPEG4 in a AVI container. Not really a common format(it does load in VLC) Dan added the "Compressed MP4" which uses H.264 and works with the hardware decoder on the Raspberry Pi. "Compressed AVI" probably is using different settings with newer ffmpeg which maybe causing the issue.

**Comment by derwin12** [comment]
Dan addressed this in his commit.
