### ISSUE TITLE
Add option for Twinkle effect to always light 2 immediately adjacent pixels, to simulate randomly appearing "eyes"

### ISSUE THREAD

**Issue by SopherConklin** [xLightsSequencer/xLights#4755]
At VCS 2024 Steven King gave a great talk on how to do a very complicated submodel to generate random pairs of pixels lighting up as "eyes".   A great  Halloween effect, but a lot of work.   It appears if we added an option to always light 2 adjacent pixels on the Twinkle effect, this would do the same thing in a very straightforward manner.

**Comment by fone626** [comment]
On the single stand effect, select the FX tab and under that select "Halloween Eyes" on FX.
Does that do what you want it to do?

**Comment by SopherConklin** [comment]
My apologies, I am pretty new and I didn't know about that - I'm surprised that it wasn't brought up at VCS, where everyone was raving about Steven's complicated submodel to accomplish the same thing.  Provided a Render Style of Horizontal Stack is used, that FX works well.  Sorry to clog up the system with my ignorance!
