### ISSUE TITLE
Fade Effect for various effects do not work properly when the effect is put on the "node" level

### ISSUE THREAD

**Issue by Joemarthey** [xLightsSequencer/xLights#4756]
When placing an On effect, as well as other effects like Single Strand, on the Node level of a prop/string, the Fade Out transition does not work.  If you place this same effect on a group or model level it works as expected.  I am currently on 2024.15 and it appears this issue started around release 2024.12.
I have verified this in the Zoom Room with other users/developers.  
This transition is especially important for use on the Dimmer for moving heads.

**Comment by derwin12** [comment]
Works in .06, Broke in .07, further broke/changed again in .08

.06
![image](https://github.com/user-attachments/assets/bf03754c-f2c7-4bc5-b510-bce6eae1b4c8)

.07 went all dark
![image](https://github.com/user-attachments/assets/f1722621-b93c-4f0c-b6a8-bbaa227a15c2)

.08 renders but no fades.
![image](https://github.com/user-attachments/assets/e8ae197d-dd52-4b61-aa35-ff2d4ca9b847)
Bars and any effects as well
![image](https://github.com/user-attachments/assets/887272a7-1d1b-455e-973c-7157107ef93b)

**Comment by Joemarthey** [comment]
Thanks for verifying and adding more examples.

**Comment by derwin12** [comment]
@dkulp Dan .. is this the gpu rendering stuff?

**Comment by derwin12** [comment]
Dan has corrected this.

**Comment by Joemarthey** [comment]
Awesome, thanks for the quick responses.  I'm assuming it will work correctly when .16 is release?

**Comment by derwin12** [comment]
or grab the nightly to verify and work with..
