### ISSUE TITLE
Timing Track "Divide Timings" produces uneven divisions

### ISSUE THREAD

**Issue by SopherConklin** [xLightsSequencer/xLights#4769]
If you Select Timing Marks on a Timing Track, then choose "Divide Timings", the timings produced for various increments produce an uneven distribution of timing marks.  Divide by 2 and divide by 5 produce equal intervals.  Divide by 3, by 4, by 6 all create unequal intervals.   All "Divide Timings" settings should subdivide the existing Timings into equally sized new timings.

Here is a video of this:
https://youtu.be/EDiVok6Y_eQ

I have not provided a sequence, since it is trivial to replicate my example.

**Comment by dkulp** [comment]
If you have a one second timing on a 20fps sequence, and you divide that by 3, there isn't a way to have three even timings.
