### ISSUE TITLE
State creation flags cells as errors until new state is created

### ISSUE THREAD

**Issue by Poporacer** [xLightsSequencer/xLights#4774]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When you are trying to create a State definition on a model, the pixels entered are flagged as an error and you cannot save the State until another state value is entered and then deleted. 

**To Reproduce**

1. Open the State Definition of a model
2. Add a State Name
3. Enter a State value (note that the Nodes entry section turns red indicating an error and the OK button is disabled)
![image](https://github.com/user-attachments/assets/9659c469-8292-49fb-832a-63681ef46e3c)

4. Enter nodes in the Nodes entry section and tab out of the Node Entry section.(note that the Nodes entry section remains red indicating an error and the OK button is disabled)
![image](https://github.com/user-attachments/assets/35d4dade-94de-4fe2-a58a-468afb6eebb8)
5. Enter another State Value and the red error highlight now moves to the newly entered Nodes for the State Value.
![image](https://github.com/user-attachments/assets/f948a947-7ec7-47e9-9e65-59d19e2ae732)

You can work around this in 2 ways:

1. After you entered your State values add one additional state value and tab out. (the previous state value will now indicate a valid value and the new "dummy" value will have the error once you tab out of the cell.) You can then delete the "dummy" state and it will clear the errors.
2. When you create your State Values, enter the nodes BEFORE you create the State Values

**Expected behavior**
A clear and concise description of what you expected to happen and why.

Entering states should not flag items as an error that are not an error.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version [2024.15]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
I dont see this. In fact I cant tab out of the node entry box ... I have to press enter and it validates correctly. If i click out it also validates correctly. If i shift tab out of the cell it also works ok.

**Comment by SopherConklin** [comment]
I am also seeing this - I <Enter> to leave the Nodes field, but it marks it as Red and Greys out the OK button until I enter the next line.   I've been working in the States screen all evening and seeing this over and over.
![image](https://github.com/user-attachments/assets/c23fbfe9-c9dc-4bd2-8c09-4e78c5b34dd5)

**Comment by computergeek1507** [comment]
fixed with 4312af8635f595cf106b821d68fcbf8d26474811
