### ISSUE TITLE
Mouse randomly jumps around on Mac Mini M2

### ISSUE THREAD

**Issue by schreyack** [xLightsSequencer/xLights#4776]
**Describe the bug**
Mouse will randomly jump around when trying to click and drag effects.  (See attached video, where you can see it happen a few times.)  This will cause effects to suddenly move or otherwise do very unexpected and undesired things, such as an effect suddenly moving to a new location or getting drastically smaller/larger.  It has happened for a long time on Mac (it's not a new issue), but it finally got annoying enough for me to open a ticket on it.

**To Reproduce**
Open any sequence on a Mac Mini and drag an effect bigger or smaller.

**Expected behavior**
Mouse shouldn't jump.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac Mini M2 Ventura 13.5.1
 - xLights version 2024.15

**Additional context**
This makes editing and creating sequences really tedious since I'm constantly having to undo something weird that happened and repeat the action to get the desired result.  Happy to provide any additional details or logs you need to assist in troubleshooting.

**Attachments**
See video of screen capture attached.

https://github.com/user-attachments/assets/08d14adf-0ed8-40bd-a26a-591ef6ed3631

**Comment by derwin12** [comment]
Related to #3919

**Comment by cybercop23** [comment]
Seems to be fixed with the latest xlights and mac os.
