### ISSUE TITLE
Clicking on Update from Base Show Folder causes conflicts

### ISSUE THREAD

**Issue by Shoe6326** [xLightsSequencer/xLights#4778]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am trying to setup Base Show functionality.  If I have my Base Show set and also have my Show folder set to the same Base Folder, then I click on the 'Update' button... I am presented with a conflict msg for **EVERY** one of my props and then at the end of all those msgs, all my Controllers are dithered/cannot be modified.  Then I need to do a restore to get back to the ability to modify my controllers, otherwise I am dead in the water and cannot modify my controllers, etc. for my Base Show.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
See above.

**Expected behavior**
I would expect that the 'Update' button be dithered out when the Show folder is set to be the same as the Base Folder.

**Screenshots**
Not able to present screen shots without doing a restore of my backup.

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024.15

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
Next one, 2024.16
