### ISSUE TITLE
Matrix Model Flys off the display when used for non RGB curtain.

### ISSUE THREAD

**Issue by ChooChooMan74** [xLightsSequencer/xLights#4779]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When a matrix model is used with anything other than RGB Nodes (example, single color, single color intensity, strobe, etc), the model will fly off the display.  You then have to zoom way out to find it. Changing it back to any type of RGB nodes returns it to its origional location. Also, in 3d mode, the handles to move it remain at it's origional location, just the model flies off.

NOTE: This is a unique use case. We discovered this when helping someone model a DMX single color curtain light into xlights.

Note 2: We tried other models, seems to only affect the matrix.

**To Reproduce**
Create a Matrix. 1 string, 500 nodes, 25 strands 
Set String type to Non RGB (example, single color intensity)
Matrix Disappears, but can be found if zooming way out

**Expected behavior**
We expect the matrix to stay where it is

**Screenshots**
![image](https://github.com/user-attachments/assets/91f72160-4c3a-45c6-822d-98a4286aaef1)

![image](https://github.com/user-attachments/assets/57740f13-99c2-4c17-b85c-99625e04ed93)

**Versions (please complete the following information):**
We tried on 2 windows 10 machines, one running 2024.14, one running 2024.15

**Additional context**
Very unique case, but reporting just to see why it happens.

The way the model flies off the display depends on orientation of Horizontal and Vertical. This also only happens when the starting location is top right or top left, not the bottom right or bottom left.

**Attachments**

**Comment by Mark79864** [comment]
Context for this:
On Zoom a person asked if they could model their standard single colour light curtain in xLights. This is being connected with a DMX DC board.

The location which the matrix 'flys' off to depends on direction of the matrix.
Horizontal:
![image](https://github.com/user-attachments/assets/c7ad85dd-1d50-4ed2-b4da-2395582ec841)
Vertical:
![image](https://github.com/user-attachments/assets/02e41430-4a1f-4e46-96a3-07b4bf7f821c)

Clicking on the matrix and dragging moves this and the empty bounding box.
Using the bounding box scale handles also works to change scale. Larger scale results in larger distance away from the bounding box.
