### ISSUE TITLE
Add effects to model Imperfections, Random Variation, Analog simulation, Decrepit conditions

### ISSUE THREAD

**Issue by SopherConklin** [xLightsSequencer/xLights#4781]
In the digital simulation world, there is considerable interest in modelling analogue variations and imperfections in a digital regime.  Whether it is the non-linear behavior of a tube amp in a digital tube amp emulator, or the "Film grain" effect applied to video, or the "Tape Simulation" applied to digital audio, these all produce outputs which are objectively "worse" than their inputs, but are preferred by many consumers, either because of nostalgia for the original media, or a distaste for digitally perfect, flat, lifeless representations.

For light displays, the pure digital uniformness of color, intensity and timing has long been accepted as the standard.   And for large shows in active mode, which actually resemble Hollywood productions, this is appropriate.   However, some small shows are much lower energy and try to evoke a mood.   Examples are many Halloween scenes and also the "static lights" displays used for off show hours.   If I am modelling an ancient, decrepit, neglected Halloween graveyard, it is not consistent with perfectly uniformly lighted props.   My tombstone should have random variation in intensity,  the corners where the most wear would accumulate should be dimmer,  random variation in light intensity, maybe some random color drift, random timing variations between lights and the occasional light popping up like a very slow Twinkle would add a lot of character and mood to the scene.  A slow variation in overall light intensity, to model a bad wiring connection in an analogue wiring system is another example.  In other digital modes, these "Imperfection effects" are very popular and we should consider adding some capability in this direction as well.

The example of "imperfection" that made me think of this was in Jackie's class on States
https://www.youtube.com/watch?v=p23TEKDjVbQ
at 44:30 he gives a great example of shading his GummyBear to eliminate the perfect, digital uniformity and give the prop some character.   That's great, but rather than requiring everyone to make States for every prop, why not create effects that can do that same sort of things and more.   I'm not a programmer but I envision that these might be variations on the "Warp" effect - they would alter the effects in the layer below them.

Submitted for your consideration.

**Comment by keithsw1111** [comment]
There are many ways to achieve this already with layers of effects and the appropriate blend style. maybe a twinkle with an almost black and a average blend style. There are also shaders that could do this. I dont see the need to add this as a feature.
