### ISSUE TITLE
Mac change folders issues after bookmark token changes

### ISSUE THREAD

**Issue by cybercop23** [xLightsSequencer/xLights#4786]
Using TF and starting with 735, when trying to change show folders (that happen to be on a NAS) they won't change.

734 works... 735 and after not.
![image](https://github.com/user-attachments/assets/8d465013-f9cb-41b9-ab56-c257ef900ac8)

From the logs.. it looks like it starts the change... but never actually changes to the new show folder. If I save and restart, the show folder had not changed.
2024-09-03 14:49:47,527 8619855680 log_base [DEBUG] Closing sequence.
2024-09-03 14:49:47,527 8619855680 log_base [DEBUG] Cleaning up the cache.
2024-09-03 14:49:47,527 8619855680 log_base [DEBUG]     Cleaned up 0 items in the cache.
2024-09-03 14:49:47,527 8619855680 log_base [DEBUG]     Cache purge done.
2024-09-03 14:49:47,528 8619855680 log_base [DEBUG] Sequence memory released.

Note.. if i change to a newly created show on the NAS, it works... older show folders created last year or earliet this year... do not work.

**Comment by kylegrymonprez** [comment]
I looked into this with @cybercop23  since I could step through the code. After futher discussion, I suspected some sort of permissions issue. While @cybercop23 can still write to that directory, I created a folder in which I only had read and execute access and could reproduce the behavior.

In and around the bookmark tokens code, https://github.com/xLightsSequencer/xLights/blob/master/xLights/TabSetup.cpp#L161-L163 seems to not have access, and also not prompt the user. There probably should be a prompt here stating something went wrong, but I'm not convinced there isn't some other issue further upstream in the code. 

@dkulp can you think of something else with this code where access gets removed that needs to be changed in the way it's handled. I'm not familiar enough with the way mac handles file permissions requesting/expiring issues.

**Comment by thekev** [comment]
I'm having the same issue as #4825 except it was working fine until a crash. Now I can't open any show folder.

**Comment by cybercop23** [comment]
> I'm having the same issue as #4825 except it was working fine until a crash. Now I can't open any show folder.

What do you get? Are you stuck in Choose Base Show prompt and then exiting that a base folder must be chosen? If so, try a reboot. Just had a user with that issue and even after wipping settigns and trying with a new empty folder was still not working until be rebooted  the mac and all was well.

**Comment by thekev** [comment]
> What do you get? Are you stuck in Choose Base Show prompt and then exiting that a base folder must be chosen? If so, try a reboot. Just had a user with that issue and even after wipping settigns and trying with a new empty folder was still not working until be rebooted the mac and all was well.

Yes that same error, "...setting a show folder is not optional" message. 

I rebooted, and... ain't that somethin. That actually solved the initial error. Now I get past choosing a show folder, but then a new error:
```
Could not obtain access to /Users/kevin/Documents/xLights/Halloween 2023/obj/House-3D.obj
Try giving xLights permission to access to the directory.
```
It is running as my user (per `ps aux`). I can read that file in iTerm. xLights is granted access to my Documents folder in System Settings. But hold on there... 2023? I selected the 2024 folder. Ran a `s/Halloween 2023/Halloween 2024/g` in xlights_rgbeffects.xml and now all is well. 🤔 🤪 I copied the show folder last month.

**Comment by cybercop23** [comment]
That's cuz you copied your 2023 folder to 2024 and you left your 3d config still pointing to the old folder. Ask me how I know....

**Comment by thekev** [comment]
> That's cuz you copied your 2023 folder to 2024 and you left your 3d config still pointing to the old folder. Ask me how I know....

What's not so clear is how the resources in the old location were fine and accessible for the last week, until today. The same files in the new copy are readable without changing any permissions. ¯\_(ツ)_/¯

**Comment by cybercop23** [comment]
Because the token hadn't expired yet and now you are trying to access 2023 from 2024 (that has premission) but 2023 doesn't.

**Comment by thekev** [comment]
How is this fixed? I just built from master and still can't open a show folder. However, I was running an older build before I exited, then encountered this issue and decided to try the latest. I have not yet rebooted.
