### ISSUE TITLE
Output to Lights Icon

### ISSUE THREAD

**Issue by Dubbs2022** [xLightsSequencer/xLights#4787]
Apologies if this is already a known issue, but when I click the lightbulb icon to "output to lights" it doesn't turn yellow. Sometimes it will eventually turn yellow after about a minute, othertimes it just stays white even though the lights are being controlled.

**Comment by cybercop23** [comment]
Can't say that we've seen that. What OS, what version?

**Comment by derwin12** [comment]
Do you have auto uploaded enabled on the controller tab?

**Comment by Dubbs2022** [comment]
I'm using Windows xLights (Ver 2024.15 64bit), this was also happening on the previous version.

I'm not familiar with "auto uploaded" maybe that is my issue, how do I turn this on/off?

**Comment by cybercop23** [comment]
It' san option for each controller. Go to Controllers tab and look for Auto Upload Config...
While having that on, may be slower to start, it should upload config and then turn on the bulb.
If they are all unchecked already, hop on zoom, xLights -> Help -> Zoom
![image](https://github.com/user-attachments/assets/528a9870-344f-4f43-801a-7c96c35f5d76)

**Comment by Dubbs2022** [comment]
I don't have "auto layout models" configured, and I don't see the other two for my controller.

**Comment by cybercop23** [comment]
ok.. so that's not it then.. what ctrls do you have... take a screen shot of the left side that lists them all and all of the options across

**Comment by Dubbs2022** [comment]
I fixed it with what you said, one of my Pixel Sticks had the "auto upload" ticked on. Once I de-selected it, it worked.
