### ISSUE TITLE
Copying Warp effect doesn't copy"treatment" attribute correctly

### ISSUE THREAD

**Issue by brett-foy** [xLightsSequencer/xLights#4788]
Anytime you copy/paste any warp effect with a treatment setting of "in" or "out" vs. the default of "constant", the pasted effect resets the treatment to constant.   This is in 2024.15 but honestly I think has been around for the last couple of years.

See video for example.

let me know if you have any questions or need more info.

https://github.com/user-attachments/assets/34bd0d3a-9e3f-43b7-b9e2-5a3208a0891c

**Comment by derwin12** [comment]
This broke between 2022.07 & 2022.08.
Trying to trace it back to a commit but proving to be challenging.
