### ISSUE TITLE
Node Layout Font Color with Windows Dark Mode is to light

### ISSUE THREAD

**Issue by sporterfx72** [xLightsSequencer/xLights#4792]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When Dark Mode is enabled in Windows and you go to the Node Layout window, the font is white on light colored cells. It is hard to read with this color combination. You have to select the cells to be able to see it or open in browser to see it.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Right click on any model and select "Node Layout" 
2. The text is white on light blue and green

**Expected behavior**
The font color for the cells should override the Windows font color and set it to black. The other dialog text is ok.

**Screenshots**
![image](https://github.com/user-attachments/assets/65b59dec-e602-472e-ab60-46f30dae240c)

![image](https://github.com/user-attachments/assets/8fecedcf-a74a-4d63-944a-3a4259acca9b)

**Versions (please complete the following information):**
 - OS: Windows 10 with dark mode enabled
 - xLights version 2024.15

**Comment by kylegrymonprez** [comment]
I'm taking a look at this - agree that the white font is hard to see.

**Comment by kylegrymonprez** [comment]
thoughts on these colors? 
![Uploading Screenshot 2024-09-06 at 12.36.39 PM.png…]()

**Comment by kylegrymonprez** [comment]
Came up with some colors after some googling.....
![Screenshot 2024-09-06 at 12 36 39 PM](https://github.com/user-attachments/assets/9bbad9d1-8fe7-4fae-92ac-2cc9fb545568)

**Comment by derwin12** [comment]
Is it (already) a preference? Check the last 2 items on the preference table..

**Comment by kylegrymonprez** [comment]
That doesn't appear to affect the HTML in the node layout unless I'm missing something
