### ISSUE TITLE
Indiv Start Channel for model Cube not calculating correct Univ/Chs per String

### ISSUE THREAD

**Issue by kjudd1212** [xLightsSequencer/xLights#4797]
**Describe the bug**
Check box the the Individual Start Channel for the Cube model are not adding up the actual number of channels for the model itself. Its only counting 36 channels per string. Other models are working as it should with Indiv Start Channel.

**To Reproduce**
1. Go to Layout
2. Click on Cube model
3. Scroll down to Indiv Start Channel and check box
4. See string not calculating correct universe/channel

**Versions **
 - OS:  Windows 10
 - xLights version 2024.15
 
![Capture5](https://github.com/user-attachments/assets/388e10c8-0b5b-4435-910e-bb252b7237c2)

**Comment by derwin12** [comment]
Please attach a tools->package logs so we can get your layout.

**Comment by derwin12** [comment]
I dont think you should even be able to get to individual start strings .. you show only 1 string in the pic .. so where is it getting 18 Strings in the drop down.

**Comment by computergeek1507** [comment]
You are running out of universes on the controller and it is overlapping on the next controller.

**Comment by kjudd1212** [comment]
Attached package log.  

I moved some of the models around. Now the Cube model (pixel forest) starts at Universe 104:1 and ends at 131:54 however the individual strings stop 106:97. Each string of the "Indiv Start Channel" is shown as 36 channel each even though the model is 32W x 12H x 12D.....144 pixels or 432 channels per string. 

![Capture6](https://github.com/user-attachments/assets/aa3cc604-75ef-444b-a24e-5074e784a883)

[xLightsProblem.zip](https://github.com/user-attachments/files/16924126/xLightsProblem.zip)

**Comment by derwin12** [comment]
You should not even be able to do individual start nodes .. checking your attached file..

**Comment by derwin12** [comment]
Each string is 36 channels since each string represents a stake - ie 12 pixels. 36 channels.
Never seen this back door used like this. I dont think it was ever meant to be used like this. Defer to Scott here.

**Comment by computergeek1507** [comment]
I'm unsure if this feature should have been skipped for cube models but it was not implemented in the code. Currently it is using the Cube Width and not the String Count.

**Comment by derwin12** [comment]
Closing as the individual start string request has other similar/duplicate tickets.
