### ISSUE TITLE
genius long range still not fixed for pushing updates and channel b

### ISSUE THREAD

**Issue by wizzard333333** [xLightsSequencer/xLights#4798]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug** The bug comes from updating to the newest version of xlights it somehow turns off b channels on a genius long range controller.  To make the the bug happen update to the newest version. push a update file to a genius long range and watch your b channels appear on the controller but not work again/

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
to import a b channel and control output

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version 2024.15
[genius file bad.json](https://github.com/user-attachments/files/16924286/genius.file.bad.json)
[genius file good.json](https://github.com/user-attachments/files/16924287/genius.file.good.json)
[xLightsProblem.zip](https://github.com/user-attachments/files/16924293/xLightsProblem.zip)

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by wizzard333333** [comment]
now when i try to add a dmx channel it crashes. 
[xLights_dbgrpt-22324-20240914T222004.zip](https://github.com/user-attachments/files/17004427/xLights_dbgrpt-22324-20240914T222004.zip)
[xLights_dbgrpt-22324-20240914T222004.zip](https://github.com/user-attachments/files/17004428/xLights_dbgrpt-22324-20240914T222004.zip)

**Comment by derwin12** [comment]
Can you please check the latest release. @computergeek1507 Scott  has pushed a fix or two..

**Comment by wizzard333333** [comment]
just did the update to 16. pushed out config files to both genius controllers and it still corrupts the files. If i make a manual file by hand and save it that works. So, its still not what needs fixed. :(

**Comment by derwin12** [comment]
Thanks for the update David. Get your latest firmware updates here
https://experiencelights.com/firmware
