### ISSUE TITLE
Issue with Controller Visualizer and Smart Receivers 

### ISSUE THREAD

**Issue by ZacharyCloutier** [xLightsSequencer/xLights#4800]
I am having a problem with the controller visualizer where if you have a prop that starts on a smart receiver it doesn't cascade to the next receiver correctly.

For example, you have a 4 port prop that starts on 2b of a 8 port smart receiver instead of port 4 of the prop going on port 1a of the next receiver it goes to 1b.

![image](https://github.com/user-attachments/assets/72ebc231-9e68-4354-bcde-ad1f8c6fe2c8)

**Comment by ZacharyCloutier** [comment]
Like this? That doesn't work. Just a note I am using a Genius Long Range Controller.
![image](https://github.com/user-attachments/assets/53ce249e-416f-442d-a454-f5f8dca08be2)

**Comment by cybercop23** [comment]
Yeah... that won't work. Once set to B, it will not wrap to A on the next port. Youc an cascade down from B->C and back to B if you have more strings, but it won't wrap B->C->A->B.

**Comment by ZacharyCloutier** [comment]
Yes, that is what I figured out but it should if it is moving to a new receiver it should start at A. I can cascade the remotes but it won't ever go from B->A or C->A etc it always starts at what the first sting is set to and that should not be the desired behavior it should always start at the first available so in this case A .

**Comment by computergeek1507** [comment]
did you set the cascade length under the "Cascaded Remotes" section?

**Comment by ZacharyCloutier** [comment]
Doing that makes it go to a C receiver I want it to go to a on the next port. So for this example I want what is on port 5B to go to 5A.

**Comment by computergeek1507** [comment]
As Alex said, that would be non-continuous strings which is not supported.
