### ISSUE TITLE
Expose to the users the hidden buffer rotation of Vertical Buffer Layout

### ISSUE THREAD

**Issue by SopherConklin** [xLightsSequencer/xLights#4802]
"Vertical Buffer Layout" on the Submodels screen seems to be a relic of the past.
The label is not clear or intuitive for anyone who hasn't been using xLights for 10 years.  What it actually does is rotate the buffer 90 degrees CC.  Now, "Vertical Buffer Layout" isn't very explicit - rotating 90 degrees CW would give a "Vertical Buffer Layout" and rotating 90 degrees CC would also give a "Vertical Buffer Layout".  Users should be able to tell what a checkmark is actually doing from the attached label and not have to perform experiments to figure out what it is doing.

I would suggest the label be changed from "Vertical Buffer Layout" to "Rotate Buffer 90 CC".

Another suggestion besides revising the cryptic, nonintuitive label,  is to not HIDE the buffer rotation.  As shown in the video, there is no way to know within the sequencer that the buffer for a submodel has been rotated 90 CC.   I suggest that instead of just using Transformation: None as a default for every submodel in the sequencer, it would be much more intuitive and clear if submodels with "Vertical Buffer Layout", or the better "Rotate Buffer 90 CC" in the Submodels screen were brought into the sequencer and given the  default of "Transformation: Rotate CC 90".   This would require a simple check when adding an effect to a submodel and if "Vertical Buffer Layout" is set on that submodel, put in "Rotate CC 90" as a default instead of None - and ensure that the buffer is not rotated by this default state, since it has already been rotated.  This allows the sequencer Layer Settings to display the actual rotation of each submodel buffer relative to the original position.    
This "true indicator" of buffer rotation would allow the user in the sequence to see what the buffer rotation actually is.  I can imagine someone putting an effect on a submodel only to see the default Transformation is "Rotate CC 90" and that triggers them to recall that last week they were in the Submodels screen and went through them and understood why the "Rotate Buffer 90 CC" was enabled there and recall the reason for all that.   Now, by having an indicator within the Sequencer,  all is made clear and there aren't any "hidden" buffer rotations anymore.

Video:
https://youtu.be/k3iCrP5GhrM

No sequence included as it is trivial to reproduce

**Comment by dkulp** [comment]
The "Horizontal" and "Vertical" notations are used EXTENSIVELY throughout xLights.   Matrices have Horizontal and Vertical layouts, buffer styles have vertical and horizontal stacked options, etc....   I see no reason to change that as it's something that fundamentally needs to be understood.   However, a GOOD enhancement would be to change the labels from "Top, Line #, Bottom" to "Left, Col #" Right" in the submodel dialog when the option is set.   That would definitely help clarify that.

The idea of changing it to always using the Rotate on the buffer would not work at all.  If the submodel is in groups, then applying a transformation like that just for the particular models that need it is not possible. 

So, to use Keith's words, "No" except for the idea of updating the grid row labels which is a good idea.

**Comment by SopherConklin** [comment]
Anything to help new users understand what that checkbox actually does would be good.

**Comment by SopherConklin** [comment]
I'm undaunted in my decision to report Quality of Life improvements.   You can always ignore them, though perhaps not as ungraciously as has sometimes happened.  Put them on the list, maybe some day resources will increase.  They could also provide fodder for anyone updating the Manual to put in some explanations and/or clarifications.  The good news is I'm not finding a bunch of bugs to report.

**Comment by derwin12** [comment]
Headings updated by Dan.
