### ISSUE TITLE
MP4 used as sequence video and audio are now flagged as Corrupted

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4805]
As I go thru sequences and batch render for this year all(?) of my sequences that use an mp4 are now flagged as corrupt or invalid.
It seems it cant pull in the audio and set the duration - they come in as 0s in length.
Anything that can be tweaked perhaps with the new ffmpeg library or do I need to reencode them?
![image](https://github.com/user-attachments/assets/fce6aa05-767a-460b-8739-b15154364af9)

https://github.com/user-attachments/assets/27cbf708-3e1e-4f9c-a587-a76de43f1aa7

https://github.com/user-attachments/assets/2f51a289-9287-4d19-ac21-520134820e03

**Comment by kylegrymonprez** [comment]
I dont see the raw file having any audio in it - is there supposed to be audio? Seems to be getting caught in an audio requirement assert AudioManager.cpp around 1967

**Comment by cybercop23** [comment]
hmmmm.. wondering if this was the new fix to get the Prepare Audio working again.

**Comment by derwin12** [comment]
I have at least 6of these that worked before. I can of course strip the
audio but I feel this might be a bigger issue.

**Comment by derwin12** [comment]
I cant even get the video to show on my pc - but it shows in github. Even if the audio isnt working .. the length should still be there.

**Comment by derwin12** [comment]
I will try much earlier versions of xlights .. perhaps it is something more like it is grabbing the matrix video rather than the source video. I have both - one has audio, one does not. Stay tuned.

**Comment by derwin12** [comment]
Confirmed .. what happened is the show folder path moved, so as I open each sequence it goes searching for the .mp4. It finds the non-audio version of it first. This version I have for the matrix. It was found before it found the correct .mp4 in the videos subfolder.
