### ISSUE TITLE
Submodel editor dialog shows different number of pixels than Custom Model Data definition dialog

### ISSUE THREAD

**Issue by abanchieri** [xLightsSequencer/xLights#4808]
**Describe the bug**
I have a large, non-rectangular custom model matrix consisting of 21,184 pixels. In the initial layout (before building the prop), I defined the custom model as a serpentine series of rows. Each successive row begins with the next node number from the end of the previous row. I also included a "border" submodel to display a 2 to 3-pixel-wide border around the array.  Sequence testing in xLights in this 21316 pixel array showed that this custom model worked as expected. (This is also how I made a similar 3000 pixel array that was in my show for the past 2 years)

During the prop build, I needed to skip a few pixels whenever the strand changed direction. My approach was to omit these node numbers in the Custom Model Data definition, effectively treating them as null pixels within the strand. Including the skipped (null) pixels my new count is 21316 pixels in this prop

After updating the Custom Model data with these skipped values, I proceeded to define the border submodel. However, I noticed that the maximum pixel number in the SubModels editor (21,184) differed from the Custom Model definition (21,316). The discrepancy is 132 nodes, which corresponds exactly to the number of skipped (null) pixels in my custom model.

I spent some time debugging the issue with the Zoom Room support team, and they suggested submitting a bug report. 

**To Reproduce**
1. Copy attached excel file to a Custom Model Data definition.  The array is 250 pixels wide x 120 pixels tall
2. Create a submodel using "21184-21316,21116-21123,21046-21053,20974-20981,20900-20907,20824-20831,20746-20753,20666-20673,20586-20591,20502-20509,20416-20423,20328-20335,20238-20245,20146-20153,20052-20059,19956-19963,19860-19865,19760-19767,19658-19665,19554-19561,19448-19455,19340-19347,19230-19237,19118-19125,19006-19011,18890-18897,18772-18779,18652-18659,18530-18537,18406-18413,18280-18287,18152-18159,18024-18029,17892-17899,17758-17765,17622-17629,17484-17491,17344-17351,17204-17209,17060-17067,16914-16921,16764-16771,16612-16619,16458-16465,16304-16309,16146-16153,15986-15993,15824-15831,15660-15667,15494-15501,15328-15333,15158-15165,14986-14993,14812-14819,14638-14643,14460-14467,14280-14287,14098-14105,13916-13921,13730-13737,13542-13549,13352-13359,13162-13167,12968-12975,12772-12779,12574-12581,12376-12381,12174-12181,11970-11977,11764-11771,11558-11563,11348-11355,11136-11143,10922-10929,10708-10713,10490-10497,10270-10277,10048-10055,9826-9831,9602-9607,9376-9381,9148-9153,8918-8923,8686-8691,8452-8457,8216-8221,7978-7983,7736-7741,7492-7497,7246-7251,6999-7003,6749-6752,6499-6502,6249-6252,5999-6002,5749-5752,5499-5502,5249-5252,4999-5002,4749-4752,4499-4502,4249-4252,3999-4002,3749-3752,3499-3502,3249-3252,2999-3002,2749-2752,2499-2502,2249-2252,1999-2002,1749-1752,1499-1502,1249-1252,999-1002,749-752,1-502" as the row definition. (see screenshot below)
3. The submodel should show a border of pixels around the matrix. 
4. This is what I see. Note that the deviation from the expected border starts where my first set of skipped pixels are and exaggerates with each successive set of skipped pixels.
![image](https://github.com/user-attachments/assets/34356a57-849f-472e-834e-f35f211055ad)
5. Also note that the upper leftmost node number in the Submodel Dialog is 21,184. I expect that it would match the Model definition at 21,316 

**Expected behavior**
I expect that the node numbers shown in the SubModels definition dialog would match the node numbers as defined in the Custom Model Data definition dialog

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2024.15

**Additional context**
I have a pair of shadow models designed to distribute this large model across 24 ports on two controllers. Although I haven’t tested them yet, I anticipate that the issue may also affect the shadow models.

The Zoom Room team suggested a potential workaround: instead of skipping pixel numbers in the Custom Model Data definition, I should create a submodel that includes all pixels, excluding the ones previously skipped. Sequencing would then be performed on this submodel, ensuring that the pixels I want to omit do not receive any data.

**Attachments**
[Custom Model Node Numbers.xlsx](https://github.com/user-attachments/files/16988969/Custom.Model.Node.Numbers.xlsx)

**Comment by computergeek1507** [comment]
It's because you skipped nodes in the custom model. It would be better to include them in the custom even if they are not used. Submodels assumes continuous nodes, if not you have to decrease the submodels node numbers by the amount of pixels you skipped at that point.
