### ISSUE TITLE
Cannot upload from Xlights to FPP

### ISSUE THREAD

**Issue by GadgetAddict** [xLightsSequencer/xLights#4809]
**Describe the bug**
When I open Xlights and click TOOLS->FPP Connect, it displays my  FPP but the "upload" check box is disabled and selecting SEQ files to upload do not appear in file manager. There's also a the word "UNSUPPORTED" under the FSEQ Column. 

**To Reproduce**
1. Launch Xlights on MacBook running Sonoma  14.6.1 
2.  Click TOOLS - > FPP CONNECT
3.  my FPP is Discovered but the check box on the left side is disabled and I cannot select it 
4. Select the checkbox next to the sequence file named "boo-flood.fseq" and click Upload
5. In the status bar at the bottom of Xlights it says Upload Completed but no sequence files appear in the FPP file manager and none of the channels are uploaded .

**Expected behavior**
1. After clicking FPP Connect and seeing the discovered FPP device, I expect to be able to select the check box on the left side of the FPP to select this as the target destination.
2. I expect the sequence file and the channels to be uploaded to the FPP

**Screenshots**

**Versions (please complete the following information):**
 - OS:  Mac OS Sonoma 14.6.1,  
 - xLights version 2024.12
- FPP Version 5.4. FPP OS Build v5.3
- 

**Additional context**
My current network setup:
FPP is connected to router via Ethernet cable
Laptop is connected to router via Ethernet cable
FPP IP address set to DHCP (temporarily) and IP address is 192.168.0.120
Macbook IP address set to DHCP and address is 192.168.0.110

Troubleshooting: 
1. Downloaded the current FPP software from Git, used BalenaEtcher to flash the image to the Micro SD card
2. Navigate to the fpp.local (192.168.0.120) and completed the Initial Configuration, grew hard disk space, set time/date
3. In the FPP User Interface, clicked Help -> About -> Upgrade FPP but no updates available 

**Attachments**
screen recording at https://youtu.be/KNSNaW0P1jg
sequence is just flood lights / random colors - You can download sequence from iCloud ->  https://www.icloud.com/iclouddrive/03aRvowUgBotN3RNrKnkcOIag#boo-flood_%5Flights%5F30sec

<img width="1440" alt="cannot-upload-to-fpp" src="https://github.com/user-attachments/assets/946f62bb-3af0-4d41-843d-d72cce654cd0">

**Comment by dkulp** [comment]
You will need to upgrade your version of FPP to 7.5 (or 8.0).

**Comment by GadgetAddict** [comment]
Thank you Dan, I will do that. I appreciate your quick response.

**Comment by GadgetAddict** [comment]
For anyone with this issue, here's the solution.
I didn't have the most current version of FPP
1. download FPP from GitHub
2. Use BalencaEtcher to flash the image to the micro sd card
3. insert the micro sd card into the raspberry pi, connect power and network cord, 
4. using Chrome, connect to the FPP using the IP address or fpp.local
5. Complete the required fields on the initial configuration, finish setup, set time, grow file system, reboot FPP
6. Launch Xlights, click TOOLS->FPP Connect,  successfully discovered the FPP
7. Now the Check box is active and selected automatically, and I can upload sequences and models

Thanks to Dan for a faster than lightening response to my post.
