### ISSUE TITLE
XLights Crashes when renaming an imported Timing track

### ISSUE THREAD

**Issue by willkillyaquick** [xLightsSequencer/xLights#4811]
**Describe the bug**
XLights Crashes when renaming a Timing track from an SRT after it is imported.  You are able to rename it after XLights is relaunched as long as the sequence was saved before the renaming crash.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Sequence Tab
2. Create a new Sequence
3. Right Click on Timing Track Rows
4. Click Import Timing Track
5. Select a Timing track, in my case an SRT
6. Right click the newly imported timing track
7. Click rename Timing Track
8. Change the name in the Text box
9. Click Save
10. XLight Crashes

**Expected behavior**
XLights renames the Timing track without crashing

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version  2024.15 

**Additional context**
I did not try other timing track imports.  I have only experienced this with SRT files.

**Attachments**
https://www.dropbox.com/scl/fi/zed3zds2bvc7603udv32b/xLightsProblem.zip?rlkey=hchrbhdnud4gwdham1gjtcudm&st=0lrgq80k&dl=0

**Comment by derwin12** [comment]
Nothing in the log.. Can you attach this .srt file that you imported? (might have to zip first)
```
2024-09-15 09:15:26,159 21016 log_base [DEBUG]   Finalized last block of data.  Frames in block: 3.
2024-09-15 09:15:26,160 21016 log_conversion [DEBUG] End fseq write
2024-09-15 09:15:26,160 21016 log_base [INFO] fseq file done.
2024-09-15 09:15:26,160 21016 log_base [INFO] E:\Profile\Will\Documents\MyLightsChristmas\Sequence Halloween\Addams Grove\Addams Groove.fseq     Updated in   0.290 seconds
2024-09-15 09:15:32,453 21016 log_base [CRIT] Crashed: Fatal exception occurred.
```

**Comment by willkillyaquick** [comment]
[lyricpotato.en_US (3).zip](https://github.com/user-attachments/files/17007611/lyricpotato.en_US.3.zip)
Attached.  This was the Lyric file I had used.

**Comment by derwin12** [comment]
Able to duplicate .. see what I (we) can find..

**Comment by willkillyaquick** [comment]
The good thing is there is at least a workaround.  Save the Sequence and restart XLights before renaming the imported timing track works just fine.

**Comment by derwin12** [comment]
Hmm .. I had it crash the first time.. but now I cant duplicate it - using the latest master branch. Are you able to test with the latest nightly build?

**Comment by willkillyaquick** [comment]
I'm using the master branch.  It's not crash for me now as well???  When it was happening, It crashed 3 times in a row on me on a new sequence.  Is there a ghost in the machine LOL?   Maybe if fixes itself if for save one sequence after a first import?  I hadn't tried it after I had saved.

**Comment by willkillyaquick** [comment]
Oh you were asking if I can test with the Nightly.  I can see if I can do that this afternoon.

**Comment by willkillyaquick** [comment]
@derwin12 , Looks like the bug has cleared up?  Its not repeatable for me anymore.  I upgraded to the latest in the main branch and still no crash after renaming the track.

**Comment by derwin12** [comment]
Lets close this till we can replicate or encounter it again.
