### ISSUE TITLE
States: 2 bugs I've experienced when saving a state

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4812]
Some bugs I've noticed, maybe someone can try to reproduce in Windows.  I'm running the latest version of xLights.

States Dialog Bug 1:
Below is a screen shot of the creation of a State, in the State Dialog.  I am able to hover over the "Nodes" column and right-click to import a Sub Mode.  I can then select a "Forced Custom Color".  You are still able to click the OK and save it. You are not flagged for not having a State name preceding the Nodes selected column.  See first image below of an import Sub Model. 

If you go back into that state, xLights detects there is no State Name in the first column and the dialog will not let you exit till you put one in.

States Dialog Bug 2:
When starting a new State for a prop that has no sub models to import, I'll enter a label on to the State name.  Then I press the Tab key to advance to the Nodes field.  Then I'll begin click-and-drag on the model preview to the right to begin creating my the tab button.  The NODES column will have a red highlight that doesn't seem to disappear when I press tab to advance to the next block, and I'm unable to click OK to save the state.   I'll end up advancing to another State name and entering a character, pressing tab again, then going back to delete the state, just to allow me to open up the State's Dialog to click OK and SAVE the created state. See image number 2 for this situation

Thank you for looking.

Clyde L

![image](https://github.com/user-attachments/assets/5f11241d-7498-4260-ac39-bf15a8f099dc)

![image](https://github.com/user-attachments/assets/3a9ee988-7710-44f7-a6f6-26c2e4d5c9af)

**Comment by computergeek1507** [comment]
I fixed the issues with https://github.com/xLightsSequencer/xLights/commit/4312af8635f595cf106b821d68fcbf8d26474811 please retest when the next version comes out.
