### ISSUE TITLE
SanDevices new firmware supports DDP.  Currently Xlights will not allow DDP to be used for Sandevices

### ISSUE THREAD

**Issue by scuba** [xLightsSequencer/xLights#4813]
From the webpage on SanDevices.com

_"Version 5.050  adds the following:
The controller IP address is displayed on the browser tab. Controller name field working (finally). POST tests
display hardware error info on LEDs. Override 1 IP address readout now blinks 10 times for a digit with value 0. Support
added for W5500-based Wiznet modules. Suffix -W5200 or -W5500 added to firmware file names to denote which
Ethernet module is supported. Unused items such as gamma and web speed removed from web page. HTTP response
header changed to version 1.0. Support added for SACN Priority. **DDP support added**. "_

**Comment by computergeek1507** [comment]
I updated my E682 Controller to 5.050 and I could not figure out how to configure to work with DDP. While the Input option is there, all the start channels are still E131 based. Last time I looked there was no documentation on it as well.

**Comment by scuba** [comment]
I'm wondering what Jim might have meant by DDP support added.

**Comment by szaske** [comment]
I love my Sandevices controller, they've been rock solid for years. It would be cool to hear they're still being supported

**Comment by cybercop23** [comment]
You guys should get with Jim to a) see what he's already got in the FW or b) get him to include it 
Nothing can be done until that fe supports it.
