### ISSUE TITLE
All Pixels Groups Showing All Props Even When Not Supposed To

### ISSUE THREAD

**Issue by blun23** [xLightsSequencer/xLights#4814]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Just noticed all of my all pixels groups, including all pixels groups no yard, All pixel groups no Matrix etc... show every prop in my show whether or not they are actually in the group as you can see from the pic.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to layout
2. Click on any all pixels group
3. everything is highlighted in yellow even if it's not in group

**Expected behavior**
Only show props in Groups
![Screenshot 2024-09-18 at 12 40 14 AM](https://github.com/user-attachments/assets/dfc83755-b745-4d3d-8305-8c8d16e2dc42)

**Screenshots**

**Versions (please complete the following information):**
 - OS: Mac 14.6.1
 - xLights version 2024.15.1

**Comment by derwin12** [comment]
This is useless without the package logs/sequence.

**Comment by computergeek1507** [comment]
Enable show Submodel and groups

**Comment by blun23** [comment]
> Enable show Submodel and groups

Where would that be sir?  I didn't see it under preferences.  Also this is only all pixel groups.  Not in All House, All Yard or any of the other groups.

**Comment by cybercop23** [comment]
> > This is useless without the package logs/sequence.
> 
> I wouldn't say useless as you clearly can see in the pic there is a flake aye aye and mega flake not in the group but highlighted on the right. Sorry it was very late last night when I put this up. I can get the log at lunch

It is in the sense that we don't have the same data to try to replicate it and see where the issue is coming from.
As Scott mentioned, check those two checkmarks... could it be that you have groups in groups and somehow somewhere you've included it?

**Comment by derwin12** [comment]
Could be overlapping channels .. could be lots of things. It is not happening for our displays, so we need to see and test yours.

**Comment by blun23** [comment]
Got a quick break here for lunch.  I was moving stuff off dummy controllers yesterday to the controllers they will be on.  There shouldn't be any overlapping channels, but I'll check each controller and make sure nothing is overlapping there by chance.  I haven't seen this one before so I'll see what I can figure out.

**Comment by blun23** [comment]
[Layout Only.zip](https://github.com/user-attachments/files/17047813/Layout.Only.zip)

**Comment by blun23** [comment]
> Enable show Submodel and groups

I clicked those boxes and still the same.  I uploaded my layout.  I tried to add an effect but it wouldn't let me put an effect on those groups either.  Kept Crashing.

**Comment by dkulp** [comment]
You have the "1.0.00 All Pixels GRP" in a bunch of the other groups...
<img width="609" alt="Screenshot 2024-09-18 at 1 16 30 PM" src="https://github.com/user-attachments/assets/4616b43a-4131-4328-9770-beaaf5debabe">

**Comment by blun23** [comment]
Okay, I didn't knowing do that so I'll go fix those.  I have no idea how that happened.

**Comment by blun23** [comment]
You certainly aren't wrong though.  I'm clueless on this.

**Comment by blun23** [comment]
So for a quick fix, I just made a copy of that All Pixels GRP, Deleted the original and then renamed the Copy.

**Comment by blun23** [comment]
Do a quick check for groups in groups

**Comment by blun23** [comment]
> You likely can switch temporarily to your various backup show folders to guestimate the time/date that this broke.

I purge backups every 7 days, so it may be tough as I've been in building/set up mode and not much xlights mode last 2 weeks.  I do the majority of all the xlights stuff first 8 months and every waken minute of my spare time.  But I'll check the oldest one there and various other show folders as any time I'm gonna try something majorly different in the layout, I make a separate folder for that.  So I should have something from before this month.  If I figure out what I did to cause this, I'll let you guys know so maybe you can prevent others from doing it.
