### ISSUE TITLE
Version Changes

### ISSUE THREAD

**Issue by bobreese** [xLightsSequencer/xLights#4818]
At some point while running 2024.15 I installed a nightly there-by adding a .1 to the version.
After upgrading to 2024.16 the .1 remained.
Is this expected? 
Should the update have cleared the .1?
![Xlights Version](https://github.com/user-attachments/assets/81d6c51c-c12e-4ad6-8cb5-775ea6d869d8)

**Comment by derwin12** [comment]
Not showing that way for me .. any chance you grabbed another nightly?

**Comment by bobreese** [comment]
No.....
Can I uninstall without loosing everything?

**Comment by cybercop23** [comment]
> No..... Can I uninstall without loosing everything?

Yes... Show folder(s) are unrelated to the sw version itself.
