### ISSUE TITLE
Mac Crash on startup "could not create render pipeline for singleColorPrograms

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4820]
Not a lot of details but posting here for visibility.  Just during startup - no sequence (ie no shaders loaded).

".. is incompatible with this OS"

@dkulp 

![image](https://github.com/user-attachments/assets/ff17f4a8-4e24-4362-b46d-0c41bcd6f34d)

Can be closed if not enough info.

**Comment by cybercop23** [comment]
May be related (or not) but using TF when I open xLights I get this... nothing useful in the log file as you can see.
Trying to rollback on TF.
![image](https://github.com/user-attachments/assets/4e10c1c5-59c6-44c8-81e5-2b3dd083c3d3)

**Comment by cybercop23** [comment]
Last 15.1 TF worked... 
![image](https://github.com/user-attachments/assets/a9a1f95f-b591-42b2-9e43-569eff9a69ba)

**Comment by cybercop23** [comment]
okay.. this latest TF version seems to be the problem... looks like a mix of 16 (pre&post release) and the laest PR merge.
 
![image](https://github.com/user-attachments/assets/be5a7bd3-93c8-4b7f-be65-206d135184c6)

**Comment by dkulp** [comment]
Anything on the 3DR branch will definitely not work, it's completely broken.   I need to figure out how to disable the TestFlight builds for it for now.

**Comment by derwin12** [comment]
Closing this .. Seems reboots are clearing up the issue.
