### ISSUE TITLE
Can't fuly open xLights 2024.16 on macOS 15.0

### ISSUE THREAD

**Issue by jnpetersen** [xLightsSequencer/xLights#4825]
**Describe the bug**
When I open xLights 2024.16 on macOS 15.0, it prompts me to select my Show Directory.  I select it and am prompted with the following

![Screenshot 2024-09-22 at 11 03 32 AM](https://github.com/user-attachments/assets/a6f95af3-bf00-48f1-964b-0a1d47f66117)

**To Reproduce**
1. Open xLights
2. Select Show Directory from "Select Show Directory" window that pops up and Click Open
3. See error (the screenshot above)

**Expected behavior**
I would like xLights to open and bring me into the application so I can work with my Sequences

**Versions (please complete the following information):**
 - OS: macOS 15.0
 - xLights version 2024.16

No actual error screen, and no access to package the logs or anything as the app closes after clicking the OK button.

**Comment by derwin12** [comment]
Duplicate .. you posted the issue just minutes prior.

**Comment by jnpetersen** [comment]
It's not duplicate, its a different version with a different issue

**Comment by derwin12** [comment]
Its the same underlying issue ... mac permissions. I am sure Dan will  figure it out.
Likely a duplicate of this one as well
https://github.com/xLightsSequencer/xLights/issues/4786
