### ISSUE TITLE
Custom Windows Submodel, meteors effect doesnt match actual result 

### ISSUE THREAD

**Issue by ctoddward** [xLightsSequencer/xLights#4826]
**Describe the bug**
Meteors effect doesn't match actual result on Windows Custom model/submodel.

**To Reproduce**
See attached zip file with:
- Video of xLights screen, sequence running
- Actual resultsof house
- Custom Model - xmodel file
- Sequence with Meteor effect
- Submodel screen print

Create custom windows model
Create submodel - 3 verticle lines (left, middle, right)
Run sequence with meteor effect, Left
 
**Expected behavior**
Meteor effect wanted is falling 3 lines    
Actual results - outside lines go up, and middle line falls    

**Screenshots**
See attached

**Versions (please complete the following information):**
- Windows 10 Enterprise
 - xLights version [e.g. 2024.16]

**Attachments**
See attached zip file
[WindowDownstairs4.zip](https://github.com/user-attachments/files/17091893/WindowDownstairs4.zip)

**Comment by derwin12** [comment]
Looking at the submodel .. the first number 82, 1 and 65.  Are ALL of those at the bottom (or top)?
If not use reverse row to correct the submodel.
If you need help on this go to xlightszoom.com zoom room.

**Comment by ctoddward** [comment]
> Looking at the submodel .. the first number 82, 1 and 65. Are ALL of those at the bottom (or top)? If not use reverse row to correct the submodel. If you need help on this go to xlightszoom.com zoom room.

Yes, I already did this and I did get it to fall downward outside.   However, when I did this the xlights preview now shows the outside line going up.   So, the root of the problem is that the preview still does not match actual results.  

For the submodel, I tried to order from top to bottom for all.  I had 65-45, where 65 is at the bottom and 45 at the top.   I reversed it to 45-65.   I will continue to play with it, but welcome any suggestions.

**Comment by derwin12** [comment]
Please attach either tools->package sequence or tools->package logs.
This way we can test with your layout.

**Comment by ctoddward** [comment]
thanks so much for helping me with this.   I'm attaching a new zip file with logs & sequence.   Tried to simplify the sequence with only the one effect.  Note, i'm using FPP on Kulp8 controller when running outside.
package sequence="Meteors_Test.xsqz"; 
package logs="xLightsProblem.zip"

[meteor_test2.zip](https://github.com/user-attachments/files/17100729/meteor_test2.zip)

**Comment by derwin12** [comment]
Okay .. if you go into each of the vertical lines submodels, on the top & Bottom rows .. click reverse row. You need the bottom nodes for each row to be on the left of the list of nodes.
![image](https://github.com/user-attachments/assets/94c620a7-797e-4ea4-b519-b1eab8f23e6c)
![image](https://github.com/user-attachments/assets/bfc8c71f-efc1-4059-9f58-1c7e51329a77)

**Comment by ctoddward** [comment]
Called into the Zoom room and we found the solution.  It was my mistake in that the wire mapping did not match actual wiring.  Thanks for the support.
