### ISSUE TITLE
Xlights crashes on splash screen win11

### ISSUE THREAD

**Issue by DrewDogg92** [xLightsSequencer/xLights#4827]
**Describe the bug**
Xlights crashes on the splash screen. I have upgraded the software, the drivers an my OS.

**To Reproduce**
1. Click on Xlights Shortcut 
2. Xlights splash screen is displayed
3. Xlights Crashes

1. Run Xlights.exe /w in CMD 
2. Splash screen pops up 
3. Xlights Crashes 

**Expected behavior**
I expect Xlights to launch 

**Versions (please complete the following information):**
 - OS: e.g. Windows 11
 - xLights version 2024.16

**Additional context**
The software was working fine a week ago, but some update (GPU driver update, OS, or Xlights) must have broke something. I have tried uninstalling and re-installing many times with no luuck.

**Attachments**
Link to Logs
https://www.dropbox.com/scl/fo/yyi1scsf1oxcl9kd0aeme/AEMmNL50HRrnkX20bNpnqB0?rlkey=zus1rcwa8divzsholhvlcrydn&st=5yv64x38&dl=0

**Comment by cybercop23** [comment]
Install C++ Resistrib from this link....
https://xlights.org/releases/

**Comment by DrewDogg92** [comment]
Thank you @cybercop23  this solved the issue
