### ISSUE TITLE
Replay Selection - not working with music sequence 

### ISSUE THREAD

**Issue by deplanche** [xLightsSequencer/xLights#4828]
This was brought up in the zoom room last night, not my find, but wanted to post it here.

The Replay Selection button no longer will replay the entire sequence when it contains a music file (2024.16).  In an animation, if you hit this button without selecting anything on the timeline, it will play the entire sequence, and repeat it over and over again until you hit stop.  With a musical sequence, when it reaches the end of the sequence, it stops and does not repeat.  The only way to get it to repeat is to select a time period on the timeline, and hit the replay.  While the button is a "replay selection", it used to work such that if nothing was selected it would replay the entire song.

I can repeat this behavior in 2024.16 on windows. 

Tested on a different computer with 2023.09 installed and if a musical sequence is opened, replay selected is pressed, the sequence will play over and over until stop is pressed.

**Comment by cybercop23** [comment]
Just =...... :)
