### ISSUE TITLE
2024.16 Crashes on model selection

### ISSUE THREAD

**Issue by thekameleon** [xLightsSequencer/xLights#4830]
**Describe the bug**
When I try to select a second model after moving a model, xlights crashes.  It doesn't seem to be specific to any one model in my layout

**To Reproduce**
1. Select a model
2. Move it with the arrow handles
3. Select second model by either selecting it directly or selecting via model pane
4. Xlights crashes.

**Expected behavior**
Not to crash

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024.16

**Additional context**
Not sure if this is related but I just inherited a base show folder.
I can only reproduce this issue in 2024.16. 2024.15 seems to work fine.  Also it appeared the movement of models in the layout was sluggish a bit in 2024.16.  Hope this additional info helps.

**Attachments**
Attaching multiple crash reports as well as RGB Effects and Network files of base and main show folder

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
[xLights_dbgrpt-18288-20240924T115318.zip](https://github.com/user-attachments/files/17118111/xLights_dbgrpt-18288-20240924T115318.zip)
[xLights_dbgrpt-19788-20240924T114523.zip](https://github.com/user-attachments/files/17118112/xLights_dbgrpt-19788-20240924T114523.zip)
[xLights_dbgrpt-27156-20240924T115120.zip](https://github.com/user-attachments/files/17118113/xLights_dbgrpt-27156-20240924T115120.zip)
[xLights_dbgrpt-30116-20240924T115724.zip](https://github.com/user-attachments/files/17118114/xLights_dbgrpt-30116-20240924T115724.zip)
[main xlights_networks.zip](https://github.com/user-attachments/files/17118122/main.xlights_networks.zip)
[base xlights_networks.zip](https://github.com/user-attachments/files/17118126/base.xlights_networks.zip)

**Comment by cybercop23** [comment]
2024.16.1 just came out that fixes a crash issue updating models not having the right protocol defined. Although you said it is any model, worth trying it. Not seeing this issue on my Mac or nightly Windows.

**Comment by thekameleon** [comment]
Ill give it a try

**Comment by thekameleon** [comment]
I just tried the September 24th night build, which is post 2024.16.1, and everything seems to be working as expected. Ill close this ticket
