### ISSUE TITLE
FPS not displayed when playting sequence

### ISSUE THREAD

**Issue by DonMc33** [xLightsSequencer/xLights#4832]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
FPS in sequencer not showing when playing a sequence in the "View window" as in prior releases

**To Reproduce**
Play any sequence and look for FPS.... No longer showing being displayed

**Expected behavior**
FPS displayed when playing a sequence

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 11 and Mac Sequoia 15
 - xLights version 2024.14

![Screenshot 2024-09-25 084616](https://github.com/user-attachments/assets/6d0f7730-1c6b-4373-82ef-e32e980f1967)

**Comment by derwin12** [comment]
Do you have small wavewform selected in the preferences?

**Comment by dkulp** [comment]
It's no longer displayed as it just clutters the interface and doesn't provide useful information
