### ISSUE TITLE
Xlights crashes when I assign a model to my controller

### ISSUE THREAD

**Issue by szaske** [xLightsSequencer/xLights#4838]
**Describe the bug**
Xlights crashes when I attempt to map my model named UpperFlake LRG to my controller named "203-Windows"

**To Reproduce**
1. Select the model UpperFlake LRG in the model list view
2. Controller should be listed as "Use Start Channel"
3. Selected the Overflow menu on "Start Channel"
4. Select the radio button Controller
5. In the drop down menu select "203-Windows"
Xlights will crash

**Expected behavior**
That it would not crash

**Versions (please complete the following information):**
Windows 11 Pro v23H2
 - xLights version 2024.16]

**Attachments**
[xLights_dbgrpt-15400-20240927T012650.zip](https://github.com/user-attachments/files/17161430/xLights_dbgrpt-15400-20240927T012650.zip)

**Comment by szaske** [comment]
I dont see my attachment, so I'll try again
[xLights_dbgrpt-15400-20240927T012650.zip](https://github.com/user-attachments/files/17161418/xLights_dbgrpt-15400-20240927T012650.zip)

**Comment by cybercop23** [comment]
This has been fixed and a new version 16.1 is out, we're just waiting on the Windows version to be released. Download the latest/ nightly from Git, or you can bulk edit all your models and set Controller Protocol to ws2811 before you visualize it.
