### ISSUE TITLE
Create Timing from Effects Context Menu does not operate as expected

### ISSUE THREAD

**Issue by SopherConklin** [xLightsSequencer/xLights#4844]
When selecting Create Timing from the Effects Context Menu,  Timing Markers are not inserted for all selected effects.
This feature has a great potential to insert timing marks delineating the Start and Stop of all selected effects.  This can be extremely useful as a "map" to allow you to play with your effects and always be able to snap them to the original timings if desired.  The attached video demonstrates that even with as few as 2 effects, if they overlap but have separate Start and End times, all of the Start and End times will not be marked by the Create Timing  option.

I'm not aware of exactly how quantization is handled in the program (could be instantaneous state at each frame, forward or backward looking with a proximity tolerance, etc,)  so you obviously may need to modify my suggestions to be consistent with the protocol.  I have made comments assuming an instantaneous state at each frame is the current mode.

A possible algorithm is:
1. Go through list of selected effects, add Start and End times of each to a list
2. Sort list of times numerically
3. Quantize each time in the list to the nearest frame (if you are using a more sophisticated quantization procedure, such as forward/backward looking, it may be necessary to treat Start and End times differently for this - in this case 2 separate Start and End lists would be assembled)
4. Eliminate duplicate times.
5. Add a Timing Mark for each time

No sequence is attached as it is trivial to reproduce the simple example from the video.

A video demonstrating the issue:
https://youtu.be/R5wPwFsUAMw

**Comment by derwin12** [comment]
Timing tracks dont have layers (lyrics are a special case) .. so the first effect that creates the timing mark will win. Others on that same start pos will be ignored.

**Comment by cybercop23** [comment]
I don't think mixing and trimming marks is what users expect. In your last example the additioal start time is usless since it has nothing to do with either effect. I also, jsut a guess, don't think that it was intended to select ALL effects from al models/submodels and create timing tracks. That will be unusable.

**Comment by derwin12** [comment]
Create a timing track using metronome for 25ms .. see if your pc can handle it.

**Comment by SopherConklin** [comment]
Been there, done that,  PC handled it just fine!
