### ISSUE TITLE
Grouping size between Falcon F16 controller and xlights seems to be broken

### ISSUE THREAD

**Issue by MSD-xLights** [xLightsSequencer/xLights#4847]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I set the group size on a prop in xlights I can't upload it to the F16v3 or v4 controller.  It just says there was an error

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Layout Tab.
2. import the model Glow tree 01 (File attached)
3. Set the group count in the model to 40
4. Select save
5. select the controller tab
6. Select the controller
7. select Visualize
8. place the prop on one of the outputs
9. Close visualizer
10. Save
11. now upload to the controller
12. You should recive an error 

**Expected behavior**
When I look at the controller after uploading to it the uploaded model I created is not there
If the group count is one in xlights it is fine

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2024.15 64 bit

**Additional context**
If you leave the group set to one and upload it to the controller you can change the group to 40 just fine but if you ever re-upload it changes right back to 1
[Glow Tree Left 01.zip](https://github.com/user-attachments/files/17182299/Glow.Tree.Left.01.zip)

Please contact me with any questions

Sales@permatrack.us

**Comment by derwin12** [comment]
40x40 is too big :-) Did you want the glow tree to operate as 1 pixel - if so the model data should have 40 1's in there. Go into model data and right click, Convert to Single Node.

**Comment by MSD-xLights** [comment]
OK...  I am testing it tonight.   All controllers are updated.  The older update would not accept a group over 20.  I talked to David about it last year and it seems the latest one now does.   So I changed the model to all "1" and set the group in xlights and it seems to be working now.

I asked David about this first and he just directed me here... I am so sorry for wasting your time!

**Comment by derwin12** [comment]
If you need further help hop on xlightszoom.com
