### ISSUE TITLE
Crash when I select my Matrix model in layout

### ISSUE THREAD

**Issue by szaske** [xLightsSequencer/xLights#4857]
**To Reproduce**
1. Open Xlights using my attached layout.
2. Switch to Layout tab
3. Scroll to my model named "Matrix"
4. Left click on it
You'll see Xlight crashes

**Expected behavior**
Expect no crash and that I can edit the model settings

**Screenshots**

**Versions (please complete the following information):**
Windows 11 Pro 23H2
Xlights 2024.16

**Attachments**
[xLights_dbgrpt-5372-20241001T233751.zip](https://github.com/user-attachments/files/17220701/xLights_dbgrpt-5372-20241001T233751.zip)

**Comment by szaske** [comment]
Okay just downloaded and tried last weeks 16.1 build and that one does NOT crash, so this may have been fixed recently.

**Comment by cybercop23** [comment]
Yup.
