### ISSUE TITLE
Faster way to find effects with Canvas mode enabled

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#4867]
I when doing a Check Sequence, some effects have Canvas mode enabled which they are normally not used on.  Is there a way to use the "Select Effects" dialog to include searching for effects with a Canvas mode "checked".  That way we can update our sequences quickly and avoid having the Check Sequence error. See image below with a checkbox added to the Select Effects dialog.  Activating the check box here would only list the specific effects that have Canvas mode "checked".  Would help tremendously to find and fix these sequencing errors and help improve rendering.

Thank you for looking,
ClydeL

![image](https://github.com/user-attachments/assets/99161598-9728-4282-9925-8946c54c714d)

**Comment by derwin12** [comment]
Use the other search feature/window.. Select Search Effects
![image](https://github.com/user-attachments/assets/c1c0c86c-e004-49dc-aed4-b789adf67ff0)

**Comment by Clyde-L** [comment]
Thank you for adding it to the Search panel.  My next ask would be for an icon to open up this panel.  Something like the Display Elements or Effects Assist.  Some new icon to click and be able to display this easily instead of navigating through the file menus.
