### ISSUE TITLE
In the Edit Display Elements screen, change "Make Master" to "Copy to Master View"

### ISSUE THREAD

**Issue by SopherConklin** [xLightsSequencer/xLights#4868]
Make Master is unclear and unintuitive.
Without knowing the details of the implementation "Make Master" can mean either 1 of 2 things:
1.  Make the sequence use the newly defined view as its "Master" instead of the "Master View" it was previously using.   Presumably, if you wanted to make future changes to the "Master" that the sequence is using you wouldn't make those changes to the old "Master View" that isn't being used by the sequence anymore, you would make the changes to your newly created View (whatever you named it), that is now being used by the sequence instead
2. Copy the selected View into "Master View" which is always used by the sequence

"Make Master" does not make it obvious which of these 2 is meant - "Copy to Master View" more clearly communicates what is happening and makes it more intuitive that "Master View" is always used by the sequence.

**Comment by cybercop23** [comment]
Make master seems to be very clear and 1000s of users get it, Not going to change that and retrain all the user base.
