### ISSUE TITLE
Full Crash

### ISSUE THREAD

**Issue by McCoyCOREUSA** [xLightsSequencer/xLights#4871]
v 2024.16.0
v2024.16.2
Edition	Windows 11 Home
Version	23H2
Installed on	‎10/‎7/‎2023
OS build	22631.4249
Serial number	PF3C648C
Experience	Windows Feature Experience Pack 1000.22700.1041.0
--------------------------

I've been leaning xLights loaded on my laptop and after a while (maybe an hour or so) I come back and xLights is no longer running. I upgraded to 2024.16.2 and same issue.

I have nothing running in xLights. It's basically idle. 

No crash errors or anything. It's just like it closed automatically. And unsaved work is lost.

**Comment by derwin12** [comment]
Please upload tools package logs after the crash.

**Comment by McCoyCOREUSA** [comment]
Sorry, totally forgot.
[xLights_l4cpp 2024-10-08-001.txt](https://github.com/user-attachments/files/17300746/xLights_l4cpp.2024-10-08-001.txt)
[xLightsProblem 2024-10-08-001.zip](https://github.com/user-attachments/files/17300747/xLightsProblem.2024-10-08-001.zip)

**Comment by derwin12** [comment]
I dont see a crash .. it looks to be following the normal quit/close/exit code - like something just wants the app to close.

**Comment by McCoyCOREUSA** [comment]
Correct. Wasn't sure how to describe it. I leave it for an hour or two, come back and it's closed. I didn't close it.

However, while this happened a couple times, it hasn't done it for the past couple of days.

**Comment by derwin12** [comment]
Going to close this as we cant duplicate it  .. feel free to reopen if you can find a reproducible case.
