### ISSUE TITLE
Crashing when setting the controller

### ISSUE THREAD

**Issue by GorillaHam** [xLightsSequencer/xLights#4872]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'Layout and setting controller to 192.168.0.13 Univ 60, start at 1
2. Click on 'Prop'
3. Scroll down to 'controller to add for the prop'
4. See error  - Crash report 
[xLights_dbgrpt-80756-20241008T223840.zip](https://github.com/user-attachments/files/17301298/xLights_dbgrpt-80756-20241008T223840.zip)

**Expected behavior**
A clear and concise description of what you expected to happen and why. Only on this prop it crashes Xlights

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...] Windoes 10 Pro
 - xLights version [e.g. 2019.37] 2024.16

**Additional context**
Add any other context about the problem here. Now any additional prop I attempt to set the controller on crashes

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by GorillaHam** [comment]
No Sequence used

**Comment by cybercop23** [comment]
Fixed in 2024.16.1. you can download it from the Latest Releases in Git or wait until .17 is out on Windows.
