### ISSUE TITLE
DMX Brightness Value Curve Broken

### ISSUE THREAD

**Issue by kbostick88** [xLightsSequencer/xLights#4875]
In older version of xlights, you could set a value curve on the brightness value and it would adjust the DMX value/effect. Especially helpful for moving heads. Brightness no longer controls the DMX value. 

**To Reproduce**

Set a value on a DMX effect, go to the brightness adjustment and set a value curve. DMX is not adjusted. 

**Expected behavior**
Previous versions (Prior to DMX Moving Head ADV Model) you could use a value curve to adjust DMX values.

**Versions (please complete the following information):**
PC and Mac 
at least xlights 2024.10>current 

**Additional context**
Many older sequences that utilized this previous feature are now broken. 

**Attachments**
[DMX Brightness Issue.zip](https://github.com/user-attachments/files/17321199/DMX.Brightness.Issue.zip)

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Brightness where?
 Here? (appears to work)
 
![image](https://github.com/user-attachments/assets/68176d85-5b0a-4baa-8e3d-5b5bfadfdf47)

**Comment by computergeek1507** [comment]
VC with induvial on effects on the node level work for me. More info Please.
![image](https://github.com/user-attachments/assets/292c4838-1faa-40f3-9c47-ed9f35914f1c)

**Comment by derwin12** [comment]
Kyle - can you reopen if this is still an issue.
