### ISSUE TITLE
Text for the blue-side size/location information is very hard to read

### ISSUE THREAD

**Issue by DPattee** [xLightsSequencer/xLights#4878]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Blue on black is almost impossible to read. <img width="552" alt="Screenshot 2024-10-10 at 2 52 32 PM" src="https://github.com/user-attachments/assets/97711a91-35e6-4b80-b5ad-c4c23458d699">

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS 14.7
 - xLights version 2024.16.1

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by Unit-108** [comment]
Also seeing this still with Dark Mode on the Map Channel window for groups, hope this helps bump this as an overall need to look into.

**Comment by djulien** [comment]
Yeah, very hard to read in dark mode!  A couple of things I've found that help are to highlight items in order to read them (which is tedious), or to hold a phone (camera app) up to it - the camera seems to be a little more sensitive to blue than human eyes.

**Comment by derwin12** [comment]
Go to file preferences .. colors .. last column .. change the blue to something else.

**Comment by derwin12** [comment]
Reeopen as the original request was for something else .. that still needs to be addressed.

**Comment by Unit-108** [comment]
> Go to file preferences .. colors .. last column .. change the blue to something else.

LIFE SAVER!!! I closed my ticket on this, thank you for mentioning it. Maybe that should default to a different color when Dark mode is detected. Hope anyone else that runs into this can find this post at least.

**Comment by derwin12** [comment]
Scott what do you think next season we just have 8? color choices and use those and let the user just select them. Basically not have anything hard coded?

**Comment by dkulp** [comment]
Personally, I think the entire ColorManager should be tossed and just stick with sane system level colors for almost everything.  It DEFINITELY should also be stored as an app preference and not a show. folder settings.   Drives be crazy to see the element list in "light mode" when I'm opening others shows/sequences.
