### ISSUE TITLE
xLights 2024.16.1 hangs & crashes macOS 10.15

### ISSUE THREAD

**Issue by StockyDoors** [xLightsSequencer/xLights#4880]
xLights hangs & crashes when selecting Layout or Sequence Tab from Controller tab after opening app
Problem is evident on 2 different machines when tested.

1. Open app
2. Click on Layout Tab or Sequence Tab
3. System hangs & crashes, see error

![Screen Shot 2024-10-11 at 11 08 11 am](https://github.com/user-attachments/assets/b7efc3f7-9d46-41d8-8115-073a25276930)

iMac 13,2 - mac OSX 10.15.7
MacBook Air 5,1 - mac OSX 10.15.7

xLights version 2024.16 & 2024.16.1

https://www.dropbox.com/scl/fi/t08n5hatsiep3xd9enflv/xLights-2024.16.1-Hang-Crash.rtf?rlkey=7hzpd30daunkuuyddks33q0ef&st=j2vkoaaf&dl=0

**Comment by puppycrack** [comment]
Having exact same issue.  Upgraded from 2023.18 to 2024.16.1 and xLights crashes when going to Layout or Sequences Tabs.

Late 2012 iMac, 3.4Ghz Quad-Code i7; 16GB Memory, NVIDIA GeFoeceGTX 680MX 2GB
OSX 10.15.7

[xLightsProblem.zip](https://github.com/user-attachments/files/17350489/xLightsProblem.zip)

**Comment by dkulp** [comment]
Honestly, unless someone with access to MacOS 10.15 jumps in and debugs this, it's unlikely to be fixed.   I'll likely tag xLights as having a macOS 11 or 12 minimum and be done with it.    I was planning on waiting until January to move to macOS 11, but if it doesn't work anyway, could easily do it sooner.

**Comment by puppycrack** [comment]
Understood on supporting such an ancient OSX version.  For what it's worth, 2024.02.1 (latest in your archive) doesn't crash.

**Comment by StockyDoors** [comment]
Yeah that version runs without issue, but just wondering if there’s a copy of 2024.15 available? That was the last version that ran smoothly for me & also supports the Baldrick boards I’m running

**Comment by derwin12** [comment]
Code updated to require Mac OS 11 or higher.
