### ISSUE TITLE
XLights/ WLED DDP issue (4 channel nodes)

### ISSUE THREAD

**Issue by Fonzi03** [xLightsSequencer/xLights#4882]
Please see full details here: https://github.com/Aircoookie/WLED/issues/4141
I posted first in WLED thinking the issue was there since this works perfectly on my F16v4

![image](https://github.com/user-attachments/assets/196ea37b-7d84-48ce-bfe6-b90bf57f3734)

cliff notes:
Xlights configuration
![image](https://github.com/user-attachments/assets/0a59e1e1-70d3-443a-9b47-5420004815a5)

WLED Configuration
![370106986-96c59288-00df-4702-8f40-a5c67cae0c00](https://github.com/user-attachments/assets/6acd8e0d-a79c-4d1a-882f-ce97ba47e3db)

When sending R, G, B, or W I get this:
the pixels show up black, red, green, blue (repeat), each color change advances the pattern one pixel. 
![374766937-cc8a9566-8d5a-411a-b081-8b14793838ca](https://github.com/user-attachments/assets/2eaba790-0aa4-4e15-b347-9f8326ac2c39)

The WLED guys last mentioned this:
"There is reference in the code to how 4 channel data is identified being "data type 0x1B (formerly 0x1A)" - I have no context for when/why this change was made, but it might be xLights is sending 0x1A still? "

I have more pictures and full details in the WLED post as well as Wireshark captures.

When WLED sends 4 channel DDP to another WLED instance it works as expected according to them.

**Comment by dkulp** [comment]
Not likely to change in xLights...  the outputs have no knowledge of the color order, it's just a big block of channels.   Plus, for controllers that  have multiple outputs, it could be a complete mix of RGB and RGBW with some strings being RGB and some being RGBW.

**Comment by computergeek1507** [comment]
If you use E131 WLED allows receiving 4 channels LED data. But I do agree with Dan, WLED  does things differently than most controllers and is harder to support in xLights

**Comment by Fonzi03** [comment]
> Not likely to change in xLights... the outputs have no knowledge of the color order, it's just a big block of channels. Plus, for controllers that have multiple outputs, it could be a complete mix of RGB and RGBW with some strings being RGB and some being RGBW.

Do you know what WLED isn't doing correctly? If so I think they would fix it but they claim their end is fine.

**Comment by Fonzi03** [comment]
> If you use E131 WLED allows receiving 4 channels LED data. But I do agree with Dan, WLED does things differently than most controllers and is harder to support in xLights

I'm not worried about there configuration portion/setting up the controller. 

Moreso just getting the pixel data correct. I imagine it should be a standard so there's not really a reason it shouldn't be working unless im missing something

**Comment by computergeek1507** [comment]
You have too main options for handing 4 Channel LEDs with WLED controllers. 1st and most easy, you configure the model/Pixels in xLights as Normal 3 channel pixels, then Configure WLED to do the 3 to 4 channel pixel conversion. This will work with DDP and E131. The 2nd away is to configure xLights as 4 channel pixels like the Falcon or Kulp and then configure WLED as e131 input and change the E131 Input Pixel option to RGBW, then configure the output as RGBW as well.

**Comment by Fonzi03** [comment]
> You have too main options for handing 4 Channel LEDs with WLED controllers. 1st and most easy, you configure the model/Pixels in xLights as Normal 3 channel pixels, then Configure WLED to do the 3 to 4 channel pixel conversion. This will work with DDP and E131. The 2nd away is to configure xLights as 4 channel pixels like the Falcon or Kulp and then configure WLED as e131 input and change the E131 Input Pixel option to RGBW, then configure the output as RGBW as well.

I'll try the e131 but my whole show is DDP and I'dich rather figure out what it takes to get that working in the long run. 

I need them to be able to be set up as 4 channel nodes and RGBW because I have my sequences compiled with a color order of RGBW or RGB only depending on if I want the white to be bright white(mixed RGB) or warm white (white channel only) 

This works perfectly on my falcon board just not with WLED. 

I'll report back if e131 works. 

Do you have any more on if this is a WLED or XLights issue with DDP data? And if it's WLED how can I point them in the right direction?

**Comment by Fonzi03** [comment]
> You have too main options for handing 4 Channel LEDs with WLED controllers. 1st and most easy, you configure the model/Pixels in xLights as Normal 3 channel pixels, then Configure WLED to do the 3 to 4 channel pixel conversion. This will work with DDP and E131. The 2nd away is to configure xLights as 4 channel pixels like the Falcon or Kulp and then configure WLED as e131 input and change the E131 Input Pixel option to RGBW, then configure the output as RGBW as well. 

Would you possibly be willing to connect with @netmindz from the WLED repo. Sounds like he's willing to discuss what's going on, on their end to get this implementation working properly. 

https://github.com/Aircoookie/WLED/issues/4141

**Comment by netmindz** [comment]
From my (very limited) understanding of DDP it is not true to say @dkulp that it is just a list of channels like say dmx, sACN, Art-Net etc as the protocol specifically includes color order information - see the data type byte

http://www.3waylabs.com/ddp/#Packet%20Format

My suspicion is that xlights is not setting to 011 when sending RGBW or that @Fonzi03 has not configured xLights correctly

**Comment by dkulp** [comment]
While there may be a flag in there, there isn't a single controller (other than WLED now) that uses it, including the minleon's for which the protocol was originally designed.   The main reason is that every controller that has supported DDP allows a complete mix of 3 channel and 4 channel pixels on the controller, with many allowing a mix on the same string/port.   Thus, every controller that has implemented DDP in the last 8 years or so have pretty much just set that flag to 001.   

In addition, the DDP outputs in xLights and FPP would have absolutely no knowledge of how the channel data is being used on the other end.   As I said, the controller will very likely interpret certain sub blocks as 3 channel, certain other blocks as 4 channel, etc...    Thus, there is no chance at all of xLights or FPP ever sending anything other than 001.     If WLED cannot handle that like all the other controllers that use DDP (Falcon, Hinks, Genius, Kulp, Minleon, Baldrick, etc...) then it's an issue for WLED.

**Comment by netmindz** [comment]
I strongly disagree that actually following the protocol spec is an issue with WLED's implementation

From your description however it does sound like implementations have found workarounds for the protocol limitation of only allowing all pixels to have the same colour config. Manual mapping on the target device sounds really ugly and totally goes against the idea of pixel Vs channels based protocol

We could however allow an option to disregard that flag to work around non complaint sources

**Comment by Fonzi03** [comment]
> I strongly disagree that actually following the protocol spec is an issue with WLED's implementation
> 
> From your description however it does sound like implementations have found workarounds for the protocol limitation of only allowing all pixels to have the same colour config. Manual mapping on the target device sounds really ugly and totally goes against the idea of pixel Vs channels based protocol
> 
> We could however allow an option to disregard that flag to work around non complaint sources 

Adding the flag would be perfect for this instance at least as a backwards compatibility feature until other boards begin to implement it.

**Comment by cybercop23** [comment]
One of the limitations that we ran into with WLED is that the entire "stream" for DDP has to be the same... either RGB, RGBW or any variations, unlike any of the other controllers that we use that can have a mix/port... some even allow a mix within a port.
I think the same applies for E131, but why bother using something less efficient.
So if there's a way forward, I think WLED should support the xlights variation either as standard, since most likely others aren't controlling the WLED externally, or as a variant.

**Comment by dkulp** [comment]
xLights and FPP are both setting that byte to "0" (all bits).  If WLED would just treat the "0" the same as it does e1.31 data, it should "just work".   For the cases where the RGB/RGBW bits are set, it can do whatever it's doing now.   Really, the spec specifically says "set to zero if not used or undefined" and we aren't trying to define the order of the channels or channel count or anything.   Thus, xLights and FPP are outputting correct per spec.

**Comment by netmindz** [comment]
We have to do **_something_** as when we get the data we need to either use every group of 3 and call setPixel(r, g, b) or every group of 4 and call setPixel(r, g, b, w)

So if you are unwilling/unable to set the bit to match the data format that you are sending, then our only option is to allow the user to define in WLED how "undefined" should be handled rather than default to RGB unless RGBW is indicated

**Comment by netmindz** [comment]
> One of the limitations that we ran into with WLED is that the entire "stream" for DDP has to be the same

I would not say that's a limitation of WLED, it looks as if the actual DDP standard does not allow for any variation of pixel type in a given packet.

If other controllers allow how to map the undefined to pixel channels, that's their choice

**Comment by Fonzi03** [comment]
> We have to do **_something_** as when we get the data we need to either use every group of 3 and call setPixel(r, g, b) or every group of 4 and call setPixel(r, g, b, w)
> 
> So if you are unwilling/unable to set the bit to match the data format that you are sending, then our only option is to allow the user to define in WLED how "undefined" should be handled rather than default to RGB unless RGBW is indicated

In my experience that's how all others do it. You choose color handling order and based off the selection you get the desired result. 

IE

RGBW
GRBW
BGRW
RGB
GRB
BGR

When anything without the W is selected the 4th channel is unused.

**Comment by Fonzi03** [comment]
@netmindz can you confirm if this is something that the WLED team is willing to add in to provide compatibility/feature parity with other boards? I'm not concerned about the time line necessarily, but this does determine if I continue to use WLED or not. As I plan to do my entire landscape lighting to match my fascia lighting and without this feature WLED is unusable for me (and probably many others). 

The biggest benefit of RGBW lights is that I can selectively use the White channel when I want to. It's precisely why I chose warm white, knowing RGB mixed made a bright/blue white and having warm white when desired and the typical RGB/mix thereof when desired gets me the best of both worlds.

**Comment by netmindz** [comment]
Your best option at the moment is to use E1.31 as the protocol from xlights to WLED as recommended in this thread

**Comment by tmblue** [comment]
I was racking my brain and my fingers trying everything.  Wled has an issue with DDP and hopefully there are no ego's that end up blocking that fix.

But as Netmindz indicated, E1.31 to wled does absolutely work via xlights when configured. 

sk6812rgbw
rgbw nodes(intersting enough rgbww is as broken as DDP in wled, just doens't work!, maybe xlights added as a future?)
r=g=b ->W

And the e1.31 config on the wled side.

**Comment by Fonzi03** [comment]
Ive been testing some more and noticed additional behavior that may or may not be worth noting.

Using an On effect set to white (255,255,255)


When I use R=G=B-> W
I get mixed RGB and no White channel
house/model Preview show the string lit up

RGB Only
Same behavior as above
house/model Preview show the string lit up

White Only
Nothing lights at all
house/model Preview do not show the string lit up

Advanced
White channel lights at expected brightness, green and red light at very low brightness and blue is not lit
house/model Preview show the string lit up

White on All
I get mixed RGB and no White channel
house/model Preview show the string lit up
