### ISSUE TITLE
Tool Icon Size option does not affect AC Lights toolbar

### ISSUE THREAD

**Issue by DPattee** [xLightsSequencer/xLights#4883]
**Describe the bug**
Setting the icon size to large/extra large only change the main effects toolbar. It does not impact the AC Lights toolbar, but it should. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
5. 

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
<img width="525" alt="Screenshot 2024-10-10 at 8 07 15 PM" src="https://github.com/user-attachments/assets/5b0bd37e-d068-4f4c-a386-08ae6763c770">

**Versions (please complete the following information):**
 - OS: mac 14.7
 - xLights version 2024.16.1

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by DPattee** [comment]
Actually I think it should impact all the toolbars, including the file/open/save/play one

**Comment by derwin12** [comment]
Some are system icons .. and controlled by windows zoom ratio.

**Comment by derwin12** [comment]
The bigger ask is to change all the buttons and ui toolbars and such. Changing these is not practical as they are defaulted by the wxwidgets and windows. Perhaps in some bigger re-write.
