### ISSUE TITLE
Add parameter to specify where xsqz TEMP folders are generated and maintain said folder

### ISSUE THREAD

**Issue by TheMonks** [xLightsSequencer/xLights#4887]
**Is your feature request related to a problem? Please describe.**
Issue is related to Bug [#4884](https://github.com/xLightsSequencer/xLights/issues/4884) 

The suggestion to redefine where an entire Windows OS puts its temporary files just to work around xlights is inconvenient, causes slowness for any other application using said TEMP file data, and requires users to do so proactively, else they find themselves out of space on a drive they didn't expect and may not know how to alleviate.  

Other apps run faster when they can utilize the higher I/O speeds of an SSD drive but they do not use up as much space a rendering a sequence in xlights appears to.  

It would be extremely beneficial to be able to specify, within xlights, where to build the xsqz temp folder and then also to purge said folder after X number of days.  If each time a user opens a new xsqz file costs them 9GBs of space, very soon they will find themselves running out of space if these folders are not maintained.  In fact, one could argue that if these are just temporary, read-only folders, then perhaps they should be deleted upon exiting of xlights.

**Describe the solution you'd like**
Add a parameter to the Preferences->Sequences page to allow users to define where xlights should built the xsqz temp folders:
![image](https://github.com/user-attachments/assets/70b9127b-7acd-4df8-addd-936d9db06034)

Consider adding a "Purge after X days" parameter as well, if it is deemed those folders shouldn't automatically be deleted upon closing of the xlights session.

**Describe alternatives you've considered**
The alternative is to move the entirety of the Windows temp folders off its desired location to a slower drive, introducting performance loss across the board.

**Comment by cybercop23** [comment]
You don't need to use this. Just rename the file to ZIP and you're done.. Back to the old/dark ages.

**Comment by TheMonks** [comment]
I like to refer to them as the "good ol days" but I'm concerned that new users aren't going to realize where all their space is going and blame xLights for running their machines out of space.  
I don't plan to use them going forward given the way they function, but there must be some sub group of users who they were meant for and I'm sure they would appreciate some sort of memory mitigation.


.Message ID: ***@***.***>

**Comment by keithsw1111** [comment]
The temporary files should all be deleted when you close xlights ... if that isnt happening then that is legitimately a bug and should be fixed. Otherwise this is working as expected and wont change.
