### ISSUE TITLE
Crash when clicking on a Model (Icicles-xx) within Layout tab

### ISSUE THREAD

**Issue by rlangley0** [xLightsSequencer/xLights#4889]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When I go to the Layout tab in xLights, I click on a model and the program crashes with the bug report.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to 'layout tab'
2. Click on 'model' (for instance, any of my icicle props.
3. See error

**Expected behavior**
Crash

**Screenshots**
None

**Versions (please complete the following information):**
 - OS: Windows 11 Home
 - xLights version 2024.16

**Additional context**

**Attachments**
https://1drv.ms/f/s!AhmYyHvEMw5Z0WqrJ9Yppejkx2qE?e=MHeoqb

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by cybercop23** [comment]
Fixed in 2024.16.1. Downgrade, upgrade from Git or look at recently closed issues for workarounds.
