### ISSUE TITLE
Renaming of imported model groups during import

### ISSUE THREAD

**Issue by thekameleon** [xLightsSequencer/xLights#4890]
**Is your feature request related to a problem? Please describe.**
It's more of a time-consuming inconvenience than a problem.  As it can take me hours to rename and move models around between groups

**Describe the solution you'd like**
When importing a model into xlights, a manufacturer can have predefined group names. However they are inconsistent between manufacturers and some of us have different naming conventions.  Such as mine where I use a Namespace naming convention (House.ModelType.Location.Number).

I would like the ability to map the imported groups to existing groups I already have in my layout.

**Describe alternatives you've considered**
Manually spending hours fixing group names and remapping models

**Additional context**
None.  I think it is self explanatory. However, if you have questions, I am more than happy to respond.

**Comment by cybercop23** [comment]
Map them once and save Aliases and next time for the sequencer they will auto map

**Comment by thekameleon** [comment]
Will xlights recreate the manufacturers groups?

Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Oct 12, 2024 at 13:43, ***@***.***> wrote:   


Map them once and save Aliases and next time for the sequencer they will auto map

**Comment by derwin12** [comment]
it wont create new ones - but it can map to existing ones and as Alex mentions, create aliases for future imports.
I wonder if we could create placeholders where you can map them and create empty placeholders. I know it wont be easy....
