### ISSUE TITLE
Modify Xlights.iss file to allow installation on ARM machines

### ISSUE THREAD

**Issue by dflatimer** [xLightsSequencer/xLights#4894]
**Is your feature request related to a problem? Please describe.**
I have a new Windows Surface Pro with an ARM processor.  Numerous programs that are x64 run well using the included windows emulator.  When the xlights setup file is created, the ISS file specifically requires that it only be installed on x64 machines.  This prevents me from even attempting to run it on the emulator.

**Describe the solution you'd like**
Release a beta version of sorts that does not prevent the software being installed on an ARM machines. 

**Describe alternatives you've considered**
I tried following the instructions to compile the code and create my own setup file.  I follow instructions well...But, i am not a programmer by any means and wasnt successful.

**Additional context**
Thank you for all of your hard work.

**Comment by dflatimer** [comment]
Thank you so very much for doing this.  It installed easily without any error messages.  I loaded up a few of my sequences, made some changes, and rendered with no issues.  Works fast...  If you need more specific testing for ARM please reach out.  I do have time.


Derek L



________________________________

**Comment by DanielFrei64** [comment]
It's worth noting, for further confirmation. I've been running off my own self compiled version for a couple days now and. Aside from some small text and funny icon placement in visualizer, this has worked for me without any real issue. I did have to update OpenGL compatibility pack for ARM otherwise it would crash on me, but since then, all has been well. I also tried the installer linked here and it worked fine for me. Quick smoke test on several routine things I normally do have worked just fine.

**Comment by derwin12** [comment]
Any benchmarking done?

**Comment by DanielFrei64** [comment]
Nothing specifically. I've added a controller, updated my layout, opened 12 sequences, made a few small modifications to some of them, re-rendered and played them. It feels snappier than my other machine I was running it on. I'll do some side by side comparisons later today and report back. Anything specific you would like to see. Glad to help.

**Comment by derwin12** [comment]
Simple test would be batch render of 10 sequences or something like that.

**Comment by DanielFrei64** [comment]
@derwin12 

**Workstations:**
**Laptop 1:** Dell Latitude, Intel i7 11th Generation 8 core 3.0Ghz x64 processor, 32GB memory, intel graphics card, ssd(2 year old developer laptop)
**Laptop 2:** Microsoft Surface Pro 11, Snapdragon 10 core 3.4Ghz ARM64 processor, 16GB memory, intel graphics card, ssd(brand new business productivity laptop) 

**Test:** 
Batched processed 10 moderately complex sequences with matrix, mega tree, doors, windows, props, rooflines, multiple singing faces, arches, etc. ~12000 lights, 

**Test Results:**
**Laptop 1:** 11:05 min. All CPU, no noticeable disk or gpu utilization. CPU would peg to 100 from time to time, but spent most of it's time at or around 60-70%

**Laptop 2:** 6:58 min All CPU, no noticeable disk or gpu utilization. CPU spiked to ~80% twice, and would spend most of it's time at or around 50%
