### ISSUE TITLE
Windows 11 vs WIndows 10

### ISSUE THREAD

**Issue by RJBorton** [xLightsSequencer/xLights#4896]
**Describe the bug**
.PROBLEM: erratic slow light response, sequence portions randomly freeze, timing is off, etc. from 2 different windows 11 systems, but all is good from an older windows 10 system which is beyond supportable.
**To Reproduce**
run any sequences from either of my Windows 11 systems as below

**Expected behavior**
 xLights to continue functioning as it did 4 months ago prior to latest Windows 11, xLights and HinksPix PRO upgrades, etc.

**Screenshots**   none

**Versions:**
 - OS: Windows 10 vs Windows 11
 - xLights versions from 2023.20 thru 2024.16

**Additional context**
Reproducible on all my sequences with multiple controlling computers;  
DETAIL SUMMARY running from 3 different PCs – all other hardware the same:
1. HP Elitebook 8570w laptop running Windows 10 Pro ver 22H2, xLights 2023.20, static IP on Hinks and PC, virus sw and firewall down, airplane mode My Show runs fine - All sequences.  This is my show computer from Christmas 2023.
2. Dell Inspiron 7391 2n1 laptop running Windows 11 Home ver. 23H2, xLights 2023.20, static IP on Hinks and PC, virus sw. and firewall down, airplane mode, show stutters and timing is bad.   The same problem occurs with various versions of xLights including 2024.16. xLights House Preview looks good. This is my Show Computer from July 4th, 2024, which was ok - then.
3. HP laptop 15-dy2033 running Windows 11 Home ver. 23H2, HP laptop, xLights virgin system, clean install of xLights 2023.20, static IP on Hinks and PC, virus sw. and firewall down, airplane mode, show stutters and timing is bad. House Preview looks good.  This laptop was ‘Borrowed’ from my wife and is running xLights for the first time.

Development of sequences, etc. is OK on the Win 11 Dell, then I move the sequences to the Show computer via thumbdrive, sequence, and they run OK. But I cannot RUN them from the Dell as I did in July.
I’m isolating and safeguarding the old laptop until a resolution is found.  

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by RJBorton** [comment]
All sequences are Musical at 40 fps/25ms. Cat 5e cable is 20' long  controller is on the front lawn. Cable runs thru the wall. All 3 laptops sit side by side on my desk and I move the Cat5 cable between them with no other changes.  What else do you need?

**Comment by RJBorton** [comment]
Is anyone else using a HinksPix Pro v2 running under Windows 11 through CAT 5e cable?

**Comment by derwin12** [comment]
Not sure what to do here .. can you provide tools->package logs

**Comment by computergeek1507** [comment]
Is xSchedule lagging or xLights?

**Comment by RJBorton** [comment]
Last night I put together a very simple musical sequence with a Fan effect over the whole house. I duplicated this on the 3 laptops and Rendered it on each. Then, I ran my outside display under HinksPix control from each by only moving the CAT 5e cable from one laptop to the other. While I worked inside, my wife captured 3 videos of the results. All files are available at:  https://www.bobritaborton.com/temporary-debug-files/

File: HP-WIN10-XL2023-20.mov is last Christmas show computer running Windows 10 and it looks OK. 
File: DELL-WIN11-XL2024-15.mov is this years July 4th computer running Windows 11 and it shows corrupt timing.  
File: HP-WIN11-XL2024-14.mov is the borrowed, virgin Windows 11 laptop and it shows corrupt timing.

The timing problem is obvious on both WIndows 11 laptops but not the Windows 10 laptop.

Observation: I scoped the data between pixels/nodes during a run of the WIndows 11 systems and the observed visual show skips match data freezes on the data line - which match freezes on the Tx and Rx leds at the interface connectors. The data transfer between either/both Windows 11 systems and the HinksPix controller is being interrupted.  Root Cause: TBD.

**Comment by RJBorton** [comment]
I updated the bug report to include a link to the .mov files showing the problem. Problem was only tested in xLights using Output to Lights not scheduler (yet).

 

Thanks for your concern/help,

 

Bob

**Comment by RJBorton** [comment]
problem has only been observed / tested in xLights.

**Comment by computergeek1507** [comment]
I don't think this is a windows 10/11 "xLights Issues". I get the logic that "one works, one doesn't, blame xLights". I have run xLights /xSchedule for a 200k pixel show on Windows 11 PC and also run and build xLights on two other Windows 11 PCs. I have seen other reports that the "HinksPix is laggy" on Facebook so maybe this is causes by something else.

**Comment by RJBorton** [comment]
Scott,

 

I suspect that you are correct.   I will continue testing after Halloween.  All is working so ‘No Touch’ for now.

 

Bob
