### ISSUE TITLE
Copy of a model causes Xlights to Crash.

### ISSUE THREAD

**Issue by mjmullin** [xLightsSequencer/xLights#4900]
I do not have a sequence built yet. I am just adding models to my controllers.

**Describe the bug**
Copy of a model causes Xlights to Crash and creates a crash file, see attached. Every time its tried.

[xLights_dbgrpt-20832-20241016T052010.zip](https://github.com/user-attachments/files/17392050/xLights_dbgrpt-20832-20241016T052010.zip)
[xLights_dbgrpt-9468-20241016T054223.zip](https://github.com/user-attachments/files/17392195/xLights_dbgrpt-9468-20241016T054223.zip)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to Model Window
2. Click on any model
3. Select Edit then Copy
4. Select edit then paste
5. Creates an error on the screen and file, then closes. 
![image](https://github.com/user-attachments/assets/31da1264-7bf8-4119-9b57-1ae38903174c)

Steps to other Senario:
1. Go to Model Window
2. Click on any model
3. Right click and select  CTRL-C
4. Xlights Closes, no warning and no crash file.

**Expected behavior**
I would expect it would copy the model and allow me to paste a duplicate but with a slightly different name.

**Screenshots**
![image](https://github.com/user-attachments/assets/1ca20446-a564-44b0-9492-4956367401c4)

**Versions (please complete the following information):**
 - OS: Windows 11 Home Version: 23H2 OS Build 22631.4317
 - xLights version Version 2024.10 64bit  wxWidgets 3.3.0

**Additional context**

**Attachments**
Log Files:
[xLightsProblem.zip](https://github.com/user-attachments/files/17392274/xLightsProblem.zip)

I have not created a Sequence yet.

**Comment by computergeek1507** [comment]
Please upgrade to the latest

**Comment by mjmullin** [comment]
![image](https://github.com/user-attachments/assets/1e1397fd-8385-4907-ad67-aaaf3ac14d52)

When I select "Check for Updates" I get the message above stating I have the latest.

My version shows:
![image](https://github.com/user-attachments/assets/11af6086-fbdd-4ac2-b635-2e53b3a56bde)

The Xlights page shows:

![image](https://github.com/user-attachments/assets/12f8ea54-31c2-47ac-bd09-1b711a594631)

Maybe the Check for update is not working in Version 10?

Updating now and have to reload. Adding this comment to save the progress.

**Comment by computergeek1507** [comment]
Yes the updater is broken in old versions

**Comment by mjmullin** [comment]
Thanks for your help.

Merv
________________________________
