### ISSUE TITLE
Batch Render dates

### ISSUE THREAD

**Issue by bobreese** [xLightsSequencer/xLights#4901]
When doing a Batch Render, it shows the last saved date.
Would be helpful if it actually showed the Last Render Date.

**Comment by cybercop23** [comment]
You are batch rendering the xsq (sequence effects) file. It has no idea of the fseq file. It should not change. If you make changes to the effects and just save it, that's what you want to know. If you change layout or port config, then everything has to be re-rendered.

**Comment by bobreese** [comment]
The point is that if a change is made to Preferences /  Hardware video decoding, the sequences need to be re-re-rendered even if the sequence did not change...
This is what I am experiencing.

**Comment by cybercop23** [comment]
Exactly. you did something that *you* know needs rerender... should not be managed by teh render process

**Comment by bobreese** [comment]
@dkulp  What's the issue with having Saved date and Last date of Render being shown when doing a batch render?
Just because I have the sequence Saved as I want it BUT I make a change to Preferences or get an update to xLights, I should be able to make the decision of if I need to Batch render everything or not based on the LAST rendered date, NOT the last Saved date....
