### ISSUE TITLE
Chaining models with set brightness followed by default brightness have inconsistent behavior between Falcon and Genius controllers

### ISSUE THREAD

**Issue by Ry0523** [xLightsSequencer/xLights#4902]
When chaining multiple models on a port where the first model in a chain sets the brightness and next models do not, on a Falcon controller, the brightness for the chain is determined by the last model that set the brightness in the chain, whereas on Genius, models that do not set the brightness use the default port brightness.

**To Reproduce**
1. Create 2 models, one with brightness set to 20%, one with the brightness not set
2. Under Falcon controller, set Default Port Brightness to 30%
3. Add the 2 models to a port in the visualizer, with the model set to 20% added first, and the model without brightness set chained after.
4. Upload configuration to Falcon controller.
5. Open Falcon controller page and view outputs to see the first model brightness of 20% is set for the port with no virtual strings created for the next model in the chain.
6. Repeat steps 2-4 with Genius controller.
7. Open Genius controller page outputs and see both models appear, with the first model showing 20%, and a virtual string for the second model showing 30%.

**Expected behavior**
I would expect the same function to perform a similar result when possible, regardless of controller type. In this case, Genius behavior is more accurate, where one would assume that a model that does not set brightness would use the default port brightness.

**Screenshots**
Screenshots depict the same setup for Falcon and Genius, with the first model setting brightness to 20% and the next 2 models in the chain not setting brightness:
![image](https://github.com/user-attachments/assets/38da9fa7-d5b2-421b-86ac-781f4d4f33ba)
![image](https://github.com/user-attachments/assets/5fdc3752-d43e-48fd-acf6-3cacc32142c8)

**Versions (please complete the following information):**
 - OS: Windows 11 Home 23H2
 - xLights version 2024.15 64-bit

**Addition Comments**
This issue seems straight forward, and is ultimately a minor issue, so keeping things on the briefer side, but please let me know if you would like to see additional information.  I do not have the ability to verify behavior of other controller types beyond these 2.

**Comment by derwin12** [comment]
we could code around it .. but it is really something the controller firmware folks have done and there is different opinions on it.
I cant see how we could change xlights now to reverse this legacy.

**Comment by merryoncherry** [comment]
Maybe everyone already knows this, but is it worth mentioning that xLights offers dimming curves per model?  These get rendered into the .fseq, so the controller does not need the brightness/gamma/etc. capabilities, which do vary greatly from one controller to the next.  (Some popular controllers do not support virtual strings, some others have very coarse granularity on dimming / gamma, etc..)

Using xLights has the advantage of being uniform across all controllers (because the controller isn't really involved).  The disadvantage is that if you want to make a change, you have to (hopefully batch) render the sequences again, so it isn't a great way to handle field issues.

**Comment by Ry0523** [comment]
Very true to the legacy component.  It feels like the handling of this is more like a natural progression than a differing opinion, but I can definitely see how it would be bad to make a change here when it's been like this for so long.
