### ISSUE TITLE
Twin Rays Shader on Mac - does it work for others?

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4908]
Couple folks in zoom couldnt get it to work. Works on Windows. Simply pull the shader in from the downloads.

Anything that can be tweaked to make it work?

**Comment by cybercop23** [comment]
Yeah..nada... matrix, all group.. all diff render styles.. just black.. .like someone turned off the lights

**Comment by kylegrymonprez** [comment]
repro on my end as well.

**Comment by dkulp** [comment]
It's a bug in the shader itself.    "vec3 color" is never initialized to anything.   If you edit the shader to make that line:

```
vec3 color = vec3(0, 0, 0);
```

it at least does something.  It might even be correct.

**Comment by kylegrymonprez** [comment]
confirmed adding it makes it show up for me- seems like we may need to get the source to update their code.....

**Comment by kylegrymonprez** [comment]
I forked it on the source website. I suppose we could update the links in shaders.xml:

https://www.interactiveshaderformat.com/sketches/6716a88b9e84f80019d211af/download for reference

**Comment by derwin12** [comment]
What has happened in the past is to submit an XL_<shader>. So perhaps submit one of those? Paul/Peter cant recall his name - did a bunch of these sorts of submissions.
