### ISSUE TITLE
Add an "Align to timing mark" option

### ISSUE THREAD

**Issue by sporterfx72** [xLightsSequencer/xLights#4913]
**Is your feature request related to a problem? Please describe.**
I typically copy/paste effects from one section of a song to another. When there is are beat timing marks, sometimes the copied effects do not line up perfectly on the timing marks. I have to manually tweak each one by hand to align them to the timing marks.

**Describe the solution you'd like**
I would like to be able to select the group of effects and have a new option under **Alignment** called "Align to timing mark". This option would align each effect to its nearest timing mark.

**Describe alternatives you've considered**
None

**Additional context**
You can see that the pasted effects do not line up with the red timing marks.
![image](https://github.com/user-attachments/assets/b9671ee1-ce9d-499a-9921-a435f4a76c71)

**Comment by cybercop23** [comment]
Use paste by call to paste
![image](https://github.com/user-attachments/assets/d919efc3-3d80-4316-a5a6-3b8bb520a275)

**Comment by sporterfx72** [comment]
The "paste by cell" only works if the original timing is perfectly aligned to the timing marks. If I had timing that was a bit off to start with, then the "paste by cell" will also make it a bit off. Having an align to timing marks would allow you to easily clean up timing that was not perfect.

**Comment by computergeek1507** [comment]
I like this idea, I will try to add it

**Comment by computergeek1507** [comment]
I added this with 6e29cfd02fb5f85428fc6766ad2fca7ad29d4ae9, Let me know if it what you envisioned.

**Comment by sporterfx72** [comment]
I gave it a try and it works exactly as I needed it to. Highlight items, right click, align to timing mark... couldn't  be any simpler. I am not sure if you have to code up support for undo. Say I highlighted too much by accident, I cant undo and revert back to the original timing. Other than that, looks good. Thanks!

**Comment by computergeek1507** [comment]
I have undo support, I need to make some adjustments today to prevent overlap

**Comment by Clyde-L** [comment]
This will be helpful.  I've selected half of the effect, held Shft+Ctrl and pressed the arrow right/left key to align quickly with at timing mark.  Thanks!
