### ISSUE TITLE
Submodels and Model DAta

### ISSUE THREAD

**Issue by thibbs5** [xLightsSequencer/xLights#4924]
**Is your feature request related to a problem? Please describe.**
When flipping horizontally or vertically in the data model it would be helpful if the submodels were flipped as well. I was correcting an issue where the model was on the layout incorrectly however the side effect of this was all text of the submodeled matrix was backwards.

**Describe the solution you'd like**
Please consider including submodels when an entire model data is flipped

**Describe alternatives you've considered**
I had to open every submodel and flip the rows. For some props this may not be an issue however I have multiple defined matrixes.

**Additional context**
I hope this helps others out as it took me hours to figure out what was going on.

**Comment by derwin12** [comment]
Trying to think if this is even possible - how would you know the new numbers? If you flip it - the submodels are not likely to change. You just changed the position of the pixels from the top to the bottom, or left to the right etc.

**Comment by thibbs5** [comment]
I promise you that it happened. I just recreated it and the text is backwards. It seems that the programming may have already been put in place since for me to correct the issue, I opened the submodel and clicked on the "Reverse Nodes" button and that fixed the text I was trying to display.

**Comment by derwin12** [comment]
We discussed this in the zoom room .. just doesnt seem practical to code this based on so many situations that could result.
