### ISSUE TITLE
Fail to launch on macOS 15 - can't read show directory

### ISSUE THREAD

**Issue by djamison** [xLightsSequencer/xLights#4925]
**Describe the bug**
At launch following a version upgrade to 2024.17 from 2024.16, xLights prompts for a show directory. No matter which directory is selected, xLights exits with: "Exiting as setting a show folder is not optional."

These log entries appear relevant:

```
error	16:29:39.506170-0700	kernel	Sandbox: xLights(55636) deny(1) file-read-data /Users/<me>/Documents/xLights/House Only
error	16:29:39.506172-0700	xLights	Could not open() the item: [1: Operation not permitted]
```

It remembers my show directory from before the upgrade, which was working.

Even selecting a folder inside `~/Library/Containers/xLights` fails.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Install 2024.17 on macOS 15
2. Launch xLights
3. Select show folder
4. Receive error "Exiting as setting a show folder is not optional."

**Expected behavior**
xLights should launch as it did before 2024.17.

**Screenshots**
None

**Versions (please complete the following information):**
 - OS: macOS 15.0.1
 - xLights version 2024.17

**Additional context**
Granting Full Disk Access did not resolve the issue.

**Attachments**
Another log entry just before the app exits `os_unix.c:49437: (2) open(/private/var/db/DetachedSignatures) - No such file or directory`: https://pastebin.com/VrsKQwtf

**Comment by djamison** [comment]
Tried reverting to 2024.16 and the issue was still present.

Rebooted and the issue went away for both 16 and 17.

**Comment by derwin12** [comment]
The key is the reboot.

**Comment by djamison** [comment]
> The key is the reboot.

Is this a known issue? I don’t usually have to reboot when updating apps from the App Store and only did it on a whim.

**Comment by cybercop23** [comment]
This seems to be a Mac OS issue. To get the new access rights with the new way they do read privileges it needs a restart.

**Comment by djamison** [comment]
macOS 15 has certainly made sandboxing more challenging for apps, but it does seem to impact xlights in a way that other apps handle without requiring a reboot. Can we dive a little deeper to see why that is? Or update the error message to suggest a reboot to the user? I’m happy to help with a PR or whatever we need.
