### ISSUE TITLE
FPP connect upload progress

### ISSUE THREAD

**Issue by cathelest** [xLightsSequencer/xLights#4931]
With FPP connect, 

Would it be possible to add a count similar to the batch render count at the bottom of xlights to say 

Uploading sequence <sequence name.fseq> (5/30),

I know you cant calculate time etc unfortunently, but a count atleast would be
helpful,

Your thoughts appreciated.

**Comment by cybercop23** [comment]
I've been thinking of the same thing. I usually compare to the list (since it's sorted by the modified date) and see how far along it is.

**Comment by cathelest** [comment]
Legend! 

Will be a massive help, many thanks!
