### ISSUE TITLE
Value Curve on Blur - legacy issue / question

### ISSUE THREAD

**Issue by brett-foy** [xLightsSequencer/xLights#4934]
Hey team.   At some point in the past, it was possible to do value curves on Blur.  I don't know when this was removed and while a bummer, never seemd to be an issue.

I am working on some sequences that were created at the end of 2022 that did have Value Curve set on the blur in the layer settings - and I have found an interesting issue while chasing down why some effects are not working.

I have narrowed down the issue to the "Blur" setting not being editable, see first image:
![image](https://github.com/user-attachments/assets/93afebbd-1205-4148-9e06-27227e6a4319)

As you will note, both the slider bar and the number field for the blur setting are grayed out, and they cannot be modified.     There is no way to modify the blur setting on the effect without selecting another effect (or creating one) and then setting the blur to 1 on the new effect, and then doing a bulk edit of any effects that had a value curve with the new one to make them a number, at which time, it over-writes the old blur setting and then becomes editable again.  When both the slider bar and the number are grayed out, the effect is not rendered or visible.

If I look in the xml, I do see that there are effects with a value curve on a blur:

    <Effect>**B_VALUECURVE_Blur=Active=TRUE**|Id=ID_VALUECURVE_Blur|Type=Custom|Min=1.00|Max=15.00|RV=TRUE|Values=0.00:0.21;0.12:0.20;0.12:0.47;1.00:0.05|,E_CHECKBOX_Twinkle_ReRandom=0,E_CHECKBOX_Twinkle_Strobe=0,E_CHOICE_Twinkle_Style=New Render Method,E_SLIDER_Twinkle_Count=52,E_SLIDER_Twinkle_Steps=30,T_CHOICE_LayerMethod=Additive,X_Effect_RenderDisabled=True</Effect>

But since the value curve on the blur is not an option in the UI anymore, I am wondering if somehow these are just getting ignored and not rendered at all?

The sequence I am looking at was made on 2022.14, I am uploading a new sequence with the effects mapped over that have the issue for analysis.

[blur_value-curve.zip](https://github.com/user-attachments/files/17611983/blur_value-curve.zip)

OK this is even getting more weird.   So I am on 2022.15 right now, and to make a sample sequence, I just created a new sequence and imported one prop that I knew had a value curve on the blur.

In this picture, you can see the Layer settings panel on the LEFT that is the new sequence, with one effect, that shows the availability of a value curve in the UI.  The Layer Settings on the right is from the current sequence, which has a prop with the value curve set, but not being editable.    any other effect in that sequence or any other new sequence does not have a value curve setting option on blur.

![image](https://github.com/user-attachments/assets/83559377-b438-4729-bec6-396204e7d658)

What is the expected xLights behaviour at this point?  Is blur supposed to have a value curve capability? Was it removed intentionally?  If it was removed, can things be fixed such that older sequences with a blur value curve can be rendered (if nothing else with a value of 1?)  Or, can the value curve for blur be made active again?

Let me know if more details is helpful.

**Comment by derwin12** [comment]
I can VC blur .. so my guess here is that you can only do it for certain effects and/or render styles.
![image](https://github.com/user-attachments/assets/1a3efe1e-1ee7-4ada-9ad3-4e557cde72d7)
Let me quickly look into the code.

**Comment by derwin12** [comment]
Not sure how it got in that state .. but I opened your attached sequence. Just dropped an ON effect on that same model. That now shows the VC and it re-enabled all the others.

**Comment by derwin12** [comment]
This seems to be a glitch .. cant duplicate.
