### ISSUE TITLE
No preview in layout tab/Can't add models

### ISSUE THREAD

**Issue by john-TC** [xLightsSequencer/xLights#4937]
In the latest version of xLights, I can't add models in the layout tab. I downloaded previous versions until it worked, and landed on version 2023.18. I am using the latest version of Manjaro Linux.

xLights 2024.17
![Screenshot_20241104_200030](https://github.com/user-attachments/assets/0db04f47-98f8-498f-bbbd-4aed7d692d07)

xLights 2023.18
![Screenshot_20241104_200129](https://github.com/user-attachments/assets/1dc7a886-39bc-4fac-a06d-37a8c23b5a0a)

**Comment by reenx** [comment]
See issue #4762.
I have the same issue on Fedora and the workaround of downgrading the mesa libraries works for me.
The command I used: sudo dnf install mesa-dri-drivers-24.0.5-1.fc40

I don't know manjaro. Perhaps there is a similar command to accomplisch the same thing

**Comment by davebarrett1959** [comment]
I had the same issue on Arch on 2 PC's. Just tried latest release 2024.18 and it seems to have solved it for me.

**Comment by john-TC** [comment]
It is working for me now too. Thanks
