### ISSUE TITLE
Selecting submodels to import - cant multiselect

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4943]
.17

In submodel dialog, import from another model. There is a right click option to select highlighted but it doesnt seem to be possible to shift select or ctrl select multiple items

![image](https://github.com/user-attachments/assets/778b6788-3f4e-4a46-819a-2edae6c8a702)

(maybe my bug?? :-) )

**Comment by computergeek1507** [comment]
Pretty sure you are the only person who uses the selected highlighted options

**Comment by cybercop23** [comment]
That's cuz it doesn't work.

**Comment by derwin12** [comment]
See that the code is used for model export when selecting groups.. It likely never was coded :-)
![image](https://github.com/user-attachments/assets/a15df7cc-3efb-4e2f-a01d-850cf3563573)

**Comment by derwin12** [comment]
Cool..I didn't think it would be possible without a lot of custom code.
