### ISSUE TITLE
Mapped sequence renders differently - Single Strand render buffer shows 2 rows vs 1

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4944]
I am trying to track the cause for this. Mapped sequence - same settings. Same pixels per spoke. Inside to out - no vertical buffer.
Group from mine on left - made up of 16 spokes from 2 models.
Group from ppd on right - made up of 16 spokes from 2 models.
Showstopperspinner vs Megaspinner.
Mine only shows red .. source shows red and white chase.
Tried v16 and v17.

@computergeek1507 Scott - any clues here?
Update: using debugger PPD shows bufferHt=2, mine shows 1
![image](https://github.com/user-attachments/assets/26f1b8e7-ed49-4715-9e8f-0755d1e45eba)

**Comment by derwin12** [comment]
Attaching theirs and mine .. single effect.
[PPDDemo.zip](https://github.com/user-attachments/files/17667964/PPDDemo.zip)
[MineDemo.zip](https://github.com/user-attachments/files/17667966/MineDemo.zip)

**Comment by derwin12** [comment]
Found that PPD submodel has one spoke with an extra line - this makes the render buffer 2 high. Checking to see the impact.
![image](https://github.com/user-attachments/assets/cc530adf-dd0d-4f49-9d13-6952b7f6b879)

**Comment by derwin12** [comment]
So it appears PPD is sequencing with this mistake - if I correct this submodel the effects are impacted. Cant do much about it. Not an xlights issue.

**Comment by cybercop23** [comment]
> So it appears PPD is sequencing with this mistake - if I correct this submodel the effects are impacted. Cant do much about it. Not an xlights issue.

AI
