### ISSUE TITLE
Submodels don't accurately match pixels defined in custom model when pixels are not in sequence in custom model's "model data"

### ISSUE THREAD

**Issue by tomhammond** [xLightsSequencer/xLights#4945]
**Describe the bug**
I attached seeds to a wireframe.  To make the seeds jump from area to area, I choose to not light up seeds between jump points.  For example, seeds 1-10 are active, there is a gap of three unused seeds, then seeds 14-24 are active.

In the attached example, in the custom model's model data, I define pixels 1-10 and 14-24, leaving out pixels 11-13.  This works as expected.

When I create a submodel, it shows all pixels from 1-24 even though 11-13 are not defined in the custom model's model data.

If you look at my layout, look at the left boot in the "Santa" custom model.  It starts with pixels 1-10, then jumps to 19-62, then jumps to 75-85.  Leaving out pixels 11-19 and 63-74 is intentional; I don't want them to light-up on the string.

But when you go into submodels and create a new submodel, it shows all pixels 1-85 and the pixels are not in the correct locations as compared to the original model data (they are shifted).  

**Expected behavior**
The bug: The submodel should not display pixels that have not been defined in the custom model's model data.

**Screenshots**
![model data (good)](https://github.com/user-attachments/assets/30457f6e-8c4c-4754-b3ff-6a69e34ba378)
![submodel (bad)](https://github.com/user-attachments/assets/52ba2177-9532-4f6f-93c3-f399dbaf601a)

**Versions (please complete the following information):**
Windows 11
xLights 2024.15

**Attachments**
[show xml files.zip](https://github.com/user-attachments/files/17672252/show.xml.files.zip)

Thank you!
Tom Hammond

**Comment by computergeek1507** [comment]
the submodel number is actually the index of the Node Vector, when you type "11" it is really node 14. Its not good practice to skip nodes.
