### ISSUE TITLE
https://xlightszoom.com redirect is not working

### ISSUE THREAD

**Issue by derwin12** [xLightsSequencer/xLights#4953]
Not sure who controls this .. but it seems the ssl forwarding is not enabled. I found I had to enable this  when google handed over the reigns to squarespace. Anyone know who to contact to get that fixed?

**Comment by cybercop23** [comment]
and it is expiting soon...
Palmetto Technical.... whomever that is

https://www.whois.com/whois/xlightszoom.com

**Comment by computergeek1507** [comment]
It's Tom Stallings Company

**Comment by derwin12** [comment]
Appears to have been paid for .. expired today :-)
