### ISSUE TITLE
Crash on model selection when controller connection is undefined

### ISSUE THREAD

**Issue by Coltonc18** [xLightsSequencer/xLights#4956]
When selecting models in the Layout pane which do not have a value saved in the Controller Connection -> Protocol field, xLights will crash. The only way to modify the layout of these models was to manually open the xlights_rgbeffects.xml and change the Controller Connection tag from `<ControllerConnection/>` to `<ControllerConnection Protocol="ws2811"/>` on each of the offending models. Only after changing this was I able to select and edit them in the Layout tab without the program crashing.

**To Reproduce**
1. Have a model in your layout which does not have a protocol specified (this was possibe in older versions of xLights)
2. Select the model
3. Program crashes

**Versions:**
 - OS: Windows 11
 - xLights version 2024.16

**Additional context**
It appears that it is no longer possible to have a blank Protocol field when creating a new object. However, older models which have been in the Layout for a while may still have a blank field, preventing a user from being able to edit them in the software until they fix the rgbeffects file.

**Attachments**
Debug Report: 
https://www.dropbox.com/scl/fi/9494daaybtwfr3uwb2upl/xLights_dbgrpt-31372-20241114T232249.zip?rlkey=fh37pdiebp8fk455lckr0v2bc&st=phpobwv6&dl=0

**Comment by computergeek1507** [comment]
Already fixed, Please update to 2024.17 or newer
