### ISSUE TITLE
XLIGHTS Unresponsive

### ISSUE THREAD

**Issue by MUVEIT0919** [xLightsSequencer/xLights#4959]
No sequence needs to be open in order for situation to occur.

1. Start XLIGHTS
2. Select controller
3. Click Visualizer
4. XLIGHTS is unresponsive and must close XLIGHTS in Task Manager
5. XLIGHTS re-starts fine next time, but Visualizer still not usable

Version 2024.18 64-bit
Windows 11 Pro

Screen grab of error
https://davehynecom-my.sharepoint.com/:v:/g/personal/dave_davehyne_com/ERExyF311a5KhEntZIhJYw0BsXmoDauOrNFuzMJ0H7OvzA?e=vjJ9l5

Show Directory
[xlights_networks.zip](https://github.com/user-attachments/files/17784755/xlights_networks.zip)

**Comment by derwin12** [comment]
It works here .. what usually happens here is that it pops up on another monitor. Did you switch from dual monitors to one or something of that nature?
You can reset things by going to the cmd line
cd \program files\xlights

then run xlights /w
You will have to reselect your showfolder when you run xlights again.

**Comment by MUVEIT0919** [comment]
That fixed it.

Thanks Daryl.
