### ISSUE TITLE
Papercut: Property grid values don't get confirmed if you select another object

### ISSUE THREAD

**Issue by degracode** [xLightsSequencer/xLights#4961]
**Describe the bug**
For me this is a very common papercut - when editing a value in a property grid - significantly, a controller in the Controllers tab, or model in the Layout tab), I will instinctively type in the new value, then found that it's been lost because I didn't explicitly confirm the edit, eg with Enter, or selecting another property. It usually happens because I've clicked on another controller or model.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Add two controllers to the Controller tab
2. Click on the first controller
3. In the property grid, start typing in a new name
4. Use the mouse to select the second controller
Notice that the name change was cancelled.

I've had the same papercut occur with controllers, models, 3d objects and the custom model dialog.

**Expected behavior**
Property grids should assume that you meant to make the edit you had typed in, and accept it on defocus.

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2024.17.1

**Comment by derwin12** [comment]
That is just a "feature" of wxwidgets. Nothing we can do to change that. Always tab out or press Enter to confirm the change.

**Comment by degracode** [comment]
Although I'm not particularly familiar with wxWidgets' workings, I wouldn't have thought this is completely unfixable. For example, the value could be cached out as it's being typed, and then applied if a defocus event happens.
