### ISSUE TITLE
Cleanup file locations on batch render

### ISSUE THREAD

**Issue by blargh2947** [xLightsSequencer/xLights#4967]
**Is your feature request related to a problem? Please describe.**
When starting my process for a new year, I will select some sequences from a prior year and use batch render to update them into my new year layout.  On inspection, I notice that batch render does not clean up file locations; the xsq will contain absolute paths to assets such as video files, images and shaders in the previous location.

Running Cleanup File Locations fixes this.

**Describe the solution you'd like**
Add a tick box to clean up file locations and execute it as part of the batch render process.

**Describe alternatives you've considered**
The work around is to open each sequences individually, and run the cleanup file locations process manually.

**Additional context**
There does not appear to be an easy/quick way to perform this other than opening each sequence and selecting cleanup.

**Comment by derwin12** [comment]
By design batch render just renders. It does not touch/change/alter/save the .xsq. Do dangerous.

**Comment by blargh2947** [comment]
> By design batch render just renders. It does not touch/change/alter/save the .xsq. Do dangerous.

Sorry, I don't understand why having a checkbox to perform that function at the same time is dangerous.

Is there another method to bulk update the file locations?

**Comment by derwin12** [comment]
You just have to open them up .. make your fixes and close.
If you want you can make a windows batch bat file and run thru opening each one
https://github.com/xLightsSequencer/xLights/issues/3017
https://github.com/xLightsSequencer/xLights/issues/2965
https://github.com/xLightsSequencer/xLights/issues/2287
https://github.com/xLightsSequencer/xLights/issues/2179
