### ISSUE TITLE
Add keybinding option for pause/unpause music

### ISSUE THREAD

**Issue by lorajoslyn** [xLightsSequencer/xLights#4973]
I currently use video editing software for other work and I regularly use the space bar to pause and unpause video playback.  It would be fantastic to be able to add an option in the current keybinding section to include play/pause.  

I accidentally keep hitting space, which sends me to the beginning of the song (my fault, but it's irritating).  

I went through the current keybindings and didn't see the option.  I also looked in the manual and it didn't seem to be there.  But perhaps I missed it...

Thanks for the consideration!

**Comment by lorajoslyn** [comment]
Correction... the space bar does stop the music, but pressing the space bar again re-starts the entire song.  It would be ideal for it to continue the music where you originally left off.

**Comment by cybercop23** [comment]
Pause/Break does it

**Comment by lorajoslyn** [comment]
I'm misunderstanding.  I don't have a pause/break key on my keyboard.  I don't see that as an option in the keybinding file.  Can you clarify?

**Comment by derwin12** [comment]
Should be here to redefine it..
![image](https://github.com/user-attachments/assets/e7f57c25-ac63-47e9-82b5-5774bb30619f)

**Comment by lorajoslyn** [comment]
Interesting.  PAUSE or TOGGLE_PLAY does not show up in my keybindings view in Xlights, even though it's in the base xml file.  Could that be why it's not working on my computer?
![keybinding-xlights-view](https://github.com/user-attachments/assets/a20a9c4a-560d-4676-802f-4d626e384fe6)
![xlights-keybinding-xml](https://github.com/user-attachments/assets/8ffcedd6-b94b-45ce-a47a-2a0043f9397e)

I am on 2024.17 version

**Comment by cybercop23** [comment]
It's under All Tabs. You're only looking in Sequencer, top dropdown.

**Comment by lorajoslyn** [comment]
Thank you!  I guess I just needed to restart - the space is now functioning. Appreciate the help!
