### ISSUE TITLE
Rotate X

### ISSUE THREAD

**Issue by McCoyCOREUSA** [xLightsSequencer/xLights#4974]
In a Custom Model, the right-click and "Rotate x" is working backwards from a standard rotation. A positive number should rotate the model clock-wise, and negative value is counter-clockwise. It's working opposite.

Not an urgent fix, but letting you know. Thanks.

**Comment by computergeek1507** [comment]
It was written by an Australian, so it's the right way for the southern hemisphere

**Comment by deplanche** [comment]
xLights follows the standard convention of positive is counter clockwise, and negative is clockwise.  Start from the positive x-axis (to the right) and goes to the positive y-axis (up).

**Comment by computergeek1507** [comment]
I was going to add a setting

**Comment by derwin12** [comment]
You are too nice ..
