### ISSUE TITLE
xscanner shutting down

### ISSUE THREAD

**Issue by srwmemphis** [xLightsSequencer/xLights#4987]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
when I run xscanner it immediately pops up a window showing a debug report and when I click on ok it closes.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
Normally it gives me a list of all the IP addresses it finds on my network and gives a related name of the associated device when it can.

**Screenshots**
![xscanner](https://github.com/user-attachments/assets/80073739-6d61-4bd2-8c93-8bbc31f0ca73)
![xscanner](https://github.com/user-attachments/assets/f0aef161-50e1-4da2-ae8f-28776509b391)

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...] Windows 11
 - xLights version [e.g. 2019.37] xlights 2024 18. 64

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

https://www.dropbox.com/scl/fi/shs00wpzu7b6xq461wwri/xScanner_dbgrpt-25108-20241122T142605.zip?rlkey=ozjmyzs5jw5wr0cao7sbxwbc1&st=tequsbpp&dl=0

**Comment by derwin12** [comment]
I believe Keith has put in a change for this .. check in the next release.
