### ISSUE TITLE
Batch Render and pop up boxes enhancement

### ISSUE THREAD

**Issue by blargh2947** [xLightsSequencer/xLights#4993]
**Is your feature request related to a problem? Please describe.**
During a batch render, the process may encounter errors that cause a pop up box to display on the screen.  This pauses the batch render and requires user intervention to cancel/continue.

**Describe the solution you'd like**
Instead of popping up a modal dialog box, capture the output and save it to a log file.  Then at the end of the batch render open the log file and display it to the user.

**Additional context**
It can be tedious when performing a batch render to have to go and fix/address every issue such as a missing shader.
Alternatively perhaps a feature to run the check sequence and log the outputs instead of halting the batch process.

**Comment by cybercop23** [comment]
Already there.. Preferences. Other... 
![image](https://github.com/user-attachments/assets/19b0a782-7a16-4985-a315-e1bacab07e77)
 Then Tools View Log.
