### ISSUE TITLE
Windows not optimized for smaller screens

### ISSUE THREAD

**Issue by AG1967** [xLightsSequencer/xLights#4999]
THERE IS NO SEQUENCE THAT IS ASSOCIATED WITH THIS ISSUE AS IT IS ACROSS xLIGHTS

**Describe the bug**
On the Sequencer tab for the effects menu bar, there are effects to the far right that do not appear inside of the xLights window even with the program window maximized.
Another issue along the same lines is that some windows (the Preferences window in this example) are larger than the screen will show. For this one, the bottom of the window, where the buttons are on the bottom to submit your changes, are not visible and there is no way to maximize the window. Any changes made cannot be saved.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to File > Preferences
2. You cannot maximize this window
3. Smaller laptop screens do not allow the full visibility of that window

**Expected behavior**

**Screenshots**
![Screenshot 2024-11-26 141914](https://github.com/user-attachments/assets/8634b602-7922-4f3e-84cb-405864ad2e76)

![Screenshot 2024-11-26 142026](https://github.com/user-attachments/assets/edacf658-7660-49ce-b0e6-32ffaa2acd37)

**Versions (please complete the following information):**
 - OS: 
 Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.82 GB usable)
Device ID	9E57775B-9CF2-4F9F-84B8-E0E01092671D
Product ID	00325-81328-51479-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

 - xLights version 2024.19

**Additional context**

**Attachments**

**Comment by derwin12** [comment]
This is known issue and a duplicate. Thanks for noting it but I will tag as a duplicate and close this.
https://github.com/xLightsSequencer/xLights/issues/4592
