### ISSUE TITLE
Xschedual Dosent Play Sequnces 

### ISSUE THREAD

**Issue by Sam3287** [xLightsSequencer/xLights#5028]
When Playing A Song in Xschedual The Vitual Matrix Shows A Bunch Of Little Lights And No Audio Plays It Also Displays On The LIghts Out SIde 

https://github.com/user-attachments/assets/e1b39c0e-de62-4131-a452-fb11f9a43981

**Comment by derwin12** [comment]
Use the xlightszoom.com room for things like this...

**Comment by Sam3287** [comment]
isnt this page for issues? why did you close it?
