### ISSUE TITLE
Bulk Edit Frame Buffer

### ISSUE THREAD

**Issue by Fonzi03** [xLightsSequencer/xLights#5030]
It would be useful to be able to bulk edit the frame buffer:

*edit: of course after posting this I find a slight work around, you can select an effect that has the desired setting you want after selecting all the other effects. The choose apply to selected effects. Just different from other bulk edits but it does at least work. 

![image](https://github.com/user-attachments/assets/70e3a16d-8926-45e1-8909-7b64032850ac)

**Comment by keithsw1111** [comment]
You already can.
