### ISSUE TITLE
Auto Map Only Specific Props

### ISSUE THREAD

**Issue by kevinsaucier** [xLightsSequencer/xLights#5031]
I've clicked and clicked so I don't think this exists currently but I may be missing something.

It would be nice to have a way to only automatically map selected props in the Import window instead of everything.  For instance, this year, I noticed my static Xmas light display is missing a few effects that existed last year.  No idea why they disappeared as they are named the same and I'm nearly certain they existed when I first converted the sequence over.....but that's a different issue (if it happens again).  

Anyway, my static display has a bunch of effects mapped to the submodels of each model.  It's time consuming to manually remap each of these and would be nice if I could select a handful of items on the right side and right click (or something) to automatically map just those over to the left.  I've already made changes to the existing sequence so I don't want to just Auto Map everything as I'd have to fix it all.

I could have sword I just multi-selected on the right side but I just tried again and it's not working so I'm guessing I dreamed that.  Makes perfect sense that you couldn't multi-select in that box.  Maybe clicking Auto Map could bring up a selection box (similar to the one we use for copying submodels from one model to multiple others.  Check all the boxes by default and give right click options like we have in the Batch Render dialog (select/unselect all/highlighted).  That would only add one more click when using AutoMap as it works now but would give a lot more flexibility when needed.

Thanks!

**Comment by kevinsaucier** [comment]
Doh!  See, that's what comes from now performing timely updates.  🤦🏼‍♂️. Thanks team!

**Comment by kevinsaucier** [comment]
OK, follow up......this doesn't seem to be working as expected, at least on Mac.


If I open the Import dialog and scroll down on the right and multi-select a few props, right click and AutoMap, good to go.  

![image](https://github.com/user-attachments/assets/cc4d9eb4-2db1-4c91-9492-fb35ef13e36b)


If I select something a few groups on the left side and Auto Map, good to go.

![image](https://github.com/user-attachments/assets/fb69e95e-a68e-4906-990e-e9fa45414ad8)


If, however, I've selected anything at all on the left OR right, I can then only AutoMap if selections on the left AND right match.

Auto Map from the selections on the left doesn't work here:

![image](https://github.com/user-attachments/assets/9d4292b8-5069-4557-85e4-756ba56c3804)


And Auto Map from the selections on the right doesn't work here:

![image](https://github.com/user-attachments/assets/4f51fadc-9086-4ac5-b008-e0f96681dc11)


But here works from either side:

![image](https://github.com/user-attachments/assets/c428e706-d46f-46ed-ba4b-c614466e3a69)



This kind of defeats the purpose as I have to select all the matching stuff or I have to make sure to get everything selected the first time since, once you have a selection in one of the boxes, it doesn't seem that you can 'clear' the selection from one of the boxes.


Side note.....WTH happened here?  The buttons are now smaller and harder to click correctly.   I'd rather have a slightly taller footer bar than have buttons that touch each other.  Also, Save and Load feel like they are out of order (maybe that's just me, but seems like Load should come before Save 🤷‍♂️) Just sayin......  😁

![image](https://github.com/user-attachments/assets/fdcf6856-6b8e-4412-bcc9-c1017a3cc309)

**Comment by cybercop23** [comment]
Use Aliases to map non-matching items, that's how auto map works now. You can't map tree to cane... unless tree has an alias of cane. You are trying to do exact to exact, but that won't work. What if you have a model/submodels, how will they map? You still need to individually select them - so use aliases
Buttons are the buttons...

**Comment by kevinsaucier** [comment]
Perhaps we're misunderstanding each other.  I have aliases but I'm not trying to map non-matching, I'm trying to match matching without having to specifically select each individual one on both sides.

For instance, I have a Merry Christmas sign with each letter submodeled.  If I select all the submodels on the right and right click AutoMap......happy day.

If, however, I have selected something else on the left first (as would happen while working within the import dialog), then it does nothing:

![image](https://github.com/user-attachments/assets/1b90cf72-289b-4678-aeeb-c9ce3c3b27e8)


If I simply select the Merry Christmas on the left, then Auto Map from the right again, it works:

![image](https://github.com/user-attachments/assets/b7bd3248-5c63-481c-83a3-9e033c4da980)


Same with Ornaments.  If I highlight Ornament Garage L1, then highlight the submodels from that model on the right, it maps them to the left.  If I highlight Ornament Garage L2 on the left, then highlight the submodels for both L2 and R1 (looks like I caught an L1 in there as well) and AutoMap from the right, it only AutoMaps L2.  

![image](https://github.com/user-attachments/assets/5b266b16-cf8e-4096-a6ec-e0a155335d1c)


It seems that AutoMap is taking into account the name of the selected prop on the left when mapping selected items on the right.  This behavior seems broken but, if it's not, doesn't it completely defeat the purpose of Auto Map (and how Auto Map has always worked), which is to be able to automatically map any props with matching names (and now matching aliases) without having to look for and select them individually.   Having to select matching props on both sides before you can automap just makes things more difficult.  What am I missing here?  

As for the buttons, not trying to be a jerk but did someone make a conscious decision to layout the buttons with no space in between?  They fit just fine in a single line in 2024.17 so not sure what the benefit of the new layout is.

**Comment by cybercop23** [comment]
Can't map MC to Flake 13. Are you saying once you click on something on the left you can't unclick/uncheck since you really can't map Flake to MC?

**Comment by kevinsaucier** [comment]
Correct, once something is clicked on the left (or right), there is no way to unclick/unselect.  It's always selected, just grayed out.

And my expectation of the AutoMap feature would be to select however many models you want to on the right, then right click / AutoMap from the right and have them map to the left with no regard to what is selected on the left.  I guess I'm not understanding why the right cares about what's selected on the left.  Shouldn't it just be named based matching using whatever is selected on the right?  Loop that list and, if it exists somewhere on the left (or in a left alias), map it.  If it doesn't exist, don't map it.
