### ISSUE TITLE
Issue with OpenGL Support on Hyper-V VM for xLights

### ISSUE THREAD

**Issue by DsEIA863** [xLightsSequencer/xLights#5032]
I am experiencing an issue with running xLights on a Hyper-V virtual machine. My setup is as follows:

Host Server: Dell PowerEdge R630 running Windows Server 2019

VM Configuration: Hyper-V virtual machine with Windows 10 Pro

Issue: xLights software reports that OpenGL 1.x/2.x are no longer supported and prompts to update video drivers.

The software will open up fine it's only when I try navigating to the layout or sequence tab.

Despite having the latest drivers installed on my host server, the VM does not seem to meet the OpenGL requirements. I have attempted to configure the VM to use a virtual GPU, but Hyper-V does not provide an option for adding a virtual graphics card..

Any guidance or solutions you can provide to resolve this issue would be greatly appreciated.

**Comment by DsEIA863** [comment]
![Xlights OpenGL crash on layout_sequence](https://github.com/user-attachments/assets/805473c3-8fa6-4646-be76-43df879d3f5c)

**Comment by DsEIA863** [comment]
[xLights_dbgrpt-12560-20241206T134653.zip](https://github.com/user-attachments/files/18042734/xLights_dbgrpt-12560-20241206T134653.zip)

**Comment by dkulp** [comment]
OpenGL 3+ is required.    If the Hyper-V thing cannot support that, then xLights will not be able to run on there.

**Comment by DsEIA863** [comment]
Thanks, just ordered the nvidia tesla k80 gpu accelerator for the server to address this issue.
