### ISSUE TITLE
Not much of a bug other than a possible typo. My OCD.

### ISSUE THREAD

**Issue by BigDPS** [xLightsSequencer/xLights#5033]
Under the Shader effect, I am assuming there might be a typo in the cloud depth.

It says CloudWith and I think it should be CloudWidth ?

Other than that, nothing to say except this program rocks. I come from Aurora sequencer and am torqued I can't bring any of my sequences in xLights. All because of a part that was licensed to Aurora Borealis. I wish I  had learned Nutcracker when it was around at the same time of Aurora. 

![image](https://github.com/user-attachments/assets/128acc1f-953a-4392-933d-4aea932807a5)

**Comment by BigDPS** [comment]
Never mind. I see it depends on who might have created the Shader. 

Still think this program rocks!!!

**Comment by derwin12** [comment]
Yep .. I was going to say that is set by the shader program itself. You can edit that code if you wish.

**Comment by BigDPS** [comment]
Well I have been building and repairing PC's since 1979 but never was
interested in coding. I know BASIC very well but I am ok to use programs as
done by others. lol

Dany

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
