### ISSUE TITLE
xSchedule music sequences not playing

### ISSUE THREAD

**Issue by Dubbs2022** [xLightsSequencer/xLights#5050]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
[Imerial March 2.zip](https://github.com/user-attachments/files/18071353/Imerial.March.2.zip)
teps to reproduce the behavior:

1. unzip the attached file
2. Open xSchedule
3. CLick "Add"
4. Add FSEQ
5. Open the sequence "Imperial MarchXmas.fseq"
6. On the right side pane rename the playlist "Christmas_Musical"
7. CLick "okay"
8. You can set a schedule, or even just click on the sequence and "play selected" and I get no light output. All my lights just go to off. The timer in the bottom right corner is running as if xSchedule is playing the sequence. I just do not get any light output.

**Expected behavior**
Lights to output all sequences to play. As stated previous, I used this exact sequence along with a handful of others for the past 3 years with no issue.

**Versions (please complete the following information):**
 - OS: Windows 11 (10.0.22631)
 - xLights version 2024.15 64bit

**Additional context**
To be clear, xSchdule works for all my static display sequences. 

**Attachments**
[Imerial March 2.zip](https://github.com/user-attachments/files/18071348/Imerial.March.2.zip)

- zip file of a sequence and audio track
- 
If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
Perhaps go to xlightszoom.com and see if there is a config issue.

**Comment by derwin12** [comment]
This was not a valid package of the logs/sequence .. but the video has no video - could that be the issue?

**Comment by Dubbs2022** [comment]
I'll go to xlightszoom call tomorrow. Not sure what you mean about video, I don't have a video file. 

It's just a sequence with an audio track. When  I play through xlights it works just fine, but when I open in xSchedule it doesn't play at all. Same is true for all sequences with audio tracks. Meaning, any sequence with an audio track doesn't work in xSchedule. All other sequences do.

**Comment by derwin12** [comment]
Usually means you haven't got an audio device selected. We can help you
tomorrow the then

**Comment by Dubbs2022** [comment]
I'll jump into zoom in just a minute

**Comment by Dubbs2022** [comment]
They were able to help! I'm a dummy, turns out I had a "0%" brightness on my xSchedule.
