### ISSUE TITLE
Unable to launch xlights 2024.17 after updating graphics drivers

### ISSUE THREAD

**Issue by Titanhunter99** [xLightsSequencer/xLights#5054]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Cannot launch xlights. I received notice from xlights to update my graphics drivers, xlights crashed and then generated reports. After updating graphics drivers xlights will no longer run, neither will xschedule or scanner. Splash screen appears momentarily then nothing.
[xLights_dbgrpt-14932-20241208T232638.zip](https://github.com/user-attachments/files/18104239/xLights_dbgrpt-14932-20241208T232638.zip)
[xLights_dbgrpt-19684-20241208T232707.zip](https://github.com/user-attachments/files/18104240/xLights_dbgrpt-19684-20241208T232707.zip)

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights versions [2024.17 ; 19, 16,15 and 14] Tried reverting to previous, no change.

**Additional context**
Crash reports attached

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment]
This is a known thing .. go to xlights.org and download and get the c++ redistributable..

**Comment by Titanhunter99** [comment]
smarty pants! No seriously, thanks so much! I tried everything under the sun, even re-installing windows, graphics rollbacks, everything I could think of.

This issue is resolved for me. Thanks and Happy Holidays!
