### ISSUE TITLE
Find Show Folders Accessed in Past X Days

### ISSUE THREAD

**Issue by MrPaulAR** [xLightsSequencer/xLights#5065]
**Is your feature request related to a problem? Please describe.**
Nearly daily we see folks come in that cannot find their show folder.  The simplest fix is to find it from the "Recent Show Folder" dropdown but it seems that it's usually not there.  Maybe this is a bug in of itself due to an imposed limit on the length of this list and/or how temp show folders are handled.

**Describe the solution you'd like**
Asking for a tool that will search through the xLights log files (`xLights_l4cpp.log` or `xLights_l4cpp.log.YYYY-MM-DD`) that are in %appdata% on windows (not sure about linux/mac) for show folders accessed in the last X days.  A possible option would be something like this.

* Tools > Find Possible Show Folders
* New window prompts for days to search and/or initial date picker from calendar.  Maybe default to previous 30 days
* Clicking find will result in a new window that shows the following columns
  * Path to show folder
  * Number of times opened
  * Button to open in explorer
  * Button to have xLights change temporally
  * Button to have xLights change permanently

**Describe alternatives you've considered**
Generally we help users hunt and peck through their file explorer until we find it.  Sometimes search for xlighs_networks.  Others manually look through the various xLights log files.

**Comment by cybercop23** [comment]
Completed by Scott. Will be in next version.
