### ISSUE TITLE
DMX Effect Custom Vlaue Curves deleted on Bulk Render

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#5082]
I was able to reproduce a bug when bulk editing an imported DMX effect.  The bulk edit works fine when remapping channels.  However, when bulk editing an Offset (to turn the moving head effects) 42, 84, or any value; xLights erases the custom value curve data. It does leave alone the pre-set value curves.  

I've included a link to a video showing the bug.  Have a look and see if you can reproduce it?

Thank you for looking,
Clyde L
https://www.dropbox.com/s/728oeu9qjc4lf75/Bulkedit%20Offset.mp4?dl=0

**Comment by derwin12** [comment]
I assume you both are reporting the same bug/enhancement
https://github.com/xLightsSequencer/xLights/issues/5081

**Comment by Clyde-L** [comment]
yep we both are.  Didn't notice it.
