### ISSUE TITLE
Importing in a superstar file, distortion on twinkling lights

### ISSUE THREAD

**Issue by smeighan** [xLightsSequencer/xLights#591]
Using the Kiss me babe, It's christmas time there is a distortion of thw twinkling lights at 2:44 minutes into the song. The effects are colorwash with white. The issue seems to be the settings in the subbuffer panel.

**Comment by AzGilrock** [comment]
I can't find this SuperStar file anywhere.  I'd need the file or the section with the problem.  Sorry I didn't look at it sooner.

**Comment by cybercop23** [comment]
Should this remain open?
