### ISSUE TITLE
ENH: UI efficiency improvements

### ISSUE THREAD

**Issue by stevegiron** [xLightsSequencer/xLights#798]
Today there are no application indicators of non-standard effect settings. Having these would save us time. Giving us the option to make them non-sticky would be welcome as well.

1. Add an indicator that there's a transition applied
2. Add an indicator that the buffer isn't 100%
3. Add an indicator when roto-zoom is active.

Where and how, I don't know. Maybe another dockable status panel with other informational items.

**Comment by keithsw1111** [comment]
They aren’t sticky as at v56

**Comment by AzGilrock** [comment]
Yeah kinda like a video editor shows you when you have transitions applied.  I didn't get the part about "non-sticky".  Are you talking about the Layer Settings panel?

**Comment by stevegiron** [comment]
I was unaware that with .56 when you set a transition like "fade out" it would not be applied to future placed effects. That's what I meant by sticky.  This is only true however if you choose a different effect as the next effect placed. I guess the non-sticky part of the request can be ignored. Just having an indicator that the buffer was rotated or a transition applied would be cool.

**Comment by keithsw1111** [comment]
Steve did you have a thought on how you wanted this indicator to work? What would it look like. I am really concerned it would just clutter up the sequencer screen. We could add it to the effects export but how many people actually look at that.

**Comment by cybercop23** [comment]
Should this remain open? Any futher interest?

**Comment by cybercop23** [comment]
Right.. not the over/unser buffer or rotozoom (sometimes that gets us in the zoom room). The over/uder buffer would be nice..but not enought to keep this open :)
