### ISSUE TITLE
Logarithmic Up/Down don't seem to be very logarithmic

### ISSUE THREAD

**Issue by MikeSoukup** [xLightsSequencer/xLights#905]
No matter how I adjust the Rate & Vertical Offset sliders, I can't get a curve that looks logarithmic. The 'Logarithmic Down' curve appears to be exponential - the slope increases from left to right instead of decreasing.  'Logarithmic Up' has a decreasing slope, but it appears to be too far into the curve to be useful and looks more linear than logarithmic.  I would expect each to have a steep slope at the beginning and flatten out towards the end.

**Comment by kylegrymonprez** [comment]
Going through old issues to see what I can see - is this still an issue? I do not see that "Logarithmic Down' is increasing instead of decreasing.
![Screenshot 2024-08-23 at 2 37 44 PM](https://github.com/user-attachments/assets/e37ecc03-1c0e-49af-a318-5a12b2b1ad73)

Perhaps this was handled and not marked done.

**Comment by MikeSoukup** [comment]
The screenshot you pasted is not logarithmic, it's slightly exponential; the slope is slightly increasing from left to right.  A logarithmic curve should start out close to a vertical line on the left and get close to a horizontal line on the right, the opposite of an exponential curve which starts out near horizontal and goes to near vertical.

These are logarithmic curves:
![image](https://github.com/user-attachments/assets/98a6d0ad-bfb7-4052-acf5-305f564b0492)

The Logarithmic Down curve in xLights is not logarithmic.  The Logarithmic Up curve in xLights is barely logarithmic and is near linear.
