### ISSUE TITLE
Form Field under "Faces" in Custom Model - Nodes Field extending past color field 

### ISSUE THREAD

**Issue by Duramadmax** [xLightsSequencer/xLights#960]
I am working on my singing trees and setting up my nodes for each phoneme. I noticed that if you have more nodes than field width, the characters will "spill" over to the color field instead of being behind the form field. Also since i am using excel as a "standard of operations", when you click teh node form field and highlight it, and press delete I anticipated the whole field to be deleted but instead in puts cursor at the first character of field and deletes one character. Thanks

**Comment by cybercop23** [comment]
https://github.com/xLightsSequencer/xLights/actions/runs/7725661949
