### ISSUE TITLE
uDMX Support

### ISSUE THREAD

**Issue by gothambeat** [xLightsSequencer/xLights#979]
Can the XL team add support for uDMX.  It does not appear like typical ENNTEC Open or ENNTEC Pro ports.

**Comment by AzGilrock** [comment]
So they don't show up as COM ports?  So then how does a custom program like ours communicate with a uDMX device?  If it requires us linking to a custom DLL provided by each manufacturer then I don't see it happening.

**Comment by gothambeat** [comment]
It comes in as a device in it's own folder in device manager.  Directory:  Libusbk USB Device  Entry: uDMX 
 Locaiton: Port_#0009.Hub_#0003

When I use a program like Freestyler there are options for things like ENNTEC Open, ENNTEC PRo, uDMX etc.  When I use XL, you have options for DMX, Pixelnet, Renard,  D-Light, LOR, OpenDMX.  

We would just need the protocol for uDMX.  I'm not sure what the technical differences are but I do know that uDMX does work through ARTNET.  I also know that it is a very popular cheap chinese way to get DMX out of your PC.

**Comment by keithsw1111** [comment]
Do you have a device you can send us and we can see if we can get it to work. There is a library which is cross platform that may help us talk to these devices ... http://www.signal11.us/oss/hidapi/

**Comment by keithsw1111** [comment]
This is sample (platform specific code) for udmx https://github.com/mirdej/udmx/blob/master/puredata/uDMX.c

**Comment by davidwill1** [comment]
Sorry not sure what your talking about, not very computer smart

**Comment by keithsw1111** [comment]
Do you have a device you can send us and we can see if we can get it to work.

**Comment by davidwill1** [comment]
Sorry this is the only way I can send the logs. Thanks

**Comment by AzGilrock** [comment]
At least you only wasted $20.  It would be cheaper to just go buy a normal controller than to pay us to add this.

**Comment by keithsw1111** [comment]
In a whole year precisely 0 other people asked for this ... let me drop everything and implement it.

**Comment by TRSATOC** [comment]
I have a uDMX dongle too, and it will be nice to implement this ;)

**Comment by AzGilrock** [comment]
> I have a uDMX dongle too, and it will be nice to implement this ;)

Keith said send him one and he will get it working.  Otherwise any reply is a waste of time.

**Comment by raptordemon** [comment]
i have a spare, where do i mail it?

**Comment by keithsw1111** [comment]
Ping me on facebook or private message me on the nutcraket forum.

**Comment by zakkwillow** [comment]
Just wanted to drop a comment here. I was trying to figure this out today and was able to get it working using the KM loopback adapter and an artnet to udmx translator. (Found it on the same site as the udmx drivers) 

Just set up xLights to send artnet to the loopback IP address. Seems to work well with very little latency.

Hope this helps!
